### ISSUE TITLE
wildignore option

### ISSUE THREAD

**Issue by iverson4664** [Yggdroot/LeaderF#10]
nice plugin, faster than ctrlp. But, there is an issue like ctrlp.
when I'm working in a large project, thousands of dir and subdirs may add into leaderf. For my expect, some assigned directorys can add, donot use Lf_WildIgnore option, how can I fix it, man?

**Comment by Yggdroot** [comment]
Now you can use `LeaderfFile dir1 dir2 dir3` or `Leaderf file dir1 dir2 dir3`.
