### ISSUE TITLE
Is the ./build directory implicitly ignored?

### ISSUE THREAD

**Issue by Leandros** [Yggdroot/LeaderF#100]
I'm having a `/build` directory, where my build files are in, it's not getting indexed by LeaderF. And it's not in my wildignore. Any idea?

**Comment by Yggdroot** [comment]
Is it in .gitignore or .hgignore or something else?

**Comment by Leandros** [comment]
🤦‍♂️ 

Ok, sorry about that. I didn't check if there is a .gitignore, because I'm not using Git. Turns out, there is one. Thanks a lot.
