### ISSUE TITLE
neovim开启winbar之后 leaderf跳转不准确

### ISSUE THREAD

**Issue by yao-weijie** [Yggdroot/LeaderF#1000]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
  >NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550
Features: +acl +iconv +tui
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
Run :checkhealth for more info

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.11.2
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

涉及的两个插件
- `Leaderf` 默认配置
- `lspsaga`
  ```lua
  require('lspsaga').setup({
     symbols_in_winbar = { enable = false} -- 控制winbar的开关
  })
  ```

### Describe your question, feature request, or bug.

大概从neovim 0.8 开始, neovim新增了winbar功能, 最近在使用leaderf的过程中, 发现开启了winbar之后会有一点小问题

不开启winbar的时候 leaderf的跳转可以直接跳转到目标位置上
![Peek 2023-04-02 14-04](https://user-images.githubusercontent.com/36393630/229334829-edc2039b-739c-4da1-8abf-26ed503af07d.gif)

当开启了winbar的时候
leaderf的跳转总是先跳转到目标行的上一行, 然后会自动往下一行才会到目标位置上
在更换了其他插件的winbar功能以后, 这个现象仍然存在
![Peek 2023-04-02 14-05](https://user-images.githubusercontent.com/36393630/229334904-dd824675-ab2b-462d-acad-42a9c9af9df1.gif)

**Comment by Yggdroot** [comment]
这是nvim的bug，比如执行
```vim
:5 | setlocal cursorline! | redraw | sleep 150m | setlocal cursorline!
```
就会复现这个问题。
