### ISSUE TITLE
打开airline或者lightline后, 在文件列表中使用t或者ctrl+t后报错,同时 tabbar出错, 后续继续使用正常

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#1001]
LeaderF commitid  45911fd6b4369j76ae9e83eb0a1968d3b8e72276b

- vim or neovim?  
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Apr 12 2023 17:29:13)
Included patches: 1-1443
Compiled by hongjiew@hongjiew-Host-Machine
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     -perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          -ruby              +wildignore
+cursorbind        -lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L/usr/local/lib -Wl,--as-needed -o vim -lm -ltinfo -lrt -ldl -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/ -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm

```
- Output of `:echo has("python")`:  0 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim):  nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim):  nothing
- Output of `:py print(sys.version)`:  E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
   rg --no-messages --files --color never  -g '!__pycache__' -g '!env' -g '!build' -g '!tools' -g '!submodules' -g '!linux-x86_64' -g '!s4proj' -g '!out' -g '!output' -g '!rootfs' -g '!*.sw?' -g '!~$*' -g '!*.bak' -g '!*.exe' -g '!*.o' -g '!*.ko' -g '!*.so' -g '!*.py[cod]' -g '!*.ico' -g
'!*.bmp' -g '!*.BMP' -g '!*.png' -g '!*.PNG' -g '!*.JPG' -g '!*.jpg' -g '!*.ini' -g '!*.xml' -g '!*.dtso' -g '!*.gz' -g '!*.xz' -g '!*.bz2' -g '!*.tar' -g '!*.zip' -g '!*.rar' -g '!*.7z'
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
function! Init_leaderf()
    "Specify the files and directories you want to exclude while indexing.
    let g:Lf_WildIgnore = {
    \ 'dir': [
        \ '.svn','.git','__pycache__','env','build','tools','submodules','linux-x86_64','s4proj',
        \ 'out','output','.build',
        \ 'rootfs'
        \ ],
    \ 'file': [
        \ '*.sw?','~$*','*.bak','*.exe','*.o','*.ko','*.so','*.py[cod]',
        \ '*.ico','*.bmp','*.BMP','*.png','*.PNG','*.JPG','*.jpg','*.ini','*.xml','*.dtso',
        \ '*.gz','*.xz','*.bz2','*.tar','*.zip','*.rar','*.7z',
        \ ]
    \ }
    let g:Lf_MruFileExclude = [
        \ '*.so', '*.exe', '*.py[co]', '*.sw?', '~$*', '*.bak', '*.tmp', '*.dll',
        \ '*.gz','*.xz','*.bz2','*.tar','*.zip','*.rar','*.7z',
    \ ]

    let g:Lf_StlColorscheme = 'gruvbox_material'

    "let g:Lf_RootMarkers = ['.root','.git','.svn','.project']
    let g:Lf_RootMarkers = ['.root']
    "let g:Lf_StlSeparator = { 'left':' ', 'right':' ', }
    let g:Lf_WorkingDirectoryMode = 'Ac'
    if exists('g:hjvim_config.path.plugdir')
        let l:tempdir = g:hjvim_config.path.plugdir
    else
        let l:tempdir = $VIMFILES
    endif

    if hjenv#IsWindows()
        let g:Lf_CacheDirectory = expand(l:tempdir . '\cache')
    else
        let g:Lf_CacheDirectory = expand(l:tempdir . '/cache')
    endif

    " 不使用版本管理软件获取文件列表
    " 如果功能设置为1, 那么文件列表会根据git获得, 比如说某个文件已经删除但是没有提交到git, 这个文件仍会从文件列表中看到
    let g:Lf_UseVersionControlTool = 0

    " 默认禁用 function/buftag 的全部自动预览功能，可以手动用 p 预览
    " 在后面可以配置想用的预览设置
    let g:Lf_PreviewResult = {
            \ 'File': 0,
            \ 'Buffer': 0,
            \ 'Mru': 0,
            \ 'Tag': 0,
            \ 'BufTag': 0,
            \ 'Function': 0,
            \ 'Line': 0,
            \ 'Colorscheme': 0,
            \ 'Rg': 0,
            \ 'Gtags': 0
            \}

    if hjenv#IsNvim()
        let l:winpos = 'right'
    else
        let l:winpos = 'popup'
    endif

    let g:Lf_WindowPosition = l:winpos
    if g:Lf_WindowPosition ==# 'bottom'
        let g:Lf_WindowHeight = 0.20
    elseif g:Lf_WindowPosition ==# 'popup'
        let g:Lf_PopupPosition = [2 , 0] " popup 窗口位置屏幕中间偏上
        " popup窗口显示在屏幕上右方,但是在gui模式下获得的&columns值偏小
        "let g:Lf_PopupPosition = [2 , &columns - float2nr(&columns*0.5)]
        "let g:Lf_PopupHeight = float2nr(&lines*0.3) " 窗口高度 0.5
        "let g:Lf_PopupWidth = float2nr(&columns*0.5)
        let g:Lf_PreviewInPopup = 1 " 是否在popup中preview
        let g:Lf_PopupPreviewPosition = 'bottom'
        " 打开相应预览功能

    elseif g:Lf_WindowPosition ==# 'right'
        let g:Lf_PreviewHorizontalPosition = 'left'
    endif

    if g:Lf_PreviewInPopup == 1 " 如果在popup中进行preview
        let g:Lf_PopupColorscheme = 'gruvbox_default' "设置popup window的皮肤
        let g:Lf_PreviewResult['Rg'] = 0 "打开搜索相应的预览,关闭,因为搜索到特别长的行会死掉
        let g:Lf_PreviewResult['BufTag'] = 1 "打开当前文件tag的预览
        let g:Lf_PreviewResult['Function'] = 1 "打开当前函数预览
    endif

    let g:Lf_CtagsFuncOpts = {
    \ 'c': '--c-kinds=fp',
    \ 'c++': '--c++-kinds=fp',
    \ 'python': '--python-kinds=fp',
    \ 'rust': '--rust-kinds=f',
    \}
    let g:Lf_ShowRelativePath = 1

    " 使用 ESC 键可以直接退出 leaderf 的 normal 模式
    let g:Lf_NormalMap = {
    \ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
    \ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<cr>']],
    \ "Mru": [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<cr>']],
    \ "Tag": [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<cr>']],
    \ "BufTag": [["<ESC>", ':exec g:Lf_py "bufTagExplManager.quit()"<cr>']],
    \ "Function": [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<cr>']],
    \ }

    " 替换leaderf 插件中默认的键
    let g:Lf_CommandMap = {
    \   '<C-R>': ['<C-E>'],
    \   '<C-F>': ['<C-D>'],
    \   '<C-Up>': ['<C-K>'],
    \   '<C-Down>': ['<C-J>'],
    \ }

    "打开对nerd font显示图标的支持,需要相应字体支持
    if hjenv#IsWindows()
        let g:Lf_ShowDevIcons = 1
    else
        let g:Lf_ShowDevIcons = 1
    endif

    " the following setting may make problems about display
    "let g:Lf_Gtagsconf = '/usr/local/share/gtags/gtags.conf'
    "let g:Lf_Gtagslabel = 'native-pygments'
    "let g:Lf_GtagsAutoGenerate = 1
      " this line is used to change the default hotkeys

endfunction

### Describe your question, feature request, or bug.
打开airline或者lightline后, 在文件列表中使用t或者ctrl+t后报错,同时 tabbar出错, 后续继续使用正常

### Steps to reproduce
1. 启动vim
2. 使用 :Leaderf file 打开一个popup的文件列表
3. (ctrl+t) or (tab后按t键) 出错, 出错时会有如下的打印
```
LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 870, in _acceptSelection^@    lfCmd("tabe %s" % escSpecial(file))^@vim.error: Vim(if):E745: Using a List as a Number
```
4. 之后使用正常, 但是tabbar显示有问题

1.启动vim
2.使用 :Leaderf file 打开一个popup的文件列表
3.tab后v键以及回车键打开文件都不会出错

关闭airline或者lightline后正常

**Comment by irreallich** [comment]
通过rollback airline的版本后解决问题, close.

**Comment by Yggdroot** [comment]
复现不了，能提供最小可复现的vimrc吗？
