### ISSUE TITLE
有没有popup打开和关闭事件？

### ISSUE THREAD

**Issue by cage1618** [Yggdroot/LeaderF#1004]
如题，有没有popup窗口打开和关闭的事件来实现修改配置？

具体需求是：
因为设置了 set mouse=a，所以鼠标双击选中复制失效了，所以想在 popup 打开时把鼠标禁用掉，在popup关闭时在启用。
不知道是否能实现

**Comment by Yggdroot** [comment]
没有。
想复制的话，如果是在终端上，可以按着shift再双击。有的终端好像是按着alt。

**Comment by cage1618** [comment]
好的，谢谢
