### ISSUE TITLE
请问gtags reference函数A时，可以显示是哪个函数调用了函数A吗？

### ISSUE THREAD

**Issue by niexin-dev** [Yggdroot/LeaderF#1007]
![image](https://user-images.githubusercontent.com/8086937/236663464-48e98255-b215-478f-8bbc-06386bf174df.png)
像上面搜索CopyUbootStampToApp，只能显示my_main.c和gk_sample_quckstart.c里有这个函数，但无法显示这两个文件里哪个函数调用了CopyUbootStampToApp
请问有什么办法可以实现显示函数名？

**Comment by Yggdroot** [comment]
gtags本身没有这个功能，结合cscope可以。
