### ISSUE TITLE
win11,vim9,Leaderf使用rg报错,rg版本13.0.0

### ISSUE THREAD

**Issue by longcp** [Yggdroot/LeaderF#1009]
yes

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 9.0
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python310.dll
- Output of `:py print(sys.version)`: could not load library python27.dll...
- Output of `:py3 print(sys.version)`: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)
- Output of `:echo g:Lf_Debug_Cmd`: rg --files --no-ignore "".""
- Output of `:echo g:Lf_FilesFromCache`: 0
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShowDevIcons = 0
let g:Lf_PreviewResult = {'Function':0, 'Colorscheme':1}
let g:Lf_NormalMap = {
    \ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
    \ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>']],
    \ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>']],
    \ "Tag":    [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<CR>']],
    \ "Function":    [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<CR>']],
    \ "Colorscheme":    [["<ESC>", ':exec g:Lf_py "colorschemeExplManager.quit()"<CR>']],
    \ }
""" <---

noremap <leader>fF :LeaderfFunction<cr>
noremap <leader>ff :LeaderfFunction!<cr>
noremap <leader>fl :LeaderfLine<cr>
noremap <leader>fT :LeaderfBufTag<cr>
noremap <leader>ft :LeaderfBufTag!<cr>
noremap <leader>fm :LeaderfMru<cr>
noremap <leader>fb :LeaderfBuffer<cr>

noremap <leader>rg :Leaderf! rg -s
noremap <leader>rgn :Leaderf! rg --no-ignore --hidden
noremap <leader>fy :Leaderf! rg -s "<C-R>""<cr>
noremap <leader>fyc :Leaderf! rg -s --current-buffer "<C-R>"" <cr>
noremap <leader>fyca :Leaderf! rg -s --current-buffer --append "<C-R>"" <cr>

noremap <leader>fwa :<C-U><C-R>=printf("Leaderf! rg -s %s ", expand("<cword>"))<CR><CR>
noremap <leader>fw :<C-U><C-R>=printf("Leaderf! rg --type-not txt -s %s ", expand("<cword>"))<CR><CR>
noremap <leader>fww :<C-U><C-R>=printf("Leaderf! rg --type-not txt -w -s %s ", expand("<cword>"))<CR><CR>
noremap <leader>fwh :<C-U><C-R>=printf("Leaderf! rg -s --hidden %s ", expand("<cword>"))<CR><CR>
noremap <leader>fwn :<C-U><C-R>=printf("Leaderf! rg -s --no-ignore --hidden %s ", expand("<cword>"))<CR><CR>
nmap <unique> <leader>fr <Plug>LeaderfRgPrompt
nmap <unique> <leader>fra <Plug>LeaderfRgCwordLiteralNoBoundary
nmap <unique> <leader>frb <Plug>LeaderfRgCwordLiteralBoundary
nmap <unique> <leader>frc <Plug>LeaderfRgCwordRegexNoBoundary
nmap <unique> <leader>frd <Plug>LeaderfRgCwordRegexBoundary

vmap <unique> <leader>fra <Plug>LeaderfRgVisualLiteralNoBoundary
vmap <unique> <leader>frb <Plug>LeaderfRgVisualLiteralBoundary
vmap <unique> <leader>frc <Plug>LeaderfRgVisualRegexNoBoundary
vmap <unique> <leader>frd <Plug>LeaderfRgVisualRegexBoundary

nmap <unique> <leader>fgd <Plug>LeaderfGtagsDefinition
nmap <unique> <leader>fgr <Plug>LeaderfGtagsReference
nmap <unique> <leader>fgs <Plug>LeaderfGtagsSymbol
nmap <unique> <leader>fgg <Plug>LeaderfGtagsGrep

vmap <unique> <leader>fgd <Plug>LeaderfGtagsDefinition
vmap <unique> <leader>fgr <Plug>LeaderfGtagsReference
vmap <unique> <leader>fgs <Plug>LeaderfGtagsSymbol
vmap <unique> <leader>fgg <Plug>LeaderfGtagsGrep

let g:Lf_UseCache = 0 " 不从缓存读数据
let g:Lf_WindowHeight = 0.25
let g:Lf_WindowPosition = 'popup' " 'top'/'bottom'/'left'/'right'/'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PopupHeight = 0.5
let g:Lf_PopupPreviewPosition = 'bottom' " 'top'/'bottom'/'left'/'right'/'popup'
let g:Lf_ExternalCommand = 'rg --files --no-ignore "%s"'    "---> not work for windows

### Describe your question, feature request, or bug.
输入LeaderfFile提示出错:
File "C:\Users\user\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\cli.py", line 696, in input^@    callback()^@  File "C:\Users\user\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 70, in deco^@    func(self, *args, **kwargs)^@  File "C:\Users\user\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2488, in _workInIdle^@    raise self._read_content_exception[1]^@  File "C:\Users\user\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2461, in _readContent^@    for line in content:^@  File "C:\Users\user\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\asyncExecutor.py", line 105, in read^@    raise Exception(lfBytes2Str(err, encoding))^@Exception: 'rg' ڲⲿҲǿеĳ^M^@ļ
Press ENTER or type command to continue

与rg相关Leaderf如Leaderf! rg --no-ignore --hidden，都会提示异常：
Exception('rg', ڲⲿҲǿеĳ^M^@ļ);

rg版本：ripgrep 13.0.0 (rev af6b6c543b)，试过12.1.1情况依旧

**Comment by Yggdroot** [comment]
更新一下code就能看到错误信息了，具体原因还需再查。

**Comment by longcp** [comment]
:echom $PATH，发现rg的$PATH有乱码，是因为我环境变量带了中文，将中文去掉rg就能正常工作了，感谢解答。
