### ISSUE TITLE
Files not opening anymore after changing working directory

### ISSUE THREAD

**Issue by Leandros** [Yggdroot/LeaderF#101]
# Steps to reproduce

1. Open Vim
2. Change working directory (for example by using NERDTree to chdir, or something like this: `nnoremap ,cd :cd %:p:h<CR>:pwd<CR>`)
3. Open LeaderF
4. Search for a file in LeaderF, and open it

# Expected Behaviour

LeaderF should open the selected file, just like normal.

# Actual Behaviour

LeaderF will try to open the file based on it's relative location to where Vim opened, resulting in an empty buffer.

# Vim Version

Using `vim` seems to work, using `nvim` doesn't. 

```
NVIM v0.2.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/config -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-53412-9ielcr/neovim-0.2.2/build/include
Compiled by brew@Sierra-2.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

Run :checkhealth for more info
```

# Notes

The issue is fixed using `set autochdir`, unfortunately, though, I can't use said setting.
It feels like this issue is a regression of https://github.com/Yggdroot/LeaderF/issues/2
Can be "fixed" by changing the LeaderF binding from

```
nnoremap <Leader>o :LeaderfFile<CR>
```
to
```
nnoremap <Leader>o :LeaderfFile $PWD<CR>
```

**Comment by Yggdroot** [comment]
This issue is caused by a [bug](https://github.com/neovim/neovim/issues/3636) of neovim.

I'll fix it in LeaderF since so many people have complained about it.

**Comment by Leandros** [comment]
It looks like this bug is complicated. My fix seems to work fine on terminal nvim on the mac, but ceases to work on nvim-qt on Windows.
If I change the directory, both `:pwd` and `:python3 print(os.getcwd())` print the same directory, but once I open LeaderF, the working directory is reset to the old one.
