### ISSUE TITLE
Leaderf 升级后有几个问题

### ISSUE THREAD

**Issue by cage1618** [Yggdroot/LeaderF#1011]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
3.9.17 (main, Jun  6 2023, 14:42:56)
[Clang 14.0.3 (clang-1403.0.22.14.1)]

- Output of `:py3 print(sys.version)`: 
3.9.17 (main, Jun  6 2023, 14:42:56)
[Clang 14.0.3 (clang-1403.0.22.14.1)]

- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd

- Output of `:echo g:Lf_FilesFromCache`: 
E121: Undefined variable: g:Lf_FilesFromCache

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_HideHelp = 1
let g:Lf_WindowHeight = 15
let g:Lf_StlColorscheme = "gruvbox_material"
let g:Lf_PreviewResult = {'rg': 0}
let g:Lf_StlSeparator = {'left': '', 'right': ''}
let g:Lf_ShowDevIcons = 1
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PopupWidth = 0.85
let g:Lf_PopupHeight = 0.382
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_PopupPosition = [-1000, 0]
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagsconf='/usr/local/share/gtags/gtags.conf'
let g:Lf_Gtagslabel = 'native-pygments'

nmap go :Leaderf rg --recall<CR>
nmap <leader>r :Leaderf --recall<CR>
nmap <leader>g :Leaderf rg 
nmap <leader>c :LeaderfHistoryCmd<CR>
nmap <leader>s :LeaderfHistorySearch<CR>
```

### Describe your question, feature request, or bug.
更新到最新版后，有两个问题：
1.使用Leaderf file、rg 等命令时，会修改vim配色方案，而且 Leaderf file 后文件列表高度很小，只能看到2行
2.Leaderf file 的预览默认打开了，还是原来 ctrl + p 才预览比较舒服，这个要怎么关闭

### Steps to reproduce
:Leaderf file
:Leaderf rg 

### Actual behaviour
正常状态下：
<img width="840" alt="nvim 2023-06-14 09-27-33" src="https://github.com/Yggdroot/LeaderF/assets/2541448/242c3f04-c767-4bd8-9c74-7787dfab13e4">

使用 :Leaderf rg 后：
![nvim 2023-06-14 09-29-27](https://github.com/Yggdroot/LeaderF/assets/2541448/8728e34f-1f29-49b1-b274-991346d69d4e)

使用 :Leaderf file 后
![nvim 2023-06-14 09-32-22](https://github.com/Yggdroot/LeaderF/assets/2541448/5e8ea907-c108-49ba-ae28-a495603b6442)

### Expected behaviour
不要修改配色方案
可以设置手动预览
Lederf file 显示的文件行数跟 rg一致

**Comment by srbarton43** [comment]
I also would like to turn off previews by default. Is there a setting to do this? Furthermore, the newest commit breaks with dashboard-nvim...

**Comment by Yggdroot** [comment]
@cage1618 

> 1.使用Leaderf file、rg 等命令时，会修改vim配色方案，而且 Leaderf file 后文件列表高度很小，只能看到2行

新的commit应该不会改配色方案，如果会改，以前应该也会改。你的图片上好像是预览窗口的颜色。以后我会想办法自适应当前配色。
这个好像是个bug，我看一下。

> 2.Leaderf file 的预览默认打开了，还是原来 ctrl + p 才预览比较舒服，这个要怎么关闭

https://github.com/Yggdroot/LeaderF/blob/1698cbbec5baabff0488f31b5c7fa89e25707d32/doc/leaderf.txt#L415-L433

**Comment by Yggdroot** [comment]
> I also would like to turn off previews by default. Is there a setting to do this? Furthermore, the newest commit breaks with dashboard-nvim...

https://github.com/Yggdroot/LeaderF/blob/1698cbbec5baabff0488f31b5c7fa89e25707d32/doc/leaderf.txt#L415-L433

**Comment by cage1618** [comment]
> @cage1618
> 
> > 1.使用Leaderf file、rg 等命令时，会修改vim配色方案，而且 Leaderf file 后文件列表高度很小，只能看到2行
> 
> 新的commit应该不会改配色方案，如果会改，以前应该也会改。你的图片上好像是预览窗口的颜色。以后我会想办法自适应当前配色。
> 
> > 只能看到2行
> 
> 更新一下code，设置 `let g:Lf_PopupAutoAdjustHeight = 0`
> 
> > 2.Leaderf file 的预览默认打开了，还是原来 ctrl + p 才预览比较舒服，这个要怎么关闭
> 
> https://github.com/Yggdroot/LeaderF/blob/1698cbbec5baabff0488f31b5c7fa89e25707d32/doc/leaderf.txt#L415-L433

我回退到上次的commit就好了，是后面主窗口的配色改了，由原来的黑色变成了青色的

**Comment by cage1618** [comment]
> 变色的原因找到了，因为我用了[neovim/neovim#3688 (comment)](https://github.com/neovim/neovim/issues/3688#issuecomment-574544618) 里提到的方法来隐藏光标。 set termguicolors 时颜色就会变。 感觉使用nvim一般set termguicolors比较好，也就是终端使用真彩色。

😂好的，那暂时老版本先用着，没时间折腾配色，感谢大佬

**Comment by Yggdroot** [comment]
> > 变色的原因找到了，因为我用了[neovim/neovim#3688 (comment)](https://github.com/neovim/neovim/issues/3688#issuecomment-574544618) 里提到的方法来隐藏光标。 set termguicolors 时颜色就会变。 感觉使用nvim一般set termguicolors比较好，也就是终端使用真彩色。
> 
> 😂好的，那暂时老版本先用着，没时间折腾配色，感谢大佬

问题已修复，最新版本也不会有变色问题了。
