### ISSUE TITLE
Please do not change the default value of `Lf_PreviewResult`

### ISSUE THREAD

**Issue by bennyyip** [Yggdroot/LeaderF#1012]
https://github.com/Yggdroot/LeaderF/commit/27bd938a422fc6fcfc453fa88fe2ad453a012074 changes `Lf_PreviewResult`. This is an unexpected change.

**Comment by Yggdroot** [comment]
Yes, but I find most people like the instant preview， so let it on by default.
If you don't like it, you can disable it.

**Comment by bennyyip** [comment]
But the docs is not updated. It's a little bit confusing.

**Comment by jdhao** [comment]
Also the instant preview will add file to buffer list even if you do not confirm the file selection, which is counter-intuitive.

**Comment by Yggdroot** [comment]
> Also the instant preview will add file to buffer list even if you do not confirm the file selection, which is counter-intuitive.

`let g:Lf_PreviewInPopup = 1` 
If you don't like popup preview, you have to disable the auto-preview by setting g:Lf_PreviewResult.

**Comment by Yggdroot** [comment]
Now you can use `Leaderf xxx --no-auto-preview`.
