### ISSUE TITLE
g:Lf_PopupPreviewPosition = 'bottom' caused  errors in vim9.

### ISSUE THREAD

**Issue by leoatchina** [Yggdroot/LeaderF#1013]
- vim or neovim? 
    - [x] vim: only found in vim9 self compiled, in debian11
    - [ ] neovim: have tested and no bugs
- Output of `vim --version` or `nvim --version`: 
```
     VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun 12 2023 21:02:56)
     Included patches: 1-1627
```
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`: 1,  
- Output of `:echo &pythondll`(only vim, not neovim):  not  tested windows so zero
- Output of `:echo &pythonthreedll`(only vim, not neovim):  not  tested windows so zero
- Output of `:py print(sys.version)`: Error
- Output of `:py3 print(sys.version)`: 
```
3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux: debian 11
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
        let g:Lf_WindowPosition = 'popup'
        let g:Lf_PopupHeight    = 0.6
        let g:Lf_PopupWidth     = 0.8
        let g:Lf_PopupPosition  = [8, 0]
        let g:Lf_PreviewInPopup = 1
        " let g:Lf_PopupPreviewPosition = 'top'
        let g:Lf_PopupPreviewPosition = 'bottom'
```

### Describe your question, feature request, or bug.
This bug maybe related with screen resolution.

In vim9, when I do `Leaderf` commands  on a  `1200x1600` monitor(a *3:4* screen, 90degrees rotated ),  and typed 2 characters to filter results,  errors will raise in  when ` g:Lf_PopupPreviewPosition = 'bottom'`, and my screen got halted.

After I moved my terminal app to a normal notebook monitor,  this bug not happened
After  set  `g:Lf_PopupPreviewPosition ` to `top`,     `no errors`
In `windows gvim` , also no errors

```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2435, in startExplorer
    self.input()
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2720, in input
    self._search(cur_content)
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1234, in _search
    self._fuzzySearch(content, is_continue, step)
  File "/home/leo/.leovim.d/pack/add/opt/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1661, in _fuzzySearch
    lfCmd("redraw")
vim.error: Vim(redraw):E340: Internal error; if you can reproduce please report a bug


```
![image](https://github.com/Yggdroot/LeaderF/assets/4470821/602d9cfb-ff31-4f24-917d-0aeb6cc0d7ae)

### Actual behaviour
Got Error
### Expected behaviour
leaderf filter succesfully

**Comment by Yggdroot** [comment]
it seems it's vim's bug.
what if lfCmd("silent! redraw")

**Comment by leoatchina** [comment]
> 

how to run this in command line,  if `slient! redraw`, no results.  I have tested `:call lfCmd("silent! redraw")` and `:py3 lfCmd("silent! redraw")` ,  errors raised.

**Comment by Yggdroot** [comment]
I mean modify the source code:
https://github.com/Yggdroot/LeaderF/blob/fc8f161eb278acda29c87d87175278c2939db3c6/autoload/leaderf/python/leaderf/manager.py#L1660-L1661

**Comment by leoatchina** [comment]
yes, it works
