### ISSUE TITLE
vim.error: Vim(call):E117: 未知的函数: g:LfDefineDefaultColors when run LeaderFFile in Vim

### ISSUE THREAD

**Issue by MagicGrapes** [Yggdroot/LeaderF#1016]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 9.0
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: not usable
- Output of `:py3 print(sys.version)`: 3.11.4 (main, Jun 20 2023, 16:51:49) [Clang 14.0.0 (clang-1400.0.29.202)] 
- Output of `:echo g:Lf_Debug_Cmd`: find  "." -name "." -o   -name ".*" -prune -o -type f -print  2>/dev/null | sed 's#^\./##'
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
None
### Describe your question, feature request, or bug.

处理 function leaderf#Any#start[4]..leaderf#LfPy[1]..function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/treeliu/.vim/pack/mypack/start/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in s
tart
    the_args.start(arguments, *args, **kwargs)
  File "/Users/treeliu/.vim/pack/mypack/start/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _
default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/treeliu/.vim/pack/mypack/start/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 827, in 
startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/treeliu/.vim/pack/mypack/start/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2397, in 
startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/Users/treeliu/.vim/pack/mypack/start/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 1097, in
 enterBuffer
    self._createBufWindow(win_pos)
  File "/Users/treeliu/.vim/pack/mypack/start/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 839, in 
_createBufWindow
    lfCmd("call leaderf#colorscheme#popup#load('{}', '{}')".format(self._category, lfEval("get(g:, 'Lf_PopupColor
scheme', 'default')")))
vim.error: Vim(call):E117: 未知的函数: g:LfDefineDefaultColors

**Comment by Yggdroot** [comment]
How to reproduce?

**Comment by MagicGrapes** [comment]
@Yggdroot 
open a file and input the command in vim
:LeaderfFile
The error will happen.

Thanks

**Comment by Yggdroot** [comment]
Could you provide a minimal vimrc to reproduce it?

**Comment by MagicGrapes** [comment]
"高亮搜索"
set hlsearch
"设置命令显示"
set showcmd
"设置智能缩进"
set smartindent
"设置自动缩进"
set autoindent
"设置tab缩进"
set tabstop=8
set shiftwidth=4
set expandtab
set smarttab
"去除vi一致性" 
set nocompatible
let g:NERDTreeNodeDelimiter = "\u00a0"
set ruler
set background=light
filetype on
let g:ycm_key_invoke_completion = ''
let g:ycm_global_ycm_extra_conf= '~/.vim/pack/mypack/opt/YouCompleteMe/.ycm_extra_conf.py'
let NERDTreeShowLineNumbers=1
let NERDTreeAutoCenter=1
set backspace=indent,eol,start
set number
packadd YouCompleteMe
packadd Killersheep
packadd beachcomber
colorscheme murphy
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_ShowDevIcons = 0 

Hi @Yggdroot  This is my .vimrc file

**Comment by Yggdroot** [comment]
I don't find LeaderF in your vimrc, how did you install it?

**Comment by MagicGrapes** [comment]
@Yggdroot 
I think It is a feature in Vim, Vim will load the plugin automatically .
please refer to the link https://learnvim.irian.to/customize/vim_packages

**Comment by Yggdroot** [comment]
那你说怎么安装LeaderF的，或者说你把它放到哪里的？

**Comment by MagicGrapes** [comment]
@Yggdroot 
I put it into the directory "/.vim/pack/mypack/start/LeaderF "
and git clone

**Comment by Yggdroot** [comment]
复现不了。

**Comment by MagicGrapes** [comment]
😑唉，感谢，是我安装的Vim版本不对吗。
@Yggdroot

**Comment by Yggdroot** [comment]
vimrc:

```vim
set encoding=utf-8
syntax enable
set nocompatible


"{{{
filetype on  
"}}}

set runtimepath^=/.vim/pack/mypack/start/LeaderF

```

执行`vim -u vimrc`， 看看能不能工作。
