### ISSUE TITLE
Using LeaderF while having a quickfix window open is pushing splits up 

### ISSUE THREAD

**Issue by Leandros** [Yggdroot/LeaderF#102]
# Steps to reproduce

1. Open Vim
2. Open four equal split aligned, one in each corner
3. Open a quickfix (in my case a vim-grepper window)
3. Repeteadly open a LeaderF window

You'll see that the two top splits are getting pushed up, until they're not visible anymore.
They'll snap back into old position once the quickfix window is closed.
This sounds to me like a very specialized case of #33 

Attached is a gif of the bug in action:

![vimbug](https://user-images.githubusercontent.com/396475/35049220-9383e470-fb9f-11e7-94e4-7bc145132dbc.gif)
 
(Sorry for opening so many tickets. I absolutely love LeaderF, it's essential to my workflow in Vim. Incredible work. Keep it up, you rock!)

**Comment by Yggdroot** [comment]
Fixed.

**Comment by Yggdroot** [comment]
@Leandros Can you confirm whether this issue been fixed? So that I can close this issue.

**Comment by Leandros** [comment]
Works.
