### ISSUE TITLE
Leaderf相关的命令突然没有反应了（通过iTerm + ssh 在Linux Server使用）

### ISSUE THREAD

**Issue by vimerzhao** [Yggdroot/LeaderF#1021]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.8.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.0/x86_64-redhat-linux-gnu/cmake.config -I/builddir/build/BUILD/neovim-0.8.0/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.8.0/x86_64-redhat-linux-gnu/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.0/x86_64-redhat-linux-gnu/include
Compiled by mockbuild@koji

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`:  nothing
- Output of `:py3 print(sys.version)`: nothing
- Output of `:echo g:Lf_Debug_Cmd`: 
<img width="489" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/17337271/5cc3bf2b-b37b-404e-ada0-4b9a6dd9ad5e">

- Output of `:echo g:Lf_FilesFromCache`:  <img width="594" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/17337271/a9e3c3ac-04f5-4172-afbc-eb9ce824738d"> 

- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
<img width="591" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/17337271/6518a424-4651-4868-881a-0d9cdf859bc3">

这类问题有没有什么好找排查思路？

**Comment by Yggdroot** [comment]
之前是好的？你做了什么？

**Comment by vimerzhao** [comment]
可能更新了下(`PlugUpdate`)，应该没什么特殊操作

**Comment by Yggdroot** [comment]
任何命令都没反应？

**Comment by vimerzhao** [comment]
是的，没有任何UI的响应。

**Comment by Yggdroot** [comment]
Leaderf file --bottom 有反应吗？

**Comment by vimerzhao** [comment]
> Leaderf file --bottom 有反应吗？

没有

**Comment by Yggdroot** [comment]
太奇怪了

**Comment by vimerzhao** [comment]
我计划在各个节点加点日志，看看哪个环节出了问题

**Comment by Yggdroot** [comment]
找到原因了？

**Comment by vimerzhao** [comment]
放弃了，没时间研究 -_-
