### ISSUE TITLE
无法在preview窗口中移动光标

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#1023]
- vim or neovim? 
    - [x] vim
    - [ ] nvim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jun  6 2023 10:02:51)
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.8.10 (default, May 26 2023, 14:05:08)
[GCC 9.4.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```

set nocompatible


let mapleader = ' '
let g:mapleader = ' '

set encoding=utf-8  " must set this value to support chinese work in vimrc

let $MYVIMRC=fnamemodify(expand('<sfile>'), ':p')
let $VIMFILES=fnamemodify(expand('<sfile>'), ':p:h')
set runtimepath+=$VIMFILES

call plug#begin()
    Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
call plug#end()

" 替换leaderf 插件中默认的键
let g:Lf_CommandMap = {
\   '<C-R>': ['<C-E>'],
\   '<C-F>': ['<C-D>'],
\   '<C-Up>': ['<C-K>'],
\   '<C-Down>': ['<C-J>'],
\ }


let g:Lf_PopupPosition = [2 , 0] " popup 窗口位置屏幕中间偏上
let g:Lf_PreviewInPopup = 1 " 是否在popup中preview
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_WindowPosition = 'popup'
let g:Lf_ShortcutF = "<leader>lf"

```
### Steps to reproduce
复现步骤:
   ```
 leader键lf open file list
    tab后选择较长的文件, 按p打开preview
    通过<C-K>或者<C-J>在preview窗口中移动光标 
```

### Actual behaviour
    结果:
    commit https://github.com/Yggdroot/LeaderF/commit/27bd938a422fc6fcfc453fa88fe2ad453a012074 无法在preview中移动光标
    commit https://github.com/Yggdroot/LeaderF/commit/86013dd6208609e51c722e91e8faa6c4597ed83a 可以移动光标

### Expected behaviour
    期望光标可以在preview中移动

**Comment by Yggdroot** [comment]
复现不了。

**Comment by Yggdroot** [comment]
难道跟终端有关系？

**Comment by irreallich** [comment]
我试过ubuntu的默认终端

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/6a4e01d85337c781cf6fe37e19f87e41869adfad/autoload/leaderf/python/leaderf/manager.py#L2917C39-L2921C39

**Comment by Yggdroot** [comment]
直接把这里代码改成别的键试一下，我怀疑你的电脑上识别不了Ctrl-up，Ctrl-down

**Comment by irreallich** [comment]
我大概修改成这个样子

**Comment by Yggdroot** [comment]
不需要编译。
有点奇怪。
https://github.com/Yggdroot/LeaderF/blob/6a4e01d85337c781cf6fe37e19f87e41869adfad/autoload/leaderf/python/leaderf/manager.py#L1122
https://github.com/Yggdroot/LeaderF/blob/6a4e01d85337c781cf6fe37e19f87e41869adfad/autoload/leaderf/python/leaderf/manager.py#L1134
在这两行下面，加上`lfCmd("redraw")` 再试一下。

**Comment by irreallich** [comment]
依然没有变化
我觉得应该不是电脑上识别不了Ctrl-up，Ctrl-down
因为如果使用 86013dd6208609e51c722e91e8faa6c4597ed83a  这个commit, 那么功能就是正常的

**Comment by Yggdroot** [comment]
第一个有问题的commit是哪个？

**Comment by irreallich** [comment]
是这个 https://github.com/Yggdroot/LeaderF/commit/27bd938a422fc6fcfc453fa88fe2ad453a012074
里面改的文件比较多, 如果能够列出与这个功能有关的改动, 一个个rollback, 可能容易一些

**Comment by irreallich** [comment]
@Yggdroot  能否根据这个commit修改的文件列表中, 找出和popup preview相关的文件出来
我尝试两个版本对比测试一下

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/6a4e01d85337c781cf6fe37e19f87e41869adfad/autoload/leaderf/python/leaderf/manager.py#L1124-L1134

按ctrl-down就是调用的这个函数，可以加一下打印，看看是不是走到了。

**Comment by irreallich** [comment]
通过测试, 我发现在popup的文件列表中可以输入字母来搜索文件名的

**Comment by irreallich** [comment]
基于一下配置测试:
1. 在文件列表状态位INPUT的情况下, 打开自动popup窗口, 可以通过<C-K>或者<C-J>上下移动preview的文件内的光标


commit id 
`
commit 84a9e0160df51dce9218efe5a1e3e6c6af28874e (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: Yggdroot <archofortune@gmail.com>
Date:   Fri Aug 4 17:53:57 2023 +0800

    add support for cyclic scroll
`
使用如下的配置:

`" 关闭兼容模式,如果使用-u来加载vimrc，这行必须存在
set nocompatible

" 设置leader键
let mapleader = ' '
let g:mapleader = ' '

set encoding=utf-8  " must set this value to support chinese work in vimrc

let $MYVIMRC=fnamemodify(expand('<sfile>'), ':p')
let $VIMFILES=fnamemodify(expand('<sfile>'), ':p:h')
set runtimepath+=$VIMFILES

call plug#begin()
    Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
call plug#end()


let g:Lf_PopupPosition = [2 , 0] " popup 窗口位置屏幕中间偏上
let g:Lf_PreviewInPopup = 1 " 是否在popup中preview
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_WindowPosition = 'popup'
let g:Lf_ShortcutF = "<leader>lf"

" 替换leaderf 插件中默认的键
let g:Lf_CommandMap = {
\   '<C-R>': ['<C-E>'],
\   '<C-F>': ['<C-D>'],
\   '<C-Up>': ['<C-K>'],
\   '<C-Down>': ['<C-J>'],
\ }
`

**Comment by Yggdroot** [comment]
搞了这么长时间，原来是个乌龙。
g:Lf_CommandMap 不能改normal模式下的按键。所以normal模式下，按ctrl-down，ctrl-up应该可以移动。

**Comment by irreallich** [comment]
那么有没有办法在修改normal模式下的键位呢?
因为如果只能使用ctrl-down，ctrl-up来移动preview的光标,会有至少有两个问题
1.  对于带有方向键的键盘, 手需要离开主键盘区,  对于部分笔记本, 这几个键位是很不好摸的
2.  某些特殊键盘没有单独的方向键, 需要组合键才能按出来, 这个也不是很方便
能够在normal模式下修改键位会解决这些问题

而在版本 86013dd6208609e51c722e91e8faa6c4597ed83a   , 这个功能是存在的, 不知道为什么后续被清除掉了?

**Comment by Yggdroot** [comment]
我知道你说的问题了。

**Comment by irreallich** [comment]
> 我知道你说的问题了。

可否了解下, 即将怎么处理
以后版本是否支持normal下修改按键?

**Comment by Yggdroot** [comment]
这个问题我正准备修复，应该是https://github.com/Yggdroot/LeaderF/commit/65740651731c01363c2dad0c528102bc0c7876fe 引入的bug。

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/3ded37f92807d8c6ad831d5af2c4ff22bfd32fc8/doc/leaderf.txt#L523-L553
