### ISSUE TITLE
When search keyword with ripgrep, how can I just search files under current working directory instead project root directory?

### ISSUE THREAD

**Issue by ucasfl** [Yggdroot/LeaderF#1026]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
When use command like `LeaderfRgCwordLiteralNoBoundary` to search a keyword, it will search under the whole project root directory, how can I just search under current working directory(because project root directory may contain too many thirdparty library files)?

**Comment by Yggdroot** [comment]
If you set `let g:Lf_WorkingDirectoryMode = 'c'`, it will search under current working directory.
Or add `--wd-mode c` option.

**Comment by ucasfl** [comment]
Got it. Thank you!
