### ISSUE TITLE
[Feature Request]希望能够支持查看函数的引用、定义等跟LSP相关的一些功能

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#1028]
就是希望通过LSP来查看一个函数或者变量的所有引用等等 目前是在用Coc.nVim 但是查看函数引用的时候很不方便 如果能通过Leaderf来查看就完美了  我可以简单来实现下 但是有一些问题 比如：路径显示的是全路径而不是相对于工作目录的相对路径
``` 
let g:coc_enable_locationlist = 0
function! GR()
  call CocAction('jumpReferences')
  call LfP(1)
  sil! sleep 10m
  exec "Leaderf! quickfix --nowrap"
  sil! exec "cclose"
endfunction
````
#731 最早这里提过 后面他自己实现了这个扩展[coc-leaderf](https://github.com/shunlir/coc-leaderf) 但是已经很久没更新了 #475  #938 都提到过这样的功能

**Comment by Yggdroot** [comment]
对LSP还没有深入研究过，不知道怎么做。

**Comment by gVimer** [comment]
> 对LSP还没有深入研究过，不知道怎么做。

这个估计你个几个小时看下文档就明白了 其实我也不明白 因为不需要直接去使用 而是别人写的插件

然后就是这个命令：`Leaderf! quickfix`没有考虑到一些参数如`g:Lf_ShowRelativePath`故不能显示相对路径 

我在`LEADERF\autoload\leaderf\python\leaderf\qfloclistExpl.py`简单改了下(不是最新版本)：
```
       30 +lines=lfEval("""map({},'bufname(v:val.bufnr).":".v:val.lnum .":".v:val.col .":".v:val.text')""".format(cmd))
       31 +lines=[lfRelpath(line) for line in lines]
       32 +return lines
       33 -return lfEval(
       34 -    """map({}, 'bufname(v:val.bufnr) . ":" . v:val.lnum . ":" . v:val.col . ":" . v:val.text')""".format(cmd)
       35 -)
```
