### ISSUE TITLE
[feature-request] 按 ALT+1-9 快速选择相关候选项

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#1029]
有时候候选项排序在 2 号位，3 号位时，想选择还要笨拙的 ctrl+j 或者切换 normal 模式，或者逼迫自己多打几个字让它排到第一
而现在的 fuzzy finder，很多都可以直接用 alt+NUM 对前几个候选项进行快速跳转，比如 uTools 里面，

默认没按 alt 时：

![图片](https://github.com/Yggdroot/LeaderF/assets/3035071/854a6ed0-87b8-4c23-87b7-8d7995e73068)

按下 alt 时，左边出现数字提醒：

![图片](https://github.com/Yggdroot/LeaderF/assets/3035071/ed3d75e2-6f29-44f1-b39e-419f43a3e96d)

然后用 ALT+NUM 就能快速跳转序号标注的候选项，不用上下键选半天，也不用点完。

如果 LeaderF 能增加对应功能，那使用会更加方便，如果 ALT+NUM 不好实现，或者可以按 SHIFT+TAB 进入

快选模式，此时数字会标注再对应选项左侧，按 0-9 将直接触发候选项，或者弄个选项把 0-9 直接弄成快速选择，而不参与匹配，连模式切换都省了。

**Comment by Yggdroot** [comment]
好多终端，Alt+数字默认是被占用的。

> 或者弄个选项把 0-9 直接弄成快速选择，而不参与匹配，连模式切换都省了。

感觉这个可行。

**Comment by skywind3000** [comment]
感觉也不用显示啥数字，有 vim 的行号即可

**Comment by Yggdroot** [comment]
确实不用显示数字，因为有行号。
有个问题，选择后用那种方式打开呢？用tab，split还是当前窗口？
现在有3种方式实现：
1. 直接支持Alt+num，但是好多终端默认不支持alt+num，需要设置
2. 弄个选项把 0-9 直接弄成快速选择，而不参与匹配，连模式切换都省了。这样稍微弱化了模糊匹配的功能，不过需要打数字的时候不多。
3. 按一个key，比如`<c-d>`, 然后就可以按0-9选择。

你觉得哪种好？

**Comment by skywind3000** [comment]
感觉用 2 吧，确实存在一个打开方式，感觉也只能让用户配置了。

**Comment by Yggdroot** [comment]
好了。
https://github.com/Yggdroot/LeaderF/blob/712da0e4ebe9376d52be0e60eff72e8411ea5992/doc/leaderf.txt#L1091-L1112

**Comment by skywind3000** [comment]
多谢
