### ISSUE TITLE
Error detected while processing

### ISSUE THREAD

**Issue by hy172574895** [Yggdroot/LeaderF#103]
system：windows10
vim version：vim8.0

When I opening vim, showing the follow message:
**Error detected while processing D:\gvim\vimfiles\bundle\LeaderF\pl
ugin\leaderf.vim:
line  123:
E722: Missing comma in Dictionary: right': '鈼?})
E116: Invalid arguments for function <SNR>22_InitVar**

when I  “ set encoding=utf-8” in vimrc, everything is OK.
Maybe it‘s a coded format problem.
But I have to use GBK. 
BTW, I really like leaderf, hoping this plugin could be  better.And thank you.

**Comment by Yggdroot** [comment]
Fixed. Before the fix, you can set `let g:Lf_StlSeparator = { 'left': '', 'right': '' }` in your vimrc to work around it.
