### ISSUE TITLE
有一个已弃用的nerd icon

### ISSUE THREAD

**Issue by Eliot00** [Yggdroot/LeaderF#1032]
- vim or neovim? 
    - [x] vim
    - [ ] neovim

Unicode f720 nf-mdi-file_lock 希望可以替換成其他可用的

**Comment by Eliot00** [comment]
https://github.com/Yggdroot/LeaderF/blob/3ded37f92807d8c6ad831d5af2c4ff22bfd32fc8/autoload/leaderf/python/leaderf/devicons.py#L51

`'',  'rmeta'`

**Comment by Yggdroot** [comment]
怎么知道它被弃用了？

**Comment by Eliot00** [comment]
> 怎么知道它被弃用了？

https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

https://www.nerdfonts.com/cheat-sheet 这里可以搜到

**Comment by Yggdroot** [comment]
用f0221 󰈡？

**Comment by Eliot00** [comment]
> 用f0221 󰈡？

<img width="28" alt="截屏2023-09-06 15 45 14" src="https://github.com/Yggdroot/LeaderF/assets/18375468/b000eb35-d2ca-4420-9bc4-054d21c35eba">

在我的wezterm里用nerdfonts3可以正常显示
