### ISSUE TITLE
NameError: name 'anyHub' is not defined

### ISSUE THREAD

**Issue by arozehnal** [Yggdroot/LeaderF#1033]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  vim -u .vimrc_tmenu   --version                      
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul  7 2023 01:12:41)
Included patches: 1-1649

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`:  1 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.so
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.12 (default, Dec 15 2021, 03:25:47)
[GCC 8.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [] Linux
    - [] Mac OS X
    - [] Windows
    - [X] Etc.
- Configurations related to LeaderF in vimrc: 
Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }

" don't show the help in normal mode
"let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
" popup mode
let g:Lf_WindowPosition = 'popup'
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }

let g:Lf_ShortcutF = "<leader>ff"
noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>

noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
" search visually selected text literally
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
noremap go :<C-U>Leaderf! rg --recall<CR>

" should use `Leaderf gtags --update` first
let g:Lf_GtagsAutoGenerate = 0
let g:Lf_Gtagslabel = 'native-pygments'
noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>

### Describe your question, feature request, or bug.
installation was ok, no errors

 Leaderf -h

return
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'anyHub' is not defined
### Expected behaviour
no error

**Comment by Yggdroot** [comment]
What's the output of `:py3 print(sys.path)`  after `Leaderf -h` is run?

**Comment by arozehnal** [comment]
**:Leaderf -h**
 Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'anyHub' is not defined

**:py3 print(sys.path)**
['/intax/roze2/.vim/plugged/LeaderF/autoload/leaderf/python', '/opt/freeware/lib64/python37.zip', '
/opt/freeware/lib64/python3.7', '/opt/freeware/lib64/python3.7/lib-dynload', '/opt/freeware/lib64/python3.7/site-packages', '/opt/freeware/lib/python3.7/site-packages', '_vim_path_']

**Comment by Yggdroot** [comment]
Duplicate of #720 .

**Comment by arozehnal** [comment]
I'm new here - sorry for the stupid question...
Is my problem to be solved by reinstalling the LeaderF plugin?
I have reinstalled the plugin, including the C extension,but the result is still the same.

According to messages like 
Symbol PyBool_FromLong (number 1) is not exported from dependent module vim.
I judge that the problem is in the setting/availability of some symbols in vim-leaderf-python communication.
I compiled vim to have python support bolted on statically, but the result is still the same.

vim reports that it has Python3 support, the LeaderF installation went Ok... 
Question: 
Is there any way to verify the functionality of LeaderF outside of Vim?

**Comment by Yggdroot** [comment]
Actually, if `Leaderf -h`, 
https://github.com/Yggdroot/LeaderF/blob/7088babc96bc35b5a5a0b5ad12e3d2e7430b1a38/autoload/leaderf/Any.vim#L10-L14
should have been executed.

You can run `:py3 from leaderf.anyExpl import *` after `Leaderf -h`.

To see the output of `:py3 print(globals())` before and after the command above.

**Comment by arozehnal** [comment]
**Here is output of :py3 print(globals()) before** 
py3 print(globals())
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <cl
ass '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {
}, '__builtins__': <module 'builtins' (built-in)>, 'vim': <module 'vim' (built-i
n)>, 'sys': <module 'sys' (built-in)>}

**and after**
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <cl
ass '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {
}, '__builtins__': <module 'builtins' (built-in)>, 'vim': <module 'vim' (built-i
n)>, 'sys': <module 'sys' (built-in)>, 'os': <module 'os' from '/opt/freeware/li
b/python3.7/os.py'>, 're': <module 're' from '/opt/freeware/lib/python3.7/re.py'
>, 'cwd': '/intax/roze2/.vim/plugged/LeaderF/autoload'}


I'm not a programmer, but from the output, it seems that Vim and Python were successfully linked, but the loading of LeaderF failed, specifically the import of Python modules.

I've requested help on the AIX discussion forum as well, so we'll see.

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/7088babc96bc35b5a5a0b5ad12e3d2e7430b1a38/autoload/leaderf/Any.vim#L10-L14

It seems Line 14 is not executed, could you check it please?
You can add the code as below:

```vim
if leaderf#versionCheck() == 0  " this check is necessary 
     echoerr "leaderf#versionCheck() failed." 
     finish 
 endif 
  
 exec g:Lf_py "from leaderf.anyExpl import *" 
```

**Comment by arozehnal** [comment]
I'd like to thank you for your willingness and helpfulness. I've come to the conclusion that the plugin is unrunnable on AIX.  I tried the replacements you sent last time and didn't get much further...

`Error detected while processing /intax/roze2/.vim/plugged/LeaderF/autoload/leaderf/Any.vim:
line   16:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/intax/roze2/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 15
, in <module>
    from .manager import *
  File "/intax/roze2/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 19
, in <module>
    from .asyncExecutor import AsyncExecutor
  File "/intax/roze2/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", l
ine 7, in <module>
    import subprocess
  File "/opt/freeware/lib/python3.7/subprocess.py", line 152, in <module>
    import _posixsubprocess
ImportError: Symbol resolution failed for /opt/freeware/lib/python3.7/lib-dynload/_posixsubpro
cess.so because:
^ISymbol PyArg_ParseTuple (number 1) is not exported from dependent
^I  module vim.
^ISymbol PyBytes_AsString (number 2) is not exported from dependent
^I  module vim.
^ISymbol PyErr_Fetch (number 3) is not exported from dependent
^I  module vim.
^ISymbol PyErr_Restore (number 4) is not exported from dependent
^I  module vim.
^ISymbol PyErr_SetFromErrno (number 5) is not exported from dependent
^I  module vim.
^ISymbol PyErr_SetString (number 6) is not exported from dependent
^I  module vim.
Additional errors occurred but are not reported.
Examine .loader section symbols with the 'dump -Tv' command.
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):


I tried a little search for Symbol PyArg_ParseTuple (number 1) 
and found ... https://bugs.python.org/issue13493
I've long ago accepted that rows of things are common on Linux, but on AIX there is a problem.
Thanks again for the help, I'm going to run LeaderF on windows :-)
