### ISSUE TITLE
commit 9ea4885 使用rg搜索后,打开结果,却直接在preview窗口开始编辑.

### ISSUE THREAD

**Issue by fzhzhen1987** [Yggdroot/LeaderF#1034]
- vim or neovim? 
    - [ ] vim
    - [ x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.9.0-dev-1312+g908494889
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`:  3.10.9
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let $GTAGSLABEL = 'native-pygments'
let $GTAGSCONF = expand('~/.gtags.conf')

let g:gutentags_define_advanced_commands = 1
"搜索工程目录的标志，碰到这些文件/目录名就停止向上一级目录递归
let g:gutentags_project_root = ['.stop_gun', '.root', '.svn', '.git', '.hg', '.project']

"同时开启 ctags 和 gtags 支持：
let g:gutentags_modules = []
if executable('gtags-cscope') && executable('gtags')
	let g:gutentags_modules += ['gtags_cscope']
endif

"检测 ~/.cache/tags 不存在就新建
"将自动生成的tags文件全部放入~/.cache/tags 目录中，避免污染工程目录
let s:vim_tags = expand('~/.cache/tags')
let g:Lf_CacheDirectory = s:vim_tags
let g:gutentags_cache_dir = expand(g:Lf_CacheDirectory.'/LeaderF/gtags')

if !isdirectory(s:vim_tags)
	silent! call mkdir(s:vim_tags, 'p')
endif

"禁用gutentgs自动加载gtags数据库的行为
let g:gutentags_auto_add_gtags_cscope = 0

"Yggdroot/LeaderF
" don't show the help in normal mode
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1

let g:Lf_GtagsAutoGenerate = 0
let g:Lf_GtagsGutentags = 1
let g:Lf_RootMarkers = ['.stop_gun', '.root', '.svn', '.git', '.hg', '.project']

let g:Lf_WindowPosition = 'right'
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewHorizontalPosition = 'right'
let g:Lf_JumpToExistingWindow = 0
let g:Lf_PopupWidth = 0.8
let g:Lf_PopupHeight = 0.6
let g:Lf_PreviewCode = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }

let g:Lf_ShortcutF = '<nop>'
let g:Lf_ShortcutB = '<nop>'

### Describe your question, feature request, or bug.
我的操作逻辑是:
按键"?"使用rg搜索光标当前的单词,并打开预览.

发生错误在于:
当我打开一个搜索结果的时候,没有 [关闭预览页面并打开新的页面],而是[光标跳到preview页面开始编辑,文本显示也不是正常的格式].

使用的rg搜索命令是:
`noremap ? :<C-U><C-R>=printf("Leaderf rg --current-buffer -F -e %s --no-sort --stayOpen", expand("<cword>"))<CR><CR>`

我的配置文件在以下URL
https://github.com/fzhzhen1987/nvim

**Comment by fzhzhen1987** [comment]
--stayOpen 的逻辑改变了
具体从哪个提交改变没具体测试,不过和
2144e40a fix issue #1011的逻辑不一样

**Comment by Yggdroot** [comment]
行为没变，只是一些配置的默认值变了。
好像你以前不是用的popup preview，那`let g:Lf_PreviewInPopup = 1` 应该改成`let g:Lf_PreviewInPopup = 0`，
还有默认打开了自动预览，可以在每个命令后面加上`--no-auto-preview`，或者把`g:Lf_PreviewResult`里面对应项的值设为0.

不过你说的这个问题倒是个问题，我看看怎么修复。

**Comment by fzhzhen1987** [comment]
> 行为没变，只是一些配置的默认值变了。 好像你以前不是用的popup preview，那`let g:Lf_PreviewInPopup = 1` 应该改成`let g:Lf_PreviewInPopup = 0`， 还有默认打开了自动预览，想关掉，可以在每个命令后面加上`--no-auto-preview`，或者把`g:Lf_PreviewResult`里面对应项的值设为0.
> 
> 不过你说的这个问题倒是个问题，我看看怎么修复。

①"Leaderf gtags -s %s --top --auto-preview', expand('')"
②"Leaderf gtags -d %s --top --auto-preview", expand(")"
③"Leaderf gtags -r %s --top --auto-preview", expand("")
这三个操作我特意打开自动显示。

let g:Lf_PreviewInPopup = 1
是为了
noremap ? :<C-U><C-R>=printf("Leaderf rg --current-buffer -F -e %s --no-sort --stayOpen", expand("<cword>"))<CR><CR>
这个命令
特意设置的PreviewInPopup，这样左边的搜索窗不会被预览覆盖。我特意这样设置的

**Comment by Yggdroot** [comment]
好像是有两个问题，一个是--stayOpen时，预览窗口不关闭，一个是预览窗口的位置问题。

**Comment by Yggdroot** [comment]
> 原来的预览画面快捷键也失效了.

这个应该没有吧，预览还是ctrl-p，或者normal下的p

**Comment by fzhzhen1987** [comment]
> > 原来的预览画面快捷键也失效了.
> 
> 这个应该没有吧，预览还是ctrl-p，或者normal下的p

我已经把默认键位改成 <C-R>了
"修改键位
let g:Lf_CommandMap = {
			\'<C-P>': ['<C-R>'],
			\'<C-K>': ['<C-P>'],
			\'<C-J>': ['<C-N>'],
			\'<ESC>': ['<C-Q>', '<ESC>'],
			\'<C-UP>': ['<C-K>'],
			\'<C-DOWN>': ['<C-J>'],
			\'<C-X>': ['<C-O>'],
			\'<C-]>': ['<C-E>']
			\}

**Comment by fzhzhen1987** [comment]
我就是这样重新绑定的键位，然后新版本中绑定的`<C-R>`是失效的状态
```shell
"修改键位
let g:Lf_CommandMap = {
			\'<C-P>': ['<C-R>'],
			\'<C-K>': ['<C-P>'],
			\'<C-J>': ['<C-N>'],
			\'<ESC>': ['<C-Q>', '<ESC>'],
			\'<C-UP>': ['<C-K>'],
			\'<C-DOWN>': ['<C-J>'],
			\'<C-X>': ['<C-O>'],
			\'<C-]>': ['<C-E>']
			\}

"let g:Lf_ShortcutF = '<leader>lf'
let g:Lf_ShortcutF = '<nop>'
let g:Lf_ShortcutB = '<nop>'
```
.....这可以用md格式啊

**Comment by Yggdroot** [comment]
> 我就是这样重新绑定的键位，然后新版本中绑定的`<C-R>`是失效的状态
> 
> ```shell
> "修改键位
> let g:Lf_CommandMap = {
> 			\'<C-P>': ['<C-R>'],
> 			\'<C-K>': ['<C-P>'],
> 			\'<C-J>': ['<C-N>'],
> 			\'<ESC>': ['<C-Q>', '<ESC>'],
> 			\'<C-UP>': ['<C-K>'],
> 			\'<C-DOWN>': ['<C-J>'],
> 			\'<C-X>': ['<C-O>'],
> 			\'<C-]>': ['<C-E>']
> 			\}
> 
> "let g:Lf_ShortcutF = '<leader>lf'
> let g:Lf_ShortcutF = '<nop>'
> let g:Lf_ShortcutB = '<nop>'
> ```
> 
> .....这可以用md格式啊

用你的键位映射在我这边没有任何问题。

**Comment by fzhzhen1987** [comment]
`noremap ? :=printf("Leaderf rg --current-buffer -F -e %s --no-sort --stayOpen", expand(""))`
使用新的fix。使用上面这个命令，目的测试--stayOpen。但是不能显示被搜索的位置，直接就被preview 窗口替代了。

**Comment by Yggdroot** [comment]
我说的两个问题，预览窗口的位置还没改。

**Comment by fzhzhen1987** [comment]
安静等待，受累了 哥们

**Comment by fzhzhen1987** [comment]
我又发现一个是关于Preview窗口的问题，不知道你是不是特意这样设计的：
前提在不使用popup preview `let g:Lf_PreviewInPopup = 0`，不论操作命令中是否有`--auto-preview`。
使用C-R打开预览的问题是，是直接打开了文件生成了新buffer，而不是预览窗口，并且退出 搜索的结果时，不能回到原来的搜索的位置，新的位置在刚才直接打开的文件buffer。

我主要同时使用`let g:Lf_PreviewInPopup = 1` ，不同的命令会分别使用`--auto-preview`和`--stayOpen`
这3个东西在一起搭配使用和原来的逻辑一样对我来说就没什么区别。

关键配置如下
```shell
let g:Lf_PreviewInPopup = 0
noremap <silent> <A-,> :<C-U><C-R>=printf("Leaderf gtags -r %s --top ", expand("<cword>"))<CR><CR>

"修改键位
let g:Lf_CommandMap = {
			\'<C-P>': ['<C-R>'],
			\'<C-K>': ['<C-P>'],
			\'<C-J>': ['<C-N>'],
			\'<ESC>': ['<C-Q>', '<ESC>'],
			\'<C-UP>': ['<C-K>'],
			\'<C-DOWN>': ['<C-J>'],
			\'<C-X>': ['<C-O>'],
			\'<C-]>': ['<C-E>']
			\}

"let g:Lf_ShortcutF = '<leader>lf'
let g:Lf_ShortcutF = '<nop>'
let g:Lf_ShortcutB = '<nop>'

```

**Comment by Yggdroot** [comment]
就是这样设计的，所以最好let g:Lf_PreviewInPopup = 1

**Comment by fzhzhen1987** [comment]
想问你个statusline的事.leaderf支持显示当前行所在函数功能吗.针对c语言.

**Comment by Yggdroot** [comment]
> 想问你个statusline的事.leaderf支持显示当前行所在函数功能吗.针对c语言.

不支持，用Leaderf function可以

**Comment by fzhzhen1987** [comment]
> > 想问你个statusline的事.leaderf支持显示当前行所在函数功能吗.针对c语言.
> 
> 不支持，用Leaderf function可以

请教一下用Leaderf function 跟什么参数可以显示当前行所在函数

**Comment by Yggdroot** [comment]
Leaderf! function

**Comment by fzhzhen1987** [comment]
> Leaderf! function

好用 谢了 朋友

**Comment by Yggdroot** [comment]
> `noremap ? :=printf("Leaderf rg --current-buffer -F -e %s --no-sort --stayOpen", expand(""))` 使用新的fix。使用上面这个命令，目的测试--stayOpen。但是不能显示被搜索的位置，直接就被preview 窗口替代了。
> 
> 可以使用 [2144e40](https://github.com/Yggdroot/LeaderF/commit/2144e40ac60782ea4ed779834daff3cf89317d66) fix issue #1011 和现在的提交做个对比。 在2144e40a可以 --stayOpen

加上`--preview-position cursor`就可以了。

**Comment by fzhzhen1987** [comment]
哥们有个问题,这个命令如何让preview不自动打开.我想看所有的搜索结果后,使用自己设置的预览快捷键打开preview
`noremap ? :=printf("Leaderf rg --current-buffer -F -e %s --no-sort --stayOpen --preview-position cursor", expand(""))`

**Comment by Yggdroot** [comment]
> 请教一个问题 leaderf这个软件编译使用的是python2么? 如果用python3的头文件编译,可以运行吗 我公司里的安全策略把python2禁用了只能用python3编译. 编译是通过了.但是插件失效了.所有的功能都失效了.和python的版本有关么

py2，py3都可以。只要:echo has("python") 或者:echo has("python3")为1就可以用。

**Comment by fzhzhen1987** [comment]
> > 请教一个问题 leaderf这个软件编译使用的是python2么? 如果用python3的头文件编译,可以运行吗 我公司里的安全策略把python2禁用了只能用python3编译. 编译是通过了.但是插件失效了.所有的功能都失效了.和python的版本有关么
> 
> py2，py3都可以。只要:echo has("python") 或者:echo has("python3")为1就可以用。

好的.我回去试试.
假如python2或者3 是1.
但是leaderf所有功能还是都不能使用,可能性有什么.
我应该查哪个部分.可以给点提示么

**Comment by Yggdroot** [comment]
这只能具体问题具体分析了。
看看不能用是指什么，敲了命令报错还是没有任何反应？报错就根据错误信息来定位问题，应该很容易。没有任何反应这个问题应该很难遇到。

**Comment by fzhzhen1987** [comment]
昨天ubuntu系统更新之后我也傻了.任何反应都没有了. 其他插件没问题.只有leaderf出问题了
