### ISSUE TITLE
请问能否在打开vim的时候，在后台执行一次Leaderf gtags，将gtags索引全部载入

### ISSUE THREAD

**Issue by niexin-dev** [Yggdroot/LeaderF#1035]
![image](https://github.com/Yggdroot/LeaderF/assets/8086937/c2bf5dd4-078e-4a66-9e4c-a7ef079e6757)
如果gtags文件大，想通过Leaderf gtags去搜索函数，第一次去搜索时，很慢
 像我这gtags就有1643478个数据，第一次必须等这些全部出来了，下次调用leaderf gtags时才能快速搜索到数据
 
![image](https://github.com/Yggdroot/LeaderF/assets/8086937/02085296-bce2-4f7b-b6fa-0dc5e933eed3)

 1/1643478  Total: 1643478

**Comment by niexin-dev** [comment]
主要是有时不记得函数全称，就想通过leaderf gtags去搜索一下，但第一次打开就很慢，这两个选项都开启了
   771 let g:Lf_UseCache = 1                                                                                                                                                                                                                                                                                               
   772 let g:Lf_UseMemoryCache=1

**Comment by Yggdroot** [comment]
> 主要是有时不记得函数全称，就想通过leaderf gtags去搜索一下，但第一次打开就很慢，这两个选项都开启了 771 let g:Lf_UseCache = 1 772 let g:Lf_UseMemoryCache=1

这两个选项都是Leaderf file相关的，跟gtags没关系。

**Comment by niexin-dev** [comment]
但我发现

**Comment by niexin-dev** [comment]
> 但我发现如果把leaderf的cache打开，leadetf gtags只会加载一次全部条目1643478，如果把cahe关了，每次都是从1一直读取到1643478，难道是我记错了，明天我再试试

这两个选项确实跟gtags没关系，我记混了，那么针对Leaderf[!] gtags --all第一次进入右下角需要加载，请问有什么办法让这个能打开vim的施主异步自动加载一次吗？第一次加载要等待，后续再调用Leaderf[!] gtags --all就是秒开了

**Comment by Yggdroot** [comment]
如果文件有变化，gtags数据库也会跟着变化，同样需要重新加载。所以感觉感觉在后台执行一次没有必要。

**Comment by niexin-dev** [comment]
> 如果文件有变化，gtags数据库也会跟着变化，同样需要重新加载。所以感觉感觉在后台执行一次没有必要。

不一定要改到eaderf中，没用过python，viml也不熟悉，所以主要是想了解怎样开机自动调用一次这个Leaderf gtags，想用autocmd VimEnter * call 来弄，但没想明白怎么调用这个Leaderf gtags

**Comment by Yggdroot** [comment]
直接调用Leaderf gtags好像不行，因为这样还是会打开leaderf的窗口。

https://github.com/Yggdroot/LeaderF/blob/c632d20218ddd9ad4758586b89debd08ae43a6bd/autoload/leaderf/python/leaderf/gtagsExpl.py#L75-L289

https://github.com/Yggdroot/LeaderF/blob/c632d20218ddd9ad4758586b89debd08ae43a6bd/autoload/leaderf/python/leaderf/gtagsExpl.py#L178-L199

主要逻辑在这里，代码耦合性有点大，不改Leaderf的代码应该做不到。
