### ISSUE TITLE
关闭preview 后，popup window 的大小仍然是原来的一半

### ISSUE THREAD

**Issue by sheeaza** [Yggdroot/LeaderF#1037]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
    - lua配置
    ``` lua
    vim.g.Lf_PreviewResult = { 
            File = 0,          
            Tag = 0,           
            Function = 0,      
            Jumps = 0,         
            Mru = 0,           
            Rg = 0,            
            Line = 0,          
            Buffer = 0,        
    }                          
                           
    ```
### Describe your question, feature request, or bug.
关闭preview后，期望popupwindow 大小能扩充到以下红框部分，也就是preview 窗口部分
![屏幕截图 2023-09-16 095003](https://github.com/Yggdroot/LeaderF/assets/9819120/aa4d96f4-f3b0-4246-bac4-fab7ad68e20f)

**Comment by Yggdroot** [comment]
没有这个功能

**Comment by chenkui164** [comment]
我也是和楼主一样的使用习惯，使用的popupwindow，并关闭了preview功能。感觉右边空了一半，左边的又不够长，不能在一行的同时显示

**Comment by Yggdroot** [comment]
> 我也是和楼主一样的使用习惯，使用的popupwindow，并关闭了preview功能。感觉右边空了一半，左边的又不够长，不能在一行的同时显示

如果不使用preview，可以用`g:Lf_PopupWidth`或者`--popup-width` 来指定宽度，用`g:Lf_PopupPosition` 来指定左上角的位置。
当然预览窗口还可以放上面或下面。

**Comment by epheien** [comment]
一样的问题, 这个应该要自动匹配尺寸以及位置才行吧, 当这个类别没有preview的时候, 至少要做到自动居中吧, 只是简单粗暴地干掉预览窗口实在是丑啊

**Comment by sheeaza** [comment]
感谢作者优化。
