### ISSUE TITLE
Leaderf rg --live mode dosen't work, error 'NoneType' object has no attribute 'isReverseOrder'

### ISSUE THREAD

**Issue by JaminYoung** [Yggdroot/LeaderF#1038]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.2 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): none output
- Output of `:echo &pythonthreedll`(only vim, not neovim): none output
- Output of `:py print(sys.version)`: invalid command
- Output of `:py3 print(sys.version)`: 3.10.12
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux (WSL)
    - [ ] Mac OS X
    - [ ] Windows 
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
![image](https://github.com/Yggdroot/LeaderF/assets/25146444/55a335e2-7faa-4e7a-99bc-2500c4b8ea7b)

### Describe your question, feature request, or bug.
each time I start vim , and type :Leaderf rg --live, showing error below
![image](https://github.com/Yggdroot/LeaderF/assets/25146444/35c06ee2-96d8-4bed-8e21-53191dbe8f42)
but if I typed :Leaderf rg, and it works fine, and after that, typing  :Leaderf rg --live works fine as well.

### Steps to reproduce
1. open vim
2. :Leaderf rg --live
3. :Leaderf rg 
4. :Leaderf rg --live

### Actual behaviour
step 2 would show error mentioned before, step 4 works fine 
### Expected behaviour
running step 2 without error.

**Comment by Yggdroot** [comment]
Fixed, thanks.

**Comment by JaminYoung** [comment]
thanks for fixing it!
