### ISSUE TITLE
Swap mapping of 's' and 'x' in normal mode

### ISSUE THREAD

**Issue by mechkb** [Yggdroot/LeaderF#104]
First of all, this plugin is awesome! Thank you for making it. 

I just have a quick question. I want to swap the mappings of 'x' (split) with 's' (selection). How can I do that?

**Comment by Yggdroot** [comment]
```
    let g:Lf_NormalMap = {
        \ "File":   [["s", ":exec g:Lf_py 'fileExplManager.accept(''h'')'<CR>"],
        \            ["x", ":exec g:Lf_py 'fileExplManager.addSelections()'<CR>"]
        \           ]
        \}
```
You can refer to https://github.com/Yggdroot/LeaderF/blob/2b9bf8170c0aae14012a61ad7d7d6bcea9c83c7e/doc/leaderf.txt#L425-L444 for more detail.
