### ISSUE TITLE
How to include files in files list, even if they are in gitignore

### ISSUE THREAD

**Issue by johnnadratowski** [Yggdroot/LeaderF#1043]
This is a feature request.

I always have my `.env` file in  gitignore, as it contains passwords.  However, I can never search for it now using the leaderf `file` command.  I am requesting a way for leaderf to have an "includes" option.  Perhaps a `.leaderf-include` file.

**Comment by Yggdroot** [comment]
Use `Leaderf file --no-ignore`.

**Comment by johnnadratowski** [comment]
The main problem with that is, for javascript projects, I get so many results from .node-modules.  I was hoping to be able to keep those results off the list.

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/2c85c8b160fb13d8af4fac3efbd6d48badf146cf/doc/leaderf.txt#L141-L165

You can set this option to exclude .node-modules.

**Comment by johnnadratowski** [comment]
Ah that's great!  I thought that no-ignore would include wildignore.  Thanks!
