### ISSUE TITLE
关于leader gtags -g 结果的正则表达式(不是bug,只是想确认正则相关信息)

### ISSUE THREAD

**Issue by fzhzhen1987** [Yggdroot/LeaderF#1044]
使用的以下命令
`noremap <silent> <A-p> :<C-U><C-R>=printf("Leaderf gtags -g %s --auto-jump", expand("<cword>"))<CR><CR>`

正则表达式可以在结果中筛选出.c文件或者.h文件的结果吗? 
或者是针对某个文件名的文件的结果

而且正则表达关系 不能使用 + 和 ?的扩展吧?
+：匹配前面的子表达式一次或多次。
?：匹配前面的子表达式零次或一次。

leaderf的正则功能有列表么 想确认一下

**Comment by Yggdroot** [comment]
建议使用Leaderf rg
