### ISSUE TITLE
relativenumber, 无法相对跳转, 并报错: E481: No range allowed

### ISSUE THREAD

**Issue by persytry** [Yggdroot/LeaderF#1049]
我在`init.vim`配置中有这么一行配置，用来启用leaderf窗口的relativenumber效果：`autocmd FileType leaderf setlocal relativenumber`.
我在leaderf窗口中，想要相对当前行号的跳转，比如`2j`,`3k`之类的，会有这样的报错：`E481: No range allowed`, 如下图所示：
![image](https://github.com/Yggdroot/LeaderF/assets/88146305/3a210f62-d564-4ba9-b2cc-e2e5004f0339)
希望作者百忙中能够解决这个问题， 谢谢

**Comment by Yggdroot** [comment]
可以加个map，
```vim
let g:Lf_NormalMap = {
        \ "Function":[
        \              ["j", 'j:exec g:Lf_py "functionExplManager._previewResult(True)"<CR>']
        \              ["k", 'k:exec g:Lf_py "functionExplManager._previewResult(True)"<CR>']
        \            ]
        \}
```
相应的别的也可以加上。

**Comment by persytry** [comment]
谢谢，按您的方式处理，问题已解决

**Comment by Yggdroot** [comment]
现在不用workaround也可以了。
