### ISSUE TITLE
Feature request: List all buffers in current tab

### ISSUE THREAD

**Issue by mechkb** [Yggdroot/LeaderF#105]
Hello,

I've a small feature request. Could we have a command similar to LeaderfBuffer called something like LeaderfTabBuffer which only lists the buffers in the current tab. May be the 's:buftabs()' function described here (https://github.com/kien/tabman.vim/blob/master/autoload/tabman.vim) could be used to make such a list. 

Thank you.

**Comment by Yggdroot** [comment]
Added.

**Comment by mechkb** [comment]
Thank you so much!

**Comment by mechkb** [comment]
Unfortunately, the LeaderfTabBufferAll option is not working and is behaving the same as LeaderfTabBuffer and only showing the visible buffers in the tab window  (not the hidden ones).

**Comment by Yggdroot** [comment]
It works as designed. It shows the buffers `in current tabpage`. LeaderfTabBuffer won't show unlisted buffer, LeaderfTabBufferAll will, if all the buffers are listed buffer, they are the same.

**Comment by mechkb** [comment]
I see. Thank you. Closing.
