### ISSUE TITLE
No feedback when there is a permission denied

### ISSUE THREAD

**Issue by dreamerlzl** [Yggdroot/LeaderF#1052]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:  NVIM v0.9.4
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Currently, it seems that once there's a file/directory the current user has no access to, `Leaderf! rg` will fail to find any matches in other files which are actually accessible.

### Steps to reproduce
1. Under a directory say `test`, create a file/dir that the current user can not read (say, `drwx------` and owned by root)
2. Also, create a text file like `echo hello > a.txt` under `test`
3. Open neovim under `test` and try to use `Leaderf! rg`, no matter what input you give, no results or errors would be shown. 

### Actual behaviour
No output at all, users don't know what have happened.

### Expected behaviour
Any error message or help info so that users can know there is a permission issue.

**Comment by dreamerlzl** [comment]
and if you directly type rg under `test`, you can clearly see there is a permission denied error while the matches for other accessiable files are still working

**Comment by Yggdroot** [comment]
Can not reproduce.
I can always get 
```
Messages maintainer: The Vim Project                                                                                                                                                         
File "/home/yggdroot/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 698, in input^@    callback()^@  File "/home/yggdroot/.vim/plugged/LeaderF/autoload/leaderf/python/le
aderf/manager.py", line 70, in deco^@    func(self, *args, **kwargs)^@  File "/home/yggdroot/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2852, in _workInIdle^@   
 raise self._read_content_exception[1]^@  File "/home/yggdroot/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2825, in _readContent^@    for line in content:^@  File
 "/home/yggdroot/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 209, in __next__^@    return next(self._g)^@  File "/home/yggdroot/.vim/plugged/LeaderF/autoloa
d/leaderf/python/leaderf/asyncExecutor.py", line 106, in read^@    raise Exception(lfBytes2Str(err) + lfBytes2Str(err, encoding))^@Exception: test.txt: Permission denied (os error 13)^@test
.txt: Permission denied (os error 13)
```

**Comment by dreamerlzl** [comment]
ok, sorry for the bothering. It seems that this error is a `kind: echo` message defined by `:h ui-messages` and is filtered out by my [noice](https://github.com/folke/noice.nvim) plugin.

**Comment by dreamerlzl** [comment]
Still, can we show other matches despite the permission denied error? 
Because if you execute the `rg` in terminal outside neovim, it will still show other accessible matches.

**Comment by Yggdroot** [comment]
Add `--no-messages`.
