### ISSUE TITLE
Help buffers are not seen in `buffer` mode

### ISSUE THREAD

**Issue by eyalk11** [Yggdroot/LeaderF#1053]
- vim or neovim? 
    - [ ] vim
    - [ X] neovim
- Output of `vim --version` or `nvim --version`: 

NVIM v0.9.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe /MD /Zi /O2 /Ob1  -W3 -wd4311 -wd4146 -DUNIT_TESTING -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_WIN32_WINNT=0x0602 -DMSWIN -DINCLUDE_GENERATED_DECLARATIONS -ID:/a/neovim/neovim/.deps/usr/include/luajit-2.1 -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include -ID:/a/neovim/neovim/build/cmake.config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include -ID:/a/neovim/neovim/.deps/usr/include

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [X ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

Irrelevant
### Describe your question, feature request, or bug.

Using `Leaderf --popup buffer` , any help buffers are not present . Those are the buffer found by help. 
I understand that `:buffers` doesn't display them as well. I have countless of times reopened buffers because of this. 
They do have buffer number.

### Steps to reproduce
1. :help winid 
2. Leaderf --popup buffer

### Actual behaviour
can't find help buffer

### Expected behaviour

To be found.

**Comment by eyalk11** [comment]
Interesting . It does work with `Leaderf window` .

**Comment by Yggdroot** [comment]
`:Leaderf buffer --all`
