### ISSUE TITLE
g:Lf_Rg配置似乎不生效

### ISSUE THREAD

**Issue by NasdaqGodzilla** [Yggdroot/LeaderF#1054]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 18 2023 09:20:34)
Included patches: 1-1453, 3625, 3669, 3741`
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
<img width="311" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/26323326/fb4ba8f1-b116-43e2-be48-54c8649720fb">

### Describe your question, feature request, or bug.
设置g:Lf_Rg后，没有生效，仍然使用默认的rg命令。在vim内部:echo g:Lf_Rg确认已经设置成功了

**Comment by Yggdroot** [comment]
怎么知道没生效？

**Comment by NasdaqGodzilla** [comment]
> 怎么知道没生效？

我使用如下配置后，重新打开vim窗口并执行:PlugInstall，调用Rg搜索仍然能正常搜索，预期应该是无法搜索的。
`let g:Lf_Rg = 'ls'`

**Comment by NasdaqGodzilla** [comment]
经过排查发现，“调用Rg搜索”，实际上调用的不是LeaderF，而是fzf，不是问题
