### ISSUE TITLE
LeaderF触发nvim cpu loading 异常

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#1056]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.10.0-dev-2445+g2e1f5055a
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.8.10
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
LeaderfFile 打开后不需搜索，即有如下CPU占用的异常。其他LeaderF功能也可能导致此问题，并未全部测试。关闭Leaderf后cpu loading恢复正常。
更早的nvim版本CPU直接占满，界面卡住。此版本固定占用20%左右的CPU。 
![图片](https://github.com/Yggdroot/LeaderF/assets/8309631/718f6a6e-ec3d-4496-b5e6-64679dbc3c09)

### Steps to reproduce
LeaderfFile
### Actual behaviour
cpu占用异常
### Expected behaviour
打开Leaderf不应该引发性能问题。

**Comment by xaljer** [comment]
[runtime/lua/vim/provider/python.lua](https://github.com/neovim/neovim/blob/0fcbda59871ebc5fc91cac7fa430a4a93f6698c2/runtime/lua/vim/provider/python.lua#L107)

**Comment by Yggdroot** [comment]
这个问题是实现决定的，因为vim不支持多线程，所以加了个轮询机制来空转。
可以设置`let g:Lf_NoAsync = 1`。

**Comment by xaljer** [comment]
> 这个问题是实现决定的，因为vim不支持多线程，所以加了个轮询机制来空转。 可以设置`let g:Lf_NoAsync = 1`。

这样设置有什么其他的影响吗？

**Comment by Yggdroot** [comment]
> > 这个问题是实现决定的，因为vim不支持多线程，所以加了个轮询机制来空转。 可以设置`let g:Lf_NoAsync = 1`。
> 
> 这样设置有什么其他的影响吗？

有时候可能搜不到结果，或者结果不完整。
不过10万以内个文件应该没什么问题。

**Comment by xaljer** [comment]
> 
> 有时候可能搜不到结果，或者结果不完整。 不过10万以内个文件应该没什么问题。



> > > 这个问题是实现决定的，因为vim不支持多线程，所以加了个轮询机制来空转。 可以设置`let g:Lf_NoAsync = 1`。
> > 
> > 
> > 这样设置有什么其他的影响吗？
> 
> 有时候可能搜不到结果，或者结果不完整。 不过10万以内个文件应该没什么问题。

这个问题好像也不是必现的？是新版本的Leaderf才会有还是新版本的neovim才会有？
我日常的工作环境有超过120万个文件……不过一直用的比较旧版本的LeaderF。

**Comment by xaljer** [comment]
> 
> 有时候可能搜不到结果，或者结果不完整。 不过10万以内个文件应该没什么问题。



> > > 这个问题是实现决定的，因为vim不支持多线程，所以加了个轮询机制来空转。 可以设置`let g:Lf_NoAsync = 1`。
> > 
> > 
> > 这样设置有什么其他的影响吗？
> 
> 有时候可能搜不到结果，或者结果不完整。 不过10万以内个文件应该没什么问题。

这个问题好像也不是必现的？是新版本的Leaderf才会有还是新版本的neovim才会有？
我日常的工作环境有超过120万个文件……不过一直用的比较旧版本的LeaderF。

**Comment by Yggdroot** [comment]
leaderf的逻辑一直没变。

**Comment by Yggdroot** [comment]
修复了。
