### ISSUE TITLE
关于Leaderf git的一个小建议

### ISSUE THREAD

**Issue by fzhzhen1987** [Yggdroot/LeaderF#1058]
看你一直在维护这个插件，辛苦了。

看到已经可以支持git的命令。
如果 git diff的执行结果可以用颜色区分 “添加行”和“删除行”就完美了。

**Comment by Yggdroot** [comment]
不是很明白，能具体一点吗？方便的话可以上个图。
是哪个命令？
我觉得已经有了吧。如果是side-by-side模式，就是vimdiff本身的语法高亮，应该已经区分了。如果是普通模式，也是vim的diff文件语法高亮。

**Comment by fzhzhen1987** [comment]
两个测试例：一个没有颜色，一个报错(平台为window powershell nvim)
- Leaderf git diff --side-by-side

![Snipaste_2024-03-06_11-35-03](https://github.com/Yggdroot/LeaderF/assets/40282264/5bcc706d-ff50-41e4-8f4d-38eba284cb01)

- Leaderf git diff --side-by-side --current-file

![Snipaste_2024-03-06_11-36-52](https://github.com/Yggdroot/LeaderF/assets/40282264/62d852cc-6108-4d2d-92ac-227f0c6d5ec2)

- 我对文件做的修改

![Snipaste_2024-03-06_11-38-44](https://github.com/Yggdroot/LeaderF/assets/40282264/c292a1a1-8cf0-4369-86b9-b163376be370)

**Comment by Yggdroot** [comment]
正常是有颜色的，不知道是不是你的环境的问题。
你在normal模式下，focus到previewbuffer，`echom &ft` 看看输出是什么。
在这个buffer里设值`set ft=diff`, 看看有没有颜色。

至于报错，我看是E97，
```
						*E810* *E97*
Vim will do a test if the diff output looks alright.  If it doesn't, you will
get an error message.  Possible causes:
-  The "diff" program cannot be executed.
-  The "diff" program doesn't produce normal "ed" style diffs (see above).
-  The 'shell' and associated options are not set correctly.  Try if filtering
   works with a command like ":!sort".
-  You are using 'diffexpr' and it doesn't work.
If it's not clear what the problem is set the 'verbose' option to one or more
to see more messages.

The self-installing Vim for MS-Windows includes a diff program.  If you don't
have it you might want to download a diff.exe.  For example from
http://gnuwin32.sourceforge.net/packages/diffutils.htm.
```
看看是不是上面提到的某个原因。

**Comment by fzhzhen1987** [comment]
回头我试试其他设备。

又有个问题
一打开文件，报错，不过不影响使用.不知道是不是我的环境问题。

`nvim xxx.c`

就报下面的错
```shell
BufEnter Autocommands for "*"..function lfMru#record の処理中にエラーが検出されました:
line   10:
E684: List index out of range: 2
```

**Comment by Yggdroot** [comment]
> 回头我试试其他设备。
> 
> 又有个问题 一打开文件，报错，不过不影响使用.不知道是不是我的环境问题。
> 
> `nvim xxx.c`
> 
> 就报下面的错
> 
> ```shell
> BufEnter Autocommands for "*"..function lfMru#record の処理中にエラーが検出されました:
> line   10:
> E684: List index out of range: 2
> ```

这个是最基本功能了，是Leaderf mru用到的。感觉不会有错。你的nvim版本是多少，是不是太旧了。
为什么你的报错都是日文的。

**Comment by fzhzhen1987** [comment]
version: NVIM v0.10.0-dev-2051+gee3d4f6b9
因为用的日语编码的格式...我试了用utf-8就没事。
傻逼日语编码sjis就报上面那个错

**Comment by fzhzhen1987** [comment]
> 正常是有颜色的，不知道是不是你的环境的问题。 你在normal模式下，focus到previewbuffer，`echom &ft` 看看输出是什么。 在这个buffer里设值`set ft=diff`, 看看有没有颜色。
> 
> 至于报错，我看是E97，
> 
> ```
> 						*E810* *E97*
> Vim will do a test if the diff output looks alright.  If it doesn't, you will
> get an error message.  Possible causes:
> -  The "diff" program cannot be executed.
> -  The "diff" program doesn't produce normal "ed" style diffs (see above).
> -  The 'shell' and associated options are not set correctly.  Try if filtering
>    works with a command like ":!sort".
> -  You are using 'diffexpr' and it doesn't work.
> If it's not clear what the problem is set the 'verbose' option to one or more
> to see more messages.
> 
> The self-installing Vim for MS-Windows includes a diff program.  If you don't
> have it you might want to download a diff.exe.  For example from
> http://gnuwin32.sourceforge.net/packages/diffutils.htm.
> ```
> 
> 看看是不是上面提到的某个原因。

`echom &ft`  显示c
改成diff后 还是没有颜色.

**Comment by Yggdroot** [comment]
我认为这不是LeaderF的问题，而是你的环境的问题，你直接打开一个diff文件应该也没有颜色。

**Comment by fzhzhen1987** [comment]
> > 回头我试试其他设备。
> > 又有个问题 一打开文件，报错，不过不影响使用.不知道是不是我的环境问题。
> > `nvim xxx.c`
> > 就报下面的错
> > ```shell
> > BufEnter Autocommands for "*"..function lfMru#record の処理中にエラーが検出されました:
> > line   10:
> > E684: List index out of range: 2
> > ```
> 
> 这个是最基本功能了，是Leaderf mru用到的。感觉不会有错。你的nvim版本是多少，是不是太旧了。 为什么你的报错都是日文的。

发现在v1.25中就是有这个错误,在v1.24就没有报错。
具体哪个commit修改导致的问题没有具体找。

**Comment by Yggdroot** [comment]
如果你那里是必现的话，帮忙调试一下这个函数：

https://github.com/Yggdroot/LeaderF/blob/735a2f36d3a25e320182bf3f385f5530d674600e/autoload/lfMru.vim#L30-L54

看看具体为什么。
