### ISSUE TITLE
[HELP WANTED] error when called  the ' leaderf#Rg#NormalModelFilter '

### ISSUE THREAD

**Issue by xm-tech** [Yggdroot/LeaderF#1063]
处理 function leaderf#Gtags#NormalModeFilter 时发生错误:
第    1 行:
E859: 无法将返回的 Python 对象转换为 Vim 值, as below:

![截屏2024-04-16 16 52 57](https://github.com/Yggdroot/LeaderF/assets/31558853/2ee9d8f0-b3bc-48a3-b784-f15c80c4b0a2)

the error occurred at the function leaderf#Rg#NormalModeFilter
so i try to update the function as below:

![截屏2024-04-16 17 23 54](https://github.com/Yggdroot/LeaderF/assets/31558853/c1dc7e95-1d13-4c72-92f0-795b8b14e27a)
which displays:
![截屏2024-04-16 17 25 11](https://github.com/Yggdroot/LeaderF/assets/31558853/c6bd7897-8c54-4bc5-a4e8-79af6cfc096d)

why `winid` and `key` here is not defined

i displayed the value of variables:  g:Lf_PyEval && g:Lf_Py
`:echo g:Lf_PyEval`  output :  `py3eval`

while 
`:echo g:Lf_Py`  output:   `E121: 未定义的变量: g:Lf_Py`

my env: 
-------

vim:  9.0.2121
os:  Linux raspberrypi 6.5.0-1013-raspi #16-Ubuntu SMP PREEMPT Thu Mar 14 15:47:52 UTC 2024 armv7l armv7l armv7l GNU/Linux
python:  Python 3.11.6

**Comment by Yggdroot** [comment]
If you want to access the function arguments, you should use a:xxx, here you should use a:winid.

**Comment by xm-tech** [comment]
> If you want to access the function arguments, you should use a:xxx, here you should use a:winid.

thanks for reply 🤝, 
i just changed the function as below: 

![截屏2024-04-16 18 51 47](https://github.com/Yggdroot/LeaderF/assets/31558853/0b0a8d25-3272-42cf-924f-628640c0b088)

it plays well, no error . 

but this will play error : 

![截屏2024-04-16 18 55 38](https://github.com/Yggdroot/LeaderF/assets/31558853/6cd53923-3db3-4a39-8b0b-dd5ff79c27f9)

and this will error, and cause the vim exited, which report error below: 

![截屏2024-04-16 18 57 20](https://github.com/Yggdroot/LeaderF/assets/31558853/57281734-ebc5-44a5-becf-e3df268b7771)

**Comment by Yggdroot** [comment]
How to reproduce?

**Comment by xm-tech** [comment]
> How to reproduce?


i think it is hard to reproduce the error,  as there are too many env deps, 

but still , hope u can try to help me to figure out, and below is my install script :

https://github.com/xm-tech/dotfiles-ubuntu.git

```
make install
```

**Comment by xm-tech** [comment]
@Yggdroot 
chinese ? 在上海 ？

如果是的话，我可以过来拜访😄

**Comment by Yggdroot** [comment]
没错，中国人。

**Comment by Yggdroot** [comment]
> > How to reproduce?
> 
> i think it is hard to reproduce the error, as there are too many env deps,
> 
> but still , hope u can try to help me to figure out the problem. below is my install script :
> 
> https://github.com/xm-tech/dotfiles-ubuntu.git
> 
> ```
> make install
> ```

具体我不知道你是在什么情况下出现的这个错误。

试试 如下：
vimrc
```vim

set encoding=utf-8
syntax enable
set nocompatible


"{{{
filetype on  
"}}}

set runtimepath^=~/.vim/plugged/LeaderF

```

vim -u vimrc

然后执行你要执行的命令。
