### ISSUE TITLE
使用Lf_PopupPreviewPosition = 'top'时提示Pattern not found: Lf_PopupPreviewPosition = 'top'

### ISSUE THREAD

**Issue by Kaiser-Yang** [Yggdroot/LeaderF#1064]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 10 2022 08:40:37)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim):  no output
- Output of `:echo &pythonthreedll`(only vim, not neovim):  no output
- Output of `:py print(sys.version)`: not work
- Output of `:py3 print(sys.version)`: 3.8.10 (default, Nov 22 2023, 10:22:35) [GCC 9.4.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux (wsl2)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/5d46736e-2a17-401c-b25e-c879b461f06c)

source leaderf_config after source vimplug_config

![image](https://github.com/Yggdroot/LeaderF/assets/58209855/53ffeaa1-0d33-4822-852b-e2b2b5912cf2)

### Describe your question, feature request, or bug.
当我启动vim时，提示我：
```
Pattern not found: Lf_PopupPreviewPosition = 'top'
Press ENTER or type command to continue
```

### Steps to reproduce
配置完后启动vim时。

### Actual behaviour
preview window依然在右侧：
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/c8eb72a8-3ef5-40df-8419-ad1394e5a4ad)

### Expected behaviour
希望将preview window移动到搜索栏的上侧。

**Comment by Kaiser-Yang** [comment]
Translation：
I cannot use `^J` and `^K` to navigate when leaderf is on.
When I use `Lf_PopupPreviewPosition = 'top'`, every time I launch vim, it gives me:
```
Pattern not found: Lf_PopupPreviewPosition = 'top'
Press ENTER or type command to continue
```
My  configure files are pinned above.

**Comment by Kaiser-Yang** [comment]
It is worth noting that I can navigate through <up> and <down>.
值得一提的是，我可以通过上下键进行导航。

**Comment by Kaiser-Yang** [comment]
我已经解决了第一个问题，我发现当我将`let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}`这一行的配置移除后，我便可以通过^J和^K进行导航了。

因为我在leaderf主页的usage部分发现^J和^K已经在默认的配置里了：
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/37d34cc1-6994-4cb0-9168-13f3195bdf96)

所以我猜测是我的更改行为发生了冲突，当我去掉这行后，我可以通过^J和^K进行导航，因此我建议将自定义配置部分的例子进行更换：
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/0c064f9f-2a3e-446f-8ab5-292e31e9b855)

I've already solve the first problem. Now I can use ^J and ^K to navigate after I remove `let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}` in my configure file.

I found this in main page of leaderf: ^J and ^k have already been hotkey for navigate in default.

So I suggest to change the example of Customization part of main page's guide.

**Comment by Yggdroot** [comment]
`let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}`
的意思是把默认的键c-k 变成 up，map后，up有c-k的功能，而c-k失效了。
如果想让两个同时有效，`let g:Lf_CommandMap = {'<C-K>': ['<Up>', '<C-K>'], '<C-J>': ['<Down>']}`, 所以文档没错。

**Comment by Kaiser-Yang** [comment]
> `let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}` 的意思是把默认的键c-k 变成 up，map后，up有c-k的功能，而c-k失效了。 如果想让两个同时有效，`let g:Lf_CommandMap = {'<C-K>': ['<Up>', '<C-K>'], '<C-J>': ['<Down>']}`, 所以文档没错。

好像是我读错了，文档确实没错。那么请问第二个问题是什么原因呢？

**Comment by Yggdroot** [comment]
> Pattern not found: Lf_PopupPreviewPosition = 'top'
> Press ENTER or type command to continue

是这个问题吗？
不知道为什么启动vim就有这个问题，启动时好像跟LeaderF没关系。
也就是`let g:Lf_PopupPreviewPosition = 'top'` 会报错太奇怪了。

vimrc
```vim
set encoding=utf-8
syntax enable
set nocompatible

"{{{
filetype on  
"}}}

set runtimepath^=~/.vim/plugged/LeaderF
let g:Lf_PopupPreviewPosition = 'top'
```

vim -u vimrc 
这样试一下。

**Comment by Kaiser-Yang** [comment]
> > Pattern not found: Lf_PopupPreviewPosition = 'top'
> > Press ENTER or type command to continue
> 
> 是这个问题吗？ 不知道为什么启动vim就有这个问题，启动时好像跟LeaderF没关系。 也就是`let g:Lf_PopupPreviewPosition = 'top'` 会报错太奇怪了。
> 
> vimrc
> 
> ```viml
> set encoding=utf-8
> syntax enable
> set nocompatible
> 
> "{{{
> filetype on  
> "}}}
> 
> set runtimepath^=~/.vim/plugged/LeaderF
> let g:Lf_PopupPreviewPosition = 'top'
> ```
> 
> vim -u vimrc 这样试一下。

前四行在我的.vimrc文件中本身存在，因此我只增加了倒数第二行，位置在我source插件配置文件之前，ruxx如下图所示：
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/0997df50-3702-4c6e-afd4-940c1601d7da)

即使是这样，我依然会得到同样的报错

**Comment by Kaiser-Yang** [comment]
刚刚进行了测试输入中文句号后，可以键入其他字母，但只要输入y就会出现相同的错误，例如我输入`。abc`，此时一切正常，但当我输入`y`，便产生了同样的报错信息。

**Comment by Yggdroot** [comment]
首先，用我的最小vimrc应该没有问题，然后你再慢慢加上你的source xxx，看看问题出在哪里。

**Comment by Kaiser-Yang** [comment]
> 首先，用我的最小vimrc应该没有问题，然后你再慢慢加上你的source xxx，看看问题出在哪里。

我已经注释了我的所有vim配置，只留下了：
```vim
set nocompatible
filetype on
scriptencoding utf-8
set encoding=utf-8
syntax on
set runtimepath^=~/.vim/plugged/LeaderF
source ~/.vim/vim_plugin_config/vimplug_config.vim
source ~/.vim/vim_plugin_config/leaderf_config.vim
```
并且我的vimplug_config.vim中我也只留下了：
```vim
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
call plug#end()
```
我的leader_config.vim保持不变，此时依然会出现同样的错误：
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/f9e77dde-8045-4b12-8db9-7971c3f1fbf1)

![image](https://github.com/Yggdroot/LeaderF/assets/58209855/5ff93b99-4615-494f-8a39-1ce23ff02437)
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/6bd40e43-7be8-4662-bf2a-d298a3e48d24)
![image](https://github.com/Yggdroot/LeaderF/assets/58209855/1d07627d-6550-4ac9-aae8-b16feffcbd4b)

**Comment by Kaiser-Yang** [comment]
好吧，我已经找到问题了，我把let写成了leg

**Comment by Kaiser-Yang** [comment]
> 首先，用我的最小vimrc应该没有问题，然后你再慢慢加上你的source xxx，看看问题出在哪里。

我已经找到问题了，我把let写成了leg，非常抱歉浪费了你宝贵的时间，谢谢你的耐心解答。

**Comment by Yggdroot** [comment]
> 好吧，我已经找到问题了，我把let写成了leg

![image](https://github.com/Yggdroot/LeaderF/assets/2705841/a5cbda9d-9182-4142-af81-bb976f5375d6)
