### ISSUE TITLE
让 leaderf git 支持多个git 仓库

### ISSUE THREAD

**Issue by keeferwu** [Yggdroot/LeaderF#1066]
可否优化一下 Leaderf git 使其能够适应多个 git 仓库

例如有如下结构：
```
root_git
---  .git
---  aaa.c
---  sub1_git
	 --- .git
	 --- bbb.c
---  sub2_git
	 --- .git
	 --- ccc.c 
```
在 root_git 下打开bbb.c 或 ccc.c 使用Leaderf git log 就只能看到 root_git 下的log

目前的行为好像是显示当前工作目录下对应git仓库的log

能否做到不切换目录的情况下使用Leaderf git log 可以显示子仓库的log，

比如可以根据当前buffer 向上查找最近的.git，找到后就显示其对应仓库的log

或者命令中提供一个可以选择路径的选项，由用户自己决定查看哪个仓库

**Comment by Yggdroot** [comment]
等有时间考虑一下，看看怎么实现。

**Comment by Yggdroot** [comment]
现在可以根据当前buffer 向上查找最近的.git了。
