### ISSUE TITLE
Regex mode of Leaderf rg matching result is unexpected

### ISSUE THREAD

**Issue by bbchung** [Yggdroot/LeaderF#1067]
- vim or neovim? 
    - [ x] vim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled May  1 2024 13:13:20)
Included patches: 1-384
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1

### Describe your question, feature request, or bug.
use `:Leaderf rg` with regex mode should not match with file name

### Steps to reproduce
when there is a file named "item.cpp" under folders, use `:Leaderf rg` then type `is.*ok`(regex mode)
### Actual behaviour
the "i" of item.cpp will be matched

### Expected behaviour
the "i" of item.cpp should not be matched

**Comment by Yggdroot** [comment]
![image](https://github.com/Yggdroot/LeaderF/assets/2705841/02db3644-d93a-45e5-b0eb-dc0a3515556d)

i is not matched.

**Comment by bbchung** [comment]
There are 2 txt files, both have single line `enough`
![image](https://github.com/Yggdroot/LeaderF/assets/3892170/b9823095-a6c2-48ae-ab61-95d2a58134a4)
![image](https://github.com/Yggdroot/LeaderF/assets/3892170/24fe5d39-7b4a-4c75-8479-425a198c2a61)
![image](https://github.com/Yggdroot/LeaderF/assets/3892170/6282eceb-93bc-448d-8a0f-7747e72ccea5)
![image](https://github.com/Yggdroot/LeaderF/assets/3892170/5b37cd93-a88a-4499-913a-95df2c16f965)

The last image show that when I insert `is.*enough` match the line in is.txt, it should be a unexpected matching?

**Comment by Yggdroot** [comment]
Oh, it works as disigned.  It's better not use the regex mode, use the fuzzy mode instead.
