### ISSUE TITLE
Not seeing files in the list of LeaderfFile

### ISSUE THREAD

**Issue by phuongnd08** [Yggdroot/LeaderF#1068]
This is what I see:

<img width="589" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/184037/419fda8b-ad34-4b29-bc01-f84cf477271e">

- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  `NVIM v0.9.5`
- Output of `:echo has("python")`:  `0`
- Output of `:echo has("python3")`:  `1`
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`:  `3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]`
- Output of `:echo g:Lf_Debug_Cmd`: `git ls-files  "." && git ls-files --others --exclude-standard  "."`
- Output of `:echo g:Lf_FilesFromCache`: `1`
- Operating system: 
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

Not see files when invoke :LeaderfFile

### Steps to reproduce
Invoke :LeaderfFile
### Actual behaviour
<img width="589" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/184037/419fda8b-ad34-4b29-bc01-f84cf477271e">

### Expected behaviour
Showing some files

**Comment by phuongnd08** [comment]
After running the debug command, I see git ls-files and look like LeaderF expect the files to be in git history. So I commit the files to git and see it populates. However this is not my wanted behavior. Not sure how did git ls-files is used here. Would not see files unless they were committed to git.

**Comment by Yggdroot** [comment]
let g:Lf_UseVersionControlTool=0

**Comment by phuongnd08** [comment]
That solves the problem. Though I wonder why it's not by default. Make me pull my hair for a while.
