### ISSUE TITLE
LeaderF uses Ctrl+C to quit which will interrupt jobs/timer's callbacks by mistake.

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#107]
LeaderF requires user to press ctrl-c when they want to close the search window. and sometimes ctrl-c will easily be pressed by mistake and will interrupt a timer callback. or other job callbacks running at the same time.

All the internal state of timers/jobs messed up because of a single unexpected ctrl+c. Ctrl+C is not encouraged in daily usage. Can leaderf use a different key to quit ? like ctrlp just a single ESC ?

**Comment by Yggdroot** [comment]
You can refer to below:
https://github.com/Yggdroot/LeaderF/blob/b54d8b9ced89924b2ff2d928aa4de3bb1e78f7e1/doc/leaderf.txt#L472-L478
Or the Readme.
The readme says: 
Change key bindings

```
By default, <ESC> is the shortcut key to switch to normal mode, if you want to change it to be 'Quit from LeaderF':

let g:Lf_CommandMap = {'<C-C>': ['<Esc>', '<C-C>']}
```

**Comment by skywind3000** [comment]
That makes sense, I love this option.
