### ISSUE TITLE
git blame help has some error in neovim

### ISSUE THREAD

**Issue by keeferwu** [Yggdroot/LeaderF#1070]
在neovim 中 git blame window 使用 F1 查看帮助时出现错误：
![image](https://github.com/Yggdroot/LeaderF/assets/61483526/fd3b0157-0843-45ab-baef-36752c929a67)

**Comment by Yggdroot** [comment]
You'd better use the latest nvim.

**Comment by keeferwu** [comment]
neovim 更新到 V0.9.4， 问题解决

**Comment by keeferwu** [comment]
neovim 更新到 V0.9.4， 问题解决

**Comment by Yggdroot** [comment]
> neovim 更新到 V0.9.4， 问题解决

如果更新到0.10.0，就会支持unified diff view。
