### ISSUE TITLE
after update  git blame exists errors

### ISSUE THREAD

**Issue by keeferwu** [Yggdroot/LeaderF#1073]
插件更新后 git blame 有错误
回退到 7c60ba4c6f6803ade667f4b463dcdb1d169c7c54 没有问题

:LeaderfGit
![image](https://github.com/Yggdroot/LeaderF/assets/61483526/5edca2a1-1687-40fd-bf72-b0d84bdc39f3)

:Leaderf git blame
![image](https://github.com/Yggdroot/LeaderF/assets/61483526/bdd6f173-180f-48dd-af19-fe3157a37c3f)

**Comment by Yggdroot** [comment]
出错的是哪个版本？
Python版本？
vim还是nvim？

**Comment by keeferwu** [comment]
vim还是nvim？---> 都有问题
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 10 2022 08:40:37)
NVIM v0.10.0

Python版本?   ---->
python --version
Python 2.7.18
python3 --version
Python 3.8.10

**Comment by Yggdroot** [comment]
首先，更新到最新版试一下，这段代码应该没有了。

要设置let g:Lf_PythonVersion = 3，你的机器默认跑的是Python2，现在leaderf的代码不在Python2上测了，Python2上能跑是惊喜，不能跑正常。

**Comment by keeferwu** [comment]
更新到最新，问题仍然存在

**Comment by Yggdroot** [comment]
修复了。

**Comment by keeferwu** [comment]
好了，感谢
