### ISSUE TITLE
LeaderF requires Vim compiled with python and/or a compatible python version.

### ISSUE THREAD

**Issue by chenghua-root** [Yggdroot/LeaderF#1074]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:
    - VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jun  5 2024 17:56:40)
    - Included patches: 1-466
    - Compiled by chenghua@n31-144-029 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
https://vi.stackexchange.com/questions/11526/how-to-enable-python-feature-in-vim

**Comment by chenghua-root** [comment]
compile vim source code with configure --enable-python3interp=yes
