### ISSUE TITLE
Fails to build the C extension under windows

### ISSUE THREAD

**Issue by pedrohgmacedo** [Yggdroot/LeaderF#1077]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
:Leaderf file -->
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.

Running the command to install the C extension does not work. 
After installing the build tools for vistual studio 2022, the install.bat must be running under the environment of `"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvars64.bat"`

**Comment by Yggdroot** [comment]
> Running the command to install the C extension does not work.

Any logs?

**Comment by pedrohgmacedo** [comment]
It complains that the build tools are not installed. What logs are you looking for?
