### ISSUE TITLE
Leaderfbuffer got very slow when some large files open

### ISSUE THREAD

**Issue by zhyzky** [Yggdroot/LeaderF#1079]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  9.0
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`:  3.10.12
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShortcutF = "<Plug>noexistkey"
let g:Lf_ShortcutB = "<Plug>noexistkey"
let g:Lf_WindowPosition = 'popup'
let g:Lf_StlSeparator = { 'left': '', 'right': '' }
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
let g:Lf_WorkingDirectoryMode = 'Ac'

### Describe your question, feature request, or bug.
When vim has several large files (>100M) open, the leaderfbuffer got very slow.
It seems this command would excute some file open operation, while the file already loaded. 

### Steps to reproduce
1. Just load several large files
2. Execute leaderfbuffer and wait

### Actual behaviour
The buffer navigation should not be slower than it is inside vim.

### Expected behaviour
Somooth navigation between buffers.

**Comment by Yggdroot** [comment]
yes, because vim's popup window is not so good. Neovim would be faster.

**Comment by Yggdroot** [comment]
I created an issue https://github.com/vim/vim/issues/15006.

**Comment by zhyzky** [comment]
> yes, because vim's popup window is not so good. Neovim would be faster.

According to vim help, popup_create function allow buffer number being the first parameter. This can speedup the buffer oppenning.
I think the real problerm is when navigate the buffer, getbufline is too slow.

**Comment by Yggdroot** [comment]
I modified the code that we can only preview 4096 lines. This may speedup the preview.

**Comment by zhyzky** [comment]
> I modified the code that we can only preview 4096 lines. This may speedup the preview.

Thanks for your work. But really little speedup.
