### ISSUE TITLE
leaderf git diff 和 git blame 报错

### ISSUE THREAD

**Issue by keeferwu** [Yggdroot/LeaderF#1080]
leaderf git diff ： 第一次按 q 退出窗口会报错

![PixPin_2024-06-15_16-49-41](https://github.com/Yggdroot/LeaderF/assets/61483526/2824c4ce-1e8e-4eb7-beb1-aa6982e2c6ea)

leaderf git blame 报错：

![PixPin_2024-06-15_16-50-41](https://github.com/Yggdroot/LeaderF/assets/61483526/d37b9a8f-b459-43bd-8154-6da7fc301719)

**Comment by Yggdroot** [comment]
第一个问题可能是因为你更新code后，没有重新生成c扩展，需要执行一下`:LeaderfInstallCExtension`， 因为这一次c code 也有改动。
第二个已修复。
