### ISSUE TITLE
`<C-Up>` and `<C-Down>` Keybindings Not Working in Popup Preview Window

### ISSUE THREAD

**Issue by Elite-zx** [Yggdroot/LeaderF#1081]
**Description:**

I am experiencing an issue with the LeaderF plugin where the `<C-Up>` and `<C-Down>` keybindings do not function as expected in the popup preview window. These keybindings are intended to scroll up and down within the popup preview window, but they do not seem to have any effect.

**Steps to Reproduce:**

1. Open Vim with the LeaderF plugin installed.
2. Trigger a LeaderF command that opens a popup preview window.
3. Attempt to use `<C-Up>` to scroll up in the popup preview window.
4. Attempt to use `<C-Down>` to scroll down in the popup preview window.

**Expected Behavior:**

- `<C-Up>` should scroll up within the popup preview window.
- `<C-Down>` should scroll down within the popup preview window.

**Actual Behavior:**

- `<C-Up>` does not scroll up in the popup preview window.
- `<C-Down>` does not scroll down in the popup preview window.

cmd-up will scroll up the entire terminal
cmd-Down will  scroll down the entire terminal

**Environment:**

- Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  1 2021 16:57:56)
- Operating System:  linux (connected by ssh in my macos)

**vimrc**
```
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" LeaderF
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" popup mode
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewHorizontalPosition = 'right'
let g:Lf_WindowPosition = 'popup'
let g:Lf_StlSeparator = { 'left': "\ueb0", 'right': "\ue0b2", 'font': "Monaco Nerd Font Mono" }
let g:Lf_PreviewResult = {'File':1,'Rg':1,'Function': 0, 'BufTag': 0 }
let g:Lf_ShortcutF ='<leader>f'
let g:Lf_ShowDevIcons = 1
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_MaxCount=6000000
" let g:Lf_ReverseOrder = 1

nmap <Leader>r  :Leaderf rg<CR>
nmap <Leader>g :Leaderf gtags<CR>
nmap <C-]> :Leaderf gtags --by-context --auto-jump<CR>
```

**Comment by Yggdroot** [comment]
Is these two keys occupied by your terminal?
You can set them to other keybindings.
`let g:Lf_CommandMap = {'<C-Down>': ['<C-D>']}`

You can give it a try.
