### ISSUE TITLE
Leaderf file  结果可以按照最后修改时间排序吗?

### ISSUE THREAD

**Issue by lwx5924** [Yggdroot/LeaderF#1082]
如题, 使用 Leaderf file <文件夹>, 这个会出来结果.
1. 请问一下这个结果是根据什么排序的? 
2. 结果可以按照最后修改时间排序吗?(或者支持其他,例如文件大小,文件类型等)?

**Comment by Yggdroot** [comment]
结果没有排序，直接拿的后台命令的输出。
不支持排序。
