### ISSUE TITLE
The leaderf popup window won't change its size when opened second time

### ISSUE THREAD

**Issue by zhyzky** [Yggdroot/LeaderF#1083]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 9.0
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.10.12
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShortcutF = "noexistkey"
let g:Lf_ShortcutB = "noexistkey"
let g:Lf_WindowPosition = 'popup'
let g:Lf_StlSeparator = { 'left': '', 'right': '' }
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
let g:Lf_WorkingDirectoryMode = 'Ac'

### Describe your question, feature request, or bug.
When the popup window closed and reopened, its size will remain the same even if vim itself resized.

### Steps to reproduce
First, open a leaderf popup window
Then close the leaderf window
Resize vim window
Reopen leaderf window

### Actual behaviour
Leaderf window should change its size according to vim size

### Expected behaviour
Leaderf window size remains the same
I think it has something todo with manager._is_previewed, that not set to false when closed.

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by Yggdroot** [comment]
> Actual behaviour
> Leaderf window should change its size according to vim size
> 
> Expected behaviour
> Leaderf window size remains the same
> I think it has something todo with manager._is_previewed, that not set to false when closed.

I don't understand what you mean.
What is Actual behaviour and what is Expected behaviour?
