### ISSUE TITLE
只能显示200条结果

### ISSUE THREAD

**Issue by Elite-zx** [Yggdroot/LeaderF#1084]
<img width="777" alt="image" src="https://github.com/Yggdroot/LeaderF/assets/110723979/6ec35a5c-03e9-4853-a74a-d8b6db5cd5cf">

当我选中到第200条结果时，按ctrl-j到下一个结果，没有反应

**Comment by Yggdroot** [comment]
到normal模式下再选。

**Comment by Elite-zx** [comment]
Leaderf Gtags命令在大型项目下太乱了， 能不能根据输入路径筛选

**Comment by Yggdroot** [comment]
> Leaderf Gtags命令在大型项目下太乱了， 能不能根据输入路径筛选

不太清楚你的需求

**Comment by Elite-zx** [comment]
> > Leaderf Gtags命令在大型项目下太乱了， 能不能根据输入路径筛选
> 
> 不太清楚你的需求

比如我有一个大型项目 P, 下面有 a， b ，c 三个目录，这三个目录包含的cpp文件中都包含 标签functionA.   此时我在a目录下打开vim, 执行 leaderF gtags  搜索functionA， 那么会弹出a ，b, c 3个目录下的结果。 我希望此时我输入a，即路径之后，可以筛选出a目录下的functionA.


此外，我是一名高强度的leaderF gtags 使用选手，我发现 使用 --by-context --auto-jump 选项时，对标签的搜索非常快，几乎是秒出结果，而且很准确。 但是我仅仅执行leaderF gtags 并搜索相同的内容时，结果出现的就很慢，而且不准确。这是怎么回事呢？

这个插件非常好用，期待你的解答

**Comment by Yggdroot** [comment]
Leaderf gtags 有个功能，当你输入分号时，分号后面的输入可以匹配路径。比如你的例子，就可以输入`fun;a`来匹配a目录下的functionA。

直接使用Leaderf gtags, 执行的是`global -P | global -L- -f --gtagslabel=default --color=never --result=ctags`，它是把gtags数据库里的所有tags符号解析出来（因为gtags是用二进制存储的，有他自己的一套编解码机制），如果gtags数据库比较大，这个命令会比较耗时。

使用`--by-context --auto-jump`，执行的是`global --gtagslabel=default --from-here "21:/filename.cpp" xxx  --color=never --result=ctags-mod`, 它直接从gtags数据库里找某个tag，显然会更快一些。

**Comment by Elite-zx** [comment]
> Leaderf gtags 有个功能，当你输入分号时，分号后面的输入可以匹配路径。比如你的例子，就可以输入`fun;a`来匹配a目录下的functionA。
> 
> 直接使用Leaderf gtags, 执行的是`global -P | global -L- -f --gtagslabel=default --color=never --result=ctags`，它是把gtags数据库里的所有tags符号解析出来（因为gtags是用二进制存储的，有他自己的一套编解码机制），如果gtags数据库比较大，这个命令会比较耗时。
> 
> 使用`--by-context --auto-jump`，执行的是`global --gtagslabel=default --from-here "21:/filename.cpp" xxx --color=never --result=ctags-mod`, 它直接从gtags数据库里找某个tag，显然会更快一些。

非常感谢你的回答！

**Comment by Elite-zx** [comment]
> Leaderf gtags 有个功能，当你输入分号时，分号后面的输入可以匹配路径。比如你的例子，就可以输入`fun;a`来匹配a目录下的functionA。
> 
> 直接使用Leaderf gtags, 执行的是`global -P | global -L- -f --gtagslabel=default --color=never --result=ctags`，它是把gtags数据库里的所有tags符号解析出来（因为gtags是用二进制存储的，有他自己的一套编解码机制），如果gtags数据库比较大，这个命令会比较耗时。
> 
> 使用`--by-context --auto-jump`，执行的是`global --gtagslabel=default --from-here "21:/filename.cpp" xxx --color=never --result=ctags-mod`, 它直接从gtags数据库里找某个tag，显然会更快一些。

非常感谢你的回答！
