### ISSUE TITLE
Lf_ShortcutF 启动搜索 ，使用MobaXterm  无法右键黏贴所有字符，只会出现第一个字符。使用SecureCRTPortable可以正常黏贴所有字符

### ISSUE THREAD

**Issue by wuguitong** [Yggdroot/LeaderF#1085]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
这个貌似没有解决办法。
