### ISSUE TITLE
Leaderf rg find nothing in case of  spaces in path

### ISSUE THREAD

**Issue by eyalk11** [Yggdroot/LeaderF#1086]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim

- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 

On Windows 10 ! 
```


NVIM v0.10.0-dev-3122+ga0a189a8e
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068
Run ":verbose version" for more info
0
1
3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]





```

I can't believe such a bug goes unnoticed for so long . 
LeaderfInteractive doesn't work with folders in spaces in filename . 
Btw, it also doesn't work in case of UNC paths like `\\192.168.1.1\c$`

e67d7b5286932823b8ba925151402a231ba3b0e6 (last commit I have  ) 
not too old

### Steps to reproduce
```
cd c:\Program Files\Wireshark 
:LeaderfRgInteractive
```
look for html or aa in all files 

### Actual behaviour
find nothing 

### Expected behaviour
finds a lot  (native rg finds) 

Worth to mention that 
```
Leaderf rg aa 
```
does work

**Comment by Yggdroot** [comment]
Can not reproduce it.
What is the output of `echom g:Lf_Debug_RgCmd`?
