### ISSUE TITLE
Some kind of conflict with vim-fswitch

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#109]
I'm using https://github.com/derekwyatt/vim-fswitch as well as LeaderF and when I open the counterpart file, it works, but it's not listed in the buffers when I use `<Leader>B`.

Is there a solution for that?

**Comment by MightyCreak** [comment]
Maybe a solution would be to include a new feature in LeaderF would be able to find the counterpart file.

It's not too far fetch I think since, after all, the goal of LeaderF is to navigate easily in the source code.

**Comment by Yggdroot** [comment]
Can not reproduce it.

**Comment by MightyCreak** [comment]
Hmm.. in which order did you loaded LeaderF and fswitch?

**Comment by Yggdroot** [comment]
Could you show me the exact steps to reproduce the issue?

**Comment by MightyCreak** [comment]
You're right, it works when i try from a freshly opened MacVim window!

But at some point it stop working and the files opened with fswitch don't appear in the buffer window.
That being said, I remember fudging around with this buffer window. It happens, sometime, that I open a file in this buffer window, by mistake, so I kill the window. And maybe it's after this kind of manipulation that I get the faulty behaviour.

I'll try to find the reproduce steps!
