### ISSUE TITLE
如何默认不加载.gitinore文件 ？做到不忽略.gitinore里面指定的文件/文件夹

### ISSUE THREAD

**Issue by jjzqp** [Yggdroot/LeaderF#1093]
master

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  VIM - Vi IMproved 8.1
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
--no-ignore
