### ISSUE TITLE
preview window中的预览代码只能显示4096行，能不能扩大，我的工程中有的文件有1w多行。

### ISSUE THREAD

**Issue by leichen2552** [Yggdroot/LeaderF#1097]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 9.1
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython3.10.s0.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.10.s0.1.0

- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [1 ] Linux
    - [ 1] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
![图像2024-8-25 18 36](https://github.com/user-attachments/assets/017a7f58-35f6-44f6-9781-d583fed1e4ff)

### Expected behaviour

![WechatIMG22](https://github.com/user-attachments/assets/bae9a82e-0d24-44c3-badb-b8ae32f12538)

**Comment by Yggdroot** [comment]
更新一下，现在有2万多行了

**Comment by leichen2552** [comment]
太棒了，已经生效！
