### ISSUE TITLE
Lf_WildIgnore not useful

### ISSUE THREAD

**Issue by chenghua-root** [Yggdroot/LeaderF#1098]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Jun  5 2024 19:48:02)
Included patches: 1-466
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: let g:Lf_WildIgnore={'file':['*.html', '*.txt'],'dir':['3rdparty']}
noremap <leader>rg :<C-U><C-R>=printf("Leaderf! rg -w -e %s --stayOpen", expand("<cword>"))<CR><CR>

### Describe your question, feature request, or bug.
when use ",rg", still find the key word in .html files

**Comment by Yggdroot** [comment]
g:Lf_WildIgnore is only used for `Leaderf file`.
You can use
```vim
 let g:Lf_RgConfig = [
        \ '-g "*.{html,txt}"',
        \ "-g!3rdparty",
    \ ]
```

**Comment by chenghua-root** [comment]
let g:Lf_WildIgnore={'file':['*.html', '*.txt'],'dir':['3rdparty']}   "忽略文件和目录
let g:Lf_RgConfig = ['-g "*.{html,txt}"', "-g!3rdparty"]

",rg" still find PeWritePageTask in *.html files
![image](https://github.com/user-attachments/assets/79c5acbd-8eb7-4952-b395-0e6b189c7a33)
