### ISSUE TITLE
中文路径支持错误

### ISSUE THREAD

**Issue by loseblue** [Yggdroot/LeaderF#11]
leaderF打开中文路径文件夹下文件出错，可以搜索文件名，回车后会创建一个乱码文件。

例如
打开d:\codes\Linux kernal V3.0\Linux内核完全注释V3.0书签版\init\main.c
会新建一个乱码文件。

![leaderf](https://cloud.githubusercontent.com/assets/1415040/5499915/d9ca0f20-8773-11e4-80e2-4f1acf5e3e7f.png)

**Comment by xietren** [comment]
支持中文真好，ctrlp好像不太支持中文？
