### ISSUE TITLE
Suggestion: Remove the Prefix 'Leaderf' from the list that appears in :LeaderfSelf

### ISSUE THREAD

**Issue by mechkb** [Yggdroot/LeaderF#110]
Hello,

Love this plugin. I've a small suggestion. In the LeaderfSelf menu, items appear as:
```
  1 0  LeaderfFile             "search files"
  2 1  LeaderfFileFullScreen   "search files, LeaderF window take up full screen"
  3 2  LeaderfBuffer           "search listed buffers"
  4 3  LeaderfBufferAll        "search all buffers"
  5 4  LeaderfTabBuffer        "search listed buffers in current tabpage"
```

I think it would make items more clearer if the 'Leaderf' prefix was dropped and the list looked like this:
```
  1 0  File             "search files"
  2 1  FileFullScreen   "search files, LeaderF window take up full screen"
  3 2  Buffer           "search listed buffers"
  4 3  BufferAll        "search all buffers"
  5 4  TabBuffer        "search listed buffers in current tabpage"
```

The Leaderf prefix looks redundant as we are already in the LeaderfSelf menu and adds clutter to the menu in my humble opinion. The list items look much cleaner without the prefix and its easy to make out what individual items do. Perhaps the plugin can provide an option that would allow dropping of the prefix in the LeaderfSelf menu?

Thank you.

**Comment by eebrahimi7** [comment]
+1 for this

**Comment by Yggdroot** [comment]
I just want `LeaderfSelf` to list the **commands** of itself.
