### ISSUE TITLE
git blame --inline报错

### ISSUE THREAD

**Issue by CJTSAJ** [Yggdroot/LeaderF#1102]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 20 2024 14:18:20)
Included patches: 1-139

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.6m.so.1.0
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.6.8 (default, Nov 14 2023, 16:29:52)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

let g:Lf_PreviewInPopup = 1
noremap <leader>w :<C-U><C-R>=printf("Leaderf rg -e \"%s\" ", expand("<cword>"))<CR>

highlight Lf_hl_match gui=bold guifg=Blue cterm=bold ctermfg=blue
highlight def Lf_hl_rgHighlight gui=bold guifg=Blue cterm=bold ctermfg=blue

let g:Lf_RgConfig = [
        \ "--glob=!tags",
        \ "--glob='!*.html'"
    \ ]

call plug#begin('~/.vim/plugged')
Plug 'vim-scripts/LeaderF-master'
call plug#end()

### Describe your question, feature request, or bug.
执行 Leaderf git blame --inline 报错：
![image](https://github.com/user-attachments/assets/bc5442af-e964-400d-9b2d-7732aeb8a93b)

**Comment by Yggdroot** [comment]
你的vim版本有点低，需要vim9.0.67+才可以

**Comment by CJTSAJ** [comment]
vim版本升级后可以了，感谢大佬~
