### ISSUE TITLE
Feature Request: Display Last Edited Position in Preview for LeaderFBuffer

### ISSUE THREAD

**Issue by yakoye** [Yggdroot/LeaderF#1104]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Nov 13 2024 20:39:13) Included patches: 1-842
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.8.so.1.0
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.10 (default, Jul 29 2024, 17:02:10) [GCC 9.4.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
 let g:Lf_WindowHeight = 0.30
 let g:Lf_HideHelp = 1
 let g:Lf_UseCache = 0
 let g:Lf_UseVersionControlTool = 0
 let g:Lf_IgnoreCurrentBufferName = 1
 let g:Lf_StlColorscheme = 'Powerline'
 let g:Lf_MruEnableFrecency = 1
let g:Lf_PreviewCode = 1
let g:Lf_PreviewResult = {
        \ 'File': 1,
        \ 'Buffer': 1,
        \ 'Mru': 1,
        \ 'Tag': 1,
        \ 'BufTag': 1,
        \ 'Function': 1,
        \ 'Line': 1,
        \ 'Colorscheme': 0,
        \ 'Rg': 1,
        \ 'Gtags': 0
        \}
let g:Lf_WildIgnore = {
    \ 'dir': ['.git', '.hg', '.svn'],
    \ 'file': ['*.o', '*.a', '*.d', '*.i', '*.s', '*.bc', '*.so', '*.pyc', '*.swp', '*.class']
    \ }
let g:Lf_MruWildIgnore = {
    \ 'dir': ['.git', '.hg', '.svn'],
    \ 'file': ['*.o', '*.a', '*.d', '*.i', '*.s', '*.bc', '*.so', '*.pyc', '*.swp', '*.class']
    \}
" If needs
set ambiwidth=double
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }

" LeaderfFile
let g:Lf_ShortcutF = '<C-P>'
noremap <leader>p :LeaderfFile<CR>

noremap <C-L> :LeaderfMru<CR>
noremap <leader>l :LeaderfMru<CR>

"LeaderfBuffer
let g:Lf_ShortcutB = '<C-B>'

let g:Lf_CommandMap = {'<C-K>': ['<Up>'],
                     \ '<C-J>': ['<Down>']}

"noremap <leader>fs :<C-U><C-R>=printf("Leaderf file %s", "")<CR><CR>
"" preview all Line
nnoremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
"" preview all tag, such as function
nnoremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
"" preview all tag, such as function, more detail
nnoremap <leader>ff :<C-U><C-R>=printf("Leaderf function %s", "")<CR><CR>
noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
"noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>

let g:Lf_RgConfig = [
    \ "--glob=!git/*",
    \ "--glob=!cscope.*",
    \ "--glob=!tags*",
    \ "--hidden"
    \ ]
" search word under cursor, the pattern is treated as regex, and enter
" normal mode directly
nnoremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>

" search word under cursor literally in all listed buffers
nnoremap <C-D> :<C-U><C-R>=printf("Leaderf! rg --all-buffers -e %s ", expand("<cword>"))<CR>

" search word under cursor literally only in current buffer
nnoremap <leader>gc :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>

" search visually selected text literally
xnoremap <leader>gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>

" recall last search. If the result window is closed, reopen it.
nnoremap <leader>gr :<C-U>Leaderf! rg --recall<CR>

```

### Describe your question, feature request, or bug.

When I trigger :LeaderfBuffer or <C-B>, the LeaderF buffer window appears. I would like the preview to display the last edited position of the file instead of starting from the first line. How can I configure this behavior?

### Steps to reproduce
1. :LeaderfBuffer  '<Enter>'
2. '<Up>' or <'Down>',  Preview show
3. Without pressing the '<Enter>' key, see Preview windows，all files start displaying from the first line 0.

 I would like the preview to display the last edited position of the file in the center of the preview window instead of starting from the first line.
![image](https://github.com/user-attachments/assets/11b5cd0a-b835-4d3d-8c3f-4ddadd9eea49)

**Comment by Yggdroot** [comment]
Done. But it is displaying the last cursor position instead of last changed position.

**Comment by yakoye** [comment]
> Done. But it is displaying the last cursor position instead of last changed position.

How to set it so that the cursor is at the last position? With my current settings, the result always starts displaying from line 0.

**Comment by Yggdroot** [comment]
no need extra settings.

**Comment by Yggdroot** [comment]
It's weird, it doesn't work on my another machine either.

**Comment by Yggdroot** [comment]
In vim 9.1.16 it does not work. It works in vim9.1.602.

**Comment by yakoye** [comment]
In vim 9.1.842 it does not work.

**Comment by Yggdroot** [comment]
It should work after 9.1.0500.

**Comment by yakoye** [comment]
When I use git pull to get the latest LeaderF code, LeaderFBuffer works well.

**Comment by Yggdroot** [comment]
[擦汗]
