### ISSUE TITLE
Error when compiling C extension of Python3 in Python 3.12.7

### ISSUE THREAD

**Issue by jiangyinzuo** [Yggdroot/LeaderF#1106]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`:  3.12.7 (main, Nov  6 2024, 18:29:01) [GCC 14.2.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

```
Begin to compile C extension of Python3 ...
Traceback (most recent call last):
  File "/root/plugged/LeaderF/autoload/leaderf/fuzzyMatch_C/setup.py", line 5, in <module>
    from setuptools import setup
ImportError: cannot import name 'setup' from 'setuptools' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/plugged/LeaderF/autoload/leaderf/fuzzyMatch_C/setup.py", line 8, in <module>
    from distutils.core import setup
ModuleNotFoundError: No module named 'distutils'
```

```
Python 3.12.7 (main, Nov  6 2024, 18:29:01) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from setuptools import setup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
>>>
```

`distutils` module has been removed in Python 3.12 https://github.com/python/cpython/issues/92584

**Comment by Yggdroot** [comment]
Have a try the solutions in https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed/76691103#76691103.

**Comment by jiangyinzuo** [comment]
> Have a try the solutions in https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-installed/76691103#76691103.

Thanks, it works!
