### ISSUE TITLE
Feature: support find tabs.  like leaderf buffer

### ISSUE THREAD

**Issue by gulu-star** [Yggdroot/LeaderF#1108]
- vim or neovim? 
    - [ ] vim
    - [x] neovim

    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
feature: I hope to be able to directly search and jump to the corresponding tab by its name

**Comment by gulu-star** [comment]
I want to write a extension, but I don't know how to implement preview.  I haven't written any plugins before, this was written with the help of GPT

```
function! leaderf#showtab#source(args) abort "{{{
    let tab_list = []
    let current_tab = tabpagenr()    

    for tabinfo in gettabinfo()
        let tab_num = tabinfo.tabnr
        let buf_name = bufname(tabinfo.windows[0])
        if buf_name == '' 
            let buf_name = '[No Name]'   
        endif
        let tab_name = printf("%d: %s", tab_num, buf_name)
        call add(tab_list, tab_name)
    endfor
    
    return tab_list
endfunction "}}}


function! leaderf#showtab#accept(line, args) abort "{{{
    let match = matchstr(a:line, '^\d\+')
    if match != ''
        let tab_num = str2nr(match)
        if tab_num > 0 && tab_num <= tabpagenr('$')
            execute 'tabnext' tab_num
        else
            echo "Invalid tab number: " . tab_num
        endif
    endif
endfunction "}}}
```

**Comment by Yggdroot** [comment]
You can refer to https://github.com/Yggdroot/LeaderF-changes.

**Comment by gulu-star** [comment]
Thank you for your help。

**Comment by gulu-star** [comment]
> You can refer to https://github.com/Yggdroot/LeaderF-changes.

i read this repo， but I don't know how to implement this function of moveAndPreview

**Comment by Yggdroot** [comment]
You don't need to implement it by yourself.

**Comment by gulu-star** [comment]
![Image](https://github.com/user-attachments/assets/955e9242-39d0-49b8-a6a7-4d57175bfa9f)
I met with this mistake

**Comment by Yggdroot** [comment]
You need to update the LeaderF first. The bug has been fixed by 1116c71e.

**Comment by gulu-star** [comment]
update has solved the problem. thank u

**Comment by gulu-star** [comment]
my plugin，https://github.com/gulu-star/LeaderF-tabs
