### ISSUE TITLE
我安装了两次。第一次是能搜索到文件，打开报错；然后我重新安装了一下，还是可以搜索到问题，但是选择打开文件的时候就会core dump；

### ISSUE THREAD

**Issue by Allen-Scai** [Yggdroot/LeaderF#1109]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): 没有输出
- Output of `:echo &pythonthreedll`(only vim, not neovim): 没有输出
- Output of `:py print(sys.version)`: 
![image](https://github.com/user-attachments/assets/e8f7565e-e133-496b-bbf5-84e7864b7861)
- Output of `:py3 print(sys.version)`: 没有输出
- Output of `:echo g:Lf_Debug_Cmd`: 
![image](https://github.com/user-attachments/assets/78c9d5db-6b40-46bb-a80e-e8b59aa218ad)
- Output of `:echo g:Lf_FilesFromCache`: 
![image](https://github.com/user-attachments/assets/31f0d35e-3b34-4332-9b6f-97383213e6d7)
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
![image](https://github.com/user-attachments/assets/c965452b-4eb5-4519-9b77-c844a9016dd5)
### Describe your question, feature request, or bug.
我安装了两次。第一次是能搜索到文件，打开报错；然后我重新安装了一下，还是可以搜索到问题，但是选择打开文件的时候就会core dump；
第一次报错和此issue一样：https://github.com/Yggdroot/LeaderF/issues/1095
### Steps to reproduce
将LeaderF-master放到~/.vim/plugged，然后在.vimrc里面加上了下面的配置，接着就正常使用了

### Expected behaviour
能正常使用

**Comment by Allen-Scai** [comment]
不知道是哪里的问题，可能是python3的动态链接库找不到吗？麻烦作者大大看看这个issue

**Comment by Yggdroot** [comment]
现在建议用py3，你还是用的py2。而且你说报错和core dump，你没有提出具体错误信息，我也不知道什么原因。

**Comment by Allen-Scai** [comment]
> 现在建议用py3，你还是用的py2。而且你说报错和core dump，你没有贴出具体错误信息，我也不知道什么原因。

抱歉给您带来困扰，使用vim打开文件报的coredump我也不知道存放在哪里，因此没能打印出具体信息。
“现在建议用py3，你还是用的py2” <<< 这您是怎么看出来的呢？echo has("python3")为0吗？系统中是已经安装了python3的，是我设置得不对导致vim无法支持python3吗？我使用的vim版本看了下是支持python3的
![image](https://github.com/user-attachments/assets/2f7ee51e-8f04-40e8-afbe-7a19b8fe3513)

**Comment by Yggdroot** [comment]
`echo has("python3") ` 为0说明用的是python2.

看看https://zhuanlan.zhihu.com/p/89243293， 这上面有些说明。

**Comment by Allen-Scai** [comment]
我在gdb里面运行了下，如下所示，看起来像是动态链接库的问题吗？
另外，pythonthreedll 这个配置项在.vimrc里面不可配置，会提示错误，vim版本如下所示：
![image](https://github.com/user-attachments/assets/7af8beef-c365-49f4-bb5d-1ae284b48f45)
![image](https://github.com/user-attachments/assets/21a25099-d8a9-499a-8a19-e053f1ab27d8)
