### ISSUE TITLE
默认的索引缓存文件在什么路径下呢？

### ISSUE THREAD

**Issue by Allen-Scai** [Yggdroot/LeaderF#1110]
作者你好，请问下这个插件默认的缓存路径在哪里啊，我找了下没找到

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/1116c71e3290560a6f98fa336adf39d9bba7a997/doc/leaderf.txt#L106-L113

**Comment by Allen-Scai** [comment]
好的，十分感谢
