### ISSUE TITLE
加个大小写区别的 option 吧？

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#113]
哥，加个大小写区别的选项吧，我windows下经常搜索出同一个文件的好几条来，太影响查询了，你跟 vim 一样给个忽略大小写的选项吧？

**Comment by Yggdroot** [comment]
最近有点忙，等有空了加上。

**Comment by skywind3000** [comment]
你如果嫌弃匹配麻烦，没有时间搞，能不能给个选项，在加入到数据库之前，如果选项打开就将路径全部转成小写？

**Comment by Yggdroot** [comment]
不明白你为什么会有大小写不同的相同文件。你这个需求我不打算实现，你可以fork一下自己来做。

**Comment by skywind3000** [comment]
很正常，用 e 命令打开文件，有时输入大写，有时输入小写，有时候文件是被其他插件打开的，比如 gcc 的错误信息捕获到 quickfix 中，windows下错误信息里文件名全被弄成小写了，一打开就是一个小写文件名。还有其他一些会输出文件名的外部工具，只要 vim 按照这些信息跳转就都会导致 LeaderF MRU 出问题。

再 mru 里，他们都就被你当成不同的几个文件名了，同样一个 test.go 就有几个：

```text
E:\Lab\test.go
e:\lab\test.go
E:\lab\test.go
```

我是 MRU 的重度用户，CtrlP 的 MRU 和 FuzzyFinder 的 MRU 都不会把 Windows 下大小写不同的文件名识别成不同的文件。

你觉得这个理由成立么？

**Comment by skywind3000** [comment]
其实就是 MRU 数据收录问题，或者这样吧，如果你太忙的话，可以简单叙述下怎么改，改哪几个文件？我改完了 PR 过来，毕竟这是让windows下 leaderf 更完善的改进。

**Comment by Yggdroot** [comment]
你早这样说啊，你只让查询的时候区分大小写，这样只是治标不治本。治本的办法就是让mru列表里只出现一个文件名。

**Comment by skywind3000** [comment]
是啊，就是这个意思，加上这个 Windows 下就完美了。我现在 70% 的文件打开都是走 MRU

**Comment by skywind3000** [comment]
你这个插件绝逼比 CtrlP 好用，只是知道的人太少了，等我有机会帮你宣传，你可以再 tweet 上面 at 几个 vimcast 之类的 vim 相关公众号，人多的那种，让他们帮你推荐，就说 CtrlP 和 Fzf 的替代品，口气大点。我之前写了个破插件，at 了几个 vim 公众号，几个月就 500 星了。

**Comment by Yggdroot** [comment]
谢谢你的建议。有空帮忙宣传一下。:smile:

**Comment by Yggdroot** [comment]
我来改吧，也好改，因为mac也有不区分大小写的情况，所以要考虑全面些。

**Comment by Yggdroot** [comment]
还是你来改吧，我改了还要你来测，来确认。

代码改动在这里：
https://github.com/Yggdroot/LeaderF/blob/dff632620d39a9d76631cdda13c8cdd073a8deac/autoload/leaderf/python/leaderf/mru.py#L35-L53

这个函数是存储新的文件名到mru cache文件里，如果文件名已经存在就删掉，然后新的文件名插入到最上面。第42行就是比较文件名的，用的`==`，这里可以判断一下不区分大小写。

**Comment by skywind3000** [comment]
好今晚就改

**Comment by skywind3000** [comment]
看了下 MRU 数据库，还发现很多问题，比如文件加入前没有 abspath，比如那个 `e://lab///timer.py`

```text
D:\ACM\github\vim\tools\child.c
D:\acm\github\vim\bundle.vim
e:\lab\timer.py
D:\ACM\github\awesome-cheatsheets\editors\emacs.txt
e://lab///timer.py
E:\Lesson\collection\Makefile
D:\acm\github\vim\asc\menu.vim
d:\acm\github\vim\asc\menu.vim
d:\acm\github\vim\asc\keymaps.vim
D:\ACM\github\vim\autoload\svnhelp.vim
```

**Comment by skywind3000** [comment]
改好了：
https://github.com/Yggdroot/LeaderF/pull/117

两处改动：

1. Windows/Cygwin/Msys 下面 MRU 加入新文件忽略大小写
2. 文件名加入MRU 前进行归一化处理，避免同个文件被识别成不同的名字加入数据库

**Comment by skywind3000** [comment]
最后修正一处：

MRU 加入文件时，文件名归一化移到 fnmatch 前才合理。

**Comment by Yggdroot** [comment]
谢谢你的patch。

**Comment by Yggdroot** [comment]
Merge 了。

**Comment by Yggdroot** [comment]
非常感谢啊！
