### ISSUE TITLE
[BUG] python version check cause an error

### ISSUE THREAD

**Issue by sabearcher** [Yggdroot/LeaderF#115]
> if g:Lf_PythonVersion == 2 && pyeval("sys.version_info[:2] < (2, 7)")

this will always be TRUE, than we cannot use it.

**Comment by Yggdroot** [comment]
Sorry, I don't know where is wrong.

**Comment by sabearcher** [comment]
the version of my Python is 2.7.8, but it still cause a error, said Python2.7+ needed.

**Comment by sabearcher** [comment]
enn, something strange, I found that there are 2 versions of Python on my machine, the other one is 2.6.6, but this check func use the lower one, how to solve it?

**Comment by Yggdroot** [comment]
Please use `:py print(sys.version)` to see the output. I think your vim is using python 2.6.6.

**Comment by sabearcher** [comment]
yep, thanks.
truely its 2.6.6.
