### ISSUE TITLE
LeaderF is quite interesting, I just wrote a extension for it.

### ISSUE THREAD

**Issue by markwu** [Yggdroot/LeaderF#116]
LeaderF is quite interesting, and works well under my development environment. I just wrote an extension for it to integrate obsession/prosession.

![2018-03-05 2 03 31](https://user-images.githubusercontent.com/196861/36959817-110ad742-207f-11e8-810c-9a4670b19f6e.png)

You can find the repository here https://github.com/markwu/LeaderF-prosessions.

I have several minor suggestions for this project:

1. Create a wiki page for LeaderF extension listing. I see several extensions in github https://github.com/search?utf8=%E2%9C%93&q=leaderf-&type=, create a page for hosting these information is good to a newbie.
2. Need more information and tutorial about extension architecture, it take me some time to navigate the source code to understand how to wrote an extension for LeaderF.

Thanks for this project.

**Comment by Yggdroot** [comment]
Thanks for your suggestions. I'll take it into account.
