### ISSUE TITLE
best match is not the first option

### ISSUE THREAD

**Issue by mzlogin** [Yggdroot/LeaderF#12]
When I'm searching a file in fullpath way, sometimes the best match is not the first option, like the image below. So I think may be the matching algorithm can optimize.

Thanks for your great plugin!

![image](https://cloud.githubusercontent.com/assets/1646590/8772695/caf55588-2f00-11e5-9559-534e74a4c63e.png)

**Comment by Yggdroot** [comment]
Actually, there is no sort for fullPath, I'll optimize it later.

**Comment by Yggdroot** [comment]
This issue has been fixed by new commits.

**Comment by mzlogin** [comment]
@Yggdroot Glad to hear that. Thx a lot.
