### ISSUE TITLE
No mixed mode???

### ISSUE THREAD

**Issue by acgtyrant** [Yggdroot/LeaderF#120]
I would like to search in Files, Buffers and MRU files at the same time.

**Comment by Yggdroot** [comment]
Yes, there is no mixed mode. I don't think it is necessary.

**Comment by chenzhihuai1990** [comment]
But I think that a mixed mode is very useful. With an all-in-one keybinding, I can search everything in it without thinking where it is placed and which shortcut I should press. 

> Yes, there is no mixed mode. I don't think it is necessary.
