### ISSUE TITLE
Only can list files under current directory but cannot list files under other path

### ISSUE THREAD

**Issue by toplinq** [Yggdroot/LeaderF#121]
Hi I use 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 14 2018 13:52:49)
macOS version
Included patches: 1-1600

I install LeaderF by Vundle. 
I can only list the files under current files, when I want change to other path and list files like
:LeaderFile /User/xxxx/xxx
the error message is "no content!"

**Comment by Yggdroot** [comment]
Sorry, I can not reproduce it.
What is your configuration about LeaderF in your vimrc?
Can you try some other directories? Does this always happen?

**Comment by toplinkq** [comment]
Thanks for response so quickly. 
I try again and I also cannot reproduce it too. It seems disappear. 
Only issue is 
:LeaderFile ~ 
does't work, it shows "no content!"  but 
:LeaderFile ~/ 
works
But it is okey for me. 
Thanks a lot. I like this tool.

**Comment by Yggdroot** [comment]
The issue has been fixed, thanks for reporting.
