### ISSUE TITLE
切换输入和结果窗口的默认快捷键问题。

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#123]
给几个朋友推广过 leaderf，用惯了 CtrlP 切换过来一开始都有一些不习惯，就是按ESC是默认返回结果面板，我后来告诉了他们可以改配置，弄成和 CtrlP 一样，以后才觉得好用。

建议默认键位完全无缝同步 CtrlP ？不用人家研究改键位了，因为用 CtrlP 不满的人太多了，如果 LeaderF 体验完全和 CtrlP 一样的话，能团结一大堆 CtrlP 用户，至于切换到文件列表窗口里做些事情，的确是 LeaderF 的新功能，但用不着因为引入一个新功能就把老的方便的操作路径给阻挡了，能否：
输入模式和列表窗口间使用tab切换？

体验就像windows里搜索文件筐里输了几个关键字，然后可以 tab 把焦点移动下来选择一个文件一样。再用tab还可以回去接着输入关键字。

我每次都要教朋友这么配一堆：

```VimL
		let g:Lf_ShortcutF = '<c-p>'
		let g:Lf_CommandMap = {'<C-C>': ['<Esc>', '<C-C>'], '<Esc>':[ '<tab>' ]}
		let g:Lf_NormalMap = {
			\ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>'],
			\            ["<F6>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']
			\            ["<tab>", ':exec g:Lf_py "fileExplManager.input()"<CR>']
			\           ],
			\ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>'],
			\            ["<F6>", ':exec g:Lf_py "bufExplManager.quit()"<CR>'],
			\            ["<tab>", ':exec g:Lf_py "bufExplManager.input()"<CR>'],
			\           ],
			\ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>'],
			\			 ["<tab>", ':exec g:Lf_py "mruExplManager.input()"<cr>']],
			\}
```

然后他们才觉得舒服，或者出一个：兼容 CtrlP 配置模式的 Option ？？就像 nerdtree 有个选项可以劫持 netrw 一样？？

**Comment by skywind3000** [comment]
最后是，能不能加个选项，把 "Press <F1> for help" 给隐藏掉？

**Comment by Yggdroot** [comment]
嗯，可以考虑加个`g:Lf_CtrlpCompatible`，如果设了这个选项，就让所有快捷键跟ctrlp一样，但我不想让它默认开启。当时写这个插件的时候，没有跟ctrlp一样，一方面是因为我不习惯它的键位设置，另一方面是不想让人感觉我在**copy** ctrlp。
把默认切换键改成tab可以接受。
你说的第二个问题也可以做。
我没有太多时间来做这个事情，我最近在考虑在匹配的时候加入多线程支持，充分利用多核。你如果有空是否可以帮忙 :smile:

**Comment by skywind3000** [comment]
不会觉得在copy ctrlp，比后者好多了谈何copy，就像大家不会觉得nerdtree在copy netrw一样

**Comment by Yggdroot** [comment]
想来想去还是不打算默认跟ctrlp一样。一方面，这是这个插件的差异化特点，另一方面，这样就破坏了后向兼容性，对于现有用户来说，如果更新了插件，原来的习惯就突然变了。

**Comment by skywind3000** [comment]
尊重你的设计思路，只是默认ctrl-c退出输入真的太危险了，ctrl-c是不推荐用户按的，除非有脚本死循环了。特别新版vim，各种timer和后台任务，你不小心按错了时机就把一个刚好运行的callback弄挂了。

现在用timer的插件太多了，youcompleteme，ale。我自己写的一个小插件里面有一个10Hz的timer，都经常被一个习惯了ctrl+c退出ctrlp的用户每隔两天弄挂一次，何况其他密集运行的回掉。

至少搞个兼容ctrlp的选项？默认关闭的那种？

**Comment by Yggdroot** [comment]
等有空加个`g:Lf_CtrlpCompatible`，默认关闭。如果设了这个选项，就让所有快捷键跟ctrlp一样。

**Comment by Yggdroot** [comment]
这个[commit](https://github.com/Yggdroot/LeaderF/commit/c8871af62adef2d2b41eab71de512738d9d0b95a) 把`<esc>`改为退出了，`<tab>`代替原来`<esc>`的功能。
我觉得ctrlp用户最大的不习惯就是这里吧，其他的就没必要改了。

**Comment by Yggdroot** [comment]
这个[commit](https://github.com/Yggdroot/LeaderF/commit/a07e3184ac78dc765915cf2fa1aa77950ad2d435)把normal模式下`<tab>`也变成进入输入模式了，`<esc>`也变成退出了。
你可以把`let g:Lf_NormalMap = {}`里面的定义去掉了。

**Comment by skywind3000** [comment]
thanks 啊！！

**Comment by skywind3000** [comment]
之前设这个map主要更符合我的直觉和旧习惯一点，最近更新很给力啊。

**Comment by sisrfeng** [comment]
一开始不适应tab切换到normal, 这个说法好:
体验就像windows里搜索文件筐里输了几个关键字，然后可以 tab 把焦点移动下来选择一个文件一样。再用tab还可以回去接着输入关键字。

**Comment by sisrfeng** [comment]
但习惯esc切到normal, 容易不小心就退出了,这样map不行:
![image](https://user-images.githubusercontent.com/53520949/151100316-139e227e-d1c9-40ed-9d49-c9a888c2a809.png)

怎么改呢?

**Comment by Yggdroot** [comment]
> 但习惯esc切到normal, 容易不小心就退出了,这样map不行: ![image](https://user-images.githubusercontent.com/53520949/151100316-139e227e-d1c9-40ed-9d49-c9a888c2a809.png)
> 
> 怎么改呢?
`
let g:Lf_CommandMap = {'<tab>':[ '<ESC>' ]}`
