### ISSUE TITLE
帮忙测试

### ISSUE THREAD

**Issue by Yggdroot** [Yggdroot/LeaderF#124]
@skywind3000 能否帮个忙测试一下LeaderF的模糊匹配算法？在branch `fuzzy4`里，我做了一些修改，增加了单词首字母的权值，减小了连续字符的权值。因为每个人的搜索习惯不一样，我不知道改了后是不是比原来好点（我认为好点），能否帮忙比较一下？

**Comment by skywind3000** [comment]
好，稍后测试一下。

**Comment by Yggdroot** [comment]
branch 改为`fuzzy`.

**Comment by skywind3000** [comment]
为啥我运行起来和master感觉没什么区别？

**Comment by Yggdroot** [comment]
需要重新编译。
其实本来区别就不大。

**Comment by Yggdroot** [comment]
排在前几位的基本都是一样的，往下一点才能看出差别。

**Comment by skywind3000** [comment]
重新编译了，还是没什么区别，对了 install.sh 最后有一句：

    install.sh: 0: not found

```text
Begin to compile C extension of Python2 ...
running build
running build_ext
building 'fuzzyMatchC' extension
creating build
creating build/temp.freebsd-11.1-RELEASE-amd64-2.7
cc -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing -DNDEBUG -fPIC -I/usr/local/include/python2.7 -c fuzzyMatch.c -o build/temp.freebsd-11.1-RELEASE-amd64-2.7/fuzzyMatch.o
creating build/lib.freebsd-11.1-RELEASE-amd64-2.7
cc -shared -lpthread -L/usr/local/lib -fstack-protector build/temp.freebsd-11.1-RELEASE-amd64-2.7/fuzzyMatch.o -L/usr/local/lib -lpython2.7 -o build/lib.freebsd-11.1-RELEASE-amd64-2.7/fuzzyMatchC.so
install.sh: 0: not found
```

**Comment by Yggdroot** [comment]
奇怪，是不是你的bash版本比较低，不支持`(( ))`语法，所以在https://github.com/Yggdroot/LeaderF/blob/c8871af62adef2d2b41eab71de512738d9d0b95a/install.sh#L15 里出错了。

**Comment by Yggdroot** [comment]
在`nameOnly`模式，可能不易发现区别，在`fullpath`模式也许会好点。

**Comment by skywind3000** [comment]
我再 freebsd 下面测试的，我看你后缀些的是 .sh 不是 .bash 我就默认用  sh 跑了。freebsd 下 sh 就是个 posix shell，不支持 (( )) 可以写成：

    if [ $? -eq 0 ]

就通用了

**Comment by Yggdroot** [comment]
嗯，那我就改一下。
之前install有错，你是怎么用的？不会用的py版本的fuzzyMatch吧

**Comment by skywind3000** [comment]
生成出so来了啊。我看着。

**Comment by skywind3000** [comment]
没起作用？

**Comment by Yggdroot** [comment]
只生成so还不行，脚本的下一部分是把so拷贝到某个目录下，这样才行。
After running any command of LeaderF, check the value of `echo g:Lf_fuzzyMatch_C`, if the value is 1, it means the C extension is loaded sucessfully.

**Comment by Yggdroot** [comment]
不用测了，我还要改。

**Comment by skywind3000** [comment]
有个权重匹配算法比较科学啊，FireFox 用于输入 URL 匹配最佳历史的 Frecent 计算方法：每条记录维护两个字段：rank (访问次数，每访问一次+1），time(最近一次访问的unix时间戳), 

frecent 的计算方法如下：

```python
current = time.time()
for item in items:
    dx = current - item.time
    if dx < 3600:
       item.frecent = item.rank * 4
    elif dx < 86400:
       item.frecent = item.rank * 2
    elif dx < 604800:
       item.frecent = item.rank / 2
    else:
       item.frecent = item.rank / 4
```

这个 frecent 是一个兼顾最近访问时间和访问次数的结果，如果一小时内访问过，那么权重是访问次数*4，如果 1 天内访问过那权重是访问次数 * 2，如果一周内访问过那么权重是访问次数的二分之一，超过一周就变成四分之一。

firefox 最终在所有匹配结果中用 frecent 进行排序，可能你用过  [z](https://github.com/rupa/z), fasd 之类的软件快速跳转插件，他们也是使用 frecent 进行目录跳转，文件查找，效果也很好。我在 bash 中基本使用 z 进行目录跳转比 fzf 精确度高多了，基本能猜出我的心意。

如果 Leaderf 继续优化排序的话或许可以参考下，比如 MRU 之类的。

**Comment by Yggdroot** [comment]
谢谢你的建议。
不过这个算法好像不太适合Leaderf的查找场景，MRU里也许可以用到。
我觉得我的算法跟同类插件（ctrlp，fzf，command-t，cpsm）比较，是最好的（有点太不谦虚了），他们的算法要么排序不太好（ctrlp，cpsm），要么时间复杂度是O(m*n), 我的时间复杂度是O(m+n)的。我也一直在使用中做细微调整，希望它更好。

**Comment by skywind3000** [comment]
嗯，现在匹配算法不用改了，我用着挺舒服的。你有空的话，或者你可以告诉我一下，怎么去掉 

    " Press <F1> for help

这句话，切到 normal 下面就出现，怎么加个类似 g:Lf_hide_help 之类的 option 把这句话干掉？我可以改了提交过来。

**Comment by Yggdroot** [comment]
把这两行去掉就可以了：
https://github.com/Yggdroot/LeaderF/blob/8078ef460e99d56a7f653357f8bab545b73234ed/autoload/leaderf/python/leaderf/manager.py#L233-L234
可以用
`if lfEval("g:Lf_hide_help") == '1'` 把这两行包起来。

**Comment by skywind3000** [comment]
改好了，麻烦帮查收一下啊：
https://github.com/Yggdroot/LeaderF/pull/127

**Comment by Yggdroot** [comment]
Merge了。

**Comment by skywind3000** [comment]
对了，我本来想更新下 doc 的，但是我不会写 vim 的 help 格式，还原 filetype 为 txt 时发现 help 很多转义符号，没敢弄，你如果哪天更新这个 help 了，顺便弄一下啊。
