### ISSUE TITLE
LeaderfFunction 的 normal mode 窗口性能很差，j, k 上下移动光标反应很迟缓

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#125]
我现在已经完全用 LeaderfFunction 代替 tagbar 了，自从我发现 tagbar 会在我没有打开它面板时偷偷给我运行 ctags 并且没有用 jobs 跑，我就怒了，我主要用 windows 开发，windows 下面有时候启动一个进程就会被反病毒扫描，导致偶尔情况一个小程序会卡个几百毫秒，加到卡巴斯基信任列表里都没用。

用了 tagbar 以后，它时不时不经我允许运行ctags，我打着字呢，就卡住几百毫秒，最后被我纠出来是 tagbar的问题，立马卸载了用 LeaderfFunction 代替，用了一段时间，发现比 tagbar 清爽高效多了，唯一不爽就是我大部分时候是在 LeaderfFunction 的 normal mode 下面来上下浏览这个文件有些什么函数的，而不是直接输入匹配，此时列表窗口中 j/k 上下移动光标时我感到明显的延迟，cpu占用很高。

我记得 tagbar 窗口里上下移动光标不会卡，是否因为移动了光标要自动跳到文件对应位置引起的？这里能否有优化的空间？如果没有的话，能不能跟 tagbar 一样在自动跳转位置前加一个延迟？类似 CursorHold 1-2秒再执行自动跳转？这样的话，我上下快速移动光标就会很流畅了，停下来上面文件的位置也会立马更新，好像 tagbar 就是这么做的。

**Comment by Yggdroot** [comment]
卡的原因就是每次移动都会跳到文件对应位置引起的，可以禁掉：
```vim
let g:Lf_PreviewResult = {
            \ 'File': 0,
            \ 'Buffer': 0,
            \ 'Mru': 0,
            \ 'Tag': 0,
            \ 'BufTag': 0,
            \ 'Function': 0,
            \ 'Line': 0,
            \ 'Colorscheme': 0
            \}
```
你说的CursorHold 再跳也可以，有空加上。

**Comment by Yggdroot** [comment]
没有优化的空间了，因为vim是单线程的，跳过去会sleep 几十毫秒来显示cursorline，如果支持多线程就不会有这个问题了。
