### ISSUE TITLE
Add Changelog file?

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#130]
Hi!

I just updated LeaderF and was surprised that ESC didn't work as expected. I finally found that it's now TAB that is used for that.

I think it would be interesting to list the fixes, changes and improvements in a Changelog file.

What do you think about that?

**Comment by Yggdroot** [comment]
In the future, I'll try my best to keep LeaderF backward compatible, so users don't need to care about the Changelog file then.

**Comment by romainf-unity** [comment]
I'm not against breaking backward compatibility from time to time. I prefer a bad design to be ironed out once and for all instead of hacking around it for many years.

That being said, maybe I could just read the commit list.. it's not that long indeed.

**Comment by romainf-unity** [comment]
A good template for CHANGELOG files: https://keepachangelog.com/

**Comment by Yggdroot** [comment]
THANKS

**Comment by Yggdroot** [comment]
Added.
