### ISSUE TITLE
是否有搜索项目全局函数的功能？

### ISSUE THREAD

**Issue by lemon0910** [Yggdroot/LeaderF#135]
我想问一下有没有搜索项目中所有函数的功能，因为我打开文件，要么根据文件名，要么根据函数名，使用了LeaderfTag功能，有些函数名能搜索到，有些没搜索到

**Comment by lemon0910** [comment]
我更新了一下ctags版本，找到了，请问有没有办法只查找函数符号，不查找其它符号

**Comment by Yggdroot** [comment]
只对打开的文件有这个功能，全局查找还没有。

**Comment by lemon0910** [comment]
嗯，我能想到的常用跳转就是文件名和符号名，但全局符号对vim确实有难度

**Comment by Leviathan1995** [comment]
@Yggdroot 这个后续考虑支持吗? 现在自己都是grep 搜索函数

**Comment by Yggdroot** [comment]
> @Yggdroot 这个后续考虑支持吗? 现在自己都是grep 搜索函数

全局范围搜索函数？ 可以试试`Leaderf gtags`。
