### ISSUE TITLE
relative path for tags

### ISSUE THREAD

**Issue by meijieru** [Yggdroot/LeaderF#136]
Sometimes the abs path for tags are too long.
option `let g:Lf_ShowRelativePath = 1` does not work for tags.

**Comment by Yggdroot** [comment]
What command did you use? Can you show me an example?

**Comment by meijieru** [comment]
![image](https://user-images.githubusercontent.com/9511136/39167208-862d454c-47c0-11e8-81da-d0a7314c966d.png)

`:LeaderfTag` is used

**Comment by meijieru** [comment]
As shown in the above example, the path is too long to display. A relative path to current dir may be better.

**Comment by Yggdroot** [comment]
LeaderfTag just reads the tags you generated. It depends on how you generate the tags file.
