### ISSUE TITLE
Some files are missing using Leaderf

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#14]
I open Vim in the root directory in the Linux kernel source tree. In Leaderf name-only mode, I entered `mmu.c`. However, I couldn't find `arch/x86/kvm/mmu.c` in the list. In Leaderf full-path mode, `x86/mmu.c` could list `arch/x86/kvm/mmu.c`.
So is there something wrong with LeadF? Thanks very much!

**Comment by Yggdroot** [comment]
I can find it in Linux kernel 4.4.
![linux](https://cloud.githubusercontent.com/assets/2705841/12392995/e5e9d212-be2d-11e5-972c-6377cfddafd2.png)
I don't know what happened to you.

**Comment by tamlok** [comment]
I tested it on two machine, one succeed and the other failed. If I can provide any debug info to help improve it, please let me know! :)

**Comment by Yggdroot** [comment]
Could you provide the exact source which has this issue?

**Comment by tamlok** [comment]
I couldn't reproduce the issue with the same sources on another machine. Is there any way to clean the cache or some cache file instead of `<F5>`?

**Comment by Yggdroot** [comment]
Currently, the answer is no. And I am refactoring the plugin, perhaps I will add the function of  managing the cache later.
