### ISSUE TITLE
Ctrl+R,Ctrl+W to insert the word under current cursor

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#140]
Hi,

Thanks for your great work! I am back to `LeaderF` again after struggling with `CtrlP` for a while.

In the command line of Vim, `Ctrl+R Ctrl+W` is a great and universal feature to insert the word under current cursor. Could we enable this shortcut within `LeaderF`?

Thanks!

**Comment by Yggdroot** [comment]
What is the scenario that you want to use `Ctrl+R Ctrl+W` in LeaderF?
If LeaderF is launched, the cursor is hidden, how do you know which word is under current cursor?

**Comment by tamlok** [comment]
When my cursor is under a variable name, and I now want to search this symbol using LeaderF. Then I press `<leader>F`, then I need to type the whole symbol in LeaderF without `Ctrl+R Ctrl+W`.

I know that LeaderF provide more specific commands to search the word under current cursor. But it is hard for me to assign a `<leader>` shortcut for each of these commands. I just want to call out the LeaderF in its universal interface, then insert current word to search with a handy shortcut.

`Ctrl+R Ctrl+W` is a standard shortcut in command line mode in Vim to insert the word under current cursor.

Thanks!

**Comment by tamlok** [comment]
By the way, `Ctrl+R` is also a standard shortcut to read the content of a register, such as `Ctrl+R +` to read the system clipboard.

**Comment by Yggdroot** [comment]
I think you can copy the word first, then use <c-v> to paste it to the command line.

**Comment by tamlok** [comment]
`Ctrl+R` is an important shortuct in Vim: to **read a register**, to **insert current word**. I think changing the standard behavior of it is not a good idea, just like `Ctrl+U` to delete till the beginning.

Will it be an option to custom the shortcut to change the regex mode and fuzzy search?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/96c22807b7920be46d63e05f5a7b159030908ca7/doc/leaderf.txt#L476-L481
