### ISSUE TITLE
Absurd height of the LeaderF window after resizing GVim while LeaderF is opening

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#141]
- Win10, GVim 8.0
- How to reproduce
    1. Open GVim with its init size, such as 800*600;
    2. `<leader>f` to open LeaderF;
    3. Maximize GVim;
    4. Now the window of the `<leader>f` will occupy more than half of the height of GVim;
    5. Press `<Esc>` to exit LeaderF;
    6. Here comes the bug: the height of the LeaderF window is still half of the height of GVim, instead of minimizing to one line height.

![image](https://user-images.githubusercontent.com/5763157/39281929-bec6beb8-4939-11e8-9fb8-262093837eee.png)

Thanks!

**Comment by geekyes** [comment]
我也试了下，在win7下，在按过<Esc>后，多点击几次最大化就好了！！！
