### ISSUE TITLE
有没有可以在终端下运行的二进制

### ISSUE THREAD

**Issue by jkunlin** [Yggdroot/LeaderF#142]
fzf除了vim插件之外，还可以在终端使用，配合z使用的时候很方便。
请问LeaderF是否有相应的二进制？

**Comment by Yggdroot** [comment]
LeaderF只是vim的插件，而不是一个终端工具。
如果说有的话，就是https://github.com/Yggdroot/AllFuzzy 了，不过还没有写好。

**Comment by jkunlin** [comment]
请问AllFuzzy有计划什么时候完成吗？

**Comment by Yggdroot** [comment]
不知道，一直没有时间写。
我也只是打算写着玩，练习练习Python，并没有打算要取代fzf的意思，毕竟fzf已经开发那么多年了，各方面功能也没有明显的缺点。

**Comment by jkunlin** [comment]
好的，多谢啦
