### ISSUE TITLE
MRU file list might always be sorted by time

### ISSUE THREAD

**Issue by 12425** [Yggdroot/LeaderF#146]
Now the list of `:LeaderfMru` is sorted by time, but after I input something, the new list seems randomly sorted.

I'll be happy if the list is always sorted by time. Thank you!

**Comment by Yggdroot** [comment]
I don't know why you have such a requirement.

**Comment by 12425** [comment]
For example, after I open Vim, I want to continue my last work.
I input "cpp" and the **Most Recent Used** file with cpp should appear at the first.
Often on Mondays I don't remember the file name of my last work on Friday  :)
That is what MRU is, isn't it? The requirement is just for MRU.

**Comment by Yggdroot** [comment]
Sorry, LeaderF can not add this feature.
