### ISSUE TITLE
g:Lf_MruFileExclude not work

### ISSUE THREAD

**Issue by Cooie** [Yggdroot/LeaderF#149]
- vim or neovim?
    - [x] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 18 2018 15:30:48)
macOS version
Included patches: 1-1700
Compiled by Homebrew

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): nothing printed
- Output of `:echo &pythonthreedll`(only vim, not neovim): nothing printed
- Output of `:py print(sys.version)`: `Sorry, the command is not available in this version`
- Output of `:py3 print(sys.version)`: 3.6.5
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
            \}
let g:Lf_MruFileExclude = ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]', '*.cnx']
```

### Describe your question, feature request, or bug.
Mrus still show `.cnx` files when I set `g:Lf_MruFileExclude`. By the way, how can I exclude files in specific directory? I have add `.git` direcotry in `g:Lf_WildIgnore` but mrns still show files in `.git` directory.

**Comment by Yggdroot** [comment]
`g:Lf_WildIgnore` does not work for MRU, it only works for LeaderfFile.
`g:Lf_MruFileExclude` indicates that files match pattern defined in it won't be recorded in MRU cache. If you have opened the `.cnx` file before setting g:Lf_MruFileExclude, the `.cnx` file can still be shown, the .cnx file after the setting won't show in the MRU.
Maybe I need add a `g:Lf_MruWildIgnore` option to meet your requirement.

**Comment by Cooie** [comment]
How can I refresh MRU cache? I have tried use `F5` but not work.

**Comment by Yggdroot** [comment]
Why do you want to refresh the cache?

**Comment by Cooie** [comment]
Sorry for misunderstanding  your reply. There is no need to refresh the cache.

By the way, I think it may be better to make `g:Lf_WildIgnore` works for all modes than add a new `g:Lf_MruWildIgnore`

**Comment by nooberfsh** [comment]
Adding `g:Lf_MruWildIgnore`  +1

**Comment by Cooie** [comment]
I have updated LeaderF and replaced `g:Lf_MruFileExclude` with `g:Lf_MruWildIgnore`. 

Thanks a lot for making the charming plugin!
