### ISSUE TITLE
在空文件里 LeaderfFunction! 会报错

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#150]
我记得我之前改的时候注意过这个情况，但是最近这次更新好像被你改没了那个条件判断了。
之前是要判断 self._launched 的，你把它删除了，新文件就出错了。

重现：

```VimL
:tabe
:LeaderfFunction!
```

**Comment by skywind3000** [comment]
```
Error detected while processing function leaderf#Function#startExpl[5]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Linwei\.vim\bundles\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 324, in startExplorer
    self._relocateCursor()
  File "C:\Users\Linwei\.vim\bundles\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 328, in _relocateCursor
    inst.buffer.options['modifiable'] = False
AttributeError: 'NoneType' object has no attribute 'options'
```

**Comment by skywind3000** [comment]
因为是一个 `[NO NAME]` 的空文件 self._launched 为假，下面还提示 `No content!` ，normal模式窗口也不会弹出来。所以没有 self._launched 判断的话后面就都错了

**Comment by Yggdroot** [comment]
哦，你之前说过有个错误，我不知道怎么出现的。我看那个条件好像有些多余，就去掉了，试了几种情况也没出错，所以就改了。我再改过来。

**Comment by Yggdroot** [comment]
改好了。

**Comment by skywind3000** [comment]
已更新，没问题了，哈哈。

其实把 LeaderfAny 做好以后，好像 Function, BufTag, Color 这些都可以归并过去了，拆分成及部分即可：

- 源：字符串 list，含 tab 分隔，每个 tab 分隔的元素 syntax 颜色不同
- 响应回调：包含一个参数，选中第几行，-1表示q退出了。
- 预览回调：包含一个参数，预览第几行
- 初始 index ，用于设定直接！进入normal以后光标停留在哪里。

可能这个 LeaderfAny 以函数形式存在更好点。

**Comment by skywind3000** [comment]
以后这类东西扩充，就只需要写一个函数就行了，我准备把功能目录放进去，比如 vimrc 里的快捷键，一些少用的经常搞忘记，有这个东西就直接做成目录，比如我 vimrc里就可以配置功能菜单：

- 查找 tag 定义
- 查找 tag 引用
- 光标下单词 grep
- 编译文件
- 运行文件
- 编译项目
- 运行项目
- 从 URL 读取内容贴到当前buf
....
- 切换 paste
- 切换 spell

写个函数就能调用 leaderf的搜索我的功能，多方便，还能有快捷键提醒。

**Comment by skywind3000** [comment]
这样我就可以把 Leaderf 当作 vim 的【开始】菜单用了，把我的 vimrc 分享给别人，别人打开菜单就直到里面可以干嘛。

**Comment by Yggdroot** [comment]
你觉得呢？

**Comment by skywind3000** [comment]
或者我们先看看 fzf 和 denite 的接口是怎么设计的，然后再确定下？

**Comment by skywind3000** [comment]
再说配置问题，FZF 没有配置，直接提供个启动函数：

For more advanced uses, you can use `fzf#run([options])` function with the
following options.

```
--------------------------+---------------+--------------------------------------------------------------
Option name               | Type          | Description                                                  ~
--------------------------+---------------+--------------------------------------------------------------
source                    | string        | External command to generate input to fzf (e.g.  find . )
source                    | list          | Vim list as input to fzf
sink                      | string        | Vim command to handle the selected item (e.g.  e ,  tabe )
sink                      | funcref       | Reference to function to process each selected item
sink*                     | funcref       | Similar to  sink , but takes the list of output lines at once
options                   | string/list   | Options to fzf
dir                       | string        | Working directory
up / down / left / right  | number/string | Use tmux pane with the given size (e.g.  20 ,  50% )
window  (Vim 8 / Neovim)  | string        | Command to open fzf window (e.g.  vertical aboveleft 30new )
launcher                  | string        | External terminal emulator to start fzf with (GVim only)
launcher                  | funcref       | Function for generating  launcher  string (GVim only)
--------------------------+---------------+--------------------------------------------------------------
```

`options` entry can be either a string or a list. For simple cases, string
should suffice, but prefer to use list type if you're concerned about escaping
issues on different platforms.

    call fzf#run({'options': '--reverse --prompt "C:\\Program Files\\"'})
    call fzf#run({'options': ['--reverse', '--prompt', 'C:\Program Files\']})

它可以配置接受外部命令，这些字段可以参考一下，不管使用全局字典还是用函数参数。

**Comment by skywind3000** [comment]
用户自己再配置一个全局字典的话，会不会把原有 leaderf 的 function 这些覆盖了？还是说有一个内建字典，还有一个配置字典，可以联合使用？

如果用全局配置，配置一次就不动的话，就不能用 FZF#run 这种提供个list的方法了，只能写个函数名字，每次 Leaderf name 的时候调用并返回了？

 ```VimL
let g:Lf_sources = {}
let g:Lf_sources.function = {
  \ "source": function("s:generate_function_list"),
  \ }
```

再，配置里面是写 python 代码还是 vim 代码？比如预览回掉和选中回掉？我建议都支持，比如可以写做：

```VimL
let g:Lf_sources.function = {
  \ "on_selected": function("s:function_selected"),
  \ }
```

或者：

```VimL
let g:Lf_sources.function = {
  \ "on_selected_py": 'mymodule.on_selected',
  \ }
```

提供一个即可？

**Comment by Yggdroot** [comment]
还是支持Python吧，别人不用，自己用着舒服。

**Comment by skywind3000** [comment]
我前面说的做成全局字典就不能像 FZF 一样提供个list，意思是，如果是函数，在使用时就可以这么用：

```VimL
function! MyFunctionList()
    let funnames = ['fun1', 'fun2', 'fun3', 'fun4']
    let initial_index = 1
    let selected_index = call Leaderf#Any(funnames, initial_index, {options})
    if selected_index < 0   
        " on cancel
    else
        " on selected
    endif
endfunc
```

这就和 FZF#run 的用法差不多了，每次弹出 fzf 前，我先把结果计算好，弄成 list 然后再传递给 fzf，或者告诉 fzf 一个命令行，它去执行以后生成选项。

就是源可以每次使用前再确定，那么调用any的时候就可以直接传送一个计算好的list。如果用全局字典的话，就不能这么做了，会更麻烦一些，需要一开始就确定源，那么用户都还没有开始使用，怎么确定源呢？就只能传一个函数指针过来了，告诉 Leaderf ，命令发生时需要源的时候调用这个函数，这个函数会返回一个list。还有全局字典的话，需要再我的 vimrc 里一开始就定义好所有源，不能说你模块化的vimrc，这个配置里定义一个源，那个配置里定义一个源。

我没有太强的偏好，事实上你说的方式和 denite 有些类似，一开始先把所有源定义好了。

**Comment by Yggdroot** [comment]
有点明白你的意思了，全局字典的方法只是比你说的这个方法多了2个回调，一个生成数据源的回调，一个on_selected()回调，好像没有别的了。你这个方法好像对用户的要求更高一点，相当于只提供了API，用户再做二次开发。
“不能说你模块化的vimrc，这个配置里定义一个源，那个配置里定义一个源。”这句话没太看明白。

**Comment by skywind3000** [comment]
定义成全局字典的话，回调可能需要传一些参数，比如 on_selected/on_preview 除了需要知道 selected_index 以外，是否还需要知道被选中那一行的文本，好做分析。

**Comment by Yggdroot** [comment]
我明白你的想法和顾虑了，我也不反对你说的方法，我觉得跟全局字典并不矛盾，可以两个都实现，只是功能有点重叠。全局字典的方法我主要是想让leaderf有个统一接口。
要么我来实现全局字典的方法，你来实现你那个方法？实现中遇到的问题和细节我们再讨论。

**Comment by skywind3000** [comment]
好的，这个改动很大，等你写出来我参考一下，难说主要还是在调用你新写的接口

**Comment by Yggdroot** [comment]
#144.
