### ISSUE TITLE
Error: LeaderF requires vim compiled with +python or +python3

### ISSUE THREAD

**Issue by yanugto** [Yggdroot/LeaderF#151]
- vim or neovim?$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  8 2018 15:00:34)
包含补丁: 1-1476
编译者 <alexpux@gmail.com>
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl/dyn          +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               -ruby              -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static

    - [1 ] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): can't load
- Output of `:echo &pythonthreedll`(only vim, not neovim): can't load
- Output of `:py print(sys.version)`: can't load
- Output of `:py3 print(sys.version)`: can't load
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ 1] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by yanugto** [comment]
git bash

E370: 无法加载库 msys-python3.6m.dll

Administrator@PC-20180322WCAK ~                                                                  
λ python                                                                                         
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32        
Type "help", "copyright", "credits" or "license" for more information.                           
>>>

**Comment by Yggdroot** [comment]
Please read https://www.v2ex.com/t/410079 first.

**Comment by whalecold** [comment]
> Please read https://www.v2ex.com/t/410079 first.

Thanks!

**Comment by DanielTate** [comment]
I can't read chinese is there an english version?

**Comment by Yggdroot** [comment]
> 
> 
> I can't read chinese is there an english version?

No, you can translate it here: https://translate.google.cn/?sl=auto&tl=zh-CN&op=translate

**Comment by liaol** [comment]
Add these lines to ~/.vimrc works for me  on MacOS
```
" Python Setting {
  set pythondll=/usr/local/Frameworks/Python.framework/Versions/3.9/Python
  set pythonhome=/usr/local/Frameworks/Python.framework/Versions/3.9
  set pythonthreedll=/usr/local/Frameworks/Python.framework/Versions/3.9/Python
  set pythonthreehome=/usr/local/Frameworks/Python.framework/Versions/3.9
" }

```

**Comment by z0xyz** [comment]
Just had to execute `pip3 install --user --upgrade neovim` and restart it
