### ISSUE TITLE
在部分目录下执行LeaderfFile报错

### ISSUE THREAD

**Issue by Blameying** [Yggdroot/LeaderF#153]
- vim or neovim?
    - [X] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 26 2018 23:00:19)

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.6m.so.1.0
- Output of `:py print(sys.version)`: 2.7.15 (default, May  1 2018, 20:16:04)
[GCC 7.3.1 20180406]
- Output of `:py3 print(sys.version)`: 3.6.5 (default, Apr 14 2018, 13:17:30)
[GCC 7.3.1 20180406]

- Operating system: 
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
nnoremap <leader>f :LeaderfFile<Enter>
nnoremap <leader>u :LeaderfFunctionAll<Enter>
nnoremap <leader>t :LeaderfTag<Enter>

### Describe your question, feature request, or bug.

当我使用LeaderfFile的时候出现这个
路径：/home/blamer/SourcePlan/KSDK2_MKV58F24

处理 function leaderf#File#startExpl[2]..leaderf#LfPy 时发生错误:
第    1 行:
‘’‘python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 603, in s
tartExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 767, in st
artExplorer
    self.input(content)
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 47, in dec
o
    func(self, *args, **kwargs)
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 817, in in
put
    for cmd in self._cli.input(partial(self.setContent, content)):
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 26, in deco
    for i in func(*args, **kwargs):
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 326, in input
    if lfEval("g:Lf_CursorBlink") == '1' and callback() == False:
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 779, in se
tContent
    for i, line in enumerate(itertools.islice(content, 10)):
  File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 80, 
in read
    raise Exception(lfEncode(lfBytes2Str(err)))
Exception: Usage: /usr/bin/pt command ...
Known commands:
^I/usr/bin/pt help ?TOPIC?
^I
^I^IProvides general help, or specific to the given topic.
^I/usr/bin/pt generate PFORMAT ?-option value...? PFILE INFORMAT GFILE
^I
^I^IGenerate data in format PFORMAT and write it to PFILE.  Read
^I^Ithe grammar to be processed from GFILE (assuming the format
^I^IGFORMAT). Use any options to configure the generator. The are
^I^Idependent on PFORMAT.
处理 function leaderf#File#startExpl 时发生错误:
第    2 行:
E171: 缺少 :endif
'''
只有部分目录存在该错误。

在参考前面issue的情况下展开后的报错为：

File "/home/blamer/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 80, 
in read
    raise Exception(err)
Exception: b'Usage: /usr/bin/pt command ...\n\nKnown commands:\n\n\t/usr/bin/pt help ?TOPIC?\n\t\n\t\t
Provides general help, or specific to the given topic.\n\n\t/usr/bin/pt generate PFORMAT ?-option valu
e...? PFILE INFORMAT GFILE\n\t\n\t\tGenerate data in format PFORMAT and write it to PFILE.  Read\n\t\t
the grammar to be processed from GFILE (assuming the format\n\t\tGFORMAT). Use any options to configur
e the generator. The are\n\t\tdependent on PFORMAT.\n\n'
处理 function leaderf#File#startExpl 时发生错误:

Thanks for your help.

**Comment by Yggdroot** [comment]
看一下`:echo g:Lf_Debug_Cmd`的输出是什么？这是你使用的命令，直接在出问题的目录下运行那个命令，看看有没有报错，我怀疑是pt的问题。
如果是pt的问题，建议使用rg，我感觉比pt快，还没那么多问题。

**Comment by Blameying** [comment]
出现这个
E121: 未定义的变量: g:Lf_Debug_Cmd
E15: 无效的表达式: g:Lf_Debug_Cmd

**Comment by Yggdroot** [comment]
你需要更新一下LeaderF。https://github.com/Yggdroot/LeaderF/commit/a1436347a3a0d2afcf4eefee650784eb2e3437de，这个commit加进去的。

**Comment by Blameying** [comment]
已经是最新版的了，有这个commit的记录

**Comment by Yggdroot** [comment]
要先运行一下`LeaderfFile`这个命令，再看`:echo g:Lf_Debug_Cmd`。

**Comment by Blameying** [comment]
pt --nocolor   -g="" "."
真的是麻烦您了

**Comment by Yggdroot** [comment]
不客气。

**Comment by 0chunhui** [comment]
所以这个问题是怎么解决的？

**Comment by Yggdroot** [comment]
> 所以这个问题是怎么解决的？

https://github.com/Yggdroot/LeaderF/issues/153#issuecomment-387716141

**Comment by 0chunhui** [comment]
大佬，我也输出了pt，但不明白rg是什么意思？怎么换？

**Comment by Yggdroot** [comment]
> 大佬，解决了。 想问问为啥用了好几年也没问题，今天突然出问题？

出了什么问题？
