### ISSUE TITLE
multiple autocmd

### ISSUE THREAD

**Issue by go2chenhua** [Yggdroot/LeaderF#155]
- [x ] neovim

NVIM v0.3.0-1201-g8ce639304

    - [x ] Windows 7

do:

:LeaderfBufTag
:LeaderfFunction

multi time

:au BufWipeout

--- Auto-Commands ---
BufWipeout
    *         call leaderf#BufTag#removeCache(expand('<abuf>'))
              call leaderf#BufTag#removeCache(expand('<abuf>'))
              call leaderf#Function#removeCache(expand('<abuf>'))
              call leaderf#Function#removeCache(expand('<abuf>'))
              call leaderf#BufTag#removeCache(expand('<abuf>'))
              call leaderf#BufTag#removeCache(expand('<abuf>'))

and 

VimLeave
    *         call GuiClose()
              call leaderf#BufTag#cleanup()
              call leaderf#BufTag#cleanup()
              call leaderf#Function#cleanup()
              ...
              call leaderf#Function#cleanup()
              call leaderf#Function#cleanup()j

### in python code

    def _defineMaps(self):
        lfCmd("call leaderf#Function#Maps()")
        lfCmd("autocmd BufWipeout * call leaderf#Function#removeCache(expand('<abuf>'))")
        lfCmd("autocmd VimLeave * call leaderf#Function#cleanup()")

**changed code**

    def _defineMaps(self):
        lfCmd("call leaderf#Function#Maps()")
        lfCmd("augroup LFGRP")
        lfCmd("autocmd!")
        lfCmd("autocmd BufWipeout * call leaderf#Function#removeCache(expand('<abuf>'))")
        lfCmd("autocmd VimLeave * call leaderf#Function#cleanup()")
        lfCmd("augroup END")

do:
LeaderfBufTag
LeaderfFunction

multi time:

:au BufWipeout

--- Auto-Commands ---
BufWipeout
    *         call leaderf#BufTag#removeCache(expand('<abuf>'))
              call leaderf#BufTag#removeCache(expand('<abuf>'))
LFGRP  BufWipeout
    *         call leaderf#Function#removeCache(expand('<abuf>'))

BUT:

when nvim quit, still slow,

**Comment by Yggdroot** [comment]
Thanks for your suggestion.
 Is it slow when quiting nvim if you don't use LeaderF?

**Comment by Yggdroot** [comment]
The multiple autocmds shown in your screenshot work as designed(except the g:Lf_VimResized), because they are attached to different event:
https://github.com/Yggdroot/LeaderF/blob/ddfcfe0b6c5b0370cae4e75c4f86b8acbda7803a/autoload/leaderf/python/leaderf/instance.py#L89-L92

How to reproduce the "Press ENTER..." issue? Could you describe the steps in more detail please?

**Comment by go2chenhua** [comment]
only plug 'leaderf'
start nvim
e $MYVIMRC

source ~/.config/nvim/config/plugins.vim
finish

:LeaderfFunction<cr>

sel, <cr>

:q<cr>

Press ENTER....
Press ENTER...
Press ENTER...
Press ENTER...


英文好累, 若你的电脑不出现这种问题, 那就算了. 应该是我的电脑环境问题. 谢了.

**Comment by go2chenhua** [comment]
添加 silent! 之后, 就没有 Press Enter... 了. 不过, 退出很慢. 可以忍受.

function! leaderf#Function#removeCache(bufNum)
    silent! call leaderf#LfPy("functionExplManager.removeCache(".a:bufNum.")")
endfunction

function! leaderf#Function#cleanup()
    silent! call leaderf#LfPy("functionExplManager._beforeExit()")
endfunction

**Comment by go2chenhua** [comment]
https://github.com/neovim/neovim/releases

Nvim development (pre-release) build

**Comment by Yggdroot** [comment]
你说的“Press Enter”的问题应该是neovim的bug。

**Comment by go2chenhua** [comment]
## 测试

```vim
function! Xxxd()
    py3 import subprocess; subprocess.Popen("cd", shell=True)
endfunction

" 退出不会
au VimLeave * silent! Xxxd

"　退出有问题   -> 循环 Press Enter .... 
" au VimLeave * silent py3 import subprocess; subprocess.Popen("cd", shell=True)

" 加 silent!  -> 没问题
" au VimLeave * silent! py3 import subprocess; subprocess.Popen("cd", shell=True)


" 未加 import subprocess;  -> Press Enter 一次, 等待很久 -> 符合 issue 
" au VimLeave * silent! py3 import subprocess; subprocess.Popen("cd", shell=True)

```

**Comment by go2chenhua** [comment]
写错了
安静退出, 无等待
au VimLeave * silent! call Xxxd()

**Comment by Yggdroot** [comment]
开了个issue，https://github.com/neovim/neovim/issues/8380

**Comment by go2chenhua** [comment]
## init.vim

autocmd! VimLeave * call leaderf#BufTag#cleanup() | call
leaderf#File#cleanup() | call leaderf#Function#cleanup() | call GuiClose()

## leaderf

comment 上面三个 autocmd
保证 GuiClose 在最后.

现在瞬间退出.

**Comment by go2chenhua** [comment]
## init.vim 
```vim
autocmd! VimLeave * call leaderf#BufTag#cleanup() | call leaderf#File#cleanup() | call leaderf#Function#cleanup() | call GuiClose() 
```

## leaderf 

comment 上面三个 autocmd 

保证 GuiClose 在最后. 

现在瞬间退出.

**Comment by go2chenhua** [comment]
使用 VimLeavePre, 也可以更好解决.
就不用 在 用户 init.vim 里 设置.

**Comment by Yggdroot** [comment]
不想因为neovim的bug，弄那么多弯弯绕的workaround，代码里已经有好多Neovim的workaround了，等Neovim稳定点再支持吧。
话说Neovim那么多bug，你为什么在windows上用Neovim，而不是gVim？

**Comment by go2chenhua** [comment]
最近才 从 sublime text 转过来.

试一下 gvim 吧, 不过 等我看完 nvim 的文档 再说, 毕竟 nvim 是未来, 就像 py3 一样.

不是 bug 吧, VimLeavePre 我是看了别人代码才知道的, 我装的其他插件没用 VimLeave.

本地修改代码, 还是比较好.

话说, 动态添加 autocmd, 有点频繁, 添加一次 autocmd 就行.

最后, 我还是 comment 了这些动态代码, comment 了 非 fuzzyMatchC 的实现.

thx.

**Comment by Yggdroot** [comment]
也许你是对的，使用VimLeavePre 确实没问题了，不过gVim使用VimLeave也没问题，我觉得这是neovim的bug。

**Comment by Yggdroot** [comment]
确认是neovim-qt的bug，https://github.com/equalsraf/neovim-qt/issues/394。

**Comment by Yggdroot** [comment]
我还没怎么用neovim就已经遇到一堆bug了，我都开了十来个issue了，https://github.com/neovim/neovim/issues/8382
这是一个新发现的。
