### ISSUE TITLE
tempfile.NamedTemporaryFile 缺少 encoding 时 出错

### ISSUE THREAD

**Issue by go2chenhua** [Yggdroot/LeaderF#156]
当 未保存文档 出现:

set listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨

![image](https://user-images.githubusercontent.com/4133216/39959517-5b5953c2-5645-11e8-9b8f-414ff0bddcba.png)

使用 utf-8 解决

            with tempfile.NamedTemporaryFile(mode='w+',
                                             encoding='utf-8',
                                             suffix='_'+os.path.basename(buffer.name),
                                             delete=False) as f:

**Comment by Yggdroot** [comment]
为什么关了？
这个问题是怎么复现的？你的vimrc里面设置了`set encoding=utf-8`了吗？

**Comment by go2chenhua** [comment]
'encoding' 'enc'	Removed. |vim-differences| {Nvim}
	Nvim always uses UTF-8 internally. RPC communication
	(remote plugins/GUIs) must use UTF-8 strings.

好像添加 一行 代码就解决了, 所以 关了.

**Comment by Yggdroot** [comment]
你使用的是Python3，Python2的NamedTemporaryFile（）没有encoding这个参数。
所以对于插件的修改，我不能简单的加上这么一句。而且还要考虑vim（not neovim）上，没有设置`set encoding=utf-8`的情况。

**Comment by go2chenhua** [comment]
这样啊.
我看了下代码, 好像为了用户的需求牺牲了性能.
还是不要修改好. 我自己本地改一下就行.
希望不要像 denite 那样, 越改越复杂.
leaderf 明显要快.
用了一下你的 fuzzyMatchC, 希望将来可以用在 deoplete 上.
thx.

**Comment by Yggdroot** [comment]
我在gvim上复现了，只有在是Python3的时候才会有错，你能帮忙确认一下你那边使用Python2是否报错吗？

**Comment by go2chenhua** [comment]
```py
from tempfile import NamedTemporaryFile


with NamedTemporaryFile(mode='w+', delete=False, suffix='xx_') as f:
    f.write("""set listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨""")
    # f.write("""xxxx""")
```

其实直接使用 py3 运行就会 报错.
py2:

```py
λ py2 D:/xx/Python/py3/py1.py
  File "D:/xx/Python/py3/py1.py", line 5
SyntaxError: Non-ASCII character '\xe2' in file D:/xx/Python/py3/py1.py on line 5, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details


```
别说运行, comment 掉 都不能运行.

**Comment by go2chenhua** [comment]
以上代码保存为 utf-8的

**Comment by go2chenhua** [comment]
py2 文档 添加

# coding: utf8

可以正常运行.

**Comment by go2chenhua** [comment]
```py
# coding: utf8
```

**Comment by Yggdroot** [comment]
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from tempfile import NamedTemporaryFile

with NamedTemporaryFile(mode='w+', delete=False, suffix='xx_') as f:
    f.write("""set listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨""")
    # f.write("""xxxx""")
```
有非ASCII字符，需要在代码开头加上`# -*- coding: utf-8 -*-`指定编码。你上面说的Python2的问题是一个common issue，不是NamedTemporaryFile的问题。
如果按照你这样测试的话，py2上是没有问题。
我在py3上修复一下。

**Comment by Yggdroot** [comment]
修复了。

**Comment by go2chenhua** [comment]
tempfile 频繁 读写, 不是很消耗资源吗?
再加上 动态运行求值...
反正我在本地删了这些兼容性代码. :smile:

**Comment by go2chenhua** [comment]
```py
from tempfile import NamedTemporaryFile
from functools import partial
if 3 > 2:
    fn = partial(NamedTemporaryFile, encoding='utf-8')
else:
    fn = NamedTemporaryFile

with fn(mode='w+', delete=False, suffix='_xx_') as f:
    f.write("ddddddddddddset listchars=tab:→\ ,nbsp:␣,trail:•,extends:⟩,precedes:⟨")

```
if 一次, 不用每次 if
顺便减少   .call

**Comment by Yggdroot** [comment]
首先，一个代码文件一般不是很大，这些操作在现代计算机上都会很快，一般不会有什么感觉。
其次，临时文件不是每次都使用的，当你代码有改动，但是还没有保存的时候才会用临时文件，这样保证你新加的一个函数也能看到。如果代码保存了，直接用磁盘上的文件，不会用临时文件。

**Comment by go2chenhua** [comment]
我知道未保存才用tempfile, 其实我之前就搜 能否 让 ctags daemon 运行, 别人早就提了. 是我想太多了吧, 也可能是我更关心我的电脑吧. 其实我是担心电费而已. 就这样吧.
