### ISSUE TITLE
Use Tab to go back to "insert" mode

### ISSUE THREAD

**Issue by romainf-unity** [Yggdroot/LeaderF#158]
- MacVim
- `mvim --version`:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 27 2018 11:10:27)
macOS version
```

(There's more information, like patches applied, options enabled by default, etc. I can paste it if you're interested)

- Output of `:echo has("python")`: 0 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): ""
- Output of `:echo &pythonthreedll`(only vim, not neovim): ""
- Output of `:py print(sys.version)`: `E319` (command not available)
- Output of `:py3 print(sys.version)`: `3.6.4 (default, Mar  9 2018, 23:15:03)`  
`[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]`
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: none

### Describe your question, feature request, or bug.

It would be nice if it's possible to also press <kbd>Tab</kbd> to go back to "insert" mode.

### Steps to reproduce

- `<Leader>F`
- Press <kbd>Tab</kbd>

### Actual behaviour

When pressing <kbd>Tab</kbd> it does nothing.

### Expected behaviour

When pressing <kbd>Tab</kbd> it goes back in "insert" mode (as if I pressed <kbd>i</kbd>).

**Comment by Yggdroot** [comment]
You can refer to the below:
https://github.com/Yggdroot/LeaderF/blob/7eada2057cb2cae4f50e6b7bc4b342ee96b730b9/doc/leaderf.txt#L429-L448
e.g.,
```vim
let g:Lf_NormalMap = { 
         \ "File":   [["<tab>", ':exec g:Lf_py "fileExplManager.input()"<CR>']]
         \ }

```

**Comment by romainf-unity** [comment]
Thanks, I'll try that locally, but don't you think it would be interesting to make it by default for everyone? It seems simpler (to me) to have one key to swap between modes.

**Comment by romainf-unity** [comment]
I added that in my `.vimrc` and it feels way more natural to use now:

```vim
"" LeaderF
let g:Lf_NormalMap = { 
         \ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>'],
         \            ["<TAB>", ':exec g:Lf_py "fileExplManager.input()"<CR>']
         \           ]
         \ }
```

It would be nice to have that by default IMHO.

**Comment by Yggdroot** [comment]
Sorry, I am already accustomed to "i", so I don't plan to change it.

**Comment by Yggdroot** [comment]
I think adding `<tab> ` instead of just replacing "i"  is another solution.

**Comment by romainf-unity** [comment]
Yep, I also think that adding is better since it doesn't change users habits.

**Comment by romainf-unity** [comment]
Just tested on File and Buffer pages, it works super nice, thanks! ;)
