### ISSUE TITLE
LeaderF produced a "divide by 0" error.

### ISSUE THREAD

**Issue by Yggdroot** [Yggdroot/LeaderF#16]
@chunmingli commented on commit [Yggdroot/LeaderF@8e5c6db83a](https://github.com/Yggdroot/LeaderF/commit/8e5c6db83a55b5a47a2b2e49617ead6680cb3873#commitcomment-18727096)
Hi, thanks for the great plugin. I wanted to report an issue. I came across a case where end == beg and LeaderF produced a "divide by 0" error.

**Comment by Yggdroot** [comment]
@chunmingli This issue has been fixed, please have a try.

**Comment by chunmingli** [comment]
@Yggdroot Works like a charm. Thanks for the quick turnaround!
