### ISSUE TITLE
Search result window auto closed after choose a item

### ISSUE THREAD

**Issue by rush3** [Yggdroot/LeaderF#160]
Latest verion commit : ....101485

- vim or neovim?
    - [ *] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:vim 8.1

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: yes
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Operating system: 
    - [ *] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
	1.Search result window closed automatically after choose one item by click <CR>, can the result window remain there until i leave Leadf.
	2. Any option to set position of file to be opened by default, like default value set to "right" in vim, not just by current cursor.
	By the way, Leaderf is much more fast and accuracy than CtrlP,  than  you for your valuable work. I will recommend my friends to switch to Leaderf

**Comment by Yggdroot** [comment]
Now you can use: `:Leaderf file --stayOpen`.
