### ISSUE TITLE
How to auto refresh cache of LeaderF after start vim?

### ISSUE THREAD

**Issue by bearzyj** [Yggdroot/LeaderF#161]
As the doc mentioned, after start LeaderF in vim, we can press F5 to refresh cache.

May I ask that, if I want Leader to **auto-refresh cache** every time I start vim, or at least every time I start LeaderF in vim, what shall I do?

**Comment by bearzyj** [comment]
您好，看到有人用中文和您交流。那我用中文也重述一下吧。

对于某个大型项目的目录，第一次使用LeaderF的时候一切都OK。
当我删除这个目录，重新下载一份该大型项目的全部文件后，有些新增文件，有些删除的文件。此时LeaderF还是会找到那些被删除的文件，但是新增的文件没有找到。

根据文档描述，在VIM里启动LeaderF后按下F5刷新一下缓存，确实能解决问题。

期间我也尝试了一下fzf，fzf似乎是每次自动刷新缓存。因此我想请教一下：

如果我希望在vim打开的时候自动刷新LeaderF的缓存，或者至少在我每次启动LeaderF的时候刷新一次（比起前一种，这一种似乎太频繁了），我应该怎样做呢？

感谢。

**Comment by Yggdroot** [comment]
可以设置`let g:Lf_UseCache = 0`。
纠正一下，fzf不是自动刷新缓存，是根本没有缓存，每次都是重新搜索。
