### ISSUE TITLE
支持PageUp/PageDown

### ISSUE THREAD

**Issue by winest** [Yggdroot/LeaderF#162]
- vim or neovim?
    - [v] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 10:15:55)

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.4m.so.1.0
- Output of `:py print(sys.version)`: None
- Output of `:py3 print(sys.version)`: 
3.4.5 (default, May 20 2018, 23:57:50)
[GCC 6.3.1 20170216 (Red Hat 6.3.1-3)]
- Operating system: 
    - [v] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
nnoremap <F3> :LeaderfFile<CR>
All other values are default

### Describe your question, feature request, or bug.
能否在:LeaderFile搜尋檔案時，除了Up、C-K、Down、C-J上下移動外
同時能用PageUp、PageDown操作？

以xterm為例，當前PageUp和PageDown的值可以從
infocmp | grep kpp >   knp=\E[6~, kpp=\E[5~,
所以在vim一般模式下輸入
:exe "normal \<Esc>[5~"可以送出PageUp往上翻頁
:exe "normal \<Esc>[6~"可以送出PageDown往下翻頁

我雖然試著改了下您的module但似乎無法達成
能否請您幫忙看看或加上？謝謝

[Add_PageUp_PageDown.txt](https://github.com/Yggdroot/LeaderF/files/2036004/Add_PageUp_PageDown.txt)

**Comment by winest** [comment]
早上又試了下，改成像lfCmd("exe \"normal \\<Esc>[5~\"")似乎就有反應了，但explorer會有錯
或是用lfCmd("norm! 10j")這類的方式做workaround，不知哪裡有顯示幾個檔案的變數可以直接拿不用hard code

**Comment by Yggdroot** [comment]
加好了。
