### ISSUE TITLE
leaderf will stuck on searching files after changing pwd.

### ISSUE THREAD

**Issue by kran** [Yggdroot/LeaderF#166]
- vim or neovim?
    - [x] vim
    - [*] neovim
- `nvim --version`: 
:version
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.0.4
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORT
IFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-c
olor=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-HJnLxJ/neovim-0.2.2/build/config -I/build/neovim-HJnLxJ/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr
/include -I/usr/include -I/usr/include -I/build/neovim-HJnLxJ/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-HJnLxJ/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609]

- Output of `:py3 print(sys.version)`: 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609]

- Operating system: 
    - [*] Linux (WSL)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
nmap <c-p> :LeaderfFile<cr>
imap <c-p> <c-o>:LeaderfFile<cr>
nmap <space>f :LeaderfFunction<cr>
nmap <space>b :LeaderfBuffer<cr>
nmap <space>t :LeaderfBufTag<cr>

### Describe your question, feature request, or bug.
stuck on searching.

### Steps to reproduce
1. run command `:LeaderfFile`, then ESC
2. run `:lcd /another/path` 
3. run `:LeaderfFile`, and then Leaderf will stuck on Searching...no matter how long you wait.
 
### Actual behaviour
as above

### Expected behaviour
show files list

**Comment by Yggdroot** [comment]
Can this issue be reproduced on a real Linux os?
I can not reproduce on Linux but not WSL.

**Comment by kran** [comment]
sorry, I don't have real linux os. 
but vim+leaderf works well in wsl.

**Comment by Yggdroot** [comment]
I think it is probably a bug of nvim on WSL.

**Comment by kran** [comment]
OK, thank you.
