### ISSUE TITLE
Can I set search mode in special cmd?

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#167]
ex:  
`:LeaderfFile --FullPath`
`:LeaderfLine --Regex`

**Comment by Yggdroot** [comment]
No. I don't see any necessity of these options since you can switch between the mode easily.

**Comment by pacidic** [comment]
I'd also be interested in this feature. I use the following to jump to the header file included in the line under the cursor:

```
function! g:StripInclude(line)
    let strip_include = substitute(a:line, '\v.*[\<"]([a-zA-Z0-9_/\.]+)[\>"]', '\1', 'g')
    return strip_include
endfunction
nnoremap <Leader>j :exec "LeaderfFilePattern ".g:StripInclude(getline("."))<CR>
```
As far as I can tell, currently only toggling of the search mode using e.g. <C-r> is supported. However, I'd like to call this command in regex mode, regardless of which mode I was in before.

**Comment by Yggdroot** [comment]
This feature will be added in the future.

**Comment by fcying** [comment]
Looking forward to your updates~

**Comment by Yggdroot** [comment]
Now may options are available, you can use `Leaderf file --fullPath`, please turn to `:Leaderf file -h` for more information.
@pacidic `Leaderf file --input` is equivalent to `LeaderfFilePattern` now.

**Comment by fcying** [comment]
@Yggdroot  Leaderf file can use special search mode now. 
Is leaderline not yet added?

**Comment by Yggdroot** [comment]
You can use `:Leaderf line`, also available for `Leaderf` + `mru, bufTag, funtion, buffer ...`

**Comment by fcying** [comment]
@Yggdroot  Great~ Thanks for your help~~ It work fine~
