### ISSUE TITLE
leaderf require `filetype plugin indent on`

### ISSUE THREAD

**Issue by zgpio** [Yggdroot/LeaderF#170]
- vim or neovim?
    - [x] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:
    latest

- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows

- Configurations related to LeaderF in vimrc: 
    
### Describe your question, feature request, or bug.
    if `filetype plugin indent on` is not set, leaderf's statusline display incorrect, just like:
![default](https://user-images.githubusercontent.com/19503791/40918239-49f17c18-6838-11e8-8a87-7d8bcc38665e.png)

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by zgpio** [comment]
emmm, 我在最小化配置中测试了，确实不能复现，是其他问题，...
