### ISSUE TITLE
After install LeadeF, use vim it informed :Unknown function: lfMru#record; commented the augroup, it works well

### ISSUE THREAD

**Issue by mumuchong** [Yggdroot/LeaderF#171]
- vim or neovim?
    - [√] vim
    - [ ] neovim
- `vim --version` or `nvim --version`:
VIM - Vi IMproved 8.1
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
nothing
- Output of `:py print(sys.version)`: 
command is not available
- Output of `:py3 print(sys.version)`: 
3.6.5 (default, Jun  4 2018, 05:05:21)
[GCC 4.3.4 [gcc-4_3-branch revision 152973]]
- Operating system: 
    - [√] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
do nothing for now
### Describe your question, feature request, or bug.
 I got the LeaderF latest from https://github.com/Yggdroot/LeaderF and installed it , all steps goes well until I use vim . Some of the problems encountered when I start VIM, it informed as follow:
              Error detected while processing BufEnter Auto commands for "*":
              E117: Unknown function: lfMru#record
accounding the info , I commented this function in th file leader.vim , but it work well 
This is the code in ~/.vim/plugin/leaderf.vim i commented:
241 "comment out by yishi since unknow function
242 "augroup LeaderF_Mru
243 "    autocmd BufAdd,BufEnter,BufWritePost * call lfMru#record(expand('<afile>:p')) |
244 "                \ call lfMru#recordBuffer(expand('<abuf>'))
245 "augroup END

So why I have to commented this function so it can work, Does something in my enviroment goes wrong?
### Actual behaviour
commented augroup,it can work s well
### Expected behaviour
Do not commented the augroup,I can use LeaderF after installed.

**Comment by mumuchong** [comment]
After commented the augroup, it no longer informed error when use vim,but also can not open LeaderF in command mode in VIM

**Comment by Yggdroot** [comment]
How did you install LeaderF?
What is the output of `:script`?

**Comment by Yggdroot** [comment]
```
but also can not open LeaderF in command mode in VIM
```
what does this mean?

**Comment by Hezhiqing** [comment]
I've encountered this same issue.
my vim version is vim8.1(OS: linux 2.6.18, Red Hat 4.1.2), and  echo has("python")  gets "1" , echo has("python3") gets "0"
How did I install LeaderF?   --I Just put the file leader.vim in my ~/.vim/plugin/ folder.
What is the output of :script?  -- as followes:
  1: ~/.vimrc
  2: /usr/share/vim/vim81/defaults.vim
  3: /usr/share/vim/vim81/syntax/syntax.vim
  4: /usr/share/vim/vim81/syntax/synload.vim
  5: /usr/share/vim/vim81/syntax/syncolor.vim
  6: /usr/share/vim/vim81/filetype.vim
  7: /usr/share/vim/vim81/ftplugin.vim
  8: /usr/share/vim/vim81/indent.vim
  9: ~/.vim/plugin/leaderf.vim
 10: ~/.vim/plugin/tagbar.vim
 11: /usr/share/vim/vim81/plugin/getscriptPlugin.vim
 12: /usr/share/vim/vim81/plugin/gzip.vim
 13: /usr/share/vim/vim81/plugin/logiPat.vim
 14: /usr/share/vim/vim81/plugin/manpager.vim
 15: /usr/share/vim/vim81/plugin/matchparen.vim
 16: /usr/share/vim/vim81/plugin/netrwPlugin.vim
 17: /usr/share/vim/vim81/plugin/rrhelper.vim
 18: /usr/share/vim/vim81/plugin/spellfile.vim
 19: /usr/share/vim/vim81/plugin/tarPlugin.vim
 20: /usr/share/vim/vim81/plugin/tohtml.vim
 21: /usr/share/vim/vim81/plugin/vimballPlugin.vim
 22: /usr/share/vim/vim81/plugin/zipPlugin.vim
 23: /usr/share/vim/vim81/pack/dist/opt/matchit/plugin/matchit.vim
 24: /usr/share/vim/vim81/autoload/dist/ft.vim
 25: /usr/share/vim/vim81/syntax/c.vim
 26: /usr/share/vim/vim81/ftplugin/c.vim
 27: /usr/share/vim/vim81/indent/c.vim

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by dreamerlzl** [comment]
I have encounter this problem recently and it's fixed after updating pynvim
