### ISSUE TITLE
是否需要一个忽略某些目录以及限制搜索范围的配置选项?

### ISSUE THREAD

**Issue by ta7sudan** [Yggdroot/LeaderF#173]
抱歉英语不太好...
对于搜索文件和文件内容功能, 请问是否可以提供一个忽略某些目录的配置选项? 以及根据某些文件, 比如 package.json, pom.xml 等, 定位项目根目录, 限制搜索范围在此目录的配置选项?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/bb1c8a79fb1b02da912904ef71d7d62bf9769e18/doc/leaderf.txt#L138-L162

https://github.com/Yggdroot/LeaderF/blob/bb1c8a79fb1b02da912904ef71d7d62bf9769e18/doc/leaderf.txt#L450-L474

**Comment by ta7sudan** [comment]
抱歉没注意到文档, 非常感谢!
