### ISSUE TITLE
LeaderF搜索结果显示栏可以自适应大小吗？改变目录有更简单的方式吗？

### ISSUE THREAD

**Issue by GooCoder** [Yggdroot/LeaderF#175]
自适应大小其实还好，习惯了就好了。。
但是改变目录该怎么办呢？每次都要`:LeaderfFile [dir]`吗？

**Comment by Yggdroot** [comment]
改变目录目前只有这种方法，你想怎样方便？

**Comment by GooCoder** [comment]
我期待支持输入`..`或者更多的`.`用来返回上级目录。。因为我需要的文件往往不在当前工作目录。

**Comment by Yggdroot** [comment]
..支持的呀

**Comment by GooCoder** [comment]
`README.md`里面应该没有说支持这个功能吧。我在电脑上运行`..`没有作用啊。难道是我姿势不对？

**Comment by GooCoder** [comment]
您好，为什么我`PlugUpdate`之后还是不能用`..`。不是修复了吗？

**Comment by Yggdroot** [comment]
不知道，是不是PlugUpdate这个命令有问题，你可以试试卸载后再重新完整安装看看。

**Comment by Yggdroot** [comment]
看看代码是否包含8f0dbb1这个commit。
