### ISSUE TITLE
和autocd结合的话如何操作？

### ISSUE THREAD

**Issue by RichyMong** [Yggdroot/LeaderF#177]
使用ctrlp没遇到过这个问题。用LeaderF打开个文件工作目录变了之后，就没法用了。
似乎没找到可以配置使用绝对的路径，谢谢！

**Comment by RichyMong** [comment]
抱歉，我没说清楚。不过没复杂应用场景，需要的就是这个设置。偷懒了，应该help看下的。谢谢！
建议加到README里，autochdir这个选项开的人应该比较多。
再请教个问题啊，有没办法在LeaderF中同时显示file, mru等的。就是说可以在这几个中切换，不用LeaderfBuf，LeaderfMru这样去打开。当然用了key map也快，但用习惯了ctrlp，另外也不希望记那么多key.

**Comment by Yggdroot** [comment]
目前还没有这个功能。我还没有感觉到这个功能的必要性。

**Comment by RichyMong** [comment]
ok. 那我自己fork吧:)
