### ISSUE TITLE
git文件夹支持请求

### ISSUE THREAD

**Issue by sillybun** [Yggdroot/LeaderF#179]
非常感谢您的插件！

我想请问能否增加这样的功能：
在一个git的文件夹下，用LeaderfFile的话，是默认从git的根目录而不是当前目录进行搜索，就像是ctrlp一样。

**Comment by Yggdroot** [comment]
这个功能已经有了：
https://github.com/Yggdroot/LeaderF/blob/d222b2187b359b484435628bb64829c724c453ad/doc/leaderf.txt#L450-L474

**Comment by sillybun** [comment]
好的！我已经配置好了。
我用的是：
let g:Lf_WorkingDirectoryMode = 'a'
因为如果用A的话，出现的问题是如果不打开文件的话（直接进入vim），然后运行Leaderf的话，不会向上进行搜索。
Thank you very much

**Comment by Yggdroot** [comment]
这么客气，给个star呗。

**Comment by sillybun** [comment]
当然啦。我下意识点了一下，结果发现自己star过了。。
