### ISSUE TITLE
Is it possible to load the cache according to the path ?

### ISSUE THREAD

**Issue by johnzeng** [Yggdroot/LeaderF#18]
I may work on multiple projects in one day, I wanna use the mru feature but the cache is saved for all projects, is is possible to save the cache according to the current path?

Like, I have three projects under:
~/projA
~/projB
~/projC

I may save three cache file naming:
~/projA/.leaderf
~/projB/.leaderf
~/projC/.leaderf

Is it possible?

**Comment by Yggdroot** [comment]
Good point. I'll consider it.

**Comment by Misfit-John** [comment]
I tried to set `let g:Lf_CacheDiretory = '.'` , it works, but it will create .LfCache file every where, maybe we can make a setting that if you use a relative path, leaderf will check the relative path, if it doesn't have .LfCache file, it will still use the default cache path.

**Comment by Yggdroot** [comment]
Please use new added command `LeaderfMruCwd`.

**Comment by johnzeng** [comment]
great

**Comment by johnzeng** [comment]
great

**Comment by johnzeng** [comment]
great

**Comment by johnzeng** [comment]
great

**Comment by johnzeng** [comment]
great

**Comment by johnzeng** [comment]
great

**Comment by johnzeng** [comment]
great
