### ISSUE TITLE
Search dir is same when two tabpage's work dir is different.

### ISSUE THREAD

**Issue by Cosson2017** [Yggdroot/LeaderF#181]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Search dir is same when two tabpage's work dir is different.

**Comment by Cosson2017** [comment]
I usually use a tabpage for a project,Two tabpage's dir are different pojects. So I expect leaderf work dir is different for two tabpages where dir setted different by 'tcd'

**Comment by Yggdroot** [comment]
Please refer to https://github.com/Yggdroot/LeaderF/blob/d222b2187b359b484435628bb64829c724c453ad/doc/leaderf.txt#L450-L474.

**Comment by Cosson2017** [comment]
@Yggdroot  I use 'tcd' cmd to set different tabpages. It is still change when I set g:Lf_WorkingDirectoryMode.
Calling getcwd() show different dir when use 'tcd' cmd setting work dir.

**Comment by Yggdroot** [comment]
我不知道有个命令是`tcd`，你的vim版本是多少？
你设置`let g:Lf_WorkingDirectoryMode = 'a'` 不可用吗？

**Comment by Yggdroot** [comment]
tcd是neovim的命令，为什么你勾选的是vim？

**Comment by Yggdroot** [comment]
改好了，不用设置 g:Lf_WorkingDirectoryMode。

**Comment by Cosson2017** [comment]
@Yggdroot Nice 非常感谢
