### ISSUE TITLE
不改变工作目录

### ISSUE THREAD

**Issue by meijieru** [Yggdroot/LeaderF#182]
在如下设置的情况下，运行`Leaderf file`会将vim的工作目录设置为包含`root_marker`的目录
```
let g:Lf_WorkingDirectoryMode = 'ac'
```
但改变vim的工作目录会带来一些问题，比如有如下目录结构
```
root
    .git
    src (work here)
        test
```
我会定时自动运行 `src/test` 中的测试文件，要求工作目录为 `src`，如果工作目录被设置为 `root` 会遇到包导入的问题

**Comment by Yggdroot** [comment]
当leaderf退出的时候，会恢复到原来的工作路径。

**Comment by meijieru** [comment]
嗯，但这样还是有影响的，比如上述的例子

**Comment by Yggdroot** [comment]
你定时运行src/test可以使用绝对路径呀。

**Comment by meijieru** [comment]
我有挺多工程遵循这个模式的，不能把路径写死啊
