### ISSUE TITLE
add support for GNU Global?

### ISSUE THREAD

**Issue by linusboyle** [Yggdroot/LeaderF#191]
`g:Lf_Ctags` doesn't work for gtags,no matter what I set it to be,`gtags` or `global` or `gtags-cscope`.It seems only ctags is supported right now. Anyway,I can use cscope and just lack some fuzzy and regex things,but maybe you can enhance this great plugin?

**Comment by 9527KGG** [comment]
+1

**Comment by renchili** [comment]
+1

**Comment by xaljer** [comment]
I think fuzzy find symbol reference of gtags (or some other provider) is also very useful feature.

**Comment by linusboyle** [comment]
Well, it's not difficult to script myself if #144 is implemented. Likewise the ctags support will be unnecessary then

**Comment by 9527KGG** [comment]
GNU Global support is great. But I think ctags support is a fundamental need though~

**Comment by Yggdroot** [comment]
`Leaderf gtags -h`:
```java
usage: 
Leaderf[!] gtags [-h] [--remove] [--recall] [--all]
Leaderf[!] gtags --update [--gtagsconf <FILE>] [--gtagslabel <LABEL>] [--accept-dotfiles]
                 [--skip-unreadable] [--skip-symlink [<TYPE>]] [--gtagslibpath <PATH> [<PATH> ...]]
Leaderf[!] gtags -d <PATTERN> [-i] [--literal] [--path-style <FORMAT>] [-S <DIR>] [--append]
                 [--match-path] [--gtagsconf <FILE>] [--gtagslabel <LABEL>] [COMMON_OPTIONS]
Leaderf[!] gtags -r <PATTERN> [-i] [--literal] [--path-style <FORMAT>] [-S <DIR>] [--append]
                 [--match-path] [--gtagsconf <FILE>] [--gtagslabel <LABEL>] [COMMON_OPTIONS]
Leaderf[!] gtags -s <PATTERN> [-i] [--literal] [--path-style <FORMAT>] [-S <DIR>] [--append]
                 [--match-path] [--gtagsconf <FILE>] [--gtagslabel <LABEL>] [COMMON_OPTIONS]
Leaderf[!] gtags -g <PATTERN> [-i] [--literal] [--path-style <FORMAT>] [-S <DIR>] [--append]
                 [--match-path] [--gtagsconf <FILE>] [--gtagslabel <LABEL>] [COMMON_OPTIONS]
Leaderf[!] gtags --by-context [-i] [--literal] [--path-style <FORMAT>] [-S <DIR>] [--append]
                 [--match-path] [--gtagsconf <FILE>] [--gtagslabel <LABEL>] [COMMON_OPTIONS]

[COMMON_OPTIONS]: [--reverse] [--stayOpen] [--input <INPUT> | --cword]
                  [--top | --bottom | --left | --right | --belowright | --aboveleft | --fullScreen]
                  [--nameOnly | --fullPath | --fuzzy | --regexMode] [--nowrap]
 
optional arguments:
  -h, --help            show this help message and exit

specific arguments:
  --update              Create tag files if tag files do not exist, update the tag files otherwise.
  --remove              Remove the tag files generated.
  --accept-dotfiles     Accept files and directories whose names begin with a dot. By default, gtags
                        ignores them.
  --skip-unreadable     Skip unreadable files.
  --gtagsconf <FILE>    Set environment variable GTAGSCONF to <FILE>.
  --gtagslabel <LABEL>  Set environment variable GTAGSLABEL to <LABEL>.
  --skip-symlink [<TYPE>]
                        Skip symbolic links. If type is 'f' then skip only symbolic links for file, else
                        if 'd' then skip only symbolic links for directory. The default value of type is
                        'a' (all symbolic links).
  --gtagslibpath <PATH> [<PATH> ...]
                        Specify the paths to search for library functions.
  -d <PATTERN>, --definition <PATTERN>
                        Show locations of definitions.
  -r <PATTERN>, --reference <PATTERN>
                        Show reference to a symbol which has definitions.
  -s <PATTERN>, --symbol <PATTERN>
                        Show reference to a symbol which has no definition.
  -g <PATTERN>, --grep <PATTERN>
                        Show all lines which match to the <PATTERN>.
  --by-context          Decide tag type by context at cursor position. If the context is a definition of
                        the pattern then use -r, else if there is at least one definition of the pattern
                        then use -d, else use -s. Regular expression is not allowed for pattern.
  -i, --ignore-case     Ignore case distinctions in the pattern.
  --literal             Execute literal search instead of regular expression search.
  --path-style <FORMAT>
                        Show path names using <FORMAT>, which may be one of: `relative`, `absolute`,
                        `shorter`, `abslib` or `through`. `relative` means relative path. `absolute`
                        means absolute path. `shorter` means the shorter one of relative and absolute
                        path. `abslib` means absolute path for libraries (GTAGSLIBPATH) and relative path
                        for the rest. `through` means the relative path from the project root directory
                        (internal format of GPATH). The default is `relative`.
  -S <DIR>, --scope <DIR>
                        Show only tags which exist under <DIR> directory.
  --recall              Recall last search. If the result window is closed, reopen it.
  --append              Append to the previous search results.
  --match-path          Match the file path when fuzzy searching.
  --all                 search tags in all opening buffers

common arguments:
  --reverse             show results in bottom-up order
  --stayOpen            don't quit LeaderF after accepting an entry
  --input <INPUT>       specifies INPUT as the pattern inputted in advance
  --cword               current word under cursor is inputted in advance
  --top                 the LeaderF window is at the top of the screen
  --bottom              the LeaderF window is at the bottom of the screen
  --left                the LeaderF window is at the left of the screen
  --right               the LeaderF window is at the right of the screen
  --belowright          the LeaderF window is at the belowright of the screen
  --aboveleft           the LeaderF window is at the aboveleft of the screen
  --fullScreen          the LeaderF window takes up the full screen
  --nameOnly            LeaderF is in NameOnly mode by default
  --fullPath            LeaderF is in FullPath mode by default
  --fuzzy               LeaderF is in Fuzzy mode by default
  --regexMode           LeaderF is in Regex mode by default
  --nowrap              long lines in the LeaderF window won't wrap

If [!] is given, enter normal mode directly.
```

**Comment by linusboyle** [comment]
@Yggdroot Thanks for implementing this feature. 
I think maybe I should take time to have a test of it, but at least the major problem is solved.Closed

**Comment by xaljer** [comment]
Can `Leaderf gtags` use exist gtags files managed by other vim plugin like gen_tags.vim?

**Comment by Yggdroot** [comment]
@xaljer No. LeaderF can manage the gtags files very well.

**Comment by xaljer** [comment]
so Leaderf can auto update tags when file is changed? that sounds great. I do not find an option to specify location of tag file. where are gtags files, and can i change it?

**Comment by linusboyle** [comment]
> where are gtags files, and can i change it?
@xaljer the tag file is in the cache folder you set and of course you can change it.

So far my experience with gtags feature is excellent. Despite the lack of several other cscope interface query methods such as include hierarchy, leaderf functions even better than gutentags. Haven't test and don't know if leaderf can update the database on writeout, but otherwise a single line vimscript can achieve this.

**Comment by Yggdroot** [comment]
@xaljer Yes, tags can be updated automatically when a file is changed if `g:Lf_GtagsAutoGenerate` is 1. `g:Lf_GtagsAutoGenerate` is 0 by default.
The location of tag files is at `$HOME/.LfCache/gtags/%PATH%OF%YOUR%PROJECT/`, `%PATH%OF%YOUR%PROJECT` is generated by replacing the seperator `\` or `/` in the path of your project with `%`. But I don't think you need to change the tag files.

@linusboyle Some features of cscope will be implemented in the future.

**Comment by xaljer** [comment]
I think it would be more convenient for `definition` to jump directly if there is only one result. May be you can provide an option to do that. @Yggdroot .

**Comment by Yggdroot** [comment]
@xaljer Now you can add `--auto-jump` to jump to the tag directly when there is only one match.

**Comment by linusboyle** [comment]
> @xaljer Now you can add `--auto-jump` to jump to the tag directly when there is only one match.

@Yggdroot BTW, Now that LeaderF has evolved into a powerful tag management tool, I'm wondering if it's possible to simulate the quickfix list. As leaderf stores the location info and it would be nice to have something like `:leaderfnext` and `leaderfprevious`, especially dealing with tags.

**Comment by xaljer** [comment]
@Yggdroot , Thank you:-)

**Comment by Yggdroot** [comment]
> @Yggdroot BTW, Now that LeaderF has evolved into a powerful tag management tool, I'm wondering if it's possible to simulate the quickfix list. As leaderf stores the location info and it would be nice to have something like `:leaderfnext` and `leaderfprevious`, especially dealing with tags.

In normal mode, you can use `j`, `k` to navigate the result, I don't think  `:leaderfnext` and `leaderfprevious` are necessary.

**Comment by linusboyle** [comment]
I think it's not so convenient to navigate to the leaderf window and use jk
to jump. If the window is closed I will have to open it manually, which is
annoying. If leaderf can provide a mean to jump without opening the window
it would be nice

Yggdroot <notifications@github.com> 于 2019年4月30日周二 上午9:56写道：

**Comment by Yggdroot** [comment]
@linusboyle Now `--next` and `--previous` are available for your requirement.
You can use it like this:
```
:Leaderf gtags --next
:Leaderf gtags --previous
```
`Leaderf <category> [--next | --previous]` , category can be any subcommand supported.

**Comment by haihualuo** [comment]
I'm having an issue to navigate to code in a different location (as library).

Assume my username is 'john' and I have two directories with their respective GTAGS file

1) ~/foo/one.c  with gtags generated in ~/.LfCache/gtags/%home%john%foo
2) ~/bar/two.c  with gtags generated in ~/.LfCache/gtags/%home%john%bar

I wrote a small script to produce $GTAGSLIBPATH. So, "echo $GTAGSLIBPATH" on my machine outputs "/home/john/.LfCache/gtags/%home%john%foo:/home/john/.LfCache/gtags/%home%john%bar"

Now, when I'm in "foo/" and look up symbols in foo, everything works beautifully. But when I tried looking up symbol in "bar/", path in result is wrong. Let me explain:

1) I opened foo/one.c in VIM, move my cursor over a symbol that I knew is defined in bar/two.c. Then issue the command:

:<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>

2) The result says path to destination source file is:

/home/john/.LfCache/gtags/%john%bar%/two.c

The part "%john%bar%/two.c" seems correct. The line number in "two.c" is also correct. But
the complete path "/home/john/.LfCache/gtags/%john%bar%/two.c" doesn't help - in fact no file exists there, thus selecting the result makes VIM open an empty buffer for new file.

**Comment by Yggdroot** [comment]
I think you have misunderstood the meaning of **$GTAGSLIBPATH**, as described in https://www.gnu.org/software/global/globaldoc_toc.html.

```
If you want to locate symbols that are not defined in the source tree, then you can specify library directories with GTAGSLIBPATH environment variable.
You should execute gtags(1) at each directory in the GTAGSLIBPATH. If GTAGS is not found there, global ignores such directories.

    $ pwd
    /develop/src/mh                 # this is a source project
    $ gtags
    $ ls G*TAGS
    GRTAGS  GTAGS
    $ global mhl
    uip/mhlsbr.c                    # mhl() is found
    $ global strlen                 # strlen() is not found
    $ (cd /usr/src/lib; gtags)      # library source
    $ (cd /usr/src/sys; gtags)      # kernel source
    $ export GTAGSLIBPATH=/usr/src/lib:/usr/src/sys
    $ global strlen
    ../../../usr/src/lib/libc/string/strlen.c  # found in library
    $ global access
    ../../../usr/src/sys/kern/vfs_syscalls.c   # found in kernel
```
If you use LeaderF, you don't have to manage gtags by yourself, LeaderF can help to do it.
So 
> I opened foo/one.c in VIM, move my cursor over a symbol that I knew is defined in bar/two.c. Then issue the command:

All what you need to do is:
1. `Leaderf gtags --update --gtagslibpath ~/bar` to generate the gtags for both `~/foo` and `~/bar`.
2. :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>

**Comment by haihualuo** [comment]
> I think you have misunderstood the meaning of **$GTAGSLIBPATH**, as described in https://www.gnu.org/software/global/globaldoc_toc.html.
>
> ```
> If you want to locate symbols that are not defined in the source tree, then you can specify library directories with GTAGSLIBPATH environment variable.
> You should execute gtags(1) at each directory in the GTAGSLIBPATH. If GTAGS is not found there, global ignores such directories.

The description appears to align with my understanding. My operations are as follows:

1) Go to foo, open one.c. Witness "gtags successful" msg in VIM
2) Go to bar, open two.c. Witness the same message in VIM

After that, I could see two sets of gtag files under appropriate .LfCache/gtags subdirectories. 

> 
>     $ pwd
>     /develop/src/mh                 # this is a source project
>     $ gtags
>     $ ls G*TAGS
>     GRTAGS  GTAGS
>     $ global mhl
>     uip/mhlsbr.c                    # mhl() is found
>     $ global strlen                 # strlen() is not found
>     $ (cd /usr/src/lib; gtags)      # library source
>     $ (cd /usr/src/sys; gtags)      # kernel source
>     $ export GTAGSLIBPATH=/usr/src/lib:/usr/src/sys
>     $ global strlen
>     ../../../usr/src/lib/libc/string/strlen.c  # found in library
>     $ global access
>     ../../../usr/src/sys/kern/vfs_syscalls.c   # found in kernel
> ```
> 
> If you use LeaderF, you don't have to manage gtags by yourself, LeaderF can help to do it.
> So
> 
> > I opened foo/one.c in VIM, move my cursor over a symbol that I knew is defined in bar/two.c. Then issue the command:
> 
> All what you need to do is:
> 
> 1. `Leaderf gtags --update --gtagslibpath ~/bar` to generate the gtags for both `~/foo` and `~/bar`.
> 2. `:<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>`

I actually have many foo, bar (not just 2 source trees). Therefore it is more convenient for me to generate respective gtags files by going to each individual source trees vs. appending a long list of source tree parameter with "--gtagslibpath". What's the difference between the two operations (go to each tree vs. using --gtabslibpath repeatedly)?

Another observation is that finding symbols in tree B while I'm in tree A kind of works already, Leaderf did return the "semi-correct" path, but it is escaped with % and appended to the cache directory.

**Comment by haihualuo** [comment]
> > I think you have misunderstood the meaning of **$GTAGSLIBPATH**, as described in https://www.gnu.org/software/global/globaldoc_toc.html.

Given source tree A, B and C, it is required that while in tree A, lib points to only {B, C}, while in tree B, lib points only to {A, C} and so forth? I previously tried gutentags / gutentags_plus with exporting {A, B, C} as gtagslibpath (i.e. no matter which tree I'm in, the lib value is always {A, B, C}) and it worked for me, i.e. in any tree, I can always precisely locate symbols/references in the other 2 trees.

**Comment by Yggdroot** [comment]
@haihualuo 
> The description appears to align with my understanding.

$GTAGSLIBPATH is a global environment variable, LeaderF does not use or read it. However gtags will respect the value of it. $GTAGSLIBPATH indicates the paths of the source code, so there is
```
$ export GTAGSLIBPATH=/usr/src/lib:/usr/src/sys
$ global strlen
../../../usr/src/lib/libc/string/strlen.c  # found in library
```
`libc/string/strlen.c` is in the directory `/usr/src/lib`. You said 
> "echo $GTAGSLIBPATH" on my machine outputs "/home/john/.LfCache/gtags/%home%john%foo:/home/john/.LfCache/gtags/%home%john%bar"

`/home/john/.LfCache/gtags/%home%john%foo` is actually where LeaderF stores the gtags, not the directory of source code. If you use **$GTAGSLIBPATH**, the gtags database files are supposed to be generated in the directory pointed by **$GTAGSLIBPATH**. So, as per your example,  you should generate gtags database file in `~/bar/` and `export GTAGSLIBPATH=~/bar/`. Is that clear about **$GTAGSLIBPATH**?

------
> What is the difference between specifying all the source trees in GTABSLIBPATH vs. having them specified in multiple "--gtagslibpath x", "--gtagslibpath y", "--gtagslibpath z" ... fashion?

To specify multiple paths, the usage is `--gtagslibpath x y z ...`.
The difference is that LeaderF can manage the gtags database files for all the paths x, y, z... if use `--gtagslibpath x y z ...`, if use **$GTAGSLIBPATH**, the gtags database files have to be put in x, y, z... respectively. Another **advantage** is that LeaderF can handle such a scenario: source tree A, libpath of A is D, E. source tree B, libpath of B is F, G.  If you use **$GTAGSLIBPATH**, you have to specify `export GTAGSLIBPATH=D:E:F:G`, suppose a symbol `foo` is defined in all the D, E, F, G, so if you search the definition of `foo` in source tree A, the definitions in F, G are also listed.

> Given source tree A, B and C, is it required that while in tree A, lib points to only {B, C}, while in tree B, lib points only to {A, C} and so forth? I previously tried gutentags / gutentags_plus with exporting {A, B, C} as gtagslibpath (i.e. no matter which tree I'm in, the lib value is always {A, B, C}) and it worked for me, i.e. in any tree, I can always precisely locate symbols/references in the other 2 trees.

I find I have already answered this question.

**Comment by haihualuo** [comment]
> If you use **$GTAGSLIBPATH**, the gtags database files are supposed to be generated in the directory pointed by **$GTAGSLIBPATH**. So, as per your example, you should generate gtags database file in `~/bar/` and `export GTAGSLIBPATH=~/bar/`. Is that clear about **$GTAGSLIBPATH**?

Understand. But one major benefit of Leaderf+gtags / gutentags / gutentags_plus is that the G*TAGS files are located centrally at a different location, away from source tree. In Leaderf, I have:

let g:Lf_CacheDirectory = expand('~/.cache/leaderf')

So all the G*TAGS files are there. AFAIK, GTAGSLIBPATH must points to directories that contains these G*TAGS file. It is not required that such location is part of source tree (otherwise the major benefit would not be possible).

Therefore, I set the value of GTAGSLIBPATH to "~/.cache/leaderf/gtags/%some_tree%" - that is my real config vs. "foo/bar" are just examples in my previous comment.

Btw, I found Leaderf superior to gutentags/gutentags_plus. But when using gutentags/gutentags_plus, I set up my GTAGSLIBPATH exactly the same way - it points to ~/.cache/tags/my_source_tree[1234..], as I have following:

let g:gutentags_cache_dir = expand('~/.cache/tags')

... and my source trees are in /my/source/tree[1234...] (gutentags uses "_" vs. "%")

> 
> > What is the difference between specifying all the source trees in GTABSLIBPATH vs. having them specified in multiple "--gtagslibpath x", "--gtagslibpath y", "--gtagslibpath z" ... fashion?
> 
> To specify multiple paths, the usage is `--gtagslibpath x y z ...`.
> The difference is that LeaderF can manage the gtags database files for all the paths x, y, z... if use `--gtagslibpath x y z ...`, 

> if use **$GTAGSLIBPATH**, the gtags database files have to be put in x, y, z... respectively. 

As described above, it is not the case for gutentags/gutentags_plus.

> Another **advantage** is that LeaderF can handle such a scenario: source tree A, libpath of A is D, E. source tree B, libpath of B is F, G. If you use **$GTAGSLIBPATH**, you have to specify `export GTAGSLIBPATH=D:E:F:G`, suppose a symbol `foo` is defined in all the D, E, F, G, so if you search the definition of `foo` in source tree A, the definitions in F, G are also listed.

That is a good point.

**Comment by Yggdroot** [comment]
@haihualuo  

> AFAIK, GTAGSLIBPATH must points to directories that contains these GTAGS file. It is not required that such location is part of source tree (otherwise the major benefit would not be possible).

I don't think so. You can try $GTAGSLIBPATH in command line(run gtags command in command line).
The benefit is because there are many codes to handle the logic to wrok as expected, we can call it as workaround.

> But when using gutentags/gutentags_plus, I set up my GTAGSLIBPATH exactly the same way 

Because LeaderF does not have any logic to specifically handle $GTAGSLIBPATH, just leave it as it is. So the error demonstrates `GTAGSLIBPATH must points to directories that contains these GTAGS file. It is not required that such location is part of source tree` is wrong.
Maybe gutentags has special handle of $GTAGSLIBPATH.

**Comment by haihualuo** [comment]
> @haihualuo
> 
> > AFAIK, GTAGSLIBPATH must points to directories that contains these GTAGS file. It is not required that such location is part of source tree (otherwise the major benefit would not be possible).
> 
> I don't think so. You can try $GTAGSLIBPATH in command line(run gtags command in command line).

I did an experiment - I simply updated my script to point GTAGSLIBPATH to 'foo' and 'bar' - notice that there are no GTAGS file there; those files are saved in ~/.LfCache/gtags/%some_path%.

The experiment failed - in tree A, Leaderf + gtags cannot locate symbols from tree B.

I think this experiment is fairly reproducible, but if it works for you, I'd like to learn the differences in our steps ...

> The benefit is because there are many codes to handle the logic to wrok as expected, we can call it as workaround.
> 
> > But when using gutentags/gutentags_plus, I set up my GTAGSLIBPATH exactly the same way
> 
> Because LeaderF does not have any logic to specifically handle $GTAGSLIBPATH, just leave it as it is. So the error demonstrates `GTAGSLIBPATH must points to directories that contains these GTAGS file. It is not required that such location is part of source tree` is wrong.

"Is wrong" meaning? The entry in GTAGSLIBPATH must both contain GTAGS file as well as source code?

> Maybe gutentags has special handle of $GTAGSLIBPATH.

That I am not sure.

**Comment by Yggdroot** [comment]
@haihualuo  

> "Is wrong" meaning? The entry in GTAGSLIBPATH must contain both GTAGS file and source code?

Yes.
If you try to understand GTAGSLIBPATH, please do not use LeaderF or gutentags, just experiment in the command line. I think you will catch what I mean.

**Comment by haihualuo** [comment]
> @haihualuo
> 
> > "Is wrong" meaning? The entry in GTAGSLIBPATH must contain both GTAGS file and source code?
> 
> Yes.
> If you try to understand GTAGSLIBPATH, please do not use LeaderF or gutentags, just experiment in the command line. I think you will catch what I mean.

Thanks. You are partially correct. I could use GTAGSLIBPATH to locate library symbols without GTAGS in the library directory. The following works:

1) gtags in foo to generate GTAGS files
2) gtags in bar to generate GTAGS files
3) move all foo's GTAGS files to a new directory called "lib_foo" (previously empty, no source)
4) export GTAGSLIBPATH="lib_foo"
5) From bar (with bar's GTAGS file), we can locate symbols from foo. After unsetting GTAGSLIBPATH, we cannot. In this case, library source and GTAGS file are in different locations.

I have no intention to drag on the environment variable. The main reason I brought it up is it seems to work with gutentags (with GTAGS file and source code completely separate), so I was hoping the same setup can work under Leaderf ... I will check "--gtagslibpath". The main challenge there is "x y z" could be different when we clone the same repo to different physical directories (sometimes necessary & faster than switching between branches in the same place).

**Comment by Yggdroot** [comment]
@haihualuo

> 1. gtags in foo to generate GTAGS files
> 2. gtags in bar to generate GTAGS files
> 3. move all foo's GTAGS files to a new directory called "lib_foo" (previously empty, no source)
> 4. export GTAGSLIBPATH="lib_foo"
> 5. Using 'global' from bar (with bar's GTAGS file), we can locate symbols from foo. After unsetting GTAGSLIBPATH, we cannot. In this case, library source and GTAGS file are in different locations.

Suppose the full path of `foo`, `bar` and `lib_foo` are `/foo`, `/bar` and `/lib_foo` respectively,
and the 4th step is `export GTAGSLIBPATH=/lib_foo`, and a function called `fun()` is defined in `foo`.
Run `global -d fun` in `bar`, the output will be `/lib_foo/foo.c` but not `/foo/foo.c`, this is not correct, I don't know why you said `we can locate symbols from foo`.

**Comment by haihualuo** [comment]
> @haihualuo
> 
> > 1. gtags in foo to generate GTAGS files
> > 2. gtags in bar to generate GTAGS files
> > 3. move all foo's GTAGS files to a new directory called "lib_foo" (previously empty, no source)
> > 4. export GTAGSLIBPATH="lib_foo"
> > 5. Using 'global' from bar (with bar's GTAGS file), we can locate symbols from foo. After unsetting GTAGSLIBPATH, we cannot. In this case, library source and GTAGS file are in different locations.
> 
> Suppose the full path of `foo`, `bar` and `lib_foo` are `/foo`, `/bar` and `/lib_foo` respectively,
> and the 4th step is `export GTAGSLIBPATH=/lib_foo`, and a function called `fun()` is defined in `/foo/foo.c`.
> Run `global -d fun` in `bar`, the output will be `/lib_foo/foo.c` but not `/foo/foo.c`, this is not correct, I don't know why you said `we can locate symbols from foo`.

Stand corrected. I checked again. One use case for separating source tree and related GTAGS file is via https://lists.gnu.org/archive/html/help-global/2015-07/msg00001.html. But this seems convoluted and my original purpose is not to separate GTAGS and source tree, mainly to take advantage of that as offered by the tool.
