### ISSUE TITLE
E117: Unknown function: leaderf#versionCheck

### ISSUE THREAD

**Issue by skygragon** [Yggdroot/LeaderF#193]
vim 8.1.209

hit this error when trying to search file via leaderf

**Comment by skygragon** [comment]
resolved by compiled with python.

**Comment by lwx5924** [comment]
how to 'compiled with python."?

**Comment by Yggdroot** [comment]
@lwx5924 https://vi.stackexchange.com/questions/11526/how-to-enable-python-feature-in-vim
For more information, turn to google for help.
