### ISSUE TITLE
g:Lf_UseVersionControlTool not working

### ISSUE THREAD

**Issue by mechkb** [Yggdroot/LeaderF#194]
I've `let g:Lf_UseVersionControlTool = 0` set but LeaderF still ignores files form `.gitignore`. How can I ignore the `.gitignore`?

**Comment by Yggdroot** [comment]
Why do you want to ignore the .gitignore?

**Comment by mechkb** [comment]
Because I generate a lot of *.log files for my runs and have to look at them. Unfortunately the Github source I'm working with has *.log in its .gitignore. May be that's what the author of the repo wanted but I don't want that. I want LeaderF to show me the log files I'm generating so I can jump to them easily. 

ripgrep has the -u option to ignore .gitignore. I think Leaderf should also provide that option. I don't want to rename my log files to a different extension just to get around .gitignore. As a user if I want to ignore it, then I should have the option to do that. By its very name, setting `Lf_UseVersionControlTool=0' should ignore all involvement of version control.

**Comment by Yggdroot** [comment]
There is a workaround for your problem:
```vim
let g:Lf_DefaultExternalTool = ""
let g:Lf_UseVersionControlTool = 0
```
, if these two options are set, LeaderF will use os.walk() to index the files, the drawback is that it is a little slow.

**Comment by mechkb** [comment]
I want to continue using `rg` and not have to fall back to anything slow. I use `rg` for everything else. Can you add an option g:Lf_PassArgsToDefaultExternalTool to allow the user a way to pass arguments to the DefaultExternalTool. This way they can get behaviors like ignoring .gitignore themselves thru the external tool.

**Comment by Yggdroot** [comment]
You can use [g:Lf_ExternalCommand](https://github.com/Yggdroot/LeaderF/blob/73444bba61483af13fbd20ab2944c65f96640d5d/doc/leaderf.txt#L386-L397), in which case you can do whatever that `rg` can.
e.g.,
```vim
let g:Lf_ExternalCommand = 'rg --files --no-ignore "%s"'
```

**Comment by mechkb** [comment]
Perfect. Thanks!
