### ISSUE TITLE
搜索结果倒序显示

### ISSUE THREAD

**Issue by mliug** [Yggdroot/LeaderF#195]
可否增加一个将结果列表倒序显示在窗口中的功能，即像ctrlp那样将最佳匹配放在最底部，依次往上显示。因为我们在输入搜索内容时，目光是注视着底部的输入栏。如果搜索结果刚好在其附近，那么思维停顿会少点。
或者将输入栏放在窗口的顶部。

**Comment by Yggdroot** [comment]
加好了。
