### ISSUE TITLE
Why hidden directories and hidden files are displayed when I press `<leader>f`?

### ISSUE THREAD

**Issue by zhanglintc** [Yggdroot/LeaderF#197]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
:version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 11 2018 15:17:01)
Included patches: 1-1813
```
- Output of `:echo has("python")`: 
`1`
- Output of `:echo has("python3")`: 
`0`
- Output of `:echo &pythondll`(only vim, not neovim): 
`libpython2.7.so.1.0`
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
**nothing**
- Output of `:py print(sys.version)`: 
```
2.7.5 (default, Jul 13 2018, 13:06:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
- Output of `:py3 print(sys.version)`: 
**nothing**
- Output of `:echo g:Lf_Debug_Cmd`: 
`find  "." -name . -o   -type f -print  2>/dev/null | sed 's#^\./##'`
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
" Leaderf settings
map <leader>r :Leaderf function<CR>
```
### Describe your question, feature request, or bug.
1. this is my ~ folder
```
[lane@vbox ~]$ ls
a.out  auto-commit  critical  lib  mssout  pms_statistics_batch  shell-conf  vs.cpp  vv.cpp
```
2. jut type `vim` in terminal, then press `<leader>f`. this is the output:
```
   1 .bash_logout
   2 .bash_profile
   3 .cache/abrt/lastnotification
   4 .cache/go-build/README
   5 .cache/go-build/06/0698933c5ec965bf12f620cedfb65b107fe7787e112806b14216b3a0d06e1d74-a
   6 .cache/go-build/0c/0cf4a399696cc3e8c06c2e9154adfc4fd6a01c91db87c71d996b9ef94336230e-d
   7 .cache/go-build/33/339f156709622028a74b71257fcc2b8a46da6245f73d0943068cb81990cc7334-a
   8 .cache/go-build/38/383c62707d8fff8d8282a6fd2dd043729e45f361a96031964e20954e878d3a0d-a
   9 .cache/go-build/43/433c1fbd69d3d56513bae7a477fdc37198e7cdbbdf533e0b6124745de0e09b9a-a
  10 .cache/go-build/4d/4dc59a48a33fb36ab5869a41a2fddc751b5711c7e0ae66ba939d43db740faf2b-a
  11 .cache/go-build/a9/a99bee50b5c4db4031abb035aff4b6b25de93b3b8cb8cbf78acd994f15c79712-a
  12 .cache/go-build/b9/b9e0a12eff093772e9839db597e270280f6daca9135cc111b4565d2e684164ce-d
  13 .cache/go-build/b9/b9b708337ca7f03577f430c963f3c8c140a8b8a7f16bb25d9ce8e75f59c207d6-d
  14 .cache/go-build/e3/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855-d
  15 .cache/go-build/log.txt
  16 .cache/go-build/trim.txt
  17 .cache/ctrlp/mru/cache.txt
```
3. type `<c-p>`, this is what CtrlP output:
```
> lib/libapl.pl
> mssout/base64.o
> mssout/mssout.o
> mssout/makefile
> mssout/mCurl.o
> mssout/cJSON.o
> mssout/mssout
> vs.cpp
> vv.cpp
> a.out
```

I think LeaderF's output is strange. I don't want to see something like `.cache/XXXX` or `.git/XXXX` when I press `<leader>f`. It seems CtrlP's output is more accetpable. Is this a bug? Or just something I haven't set up correctly?

hi, 我就是前几天在知乎评论问问题那个, 今天终于可以把问题详细的整理成issue了. 感觉每次使用`<leader>f`的时候出来那堆隐藏文件夹下的东西看着挺别扭的, 不知道是刻意为之还是就是有bug? 而且通常情况下, 我文件夹里都会有比如`.gitignore`文件, 在使用`<c-p>`的时候他并不会默认显示出来, 但是`<leader>f`的时候会显示出来. 总感觉这些隐藏文件不显示似乎更符合直觉来着.
### Steps to reproduce
see **Describe your question, feature request, or bug.**
### Actual behaviour
see **Describe your question, feature request, or bug.**
### Expected behaviour
see **Describe your question, feature request, or bug.**

**Comment by Yggdroot** [comment]
这也算是个bug吧，我fix了。
不过你还可以安装[rg](https://github.com/BurntSushi/ripgrep)，这样就可以使用rg来建立索引，会更快。

**Comment by zhanglintc** [comment]
更新了, 确认了下, 现在 `.cache` 这样的隐藏文件夹不会出现了, 非常感谢. `.gitignore` 这样的隐藏文件依然会出现, 不过这个倒不影响, 反正隐藏文件没几个, 显示出来心里还有数一些. 只有隐藏文件夹比较烦人.

rg是什么意思, 就是我按他的记载安装就可以吗, 你这个插件到时候会自动调用rg来提高检索速度呗?

**Comment by Yggdroot** [comment]
哦，原来如此。
你如果在一个git的repo下运行LeaderF，就会用`git ls-files && git ls-files --others --exclude-standard`。
具体逻辑在这里：
https://github.com/Yggdroot/LeaderF/blob/30f50ebd10ddbb5a9eb67ec070b9fdc078cb19b3/autoload/leaderf/python/leaderf/fileExpl.py#L207-L373

`let g:Lf_UseVersionControlTool = 0`可以不使用git。
