### ISSUE TITLE
leaderF's file search function didn't work on win10 gvim

### ISSUE THREAD

**Issue by abelZ** [Yggdroot/LeaderF#198]
- vim or neovim? 
    - [x] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by abelZ** [comment]
vim version8.1
:echo has('python') 1
:echo &pythondll python27.dll
:echo &pythonthreedll python36.dll
:py print(sys.version) 2.7.14 .... windows 32bit
:py3 can't load dll
:echo g:Lf_Debug_Cmd ag --nocolor --silent    -g "" "."
system: window10

the issue was, when I use command :LeaderfFile， no matter which directory I use, it will always get a empty file list, other command like LeaderfTag work well. I tried to clean the vimrc and left only leaderF, the issue still exsit.

**Comment by Yggdroot** [comment]
This issue is the same as issue #190, it is a bug of vim or ag, please dont use ag.
