### ISSUE TITLE
it's fast,but i need help

### ISSUE THREAD

**Issue by zhenyangze** [Yggdroot/LeaderF#20]
thanks, it suit me.
but how can i customizing the shortcut keys

**Comment by Yggdroot** [comment]
Please refer to [here](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L161).

**Comment by zhenyangze** [comment]
sorry, i can't find how to change `<leader>f`.

**Comment by zhenyangze** [comment]
wow, find it,` let g:Lf_ShortcutF = '<C-P>'`, thanks. :-)
