### ISSUE TITLE
搜索中文的时候，会出现输入异常情况

### ISSUE THREAD

**Issue by ActiveMouse** [Yggdroot/LeaderF#200]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Expected behaviour
![6eea5e40-a01a-47a9-b503-15478fbd4917](https://user-images.githubusercontent.com/42526029/44315950-4e73ef00-a45b-11e8-8a32-b9e0ffc3e2b5.png)
我直接在vim里面输入LeaderfFile，然后我输入中文“我们”（采用搜狗输入法），发现拼音和中文最后黏在一起输出了，这个是什么问题?

**Comment by Yggdroot** [comment]
win上不能复现，不知道你是什么系统。
不管什么系统，这是输入法的问题，跟LeaderF没关系。

**Comment by ActiveMouse** [comment]
我尝试了苹果自带，谷歌，搜狗输入法的中文，均出现类似情况，但是在正常的vim情况下则正常的呀

**Comment by ActiveMouse** [comment]
就是在Leaderf-的中文输入情况下，就会连带拼音一起输入进来了，这个很湿郁闷啊

**Comment by Yggdroot** [comment]
你是什么系统？

**Comment by Yggdroot** [comment]
这样可以证明是输入法的问题：
运行：`echo nr2char(getchar()) == 'w'`, 然后输入“我”，因为getchar()`是阻塞的，所以在“我”没有输入前不会返回，在你那里可能在打“我”的过程中就返回了。

**Comment by ActiveMouse** [comment]
我在命令行里输入你说的，打印出了：zsh: parse error near `)'

**Comment by ActiveMouse** [comment]
我的是macos系统，10.13.4，苹果最最新的系统

**Comment by ActiveMouse** [comment]
应该是没这个命令在macos上

**Comment by Yggdroot** [comment]
是在vim的命令行里输入。

**Comment by ActiveMouse** [comment]
![image](https://user-images.githubusercontent.com/42526029/44383530-970ad580-a54b-11e8-93b1-c0897f4fd554.png)
是这个样子的，就是我在输入“echo nr2char(getchar()) == 'w'”之后，回车，然后输入中文“我”，空格就变成这样子插入的模式了
![image](https://user-images.githubusercontent.com/42526029/44383575-bc97df00-a54b-11e8-86a1-c8301138f70b.png)

**Comment by Yggdroot** [comment]
从上面可以看出，你输入“我”，然后空格时，vim实际上接收到了w和o，这是不应该的，不知道是vim的bug还是输入法的bug。（你vim的版本是什么）
你再试一下`:echom getchar()`，输入“我”。
我的输出：25105，这是正确的。

**Comment by ActiveMouse** [comment]
我的vim是8.0.1283的，输入法我试过苹果自带，搜狗以及谷歌输入法，表现症状都一样，另外，我在正常的vim模式下输入中文就是好的，但是在leaderf模式下输入中文就会出那样的问题；我按照你的echom getchar() ，空格之后输出的也是25105，很是郁闷啊。。

**Comment by Yggdroot** [comment]
这不是leaderf的问题，只是因为leaderf里面使用getchar()来获取用户的输入。

**Comment by ActiveMouse** [comment]
但是在leaderf模式下会出现输入拼音和汉字一起打印出来的问题我试了下，在window下，就好的

**Comment by ActiveMouse** [comment]
会不会是接受输入的方式不对呢？

**Comment by ActiveMouse** [comment]
会不会换个姿势，会让leaderf更舒服些呢？

**Comment by Yggdroot** [comment]
前面已经证明了是输入法或者vim的问题呀，因为你输入“我”的时候会进入插入模式，是因为vim接收到了'o'。

**Comment by GodIsAFish** [comment]
我的mac也出现输入中文出现错乱的问题

**Comment by Yggdroot** [comment]
#508 中已经有解决方案，可以看下。
