### ISSUE TITLE
Is it possible to remap <leader> key?

### ISSUE THREAD

**Issue by 9527KKK** [Yggdroot/LeaderF#201]
By default, the leader key is "\\". May you please add a feature which allows user to remap leader key?

I wish I could use other key to trigger LeaderF's stuff, eg \<a-f\>f, \<a-f\>b .....

What I am asking is similar to "easymotion-prefix", from https://github.com/easymotion/vim-easymotion/blob/master/doc/easymotion.txt.

Thanks,

(BTW, LeaderF is much faster&accurate than CtrlP. Thanks for your great work.)

**Comment by Yggdroot** [comment]
I think it's not LeaderF's business. You can map whatever shortcut key by yourself.
For instance, `noremap <a-f>f  :Leaderf file<cr>`.

**Comment by Yggdroot** [comment]
Please turn to  `:h mapleader` for help.

**Comment by 9527KKK** [comment]
Thanks. But I don't think this is what I am asking for.

Basically, #1, I don't want to change the default leader mapping, which "\", #2. I want other plugin uses <leader>f, etc "\"f. #3. I want to use LeaderF for sure. But I want "open file search" uses other key, possibly <a-c>f, not <Leader>f.

If LeaderF can provides, leader-prefix, which is similar to easymotion-prefix, that will be handy.

Any suggestion?

**Comment by Yggdroot** [comment]
First, please learn the syntax of markdown to make sure the comments you write can be displayed very well.
(`text between '<' and '>' can not be seen`)

There are only two pre-defined short cut key, I do not think it is necessary to add such a functionality.
Also, in my opinion, `let g:Lf_ShortcutF = '<a-f>f'` has already met your requirement.

**Comment by 9527KKK** [comment]
Thanks.
