### ISSUE TITLE
为什么修改了g:Lf_WindowPostion好像并没有起什么作用

### ISSUE THREAD

**Issue by GoodlPlus** [Yggdroot/LeaderF#204]
我想要让leaderf的窗口显示在右边，但是当我修改了g:Lf_WindowsPostion = 'right'之后发现好像并么有起作用。

**Comment by Yggdroot** [comment]
不能复现。

**Comment by GoodlPlus** [comment]
哦，刚才好像有个单词输入错误了，导致没有改变，改正了就可以了，不好意思哈
