### ISSUE TITLE
Feature request: support input file list.

### ISSUE THREAD

**Issue by 9527KGG** [Yggdroot/LeaderF#208]
My dir has lots of files which I don't care. So when I create tag file, I create input file list first. Then I use, eg ctags -L c:\tmp\file_list.txt to create tag file.

May you please allow for leaderf to support input file list? eg add a new command 
:LeaderfFileList file_list.txt
or reuse the existing one
:LeaderfFile [directory] | [file_list.txt]

Benefit:

1. LeaderF should be even faster since it does not need search the whole dir, again and again
2. It's especially useful when the project is across multiple dirs. (Currently, when the project is big, I cannot use ":LeaderfFile root_dir" since it's too big. I've to switch to different dir back and forth, again and again.).

Thanks. Really appreciate.

**Comment by Yggdroot** [comment]
Added. Now you can use like this: `Leaderf file --file file_list.txt`.

**Comment by 9527KKK** [comment]
Fantastic!!! Really appreciate your help!!!

**Comment by 9527KKK** [comment]
I've one more question: would it be hard to support multiple files? eg,
Leaderf file --file file_list1.txt file_list2.txt
or
Leaderf file --file file_list1.txt --file file_list2.txt

Sadly, I just found my project generally have 2 input list files, which generally cannot be merged~~~

**Comment by Yggdroot** [comment]
Done, `Leaderf file --file file_list1.txt file_list2.txt` is available.

**Comment by Yggdroot** [comment]
NP.
