### ISSUE TITLE
leaderf 自定义 扩展与vim python3 出现兼容性问题

### ISSUE THREAD

**Issue by tracyone** [Yggdroot/LeaderF#209]
https://github.com/tracyone/vinux/blob/leaderf_extend/autoload/te/leaderf/dir.vim#L1-L50

https://github.com/tracyone/vinux/blob/leaderf_extend/rc/jump.vim#L34-L41

```
    nnoremap <Leader>ff :Leaderf dir<cr>
```

注意把代码里面的`te#compatiable#systemlist`换成systemlist函数即可。

问题描述：

vim 最新版本（几乎），使能python3，`echo has('python3)`为1.

leaderf插件的版本为最新`dev`分支。

执行上面的`Leaderf dir`的时候，首次进入界面没有错误，但是一开始输入字就出现下面截图错误：

![error](https://user-images.githubusercontent.com/4246425/44985772-15d42980-afb4-11e8-9d45-b16017dc0bf6.png)

这个问题可以在ubuntu 16.04.4和macOS 10.13.6上复现。

**Comment by Yggdroot** [comment]
fix了，试一下，在dev branch。

**Comment by Yggdroot** [comment]
```vim
function! te#leaderf#dir#accept(line, args) abort
    let l:file_or_dir=matchstr(a:line,".*[^@]")
    if isdirectory(l:file_or_dir)
        execute 'cd 'l:file_or_dir
        :Leaderf dir
    else
        execute 'e '.l:file_or_dir
    endif
endfunction
```
这个函数调用:Leaderf dir 这样实现，是退出去再进来有点不舒服，我增加了一个函数：
`    \       "need_exit": funcref (line, arguments),
`
你只要写一个函数返回0，就不会退出了。
例如：
```vim
function! te#leaderf#dir#needExit(line, args) abort
    let l:file_or_dir=matchstr(a:line,".*[^@]")
    if isdirectory(l:file_or_dir)
        return 0   "不退出
    else
        return 1
    endif
endfunction
```

**Comment by tracyone** [comment]
题目的问题确认解决了。

你说的这个need_exit，有个问题：

按照我这个扩展

首先选择一个目录进去，然后在该目录选择一个文件打开，这个时候出现下图的情况，leaderf似乎没有离开

<img width="143" alt="screen shot 2018-09-04 at 21 00 24" src="https://user-images.githubusercontent.com/4246425/45032990-c4946a80-b085-11e8-852f-f14b7d9123fd.png">

**Comment by Yggdroot** [comment]
accept函数也要相应的修改。
例如：
```vim
function! te#leaderf#dir#accept(line, args) abort
    let l:file_or_dir=matchstr(a:line,".*[^@]")
    if isdirectory(l:file_or_dir)
        execute 'cd 'l:file_or_dir
        把这个目录下的文件或目录再列出来
    else
        execute 'e '.l:file_or_dir
    endif
endfunction
```

**Comment by Yggdroot** [comment]
```vim
function! te#leaderf#dir#accept(line, args) abort
    let l:file_or_dir=matchstr(a:line,".*[^@]")
    if isdirectory(l:file_or_dir)
        execute 'cd 'l:file_or_dir
        let source = te#leaderf#dir#source(0)
        norm! ggdG
        call setline(1, source)
    else
        execute 'e '.l:file_or_dir
    endif
endfunction
```
我的意思大致就是这个函数，不过高亮好像有bug，我再看看。

**Comment by Yggdroot** [comment]
使用最新的dev branch，应该没什么问题了。

**Comment by Yggdroot** [comment]
Leaderf dir 这个功能我打算原生支持了，也许可以吸引一些用户，到时候希望能提出一些建议。

**Comment by tracyone** [comment]
Awesome!，问题解决。
