### ISSUE TITLE
unknown option `recurse-submodules'

### ISSUE THREAD

**Issue by cosmtrek** [Yggdroot/LeaderF#211]
- vim or neovim? 
    - [ x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
    vim 8
- Output of `:echo has("python")`: 
    0
- Output of `:echo has("python3")`: 
    1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.7.0 (default, Jul  1 2018, 10:02:32)
- Output of `:echo g:Lf_Debug_Cmd`: 
  git ls-files --recurse-submodules && git ls-files --others --exclude-standard
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
![screen shot 2018-09-05 at 11 39 46](https://user-images.githubusercontent.com/8832222/45069719-783a4080-b100-11e8-985b-e3137766fa98.png)
### Describe your question, feature request, or bug.
![screen shot 2018-09-05 at 11 30 30](https://user-images.githubusercontent.com/8832222/45069725-7e302180-b100-11e8-8e07-1c4cb2644dcf.png)

Maybe related with this commit https://github.com/Yggdroot/LeaderF/commit/faea4e759debdb5b4918c7906585a7cd93aaa762

**Comment by Yggdroot** [comment]
The version of your git is too low, please upgrade it.

**Comment by cosmtrek** [comment]
@Yggdroot Thanks!
