### ISSUE TITLE
[FeatureRequest] `<c-p>` `<c-n>` to loop input history

### ISSUE THREAD

**Issue by ZSaberLv0** [Yggdroot/LeaderF#213]
similar to ctrlp.vim, use `<c-p>` and `<c-n>` to loop "input history" inside the LeaderF (not search or cmd history)

Why?

- you have input `long long AAA long long` to search something
- you want to change the pattern to `long long BBB long long` to search again
- it would be more convenient to have input history

**Comment by Yggdroot** [comment]
Added, but use `<Up>` and `<Down>` by default in accord with vim command line.

**Comment by ZSaberLv0** [comment]
good job :+1:
