### ISSUE TITLE
调出函数列表后 输入i 进入模糊搜索报错

### ISSUE THREAD

**Issue by CodingdAwn** [Yggdroot/LeaderF#224]
是最新的 使用vim-plug更新后测试的

- vim or neovim? 
    - [x ] vim
    - [ ] neovim

- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)

- Output of `:echo has("python")`: 
0

- Output of `:echo has("python3")`: 
1

- Output of `:echo &pythondll`(only vim, not neovim): 
没有输出

- Output of `:echo &pythonthreedll`(only vim, not neovim): 
没有输出

- Output of `:py print(sys.version)`: 
E319: Sorry, the command is not available in this version

- Output of `:py3 print(sys.version)`: 
3.6.5 (default, Apr  1 2018, 05:46:30)
[GCC 7.3.0]

- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd
E15: Invalid expression: g:Lf_Debug_Cmd

- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
使用的是skywind3000的配置vim-init
Plug 'Yggdroot/LeaderF', {'do': './install.sh'}
  422
  423 |   |   " CTRL+p 打开文件模糊匹配
  424 |   |   let g:Lf_ShortcutF = '<c-p>'
  425
  426 |   |   " ALT+n 打开 buffer 模糊匹配
  427 |   |   let g:Lf_ShortcutB = '<m-n>'
  428
  429 |   |   " CTRL+n 打开最近使用的文件 MRU，进行模糊匹配
  430 |   |   noremap <c-n> :LeaderfMru<cr>
  431
  432 |   |   " ALT+p 打开函数列表，按 i 进入模糊匹配，ESC 退出
  433 |   |   noremap <m-p> :LeaderfFunction!<cr>
  434
  435 |   |   " ALT+SHIFT+p 打开 tag 列表，i 进入模糊匹配，ESC退出
  436 |   |   noremap <m-P> :LeaderfBufTag!<cr>
  437
  438 |   |   " ALT+n 打开 buffer 列表进行模糊匹配
  439 |   |   noremap <m-n> :LeaderfBuffer<cr>
  440
  441 |   |   " 全局 tags 模糊匹配
  442 |   |   noremap <m-m> :LeaderfTag<cr>
  443
  444 |   |   " 最大历史文件保存 2048 个
  445 |   |   let g:Lf_MruMaxFiles = 2048
  446
  447 |   |   " ui 定制
  448 |   |   let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
  449
  450 |   |   " 如何识别项目目录，从当前文件目录向父目录递归知道碰到下面的文件/目录
  451 |   |   let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
  452 |   |   let g:Lf_WorkingDirectoryMode = 'Ac'
  453 |   |   let g:Lf_WindowHeight = 0.30
  454 |   |   let g:Lf_CacheDirectory = expand('~/.vim/cache')
  455
  456 |   |   " 显示绝对路径
  457 |   |   let g:Lf_ShowRelativePath = 0
  458
  459 |   |   " 隐藏帮助
  460 |   |   let g:Lf_HideHelp = 1
  461
  462 |   |   " 模糊匹配忽略扩展名
  463 |   |   let g:Lf_WildIgnore = {
  464 |   |   |   |   |   \ 'dir': ['.svn','.git','.hg'],
  465 |   |   |   |   |   \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
  466 |   |   |   |   |   \ }
  467
  468 |   |   " MRU 文件忽略扩展名
  469 |   |   let g:Lf_MruFileExclude = ['*.so', '*.exe', '*.py[co]', '*.sw?', '~$*', '*.bak', '*.tmp', '*.dll']
  470 |   |   let g:Lf_StlColorscheme = 'powerline'

  472 |   |   " 禁用 function/buftag 的预览功能，可以手动用 p 预览
  473 |   |   let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}
  474
  475 |   |   " 使用 ESC 键可以直接退出 leaderf 的 normal 模式
  476 |   |   let g:Lf_NormalMap = {
  477 |   |   |   |   \ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
  478 |   |   |   |   \ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<cr>']],
  479 |   |   |   |   \ "Mru": [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<cr>']],
  480 |   |   |   |   \ "Tag": [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<cr>']],
  481 |   |   |   |   \ "BufTag": [["<ESC>", ':exec g:Lf_py "bufTagExplManager.quit()"<cr>']],
  482 |   |   |   |   \ "Function": [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<cr>']],
  483 |   |   |   |   \ }
  484
  485 |   else
  486 |   |   " 不支持 python ，使用 CtrlP 代替
  487 |   |   Plug 'ctrlpvim/ctrlp.vim'
  488
  489 |   |   " 显示函数列表的扩展插件
  490 |   |   Plug 'tacahiroy/ctrlp-funky'
  491
  492 |   |   " 忽略默认键位
  493 |   |   let g:ctrlp_map = ''
  494
  495 |   |   " 模糊匹配忽略
  496 |   |   let g:ctrlp_custom_ignore = {
  497 |   |     \ 'dir':  '\v[\/]\.(git|hg|svn)$',
  498 |   |     \ 'file': '\v\.(exe|so|dll|mp3|wav|sdf|suo|mht)$',
  499 |   |     \ 'link': 'some_bad_symbolic_links',
  500 |   |     \ }
  501
  502 |   |   " 项目标志
  503 |   |   let g:ctrlp_root_markers = ['.project', '.root', '.svn', '.git']
  504 |   |   let g:ctrlp_working_path = 0
  505
  506 |   |   " CTRL+p 打开文件模糊匹配
  507 |   |   noremap <c-p> :CtrlP<cr>
  508
  509 |   |   " CTRL+n 打开最近访问过的文件的匹配
  510 |   |   noremap <c-n> :CtrlPMRUFiles<cr>
  511
  512 |   |   " ALT+p 显示当前文件的函数列表
  513 |   |   noremap <m-p> :CtrlPFunky<cr>
  514
  515 |   |   " ALT+n 匹配 buffer
  516 |   |   noremap <m-n> :CtrlPBuffer<cr>
  517 |   endif

### Describe your question, feature request, or bug.
打开cpp文件 使用列出函数列表的功能 没有问题 但是输入i后 报错  不能进入模糊搜索

### Steps to reproduce
打开cpp或者py文件 alt+p打开函数列表 输入i 或者tab 都会报错

### Actual behaviour
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/dawn/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 58, in deco
    func(self, *args, **kwargs)
  File "/home/dawn/.vim/bundles/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1054, in input
    callback = self._callback_backup
AttributeError: 'FunctionExplManager' object has no attribute '_callback_backup'
这是报错内容
### Expected behaviour
vim新手 实在自己查不出来 求教

**Comment by Yggdroot** [comment]
确实是个bug，改好了。（哎，最近代码改动有点多，bug也变多了）

**Comment by CodingdAwn** [comment]
> 
> 
> 确实是个bug，改好了。（哎，最近代码改动有点多，bug也变多了）
辛苦了~ 非常好用的插件 加油
