### ISSUE TITLE
install.sh failed on Windows10(msys64)

### ISSUE THREAD

**Issue by cjun714** [Yggdroot/LeaderF#225]
- vim or neovim? 
    - [x] gvim
- Output of `vim --version`: 8.1.429
- Operating system: 
    - [x] Windows + msys64 + gcc 8.2.0 +  mingw-w64-x86_64-python3
- Configurations related to LeaderF in vimrc: 
``` vim
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
```
### Describe your question, feature request, or bug.
Run install.sh failed.
lib can be compiled, but script failed at `cp lib to autoload/leaderf/python` .
### Steps to reproduce
``` shell
> cd ~/.vim/plugged/LeaderF
> ./install.sh
Begin to compile C extension of Python3 ...
...
cp: cannot stat 'build/lib*3.?/*.so': No such file or directory
> ll ./autoload/leaderf/fuzzyMatch_C/build/lib.mingw-3.7/
total 120K
-rwxr-xr-x 1 John None 61K Sep 27 17:32 fuzzyEngine-cpython-37m.dll*
-rwxr-xr-x 1 John None 54K Sep 27 17:32 fuzzyMatchC-cpython-37m.dll*
```

In install.sh, should use `cp build/lib*3.?/* ../python` instead of `cp build/lib*3.?/*.so ../python`
In msys64, dynamic lib suffix is always '.dll' not '.so'

**Comment by Yggdroot** [comment]
On windows, please use install.bat.

**Comment by cjun714** [comment]
install.bat. can't run in cygwim or msys64.
On Windows, I always launch vim through shell like fish, it works well with tool chain like mingw64 gcc, clang, cmake and also with all .sh scripts and most linux env settings, I think lots of people handle things like this.
install.bat is not proper here, and it will never work.

**Comment by Yggdroot** [comment]
What is in your `build/lib*3.?/` ?

**Comment by Yggdroot** [comment]
Fixed.
