### ISSUE TITLE
方向鍵選取

### ISSUE THREAD

**Issue by misakisuna705** [Yggdroot/LeaderF#228]
- vim or neovim? 
    - [ ] vim
    - [x] neovim

- Output of `vim --version` or `nvim --version`: vim --8.1.450

- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [x] Etc.

- Configurations related to LeaderF in vimrc: 

Plug 'Yggdroot/LeaderF'",{'on': ['LeaderfFunction', 'LeaderfFile'],'do': './install.sh'}
let g:Lf_CacheDirectory = expand('~/.cache')
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_RootMarkers = ['.git']
map <C-p> :LeaderfFile<CR>
map <C-g> :Leaderf bufTag<CR>
map <C-t> :LeaderfTag<CR>
let g:Lf_ShowHidden = 1 
let g:Lf_WindowHeight = 0.30
let g:Lf_HideHelp = 1

### Describe your question, feature request, or bug.

你好，我今天使用leaderf搜尋檔案或標籤時，都無法使用方向鍵選取@@

**Comment by misakisuna705** [comment]
上面勾錯
應該是 "vim" 和 "Mac OSX"

**Comment by Yggdroot** [comment]
这是 #213 这个feature引入的，以前选取是`<c-j>,<down>`和`<c-k>,<up>`, 现在只用`<c-j>`和`<c-k>`了。`<up>`和`<down>`用来翻看历史。
如果不习惯可以用下面方法来自定义：
https://github.com/Yggdroot/LeaderF/blob/a64ea189a426444875ae2df4b69a991f7d5b7043/doc/leaderf.txt#L484-L489

**Comment by misakisuna705** [comment]
可以了，十分感謝！！
