### ISSUE TITLE
[Feature Request] Also show files under subdirectories when run `LeaderfFile`

### ISSUE THREAD

**Issue by hiberabyss** [Yggdroot/LeaderF#232]
When I run `:LeaderfFile /path/to/bundle/`, only file under `bundle` will be shown. Instead, when I run `FZF /path/to/bundle/`, even files under subdirectories will also ben shown. Just like following image shows:

![image](https://user-images.githubusercontent.com/2898670/47011102-9e2d1900-d173-11e8-9d2d-9a09ad26695a.png)

Could `LeaderfFile` has the similar behavior like `FZF`?

**Comment by Yggdroot** [comment]
What is the output of `:echo g:Lf_Debug_Cmd`?

**Comment by hiberabyss** [comment]
@Yggdroot The output is:

```
git ls-files --recurse-submodules && git ls-files --others --exclude-standard
```

**Comment by Yggdroot** [comment]
I think this command can list all the files.
Can you have a try this command in the terminal?
what is in your .gitignore?

**Comment by Yggdroot** [comment]
Please have a try: `Leaderf file --no-ignore`.
