### ISSUE TITLE
doesn't work with vim that compiled with '+python/dyn' and '+python3/dyn'

### ISSUE THREAD

**Issue by aj3423** [Yggdroot/LeaderF#234]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 17 2018 05:44:07)
MS-Windows 64-bit console version
包含补丁: 1-401
编译者 appveyor@APPVYR-WIN
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +emacs_tags         +mouse              +tag_old_static
+arabic             +eval               -mouseshape         -tag_any_white
+autocmd            +ex_extra           +multi_byte_ime/dyn +tcl/dyn
+autochdir          +extra_search       +multi_lang         +termguicolors
+autoservername     +farsi              +mzscheme/dyn       +terminal
-balloon_eval       +file_in_path       -netbeans_intg      -tgetent
+balloon_eval_term  +find_in_path       +num64              -termresponse
-browse             +float              +packages           +textobjects
++builtin_terms     +folding            +path_extra         +timers
+byte_offset        -footer             +perl/dyn           +title
+channel            +gettext/dyn        +persistent_undo    -toolbar
+cindent            -hangul_input       -postscript         +user_commands
+clientserver       +iconv/dyn          +printer            +vartabs
+clipboard          +insert_expand      +profile            +vertsplit
+cmdline_compl      +job                +python/dyn         +virtualedit
+cmdline_hist       +jumplist           +python3/dyn        +visual
+cmdline_info       +keymap             +quickfix           +visualextra
+comments           +lambda             +reltime            +viminfo
+conceal            +langmap            +rightleft          +vreplace
+cryptv             +libcall            +ruby/dyn           +vtp
+cscope             +linebreak          +scrollbind         +wildignore
+cursorbind         +lispindent         +signs              +wildmenu
+cursorshape        +listcmds           +smartindent        +windows
+dialog_con         +localmap           +startuptime        +writebackup
+diff               +lua/dyn            +statusline         -xfontset
+digraphs           +menu               -sun_workshop       -xim
-dnd                +mksession          +syntax             -xpm_w32
-ebcdic             +modify_fname       +tag_binary         -xterm_save
     系统 vimrc 文件: "$VIM\vimrc"
     用户 vimrc 文件: "$HOME\_vimrc"
 第二用户 vimrc 文件: "$HOME\vimfiles\vimrc"
 第三用户 vimrc 文件: "$VIM\_vimrc"
      用户 exrc 文件: "$HOME\_exrc"
  第二用户 exrc 文件: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
编译方式: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERM
INAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
链接方式: link  /nologo /subsystem:console,5.02 /opt:ref /LTCG:STATUS oldnames.lib kernel3
2.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib /PDB:vim.pdb -debug

- Output of `:echo has("python")`: 
1

- Output of `:echo has("python3")`: 
1

- Output of `:echo &pythondll`(only vim, not neovim): 
python27.dll

- Output of `:echo &pythonthreedll`(only vim, not neovim): 
python37.dll

- Output of `:py print(sys.version)`: 
2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]

- Output of `:py3 print(sys.version)`: 
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
Plug 'Yggdroot/LeaderF', { 'do': '.\install.bat' }
let g:Lf_ShortcutF = '<c-p>'
let g:Lf_WildIgnore = {
		\ 'dir': ['.svn','.git','build','debug','release','reldbg','DS_Store','.exvim.*','jqwidgets','bower_components','dist','documentation','plugins'],
		\ 'file': ['*.aj', '*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]','*.pb.h','*.pb.cc']
		\}
let g:Lf_DefaultMode='Regex'
let g:Lf_CommandMap = {'<C-c>': ['<Esc>']}
let g:Lf_CacheDirectory = expand('~/.ajcache/LF_cache')

### Describe your question, feature request, or bug.
Doesn't work with vim that compiled with '+python/dyn' and '+python3/dyn'

### Steps to reproduce
1. set in vimrc:   `let g:Lf_ShortcutF = '<c-p>'`
2. open gvim.exe, press Ctrl+p

### Actual behaviour
error occur
![image](https://user-images.githubusercontent.com/4710875/47108462-4e874400-d27e-11e8-9d0a-9785fa626d9b.png)

### Expected behaviour
list files

**Comment by Yggdroot** [comment]
Fixed, thanks for your report.
