### ISSUE TITLE
How to exchange the keys <Esc> and <C-C> by g:Lf_CommandMap?

### ISSUE THREAD

**Issue by xietren** [Yggdroot/LeaderF#24]
I'd like to exchange two keys `<Esc>` and `<C-C>`. So I write this following in my _vimrc.

`let g:Lf_CommandMap = {'<C-C>': ['<Esc>'], '<Esc>': ['<C-C>']}`

However,  pressing <Esc> will quit from LeaderF, but  pressing <C-C> doesn't switch to normal mode. It becomes that `<C-C>` equals `<Esc>`. 
Another question is that when I switch from LeaderF to normal mode, the  label ">>>"(at the bottom of window) doesn't disappear soon.
So what I shoud do? Thanks a lot!

> g:Lf_CommandMap                                 *g:Lf_CommandMap*
    Use this option to customize the mappings inside LeaderF's
    prompt(|leaderf-prompt|).
    for example, if you want to change the default command `<C-F>` to `<C-D>` and
    change the default command `<C-Q>` to `<Esc>`: >
`let g:Lf_CommandMap = {'<C-F>': ['<C-D>'], '<C-Q>': ['<Esc>']}`

**Comment by Yggdroot** [comment]
`<C-C> ` is always 'quit from LeaderF', you can not change it.
You have to use another key other than `<C-C>`.

**Comment by xietren** [comment]
Good job. I will consider about using other key. Thank you very much! 
How about the second question?

> Another question is that when I switch from LeaderF to normal mode, the label ">>>"(at the bottom of window) doesn't disappear. (default: press <ESC> to switch from LeaderF to normal mode)

**Comment by Yggdroot** [comment]
It works as design.

**Comment by xietren** [comment]
Thanks!
