### ISSUE TITLE
install.bat装完 打开Leaderf -file 报错

### ISSUE THREAD

**Issue by 1501432163** [Yggdroot/LeaderF#242]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by 1501432163** [comment]
Error detected while processing >>>\leaderf\File.vim
Unknown function: leaderf#lfpy

自己执行
echo g:Lf_fuzzyMatch_C也为空 报错

**Comment by Yggdroot** [comment]
我给的问题模板，你能多填几个吗？

**Comment by 1501432163** [comment]
![1](https://user-images.githubusercontent.com/12163502/48175211-125b7680-e346-11e8-9808-623eb1cb7aae.png)
![Uploading 2.png…]()

**Comment by 1501432163** [comment]
:echo has("python") = 0;
:echo has("python3") = 0;

**Comment by 1501432163** [comment]
![3](https://user-images.githubusercontent.com/12163502/48175250-4171e800-e346-11e8-8b19-0bf5f70c8d73.png)

**Comment by 1501432163** [comment]
![2](https://user-images.githubusercontent.com/12163502/48175263-4afb5000-e346-11e8-9e5b-823f824e8105.png)

**Comment by 1501432163** [comment]
现在同时装了python2.7 和 python3.7

**Comment by 1501432163** [comment]
vim --version
![5](https://user-images.githubusercontent.com/12163502/48175378-bba26c80-e346-11e8-893e-fa10c6ba6f6f.png)

**Comment by Yggdroot** [comment]
问题很清楚了，你的vim不支持Python。
可以参考https://www.v2ex.com/t/410079#reply9 这篇文章的准备工作部分看看。
当echo has("python") 或者echo has("python3")不是0 就可以了。

**Comment by 1501432163** [comment]
version 里面是+python/dyn呀

**Comment by 1501432163** [comment]
我重下个python

**Comment by 1501432163** [comment]
现在函数列表不支持Typescript的搜索吗

**Comment by 1501432163** [comment]
@Yggdroot 现在函数列表不支持Typescript的搜索吗

**Comment by qw9002** [comment]
> Typescript貌似是个新语言，ctags现在不支持。

universal-ctags 现在已经支持 Typescript了，加一下Typescript函数列表配置。

**Comment by Yggdroot** [comment]
设置一下`g:Lf_CtagsFuncOpts`。
