### ISSUE TITLE
press `tab` after :Leaderf line can not output filtered data

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#245]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1.538
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.6m.so.1.0
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.6.7 (default, Oct 21 2018, 08:08:16)[GCC 8.2.0]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
  let g:Lf_PreviewCode = 0
  let g:Lf_UseVersionControlTool = 0
  let g:Lf_DefaultMode = 'FullPath'
  let g:Lf_RootMarkers = ['.root', '.git']
  let g:Lf_WildIgnore = {
        \ 'dir': ['.root','.svn','.git','.hg'],
        \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
        \}

  let g:Lf_CommandMap = {'<F5>': ['<C-L>']}
```

### Describe your question, feature request, or bug.
last version `20a982e0cff28` use `:Leaderf line` search some key word, and then `tab`, The output window show all the data, not the filtered data. commit `dd9c0b0ff42ffa4482f` work fine.

### Steps to reproduce
```
vim a.log
:Leaderf line<CR>
input key_word
<TAB>
```

### Actual behaviour
after press `tab`, show all data.

### Expected behaviour
after press `tab`, show filtered data.

**Comment by Yggdroot** [comment]
I can not reproduce this issue. Could you please attach the a.log?

**Comment by fcying** [comment]
There was a problem described yesterday. It only happeded in `regex` mode, `fuzzy` mode work fine. 
```
vim l.log
:Leaderf line --regex<CR>
ipcctl
<TAB>
```
![1](https://user-images.githubusercontent.com/106934/48813505-30779c80-ed72-11e8-9731-261b9966bd2d.jpg)
![1](https://user-images.githubusercontent.com/106934/48813508-32d9f680-ed72-11e8-8b22-7658dbf5176b.jpg)
![2](https://user-images.githubusercontent.com/106934/48813509-32d9f680-ed72-11e8-96eb-deebce71230a.jpg)
![3](https://user-images.githubusercontent.com/106934/48813516-35d4e700-ed72-11e8-9eda-0eb31f918374.jpg)
[l.log](https://github.com/Yggdroot/LeaderF/files/2602268/l.log)

**Comment by Yggdroot** [comment]
Got it, I'll fix it soon.

**Comment by Yggdroot** [comment]
Fixed in dev branch, please have a try.

**Comment by fcying** [comment]
It work fine in dev branch.

**Comment by Yggdroot** [comment]
Merged.
