### ISSUE TITLE
LeaderfFile命令结果中有不存在的文件

### ISSUE THREAD

**Issue by imbear** [Yggdroot/LeaderF#246]
在一个hg仓库中打开文件，然后执行:LeaderfFile命令，由于仓库之前删除过文件但未提交，后台hg files返回的列表中包括了已删除的文件

**Comment by Yggdroot** [comment]
这个是正常功能，如果一个仓库有5万个文件，难道要每一个都检查是否存在吗？这会非常耗时。
如果想避免这个问题，可以设置`let g:Lf_UseVersionControlTool = 0`, 这样会使用`rg`等工具建立索引，就没问题了。

**Comment by Yggdroot** [comment]
```
$ hg --version
Mercurial Distributed SCM (version 4.2+4)
```
```
$ hg files -x "set:deleted()"
hg files: option -x not recognized
```
这个设置可能依赖hg版本。

不打算改了。而且我觉得把文件删掉而不提交不是个好习惯。
