### ISSUE TITLE
设置g:Lf_RootMarkers 是不是有bug

### ISSUE THREAD

**Issue by yanke1311** [Yggdroot/LeaderF#248]
设置后搜索到其他目录的文件，打开后发现是在当前目录上开了一个新的，而不是想要的那个文件

**Comment by Yggdroot** [comment]
能把问题描述清楚一点吗，是vim还是neovim，版本，以及具体怎么设置的，现象是什么，期望结果是什么？（如果能按照我给的问题模板填的话，我就可以直接排查问题，而不需要再问。）

**Comment by yanke1311** [comment]
设置了g:Lf_RootMarkers 和 g:Lf_WorkingDirectoryMode 后，用leaderf可以搜索到我想要的文件(不在当前打开的文件所在路径下)，但是enter后发现并没有转到我要的那个文件里，而是在当前路径下创建了一个和想转到的文件名字一样的空文件

**Comment by Yggdroot** [comment]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

### Steps to reproduce

### Actual behaviour

### Expected behaviour

**Comment by Yggdroot** [comment]
不能复现。
能不能在LeaderF的源码中试一下，说一下每一步骤：
进入vim后，pwd、当前buffer打开的文件名称、使用LeaderF搜索的文件已经LeaderF状态栏上显示的目录

**Comment by yanke1311** [comment]
1.在leaderF工程目录(有.git的目录)下新建一个tmp目录，在此目录中新建1文件；
2.打开1文件，用`<leader>f`快捷键打开leaderf，搜索README,搜索到后enter 这时状态栏下面有[New File]字样，打开的是一个叫README的新建的空文件

**Comment by Yggdroot** [comment]
你说的每一步我都明白了，但是我电脑上不能复现。

**Comment by yanke1311** [comment]
那可能是我电脑有问题，我用的linux子系统，明天我用ubuntu试试，多谢啦~，发现ctrl+t +x都可以用

**Comment by yanke1311** [comment]
不加Lf_WorkingDirectoryMode或者Lf_WorkingDirectory的话只能在当前目录下查找，这样打开找到的结果没有问题，加上Lf_WorkingDirectoryMode或者Lf_WorkingDirectory后，需要递归向上查询，这样就会出现查到的结果打开为空的情况

**Comment by Yggdroot** [comment]
你那里每次都是这样吗？我不能复现。

**Comment by yanke1311** [comment]
是的 台式机也是，就死加上Lf_WorkingDirectoryMode后就不行了

**Comment by Yggdroot** [comment]
> 1.在leaderF工程目录(有.git的目录)下新建一个tmp目录，在此目录中新建1文件；
> 2.打开1文件，用`<leader>f`快捷键打开leaderf，搜索README,搜索到后enter 这时状态栏下面有[New File]字样，打开的是一个叫README的新建的空文件

在你打开Leaderf时，状态栏是什么样子的？

**Comment by yanke1311** [comment]
![image](https://user-images.githubusercontent.com/23717792/49844707-03615b80-fdff-11e8-9a21-d776de256bd7.png)
这是搜索的
![image](https://user-images.githubusercontent.com/23717792/49844695-f3497c00-fdfe-11e8-9d67-09cf1ff568f5.png)
这是打开的，变成了一个空的文件
![image](https://user-images.githubusercontent.com/23717792/49844725-12e0a480-fdff-11e8-9558-96a3255bb1c6.png)
随便写点东西，然后输入`:w`后的结果显示

**Comment by Yggdroot** [comment]
> 1.在leaderF工程目录(有.git的目录)下新建一个tmp目录，在此目录中新建1文件；
> 2.打开1文件，用`<leader>f`快捷键打开leaderf，搜索README,搜索到后enter 这时状态栏下面有[New File]字样，打开的是一个叫README的新建的空文件

在LeaderF目录，按照上面步骤，当打开leaderf时，状态栏显示的路径是什么？

**Comment by yanke1311** [comment]
是$HOME/.vim/bundle/LeaderF

**Comment by Yggdroot** [comment]
这是正常的。太奇怪了。 有可能是你的什么配置的问题。

**Comment by kerwinxu** [comment]
记得有看过某个插件，是可以自动新建文件的，忘记叫什么名字了。
