### ISSUE TITLE
Leaderf can't find the new file.

### ISSUE THREAD

**Issue by featheryus** [Yggdroot/LeaderF#249]
- vim or neovim? 
    - [X] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
leaderf can't find the new file. It can find the legacy file normally. No errrors
### Expected behaviour

Thanks.

**Comment by Yggdroot** [comment]
Please set `let g:Lf_UseVersionControlTool = 0`, and install rg.
