### ISSUE TITLE
can you let buffer sort like unite.vim

### ISSUE THREAD

**Issue by liangguohuan** [Yggdroot/LeaderF#25]
it's better to sort buffer like unite.vim  when open the buffer list. 
unite.vim let the buffer list to view more humanized,  it's  very convenient to hit the 'enter' key to go prev buffer when open the buffer list.

**Comment by Yggdroot** [comment]
I don't understand what you mean.

**Comment by liangguohuan** [comment]
Sorry，my english writing ability is not very good.
I mean, i just press the 'enter' key it can be go back to last modified buffer when i open the buffer list.

**Comment by liangguohuan** [comment]
Maybe it's not necessary. let the 'bm' action do the thing if just want to go to next modified buffer.
