### ISSUE TITLE
打开包含有大量子目录的项目时，Total显示为0

### ISSUE THREAD

**Issue by chujun-L** [Yggdroot/LeaderF#250]
![image](https://user-images.githubusercontent.com/20207830/49500415-9bb18a80-f8ab-11e8-87da-6f6c2095eca9.png)

![image](https://user-images.githubusercontent.com/20207830/49500493-c865a200-f8ab-11e8-9e59-f144f97320f2.png)

**Comment by Yggdroot** [comment]
能把我给的模板后面几项填一下吗

**Comment by Yggdroot** [comment]
Output of `:echo g:Lf_Debug_Cmd`:
