### ISSUE TITLE
执行LeaderfHistoryCmd报错

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#252]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.dll
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.1 (default, Oct 21 2018, 19:17:50)  [GCC 7.3.0 32 bit]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

执行`LeaderfHistoryCmd/Leaderf searchHistory`命令会报错：

![1](https://user-images.githubusercontent.com/5853792/49595758-a9eace00-f9b3-11e8-936d-7a8665e25f42.png)

**Comment by Yggdroot** [comment]
Fix了。

**Comment by bstaint** [comment]
谢谢，没问题了
