### ISSUE TITLE
搜索中文名文件显示多字节字符问题

### ISSUE THREAD

**Issue by zengzhuohao** [Yggdroot/LeaderF#253]
你好，我使用leaderf搜索中文文件的时候，显示文件名乱码(应该转成多字节了)，乱码显示如下：
![image](https://user-images.githubusercontent.com/45678880/49869794-734a0300-fe4c-11e8-96e2-d078abab3b20.png)

我尝试用"LeaderF file -E=utf-8 <PATH>"命令来设置格式，也不管用，另外我的.vimrc文件也设置了"set encoding=utf-8 "，不知问题出在哪里，还请指教，谢谢~

**Comment by Yggdroot** [comment]
`:echo g:Lf_Debug_Cmd` 输出是什么？

**Comment by Yggdroot** [comment]
This is a duplicate of issue #203 .
这是git的问题，你直接在终端使用`git ls-files`也会这样。

**Comment by zengzhuohao** [comment]
按照 #203 已经修复了这一问题，非常感谢。
另外我刚才分别在终端用 vim 和 macvim上分别试用leaderf的功能的时候，发现中文输入异常的情况(同https://github.com/Yggdroot/LeaderF/issues/200)，但这种情况在终端的vim上是正常的(一样的输入法)。
按照你提到方法：:echom getchar()后输入“我”，在终端vim上是正确返回25105，在macvim上却返回119(应该是在输入“我”的时候，先接收到了w)。
https://github.com/Yggdroot/LeaderF/issues/200后续没有跟进是如何解决的，且本人菜鸟一枚，希望能够得到大神的帮助~

**Comment by zengzhuohao** [comment]
macvim的版本是8.1.560

**Comment by Yggdroot** [comment]
> 按照你提到方法：:echom getchar()后输入“我”，在终端vim上是正确返回25105，在macvim上却返回119(应该是在输入“我”的时候，先接收到了w)。

这个很可能是macvim的bug或者是输入法的bug， 输出119已经证明了呀，我也解决不了。

**Comment by zengzhuohao** [comment]
好的，多谢~
