### ISSUE TITLE
Report errors when using LeaderF

### ISSUE THREAD

**Issue by createwindow** [Yggdroot/LeaderF#255]
yes

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)`
- Output of `:echo has("python")`:  1
- Output of `:echo has("python3")`:  0
- Output of `:echo &pythondll`(only vim, not neovim):  `/System/Library/Frameworks/Python.framework/Versions/2.7/Python`
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
`/System/Library/Frameworks/Python.framework/Versions/3.7/Python`
- Output of `:py print(sys.version)`: 
![image](https://user-images.githubusercontent.com/4122051/49909793-47b23180-febb-11e8-9345-16d724e98bb8.png)

- Output of `:py3 print(sys.version)`: 
![image](https://user-images.githubusercontent.com/4122051/49909840-6ca6a480-febb-11e8-8951-464d7b82252e.png)

- Output of `:echo g:Lf_Debug_Cmd`:  Undefined variable: g:Lf_Debug_Cmd
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_UseVersionControlTool = 0
" let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_RootMarkers = ['.git', '.hg', '.svn']
nnoremap <silent> <Leader>t :LeaderfBufTag<CR>
nnoremap <silent> <Leader>l :LeaderfLine<CR>
nnoremap <silent> <Leader>m :LeaderfMru<CR>
nnoremap <silent> <Leader>h :LeaderfHistoryCmd<CR>

let g:Lf_WildIgnore = {
    \ 'dir': ['.svn','.git','.hg','chromium/src/third_party/webrtc'],
    \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]','*.a','*.bin','*.wav','*.pcm','*yuv','*.rtp','*.d','gtags.files','GRTAGS','GTAGS','GPATH']
    \}
```

### Describe your question, feature request, or bug.

each time I  typed `<C-P>` to use LeaderF, the following errors are reported.
```
Error detected while processing /Volumes/espace/softwares/dotvim/bundle/LeaderF/autoload/leaderf/File.vim:
line   14:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Volumes/espace/softwares/dotvim/bundle/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 14, in <modul
e>
    from .manager import *
  File "/Volumes/softwares/dotvim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 10, in <module
>
    import multiprocessing
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/__ini
t__.py", line 65, in <module>
    from multiprocessing.util import SUBDEBUG, SUBWARNING
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/util.
py", line 37, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14,
 in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Error detected while processing function leaderf#File#startExpl[2]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'fileExplManager' is not defined
```

**Comment by Yggdroot** [comment]
This issue is not related to LeaderF, it's because of `ImportError: cannot import name _remove_dead_weakref`.

You can turn to [here](https://askubuntu.com/questions/981663/python2-7-broken-by-weakref-import-error-please-help) for help.

**Comment by createwindow** [comment]
Thanks for your quick response. 
Here is the solution: 
Uninstalling Python@2 by
`brew remove python@2 --ignore-dependencies`
