### ISSUE TITLE
[Feature Request] Support delete MRU item

### ISSUE THREAD

**Issue by hiberabyss** [Yggdroot/LeaderF#256]
Sometimes, there are outdated items in MRU, could command like `LeaderfClearMRU pattern` provided to clear these items?

**Comment by Yggdroot** [comment]
There has already been a way to delete outdated items.
1.` :Leaderf mru`
2. press `<tab>` to switch to normal mode
3. delete the items with `d`

**Comment by hiberabyss** [comment]
Following error occurs when I try to delete a item in mru:

![image](https://user-images.githubusercontent.com/2898670/49924528-8ebb1980-fef1-11e8-8599-b24a093920ae.png)

**Comment by Yggdroot** [comment]
Are you using the latest version? How to reproduce it?

**Comment by hiberabyss** [comment]
The `Leaderf` is the latest version: a572b353c797a24b29f21020ede7474709c82f05

Reproduce:

1. Open vim, execute `Leaderf mru`
2. Move to an item and then press `d`, then the error occur.

**Comment by Yggdroot** [comment]
Could you help to debug this issue?
https://github.com/Yggdroot/LeaderF/blob/a572b353c797a24b29f21020ede7474709c82f05/autoload/leaderf/python/leaderf/mruExpl.py#L73-L80

Add
```python
print(lines)
print(repr(lfEncode(os.path.abspath(lfDecode(name))) + '\n'))
```
below line 75, to see the output after `d` is pressed.

**Comment by hiberabyss** [comment]
@Yggdroot Here is the output after add the codes:

![image](https://user-images.githubusercontent.com/2898670/49930964-c4b3ca00-ff00-11e8-95be-691ebc586502.png)

**Comment by Yggdroot** [comment]
Can not reproduce. Please remove `$HOME/.LfCache` and have a try.
