### ISSUE TITLE
Stop complaining about python error

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#26]
Hi, I enjoy LeaderF very much and it is one of my basic plugins. However, sometimes I need to run Vim in environments without python support, such as Git Bash on Windows. In this case, LeaderF keep complaining when I start Vim, which is really annoying:
```
Error detected while processing /c/Users/tanle/vimfiles/bundle/LeaderF/plugin/leaderf.vim:
line   24:
Error: LeaderF requires vim compiled with +python or +python3
Press ENTER or type command to continue
```
Any suggestions for this?
Thanks very much!

**Comment by Yggdroot** [comment]
Thanks for reporting, I'll fix it soon.
Currently, as a workaround, you can add these lines in your vimrc:
````vim
if !has("python") && !has("python3")
    let g:leaderf_loaded = 1
endif
````

**Comment by tamlok** [comment]
Thanks!
I think we should figure out what is the proper manner to handle situations that do not meet the requirements of LeaderF, such as an old Vim's version, lack of Python support etc.
Of course, it is better if Vundle provides functionality like conditional compilation. Something like this:
```
if has("python")
    Plugin LeaderF
endif
```

**Comment by Yggdroot** [comment]
I decide not to fix it any more. If someone else encounters this issue again, let him use the wrokaround.
