### ISSUE TITLE
two cursors inside prompt

### ISSUE THREAD

**Issue by amzyang** [Yggdroot/LeaderF#260]
- vim or neovim? 
    - [ ] vim
    - [ x] neovim
- Output of `vim --version` or `nvim --version`: 

NVIM v0.4.0-1177-gc8e78abaf

NVIM v0.3.3

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Actual behaviour
![image](https://user-images.githubusercontent.com/348936/50826602-0ce6d080-1377-11e9-8aae-b01a06cde346.png)

**Comment by Yggdroot** [comment]
This is a [bug ](https://github.com/neovim/neovim/issues/6538) of neovim that has not been fixed.
