### ISSUE TITLE
Leaderf rg is much slower than using rg directly

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#261]
- vim or neovim? 
    - [ x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1 431
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.5m.so.1.0
- Output of `:py3 print(sys.version)`: 3.5.3 (default, Sep 27 2018, 17:25:39) GCC 6.3.0 20170516
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_PreviewCode = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_DefaultMode = 'FullPath'
nnoremap fg :<C-u><C-R>=printf("Leaderf! rg --stayOpen -e ")<CR>
```

### Steps to reproduce
```
$cd .vim
$time rg set

$vim
fg set<CR>
```
### Actual behaviour
using rg directly `rg set  0.84s user 4.71s system 37% cpu 14.650 total`
use leaderf rg more than three minutes, and make vim slower.

### Expected behaviour
both of them spent almost the same time, vim is not stuck

**Comment by Yggdroot** [comment]
Did you try many times? it is accturally a little slower than using rg directly, but it should not be slower so much.

**Comment by fcying** [comment]
It stuck by some file, In my `.vim`, it is `deoplete-go`
reproduce:
```
$git clone https://github.com/zchee/deoplete-go.git
$rm -rf deoplete-go/.git
$cd deoplete-go/benchmark/json
$vim
fg set<CR>
```
May be there is too much content in one line in json file?

**Comment by Yggdroot** [comment]
I test it on my machine:
```
[yggdroot@Yggdroots-Mac:~/home/workspace/deoplete-go]$ time rg -e set > /dev/null

real	0m0.056s
user	0m0.027s
sys	0m0.027s
```
and Leaderf rg takes 0.14s.

**Comment by Yggdroot** [comment]
I can not reproduce the slow performance.
test.py:
```
import sys
import time
import subprocess
import shlex


start = time.time()

proc = subprocess.Popen(("rg --no-ignore-messages --no-heading --with-filename --color never --line-number -S -e {} ".format(sys.argv[1])),
                           shell=True,
                           bufsize=-1,
                           stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE,
                           universal_newlines=False)
out, err = proc.communicate()

end = time.time()
print('Finished in %f seconds' % (end - start))
print(len(out))

start = time.time()
out = subprocess.check_output(shlex.split("rg --no-ignore-messages --no-heading --with-filename --color never --line-number -S -e {} ".format(sys.argv[1])))
end = time.time()
print('Finished in %f seconds' % (end - start))
print(len(out))
```
Please have a try this script, to see the output.
usage: `python3 test.py set`

How to reproduce the OOM?

**Comment by fcying** [comment]
use `leaderf rg` , it consume a lot of memory.
I test in three machine.
`linux-1, 2gb ram, swap 16gb`
```
$ py3 test.py set
Finished in 397.045322 seconds
2601682943
Finished in 259.878460 seconds
2601682943
```

`linux-2, 16gb ram, swap 16gb`
```
py3 test.py set
Finished in 10.166908 seconds
2601682943
Finished in 7.037130 seconds
2601682943
```

`windows, 8gb ram, swap auto`
```
D:\workspace\python\testfg
# py3 --version
Python 3.7.1
# py3 test.py set
Exception in thread Thread-1:
Traceback (most recent call last):
  File "d:\tool\python\Python3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "d:\tool\python\Python3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "d:\tool\python\Python3\lib\subprocess.py", line 1232, in _readerthread
    buffer.append(fh.read())
MemoryError

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    out, err = proc.communicate()
  File "d:\tool\python\Python3\lib\subprocess.py", line 933, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "d:\tool\python\Python3\lib\subprocess.py", line 1265, in _communicate
    self.stderr_thread.join(self._remaining_time(endtime))
  File "d:\tool\python\Python3\lib\threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "d:\tool\python\Python3\lib\threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
![image](https://user-images.githubusercontent.com/106934/51228324-0538b480-1993-11e9-8ed1-f3641432a734.png)

**Comment by Yggdroot** [comment]
I think there is something wrong with your Windows version python3.7.1.

Where did you run `py3 test.py set`, json folder or deoplete-go or somewhere else?

**Comment by fcying** [comment]
[testfg.zip](https://github.com/Yggdroot/LeaderF/files/2762823/testfg.zip)
just with json files.
linux `2gb ram, none swap` have wrong also.

**Comment by Yggdroot** [comment]
my output is:
```
$ python3 test.py set
Finished in 0.063134 seconds
2046022
Finished in 0.036705 seconds
2046022
```
2046022 vs 2601682943, can you explain why?

**Comment by fcying** [comment]
my ripgreprc have option `--vimgrep`.

if I disable this option:

`lin-1 2gb, 16gb`
```
py3 test.py set
Finished in 0.038669 seconds
2046037
Finished in 0.018733 seconds
2046037
```

work fine in windows also

Can't use this option?

**Comment by Yggdroot** [comment]
--vimgrep
            Show results with every match on its own line, including line numbers and
            column numbers. With this option, **a line with more than one match will be
            printed more than once.**

**Comment by fcying** [comment]
`--vimgrep` printed too much, memory is not enough.

test in `linux struct` only 140540087 (no --vimgrep)
```
linux ‹master›$ py3 test.py struct
Finished in 0.997823 seconds
140540087
Finished in 11.880832 seconds
140540087
``` 

Is there any setting show results with every match on its own line, including line numbers and
column numbers, but not printed more than once?

**Comment by Yggdroot** [comment]
`rg --no-heading --with-filename --line-number --column -e xxx`

**Comment by fcying** [comment]
tks very much~_~

**Comment by fcying** [comment]
@Yggdroot 
add a option for set global custom rg setting?
ex:
let g:Lf_RgConfig = {'--hidden', '--glob=!**/prj_tags'}

Some common settings have to be set a bit long for each map(have a little more `glob`)

**Comment by Yggdroot** [comment]
Added. https://github.com/Yggdroot/LeaderF/commit/8dad47a4feb20d36ccfcfa44120a814ab12d5c29
