### ISSUE TITLE
Can't find directory XXX in cdpath

### ISSUE THREAD

**Issue by zengzhuohao** [Yggdroot/LeaderF#264]
- vim or neovim? 
    - [1] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): /System/Library/Frameworks/Python.framework/Versions/2.7/Python
- Output of `:echo &pythonthreedll`(only vim, not neovim): /usr/local/Frameworks/Python.framework/Versions/3.7/Python
- Output of `:py print(sys.version)`: 2.7.10 (default, Oct  6 2017, 22:29:07) 
- Output of `:py3 print(sys.version)`: E837: This Vim cannot execute :py3 after using :python
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [ ] Linux
    - [1 ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
default configuration
### Describe your question, feature request, or bug.
Hi, when i change the directory of search ,by using this Command: ":LeaderfFile ~/ML/",  and then i try to open a file 
### Steps to reproduce
the first step:
![image](https://user-images.githubusercontent.com/45678880/51234310-5ce11b00-19a7-11e9-825f-5d5fedbcbd86.png)
the second step:
![image](https://user-images.githubusercontent.com/45678880/51234371-7f733400-19a7-11e9-8db8-e3bd9643d8f2.png)
click"Enter" , then error occurred:
![image](https://user-images.githubusercontent.com/45678880/51234255-33c08a80-19a7-11e9-8706-0bb05cb74656.png)
### Actual behaviour
an error prompt:"Vim(lcd):E344: Can't find directory XXX in cdpath".
### Expected behaviour
open the file normally

**Comment by zengzhuohao** [comment]
if I search the file in the current directory, I can open the file normally; 
but , if I search the file which is not in the current directory ,the error always occurred while I try to open it.

**Comment by Yggdroot** [comment]
Please provide a minimum vimrc to reproduce it.

**Comment by zengzhuohao** [comment]
[vimrc.txt](https://github.com/Yggdroot/LeaderF/files/2763235/vimrc.txt)

**Comment by Yggdroot** [comment]
Please remove 
```vim
let g:autochdir = 1
if exists('g:autochdir')
autocmd BufEnter * if bufname("") !~ "^[A-Za-z0-9]*://" | lcd %:p:h | endif
endif
```
and have a try.
