### ISSUE TITLE
[feature request] display search status in statusbar?

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#268]
When I  use `leaderf line` in a large file, after I press the search keyword, If this keyword is behind the file.
It will display `0/0` for a long time, I can't judge it have not keyword or the search didn't finish.

Can you add some search status? 
ex:
![image](https://user-images.githubusercontent.com/106934/51811144-976f7f80-22e6-11e9-99be-c41cdc395b6f.png)
![image](https://user-images.githubusercontent.com/106934/51811168-aeae6d00-22e6-11e9-96ed-75c74d96fa0a.png)

**Comment by Yggdroot** [comment]
Vim does not support multithread, it may have performance issue to display status.
You can use `Leaderf rg` to search some keyword in a large file. It will display a "Done!" if finished.

**Comment by fcying** [comment]
`Leaderf rg` is not like `leaderf line`, support real-time display result.
I see the search results `1/623918` there is constantly updated, Can't display a lable `searching` `done`? 
no need multithread, only display twice. 

![image](https://user-images.githubusercontent.com/106934/51812591-27182c80-22ed-11e9-8e63-5cd4ac161025.png)

**Comment by Yggdroot** [comment]
What about adding a percentage there?

**Comment by Yggdroot** [comment]
Refreshing the statusline may slow down the performance a little, I don't plan to implement this feature any  more.

**Comment by andyshrk** [comment]
when i search a file or search keywords user Leaderf rg -e， the keywords display is withe。 Is there a way to give the keywords a special color？
