### ISSUE TITLE
the action 'remove from mru list' can't work

### ISSUE THREAD

**Issue by liangguohuan** [Yggdroot/LeaderF#27]
Platform: Ubuntu 14.04.5
Vim version:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb 27 2016 23:15:46)
Included patches: 1-1425

Action:
d : remove from mru list

Erros:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hanson/.vim/bundle/LeaderF/autoload/leaderf/mruExpl.py", line 85, in deleteMru
    self._explorer.delFromCache(line)
  File "/home/hanson/.vim/bundle/LeaderF/autoload/leaderf/mruExpl.py", line 48, in delFromCache
    lines.remove(name + '\n')
ValueError: list.remove(x): x not in list

**Comment by Yggdroot** [comment]
Thanks for reporting. I don't know how to reproduce it. Could you help to check whether this issue has been fixed by new commit?

**Comment by liangguohuan** [comment]
Thank you for following up.
i update your new commit to up-to-date, and it still get the same error.

**Comment by liangguohuan** [comment]
I trac your source file, and i found the problom now.

in mruExpl.py line 46, just put you the code `name = os.path.abspath(name)` to the method 'delFromCache'.

You save filepath to `~/.LfCache/mru/mruCache` via abspath, but `delFromCache` method dont change relativepath to abspath it yet.
