### ISSUE TITLE
LeaderfTag 问题：tagfiles() 更新了，数据却不更新

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#273]
https://github.com/Yggdroot/LeaderF/blob/cd4eec6339a37b8a03d28fdc1aaaa787209e208b/autoload/leaderf/python/leaderf/tagExpl.py#L20-L32

有两种情况：
1. 切换了文件后，tagfiles() 返回的值会更新：因为 gutentags 插件已经自动帮我根据项目生成 tags 数据库，并自动对当前文件 setlocal tags+=... 了，手工也可能调用 set[local] tags+=...，所以切换文件 tagfiles() 返回值不是恒定的。
2. tagfiles() 返回值没有改变，但是 tags 文件改变了，gutentags 等插件会根据文件修改自动更新 tags.

这两种情况都应该重新读取 tags 数据库，但是上面的代码中，只有第一次会读取，读取完了以后就再也不会改变了。导致我切换了文件，或者修改了代码，使用 LeaderfTag 还是一直出现老的 tags.

这个问题不解决，我在 Vim 里就不能切换或者修改文件了，否则 LeaderfTag 的内容就是错的。

**Comment by Yggdroot** [comment]
这个不缓存，每次都重新读取就可以了，只是有个问题，如果文件太大（tags文件往往比较大），每次执行LeaderfTag 都要花费一两秒甚至更多来加载。我在想是不是还要记一下每个tags的修改时间，用来判断是否修改了来做些缓存。

**Comment by skywind3000** [comment]
最近开始逐步尝试使用 LeaderfTag 功能了，发现挺好用，就是有些问题，所以又来烦你了。

**Comment by Yggdroot** [comment]
这个问题改好了，在tag branch，你测测看。
我再看看性能能不能再改进一下，再加上分号操作符支持。

**Comment by skywind3000** [comment]
初步测试，可以正常工作，但是有几次在 LeaderfTag 的 `>>> ` 提示符后面输入内容输入到一半的时候：

![signature](https://user-images.githubusercontent.com/3035071/52009368-b7cd5300-250d-11e9-99c2-1f6a0a97865e.png)

我不知道是 https://github.com/kshenoy/vim-signature 的问题，还是 Leaderf 的问题。

**Comment by skywind3000** [comment]
我重现了，只要使用了 signature ，并且在 leaderf 的 normal 模式的窗口中输入任何以m开头的命令，比如mm，就会出现上面的错误。

**Comment by skywind3000** [comment]
确认了，应该和本次修改无关。

**Comment by Yggdroot** [comment]
这不是leaderf的问题，错误报在signature这个插件。

**Comment by skywind3000** [comment]
嗯，那 merge 吧，我看没啥问题

**Comment by skywind3000** [comment]
leaderf 的 normal 窗口中，没有 feedkey/normal 过 m 开头的命令吧？

**Comment by Yggdroot** [comment]
没有。

**Comment by Yggdroot** [comment]
merge了。
