### ISSUE TITLE
[Feature Request] avoid change directory when use `:LeaderfFile`

### ISSUE THREAD

**Issue by hiberabyss** [Yggdroot/LeaderF#274]
Currently, when run command like `LeaderfFile ~/vimwiki` and open the file, the `pwd` will be changed to the directory of the file.

Could the `pwd` be kept without change when use `LeaderfFile`?

Thanks!

**Comment by Yggdroot** [comment]
But some others may want to keep the current behavior.

**Comment by hiberabyss** [comment]
@Yggdroot Could an option provided to control the behavior?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/b9146ddf617c1041adec23b762a540a2f657d2cd/doc/leaderf.txt#L552-L556

**Comment by hiberabyss** [comment]
Hi @Yggdroot ,

After add the configuration `let g:Lf_NoChdir = 1`, following error will occur when run `:LeaderfFile ~/vimwiki`:

![image](https://user-images.githubusercontent.com/2898670/52621064-5465fc80-2ee1-11e9-8aee-b14f786c2858.png)

**Comment by Yggdroot** [comment]
What is the output of `:echo g:Lf_Debug_Cmd`  and `pwd` ?

**Comment by hiberabyss** [comment]
The result of `:echo g:Lf_Debug_Cmd` is:

```
git ls-files --recurse-submodules "/Users/hbliu/vimwiki" && git ls-files --others --exclude-standard  "/Users/hbliu/vimwiki"
```

And the `pwd` is `/Users/hbliu`

**Comment by Yggdroot** [comment]
What is the output of `echo g:Lf_WorkingDirectoryMode` ?

**Comment by hiberabyss** [comment]
It's `c`.

**Comment by Yggdroot** [comment]
I think this issue is not related to LeaderF, it is an issue of git. You can try `git ls-files --recurse-submodules "/Users/hbliu/vimwiki" && git ls-files --others --exclude-standard  "/Users/hbliu/vimwiki"` in the comandline to figure out the root cause.

**Comment by hiberabyss** [comment]
Why `git` is used since `~/vimwiki` is not a git repo?

**Comment by Yggdroot** [comment]
> When `let g:Lf_NoChdir = 0`, the command `:LeaderfFile ~/vimwiki ` could work.
> 
What is the output of `:echo g:Lf_Debug_Cmd` if let g:Lf_NoChdir = 0` ?
> Why `git` is used since `~/vimwiki` is not a git repo?
> 
It is because there is a `.git` directory in its ancestor path. So `~` is a git repo ?

**Comment by hiberabyss** [comment]
> What is the output of `:echo g:Lf_Debug_Cmd` if let g:Lf_NoChdir = 0` ?

The output is `git ls-files --recurse-submodules "/Users/hbliu/.dotfiles/private/link/vimwiki" && git ls-files --others --exclude-standard  "/Users/hbliu/.dotfiles/private/link/vimwiki"` .

> It is because there is a `.git` directory in its ancestor path. So `~` is a git repo ?

`~` is not a git repo. In fact, `~/vimwiki` is a link to `/Users/hbliu/.dotfiles/private/link/vimwiki` and `/Users/hbliu/.dotfiles/private` is a git repo.

**Comment by Yggdroot** [comment]
Do you know the root cause now? 
Run `git ls-files --recurse-submodules "/Users/hbliu/.dotfiles/private/link/vimwiki" && git ls-files --others --exclude-standard "/Users/hbliu/.dotfiles/private/link/vimwiki"` at `/Users/hbliu` and `~/vimwiki` respectively,  I think you can find the reason.

**Comment by hiberabyss** [comment]
Using following cmd should work:

```
cmd = '(cd %s && git ls-files %s && git ls-files --others %s %s) | sed "s,^,%s/," ' % (dir, recurse_submodules, no_ignore, ignore, dir)
```

**Comment by hiberabyss** [comment]
The `let g:Lf_UseVersionControlTool = 0` setting could also solve my problem.
