### ISSUE TITLE
LeaderF突然不能使用了

### ISSUE THREAD

**Issue by ppnman** [Yggdroot/LeaderF#275]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
`VIM - Vi IMproved 8.1`
- Output of `:echo has("python")`: 
`0`
- Output of `:echo has("python3")`: 
`1`
- Output of `:echo &pythondll`(only vim, not neovim): 
没有输出
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
没有输出
- Output of `:py print(sys.version)`: 
`E391 sorry, the command is not availble in this version`
- Output of `:py3 print(sys.version)`: 
`3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609]
`
- Output of `:echo g:Lf_Debug_Cmd`: 
`undefined variable g:Lf_Debug_Cmd`
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
nnoremap <leader>m :LeaderfMru<CR>

nnoremap <leader>lf :LeaderfFile

let g:Lf_WindowHeight=0.3
```

### Describe your question, feature request, or bug.
呼出leaderF的界面之后，没法打字，也没法退出。
### Steps to reproduce
1. 一个崭新的ubuntu16.04LTS系统
2. 下载vim8.1，vim-plug
3. `:PlugInstall`安装好需要的插件
4. leaderf挂了

全程就执行了一个`install.sh`脚本，脚本内容如下：
```
# 安装vim8.0
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install vim

# 安装必备软件
sudo apt install cmake git curl tmux python-dev python3-dev python3-pip

# 安装Python语法检错工具和代码规范工具
sudo pip3 install flake8 autopep8

# 安装vim-plug插件
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```

**Comment by Yggdroot** [comment]
This issue is because of https://github.com/vim/vim/issues/3874.

**Comment by ppnman** [comment]
@Yggdroot  我已经是最新的leaderf了呀，还是有这个问题，无法输入文字，无法退出

**Comment by Yggdroot** [comment]
你有没有好好看看这个issue呀，说的是vim的bug导致的，要更新最新的vim，或者降级vim，跟LeaderF没关系。

**Comment by ppnman** [comment]
@Yggdroot 
谢谢，已经更新了最新的vim，解决了。
