### ISSUE TITLE
Why my LeaderF can't work after enter

### ISSUE THREAD

**Issue by Comux** [Yggdroot/LeaderF#276]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```sh
" leaderF
" list functions: <F2>
noremap <F2> :LeaderfFunction!<cr>
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_PreviewResult = { 'Function':0, 'Colorscheme':1}

let g:Lf_NormalMap = {
    \ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
    \ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>']],
    \ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>']],
    \ "Tag":    [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<CR>']],
    \ "Function":    [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<CR>']],
    \ "Colorscheme":    [["<ESC>", ':exec g:Lf_py "colorschemeExplManager.quit()"<CR>']],
    \ }

let g:Lf_ShortcutF = '<c-p>'
let g:Lf_ShortcutB = '<m-n>'
noremap <c-n> :LeaderfMru<cr>
noremap <m-p> :LeaderfFunction!<cr>
noremap <m-n> :LeaderfBuffer<cr>
noremap <m-m> :LeaderfTag<cr>
let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'powerline'
let g:Lf_PreviewResult = { 'Function':0, 'BufTag':0}
```
### Describe your question, feature request, or bug.
My LeaderF can't work after I press the '`<c-p>`' to select files.
When I enter the LeaderF, the Vim is stuck, I can't switch or choose any files.

### Steps to reproduce
- press \<c-p>
### Actual behaviour
The whole vim is stuck.
### Expected behaviour
Choose one file from the file list.

**Comment by Comux** [comment]
Hi, and now the LeaderF in my Vim only support function list.
However, When I press <F2> twice, my Vim will transform 
to 'Insert' mode, and there will automatic open a new line with `Q` in the editor!

**Comment by Yggdroot** [comment]
Do you mean this issue? https://github.com/vim/vim/issues/3874.

**Comment by Comux** [comment]
yes! @Yggdroot

**Comment by Yggdroot** [comment]
So please update your vim.

**Comment by Comux** [comment]
en, now my vim version is -8.1.0837. Could you tell me how to update my vim? I used the `ppa:jonathonf/vim` to install my vim before. It shows that my vim is up to latest.

**Comment by Comux** [comment]
Thanks! @Yggdroot
