### ISSUE TITLE
tag subcommand failed to execute

### ISSUE THREAD

**Issue by JayceCao** [Yggdroot/LeaderF#278]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
No python2 support.
- Output of `:py3 print(sys.version)`: 
```
3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Execute `:Leaderf tag sys_call_table`, get:
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/nitrocao/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 675, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/nitrocao/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 637, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/nitrocao/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1183, in startExplorer
    self._cli.setNameOnlyFeature(self._getExplorer().supportsNameOnly())
  File "/home/nitrocao/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 343, in _getExplorer
    self._explorer = self._getExplClass()()
  File "/home/nitrocao/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/tagExpl.py", line 18, in __init__
    os.stat_float_times(False)
AttributeError: module 'os' has no attribute 'stat_float_times'
```

**Comment by JayceCao** [comment]
After testing, `os.stat_float_times` has been removed in `Python 3.7.2`.
> The os.stat_float_times() function has been removed. It was introduced in Python 2.3 for backward compatibility with Python 2.2, and was deprecated since Python 3.1. 
 (https://docs.python.org/3/whatsnew/3.7.html)

**Comment by Yggdroot** [comment]
Thanks for your report, this issue is fixed.
But your usage `:Leaderf tag sys_call_table` is not correct, please run `Leaderf tag -h` to see the usage.

**Comment by JayceCao** [comment]
Thanks for your work. I'll read the doc carefully again :)


> Thanks for your report, this issue is fixed.
> But your usage `:Leaderf tag sys_call_table` is not correct, please run `Leaderf tag -h` to see the usage.
