### ISSUE TITLE
LeaderfFile chinese path encoding wrong

### ISSUE THREAD

**Issue by TC500** [Yggdroot/LeaderF#279]
### Describe your question, feature request, or bug.
this problem cause by git, the leaderf get file path by 'git ls-files --others', but git will show chinese file path in wrong encoding if set 'core.quotepath' to true:
```shell
$ git config --global core.quotepath true
$ git ls-files --other .                  
$ "2019-02-08-\351\253\230\346\225\210\347\232\204vim.md"
$ git config --global core.quotepath false
$ git ls-files --other .  
$ 2019-02-08-高效的vim.md
```
you may need set core.quotepath before `git ls-files` and reset it after cmd, like this
```shell
$ quotepath=`git config core.quotepath` && git config core.quotepath false && git ls-files --others && git config core.quotepath $quotepath            
```

**Comment by Yggdroot** [comment]
I don't think this issue is related to LeaderF, it's a issue of usage of git.

**Comment by Yggdroot** [comment]
Duplicate of #203 .

**Comment by TC500** [comment]
thanks for your answer
