### ISSUE TITLE
crash when searching file in the source of YouCompleteMe

### ISSUE THREAD

**Issue by mzlogin** [Yggdroot/LeaderF#28]
![image](https://cloud.githubusercontent.com/assets/1646590/19842272/3fb4baea-9f52-11e6-8d47-fbcef4ee3ffa.png)

RT, it works fine on other directory, but when I'm trying to search a file in the source of newest [YouCompleteMe](https://github.com/Valloric/YouCompleteMe), it will crash after I press any key.

**Comment by Yggdroot** [comment]
This is a codec issue. Because there is a directory called `YouCompleteMe\python\ycm\tests\testdata\uni¢𐍈d€`.

**Comment by mzlogin** [comment]
Yes, I deleted it and then LeaderF works fine. It may not appears very often but does exist. Do you have plan to fix and compatible this?

**Comment by Yggdroot** [comment]
It's a thorny issue. Now I have no idea how to resolve it. I'll fix it in the future.

**Comment by mzlogin** [comment]
OK~Thx.

**Comment by Yggdroot** [comment]
A workaround has been committed.

**Comment by mzlogin** [comment]
It works! Thanks a lot.
