### ISSUE TITLE
leaderf line regex mode jump error `embedded null byte` in some file

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#280]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1 770
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.5m.so.1.0
- Output of `:py3 print(sys.version)`: 3.5.3 (default, Sep 27 2018, 17:25:39) GCC 6.3.0 20170516
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_PreviewCode = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_DefaultMode = 'FullPath'
```

### Steps to reproduce
```
vim putty868956545.log
:Leaderf line
```

### Actual behaviour
Fuzzy mode work fine
regex mode input sth jump `embedded null byte`

![image](https://user-images.githubusercontent.com/106934/52685251-0f46d680-2f84-11e9-8039-bde432c94b32.png)

[putty868956545.log](https://github.com/Yggdroot/LeaderF/files/2858709/putty868956545.log)

**Comment by Yggdroot** [comment]
Fixed.

**Comment by fcying** [comment]
It work fine now~
