### ISSUE TITLE
[Feature request] Improvements on rg search

### ISSUE THREAD

**Issue by Cappuccin0** [Yggdroot/LeaderF#282]
Could you please consider adding support for below two improvements that I found from fzf.vim and ack.vim?

1. Add auto complete for path to be searched while searching with rg?
For instance, suppose we have a folder named _src_ in current directory and I'm using below command..
`:Leaderf rg -e mypattern sr<tab>`
After pressing tab, the auto complete should be triggered and make "_sr_" to be "_src_".

2. Preview window in rg result
It's an advanced feature in fzf and [here](https://junegunn.kr/2016/07/fzf-git/) is a bit more on how it looks like. And it would be even greater if Leaderf can support scrolling in the previous window.

Thanks!

**Comment by Yggdroot** [comment]
> Could you please consider adding support for below two improvements that I found from fzf.vim and ack.vim?
> 
> 1. Add auto complete for path to be searched while searching with rg?
>    For instance, suppose we have a folder named _src_ in current directory and I'm using below command..
>    `:Leaderf rg -e mypattern sr<tab>`
>    After pressing tab, the auto complete should be triggered and make "_sr_" to be "_src_".

You can define a command by yourself.
```vim
command! -bang -nargs=* -complete=file LeaderfRg exec printf("Leaderf<bang> rg %s", escape('<args>', '\\'))
```
It will work the same as Ack.

> 2. Preview window in rg result
>    It's an advanced feature in fzf and [here](https://junegunn.kr/2016/07/fzf-git/) is a bit more on how it looks like. And it would be even greater if Leaderf can support scrolling in the previous window.
> 

You can use `<c-p>` in input mode and `p` in normal mode to preview the code.
You can even set `let g:Lf_PreviewResult = {'Rg': 1 }` to preview code on every movement of the cursor.

**Comment by Cappuccin0** [comment]
Both solutions work great for me! Thanks a lot!
