### ISSUE TITLE
delete extra space when LeaderfHistorySearch

### ISSUE THREAD

**Issue by TC500** [Yggdroot/LeaderF#283]
suggest:
`--- historyExpl.py`
`@@ -37,0 +37,0 @@`
`- result_list = [line[1:].lstrip().split(`'<kbd>space</kbd>'`, 1)[1] for line in result_list]`
`+ result_list = [line[1:].lstrip().split(`'<kbd>space</kbd><kbd>space</kbd>'`, 1)[1] for line in result_list]`

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)                                                                                      
包含补丁: 1-1453                                                                                                                                        
修改者 pkg-vim-maintainers@lists.alioth.debian.org                                                                                                      
编译者 pkg-vim-maintainers@lists.alioth.debian.org                                                                                                      
巨型版本 with GTK3 GUI.  可使用(+)与不可使用(-)的功能:                                                                                                  
+acl               +farsi             +mouse_sgr         -tag_any_white                                                                                 
+arabic            +file_in_path      -mouse_sysmouse    +tcl                                                                                           
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors                                                                                 
-autoservername    +float             +mouse_xterm       +terminal                                                                                      
+balloon_eval      +folding           +multi_byte        +terminfo                                                                                      
+balloon_eval_term -footer            +multi_lang        +termresponse                                                                                  
+browse            +fork()            -mzscheme          +textobjects                                                                                   
++builtin_terms    +gettext           +netbeans_intg     +timers                                                                                        
+byte_offset       -hangul_input      +num64             +title                                                                                         
+channel           +iconv             +packages          +toolbar                                                                                       
+cindent           +insert_expand     +path_extra        +user_commands                                                                                 
+clientserver      +job               +perl              +vertsplit                                                                                     
+clipboard         +jumplist          +persistent_undo   +virtualedit                                                                                   
+cmdline_compl     +keymap            +postscript        +visual                                                                                        
+cmdline_hist      +lambda            +printer           +visualextra                                                                                   
+cmdline_info      +langmap           +profile           +viminfo                                                                                       
+comments          +libcall           -python            +vreplace                                                                                      
+conceal           +linebreak         +python3           +wildignore                                                                                    
+cryptv            +lispindent        +quickfix          +wildmenu                                                                                      
+cscope            +listcmds          +reltime           +windows                                                                                       
+cursorbind        +localmap          +rightleft         +writebackup                                                                                   
+cursorshape       +lua               -ruby              +X11                                                                                           
+dialog_con_gui    +menu              +scrollbind        -xfontset                                                                                      
+diff              +mksession         +signs             +xim                                                                                           
+digraphs          +modify_fname      +smartindent       +xpm                                                                                           
+dnd               +mouse             +startuptime       +xsmp_interact   
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              +mouse_gpm         +syntax
+ex_extra          -mouse_jsbterm     +tag_binary
+extra_search      +mouse_netterm     +tag_old_static
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
    系统 gvimrc 文件: "$VIM/gvimrc"
    用户 gvimrc 文件: "$HOME/.gvimrc"
第二用户 gvimrc 文件: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
        系统菜单文件: "$VIMRUNTIME/menu.vim"
         $VIM 预设值: "/usr/share/vim"
编译方式: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I
/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/inclu
de/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetyp
e2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.
0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-NQEcoP/vim-8.0.1453=. -fstack-protector-strong -Wformat
 -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
链接方式: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0
 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinu
x  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ld
l -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -
ldl -lz -lpthread -lm
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 

- Output of `:echo &pythonthreedll`(only vim, not neovim): 

- Output of `:py print(sys.version)`: 

- Output of `:py3 print(sys.version)`:
3.6.7 (default, Oct 22 2018, 11:32:17)                                                                                                                  
[GCC 8.2.0]  
- Output of `:echo g:Lf_Debug_Cmd`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShortcutF = '<C-p>'
let g:Lf_ShortcutB = '<leader>lb'
" let g:Lf_DefaultMode = 'FullPath'
nmap <leader>lt :LeaderfBufTag<CR>
nmap <leader>lf :LeaderfFunction<CR>
nmap <leader>ll :LeaderfLine<CR>
nmap <leader>lm :LeaderfMarks<CR>
nmap <leader>lc :LeaderfHistoryCmd<CR>
nmap <leader>ls :LeaderfHistorySearch<CR>
- output of :history /
```vim
:history /                                                                                                                                              
      #  search history                                                                                                                                 
      1  expand                                                                                                                                         
      2                                                                                                                                                 
      3  <map>                                                                                                                                          
      4  map      
```

### Describe your question, feature request, or bug.
line in LeaderfHistorySearch window has extra space char in the begin of line, like:
<kbd>space</kbd>`search history 1`
<kbd>space</kbd>`search history 2`
### Steps to reproduce
:LeaderfHistorySearch
### Expected behaviour
no extra space char in begin of LeaderfHistorySearch, like:
`search history 1`
`search history 2`

**Comment by Yggdroot** [comment]
Thanks, could you create a pull request please?

**Comment by TC500** [comment]
> Thanks, could you create a pull request please?  

ok, glad to do it @Yggdroot
