### ISSUE TITLE
能否提个简单的需求，对于 rg 功能，能否支持 quickfix 功能

### ISSUE THREAD

**Issue by epheien** [Yggdroot/LeaderF#285]
对于搜索到的结果，如果存到quickfix窗口的话，会非常方便

**Comment by epheien** [comment]
rg有个 --vimgrep 就是用于这种场合的

**Comment by Yggdroot** [comment]
这个功能没法实现，不明白你想用quickfix的什么功能？

**Comment by epheien** [comment]
例如rg查询了很多结果，可以在这些结果之间跳转
不实现也无所谓了，用job简单写个也很方便，leaderf就专注用来找文件了，内容的话还是rg+quickfix方便

**Comment by Yggdroot** [comment]
不实现是因为觉得没必要实现，现在已经包含quickfix的功能了，话说这个窗口也没啥特别的功能。我想是Leaderf rg你没用对，结果之间跳转Leaderf也可以呀。
