### ISSUE TITLE
[Feature Request] Support separate filename and directory for 'File' window

### ISSUE THREAD

**Issue by hiberabyss** [Yggdroot/LeaderF#286]
Currently, the MRU window list filename and directory name separately:

![image](https://user-images.githubusercontent.com/2898670/52997039-50465b80-345a-11e9-9da6-705dbff1c20b.png)

Could command `LeaderfFile` also use the same style?

Now the output of `LeaderfFile` look like following:

![image](https://user-images.githubusercontent.com/2898670/52997132-9dc2c880-345a-11e9-9b32-2a89eec74e21.png)

**Comment by Yggdroot** [comment]
There may be performance issue, because there are lots of files(more than 10k) usually.

**Comment by hiberabyss** [comment]
Is it possible to toggle the behavior depends on the files number?

**Comment by Yggdroot** [comment]
Don't plan to implement this feature, if possible, you can implement it by yourself.
