### ISSUE TITLE
:LeaderfFile无法找到目标文件

### ISSUE THREAD

**Issue by roachsinai** [Yggdroot/LeaderF#288]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.so.1.0
- Output of `:py print(sys.version)`: 2.7.15 (default, Jan 10 2019, 23:20:52)
[GCC 8.2.1 20181127]
- Output of `:py3 print(sys.version)`: 3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127]
- Output of `:echo g:Lf_Debug_Cmd`: `find  "/home/roach" -name "." -o   -name ".*" -prune -o -type f -print  2>/dev/null`
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

```
" Yggdroot/LeaderF
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_PreviewResult = {'Function':0, 'Colorscheme':1}

let g:Lf_NormalMap = {
	\ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
	\ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>']],
	\ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>']],
	\ "Tag":    [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<CR>']],
	\ "Function":    [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<CR>']],
	\ "Colorscheme":    [["<ESC>", ':exec g:Lf_py "colorschemeExplManager.quit()"<CR>']],
	\ }
" 命令后加一个叹号会进入 normal 模式
noremap <Leader>f :LeaderfFunction!<cr>
noremap <Leader>fd :LeaderfFunctionCword!<cr>
noremap <Leader>m :LeaderfMru<cr>
noremap <Leader><Leader>d :LeaderfFile<cr>
```

### Steps to reproduce

主文件下有一个名字为argos.wiki的文件和一个名字为temp.py的文件。

打开temp.py之后调用LeaderfFile，无法找到argos.wiki

### Actual behaviour

![screenshot_20190222_004126](https://user-images.githubusercontent.com/9500049/53185750-98bc6f80-363a-11e9-9565-fc3bba71eb3c.png)

### Expected behaviour

找到argos.wiki

**Comment by Yggdroot** [comment]
你不输入任何东西能列出来吗？

**Comment by roachsinai** [comment]
![screenshot_20190222_085249](https://user-images.githubusercontent.com/9500049/53212254-3fc2fa80-367f-11e9-8fe4-1df8be238ba5.png)

什么都不输入的截图。

**Comment by Yggdroot** [comment]
我怀疑那个文件就没有列出来，你执行`find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print | grep argos.wiki` 看看。

**Comment by roachsinai** [comment]
```
hmank ~ > ls | grep argos     
argos.wiki
hmank ~ > find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print | grep argos.wiki
/home/roach/argos.wiki
hmank ~ > 
```

**Comment by Yggdroot** [comment]
这个问题很奇怪，你进入normal模式，搜一下argos.wiki（`/argos.wiki`)看看。
然后你argos.wiki一个字符一个字符的敲，看看后面还剩什么？

**Comment by Yggdroot** [comment]
还有，`find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print` 这个命令的输出能保存个文件发给我吗？

**Comment by roachsinai** [comment]
![screenshot_20190222_101330](https://user-images.githubusercontent.com/9500049/53215195-85d18b80-368a-11e9-89f0-beaf3a9f2166.png)

上面是按下`Tab`之后，搜argos.wiki（`/argos.wiki`)。

**Comment by roachsinai** [comment]
`echo g:Lf_fuzzyEngine_C`和`echo g:Lf_fuzzyMatch_C`的输出都是`1`。

**Comment by roachsinai** [comment]
```
hmank ~ > find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print | fzf
hmank ~ > 
```

命令行里执行之后`fzf`按下a就出来了

![screenshot_20190222_101626](https://user-images.githubusercontent.com/9500049/53215280-ec56a980-368a-11e9-9e5b-ff27de9cb8c5.png)

**Comment by roachsinai** [comment]
`find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print` 这个命令是我主文件中的所有文件啊，233.

把`argos.wiki`和`temp.py`放到小一点儿的文件夹中可以找到。

是不是因为列的问价太多没有存下来？命令行显示总条数是`183423`，而vim中显示`183077`。

**Comment by roachsinai** [comment]
![screenshot_20190222_102308](https://user-images.githubusercontent.com/9500049/53215490-dbf2fe80-368b-11e9-81e0-cc45504f7e4a.png)

也不知道为啥上面那个命令行显示`183422`233

**Comment by roachsinai** [comment]
![screenshot_20190222_102533](https://user-images.githubusercontent.com/9500049/53215556-32f8d380-368c-11e9-88b6-7cc35fed1f41.png)

新开一个terminal session有变了，但是没有和vim差距那么大。

**Comment by roachsinai** [comment]
卧槽，没有没有。这是因为我看一次截一次图。。。


那么问题就是命令行搜到的数目和vim搜到的数目不一致。

**Comment by Yggdroot** [comment]
`find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print | wc -l` 是多少？

**Comment by Yggdroot** [comment]
> ![screenshot_20190222_101330](https://user-images.githubusercontent.com/9500049/53215195-85d18b80-368a-11e9-89f0-beaf3a9f2166.png)
> 
> 上面是按下`Tab`之后，搜argos.wiki（`/argos.wiki`)。

从这张图可以看出，这个文件就不在里面。

**Comment by roachsinai** [comment]
```
hmank ~ > find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print | wc -l
183419
```

![screenshot_20190222_103519](https://user-images.githubusercontent.com/9500049/53215885-90d9eb00-368d-11e9-8bae-bf145e4b461b.png)

和命令行是一致的（刚才把截图删掉了）。

![screenshot_20190222_103634](https://user-images.githubusercontent.com/9500049/53215916-be269900-368d-11e9-9c9c-1efba4c1de0d.png)

vim显示的就少

**Comment by Yggdroot** [comment]
能帮忙看看少的是什么样的文件吗？

**Comment by roachsinai** [comment]
插件的结果可以导出来么？

**Comment by Yggdroot** [comment]
`find  "/home/roach" -name "." -o   -name ".*" -prune -o -type f -print  2>/dev/null | wc -l` 是多少？

**Comment by roachsinai** [comment]
```
hmank ~ > find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print 2>/dev/null | wc -l
183419
hmank ~ > 
```

**Comment by Yggdroot** [comment]
> 插件的结果可以导出来么？

可以，在normal模式下，就跟vim普通的buffer一样复制。

**Comment by Yggdroot** [comment]
可以帮忙看看少的那300多个文件都是些什么文件？

**Comment by Yggdroot** [comment]
还有个可能，是不是那个命令还没有结束，按理说vim中显示的就是`find "/home/roach" -name "." -o -name ".*" -prune -o -type f -print 2>/dev/null`的输出。

**Comment by roachsinai** [comment]
是不是空格分割的文件或文件夹？
![screenshot_20190222_105630](https://user-images.githubusercontent.com/9500049/53216741-8cfb9800-3690-11e9-8977-8260d090eb9b.png)

我再看看我的argos.wiki

**Comment by roachsinai** [comment]
emm，这个有些不对啊，在vim中多出来很多（2000+）我已经删除的文件。回收站我都已经清空了。

![image](https://user-images.githubusercontent.com/9500049/53217655-d7324880-3693-11e9-9b1c-76754fa135fa.png)


上图中那个`WizNotePlus`整个文件夹我都`rm -rf`了。

```
hmank ~ > sudo find / -type d -name "WizNotePlus"
[sudo] roach 的密码：
/mnt/share/Dropbox/linux/WizNotePlus
find: ‘/run/user/1000/gvfs’: 权限不够
/home/roach/Dropbox/linux/WizNotePlus
```

唯一存在的都是我保存到`Dropbox`上的配置文件。

**Comment by roachsinai** [comment]
命令行中列出了3100+个vim没有列出的。但是我看这个文件应该是都有的。

**Comment by Yggdroot** [comment]
现在是查vim上少的问题，怎么又变成多的问题了

> emm，这个有些不对啊，在vim中多出来很多（2000+）我已经删除的文件。回收站我都已经清空了。
> 
> ![image](https://user-images.githubusercontent.com/9500049/53217655-d7324880-3693-11e9-9b1c-76754fa135fa.png)
> 
> 上图中那个`WizNotePlus`整个文件夹我都`rm -rf`了。
> 
> ```
> hmank ~ > sudo find / -type d -name "WizNotePlus"
> [sudo] roach 的密码：
> /mnt/share/Dropbox/linux/WizNotePlus
> find: ‘/run/user/1000/gvfs’: 权限不够
> /home/roach/Dropbox/linux/WizNotePlus
> ```
> 唯一存在的都是我保存到`Dropbox`上的配置文件。

你不是找vim中少的问题吗，怎么又找多的问题了？

LeaderF有缓存，`let g:Lf_UseCache = 0`就不读缓存了。

**Comment by Yggdroot** [comment]
你不用find，换个工具试试，比如说装个rg。

**Comment by roachsinai** [comment]
这是我对比的结果。。不对比我也不是到vim多了那么多不该有的。`WizNotePlus`是本周内删除的，但是也不应该找到啊。

**Comment by roachsinai** [comment]
安装rg之后，需要其他配置么?缓存这时候测试rg要不要取消？

**Comment by Yggdroot** [comment]
> 安装rg之后，需要其他配置么?缓存这时候测试rg要不要取消？

排除干扰，设上`let g:Lf_UseCache = 0`吧。

**Comment by roachsinai** [comment]
关掉缓存之后，rg，find都没有问题。这个缓存下次更新之间保存多长时间？我是第一个遇到这个问题的么？233

**Comment by Yggdroot** [comment]
你说的没问题是什么意思？ argos.wiki可以找到了？
缓存一直存在，刷新缓存，可以按F5。

**Comment by roachsinai** [comment]
是的，找到了。那就是我不按下F5，缓存就永久不变，没有更新间隔？

**Comment by Yggdroot** [comment]
对，需要手动F5刷新。

终于知道这个问题的前因后果了，因为argos.wiki是你最近才创建的，LeaderF每次读的都是缓存。

**Comment by roachsinai** [comment]
刚才微信恢复，没有显示。问一下那如果没有开启缓存，Leaderf每次是把find结果直接传给fzf么？

**Comment by HanleyLee** [comment]
我几个小时前保存的几百个.md 文件 leaderf 全部找不到, 然后我看了你们的聊天记录..., 缓存关闭, 果然找到了.

**Comment by zhouytforever** [comment]
好好的leaderF你胡乱更新什么呢？又是乱码，又是缓存的。
讲一句不太中听的话，这个缓存机制应该是脑子有坑了。我在这写着代码，新建文件，删除文件什么的都是家常便饭，你给我拿5天前的？吓死个人，要没有关闭缓存的配置，我就直接卸载了。

**Comment by roachsinai** [comment]
@zhouytforever 有开关，README.md的`Configuration examples`就有。自己翻翻文档嘛。

**Comment by zhouytforever** [comment]
> @zhouytforever 有开关，README.md的`Configuration examples`就有。自己翻翻文档嘛。
想着有一段时间没用leaderf了，刚刚看了下文档，又重新配置了下。
觉得有些默认值不太合理（最起码的向前兼容应该有吧）：
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_WindowPosition = 'popup'
这是我刚刚改的，window position 可以用 popup 作为默认值，但是cache和version control tool 就别默认为1了吧。
我猜设置cache和version control tool 是为了性能考滤，但是有点考虑不周全的味道。
在一个under git 项目中随便换个文件名字，如果不add 直接搜索不到改名后的文件，强烈建议默认禁用

**Comment by roachsinai** [comment]
你列的三个选项，我只配置了：

```
let g:Lf_UseVersionControlTool = 0
```

> 在一个under git 项目中随便换个文件名字，如果不add 直接搜索不到改名后的文件，强烈建议默认禁用

感觉是众口难调吧，感觉使用Leaderf的人大家各种需求还是挺多的。

**Comment by la-chemin** [comment]
刚遇到这个问题，新建的文件无法被file查询到，除了上面的两个缓存禁用配置，额外增加了如下配置才解决
let g:Lf_UseMemoryCache = 0

**Comment by eddyli1989** [comment]
我按F5都不行

最后设置

```
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_UseMemoryCache = 0
```

找到了

之前是因为有个目录被加到.gitignore里面去了， 后面删掉了以后还是找不到，按F5也不行。

**Comment by Yggdroot** [comment]
加上--no-ignore
