### ISSUE TITLE
加载Leaderf出现Bug

### ISSUE THREAD

**Issue by ppnman** [Yggdroot/LeaderF#291]
今天我更新了Leaderf，在进入vim的时候总是报出这个信息
![image](https://user-images.githubusercontent.com/39628662/53464715-535ad080-3a86-11e9-835d-776f579c639b.png)
但是Leaderf还是可以正常使用的。这个时候的vimrc是这样的。
`Plug 'Yggdroot/LeaderF', { 'do': './install.sh' } `
目前我发现解决办法就是让Leaderf按需加载，也就是把vimrc写成
`Plug 'Yggdroot/LeaderF', { 'do': './install.sh', 'on': 'Leaderf' }`
这样一来进入vim就不会报这个信息了。
我的关于Leader的配置如下：
```
" 取消LeaderF默认快捷键
let g:Lf_ShortcutF = ''

" <leader>fi 搜索当前目录下的文件
nnoremap <leader>fi :Leaderf file<CR>

" <leader>fm 搜索最近使用过的文件
nnoremap <leader>fm :Leaderf mru<CR>

" <leader>fc 搜索历史命令
nnoremap <leader>fc :Leaderf cmdHistory<CR>

" <leader>ff 搜索当前文件中定义的函数
nnoremap <leader>ff :Leaderf function<CR>

" <leader>fw 搜索光标处的单词
noremap <leader>fw :<C-U><C-R>=printf("Leaderf! rg -e %s", expand("<cword>"))<CR>

" <leader>fr 重新打开上一次的搜索结果
noremap <leader>fr :<C-U>Leaderf! rg --recall<CR>
```

**Comment by Yggdroot** [comment]
把`let g:Lf_ShortcutF = ''`去掉。

**Comment by ppnman** [comment]
我加这句话是为了不让Leaderf使用<leader>f这个快捷键。。。还有什么其他方式禁用<leader>f这个快捷键吗。

**Comment by Yggdroot** [comment]
那就把
```
" <leader>fi 搜索当前目录下的文件
nnoremap <leader>fi :Leaderf file<CR>
```
去掉，把`let g:Lf_ShortcutF = ''`改为`let g:Lf_ShortcutF = '<leader>fi'`

**Comment by ppnman** [comment]
Wow, 聪明的办法，谢谢您！
