### ISSUE TITLE
是否可以用..来返回上级目录?

### ISSUE THREAD

**Issue by PtNan** [Yggdroot/LeaderF#292]
neovim.
平台是macOS.
在某个issue中看到了可以使用 `..` 来返回上级目录.但是我在实际使用中发现其匹配了 `.`

**Comment by Yggdroot** [comment]
能说详细点吗，不明白什么意思。
返回上级目录，可以直接命令行上敲：`cd ..`

**Comment by PtNan** [comment]
是这样的,我使用`leaderf file` 的时候,有时候可能并不直接搜索当前目录,而是希望搜索上级目录的文件.

**Comment by PtNan** [comment]
我发现我犯蠢了,应该直接`cd ..`而不是想着添加参数来返回上一级

**Comment by Yggdroot** [comment]
你也可以使用：`Leaderf file .. `或者`LeaderfFile ..`。

**Comment by PtNan** [comment]
好的 谢谢了

**Comment by zhangxuhong1024** [comment]
更常用的是在项目文件里搜索文件，我用的是如下方式，请参考：
noremap <leader>F :LeaderfFile <C-r>=Search_root()<Cr><Cr>
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"look up project root directory
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:root_marker = [".projectroot",".git"]
if !exists('g:root_marker')
    let g:root_marker = [".git"]
endif
function! Search_root()
    let l:root = fnamemodify(".", ":p:h")
    if !empty(g:root_marker)
        let root_found = 0
        let l:cur_dir = fnamemodify(l:root, ":p:h")
        let l:prev_dir = ""
        while l:cur_dir != l:prev_dir
            for tags_dir in g:root_marker
                let l:tag_path = l:cur_dir . "/" . tags_dir
                if filereadable(l:tag_path) || isdirectory(l:tag_path)
                    let root_found = 1 | break
                endif
            endfor
            if root_found
                let l:root = l:cur_dir | break
            endif
            let l:prev_dir = l:cur_dir
            let l:cur_dir = fnamemodify(l:cur_dir, ":p:h:h")
        endwhile
        return root_found ? l:root : fnamemodify(".", ":p:h")
    endif
    return l:root
endfunction

**Comment by zhangxuhong1024** [comment]
`
更常用的是在项目文件里搜索文件，我用的是如下方式，请参考：
noremap F :LeaderfFile =Search_root()
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"look up project root directory
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:root_marker = [".projectroot",".git"]
if !exists('g:root_marker')
let g:root_marker = [".git"]
endif
function! Search_root()
let l:root = fnamemodify(".", ":p:h")
if !empty(g:root_marker)
let root_found = 0
let l:cur_dir = fnamemodify(l:root, ":p:h")
let l:prev_dir = ""
while l:cur_dir != l:prev_dir
for tags_dir in g:root_marker
let l:tag_path = l:cur_dir . "/" . tags_dir
if filereadable(l:tag_path) || isdirectory(l:tag_path)
let root_found = 1 | break
endif
endfor
if root_found
let l:root = l:cur_dir | break
endif
let l:prev_dir = l:cur_dir
let l:cur_dir = fnamemodify(l:cur_dir, ":p:h:h")
endwhile
return root_found ? l:root : fnamemodify(".", ":p:h")
endif
return l:root
endfunction

`

**Comment by Yggdroot** [comment]
> 更常用的是在项目文件里搜索文件，我用的是如下方式，请参考：
> noremap F :LeaderfFile =Search_root()
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> "look up project root directory
> """"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
> let g:root_marker = [".projectroot",".git"]
> if !exists('g:root_marker')
> let g:root_marker = [".git"]
> endif
> function! Search_root()
> let l:root = fnamemodify(".", ":p:h")
> if !empty(g:root_marker)
> let root_found = 0
> let l:cur_dir = fnamemodify(l:root, ":p:h")
> let l:prev_dir = ""
> while l:cur_dir != l:prev_dir
> for tags_dir in g:root_marker
> let l:tag_path = l:cur_dir . "/" . tags_dir
> if filereadable(l:tag_path) || isdirectory(l:tag_path)
> let root_found = 1 | break
> endif
> endfor
> if root_found
> let l:root = l:cur_dir | break
> endif
> let l:prev_dir = l:cur_dir
> let l:cur_dir = fnamemodify(l:cur_dir, ":p:h:h")
> endwhile
> return root_found ? l:root : fnamemodify(".", ":p:h")
> endif
> return l:root
> endfunction

你种用法有点过时了，只要设了`g:Lf_RootMarkers`和`g:Lf_WorkingDirectoryMode`就可以了。
