### ISSUE TITLE
[feature request] let `--recall` support all leaderf cmd.

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#293]
This is useful for leaderf other cmd. ex: `file` and `line`.

**Comment by Yggdroot** [comment]
By default, `g:Lf_UseMemoryCache` is 1, the result is always cached, it has the same effect as `--recall`.

**Comment by fcying** [comment]
Is there any cmd to open the result again?
sometimes I want get the last result, not filter again.
ex:
```
:Leaderf file
//filter some files, enter. modify file.
:Leaderf --recall  //get the last result. modify another file.
```

**Comment by Yggdroot** [comment]
I got your point. Currently, there is no such a functionality.

**Comment by Yggdroot** [comment]
Done. 
Now you can use `--recall` for all command:
```
Leaderf {cmd} --recall
```

**Comment by fcying** [comment]
can it support remember last_cmd?
ex: `Leaderf last_cmd --recall` open last closed leaderf window.

**Comment by Yggdroot** [comment]
Done.
Use `Leaderf --recall`.
