### ISSUE TITLE
rg exec failed caused by a wrong parameter

### ISSUE THREAD

**Issue by stkevintan** [Yggdroot/LeaderF#294]
error: Found argument '--no-ignore-messages' which wasn't expected, or isn't valid in this context
	Did you mean --no-ignore-parent?

https://github.com/Yggdroot/LeaderF/blob/5c0e1883bc90937e08c6d7f7468bf1733caf525f/autoload/leaderf/python/leaderf/rgExpl.py#L258

**Comment by Yggdroot** [comment]
Please update your rg.

**Comment by stkevintan** [comment]
@Yggdroot sorry!
