### ISSUE TITLE
有没有头文件 源文件 的一键切换，

### ISSUE THREAD

**Issue by featheryus** [Yggdroot/LeaderF#295]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by featheryus** [comment]
其实就是搜索当前文件名去掉后缀的文件

**Comment by Yggdroot** [comment]
我一直用的https://www.vim.org/scripts/script.php?script_id=31。

**Comment by featheryus** [comment]
@Yggdroot  谢谢，这个我也有用，但是源文件，头文件目录不一致情况，并且文件没有打开在缓存里面的话，就找不到，会新建一个文件出来。
let g:alternateSearchPath = 这个设置在大项目中就很烦
还是说我用的不对，还请指教

而leaderf 感觉已经天然支持了这个功能，只差一个入口来拿结果

**Comment by Yggdroot** [comment]
a.vim是有这个问题。我设了`let g:alternateNoDefaultAlternate = 1`，这样没找到就不会创建一个空的了。
不过现在我和leaderf配合着用。

LeaderF稍微配置一下，也可以完成你想要的功能。下面是个demo：

```vim
function! Alternative()
    let name = expand("%:t:r:r:r")
    let extension = expand("%:e:e:e")
    let mapping = {"h": "cpp", "cpp": "h"}
    return name . '.' . get(mapping, extension, "")
endfunction

noremap <silent> ga :<C-U><C-R>=printf("Leaderf file --input %s", Alternative())<CR><CR>
```

**Comment by featheryus** [comment]
多谢，这个是怎么写的，有资料介绍下吗，这个好像会替换第一个. 后面的后缀，我想替换最后一个. 后面的后缀
多谢
function! Alternative()
    let name = expand("%:t:r:r:r")
    let extension = expand("%:e:e:e")
    let mapping = {"h": "cpp", "cpp": "h"}
    return name . '.' . get(mapping, extension, "")
endfunction

**Comment by featheryus** [comment]
你都实现这些功能了，为啥不加个入口，彻底替换掉a.vim ：）

**Comment by Yggdroot** [comment]
> 多谢，这个是怎么写的，有资料介绍下吗，这个好像会替换第一个. 后面的后缀，我想替换最后一个. 后面的后缀

替换最后面的，只要改两行就行了：
```vim
function! Alternative()
    let name = expand("%:t:r")
    let extension = expand("%:e")
    let mapping = {"h": "cpp", "cpp": "h"}
    return name . '.' . get(mapping, extension, "")
endfunction
```
可以参考`:h filename-modifiers`
> 你都实现这些功能了，为啥不加个入口，彻底替换掉a.vim ：）

LeaderF的目标并不是这个，也不可能面面俱到，像这样的功能稍微配置一下就可以实现，Leaderf也支持写扩展来实现更复杂的功能。

**Comment by Yggdroot** [comment]
#360 这个feature，也可以达到你的目的了。

**Comment by Freed-Wu** [comment]
如果要找a.vim 的替代品的话，我感觉 https://github.com/derekwyatt/vim-fswitch 还行
