### ISSUE TITLE
how to set  keywords color？

### ISSUE THREAD

**Issue by andyshrk** [Yggdroot/LeaderF#296]
I use Leaderf on vim Ubuntu
when i search a file or search keywords user Leaderf rg -e， the keywords display is withe。 Is there a way to give the keywords a special color？

**Comment by Yggdroot** [comment]
You can use this highlight group:
```vim
highlight Lf_hl_rgHighlight guifg=xxx guibg=xxx ctermfg=xxx ctermbg=xxx
```

**Comment by andyshrk** [comment]
thank you very much。
