### ISSUE TITLE
Feature request: please provide a way to disable g:Lf_ShortcutB / F

### ISSUE THREAD

**Issue by 9527KGG** [Yggdroot/LeaderF#297]
This a feature request.

I've my own way to call LeaderfFile and LeaderfBuffer. So I want to disable let g:Lf_ShortcutF/B.

After I set
let g:Lf_ShortcutB = ''
, when starting, vim prompts "no mapping found"

Currently, I used eg

let g:Lf_ShortcutB = \<leader\>\<leader\>\<leader\>b (, which I never use actually).

as a workaround. But I don't think it's good.

So please provide a way to disable g:Lf_ShortcutB / F

**Comment by Yggdroot** [comment]
Duplicate of #291, now you can set `let g:Lf_ShortcutB = ''` or `let g:Lf_ShortcutB = ''`  to disable the mapping.

**Comment by 9527KGG** [comment]
thanks.
