### ISSUE TITLE
Leaderf file failed

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#298]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
<img width="1280" alt="snipaste_2019-03-03_12-31-43" src="https://user-images.githubusercontent.com/8309631/53690997-61735e80-3db0-11e9-8b0d-37c1f47c31b1.png">

- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
![image](https://user-images.githubusercontent.com/8309631/53691091-0a6e8900-3db2-11e9-953f-66f9a84b1c8b.png)

- Output of `:echo g:Lf_Debug_Cmd`: 
Undefined variable
- Output of `:echo g:Lf_FilesFromCache`: 
Undefined variable
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.32
let g:Lf_HideHelp = 1
"nnoremap <A-p> :LeaderfFunction!<CR>
nnoremap <C-p> :Leaderf file<CR>
" search word under cursor, the pattern is treated as regex, and enter normal mode directly
noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg --wd-mode=ac -e %s ", expand("<cword>"))<CR>
" search word under cursor, the pattern is treated as regex,
" append the result to previous search results.
noremap <C-G> :<C-U><C-R>=printf("Leaderf! rg --wd-mode=ac --append -e %s ", expand("<cword>"))<CR>
" search visually selected text literally, don't quit LeaderF after accepting an entry
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F --wd-mode=ac --stayOpen -e %s ", leaderf#Rg#visual())<CR>
" recall last search. If the result window is closed, reopen it.
noremap go :<C-U>Leaderf! rg --wd-mode=ac --stayOpen --recall<CR>
```
### Describe your question, feature request, or bug.
When run `Leaderf file` or `Leaderf rg -e "something"`, errors as follows:
<img width="1041" alt="snipaste_2019-03-03_12-30-14" src="https://user-images.githubusercontent.com/8309631/53691074-bbc0ef00-3db1-11e9-9c56-29461281f442.png">

### Steps to reproduce
Always.

**Comment by Yggdroot** [comment]
I think this is a bug of neovim.
You can just try the following code to verify it.
```vim
:py3 import vim
:vim.command("setlocal ft=cpp")
```

**Comment by xaljer** [comment]
After input this two commands, Leaderf file is OK，but `Leaderf rg --wd-mode=ac` is not work correctly (not search under rootmark).

**Comment by Yggdroot** [comment]
> After input this two commands, Leaderf file is OK，

I'm confused, these two commands can't help you get out of the issue in theory.


> but `Leaderf rg --wd-mode=ac` is not work correctly (not search under rootmark).

Could you provide more details?

**Comment by xaljer** [comment]
> I'm confused, these two commands can't help you get out of the issue in theory.
I don't know why, but I can't reproduce this problem for now.

For the first time I want to try `--wd-mode` option, I got errors in this issue. After this problem gone, Leaderf rg can work. But I found that it still search under `pwd` path with `--wd-mode` option, but not the path specified by root marker. All conditions and environments are same as this issue.

**Comment by Yggdroot** [comment]
I can not reproduce this issue.
Does your pwd also has a root marker?

**Comment by xaljer** [comment]
`Leaderf rg` is OK using `--wd-mode <MODE>` instead of `--wd-mode=<MODE>`.

**Comment by Yggdroot** [comment]
Still can not reproduce.
In theroy, `--wd-mode <MODE>` should be the same as `--wd-mode=<MODE>`.
