### ISSUE TITLE
"Most Recently Used" shows files from other projects

### ISSUE THREAD

**Issue by Leandros** [Yggdroot/LeaderF#30]
The most recently usage panel is already great, but still lacks a little behind CtrlP.

- CtrlP shows the most recently used buffer in row 0. Meaning I can invoke it, and press enter to jump to the last buffer. Making jumping back and forth between buffers really easy and fast.
- CtrlP resets the cursor to row 0 on each invocation, LeaderF stays at some location, which might be invalidated through other jumps.
- LeaderF shows files from other "projects" / directories, often also temporary files like COMMIT_EDITMSG.

**Comment by Yggdroot** [comment]
Do you mean `LeaderfMru`?

**Comment by Leandros** [comment]
Yes.

**Comment by Yggdroot** [comment]
This issue is similar to isue #18.

**Comment by Yggdroot** [comment]
Please use `LeaderfMruCwd` instead.

**Comment by Leandros** [comment]
Awesome! Works very well! Great work.
