### ISSUE TITLE
刚用了一阵子，一些想法

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Yggdroot/LeaderF#300]
1. 呼出leaderf时，希望可以ctrl+f/b 上下翻页
2. ctrl+r是访问寄存器的键，现在跟regex切换冲突，相当于废掉了寄存器
3. ctrl+n/p 向上向下浏览，现在是ctrl+j/k
4. 能添加个source吗，相当于fzf提供的GFiles？。就是git status 列出的文件。
5. LeaderFunction是想代替tagbar吗？缺少结构显示，方法可见性显示，能和lightline整合在状态栏显示当前光标所在函数吗？
6. 正则查询非常卡，每输入个字符都卡，按理说不应该啊

**Comment by Yggdroot** [comment]
1. `<pageup>`,`<pagedown>`可以翻页，当然还可以设置成ctrl+f/b 
2. 这个不是vim命令行，也没觉得有这个必要
3. 同1，可以自己设置
4. 支持扩展
5. LeaderFunction并没想取代tagbar，只是功能有重合，对于我来说，不需要用tagbar了。方法可见性是指public，private？这个确实没有。
6. 这个可能跟电脑配置有关系，我还没怎么觉得卡过。

**Comment by FinallyFinancialFreedom** [comment]
1和3，自己设置，ok了。
2是有--cword和xmap一个映射可用，不用寄存器了。
4我还没找到办法
6机器配置mac 15寸，很强了，我再研究下
谢谢

**Comment by Yggdroot** [comment]
4. 我说一下Leaderf file的背后逻辑吧。
有个`g:Lf_UseVersionControlTool`，默认值是1
意思是： 如果当前project是被git或hg管理的，就直接使用git ls-files 或hg files。如果不是，就是用rg, 或pt，或ag 或find来生成file list。
如果`g:Lf_UseVersionControlTool`是0，即使是个git repo，也不使用git ls-files, 而是使用rg等。
所以，你什么不用设置，在git repo里，就是使用的git ls-files.

当然，LeaderF还支持写扩展，也很简单，可以使用Python或者vimL写。https://github.com/Yggdroot/LeaderF-marks 是用Python写的一个例子。https://github.com/search?p=1&q=leaderf&type=Repositories 这里有一些其他人写的扩展。https://github.com/Yggdroot/LeaderF/issues/144 这里有用vimL写扩展的方法。
