### ISSUE TITLE
Gvim crash when executing ":Leaderf"

### ISSUE THREAD

**Issue by joeyling** [Yggdroot/LeaderF#303]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: gvim 8.1
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python36.dll
- Output of `:py print(sys.version)`: 2.7.14 32bit
- Output of `:py3 print(sys.version)`: same crash when executing this command in Gvim
- Output of `:echo g:Lf_Debug_Cmd`: undefined variable invalid expression
- Output of `:echo g:Lf_FilesFromCache`: same as above
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: Nothing

### Describe your question, feature request, or bug.
execute any ":Leaderf -[*]" command, Gvim crash

**Comment by Yggdroot** [comment]
Is your python3 32bit or 64bit?
I think it does not match with gvim.

**Comment by joeyling** [comment]
> Is your python3 32bit or 64bit?
> I think it does not match with gvim.

32bit

**Comment by joeyling** [comment]
I just run "vim --version" in `cmd` window and it shows "-python" and "-python3". Do you think that's the problem?

**Comment by Yggdroot** [comment]
> I just run "vim --version" in `cmd` window and it shows "-python" and "-python3". Do you think that's the problem?

No. 

This issue is not related to LeaderF, because `py3 print(sys.version)` also crashes.
You can turn to google to find the solution.

**Comment by joeyling** [comment]
> > I just run "vim --version" in `cmd` window and it shows "-python" and "-python3". Do you think that's the problem?
> 
> No.
> 
> This issue is not related to LeaderF, because `py3 print(sys.version)` also crashes.
> You can turn to google to find the solution.

What I mean is "-python" and "-python3"  means the givm I installed doesn't support python, right? Do you think if I install a python-support version Gvim, it can fix the problem?

**Comment by joeyling** [comment]
> > I just run "vim --version" in `cmd` window and it shows "-python" and "-python3". Do you think that's the problem?
> 
> No.
> 
> This issue is not related to LeaderF, because `py3 print(sys.version)` also crashes.
> You can turn to google to find the solution.

I have googled this problem, none of the answer can solve it. But I find this,

> Make sure you have installed VIM > 7.3 with Python support. Again, run vim --version to verify this. If you want to check the specific version of Python used in VIM, run :python import sys; print(sys.version) from within VIM:

on https://realpython.com/vim-and-python-a-match-made-in-heaven/#windows

So, does it mean that the Gvim I installed doesn't support python and I should install a python-support version Gvim?

**Comment by Yggdroot** [comment]
> What I mean is "-python" and "-python3" means the givm I installed doesn't support python, right? Do you think if I install a python-support version Gvim, it can fix the problem?

Terminal vim is not the same as gvim. You said 
```
Output of :echo has("python"): 1
Output of :echo has("python3"): 1
```
, so it must be "+python" and "+python3" for gvim, your gvim has already supported python.

**Comment by Yggdroot** [comment]
You can download vim from [here](https://github.com/vim/vim-win32-installer/releases), and you can also get the corresponding python there.

Please reinstall it.

**Comment by joeyling** [comment]
> > What I mean is "-python" and "-python3" means the givm I installed doesn't support python, right? Do you think if I install a python-support version Gvim, it can fix the problem?
> 
> Terminal vim is not the same as gvim. You said
> 
> ```
> Output of :echo has("python"): 1
> Output of :echo has("python3"): 1
> ```
> , so it must be "+python" and "+python3" for gvim, your gvim has already supported python.

I have uninstalled python2 and python3 both. Why `echo has("python3")` still get 1

**Comment by joeyling** [comment]
> You can download vim from [here](https://github.com/vim/vim-win32-installer/releases), and you can also get the corresponding python there.
> 
> Please reinstall it.

Yes, I have reinstalled it from here. Still doesn't work!

**Comment by joeyling** [comment]
> > > What I mean is "-python" and "-python3" means the givm I installed doesn't support python, right? Do you think if I install a python-support version Gvim, it can fix the problem?
> > 
> > 
> > Terminal vim is not the same as gvim. You said
> > ```
> > Output of :echo has("python"): 1
> > Output of :echo has("python3"): 1
> > ```
> > , so it must be "+python" and "+python3" for gvim, your gvim has already supported python.
> 
> I have uninstalled python2 and python3 both. Why `echo has("python3")` still get 1

I reinstalled Gvim and execute `echo has("python3")` , still get 1! Does Gvim originally support python3?

**Comment by Yggdroot** [comment]
`echo has("python3")` is 1 means everything works well.
