### ISSUE TITLE
‘String cannot contain newlines’ error when 'F5' refresh

### ISSUE THREAD

**Issue by aj3423** [Yggdroot/LeaderF#304]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.4.0-263-g969cc559
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: No 'python' provider found. Run ":checkhealth provider"
- Output of `:py3 print(sys.version)`: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]
- Output of `:echo g:Lf_Debug_Cmd`: Empty
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
Plug 'Yggdroot/LeaderF', { 'do': '.\install.bat' }
let g:Lf_DefaultMode='Regex'
let g:Lf_ShortcutF='<C-P>'
nnoremap <C-t> :LeaderfTag<CR>
let g:Lf_RootMarkers = ['.git', '.aj', '.svn']
let g:Lf_WildIgnore = {
	\ 'dir': ['.svn','.git','debug', 'release'],
	\ 'file': ['*.aj', '*.pb.*', '*.so']
	\}

### Describe your question, feature request, or bug.
Error occur when use 'F5' to refresh
### Steps to reproduce
1. create file 'e:\test\test.go'
2. double click to open it
3. open list by `:LeaderfFile`
4. press 'F5' to refresh,  error occurs
### Actual behaviour
![image](https://user-images.githubusercontent.com/4710875/54071998-a7985880-42af-11e9-81c7-3ce84ca59faa.png)

### Expected behaviour
Refresh cache without error

**Comment by Yggdroot** [comment]
fixed.
