### ISSUE TITLE
[feature request] Allow opening file with line number

### ISSUE THREAD

**Issue by TienDo1011** [Yggdroot/LeaderF#305]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.3.4
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.2 (default, Mar  4 2019, 07:25:03)
[Clang 10.0.0 (clang-1000.11.45.5)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Should allow to open a file with line number in Neovim:
For example: `README.md:25`
### Actual behaviour
The search for it just returns empty
### Expected behaviour
The search for it should still return the file, and press enter on the file will open it with correct line number.

**Comment by Yggdroot** [comment]
Sorry, I don't plan to support this feature.

**Comment by TienDo1011** [comment]
Can I know the reason why?

**Comment by Yggdroot** [comment]
The feature can not save the keystrokes, e.g., the key sequence of the feature is: `README.md:25<CR>`, you can achieve the same behavior by typing: `README.md<CR>25G`. Also, all the inputs are considered to be a fuzzy pattern, including the character `:`, to implement your feature, `:` has to be treated as a **special** character. More working, little improving. So I don't plan to support this feature.
