### ISSUE TITLE
Error when executing ":Leaderf tag", ":Leaderf function", ":Leaderf rg"

### ISSUE THREAD

**Issue by joeyling** [Yggdroot/LeaderF#306]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): python27dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.14
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Expected behaviour

:Leaderf tag
`Error: list.remove(x): x not in the list`

:Leaderf function
`Error: 处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 675, in start
    the_args.start(arguments, *args, **kwargs)
  File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 637, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 1214, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 80, in getContent
    result = self._formatResult(*result)
  File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 148, in _formatResult
    output = [line.split('\t') for line in result if line is not None]
  File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\asyncExecutor.py", line 118, in __iter__
    raise Exception(lfBytes2Str(err, self._encoding))
Exception: 'ctags' is not recognized as an internal or external command,^M
operable program or batch file.^M`

:Leaderf rg
`Error: 'rg' is not recognized as an internal or external command

ps: why can't I upload picture?

**Comment by Yggdroot** [comment]
> :Leaderf tag
> Error: list.remove(x): x not in the list

错误信息太少，不知道原因。

> :Leaderf function
> Error: 处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误: 第 1 行: Traceback (most recent call last): File "<string>", line 1, in <module> File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 675, in start the_args.start(arguments, *args, **kwargs) File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 637, in _default_action manager.startExplorer(win_pos[2:], *args, **kwargs) File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 1214, in startExplorer content = self._getExplorer().getContent(*args, **kwargs) File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 80, in getContent result = self._formatResult(*result) File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\functionExpl.py", line 148, in _formatResult output = [line.split('\t') for line in result if line is not None] File "C:\Software\Vim\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\asyncExecutor.py", line 118, in __iter__ raise Exception(lfBytes2Str(err, self._encoding)) Exception: 'ctags' is not recognized as an internal or external command,^M operable program or batch file.^M
> 

原因是“'ctags' is not recognized as an internal or external command,^M operable program or batch file.” 不是写的很清楚吗。

> :Leaderf rg
> `Error: 'rg' is not recognized as an internal or external command
> 

原因同上。

**Comment by joeyling** [comment]
> 'ctags' is not recognized as

请问如何解决呢？

**Comment by Yggdroot** [comment]
原因是你电脑上没有装[ctags](https://github.com/universal-ctags/ctags-win32/releases)和[rg](https://github.com/BurntSushi/ripgrep/releases)。

**Comment by joeyling** [comment]
> 原因是你电脑上没有装[ctags](https://github.com/universal-ctags/ctags-win32/releases)和[rg](https://github.com/BurntSushi/ripgrep/releases)。

非常感谢！我是小白。你给的链接好像是要自己编译的？有没有可以直接安装的？

**Comment by Yggdroot** [comment]
你仔细看看链接里面，有编译好的。
