### ISSUE TITLE
报告个正则选择的bug

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Yggdroot/LeaderF#307]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.34
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_RecurseSubmodules=1 只有此行配置相关。
### Describe your question, feature request, or bug.
崩溃
### Steps to reproduce
在一个源文件里，执行:Leaderf bufTag
然后，CTRL+R切换到regex模式，fuzzy模式并没有问题
然后，输入一些字母，筛选几个结果出来，CTRL+K向上浏览，到列表第一个结果，继续CTRL+K向上，就崩溃了。
### Expected behaviour
在解决问题的基础上，能循环浏览吗，就是定位到第一条结果后，再CTRL+K就到最后一条结果。

**Comment by Yggdroot** [comment]
复现不了。
崩溃是指什么？vim crash？
有错误信息吗？

**Comment by FinallyFinancialFreedom** [comment]
刚试了一把，我描述有误。
step1：在一个源文件里，执行:Leaderf bufTag，默认fuzzy模式；
step2：然后，输入一些字母，筛选几个结果出来；
step3：然后，CTRL+R切换到regex模式，这时结果列表会自动进一步精确匹配。
step4：CTRL+K向上浏览，到列表第一个结果，继续CTRL+K向上，就报错。
![image](https://user-images.githubusercontent.com/2133400/54343791-88684500-467a-11e9-8fef-01d97b9751ad.png)

**Comment by Yggdroot** [comment]
嗯，我复现了。
报issue时最好把信息提供全，一个很重要的信息你就没有提供，还是我看代码才发现的。那就是你的相关配置不可能只是`let g:Lf_RecurseSubmodules=1`。或者执行命令时有`--reverse`,  不然不能复现。

**Comment by FinallyFinancialFreedom** [comment]
不好意思贴错配置了。
let g:Lf_ReverseOrder = 1 这行相关。
