### ISSUE TITLE
无法设置let g:Lf_CommandMap = {'<ESC>': ['<A-x>']}

### ISSUE THREAD

**Issue by joeyling** [Yggdroot/LeaderF#308]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Expected behaviour

进入Leaderf，按<A-x>，不能退出，而是输入一个奇怪的字符

**Comment by Yggdroot** [comment]
不支持Alt，只支持Ctrl
