### ISSUE TITLE
不知道是个bug还是设计的就不能这么用，rg -e使用问题。

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Yggdroot/LeaderF#309]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.3.4
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`noremap <C-G> :<C-U><C-R>=printf("Leaderf rg -e %s ", expand("<cword>"))<CR><CR>`
`let g:Lf_ReverseOrder = 1`

### Describe your question, feature request, or bug.
首先按readme的配置`noremap <C-G> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>`不太好用,所以我又在后面加了个`<CR>`.另外注意我自己的配置没有！，不过这个关系不大，因为有！后再按i进insert模式问题也能复现。
就是触发上述功能后，它会列出相关备选项让选，很快。但其实我还想再过滤一些内容，所以会再输入些字母，这里有3个问题:
1. 首先能把cword值填充到输入位置吗，省的再打字了，`Leaderf rg --cword`就可以这样，但是它不支持-e选项；`Leaderf rg --cword --regexMode` 基本满足需求但还是比较慢，而且有更大问题，它不能按esc退出leaderf，而且选择选项后回车不能跳转过去。但是有！的配置是可以跳转的。
2. 我输入完一些字母后，倒是在备选项里进一步选择了，但是和上述问题一样，不能跳转。如果配置里有！就可以跳转。
3. 第二条我输入的那些字母，不能删除，就是只能输入更多字母，没法修改已经输入过的。另外也是无法esc退出leaderf，只能ctrl+c退出。

**Comment by Yggdroot** [comment]
> Configurations related to LeaderF in vimrc:

这个是跟LeaderF相关的配置都列出来，而不是你认为的跟issue相关的配置。

> 首先能把cword值填充到输入位置吗，省的再打字了，Leaderf rg --cword就可以这样，但是它不支持-e选项；Leaderf rg --cword --regexMode 基本满足需求但还是比较慢，而且有更大问题，它不能按esc退出leaderf，而且选择选项后回车不能跳转过去。但是有！的配置是可以跳转的。

不太明白“但是它不支持-e选项” 是什么意思？


你说的所有问题都复现不了。

> 不能删除

你是按得什么键删除的？我也复现不了。

上面那么多问题，我怀疑你用的终端有问题。

**Comment by FinallyFinancialFreedom** [comment]
头疼，这个问题先关了吧，一般使用是无法复现这个问题的。我用iterm最新终端。
我刚才试了半天，发现是，我配了`nmap <silent> <leader>s :source $MYVIMRC<CR>`这行用于加载配置变更，当我开buffer A，唤起过leaderf，然后在buffer B改配置，改什么无所谓，然后在buffer A加载配置，再用几次不同源的leaderf，就有很大概率复现这个问题。不仅限于leaderf rg。leaderf file, buftag都有复现，但没找到规律。
这种使用场景太少，不研究了。
