### ISSUE TITLE
关于leaderf窗口的高度显示配置，有什么好方法吗

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Yggdroot/LeaderF#310]
我配置的高度是0.35, `let g:Lf_WindowHeight = 0.35`，当备选项足够多时，可以。
当我用rg时，假设备选项有2个，leaderf实际展示了2行高度的窗口，这正常，但是我的备选项都足够长，默认折行显示很必要，所以实际需要用4行显示，这视觉观感和实际使用选择就比较别扭。

**Comment by Yggdroot** [comment]
感觉你的需求很不明确，`但是我的备选项都足够长，默认折行显示很必要`， 你又说必要，又说别扭，这个怎么搞？

**Comment by FinallyFinancialFreedom** [comment]
重点不在折不折行，而在于折行后显示的窗口过小。
希望是在折行的基础上显示尽可能多的内容。比如窗口高度的设置是绝对高度，不会根据备选项的多少而动态调整高度；比如根据实际显示行数（折行算多行，而不是一行）而动态调整高度，都行啊

**Comment by Yggdroot** [comment]
明白了。

**Comment by Yggdroot** [comment]
改好了，请试一下。

**Comment by FinallyFinancialFreedom** [comment]
试了，完美，谢谢
