### ISSUE TITLE
请问会不会增加悬浮窗口的支持呢？

### ISSUE THREAD

**Issue by 0xff91** [Yggdroot/LeaderF#311]
你好，neovim现在支持悬浮窗口了，我想leaderf配合悬浮窗口的话应该特别棒，不知道后面会不会增加对悬浮窗口的支持呢？

**Comment by Yggdroot** [comment]
等有空了也许会支持吧。

**Comment by 0xff91** [comment]
> 等有空了也许会支持吧。

好的，非常感谢

**Comment by Yggdroot** [comment]
Close as there is a duplicate issue #371  described in English.
