### ISSUE TITLE
gtags：'gbk' codec can't decode byte

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#312]
- vim or neovim? 
    - [ x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.3 (default, Apr 17 2019, 05:49:33)  [GCC 7.4.0 32 bit]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

源码：
https://github.com/reactos/reactos

运行：
 > Leaderf gtags --update

会出现：
>'gbk' codec can't decode byte 0x94 in position 96: illegal multibyte sequence

跟踪了下：
https://github.com/Yggdroot/LeaderF/blob/b9cc519e8db6388f9244371602887124da20a4cc/autoload/leaderf/python/leaderf/gtagsExpl.py#L738

会抛出异常，在：
https://github.com/Yggdroot/LeaderF/blob/b9cc519e8db6388f9244371602887124da20a4cc/autoload/leaderf/python/leaderf/gtagsExpl.py#L737

加上`encoding="utf-8"`会正常，打印的error是：
 > Warning: 'E:\Downloads\reactos-master\media\themes\lunar.msstyles\bitmaps\REACTOS_STARTBUTTON — kopia.bmp' not found. ignored.

**Comment by Yggdroot** [comment]
Reproduced, trying to fix it.

**Comment by Yggdroot** [comment]
这个问题是因为gtags不支持utf-8编码作为输入，算是gtags的bug吧，目前没办法解决，只能绕开了。直接用gtags命令，不用`cmd | gtags -f-`。

**Comment by Yggdroot** [comment]
使`g:Lf_GtagsSource`为0（default）， 就是直接使用gtags命令，就不会报错了。`g:Lf_GtagsSource`值为1或者2就是使用比如`git ls-files | gtags -f-`，由于前面命令的输出编码是utf-8，gtags不支持，就会报错。

**Comment by bstaint** [comment]
哦，感谢
