### ISSUE TITLE
gtags: not working

### ISSUE THREAD

**Issue by x1314aq** [Yggdroot/LeaderF#315]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
```
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
```
3.7.3 (default, Mar 27 2019, 09:23:15)
[Clang 10.0.1 (clang-1001.0.46.3)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
```
Request from non-main thread.
Requests from different threads should be wrapped with nvim.async_call(cb, ...)
  File "/Users/sapphire/.nvim/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 763, in _executeCmd
    print("gtags generated successfully!")
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 182, in write
    self.redirect_handler(data)
  File "/usr/local/lib/python3.7/site-packages/pynvim/plugin/script_host.py", line 75, in <lambda>
    sys.stdout = RedirectStream(lambda data: nvim.out_write(data))
  File "/usr/local/lib/python3.7/site-packages/pynvim/api/nvim.py", line 393, in out_write
    return self.request('nvim_out_write', msg, **kwargs)
```
### Steps to reproduce
type `:Leaderf gtags --update` under the project root.

**Comment by Yggdroot** [comment]
Did not test on neovim.

**Comment by x1314aq** [comment]
only vim works?

**Comment by Yggdroot** [comment]
NO, also will add neovim support. Didn't realize that neovim is not compatible with vim here.

**Comment by x1314aq** [comment]
okay, thx

**Comment by Yggdroot** [comment]
Fixed.
