### ISSUE TITLE
vim no response

### ISSUE THREAD

**Issue by jerrywang1981** [Yggdroot/LeaderF#316]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.0-632-g9d77a0768
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/local/opt/gettext/include -I/usr/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: not found
- Output of `:py3 print(sys.version)`: 
3.7.3 (default, Apr 11, 2019 07:24:24)
[Clang 10.0.1]
- Output of `:echo g:Lf_Debug_Cmd`: 
undefined variable
- Output of `:echo g:Lf_FilesFromCache`: 
undefined variable
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShortcutF = '<c-p>'
let g:Lf_CommandMap = {'<Tab>': ['<ESC>']}
let g:Lf_DefaultMode = 'NameOnly'
let g:Lf_WindowHeight = 0.3
let g:Lf_WorkingDirectoryMode = 'Ac'

### Describe your question, feature request, or bug.

```
When :Leaderf rg  to search something, sometimes no response. this time I wanted to search for .xml,  I input (trying to input \.xml)
\.
and then no response
```

### Steps to reproduce
not sure if you can have same issue.

**Comment by jerrywang1981** [comment]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/8133242/56894416-60ad2f00-6ab8-11e9-8d21-c7421cb7ba62.png">

**Comment by Yggdroot** [comment]
It is fuzzy mode, you don't have to escape the dot, just input `.xml` is OK.

**Comment by jerrywang1981** [comment]
that did the trick. hope this can help you debug

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/8133242/56902627-3b76eb80-6acd-11e9-8117-ade2d0460213.png">

**Comment by Yggdroot** [comment]
How to reproduce the error?

**Comment by Yggdroot** [comment]
This issue should be the same reason as #318 , Could you please provide the file `src/assets/img/Avatar-White-Wat...`, so that I can reproduce it ?
