### ISSUE TITLE
"gtags: unrecognized option '--skip-symlink'" when "Leaderf gtags --update"

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#319]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
0.40
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows (Windows 7)
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Steps to reproduce
run `Leaderf gtags --update`, directory is created in cache path, but no tag file generated,
`:message` shows: `gtags: unrecognized option '--skip-symlink'`.
Always.

**Comment by Yggdroot** [comment]
What is the version of your gtags? Maybe it's too old.

**Comment by xaljer** [comment]
yes, version 6.6.2 has issue, and 6.6.3 is OK.
