### ISSUE TITLE
[Feature request] Add highlight & blink on matched item in buffer

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#320]
In Leaderf rg/gtags, etc. , matched item is highlighted in Leaderf window, but isn't in current buffer.
I think it's more convenient if Leaderf can highlight the matched item in current buffer, especially when i preview many results.
I can use below way to achieve this:
`nnoremap <Leader>fw :match Cursor '<C-R><C-W>'<CR> :<C-U><C-R>=printf("Leaderf! rg --wd-mode Ac -w --match-path -e %s ", expand("<cword>"))<CR><CR>`
and behavior of `:match` is exactly what i want. But the only issue is i can't spec the priority of `:match`, i want this highlight has lower priority. (Maybe i am wrong, I'm not familiar with vim commands, but if I'm right, I have to use ` matchadd()`, more complex. So, I think maybe Leaderf can support this by itself, and do better.)

In addition, I saw Emacs (I don't know what plugin) can blink the line when jump to a symbol. I think it's also a good way to get the position easier after jump.

**Comment by Yggdroot** [comment]
LeaderF has already been able to blink the line when jump to a symbol.

**Comment by xaljer** [comment]
I don't see blink effect on `Leaderf gtags -d`?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/cc8278640a3e9fc863c298ab9d3f152fce9bc02f/autoload/leaderf/python/leaderf/gtagsExpl.py#L852

Replace the 20m with 200m, to see if it is the effect you want.

**Comment by xaljer** [comment]
no，I try to adjust that value, but I don't get what i want. I don't find a gif to show the effect.

**Comment by Yggdroot** [comment]
![aaa](https://user-images.githubusercontent.com/2705841/57744326-56677380-76fb-11e9-8f4e-e56cd1b5ecf8.gif)

Is this what you want?

**Comment by xaljer** [comment]
Yes, it like virtual bell?

**Comment by Yggdroot** [comment]
This is the effect of sleeping 200ms.
