### ISSUE TITLE
line number out range

### ISSUE THREAD

**Issue by 0xff91** [Yggdroot/LeaderF#321]
- vim or neovim? 
    - [ ] vim
    - [X] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.0-647-gf86f0a8bc
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.7.3 (default, Mar 26 2019, 21:43:19)
[GCC 8.2.1 20181127]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```shell
nnoremap <M-f> :LeaderfFile<CR>
nnoremap <M-t> :LeaderfBufTag<CR>
nnoremap <M-T> :LeaderfBufTagAll<CR>
nnoremap <M-o> :LeaderfBufferAll<CR>
nnoremap <M-s> :LeaderfLine<CR>
nnoremap <M-S> :LeaderfLineAll<CR>
nnoremap <M-r> :LeaderfMru<CR>                                
```
### Describe your question, feature request, or bug.
line number out range
### Steps to reproduce
打开文件，然后使用leaderfLineAll就出现这个问题了，使用LeaderfLine则没有问题，具体错误提示如下
```shell
Error detected while processing function leaderf#Line#startExpl[4]..leaderf#LfPy[1]..provider#python3#Call:                                                                                                                          
line   18:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/forever/.cache/plugins/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1352, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/home/forever/.cache/plugins/LeaderF/autoload/leaderf/python/leaderf/lineExpl.py", line 29, in getContent
    vim.current.buffer = cur_buffer
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 520, in buffer
    return self._session.request('nvim_set_current_buf', buffer)
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.nvim.NvimError: b'Vim(return):Line number outside range'
Error detected while processing function leaderf#Line#startExpl:
line    4:
E171: Missing :endif
```

**Comment by 0xff91** [comment]
提示第四行少了endif？

**Comment by Yggdroot** [comment]
这应该是neovim的bug，我用的nvim 0.3.4， Python3.7.2无法复现。

**Comment by Yggdroot** [comment]
因为报错的地方代码很简单，如下：
https://github.com/Yggdroot/LeaderF/blob/cc8278640a3e9fc863c298ab9d3f152fce9bc02f/autoload/leaderf/python/leaderf/lineExpl.py#L19-L32

vim上不会报错，我用的nvim 0.3.4， Python3.7.2也不会报错，所以我怀疑是neovim引入了新的bug。

你可以试试下面方式会不会复现：
1. `py3 import vim`
2. `py3 cur_buffer = vim.current.buffer`
3. `py3 vim.current.buffer = cur_buffer`
