### ISSUE TITLE
Windows install issue with leaderf

### ISSUE THREAD

**Issue by jdhao** [Yggdroot/LeaderF#322]
In the install guide about installing leaderF on windows, these is this sentence:

> First, make sure py -2 and/or py -3 commands are available.

I am not clear what this means.  Why not simply detect which python the user is using and use `python`?

I am using [Anaconda for Windows](https://www.anaconda.com/distribution/#download-section) and I do not know how I am supposed to do to make `py -3` command available.  Each time I update leaderF, I got the warning message:

> 'py' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Yggdroot** [comment]
If you install python from https://www.python.org/downloads/windows/ , `py` command should be available.

**Comment by Yggdroot** [comment]
[This ](https://docs.python.org/3/using/windows.html#launcher) is what `py` is.

**Comment by jdhao** [comment]
Anaconda is a standard python distribution which is very popular. How do we use python provided by Anaconda instead of the Python distribution from official Python website？

**Comment by Yggdroot** [comment]
I think if you install another version of python from  https://www.python.org/downloads/windows/, `py` command should also be installed and `py` can also launch python installed by Anaconda.

**Comment by jdhao** [comment]
Thanks for your suggestion. But I would rather keep just more python distribution instead of two to simply install a plugin. Maybe I should just use this plugin without the c extensions.
