### ISSUE TITLE
Freezes on neovim due to recent commit

### ISSUE THREAD

**Issue by svermeulen** [Yggdroot/LeaderF#323]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.0-442-gedc3c4be5
Build type: Debug
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector
-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/svermeulen/Projects/Ave/neovim/build/config -I/Users/svermeulen/Projects/Ave/neovim/src -I/Users/svermeulen/Projects/Ave/neovim/.deps/usr/include -I/Library/Frameworks/
Mono.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Users/svermeulen/Projects/Ave/neovim/build/src/nvim/auto -I/Users/svermeulen/Projects/Ave/neovim/build/include
Compiled by svermeulen@Stevens-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

- Output of `:echo has("python")`:  1
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`:  2.7.10 (default, Feb 22 2019, 21:17:52) 
- Output of `:py3 print(sys.version)`: 3.7.2 (default, Feb 12 2019, 08:15:36) 
- Output of `:echo g:Lf_Debug_Cmd`:  `rg --no-messages --files --color never  -g '!.svn' -g '!.git' -g '!.hg' -g '!*.meta' -g '!*.lua' -L --hidden  `
- Output of `:echo g:Lf_FilesFromCache`:  1
- Operating system: 
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```
    let g:Lf_UseVersionControlTool = 0
    let g:Lf_ShowHidden = 1
    let g:Lf_FollowLinks = 1
    let g:Lf_CommandMap = { 
            \ '<C-K>': ['<C-O>'], 
            \ '<DOWN>': ['<C-J>'], 
            \ '<UP>': ['<C-K>'], 
            \ '<C-F>': ['<C-N>'], 
            \ '<C-U>': ['<C-W>', '<c-u>'], 
            \ '<C-R>': [], 
            \ '<F5>': ['<C-R>'],
            \ '<home>': ['<c-f>'], 
            \ '<left>': ['<c-h>'], 
            \ '<right>': ['<c-l>'], 
            \ '<tab>': ['<c-d>']  
            \ }

    if has('win32')
        let g:Lf_CommandMap['<C-J>'] = ['<C-F14>']
        let g:Lf_CommandMap['<C-H>'] = ['<C-F7>']
        let g:Lf_CommandMap['<end>'] = ['<s-f3>']
    else
        let g:Lf_CommandMap['<C-J>'] = ['<D-A>']
        let g:Lf_CommandMap['<C-H>'] = ['<D-M>']
        let g:Lf_CommandMap['<end>'] = ['<C-;>']
    endif

    let g:Lf_WildIgnore = {
        \ 'dir': ['.svn', '.git', '.hg'],
        \ 'file': ['*.meta', '*.lua']
        \}
```

### Describe your question, feature request, or bug.

Freezes after typing a few characters after executing `Leaderf file --reverse DIR`

### Steps to reproduce

Execute `Leaderf file --reverse Dir` then type 2 characters

### Actual behaviour

Freezes

### Expected behaviour

Should not freeze

I found this started happening with commit 51bd00b.  If I go to the one before that it works again

**Comment by Yggdroot** [comment]
Is it terminal vim or macvim?

**Comment by Yggdroot** [comment]
Got it. It is neovim, so it's terminal vim.

**Comment by svermeulen** [comment]
[neovim-qt](https://github.com/equalsraf/neovim-qt)

**Comment by Yggdroot** [comment]
Does this issue happen on terminal neovim?

**Comment by svermeulen** [comment]
I tried upgrading neovim to master (I've been building it myself) and the problem disappeared.  So I guess it was a neovim issue.
