### ISSUE TITLE
linux vim LeaderF_Mru 里的自动命令会导致gt gT切换Tab很慢

### ISSUE THREAD

**Issue by yehuohan** [Yggdroot/LeaderF#324]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
我这边不会感觉到慢，你怎么确定是LeaderF_Mru 里的自动命令导致的？

**Comment by yehuohan** [comment]
我把plugin/leaderf.vim中LeaderF_Mru中的autocmd注释掉，Tab切换就正常了：

```
augroup LeaderF_Mru
    "autocmd BufAdd,BufEnter,BufWritePost * call lfMru#record(expand('<afile>:p')) |
    "            \ call lfMru#recordBuffer(expand('<abuf>'))
augroup END
```

在.vimrc中加以下代码，Tab切抱也正常了：
```
    Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
    augroup PluginLeaderF
        autocmd!
        autocmd VimEnter * autocmd! LeaderF_Mru
    augroup END
```

**Comment by yehuohan** [comment]
刚才又测试了下，又正常了，也是醉了。。。。之前测重启测了好几次也不见好。。。
我先close issue了，麻烦了[捂脸笑]
