### ISSUE TITLE
项目根目录以外使用'gtags --path-style through'后无法正常跳转

### ISSUE THREAD

**Issue by Howlaind** [Yggdroot/LeaderF#325]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: v0.3.5
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): -
- Output of `:echo &pythonthreedll`(only vim, not neovim): -
- Output of `:py print(sys.version)`: -
- Output of `:py3 print(sys.version)`: 3.7.3 (default, Mar 27 2019, 09:23:15)
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`let g:Lf_WorkingDirectoryMode = 'A'`
### Describe your question, feature request, or bug.
由于设置了 `Lf_WorkingDirectoryMode` 为 `A`，所以 LeaderF 会以当前文件为基准，定位项目根目录。

因为 `:Leaderf file`、`:Leaderf rg` 等子命令都是相对于项目根目录显示路径的，为了输出统一，在使用 `:Leaderf gtags` 命令的时候加了 `--path-style through` 参数。

然而在当前目录（启动 nvim 的目录）并非为项目根目录时，`gtags --path-style through` 的结果**无法正确跳转**到「项目根目录+相对路径」的对应文件，而是在「当前目录+相对路径」新建了一个文件。

能不能加入判断，当使用了 `--path-style through` 参数时，相对项目根目录进行跳转。或者像`rg` 一样，直接在项目根目录调用 `global`，然后跳转也都在根目录跳转呢？

**Comment by Yggdroot** [comment]
确实有问题，我看看。

**Comment by Yggdroot** [comment]
改好了，你试一下。

**Comment by Howlaind** [comment]
当前目录是项目内的子目录时，可以跳转了。
但如果当前目录在项目之外，运行 `:Leaderf gtags --path-style through -d foo` 之后就报错。跳转目标目录为空（''）。

MacOS下报错
`FileNotFoundError: [Errno 2] No such file or directory: ''`

Windows 10下报错
`OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ''`

**Comment by Howlaind** [comment]
试着把 `RgExplManager` 里的 `startExplorer` 拿到 `GtagsExplManager`，加个`--path-style through` 的判断，改一下 `super` 的参数和 `_nearestAncestor` 的调用，就没有报错，并且可以正确跳转了。

对 Python 不是很熟，生成 `GTAGS` 等文件时候的路径判断没怎么看明白。按说直接使用生成 `GTAGS` 的路径是最合理的。

**Comment by Yggdroot** [comment]
不太明白你的使用场景，“当前目录在项目之外”，是说有两个项目？每个都创建了gtags？能具体解释一下吗？

**Comment by Howlaind** [comment]
「当前目录」是启动 vim 的目录。vim 里 `:pwd` 应该就能返回。

```
home
└── project01
    ├── .git
    │   └── ...(略)
    ├── a.c
    ├── a.h
    ├── b.c
    └── b.h
```

好比我的项目在 `home/project01` 目录下，我在 `home` 位置 `nvim project01/a.c` 访问 `home/project01` 下的文件就是「当前目录在项目之外」。
```
$ pwd
/Users/user01/home

$ ls
project01

$ ls -a project01
.git    a.c    a.h     b.c    b.h

$ nvim project01/a.c

:Leaderf gtags --update
gtags generated successfully!

:!ls ~/.LfCache/gtags/
%Users%user01%home%project01

:Leaderf gtags --path-style through -d foo
FileNotFoundError: [Errno 2] No such file or directory: ''
```

直接运行 GUI 然后打开文件也会出现这种情况。

在 Windows 下鼠标打开 nvim-qt.exe，`:pwd` 返回 `C:\Neovim\bin`，就是 nvim-qt.exe 所在的路径。

再用 nvim-qt 打开项目中的文件，那 `:pwd` 返回的路径也就在项目路径之外了。
（虽然我平时也不用 GUI，但一般用GUI的人大概不会注意是从哪个路径运行 vim 的吧）

我个人的使用习惯是打开终端，直接 `nvim`，然后用 `'` 跳转到 Mark 过的项目文件里。所以 `:pwd` 返回的当前路径一般和项目路径没什么太大关系。

**Comment by Yggdroot** [comment]
我一般使用vim是直接到某个project根目录，然后再打开vim。
在dev branch你再试一下。

**Comment by Howlaind** [comment]
非常感谢。现在正常了。这方面应该没什么问题。close issue

不过似乎 gtags 与 file 和 rg 的逻辑不一样，是不会看 `g:Lf_WorkingDirectoryMode` 设置的。并且与 wd-mode 的任何一种模式都不完全一样。

模式对比如下：
```
gtags     | 文件祖先 -> 当前目录(pwd)祖先 -> 当前目录(pwd)

wd-mode c | 当前目录(pwd)
wd-mode a | 当前目录(pwd)祖先 -> 当前目录(pwd)
wd-mode A | 文件祖先 -> 当前目录(pwd)
wd-mode f | 文件目录
wd-mode F | 文件目录 或 当前目录(pwd)
```
这在有些时候可能会使 gtags 的结果不符合预期。

好比刚刚的目录结构，将 `b.c` `b.h` 放到 一个子目录 `sub` 下，
`g:Lf_WorkingDirectoryMode` 为 `c`（默认值），
`project01` 里有 `.git`
`sub` 目录下没有 `g:Lf_RootMarkers` 中匹配的文件，

这时在子目录 `sub` 下用 vim 打开 `b.c`，
file 和 rg 的工作目录为「当前目录(pwd)」`home/project01/sub`，
gtags 的工作目录为「文件祖先」 `home/project01`。
如下：

```
home$ pwd
/Users/user01/home

home$ tree -a
home
└── project01
    ├── .git
    │   └── ...(略)
    ├── a.c
    ├── a.h
    └── sub
        ├── b.c
        └── b.h

home$ cd sub

sub$ nvim b.c

:pwd
/Users/user01/home/project01/sub

:Leaderf gtags --remove

:echo g:Lf_WorkingDirectoryMode
c

:LeaderfFile
LeaderF ► File ► FullPath ► /Users/user01/home/project01/sub

:Leaderf gtags --update
gtags generated successfully!

:!ls ~/.LfCache/gtags/
%Users%user01%home%project01
```

虽然一般人应该不会去做这种操作，但这种结果不一致总觉得有些不大对。

要提个新 issue 等以后有空处理一下吗？还是说这个就是这么实现的，没问题。
如果就是这么实现的话，感觉文档里头说一下比较好。

**Comment by Yggdroot** [comment]
首先，gtags有点不一样的地方是它需要生成一个tags数据库，往往这个数据库是跟一个project的根目录对应的。
重要的一点是你使用的是`--path-style through `，它就是要显示相对于项目根目录的相对路径，所以工作目录变为项目的根目录没什么不对呀。如果不是`through`，就不会有你说的不一致的问题了。

**Comment by Howlaind** [comment]
明白了，默认的 `c` 模式就不是给项目使用的，而 gtags 一般和项目相关。所以 gtags 不参考 `g:Lf_WorkingDirectoryMode`。
