### ISSUE TITLE
AttributeError: 'RgExplManager' object has no attribute '_read_finished'

### ISSUE THREAD

**Issue by mulianov** [Yggdroot/LeaderF#326]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.0-881-g1ca84897a
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/cloudhead/hostutils/neovim/build/config -I/home/cloudhead/hostutils/neovim/src -I/home/cloudhead/hostutils/neovim/.deps/usr/include -I/usr/include -I/home/cloudhead/hostutils/neovim/build/src/nvim/auto -I/home/cloudhead/hostutils/neovim/build/include
Compiled by cloudhead@neobober

Features: +acl +iconv +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

- Output of `:echo has("python")`: 
1
- Output of `:echo has("python3")`: 
1
- Output of `:py print(sys.version)`: 
2.7.15 (default, May  1 2018, 05:55:50)
[GCC 7.3.0] 
- Output of `:py3 print(sys.version)`: 
3.7.2+ (default, Feb  2 2019, 14:31:48)
[GCC 8.2.0]
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
" search word under cursor, the pattern is treated as regex, and enter normal mode directly
noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
" search word under cursor, the pattern is treated as regex,
" append the result to previous search results.
noremap <C-G> :<C-U><C-R>=printf("Leaderf! rg --append -e %s ", expand("<cword>"))<CR>
" search word under cursor literally only in current buffer
noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR>
" search visually selected text literally, don't quit LeaderF after accepting an entry
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F --stayOpen -e %s ", leaderf#Rg#visual())<CR>
" recall last search. If the result window is closed, reopen it.
noremap go :<C-U>Leaderf! rg --stayOpen --recall<CR>

nnoremap <silent> <leader>o :LeaderfBufTag <CR>
"nnoremap <silent> <leader>b :LeaderfBufferAll<CR>

highlight Lf_hl_match gui=bold guifg=Blue cterm=bold ctermfg=21
highlight Lf_hl_matchRefine  gui=bold guifg=Magenta cterm=bold ctermfg=201

let g:Lf_PreviewResult = {
    \ 'File': 0,
    \ 'Buffer': 0,
    \ 'Mru': 0,
    \ 'Tag': 0,
    \ 'BufTag': 0,
    \ 'Function': 1,
    \ 'Line': 0,
    \ 'Colorscheme': 0
    \}

let g:Lf_HideHelp = 1
let g:Lf_CursorBlink = 0
let g:Lf_StlSeparator = { 'left': '', 'right': '' }
                                                  
### Describe your question, feature request, or bug.

<C-F> everytime cause next error:

Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#pyt
hon3#Call:                                                                         
line   18:
Error invoking 'python_execute' on channel 8 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cloudhead/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", li
ne 715, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/cloudhead/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", li
ne 671, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/cloudhead/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", lin
e 626, in startExplorer
    super(RgExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/cloudhead/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", li
ne 1462, in startExplorer
    self._bangEnter()
  File "/home/cloudhead/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", lin
e 544, in _bangEnter
    self._workInIdle(bang=True)
  File "/home/cloudhead/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", li
ne 1532, in _workInIdle
    if self._read_finished > 0:
AttributeError: 'RgExplManager' object has no attribute '_read_finished'

### Actual behaviour
Error message after result window popup
### Expected behaviour
No error

**Comment by Yggdroot** [comment]
Fixed.

**Comment by mulianov** [comment]
Thanks!
