### ISSUE TITLE
怎么映射<m-j>

### ISSUE THREAD

**Issue by avriltank** [Yggdroot/LeaderF#330]
> 你好，大佬，请问能不能在leaderf命令行中映射<m-j>替代原来的<c-j>来上下移动匹配项呢？

**Comment by avriltank** [comment]
就是用《m-j>》替换原来的《c-j》来上下移动选择匹配项

**Comment by Yggdroot** [comment]
<m-j>是什么按键？Alt-j？不可以

**Comment by avriltank** [comment]
是的。试了下，好像alt键，都不能映射。不知道是不是python那边的原因

**Comment by Yggdroot** [comment]
不是，是没有支持，因为vim并不总能够catch到alt键，特别是在一些终端上，所以就没有支持。

**Comment by fgheng** [comment]
> 是的。试了下，好像alt键，都不能映射。不知道是不是python那边的原因

试下neovim

**Comment by fgheng** [comment]
> 不是，是没有支持，因为vim并不总能够catch到alt键，特别是在一些终端上，所以就没有支持。

你好,我想知道leaderf用的是什么窗口,这个跟普通的分割窗口好像不一样,感觉很好用,想了解下

**Comment by Yggdroot** [comment]
> > 不是，是没有支持，因为vim并不总能够catch到alt键，特别是在一些终端上，所以就没有支持。
> 
> 你好,我想知道leaderf用的是什么窗口,这个跟普通的分割窗口好像不一样,感觉很好用,想了解下

就是普通split的窗口。

**Comment by fgheng** [comment]
> > > 不是，是没有支持，因为vim并不总能够catch到alt键，特别是在一些终端上，所以就没有支持。
> > 
> > 
> > 你好,我想知道leaderf用的是什么窗口,这个跟普通的分割窗口好像不一样,感觉很好用,想了解下
> 
> 就是普通split的窗口。

但是我使用split的时候,原来的窗口会跳动,而leaderf的窗口并没有,你是不是进行了相关设置呀?

在leaderf中,如果原来窗口的光标没有占据leaderf窗口的位置,那么打开leaderf的时候原来的窗口不会有任何移动(显示的内容,光标),而在普通的split窗口中,即便光标没有占据新打开的窗口的位置,在打开新的窗口的时候都会移动.

我不知道作者使用的什么方法设置的,请教一下,谢谢.

**Comment by Yggdroot** [comment]
哦，这是因为我用了winsaveview()和winrestview()
https://github.com/Yggdroot/LeaderF/blob/4b4804b14b8027f56f6eac790dc3d28bebff9488/autoload/leaderf/python/leaderf/instance.py#L303

https://github.com/Yggdroot/LeaderF/blob/4b4804b14b8027f56f6eac790dc3d28bebff9488/autoload/leaderf/python/leaderf/instance.py#L330-L333

**Comment by fgheng** [comment]
我了解了，非常感谢你 @Yggdroot
