### ISSUE TITLE
LeaderfHelp does not show all help tags

### ISSUE THREAD

**Issue by silver246** [Yggdroot/LeaderF#332]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

- Output of `:echo has("python")`: 
0

- Output of `:echo has("python3")`: 
1

- Output of `:py3 print(sys.version)`:
3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]

- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.
:LeaderfHelp only shows help tags for installed plugins under the home directory (~/.vim/...)
### Steps to reproduce
Execute :LeaderfHelp
### Actual behaviour
Shows help tags for installed plugins under the home directory (~/.vim/...)
### Expected behaviour
Shows all help tags including /usr/share/vim/vim80/doc/tags
### Steps to fix the problem
in helpExpl.py change line 32:
`with lfOpen(tags_file, 'r+', errors='ignore') as f:`
to
`with lfOpen(tags_file, 'r', errors='ignore') as f:`

The `'r+'` tries to open /usr/share/vim/vim80/doc/tags for reading and writing which causes a IOError: [Errno 13] Permission denied exception.
The `'r'` opens the file in read only mode which then works as expected.

**Comment by Yggdroot** [comment]
Fixed, thanks.

**Comment by silver246** [comment]
Works now, thanks.
