### ISSUE TITLE
Keep the window view position.

### ISSUE THREAD

**Issue by latiaoxia** [Yggdroot/LeaderF#334]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.4.0-460-g2470c8829
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.12 (default, Nov 12 2018, 14:36:49)[GCC 5.4.0 20160609]                   
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: undifined
- Operating system: 
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
When opening leaderf window, it will affect other window view position.
![GIF](https://user-images.githubusercontent.com/9819120/60152754-6a32e900-9814-11e9-86eb-23283c7c0bc8.gif)

### Expected behaviour
How to keep the view position like split a window:
![1](https://user-images.githubusercontent.com/9819120/60152826-ca298f80-9814-11e9-943b-ae59cca5f2d4.gif)

**Comment by Yggdroot** [comment]
This behavior works as designed.
