### ISSUE TITLE
Text can not be selected by mouse after enter filter word in leaderf.

### ISSUE THREAD

**Issue by latiaoxia** [Yggdroot/LeaderF#336]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
As title.
### Steps to reproduce
![GIF](https://user-images.githubusercontent.com/9819120/60379171-d3a73780-9a60-11e9-9e76-b5e58088997d.gif)

### Expected behaviour
I want the text can also be selected after entering the filter word.

**Comment by Yggdroot** [comment]
You can switch to normal mode by typing `<tab>`, then select the text.
