### ISSUE TITLE
能否支持合并buffer list和mru list呢？

### ISSUE THREAD

**Issue by t6ui** [Yggdroot/LeaderF#338]
buffer list和mru list的功能类似，都是查找最近打开的文件，有时候会记不清到底文件在buffer或是mru中，所以建议提供合并这两个列表的方法。。

谢谢

**Comment by Yggdroot** [comment]
这个功能也很简单，你如果有兴趣可以自己写个扩展，参考#144 或者https://github.com/Yggdroot/LeaderF-marks 。

**Comment by t6ui** [comment]
好的~

**Comment by albertnetymk** [comment]
Just switched from denite recently, and I have quite happy with this change. However, one feature I kind of miss is using one key stroke I can search among buffers and files. Similar to this feature request, but merging `LeaderfFile` and `LeaderfBuffer` instead.
