### ISSUE TITLE
Leaderf rg 能否提供缓存并查看历史搜索记录的功能

### ISSUE THREAD

**Issue by t6ui** [Yggdroot/LeaderF#339]
类似quickfix功能的colder, cnewer， chistory，平时调试查看日志的时候经常反复浏览搜索过的记录...
--
没有这个功能基本不可能用Leaderf rg排查日志文件，刚需...

我平时都是用notepad++查看日志，不知道作者排查日志会用vim当作基本工具吗？

谢谢..

**Comment by Yggdroot** [comment]
我只用vim。
可以想看历史再重新搜索，我觉得rg速度够快，重新搜索跟你敲chistory再出结果应该差不多。
Leaderf rg还有个`--append`，这样后面的搜索会追加到前面的搜索结果后，你也不用翻历史了。

**Comment by t6ui** [comment]
--append不错，谢谢
