### ISSUE TITLE
gtags error! when I run :Leaderf gtags --update

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#340]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  8.1 1600
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.3 (default, Jun 23 2019, 21:21:39) [GCC 5.4.0 20160609]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```
  let g:Lf_PreviewCode = 0
  let g:Lf_WorkingDirectoryMode = 'c'
  let g:Lf_UseVersionControlTool = 0
  let g:Lf_Gtagslabel = 'native-pygments'
```

### Describe your question, feature request, or bug.
when I run `:Leaderf gtags --update`, It have an error `gtags error!`

**Comment by Yggdroot** [comment]
:mess 看看错误信息是什么。

**Comment by fcying** [comment]
> 
> 
> :mess 看看错误信息是什么。
```
gtags: unrecognized option '--skip-symlink'
Usage: gtags [-ciIOqvw][-d tag-file][-f file][dbpath]
gtags error!
```

```
gtags --version
gtags (GNU GLOBAL) 6.5.6
```

**Comment by fcying** [comment]
编译安装了个 `6.6.3`的版本, 能正常用了. 
希望还是能兼容下老版本, 服务器上还是带老版本的多

**Comment by Yggdroot** [comment]
不打算兼容了。就像vim/neovim，好多人都追着最新的feature用，我的LeaderF兼容到vim7.4，也没有几个星。

**Comment by cyniczhi** [comment]
> 不打算兼容了。就像vim/neovim，好多人都追着最新的feature用，我的LeaderF兼容到vim7.4，也没有几个星。

hhh，我就是这种人，新环境都是自己编译最新的vim
