### ISSUE TITLE
查找输入字符多了后会卡死

### ISSUE THREAD

**Issue by jerrywang1981** [Yggdroot/LeaderF#341]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 19 2019 12:07:03)
macOS version
Included patches: 1-950
Compiled by Homebrew

- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim): nothing
- Output of `:py print(sys.version)`: nothing
- Output of `:py3 print(sys.version)`: 3.7.3
- Output of `:echo g:Lf_Debug_Cmd`:  git ls-files  "." && git ls-files --others --exclude-standard  "."
- Output of `:echo g:Lf_FilesFromCache`:  1
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
  let g:Lf_ShortcutF = '<c-p>'
  let g:Lf_CommandMap = {'<Tab>': ['<ESC>']}
  let g:Lf_DefaultMode = 'NameOnly'
  let g:Lf_WindowHeight = 0.3
  let g:Lf_WorkingDirectoryMode = 'Ac'
  let g:Lf_GtagsAutoGenerate = 0
  let g:Lf_Gtagslabel = 'native-pygments'

```
### Describe your question, feature request, or bug.
查找的时候 Leaderf rg
输入字符大约超了4个后，就会卡死。

**Comment by jerrywang1981** [comment]
不好意思，装了c extension后好像好了。

**Comment by jerrywang1981** [comment]
安装了 c extesion后， 好像还有这个问题，特别是查找  这种 <div
带尖括号的。
像这个现在就卡死在这了。
<img width="629" alt="image" src="https://user-images.githubusercontent.com/8133242/60812454-1e911f80-a1c4-11e9-91a7-2780c432bed5.png">

**Comment by Yggdroot** [comment]
这种情况有可能是有很长的行，vim对于很长的行处理很慢。

**Comment by Yggdroot** [comment]
你用`:Leaderf rg -M 150`再试一下看看。

**Comment by Yggdroot** [comment]
跟#318 应该是同一个原因。

**Comment by jerrywang1981** [comment]
加上了好用了，应该就是这个原因。
```
  let g:Lf_RgConfig = [
    \ "--max-columns=150",
    \ "--glob=!node_modules/*",
    \ "--glob=!dist/*",
    \ ]

```
