### ISSUE TITLE
Leaderf gtags --update报错

### ISSUE THREAD

**Issue by JRuiChen** [Yggdroot/LeaderF#342]
我一旦执行gtags相关的命令，就会提示 environment can only contain strings
:mess  看到的也是environment can only contain strings

请问知道怎么回事吗

**Comment by Yggdroot** [comment]
你是什么系统？

**Comment by JRuiChen** [comment]
> 你是什么系统？

我是win10  vim8.1

**Comment by Yggdroot** [comment]
python是什么版本？

**Comment by Yggdroot** [comment]
复现步骤是什么？

**Comment by Yggdroot** [comment]
https://my.oschina.net/u/58432/blog/91533
看看下面代码输出什么？
```python
import os
import types
print("============================================")
for k, v in os.environ.iteritems():
    if type(v) is not types.StringType:
        print(k, v, type(v))
print("============================================")

```

**Comment by JRuiChen** [comment]
> https://my.oschina.net/u/58432/blog/91533
> 看看下面代码输出什么？
> 
> ```python
> import os
> import types
> print("============================================")
> for k, v in os.environ.iteritems():
>     if type(v) is not types.StringType:
>         print(k, v, type(v))
> print("============================================")
> ```

这一段代码的输出内容为空，我google了下environment can only contain strings 的报错好像是python 2.7本身的问题，有bug，我先把issue关了，谢谢了。

复现的话，很容易，直接执行上面的指令 Leaderf gtags --update 必然出现。
我的系统是win10 64位，  python 2.7.16，   

gtags下载的是 GLOBAL 6.6.3  ,地址：https://www.gnu.org/software/global/download.html
gtags即 GLOBAL 6.6.3是win32版本因为windows只有这个版本可选
