### ISSUE TITLE
`let g:Lf_CursorBlink=0` breaks <C-J> and <C-K>

### ISSUE THREAD

**Issue by ruohola** [Yggdroot/LeaderF#343]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:36:07)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1
Compiled by mool@tororo
Huge version with GUI.  Features included (+) or not (-):
```

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1

- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let mapleader=' '
call plug#begin('~/vimfiles/plugins')
Plug 'Yggdroot/LeaderF'
call plug#end()
let g:Lf_CursorBlink=0
```

When using the above minimal `vimrc` file, which sets the variable `g:Lf_CursorBlink` to `0`. `<C-J>` and `<C-K>` mappings stop working completely when trying to scroll the LeaderF output.

**Comment by Yggdroot** [comment]
Are you using the latest version of LeaderF?

**Comment by ruohola** [comment]
I was not... I updated to the latest version and it's working correctly now.
