### ISSUE TITLE
[feature requerst]Support working path mode in LeaderF file search

### ISSUE THREAD

**Issue by dreamingo** [Yggdroot/LeaderF#344]
Is there a way for leaderF to support **working path mode** when search files? The concept of **working path mode** was borrowed from [kien/ctrlp.vim](https://github.com/kien/ctrlp.vim):

```
let g:ctrlp_working_path_mode = 'ra'
```

* `'c'` - the directory of the current file.
* `'r'` - the nearest ancestor that contains one of these directories or files: .git .hg .svn .bzr _darcs
* `'a'` - like c, but only if the current working directory outside of CtrlP is not a direct ancestor of the directory of the current file.
* `0` or `''` (empty string) - disable this feature.

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/256604e6dbb828a5234c8b1588141d4942c4c106/doc/leaderf.txt#L458-L482

**Comment by dreamingo** [comment]
> https://github.com/Yggdroot/LeaderF/blob/256604e6dbb828a5234c8b1588141d4942c4c106/doc/leaderf.txt#L458-L482

It works! Thanks very much
