### ISSUE TITLE
LeaderfFile do not update file lists.

### ISSUE THREAD

**Issue by latiaoxia** [Yggdroot/LeaderF#345]
- vim or neovim? 
    - [] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
LeaderfFile do not update file lists after create some files in the current directory.

### Steps to reproduce
For example, 

```
⟩ tree
.
├── 1
├── 2
└── 3

0 directories, 3 files
```
there are 3 files in the current directory, if I type `:LeaderfFile`, these 3 files shown and create a new file named 4 by command `touch 4`, type `:LeaderfFile` again, the file 4 does not exist in the file list. All the operations are done in two terminals with the same pwd, one run the command `touch 4` to create file and another run neovim.

**Comment by Yggdroot** [comment]
What is the output of `:echo g:Lf_Debug_Cmd`?

**Comment by latiaoxia** [comment]
`rg --no-messages --files --color never`
It's not a git repo.

**Comment by Yggdroot** [comment]
Please set 
```vim
    let g:Lf_UseMemoryCache = 0
    let g:Lf_UseCache = 0
```
and have a try.

**Comment by latiaoxia** [comment]
`let g:Lf_UseMemoryCache = 0` works.
And will it support dynamic updating caches?

**Comment by Yggdroot** [comment]
Yes.

**Comment by latiaoxia** [comment]
OK, thanks!
