### ISSUE TITLE
[feature request] add edit mode in leaderf rg

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#346]
### Describe your question, feature request, or bug.
like `ctrlsf.vim`, it is useful when you are working on project-wide refactoring
[https://github.com/dyng/ctrlsf.vim#edit-mode](https://github.com/dyng/ctrlsf.vim#edit-mode)

**Comment by bogdan0083** [comment]
+1 for this feature. Extremely useful for refactoring!

**Comment by Yggdroot** [comment]
I add a replacement feature for `Leaderf rg`, which can be used for refactoring. 
usage:
In normal mode, add the following commands:
**r** : replace a pattern
**w** : apply the changes to buffer without saving
**W** : apply the changes to buffer and save
**U** : undo the last changes applied

If the buffer has been changed, `:w` and `:W` are the same as `w` and `W` in normal mode.
Command `:Undo` is the same as `U` in normal mode.
