### ISSUE TITLE
Annoying 'Press ENTER or type command to continue' prompt 

### ISSUE THREAD

**Issue by meijieru** [Yggdroot/LeaderF#347]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.8/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.3 (default, Jun 24 2019, 04:54:02)                                                                                                              
[GCC 9.1.0]
- Output of `:echo g:Lf_Debug_Cmd`:  git ls-files  "." && git ls-files --others --exclude-standard  "."
- Output of `:echo g:Lf_FilesFromCache`:  1
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
    " LeaderF
    let g:Lf_ShortcutF = '<leader>ff'
    let g:Lf_ShortcutB = '<leader>fb'
    nnoremap <leader>fm :Leaderf mru<cr>
    nnoremap <leader>fc :Leaderf! function<cr>
    nnoremap <leader>fl :Leaderf! bufTag<cr>
    nnoremap <leader>ft :Leaderf tag<cr>

    let g:Lf_RootMarkers = g:root_markers
    let g:Lf_WorkingDirectoryMode = 'ac'
    let g:Lf_DefaultMode = 'NameOnly'
    let g:Lf_WindowHeight = 0.35
    let g:Lf_CacheDirectory = g:runtime_root . 'cache'
    let g:Lf_ShowRelativePath = 1
    let g:Lf_StlColorscheme = 'gruvbox'
    let g:Lf_StlSeparator = { 'left': '', 'right': '' }
    let g:Lf_MruMaxFiles = 2048
    let g:Lf_PreviewResult = {'Function':1, 'BufTag':0}
```

### Describe your question, feature request, or bug.

When `set cmdheight=1`, use leaderf file will output above prompt consistently, which is annoying. `set cmdheight=2` could solve it, but it wastes screen space.
I have `set shortmess=actIT`

**Comment by Yggdroot** [comment]
Sorry, I can not reproduce this issue.

What is the output of `:mess`?

**Comment by meijieru** [comment]
`"~/workspace/other/dotfiles/git.sh" 23L, 533C`

**Comment by Yggdroot** [comment]
Can not reproduce.

**Comment by meijieru** [comment]
Could you please tell me how to debug it?

**Comment by Yggdroot** [comment]
I don't know. Does this happen on vim?
