### ISSUE TITLE
Error when pressing <Esc> after ":LeaderfRgInteractive"

### ISSUE THREAD

**Issue by voldikss** [Yggdroot/LeaderF#349]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.0-dev
- Output of `:echo has("python")`: 
1
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
感觉这里应该判断一下 `pattern` `glob` 是否为空，或者加个 `catch`。
https://github.com/Yggdroot/LeaderF/blob/b8b9c6103738a095d77f92613ab5a863d28f7011/autoload/leaderf/Rg.vim#L79-L89
### Steps to reproduce
输入 `:LeaderfRgInteractive` 然后按 `<Esc>`, Leaderf 报错

### Actual behaviour
报错
### Expected behaviour
静默取消搜索或者输出 `Search cancelled`等

**Comment by Yggdroot** [comment]
pattern可以为空，就相当于直接执行`Leaderf rg`.
glob确实需要判断一下，为空是直接退出呢还是认为是`*`呢？

**Comment by voldikss** [comment]
噢噢这样啊。我感觉 “退出”比较好点

Yggdroot <notifications@github.com> 于 2019年8月6日周二 下午1:31写道：

**Comment by Yggdroot** [comment]
好，那就退出。

**Comment by Yggdroot** [comment]
改好了。

**Comment by voldikss** [comment]
我刚试了下可以了。

**Comment by voldikss** [comment]
还有个问题，这种情况应该考虑吗：就是在 "Search pattern "之后输了几个空格，这个也会报错
