### ISSUE TITLE
suggest: step-by-step processing

### ISSUE THREAD

**Issue by zhenyangze** [Yggdroot/LeaderF#35]
hi. bother you again.

when i open a large project,then i open leaderF,it will take a long time to search files.and i have to wait it until finish finding all.

can it do some changes?
1. search the recent changed dirs  first(not all) and then show result.
2. background process.
3. listen for directory changes.

thx!

**Comment by Yggdroot** [comment]
For 1, I think it's difficult to implement.
For 2, I will add async support later on.
For 3, watchdog?

**Comment by zhenyangze** [comment]
thx.
look forward to your work. m( _　_ )m
For 3, it aim to auto refresh.
And for 1, i will try to implemente it in one way, although not very familiar.
[]~(￣▽￣)~*

**Comment by roxma** [comment]
> listen for directory changes.

Just curious, why you need this feature?

As a regular use case, you trigger LeaderF, type and find the file you want as soon as possible, then open the file and close LeaderF. I don't see it being useful in this use case.

**Comment by Yggdroot** [comment]
@zhenyangze Now you can use LeaderF to search a file asynchronously, and you don't have to wait for its finishing the index. 
I think this issue can be closed.

**Comment by zhenyangze** [comment]
thanks!
