### ISSUE TITLE
no gcc, is there workaround?

### ISSUE THREAD

**Issue by jerrywang1981** [Yggdroot/LeaderF#350]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Steps to reproduce
Redhat Enterprise 7, 服务器上没有gcc, 自己也没有权限安装。运行install.sh的时候出错。
### Expected behaviour
(base) [jerry@kgc-jump LeaderF]$ ./install.sh
Begin to compile C extension of Python2 ...
running build
running build_ext
building 'fuzzyMatchC' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-b
uffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SO
URCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -
fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c fuzzyMatch.c -o build/temp.linux-x86_64-2.7/fuzzyMatch.o
unable to execute gcc: No such file or directory
error: command 'gcc' failed with exit status 1

Begin to compile C extension of Python3 ...
running build
running build_ext
building 'fuzzyMatchC' extension
gcc -pthread -B /home/jerry/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jerry/anaconda3/include/python3.7m -c fuzzyMatch.c -o build/temp.linux-x86_64-3.7/fuzzyMatch.o
unable to execute 'gcc': No such file or directory
error: command 'gcc' failed with exit status 1

**Comment by Yggdroot** [comment]
在别的机器上编译copy过去？
