### ISSUE TITLE
ubuntu16，安装了global，写python，搜索不到tag

### ISSUE THREAD

**Issue by aGVsZWk** [Yggdroot/LeaderF#351]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tWk8pe/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-tWk8pe/neovim-0.3.4/build/config -I/build/neovim-tWk8pe/neovim-0.3.4/src -I/usr/include -I/build/neovim-tWk8pe/neovim-0.3.4/build/src/nvim/auto -I/build/neovim-tWk8pe/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

health#jedi#check
========================================================================
##### jedi-vim version

 - jedi-vim git version: b3d715c
 - jedi git submodule status:  35e5cf2c2aa7c2f2c8ea08d74ef64f681582e49e pythonx/jedi (v0.15.0)
 - parso git submodule status:  c0ace63a6905500e18d8ac06af1a0a9057e63498 pythonx/parso (v0.5.1)

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.3 (default, Apr  3 2019, 05:39:12), [GCC 8.3.0]`
 - global site module: `/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/lib/python3.7/site.py`

##### Jedi

 - path: `/home/luke/.config/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.15.0

##### Jedi environment: <SameEnvironment: 3.7.3 in /home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi>

 - executable: /home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/bin/python3
 - sys_path:
    - `/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/lib/python37.zip`
    - `/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/lib/python3.7`
    - `/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/lib/python3.7/lib-dynload`
    - `/usr/lib/python3.7`
    - `/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/lib/python3.7/site-packages`

##### Known environments

 - <SameEnvironment: 3.7.3 in /home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi> (/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/bin/python3)

 - <Environment: 3.7.3 in /home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi> (/home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/bin/python3.7)

 - <Environment: 2.7.16 in /usr> (/usr/bin/python2.7)

##### Settings

```
  omnifunc=htmlcomplete#CompleteTags
	Last set from /usr/share/nvim/runtime/ftplugin/html.vim
  completeopt=noinsert,menuone,noselect
	Last set from ~/.config/nvim/init.vim
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/0'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - WARNING: Your virtualenv is not set up optimally.
    - ADVICE:
      - Create a virtualenv specifically for Neovim and use `g:python_host_prog`.  This will avoid the need to install the pynvim module in each virtualenv.
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.3.0 (outdated; from /usr/lib/python2.7/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.3.2

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: $VIRTUAL_ENV matches executable
  - INFO: Executable: /home/luke/.local/share/virtualenvs/virtualenv_test-aS7UFMXi/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

```
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: <!-- should only provide this information if it's an issue of :Leaderf file -->
- Output of `:echo g:Lf_FilesFromCache`: <!-- should only provide this information if it's an issue of :Leaderf file -->
- Operating system: <!-- use [x] to select, note: no space in between brackets -->
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
安装了global, 配置`let g:Lf_GtagsAutoGenerate = 1`, 在python项目目录下，`:Leaderf gtags`为空
### Steps to reproduce

### Actual behaviour

### Expected behaviour

**Comment by Yggdroot** [comment]
设置 let g:Lf_Gtagslabel = 'native-pygments' 了吗？安装pygments了吗？
