### ISSUE TITLE
能提供一个子命令，合并file 和mru的搜索结果。

### ISSUE THREAD

**Issue by liu2hai** [Yggdroot/LeaderF#353]
- vim or neovim? 
    - [c ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ c] Linux
    - [ c] Mac OS X
    - [c ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
LeaderF 很方便写扩展的，你如果有兴趣，可以自己写扩展来支持这个功能。

**Comment by liu2hai** [comment]
好的，我尝试一下
