### ISSUE TITLE
gtags could not be generated

### ISSUE THREAD

**Issue by zombo** [Yggdroot/LeaderF#354]
```
let g:Lf_RootMarkers = ['.git', '.svn']
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagsconf = 'd:/software/gtags/share/gtags/gtags.conf'
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_GtagsSkipUnreadable = 1
let g:Lf_WildIgnore = {
       \ 'dir': ['.svn','.git','.hg'],
       \ 'file': ['*.sw?','~$*','*.bak','*.exe','dll','lib', 'pdb', 'sdf', 'pch', 'class', 'doc', 'docx', 'xls', 'xlsx', 'pdf', '*.o','*.so','*.py[co]']
       \}
```

this is my configuration. however, when I run `LeaderF gtags -all`, the error message is like the following:

`
global: directory \'c:\user\me\.LfCache\gtags\d%myproject\' not found
`

**Comment by Yggdroot** [comment]
Have a try "Leaderf gtags --update" first, to see what happens.

**Comment by zombo** [comment]
> 
> 
> Have a try "Leaderf gtags --update" first, to see what happens.

Nothing happened.

and I try two commands,  `LeaderfBufTag`  and `LeaderfTag`.

the result of `LeaderfBufTag` is correct.
the result of `LeaderfTag` is `no content!`

what is the difference between with them?

**Comment by Yggdroot** [comment]
run `Leaderf gtags --update`, then `Leaderf gtags --all`

**Comment by Yggdroot** [comment]
LeaderfBufTag and LeaderfTag are not related to `Leaderf gtags`.

**Comment by zombo** [comment]
> 
> 
> run `Leaderf gtags --update`, then `Leaderf gtags --all`

update: nothing happened
all: `global: directory \'c:\user\me\.LfCache\gtags\d%myproject\' not found`

**Comment by zombo** [comment]
> are not related to `Leaderf gtags`.

so, it is another question.
 the `BufTag` is correct.  what is the wrong with `tag` ?

vim 8.1 patch 1302  x64

**Comment by Yggdroot** [comment]
> > are not related to `Leaderf gtags`.
> 
> so, it is another question.
> the `BufTag` is correct. what is the wrong with `tag` ?
> 
> vim 8.1 patch 1302 x64

LeaderfTag reads the tags file, you should generate the tags file by yourself using ctags.

**Comment by Yggdroot** [comment]
> > run `Leaderf gtags --update`, then `Leaderf gtags --all`
> 
> update: nothing happened
> all: `global: directory \'c:\user\me\.LfCache\gtags\d%myproject\' not found`

Make sure you have installed ctags.

**Comment by zombo** [comment]
> 
> 
> > > run `Leaderf gtags --update`, then `Leaderf gtags --all`
> > 
> > 
> > update: nothing happened
> > all: `global: directory \'c:\user\me\.LfCache\gtags\d%myproject\' not found`
> 
> Make sure you have installed ctags.

yes, I have installed ctags and gtags.  
buftag and tagbar works, so ctags  works.
gtags works because `vim-gutentags` works

**Comment by Yggdroot** [comment]
Add some log in https://github.com/Yggdroot/LeaderF/blob/2a4bffc1a91fbea74c3e2fd8c9e23e0d59e607ea/autoload/leaderf/python/leaderf/gtagsExpl.py#L426-L451
, to see what happens when running `Leaderf rg --update`.
