### ISSUE TITLE
Split preview window from LeaderF window without using the main window

### ISSUE THREAD

**Issue by wimstefan** [Yggdroot/LeaderF#355]
Sorry for the somewhat fuzzy (sic!) title but it's hard to describe what I'm looking for and I'm certainly lacking the correct terms in vim but I try to replicate the preview behaviour from fzf where the preview does not take over the main window but splits in the search window ... 
I'm aware of #282 but it doesn't  give me the result I'd like to achieve - you can see what I mean if you follow the [link](https://junegunn.kr/2016/07/fzf-git/) given in #282 ...

PS: if you think this request should be expressed in #282 I'll happily delete this issue and edit #282.

**Comment by Yggdroot** [comment]
I know what you mean, I plan to implement the preview by using the pop up window, so you can place the preview window wherever you like. But It maybe a long time later.

**Comment by wimstefan** [comment]
That's good to hear - both you understand what I mean and your plans ;-)
Looking forward to it!

**Comment by Yggdroot** [comment]
Done, please have a try.

**Comment by wimstefan** [comment]
Wow thank you so much!!! It's already working quite well with the default configuration :)
There are a few things not working which might be specific to my configuration: 
let g:Lf_WindowPosition = 'right'
let g:Lf_PreviewHorizontalPosition   = 'left'

In that case I can't scroll with the mouse in the popup window when invoked in input mode with <c-p>. 
If I toggle the input mode and open the popup window with 'p' I can scroll but the size of the popup window is very small if the file previewed is on top of the list. The size increases with the position of the file towards the middle of the screen. This happens with all possible Lf_PreviewHorizontalPosition configurations.

I hope this description makes some sense ...

In any case that's a very nice start of a new feature :) Thanks again :-D

**Comment by Yggdroot** [comment]
>  I can't scroll with the mouse in the popup window when invoked in input mode with `<c-p>`

This may be a bug of popup window, I tried to fix it when implementing, but did not success.
> the size of the popup window is very small if the file previewed is on top of the list.

This behavior is supposed that `let g:Lf_WindowPosition = 'bottom'`, will fix it.

**Comment by wimstefan** [comment]
And the size of the popup window is now adaptive :) 
Thanks a lot :+1:
