### ISSUE TITLE
Question: how to add mappings to custom commands?

### ISSUE THREAD

**Issue by kriansa** [Yggdroot/LeaderF#356]
I've been trying to bind `C-W` to erase a word. Do you know how can I do it?

Thanks!

**Comment by Yggdroot** [comment]
You can use ctrl-u.

**Comment by kriansa** [comment]
I know that one, but sometimes I'd like to delete a single word, not the entire string...

**Comment by Yggdroot** [comment]
currently, leaderf can't do it. In my opinion, there is little chance to type more than one word.

**Comment by kriansa** [comment]
I understand, and I'm not expecting it to be implemented either. I'm ok with it being just another customized trick on my dotfiles. 

In case I wanna do it myself, is there a place you recommend me to start? I was going after where the C-U is defined and I thought there would be some `augroup` specific for LeaderF buffers so I could make custom maps, but I didn't find it.

Bu the way, thank you so much for your work on this plugin. I was long looking for a better tool than the ones I was previously using - even considering writing one myself. Luckily I found yours.

**Comment by Yggdroot** [comment]
You can use 
https://github.com/Yggdroot/LeaderF/blob/bd90b6b2bf2545ca4ad9eec1f2be0a318cbd258d/doc/leaderf.txt#L437-L456

to customize the keys used in **normal mode**(Use `<Tab>` to switch to).

**Comment by kriansa** [comment]
Thanks @Yggdroot . I decided to do it on the Python source instead.

**Comment by kawing-chiu** [comment]
Hi. I'm looking for exactly the same feature. @Yggdroot May I ask why this cannot be supported? It feels so weird to not support it because `<C-w>` just works in so many places, like vim's command mode, CtrlP's prompt, bash shell etc. LeaderF already supports `<C-h>` and `<C-u>`, why left the other one? Also LeaderF has support for searching multiple words (as shown in the gifs in the front page), I think `<C-w>` is a natural complement to this great feature.

**Comment by Yggdroot** [comment]
> Hi. I'm looking for exactly the same feature. @Yggdroot May I ask why this cannot be supported?
> 
> It feels so weird to not support it because `<C-w>` just works in so many places, like vim's command mode, CtrlP's prompt, fzf's prompt, bash shell etc. LeaderF already supports `<C-h>` and `<C-u>`, why left the other one? Also LeaderF has support for searching multiple words (as shown in the gifs in the front page), I think `<C-w>` is a natural complement to this feature.
> 
> For example if I type `some keyword py`, but later want to search cpp files instead. With `<C-w>`, I can do `<C-w> cpp`.

OK, will support it later.

**Comment by Yggdroot** [comment]
Done.

**Comment by kawing-chiu** [comment]
@Yggdroot Thank you very much. It works great!
