### ISSUE TITLE
兼顾一下便携版Python的用户

### ISSUE THREAD

**Issue by daocang** [Yggdroot/LeaderF#357]
想转用Leaderf，使用时提示python 版本不对
1、python3 加了路径变量，有文件类型关联，能直接运行*.py。
2、没使用install.bat，手动编译fuzzyEngine.cp37-win_amd64.pyd、fuzzyMatchC.cp37-win_amd64.pyd成功，放置autoload\leaderf\python\目录下。
OS: windows 10 pro

**Comment by Yggdroot** [comment]
> 提示python 版本不对
怎么提示的？

如果在vim命令行执行`:py3 print(sys.version)`可以工作，就可以用呀。

**Comment by daocang** [comment]
返回值为1，但就是用不了，:Leaderf -h  或 rg ，静止几秒vim就闪退

**Comment by daocang** [comment]
对Python调用有什么要求吗
我Python其它方面应用也正常

**Comment by Yggdroot** [comment]
哦，这样啊。闪退是版本不兼容。一般要保证py版本跟编译vim的版本一致。

**Comment by Yggdroot** [comment]
https://www.v2ex.com/t/410079#reply9
这篇文章的前面部分看一下。

**Comment by daocang** [comment]
> 
> 
> https://www.v2ex.com/t/410079#reply9
> 这篇文章的前面部分看一下。

按文章里说的，设置了下面二项就能正常使用了，谢谢指引！
set pythonthreedll= 可用相对路径\python37.dll
set pythonthreehome=可用相对路径\python
用的是最新的Nightly Vim，python支持到3.7.4
