### ISSUE TITLE
Leaderf rg doesn't work in latest version

### ISSUE THREAD

**Issue by clark-t** [Yggdroot/LeaderF#358]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  8.1.1967
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): [empty]
- Output of `:echo &pythonthreedll`(only vim, not neovim): [empty]
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

the latest version of LeaderF doesn't work well in command `:Leaderf rg [path]`, but when I rollback LeaderF to the version Aug 20, problem solved.

### Steps to reproduce

1. update LeaderF to latest version;
2. cd to `~/.vim/bundle/LeaderF`;
3. run `vim install.sh`;
4. enter command `Leaderf rg ~/.vim/bundle/LeaderF/install.sh`;
5. nothing display in subwindow;

or

2. run `vim ~/,vim/bundle/LeaderF`;
3. enter command `Leaderf rg ~/.vim/bundle/LeaderF/install.sh`;
4. shows some strange results such as:

```
.viminfo:25:Leaderf rg /home/clarkt/.vim/bundle/LeaderF/install.sh
.viminfo:26:|2,0,1567618112,"Leaderf rg /home/clarkt/.vim/bundle/LeaderF/install.sh"
.LfCache/tempMru:1:/home/clarkt/.vim/bundle/LeaderF/install.sh
```

**Comment by Yggdroot** [comment]
This is because a new commit is introduced to comply with the rg command line.
```
rg [OPTIONS] PATTERN [PATH ...]
rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
```

So `Leaderf rg xxx` means search pattern `xxx`, just like using `rg xxx`.
If you want to achieve the same effect as before, please use `Leaderf rg "" PATH` instead.

**Comment by clark-t** [comment]
it works :)

thx
