### ISSUE TITLE
不能生成 Gtags 数据文件

### ISSUE THREAD

**Issue by daocang** [Yggdroot/LeaderF#359]
- vim or neovim? 
    - [ 

- [x ] vim

    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): x
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 1
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
不论是自动还是手动执行::Leaderf gtags --update，指定目录下都没有gtags数据文件生成。其它功能一切正常。leaderf tag  ,leaderf function 能正常执行。问题与[issues354#](https://github.com/Yggdroot/LeaderF/issues/354#issue-485496232)基本相同
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_GtagsSource = 2
let g:Lf_GtagsfilesCmd = {
            \ '.git': 'git ls-files --recurse-submodules',
            \ '.hg': 'hg files',
            \ 'default': 'rg --no-messages --files'
            \}
let g:Lf_GtagsAcceptDotfiles = 0
let g:Lf_GtagsSkipUnreadable = 0
"let g:Lf_GtagsSkipSymlink = ''
let g:Lf_Gtagslabel='native-pygments'
let g:Lf_Gtagsconf=$vim.'/gtags/share/gtags/gtags.conf'

另：gutentags.vim 功能执行正常
顺便报一个问题：工作目录路径如果包含`上标`字符，leaderf function 功能执行失败

**Comment by daocang** [comment]
> 
> 
> 想起来了，如果路径有非ASCII字符，不要使用g:Lf_GtagsfilesCmd
测试路径无非ASCII字符
let g:Lf_GtagsSource = 0 也试过，失败

**Comment by Yggdroot** [comment]
> 顺便报一个问题：工作目录路径如果包含上标字符，leaderf function 功能执行失败

ctags在windows上有bug，识别不出`test²`这样的路径。

我觉得如果不生成gtags数据库，应该会有错误信息打印出来，没有错误信息很奇怪。

可以在这个函数里加一些打印，看看当`:Leaderf gtags --update`时都做了些什么。
https://github.com/Yggdroot/LeaderF/blob/2a4bffc1a91fbea74c3e2fd8c9e23e0d59e607ea/autoload/leaderf/python/leaderf/gtagsExpl.py#L426-L451

**Comment by Yggdroot** [comment]
> LeaderF是VIM上极好用的插件，后期用户肯定会慢慢更多，从功能完整性考虑，应该加上功能调试，给个选项开关。

调试功能基本有了，常出问题的点基本都有exception或log记录，只是这个问题太corner了。

原因找到了，对于`test²`这样的路径，Windows上有问题，好多命令都会识别成`test2`，这个太奇怪了。
而且对于Python2，如果当前路径是`test²`，
```python
import os
print(os.getcwd())
```
打印出来的竟然是`test2`。
例如在`d:\test²`下执行gtags命令，
```
D:\test² > gtags
gtags: directory 'D:/test2' not found.
```
话说你如果使用的是Python3，应该能看到报错信息，什么错误信息都没有，难道使用的是Python2？
`echo g:Lf_PythonVersion`输出是什么？

**Comment by daocang** [comment]
Python3.7.4

**Comment by daocang** [comment]
gtags 是正常路径也没有文件生成，tags、func 是test²路径下有提示出错

**Comment by Yggdroot** [comment]
正常路径也没有生成就奇怪了。你加些打印看看。

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/a72c3bb35d104309d1c9770f16761004256953ec/autoload/leaderf/python/leaderf/gtagsExpl.py#L426-L436

435行打印出来了，说明`filename.startswith(root)` 是False, 你的文件名和路径有非ASCII字符吗？

**Comment by daocang** [comment]
:echo g:Lf_Debug_Gtags   
D:/.project/test.c  D:\\.project

**Comment by daocang** [comment]
经作者排查，是 set shellslash 设置问题，取消这个设置项就正常了，感谢！

**Comment by Yggdroot** [comment]
修好了。

**Comment by daocang** [comment]
> 
> 
> 修好了。

能正常使用了。
