### ISSUE TITLE
[feature request] Find file based on the current buffer

### ISSUE THREAD

**Issue by Drakirus** [Yggdroot/LeaderF#360]
The [nixprime/cpsm](https://github.com/nixprime/cpsm) CtrlP matcher has tihs awesome feature:
> cpsm will still attempt to perform matching on an empty query based on the open file in the current buffer.

When the query is empty the match is done based on the current buffer name.

I like this feature a lot because it allows me to quickly switch between the implementation file and his test file.
eg:
Having the file `foo.go` open, press `<C-p>`, select the `foo_test.go` file...

The current buffer have to be ignore from the search result.. (another feature by itself??)

I know such feature can be found in `vim-projectionist`, but I tend to prefer selecting file though the fuzzyfinder for other reason.

**Comment by Yggdroot** [comment]
Maybe I will add this feature in the future, currently, you can achieve similar effect through this:
If you opened foo.go using LeaderF by typing `foo`, then launch LeaderF, press `<up>`,  you will see the last search result.

**Comment by Yggdroot** [comment]
Added, you can give it a shot.

**Comment by Drakirus** [comment]
Awesome!
I'll take a look at this later this week.

**Comment by Drakirus** [comment]
I've tried the feature, and it didn't work :disappointed: 

I've tried to figure out what wasn't working for me, and I stumble across this line: 

https://github.com/Yggdroot/LeaderF/blob/2320e6f1020fab8ac34baaea8e2800f7ae2b5878/autoload/leaderf/python/leaderf/manager.py#L882

Removing `or self._cur_buffer.options["buftype"] != b''` from the if statement seems to resolve my issue.

Also, Could it be possible to have another VIM option to always ignore the current buffer name from the search result?

(I know I might be asking for a lot, but that's because I'm seriously considering this plugin as a drop-in replacement for CtrlP, which seems to be less and less maintain).
Ether way THANK you for your work!

**Comment by Yggdroot** [comment]
so you are using neovim? I forgot to test it on neovim.

**Comment by Drakirus** [comment]
Yes, running on neovim!

**Comment by Yggdroot** [comment]
> Also, Could it be possible to have another VIM option to always ignore the current buffer name from the search result?

Since we have the feature "Find file based on the current buffer", I don't think it is necessary to support it. Because if the file name you intend to find is much similar with current buffer name, it will be placed at the top when no input, meanwhile the current buffer name is at the bottom(we can think it is ignored). If not similar, the current buffer name won't bother you at the top.

**Comment by Drakirus** [comment]
I think there is a little miss understanding.
Let say I open the vimrc file.
Then if I run :LeaderfFile and search for 'vim', the first entry to be selected is 'vimrc', IMHO, this is undesirable, the current buffer (the one I triggered the :LeaderfFile cmd) holds the 'vimrc' file.
I don't want my current buffer to be shown in the fuzzy list, if I invoke :LeaderfFile, my goal is to switch away from it.

**Comment by Drakirus** [comment]
I have crafted #368, to fix this sub-issue (not really related to the one described in my original comment, but wellll).
I don't have any knowledge of how `def setBuffer` works, feel free to modify my PR, the goal was to illustrate and show a possible answer, I won't be offended if you close it and implement it in another way.

**Comment by Yggdroot** [comment]
Done, please have a try.

**Comment by Drakirus** [comment]
AWESOME!
 You deserve big fat **thank you**!!!

With `g:Lf_IgnoreCurrentBufferName` and `g:Lf_EmptyQuery` I get very similar result than CtrlP coupled with nixprime/cpsm.
Switching from CtrlP to LeaderF is a no-brainer!

![CtrlP vs LeaderF](https://i.imgur.com/WIqUnrF.png)

@Yggdroot Where can I find your PayPal info? I want to send you few $.

**Comment by Yggdroot** [comment]
Thank you for your kindness. I don't have a PayPal account, and you don't have to send me money.
If you like LeaderF very much, it would be appreciated that if you can advertise it to more people, for example, your colleagues and friends.
As you can see:
![Leaderf](https://user-images.githubusercontent.com/2705841/66725828-da1ebb00-ee67-11e9-9ece-ee8f4569bf22.png)
vs
![ctrlp](https://user-images.githubusercontent.com/2705841/66725833-dd19ab80-ee67-11e9-85d8-ef02d13b66bc.png)

too few people know about it.
