### ISSUE TITLE
编辑 /etc/shadowsocks/local.json 出错

### ISSUE THREAD

**Issue by yangxuanx** [Yggdroot/LeaderF#361]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.4.2
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.16 (default, Mar 11 2019, 18:59:25)
- Output of `:py3 print(sys.version)`: 3.7.4 (default, Jul 16 2019, 07:12:58)
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

nnoremap <silent> <leader>f :LeaderfFile<CR>
nnoremap <silent> <leader>fl :LeaderfLine<CR>
nnoremap <silent> <leader>ft :LeaderfBufTag<CR>
nnoremap <silent> <leader>fu :LeaderfFunction<CR>
nnoremap <silent> <leader>b :LeaderfBuffer<CR>

### Describe your question, feature request, or bug.

编辑 /etc/shadowsocks/local.json 文件，保存文件时，出现如下错误信息：

Request from non-main thread.
Requests from different threads should be wrapped with nvim.async_call(cb, ...)
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ivan/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 57, in _processTask
    task()
  File "/home/ivan/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 435, in _update
    lfCmd("let g:Lf_Debug_Gtags = '%s'" % escQuote(str((filename, root))))
  File "/usr/lib/python3.7/site-packages/pynvim/api/nvim.py", line 287, in command
    return self.request('nvim_command', string, **kwargs)

实际测试sudo nvim 编辑一个json文件，保存时没有错误输出，目前只有编辑上述文件出现错误。

### Steps to reproduce
编辑 /etc/shadowsocks/local.json 保存时出现错误。

### Actual behaviour
出现错误，回车确认，再次输出如下错误，一共三次，错误消失

### Expected behaviour
成功保存，没有错误输出

**Comment by yangxuanx** [comment]
![image](https://user-images.githubusercontent.com/26968633/65196233-bfe4fd80-dab2-11e9-8b70-30cdc30a0591.png)

**Comment by Yggdroot** [comment]
Fix了。
