### ISSUE TITLE
直接执行Leaderf gtags会抛个异常

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#362]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  8.1.1777
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Steps to reproduce

直接执行:Leaderf gtags会抛个异常：
![screenshot](https://user-images.githubusercontent.com/5853792/65212460-c84e3000-dad4-11e9-832d-640fd30bfc18.png)

**Comment by Yggdroot** [comment]
使用gtags要先生成数据库。可以`Leaderf gtags --update`.

**Comment by bstaint** [comment]
我知道 我是指可以吧这个异常给去掉加个提示之类的

**Comment by Yggdroot** [comment]
使用错误报异常很正常啊。

**Comment by bstaint** [comment]
好吧
