### ISSUE TITLE
this plugin is open files in the NERDTree window

### ISSUE THREAD

**Issue by palytoxin** [Yggdroot/LeaderF#363]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 21 2019 18:00:45)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.so.1.0
- Output of `:py print(sys.version)`: [GCC 8.2.1 20181127]
- Output of `:py3 print(sys.version)`: [GCC 9.1.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_ShowHidden=1
let g:Lf_ReverseOrder = 1
```

### Describe your question, feature request, or bug.
feature
when i open vim with nerdtree, when i press `<c-p>` to open file. this file opened in nerdtree side tab, and i have two panel which opening file.

### Expected behaviour
I want open file in right panel, and left panel is nerdtree.

**Comment by Yggdroot** [comment]
You can try to use `<c-]>`  instead of `<CR>` to open a file.

**Comment by palytoxin** [comment]
thanks, but I think the plugin is be like that ctrlp?
ctrlp is open in exist panel default

**Comment by nicoqh** [comment]
Could we add a feature that makes LeaderF avoid opening files in windows created by other plugins?

Something like this:

https://github.com/kien/ctrlp.vim/blob/master/doc/ctrlp.txt#L157-L166
