### ISSUE TITLE
打开gtags结果的同时将结果加到tagstack中

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#365]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

可以实现打开gtags结果的同时将结果加到tagstack中么，查到settagstack可以添加，或者可以通过配置来扩展打开操作么

**Comment by bstaint** [comment]
不用了，我尝试实现了下，还得考虑去重，jumplist可以解决

**Comment by Yggdroot** [comment]
哦，我一般用Ctrl-o，Ctrl-i。
