### ISSUE TITLE
guessMatch() missing required argument 'source' (pos 2)

### ISSUE THREAD

**Issue by liu2hai** [Yggdroot/LeaderF#370]
- vim or neovim? 
    - [x ] vim

- Output of `vim --version` or `nvim --version`: 

- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`: 1
- Output of `:py3 print(sys.version)`: 3.7.4 64bit

- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
   ```
     map <silent> <leader>s :Leaderf --nameOnly file <CR> 
     map <silent> <Leader>b :Leaderf  --nameOnly buffer <CR> 
     map <silent> <Leader>f :Leaderf  --nameOnly --cword --stayOpen rg -i <CR> 
   ```

### Describe your question, feature request, or bug.
      guessMatch() missing required argument 'source' (pos 2)
     

### Steps to reproduce
     1. 打开lederf界面，输入内容
     2. 然后将输入内容用退格键删除，删完的时候就会出现这个错误

**Comment by liu2hai** [comment]
![微信图片_20191018160251](https://user-images.githubusercontent.com/3427609/67077480-ed13f100-f1c1-11e9-9037-b4005e464c75.png)

**Comment by liu2hai** [comment]
我的vim version信息如下：
![微信图片_20191018160321](https://user-images.githubusercontent.com/3427609/67077598-29dfe800-f1c2-11e9-9368-8a4b766e4519.png)

**Comment by Yggdroot** [comment]
我复现不了， 你用的是最新的LeaderF吗？

**Comment by Yggdroot** [comment]
复现了，原来你输入的第一个字符是空格。

**Comment by Yggdroot** [comment]
复现了，就是输入的第一个字符是空格。

**Comment by liu2hai** [comment]
我用的是最新的LeaderF。我输入的都是英文字符，就是在使用leaderf file功能时，输入的都是[a~z]范围内的英文字符，第一个字符不是空格也会出现这种情况。

**Comment by liu2hai** [comment]
我刚刚更新了你的更改。结果更糟了，打开LeaderF，什么内容也没有了，输入内容后也不搜索了。
界面变成这样：
![微信截图_20191018190114](https://user-images.githubusercontent.com/3427609/67089218-b77b0200-f1d9-11e9-8286-246f6d0d1058.png)

**Comment by Yggdroot** [comment]
把你map后面的空格去掉吧

```vim
 map <silent> <leader>s :Leaderf --nameOnly file <CR> 
 map <silent> <Leader>b :Leaderf  --nameOnly buffer <CR> 
 map <silent> <Leader>f :Leaderf  --nameOnly --cword --stayOpen rg -i <CR> 
```

**Comment by liu2hai** [comment]
嗯嗯，果然是这样，看来要弄个插件来检测空格了。谢谢
