### ISSUE TITLE
Leaderf gtags 分屏问题

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#372]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

请问我在使用Leaderf gtags时想实现类似点击符号在下方窗口显示上下文的功能，类似source insight那样。
截图：
![GIF](https://user-images.githubusercontent.com/5853792/67535015-57b5b700-f703-11e9-8885-57aab38cadb8.gif)

目前我的实现是：
```
function! LeaderfSplit(jump)
    if (a:jump == 1)
        exec g:Lf_py "gtagsExplManager.accept('h')"
    endif
    wincmd J
    resize 10
    normal zt
endfunction

function! LeaderfGtags()
    try
        exe 'Leaderf! gtags --auto-jump h --by-context --match-path'
        if &filetype ==# 'leaderf'
            nnoremap <buffer> <silent> <CR>          :call LeaderfSplit(1)<CR>
        else
            call LeaderfSplit(0)
        endif
    catch /.*/
        exe 'normal viw'
    endtry
endfunction

nnoremap <silent> <2-LeftMouse> :call LeaderfGtags()<CR>
```

有没有更好的方式了？

**Comment by Yggdroot** [comment]
这样有什么问题，你想要的更好方式指的是什么？

**Comment by bstaint** [comment]
比如--auto-jump的参数能不能指定窗口大小，位置。
还有指定--auto-jump参数之后，如果只有一个结果会分屏，如果多个结果的话参数就无效。

**Comment by Yggdroot** [comment]
你的这段脚本用起来挺好的呀。

> 比如--auto-jump的参数能不能指定窗口大小，位置。

这个你不是已经用resize调整高度了吗

> 还有指定--auto-jump参数之后，如果只有一个结果会分屏，如果多个结果的话参数就无效。

现在不就是这样的吗？

**Comment by bstaint** [comment]
好吧 谢谢解答。

**Comment by bstaint** [comment]
再请问下：
![QQ截图20191025110822](https://user-images.githubusercontent.com/5853792/67540400-cf8ddc80-f717-11e9-9973-eb021349353b.png)

这样的情况下，Enter和双击应该怎么处理。

**Comment by Yggdroot** [comment]
不明白你的问题。

**Comment by bstaint** [comment]
在normal模式下可以正常分屏，在input mode下似乎无法处理回车和双击打开的方式。

**Comment by Yggdroot** [comment]
确实是的。

**Comment by bstaint** [comment]
另外一个问题`Leaderf --recall`似乎不会执行--auto-jump跳转，只会显示`No Content!`

**Comment by Yggdroot** [comment]
`Leaderf --recall` 只是打开原来的界面，不会做动作。
