### ISSUE TITLE
feature: 修改g:Lf_ExternalCommand后，自动刷新结果

### ISSUE THREAD

**Issue by kdurant** [Yggdroot/LeaderF#377]
- [x] neovim
- [x] Windows

我想`LeaderfFile`可以提供两种结果
1. git目录下的所有文件
2. git跟踪的文件(`git ls-files`)

我使用了2个映射
```viml
let g:Lf_UseCache=0

map <space>fa      :let g:Lf_ExternalCommand = 'rg --files --no-ignore -g !.git "%s"'<cr>:LeaderfFile<cr>
map <space>fg      :let g:Lf_ExternalCommand = 'rg "%s" --files'<cr>:LeaderfFile<cr>
```
轮流使用这两个映射，必须使用F5刷新后，才能显示正确的结果
能不能提供个自动刷新的选项

**Comment by Yggdroot** [comment]
let g:Lf_UseMemoryCache = 0 试试。

**Comment by kdurant** [comment]
可以的，谢谢

**Comment by Yggdroot** [comment]
解释一下，`let g:Lf_UseMemoryCache = 0` 并不是会自动刷新，只是不在内存中做缓存，这样每次显示的结果都是命令的输出。
