### ISSUE TITLE
gtags error

### ISSUE THREAD

**Issue by kdurant** [Yggdroot/LeaderF#378]
- [x] neovim
- [x] windows

![QQ图片20191106084908](https://user-images.githubusercontent.com/2704364/68258669-6771bb80-0072-11ea-9623-0255e94f5813.png)

```viml
let g:Lf_GtagsAutoGenerate = 1
```
gtags已经在环境变量里了

不知道还需要提供那些额外的信息了

**Comment by Yggdroot** [comment]
有c:\Neovim\share\gtags.conf 这个文件吗？

**Comment by kdurant** [comment]
文档里不是说有默认选项，不需要设置吗？

我把https://github.com/sg2002/gtags.conf-tutorial/blob/master/gtags.conf 复制到`c:\Neovim\share\gtags\gtags.conf`文件里

出现了下面的错误
![QQ截图20191106122035](https://user-images.githubusercontent.com/2704364/68268158-11137580-0090-11ea-97bc-e9af80eb37d4.png)

**Comment by Yggdroot** [comment]
你手动 `Leaderf gtags --update`试一下。

**Comment by kdurant** [comment]
`Leaderf gtags --update`还是和上面一样的错误

**Comment by Yggdroot** [comment]
update这条命令报上面那个错吗？

**Comment by kdurant** [comment]
是的

**Comment by Yggdroot** [comment]
先 Leaderf gtags --remove
再 Leaderf gtags --update

**Comment by kdurant** [comment]
错误是没有了，但缓存目录下面是空的

**Comment by Yggdroot** [comment]
echo g:Lf_Debug_GtagsCmd 看看是什么？ 然后直接运行这个命令看看。

**Comment by kdurant** [comment]
`echo g:Lf_Debug_GtagsCmd`显示
```
cd /d "E:\work\SingleScan" && gtags -i --skip-symlink --gtagsconf C:\Neovim\share\gtags\gtags.conf --gtagslabel default "C:\home\.LfCache\gtags\E%work%SingleScan"
```
![QQ截图20191120110525](https://user-images.githubusercontent.com/2704364/69205718-b72da800-0b85-11ea-91a0-313426d40c34.png)

gtags 6.6.2版本没有`--skip-symlink `，要6.6.3版本才行，建议写到readme里

**Comment by Yggdroot** [comment]
这个错误在做Leaderf gtags --update的时候就会报出来，你执行Leaderf gtags --update没有错误吗？
