### ISSUE TITLE
[feature request] WindowHeight can be auto adjusted according to content

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#379]
### Expected behaviour
`Lf_WindowHeight` can be a max height value of window, but if there are just one or two line in the windows, it's better to auto adjust the window height to minimize it.

**Comment by Yggdroot** [comment]
If show the content in reverse order, the height can be auto adjusted.
If in regular order, the first line always is the best match, the focus of eyes should change the position  when the  window height changes, this is not a good experience.

**Comment by Yggdroot** [comment]
You can try the popup mode, the height can be auto-adjusted.

**Comment by xaljer** [comment]
OK, thank you~
