### ISSUE TITLE
Please add a tag for v1.00

### ISSUE THREAD

**Issue by johnzeng** [Yggdroot/LeaderF#38]
I understand that you are developing some awesome feature on a high version of vim. But I don't wanna compile a high version vim on my ubuntu 12.04 server, I can only get a version of `7.4.5` from `apt-get`, which is not enough to run LeaderF before. Could you make a tag for the latest version before `v1.01`? Like `v1.00` ? Before the commit that will require `7.4.33` ?

**Comment by Yggdroot** [comment]
[v1.01](https://github.com/Yggdroot/LeaderF/releases/tag/v1.01) is the last vesion that support vim7.4.229 or lower.

**Comment by johnzeng** [comment]
OK，thanks
