### ISSUE TITLE
Improve the experience of Leader gtags --all

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#380]
- vim or neovim? 
    - [ x ] vim
    - [ x ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Expected behaviour
I found that leaderf gtags --all need too long time to load in some big project. Is there some method to improve that? like cache results? can gtags output those tags by type like function or varible? Or can ctags do it better?
I think some times find a symbol in whole project is very useful when you don't familiar with the source code. thanks~

**Comment by Yggdroot** [comment]
Done.
