### ISSUE TITLE
在vimwiki中执行LeaderfTag，中文tag为乱码

### ISSUE THREAD

**Issue by ChenWeird** [Yggdroot/LeaderF#381]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  vim 8.1 (2018 May 18) MS-windows 32位图形界面版本，带OLE支持 包含补丁1  巨型版本
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python36.dll
- Output of `:py print(sys.version)`: 此命令不可用
- Output of `:py3 print(sys.version)`: 3.6.6 [MSC v.1900 32 bit (Intel)]
- Output of `:echo g:Lf_Debug_Cmd`:  nothing
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
   `Plug 'Yggdroot/LeaderF', { 'do': '.\install.bat' }`

### Describe your question, feature request, or bug.
vimwiki tag 中文部分乱码

### Steps to reproduce
" 1. 进入vimwiki
`<leader>ww`
" 进入LeaderfTag
`:LeaderfTag`

### Actual behaviour
Tag的中文部分出现乱码
### Expected behaviour
Tag的中文可以正常显示

**Comment by ChenWeird** [comment]
补充：vimwiki 的 tags 是vimwiki自己的命令```:VimwikiGenerateTags```生成的。

**Comment by ChenWeird** [comment]
Vimwiki uses a [CTAGS](http://docs.ctags.io/en/latest/) file to store tag information.

**Comment by Yggdroot** [comment]
还没时间看。

**Comment by Yggdroot** [comment]
能否提供一下生成的tags文件？

**Comment by ChenWeird** [comment]
tags文件已发您的gmail邮箱，请查收。

**Comment by ChenWeird** [comment]
太感谢了，已经没有乱码了。
但有了个新问题：缺少了两个tag，以及缺少一个tag对应的部分内容。它们都在tag文件的前几行：
```
Anki	Anki学习计划.wiki	1;"	vimwiki:Anki学习计划\tAnki学习计划
Anki	Simon's_Anki_学习计划.wiki	1;"	vimwiki:Simon's_Anki_学习计划\tSimon's_Anki_学习计划
Anki	Vim's_Anki_学习计划.wiki	1;"	vimwiki:Vim's_Anki_学习计划\tVim's_Anki_学习计划
Anki词库	小学英语500词.wiki	1;"	vimwiki:小学英语500词\t小学英语500词
CMD	Command-line_Dictionary.wiki	1;"	vimwiki:Command-line_Dictionary\tCommand-line_Dictionary
```

**Comment by Yggdroot** [comment]
为什么你的这个tags，前面只有一行
```
!_TAG_FILE_SORTED	1	
```
标准的tags前面应该有6行
```
!_TAG_FILE_FORMAT	2	/extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED	1	/0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR	Darren Hiebert	/dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME	Exuberant Ctags	//
!_TAG_PROGRAM_URL	http://ctags.sourceforge.net	/official site/
!_TAG_PROGRAM_VERSION	5.8	//
```

**Comment by ChenWeird** [comment]
vimwiki的tags机制好像就是这样，并非标准的格式

**Comment by Yggdroot** [comment]
给vimwiki开个issue，问问他为什么不是标准格式？

**Comment by Yggdroot** [comment]
少了5行是因为我从第6行开始读的。
