### ISSUE TITLE
建议：采用拼音首字母搜索中文

### ISSUE THREAD

**Issue by ChenWeird** [Yggdroot/LeaderF#383]
习惯使用Total Commander + QuickSearch eXtended，对于中英混合使用的情形，无需切换中文输入法等繁琐，只需直接使用拼音首字母和英文，即可快速实现搜索过滤，非常方便。

Total Commander的QuickSearch eXtended：https://www.ghisler.ch/board/viewtopic.php?t=22592

详情可查看上述链接下载中的说明文档tcmatch.pdf，也可直接访问该PDF文档：
https://onedrive.live.com/?cid=F8C4901FA2FB692E&id=F8C4901FA2FB692E%21332&parId=F8C4901FA2FB692E%21132&o=OneUp

**Comment by Yggdroot** [comment]
貌似工作量太大。
