### ISSUE TITLE
建议：Leaderf rg的结果加入quickfix，以便导航

### ISSUE THREAD

**Issue by ChenWeird** [Yggdroot/LeaderF#384]
在某个目录下全文搜索，之前一直习惯使用vimgrep，其最方便的地方在于：结合```Plug 'tpope/vim-unimpaired'```或自定义命令可以使用 ```]q``` 、 ```[q``` 等快速地在quickfix结果中进行切换导航。

采用全文搜索，有一种情景通常是：通过多个结果的对比参考，获得某种借鉴，其搜索目标并非仅仅是一个，而是多个，因此需要类似quickfix一样的来回切换导航功能。

若Leaderf可以在我们进入某个结果之后将搜索列表加入quickfix，或其他更好的机制，那就完美了。

说明：刚使用Leaderf，很强大，还在学习中，以上若已经有类似的实现，还请提醒指教，感谢！

**Comment by Yggdroot** [comment]
不知道你说的`类似quickfix一样的来回切换导航功能`是什么，Leaderf rg的功能肯定包含quickfix。

**Comment by ChenWeird** [comment]
就是使用快捷键命令在quickfix的多个搜索结果中进行切换，如Plug 'tpope/vim-unimpaired'定义了如下导航快捷键：

*[q*     |:cprevious|
*]q*     |:cnext|
*[Q*     |:cfirst|
*]Q*     |:clast|

**Comment by ChenWeird** [comment]
我现在使用Leaderf rg 进入某个结果之后，若需查看其它结果，都是笨笨的使用 Leaderf --recall进行切换，比较麻烦...  不知是否我的使用姿势不对？

**Comment by Yggdroot** [comment]
我没用过Plug 'tpope/vim-unimpaired'，搜了一下，你说的`]q 、 [q` 应该是对应的
`Leaderf rg --next, Leaderf rg --previous`.

**Comment by Yggdroot** [comment]
我没用过Plug 'tpope/vim-unimpaired'，搜了一下，你说的`]q 、 [q` 应该是对应的
`Leaderf rg --next, Leaderf rg --previous`.

**Comment by ChenWeird** [comment]
噢，那也就是我只要自定义一个自定义命令就可以了，太强大了！

**Comment by Yggdroot** [comment]
没有对应
[Q |:cfirst|
]Q |:clast|
的功能。

**Comment by ChenWeird** [comment]
有next previous就已经够用了
