### ISSUE TITLE
"Press ENTER or type command to continue" is prompted everytime when a LeaderF command is pressed.

### ISSUE THREAD

**Issue by iintothewind** [Yggdroot/LeaderF#385]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 

```
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/config -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-13403-1or2rj3/neovim-0.4.3/build/include
编译者 brew@Mojave.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```

- Output of `:echo has("python")`: 
1

- Output of `:echo has("python3")`: 
1

- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
```
2.7.17 (default, Oct 24 2019, 12:57:47)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]
```
- Output of `:py3 print(sys.version)`: 
```
3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
" leaderf
let g:Lf_ShortcutF = '<F11>'

" LargeFile
let g:LargeFile = 2
"nmap <silent> <F11> :<C-U>LeaderfFile<CR>
nmap <silent> <F12> :LeaderfMru<CR>
let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git', '.idea', '.iml']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
let g:Lf_ShowRelativePath = 1
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'airline'
let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}
let g:Lf_WildIgnore = {
  \ 'dir': ['.svn','.git','.hg', '.idea', '.vscode'],
  \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]', '*.class', '*.DS_Store', '*.jar']
  \}
let g:Lf_CommandMap = {
  \ '<CR>': ['<C-B>'],
  \ '<C-T>': ['<CR>']
  \}

```

### Describe your question, feature request, or bug.
This issue only occurs in Neovim.
Everytime when I open LeaderF file list and try to open a new tab for a file, the message: "Press ENTER or type command to continue"  poped up. I have to click Enter key, the file then can be opened in a new tab.
This is pretty annoying, but the message "Press ENTER or type command to continue" never shows up when I was using vim.
Not sure what is the difference between vim or neovim for the settings.

### Steps to reproduce
- open any text file in neovim and open LeaderF file list
- then try to execute any action LeaderF command
- The message "Press ENTER or type command to continue" will popup

### Actual behaviour
I have to click Enter key everytime before a LeaderF command can be exectued.

### Expected behaviour
The message "Press ENTER or type command to continue" should not show up.
And the extra Enter key is not required on neovim before the command is executed.

**Comment by Yggdroot** [comment]
I can not reproduce this issue, please remove your other plugins and have a try.

**Comment by Yggdroot** [comment]
This issue seems the same as https://github.com/neovim/neovim/issues/8380. But the issue has been fix long time ago.
