### ISSUE TITLE
很奇怪的错误，希望能提供一点帮助

### ISSUE THREAD

**Issue by kdurant** [Yggdroot/LeaderF#388]
```viml
map <space>fa      :let g:Lf_ExternalCommand = 'rg --files --no-ignore -g !.git "%s"'<cr>:LeaderfFile<cr>
```
这个map一直用的好好的，某天在一台win10的机器上出现了下面提示
![QQ截图20191112093216](https://user-images.githubusercontent.com/2704364/68634186-89b28000-052f-11ea-9795-d8a29b4785b0.png)
另一台win10的机器上没有任何问题，所以可能不是leaderf本身的问题
希望可以提供一点线索，我自己去找找

**Comment by Yggdroot** [comment]
这好像是访问权限的问题。C:\\home 没有权限访问。

**Comment by kdurant** [comment]
python 的访问权限被限制了？

**Comment by Yggdroot** [comment]
`echom g:Lf_Debug_Cmd` 输出是什么？

**Comment by kdurant** [comment]
`rg ""."" --files`

**Comment by Yggdroot** [comment]
加上`--no-messages`试试。

**Comment by kdurant** [comment]
谢谢你，可以的
