### ISSUE TITLE
使用过 LeaderF 之后窗口大小会复位

### ISSUE THREAD

**Issue by WoodyGuo** [Yggdroot/LeaderF#391]
启动 mvim，打开一个文件，然后 :split 分成俩窗口，然后调整俩窗口大小为三七开（具体比例不重要），再使用 LeaderF 查文件或者 buffer，按 esc，q 退出，这时候俩窗口大小会恢复成五五开。

**Comment by Yggdroot** [comment]
复现不了。

**Comment by WoodyGuo** [comment]
我录了个屏你看看看
https://youtu.be/WK7XOF92g6I

**Comment by Yggdroot** [comment]
你能换个环境试一下吗，或者把你其他的插件都禁掉。

**Comment by WoodyGuo** [comment]
我发现有种情况下必现，就是在全屏或非全屏状态下，split 窗口，使用一次 LeaderF，然后切换到非全屏或全屏显示，再使用 LeaderF 就会出现此问题。

**Comment by WoodyGuo** [comment]
我禁掉了其他所有插件只留下 LeaderF，发现按以上步骤使用时确实会有此问题。

**Comment by Yggdroot** [comment]
复现了，只有在窗口切换到非全屏或全屏显示再切回来，然后再调用LeaderF才会出现。

**Comment by waruqi** [comment]
我这里也有这个问题，尝试升级到master版本，win分割问题没了，但是上下方向建选择似乎没法选择列表项了 = =

**Comment by Yggdroot** [comment]
现在可以使用popup模式，这个问题也不复存在了。
