### ISSUE TITLE
error while press <esc> in normal mode.

### ISSUE THREAD

**Issue by TheBigFish** [Yggdroot/LeaderF#392]
Errors while press esc in normal mode.
Thanks.

![捕获](https://user-images.githubusercontent.com/10334759/68736311-3f0e3200-061b-11ea-935e-fd557e222592.PNG)

**Comment by Yggdroot** [comment]
What is the exact steps to reproduce?

**Comment by TheBigFish** [comment]
Cursor in blank area(no word) then press esc.

**Comment by Yggdroot** [comment]
can you describe the steps so that even a newbie can reproduce it following the steps.

**Comment by TheBigFish** [comment]
I test the key map and find I make a mistake to noremap the key to call "Leaderf! gtags -d %s --auto-jump".
Sorry and thank you!
