### ISSUE TITLE
g:Lf_Extensions使用问题

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#393]
我尝试用g:Lf_Extensions来给gtags加个after_exit，似乎不能定义内置已经有的，不然会出现重复，并且会覆盖自带的：
![QQ截图20191115121102](https://user-images.githubusercontent.com/5853792/68916480-0d26d800-07a1-11ea-85cf-67640d4f7360.png)

```
function! s:test_after_exit(args)
    echom "sadfadsf"
endfunction

let g:Lf_Extensions = {
    \ 'gtags': {
    \ 'after_exit' : function("s:test_after_exit")
    \ }
\ }
```

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/issues/144#issuecomment-540008950
跟以前有点变化，再看一下吧

**Comment by bstaint** [comment]
我的意思是只给gtags加个after_exit，而不是自己定义个新的。

**Comment by Yggdroot** [comment]
对，使用let g:Lf_Extensions 只能定义新的。

**Comment by bstaint** [comment]
有什么办法可以实现么。

**Comment by Yggdroot** [comment]
现在没什么办法，除非直接改源码。

**Comment by bstaint** [comment]
哦，谢了
