### ISSUE TITLE
自定义Lf_RootMarkers，并把默认的.git去掉，貌似无效？

### ISSUE THREAD

**Issue by UKeeySDis** [Yggdroot/LeaderF#395]
### 背景
多个项目，彼此都有`.git`，但查文件的时候想跨项目进行模糊匹配
### 过程
1. 把.vimrc中的`Lf_RootMarkers`加上自己定义的文件，并把`.git`去掉。
2. 修改.vim插件中的`LeaderF/autoload/leaderf.vim`文件。把`call s:InitVar('g:Lf_RootMarkers', ['git','.hg', '.svn'])`中的`.git`去掉。把`call s:InitVar('g:Lf_UseMemoryCache', 1)`置0。
3. 把缓存文件`.LfCache`删掉
### 结果
重新查找文件，还是依据了`.git`作为工作目录。请教下，我是哪里改漏了吗？

**Comment by Yggdroot** [comment]
默认情况会根据cwd查找，不知道你说的现象是什么，期望是什么？

**Comment by UKeeySDis** [comment]
> 默认情况会根据cwd查找，不知道你说的现象是什么，期望是什么？

期望大概是这样，现在我有A、B、C三个项目，每个项目都有`.git`，我在项目A目录的时候，执行`LeaderfFile`，希望能查询到项目B、C的文件。

按照规则，我需要自定义一个文件作为A、B、C的上级目录设置为`Lf_RootMarkers `。我按照上述我描述的步骤进行了修改，但是最后的结果还是以`git`作为工作目录。所以想请教下，应该怎么才能把默认的工作目录(`.git`、`.hg`、`.svn`)移除掉？

**Comment by Yggdroot** [comment]
你可能需要设一下`let g:Lf_WorkingDirectoryMode ='a'`, 不设的话，默认是当前目录作为cwd，也就是A的目录。

**Comment by UKeeySDis** [comment]
>你可能需要设一下let g:Lf_WorkingDirectoryMode ='a', 不设的话，默认是当前目录作为cwd，也就是A的目录。

感谢，我设置了`let g:Lf_WorkingDirectoryMode ='a'`之后，显示的`FullPath`确实是A、B、C的上级目录了。

但是又有一个新问题是：A、B、C这三个目录并没有展开，也就是搜索不到A、B、C里面的文件，`LeaderfFile `只能看到A、B、C的目录名。

**Comment by Yggdroot** [comment]
复现不了。
`echo g:Lf_Debug_Cmd`输出是什么？

**Comment by UKeeySDis** [comment]
未定义。 `Undefined variable: g:Lf_Debug_Cmd`。
我刚才尝试新建了3个目录，可以正常展开，确实复现不了我现在的问题。
初步怀疑是memory cache的问题或者文件数过多（5w+）。

**Comment by UKeeySDis** [comment]
这里怀疑是memory cache的原因是因为A、B、C目录有`.git`，同一级的目录D没有，目录D可以正常展开，但是A、B、C不行。

**Comment by Yggdroot** [comment]
执行LeaderfFile后再echo

**Comment by UKeeySDis** [comment]
`git ls-files  "/home/uks/project" && git ls-files --others --exclude-standard  "/home/uks/project"`

**Comment by UKeeySDis** [comment]
解释下，`/home/uks/project`就是A、B、C的父目录，LeaderfFile是我在A目录中执行的。

**Comment by Yggdroot** [comment]
你直接执行这条命令试试，leaderf只是读的它的输出。

**Comment by UKeeySDis** [comment]
出错了。`fatal: '/home/uks/project' is outside repository`。

**Comment by UKeeySDis** [comment]
leaderf只是读这条命令的输出，那意思是无论怎么样，我还是必须依赖`.git`作为工作目录吗？因为这条命令就是git的

**Comment by Yggdroot** [comment]
是因为你的当前目录是git目录，所以leaderf选择使用git。你可以设置不使用，还可以自定义命令。

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/73a158b0047d9b30e36906ae742e92ebd52830fb/doc/leaderf.txt#L373-L405

**Comment by UKeeySDis** [comment]
好的，明白了，我修改了相关py文件，已经满足我的要求了，感谢。

**Comment by Yggdroot** [comment]
不用修改代码吧，把g:Lf_UseVersionControlTool设为0应该就可以了。

**Comment by UKeeySDis** [comment]
的确，直接设置Lf_UseVersionControlTool为0也可以。
