### ISSUE TITLE
请教：Leaderf rg <PATH> 具体如何使用？

### ISSUE THREAD

**Issue by ChenWeird** [Yggdroot/LeaderF#396]
我希望在任意目录，可以查询某个特定路径下的某个文件资料（可能在非工作目录下）。
查阅了Leaderf rg -h，看到其中有`[<PATH>[<PATH> ... ]]`，好像可以解决问题。

以下是我之前的方案，用-g，在工作目录下过滤，可以使用，但前提是somedoc.xyz在工作目录下，不是特别方便：
`nnoremap <leader>k vy:Leaderf rg -g somedoc.xyz <C-r>0<CR>`

若为somedoc.xyz指定路径如下，则总是出错，不知道该如何使用，特求助：
`nnoremap <leader>k vy:Leaderf rg path/to/somedoc.xyz <C-r>0<CR>`

不知道与这个问题是否相关： https://github.com/Yggdroot/LeaderF/issues/374

**Comment by Yggdroot** [comment]
你用Leaderf rg -e xxx path

**Comment by ChenWeird** [comment]
按照你的方法解决了，感谢！
