### ISSUE TITLE
Leaderf function --popup Lf_hi_cursorline highlight

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#398]
`Leaderf function --popup`

Lf_hi_cursorline只高亮了个括号：
![QQ截图20191119195810](https://user-images.githubusercontent.com/5853792/69144771-126c8580-0b07-11ea-9a3e-bbe27d741dd8.png)

**Comment by Yggdroot** [comment]
就是这样的，我不知道要不要把当前行的颜色覆盖掉，因为还有cursorline，就选择不覆盖。

**Comment by Yggdroot** [comment]
你这个图好奇怪，怎么也没有cursorline，有没有行号？

**Comment by bstaint** [comment]
行号我去掉了，下面是我设置：
`hi link Lf_hl_cursorline Underlined`
会比较丑，应该怎么处理：

![QQ截图20191119201119](https://user-images.githubusercontent.com/5853792/69145555-dfc38c80-0b08-11ea-9542-243ccc8eb9cb.png)

**Comment by Yggdroot** [comment]
没法设置，只能修改代码

**Comment by bstaint** [comment]
哦，另外能不能提供吧leaderf结果导入到quickfix中的功能，这样可以用cdo命令做批量替换之类的操作。

**Comment by bstaint** [comment]
另外你说我没有cursorline，应该是我用的主题没有设置CursorLine，不设置的话popup下不显示，但是在buffer中可以正常显示。

**Comment by Yggdroot** [comment]
应该是cursorline的颜色正好跟背景色很接近。
