### ISSUE TITLE
Windows fuzzyEngine APPCRASH

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#401]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1.2317
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): python37.dll
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 14 2019, 23:09:19) [MSC v.1916 32 bit (Intel)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
    let g:Lf_Gtagslabel = 'native-pygments'
    let g:Lf_GtagsSkipUnreadable = 1
```

### Describe your question, feature request, or bug.
源码：
https://github.com/mltframework/shotcut/tree/master/src/qml/filters/webvfx_threejs_text/fonts

执行`Leaderf gtags --auto-jump --match-path -g main` 之后输入`.`就会崩溃，截图：

![QQ截图20191120133855](https://user-images.githubusercontent.com/5853792/69212065-23ff6d00-0b9b-11ea-8d77-60c884dd82ba.png)

**Comment by Yggdroot** [comment]
复现不了。你的c扩展是怎么编的？

**Comment by bstaint** [comment]
vs2019 用自带的批处理编译的，我又尝试了下：

https://github.com/mltframework/shotcut/tree/master/src/qml/filters/webvfx_threejs_text/fonts/gentilis_bold.typeface.js

直接打开文件，然后`Leaderf line`输入`.`，就会崩溃。

**Comment by Yggdroot** [comment]
复现了，我看一下。

**Comment by Yggdroot** [comment]
原因找到了，我用uint16_t表示一个字符串的长度，而这个文件一行的长度有648477。

**Comment by bstaint** [comment]
哦 建议内容太长的话截断省略，应该没啥影响。

**Comment by Yggdroot** [comment]
修复了，需重新编译一下C扩展。

**Comment by bstaint** [comment]
没问题了。
