### ISSUE TITLE
链接目录中的文件不能识别 

### ISSUE THREAD

**Issue by chiplua** [Yggdroot/LeaderF#404]
YES

- vim or neovim? 
    - [X ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.1 macos version
- Output of `:echo has("python")`:0 
- Output of `:echo has("python3")`:1 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`:3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] 
- Output of `:echo g:Lf_Debug_Cmd`: git ls-files "." && git ls-files --others --ecclude-standard "."
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
map <leader>1 :LeaderfBuffer<CR>
map <leader>2 :LeaderfFunction<CR>
map <leader>3 :LeaderfFile<CR>
" map <leader>3 :LeaderfFile --no-ignore<CR>
map <leader>4 :LeaderfLine<CR>
map <leader>5 :LeaderfMru<CR>

### Describe your question, feature request, or bug.
LeaderfFile模式下，不显示链接目录下的文件:
1.ls ~/test1
   A.java
2.ln -s ~/test1 ~/test2
3.cd ~/test2
4.vim .
5.<leader>3 不能显示A.java 
### Steps to reproduce
同上
### Actual behaviour
不显示A.java
### Expected behaviour
能够显示链接目录下的文件

**Comment by Yggdroot** [comment]
`let g:Lf_FollowLinks = 1`

**Comment by chiplua** [comment]
谢谢您的回复。
还是不能识别哦，跟之前一样。由于test2是一个链接文件夹， LeaderF把src识别成文件了，无法识别里面的文件。

**Comment by chiplua** [comment]
g:Lf_FollowLinks                                *g:Lf_FollowLinks*
    Whether to visit directories pointed to by symlinks when indexing.
    0 - no
    1 - yes
    Default value is 0.
设置为1，不起作用

**Comment by chiplua** [comment]
按照我上述的步骤创建链接，可以识别A.java
如果test1有很多级子目录，test2中就不能识别了

**Comment by Yggdroot** [comment]
let g:Lf_UseVersionControlTool = 0
g:Lf_FollowLinks不用设了，跟它没关系。

**Comment by chiplua** [comment]
谢谢

**Comment by ruleizhou** [comment]
同样存在这个问题，请问有解决方法嘛

**Comment by Yggdroot** [comment]
> 同样存在这个问题，请问有解决方法嘛

上面不是有解决方法吗

**Comment by Yggdroot** [comment]
echo g:Lf_Debug_Cmd输出是什么

**Comment by ruleizhou** [comment]
rg --no-messages --files --color never -L

**Comment by Yggdroot** [comment]
let g:Lf_FollowLinks = 1 这个没用吗

**Comment by Yggdroot** [comment]
按f5刷新一下看看

**Comment by ruleizhou** [comment]
这个设置还是无效果

**Comment by ruleizhou** [comment]
在leaderffile 中无法识别到链接目录中的文件

**Comment by Yggdroot** [comment]
> rg --no-messages --files --color never -L

直接命令行执行这条命令呢？

**Comment by ruleizhou** [comment]
vim 命令行内无法执行  终端执行？

**Comment by Yggdroot** [comment]
是看看这条命令输出有没有，如果有，leaderf也肯定会有，没有就f5刷新一下结果。如果没有，就怪不到leaderf了。我能想到的这条命令输出没有链接目录只有一个可能，链接目录在.gitignore里了。

**Comment by Yggdroot** [comment]
> vim 命令行内无法执行 终端执行？

终端执行。

**Comment by ruleizhou** [comment]
找到原因了  链接目录+.gitignore 导致的，let g:Lf_FollowLinks = 1 let g:Lf_UseVersionControlTool = 0 用这个两个命令 在使用leaderf file --no-ignore 就可以了

**Comment by ruleizhou** [comment]
感谢

**Comment by ruleizhou** [comment]
请教下 有什么方法可以禁用.gitignore 中的设置

**Comment by ruleizhou** [comment]
如果链接目录的上层目录中的gitignore 中有指定链接目录 上面的设置后还是无法找到链接目录中的文件  这个有方法解决嘛

**Comment by Yggdroot** [comment]
想不通的一点是既然放到.gitignore里，为什么还想要列出来，列出来为什么还要ignore。
Leaderf file --no-ignore就可以呀。

**Comment by ruleizhou** [comment]
gitignore 是想在提交code 的时候忽略这部分code ，但是我们用vim 阅读源码的时候有需要了解这部分code，

**Comment by ruleizhou** [comment]
在请教一个问题 Leaderf file --no-ignore 可以将gitignore中的文件显示出来，gitignore中的目录则无效  这个有什么方案嘛

**Comment by Yggdroot** [comment]
能举个例子吗？

**Comment by ooing** [comment]
@Yggdroot   可以关闭 ignore吗 虽然是加入.ignore  但是需要去看源码

**Comment by Yggdroot** [comment]
Leaderf file --no-ignore

**Comment by Yggdroot** [comment]
> @Yggdroot 可以关闭 ignore吗 虽然是加入.ignore 但是需要去看源码

Leaderf file --no-ignore

**Comment by ooing** [comment]
@Yggdroot   抱歉我没说清楚，我想直接加入配置，默认是关闭的

**Comment by ooing** [comment]
nnoremap <silent> <C-p> :Leaderf file  --no-ignore<CR>

**Comment by ooing** [comment]
nnoremap <silent> <C-p> :Leaderf file  --no-ignore  --auto-preview<CR>

**Comment by jhbdream** [comment]
> 
比如一些编译中间文件 比如 反汇编等，有时候调试需要查看 。 但是并不加入到版本控制里跟踪
