### ISSUE TITLE
Running Leaderf file twice leads to error: module fuzzyEngine has no attribute guessMatch

### ISSUE THREAD

**Issue by jdhao** [Yggdroot/LeaderF#405]
I see issue #367 reports the same error but the cause may be different. I am using the latest version of leaderf.

- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.5.0-1ff5b60cb
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191118-2246-wrknjv/build/config -I/tmp/neovim-20191118-2246-wrknjv/src -I/usr/local/include -I/tmp/neovim-20191118-2246-wrknjv/deps-build/include -I/usr/local/opt/gettext/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191118-2246-wrknjv/build/src/nvim/auto -I/tmp/neovim-20191118-2246-wrknjv/build/include
Compiled by jdhao@jdhao-MBP.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-1ff5b60/share/nvim"

Run :checkhealth for more info
```

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:py3 print(sys.version)`: 
```
3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
```
- Output of `:echo g:Lf_Debug_Cmd`:  
Immediately after I open Neovim, when I use the above command, I see:
> Undefined variable: g:Lf_Debug_Cmd

Only after I run the `:Leaderf file` command once, I can see the variable being set to  `rg --no-messages --files --color never`.

- Output of `:echo g:Lf_FilesFromCache`:  
Immediately after I open Neovim, when I use the above command, I see:
> Undefined variable: g:Lf_FilesFromCache

Only after I run the `:Leaderf file` command once, I can see the variable being set to 1.

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
No custom config for LeaderF. Just installed it.

### Describe your question, feature request, or bug.

I see the following error when I run `:Leaderf file` command the second time inside Neovim. I should emphasize that the first time I run this command, everything is OK. The error happens on second time. The error message is:

```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3:
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 758, in start
    the_args.start(arguments, *args, **kwargs)

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 701, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1954, in startExplorer
    self.input()

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 59, in deco
    func(self, *args, **kwargs)

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2219, in input
    self._guessSearch(self._content)

  File "/Users/jdhao/.local/share/nvim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1285, in _guessSearch
    filter_method = partial(fuzzyEngine.guessMatch, engine=self._fuzzy_engine, filename=filename,

AttributeError: module 'fuzzyEngine' has no attribute 'guessMatch'
```

### Steps to reproduce

+ Open neovim with the following minimum config (`nvim -u init.vim`):

```
let s:PLUGIN_HOME=expand('~/.local/share/nvim/plugged')

call plug#begin(s:PLUGIN_HOME)
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
call plug#end()
```

+ Run `:Leaderf file` command the first time. Everything is fine.
+ Run `:Leader file` again. The above error occurs.

### Actual behaviour

The error occurs the second time I use `:Leaderf file`. Note that `:Leaderf colorscheme`, `:Leaderf mru` etc. still work without any erors. It seems that only `:Leaderf file` fails.

### Expected behaviour

No error occurs what so ever.

**Comment by Yggdroot** [comment]
Have you tried the solution of #367 ?

**Comment by jdhao** [comment]
I have set up vim-plug to run the post-install hook. But to ensure I have not missed anything,  I have tried to go to the directory of Leaderf and run `./install.sh` manually. It shows the following message:

```
Begin to compile C extension of Python2 ...
running build
running build_ext

=================================================
^_^ C extension of Python2 installed sucessfully!
=================================================

Begin to compile C extension of Python3 ...
running build
running build_ext

=================================================
^_^ C extension of Python3 installed sucessfully!
=================================================
```

**Comment by Yggdroot** [comment]
If so, I don't think the issue still exists.

**Comment by jdhao** [comment]
But it does exist after I run the above command. I looked at your `install.sh` script and found that it is using `python3` command to run the setup.py to compile the c source files.  I suspect this issue may be the mismatch between python3 used by Neovim and python3 used to compile the c code.

`which python3` shows that `/usr/local/bin/python3` is used. But Neovim is using python (which is python 3 by default) command provided by Anaconda. I changed the system `PATH` variable to make sure that `python3` command provided by Anaconda is used.  After that, I recompiled the Leaderf  extensions.  The output is like the following

```
Begin to compile C extension of Python2 ...
running build
running build_ext

=================================================
^_^ C extension of Python2 installed sucessfully!
=================================================

Begin to compile C extension of Python3 ...
running build
running build_ext
building 'fuzzyMatchC' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jdhao/anaconda3/include -arch x86_64 -I/Users/jdhao/anaconda3/include -arch x86_64 -I/Users/jdhao/anaconda3/include/python3.7m -c fuzzyMatch.c -o build/temp.macosx-10.7-x86_64-3.7/fuzzyMatch.o
gcc -bundle -undefined dynamic_lookup -L/Users/jdhao/anaconda3/lib -arch x86_64 -L/Users/jdhao/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/fuzzyMatch.o -o build/lib.macosx-10.7-x86_64-3.7/fuzzyMatchC.cpython-37m-darwin.so
building 'fuzzyEngine' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jdhao/anaconda3/include -arch x86_64 -I/Users/jdhao/anaconda3/include -arch x86_64 -I/Users/jdhao/anaconda3/include/python3.7m -c fuzzyMatch.c -o build/temp.macosx-10.7-x86_64-3.7/fuzzyMatch.o
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/jdhao/anaconda3/include -arch x86_64 -I/Users/jdhao/anaconda3/include -arch x86_64 -I/Users/jdhao/anaconda3/include/python3.7m -c fuzzyEngine.c -o build/temp.macosx-10.7-x86_64-3.7/fuzzyEngine.o
gcc -bundle -undefined dynamic_lookup -L/Users/jdhao/anaconda3/lib -arch x86_64 -L/Users/jdhao/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/fuzzyMatch.o build/temp.macosx-10.7-x86_64-3.7/fuzzyEngine.o -o build/lib.macosx-10.7-x86_64-3.7/fuzzyEngine.cpython-37m-darwin.so

=================================================
^_^ C extension of Python3 installed sucessfully!
=================================================
```

This time, I do not see errors any more no matter how many times I have run the `:Leaderf file` command.

**Comment by Yggdroot** [comment]
So now it is resolved?

Let me explain why the first time was OK while the second time got an error.
`guessMatch` is a feature that try to "guess" the best match of files according to the current buffer name if you have not typed any searching character. The fist time, your current buffer name must be a no name buffer, so it does not run into the logic of `guessMatch`, however the second will run into the logic.

**Comment by jdhao** [comment]
Yes, it is resolved.
