### ISSUE TITLE
A small bug related with a variable of YCM

### ISSUE THREAD

**Issue by leoatchina** [Yggdroot/LeaderF#408]
- leaderf version: latest with --popup
- os: macOS 10.14.6
- vim or neovim? 
    - [x] vim 
    - [ ] neovim
- Output of `vim --version` :   git you the important informations of my config
```
'version': 'vim-8.1.2152', 
'dir_tool': 'defx', 
'complete_engine': 'YCM', 
'gtags_generator': 'gutentags_plus_LeaderF', 
'colors': 'cosmic_latte', 
'tags_browser': 'vista', 
'snippet': 'ultisnips', 
'syntax': 'ale', 
'code_finder': 'Leaderf',   
'python': 3.75, 
'fuzzy_finder': 'LeaderF'
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:py print(sys.version)`:   not work
- Output of `:py3 print(sys.version)`:   3.7.5 (default, Nov  1 2019, 02:16:32) [Clang 11.0.0 (clang-1100.0.33.8)

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:  Not leaderf config, but a YCM variable
  let g:ycm_seed_identifiers_with_syntax  = 1 
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taotao/.vim/plug/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 758, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/taotao/.vim/plug/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 701, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/taotao/.vim/plug/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1917, in startExplorer
    self._getInstance().enterBuffer(win_pos)
  File "/Users/taotao/.vim/plug/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 870, in enterBuffer
    self._createPopupWindow()
  File "/Users/taotao/.vim/plug/LeaderF/autoload/leaderf/python/leaderf/instance.py", line 477, in _createPopupWindow
    lfCmd("call win_execute(%d, 'setlocal filetype=leaderf')" % self._popup_winid)
vim.error: Vim(py3):vim.error: Vim(redir):E930: Cannot use :redir inside execute()
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
```

### I used 3 ways to deal with this bug
- 1st 
Do leaderf without --popup at first,  then with --popup, worked
- 2nd
Cd into leaderf path, find instance.py, delete 4 lines like `setlocal filetype=leaderf`, worked but the popup window looked strange
- 3rd
  let g:ycm_seed_identifiers_with_syntax  = 0  

It is not a big bug, I can still write script with YCM.

### More information
When I use deoplete/asyncomplete with leaderf ,  this bug not happened

**Comment by Yggdroot** [comment]
I think this is accturally a YCM bug or conflict with YCM, LeaderF does not use `:redir` at all.
I guess it is because `setlocal filetype=leaderf` triggers autocmds, the autocmds defined in ycm have used the `:redir`.

**Comment by Yggdroot** [comment]
Maybe the root cause is here:

https://github.com/ycm-core/YouCompleteMe/blob/a7fd70cf7213c75088a47967c3e28aa4f6c47872/python/ycm/vimsupport.py#L200-L207

**Comment by Yggdroot** [comment]
I am not very farmilar with YCM, do you know how to disable it in a buffer?

**Comment by Yggdroot** [comment]
Have a try
```vim
let g:ycm_filetype_specific_completion_to_disable = {
        \ 'leaderf': 1
        \}
```

**Comment by leoatchina** [comment]
Not works , but your advice remind me another variable in YCM, that Works when still

`let g:ycm_seed_identifiers_with_syntax = 1`
```
let g:ycm_filetype_blacklist = {
            \ 'tagbar' : 1,
            \ 'leaderf': 1,
            \ 'defx': 1,
            \ 'gitcommit': 1,
            \ 'nerdtree' : 1,
        \ }
```

**Comment by bstaletic** [comment]
For posterity, YCM will add `leaderf` to "blacklisted by default" filetypes in ycm-core/YouCompleteMe#3545.

**Comment by Yggdroot** [comment]
> For posterity, YCM will add `leaderf` to "blacklisted by default" filetypes in [ycm-core/YouCompleteMe#3545](https://github.com/ycm-core/YouCompleteMe/pull/3545).

Thanks.
