### ISSUE TITLE
High cup usage.

### ISSUE THREAD

**Issue by wsdjeg** [Yggdroot/LeaderF#41]
![2017-03-17-22 45 38](https://cloud.githubusercontent.com/assets/13142418/24048434/d7ead7a4-0b63-11e7-9d46-ebf95800a50b.png)

**Comment by wsdjeg** [comment]
最近我在测试这个插件，发现neovim下使用的时候cpu占用非常大，不知道是不是内部匹配算法出了点问题。

**Comment by Yggdroot** [comment]
Thank you.
