### ISSUE TITLE
centos 有默认的python,为什么还报错

### ISSUE THREAD

**Issue by thisloving** [Yggdroot/LeaderF#414]
[root@izbp1goz1ulmtus2vec80fz LeaderF]# python3
Python 3.6.8 (default, Aug  7 2019, 17:28:10) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[root@izbp1goz1ulmtus2vec80fz LeaderF]# ./install.sh 
Begin to compile C extension of Python2 ...
running build
running build_ext
building 'fuzzyMatchC' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c fuzzyMatch.c -o build/temp.linux-x86_64-2.7/fuzzyMatch.o
fuzzyMatch.c:17:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^

**Comment by Yggdroot** [comment]
This issue is not specific to LeaderF, please refer to https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory/21530768.
