### ISSUE TITLE
remove number in popup 

### ISSUE THREAD

**Issue by pchampio** [Yggdroot/LeaderF#415]
I'll like to remove the number in the popup window:
![](https://i.imgur.com/37SUEZF.png)

https://github.com/Yggdroot/LeaderF/blob/f663dc9aff7d3d282164df8f6429ab3535affc75/autoload/leaderf/python/leaderf/instance.py#L278-L286

but:
https://github.com/Yggdroot/LeaderF/blob/f663dc9aff7d3d282164df8f6429ab3535affc75/autoload/leaderf/python/leaderf/instance.py#L695-L696

Do we need another option or is `        if self._reverse_order and "--popup" in self._arguments or lfEval("g:Lf_WindowPosition") == 'popup':` enough?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/f663dc9aff7d3d282164df8f6429ab3535affc75/autoload/leaderf/python/leaderf/instance.py#L278-L286 is enough for nvim. 
https://github.com/Yggdroot/LeaderF/blob/f663dc9aff7d3d282164df8f6429ab3535affc75/autoload/leaderf/python/leaderf/instance.py#L476 for vim. 
I don't plan to remove line number,if you want to do so, you can change the code by yourself.

**Comment by pchampio** [comment]
Okay thanks
