### ISSUE TITLE
Preview mode when collapsed

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#417]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim

- Operating system: 
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.

Hi,

I set Lf_PreviewResult to 1 on Lines. 

Suppose I search for a term, and I navigate through the matching lines( LeaderfLine), expecting to see the current line in the right context in the original file(I don't remember if I had to code something for this to display the preview automatically, think not). If the line is happened to be part of a collapsed section, instead all I see is the section header suggestive of a collapsed section. 
 
It causes the preview to be useless in this case. 

Thanks.
![image](https://user-images.githubusercontent.com/23480511/70097849-0a4a3500-1633-11ea-9e1b-b05133e4f778.png)

**Comment by Yggdroot** [comment]
Sorry, I don't understand what you mean, could you describe in more detail?

**Comment by eyalk5** [comment]
Yes, really not clear(written from phone but still). Fixed in the original post.

**Comment by Yggdroot** [comment]
Please set `let g:Lf_PreviewInPopup = 1`, so that you can use popup window to preview.

**Comment by eyalk5** [comment]
While it is better to have it in the popup window, the issue persists.

**Comment by Yggdroot** [comment]
The issue has been fixed.

**Comment by eyalk5** [comment]
Thanks. It is indeed solved in regular mode, but persist in preview-popup mode.

**Comment by Yggdroot** [comment]
Why are the codes all folded? what setup caused this?

**Comment by eyalk5** [comment]
```
source ~/.vim/autoload/plug.vim

call plug#begin('~/.vim/plugged')
	Plug 'tmhedberg/SimpylFold'
call plug#end()
```
Now, open any python file with functions.

**Comment by Yggdroot** [comment]
> ```
> source ~/.vim/autoload/plug.vim
> 
> call plug#begin('~/.vim/plugged')
> 	Plug 'tmhedberg/SimpylFold'
> call plug#end()
> ```
> 
> Now, open any python file with functions(you would need leaderf too :) ).

This plugin does not work for me.

**Comment by eyalk5** [comment]
Sorry, I haven't noticed.  
There is a simple solution that doesn't require plugin.
open a new file. 
Do `:set foldmethod=manual`
Pick some lines in  <shift-v> and do `zf`. It will create a fold.
now search for something inside the fold using LeaderFLine with preview set to popup.
