### ISSUE TITLE
怎么才能shift+insert把剪切板中的数据粘贴到输入区？

### ISSUE THREAD

**Issue by gaofei1982** [Yggdroot/LeaderF#418]
- vim or neovim? 
    - [1] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  4 2019 15:07:30)

- Output of `:echo has("python")`: 
1
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
libpython2.7.so.1.0
- Operating system: 
    - [1] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
shift+insert只能输入第一个字符

**Comment by Yggdroot** [comment]
用ctrl-v试试。

**Comment by gaofei1982** [comment]
用的是putty远程使用vim。C+V粘贴的是yank复制的内容，不是剪切板中的内容。

**Comment by Yggdroot** [comment]
我用xshell没问题，甚至shift-insert也没问题

**Comment by wugj00** [comment]
我也遇到这个问题，iterm2编辑器，远程到linux使用vim。有解决方案啊
