### ISSUE TITLE
一些使用建议

### ISSUE THREAD

**Issue by wsdjeg** [Yggdroot/LeaderF#42]
### 循环监控输入不该被关闭

使用过程中发现，这个插件不同与ctrlp，和denite相似，监控用户输入字符，分析，作出响应，不同点，denite的normal模式，不是真正的normal模式，他还在不停监控输入，而leaderf 直接关闭的监控循环，切换到了真正的vim normal模式，虽然关闭了buffer 的 编辑权限，但是感觉这样不是非常的好， 容易出问题， 很简单一个，模式变更，触发autocmd， airline 刷新了状态栏，当再次进入insert模式时，状态栏没有得到恢复。 这里就要提到，前面我说的，不停止监控的好处了，基本上不会触发模式变更autocmd 状态栏也不会被刷新。 可以看我的 vim-chat 的实现。 纯 viml实现的。

建议即便是按`esc`切换到 normal模式，也不要停止监控输入，而是换成另外一套分析法则，

### 自定义快捷键

我是习惯于 tab 和 shift-tab键上下选择选项，目前似乎只能是上下键。

**Comment by wsdjeg** [comment]
还在测试中，如果有什么，我再在这个issue下留言，后期等你有时间，我们细聊下。

**Comment by Yggdroot** [comment]
Normal 模式我很少在上面操作，只是有时候想查看一些结果的时候更方便一些，而设计它的初衷也就是为了查看结果。你说的容易出问题，至少我还没感觉到有什么问题。我没用airline，LeaderF自带状态栏。
**自定义快捷键**，你是指normal模式下的？normal下没这个功能，我觉得j,k比tab 和 shift-tab更方便，而且我也没有增加这个功能的打算。如果不是normal模式下的，有自定义快捷键的功能。
具体有什么问题，就开issue吧。

**Comment by wsdjeg** [comment]
我在多尝试下吧，今天试了下，不知道是不是我的姿势不对，回车键不能打开文件。

**Comment by wsdjeg** [comment]
我刚才试了一下，linux neovim下 回车无法打开文件， vim中正常工作。

**Comment by Yggdroot** [comment]
我没在neovim上测过。

**Comment by Yggdroot** [comment]
`"容易出问题， 很简单一个，模式变更，触发autocmd， airline 刷新了状态栏，当再次进入insert模式时，状态栏没有得到恢复。" ` 你说的这些可能是你想象的，不是真正遇到的。 实际上，LeaderF的input mode和normal mode都是vim的normal mode，不会触发你所说的autocmd。
