### ISSUE TITLE
`Leaderf gtags` some command not save `self._last_command`

### ISSUE THREAD

**Issue by lwllvyb** [Yggdroot/LeaderF#420]
- vim or neovim? 
    - [ ] vim
    - [ x ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
`Leaderf gtags` some command not save `self._last_command`

**Comment by Yggdroot** [comment]
Sorry, I don't understand what you mean.
