### ISSUE TITLE
Unexpected buffer background highlighting when file is opened after using preview

### ISSUE THREAD

**Issue by obxhdx** [Yggdroot/LeaderF#422]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: v0.4.3
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
- Output of `:echo g:Lf_Debug_Cmd`:  rg --no-messages --files --color never
- Output of `:echo g:Lf_FilesFromCache`:  1
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

This is the full content from my minimal_vimrc file: 
```VimL
set number
let mapleader = " "
call plug#begin('~/.vim/plugins')
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
let g:Lf_HideHelp = 1
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2" }
let g:Lf_WindowPosition = 'popup'
call plug#end()
```

### Describe your question, feature request, or bug.
I noticed a strange highlighting on the background of a buffer whenever I preview a file before opening it. I have some gifs below, hopefully it will be clear what the problem is. Notice that after the previewed file is open, its buffer retains the same background color as the preview window, and you can also see that the sign column color is different.

### Steps to reproduce
1. Call `Leaderf file`
2. Hit `<C-P>` to toggle preview
3. Open the file that was previewed (it doesn't matter if the preview window was open or closed when you open the previewed file)

### Actual behaviour
![with-preview](https://user-images.githubusercontent.com/761254/70270714-d9185480-1759-11ea-978f-200ce54a6ab3.gif)

### Expected behaviour
![no-preview](https://user-images.githubusercontent.com/761254/70270735-e5041680-1759-11ea-88dd-56134904dce9.gif)

**Comment by Yggdroot** [comment]
This seems a bug of neovim, I'll test it further.

**Comment by Yggdroot** [comment]
This is a bug of neovim, I have created an issue: https://github.com/neovim/neovim/issues/11525.

**Comment by Yggdroot** [comment]
This issue has been fixed by a workaround.

**Comment by obxhdx** [comment]
Amazing, thank you for the quick fix!

**Comment by hzchirs** [comment]
Hi, @Yggdroot, this issue also happens when searching files by `rg`. When I preview in `Leaderf rg` window, than the background color stills be changed.

**Comment by Yggdroot** [comment]
@hzchirs fixed.

**Comment by tangdading6** [comment]
这个问题我现在偶尔还会遇到... neovim 0.4.4-1

**Comment by Yggdroot** [comment]
> 
> 
> 这个问题我现在偶尔还会遇到... neovim 0.4.4-1

按理说现在已经fix这个问题了，你如果还会遇到，请把具体的复现步骤写清楚。
