### ISSUE TITLE
Edit the cmdHistory entry

### ISSUE THREAD

**Issue by anuvyklack** [Yggdroot/LeaderF#423]
Add the possibility to edit the entry in `cmdHIstory` and `searchHistory` before execution. Appropriate keybindings, in my opinion, would be `Ctrl-e` in "Input" mode (like in fzf) and `e` in "Normal" mode.

**Comment by tamago324** [comment]
Implements for #448 !
Try it if you want.

Usage:
* Insert mode: `<C-o>`
* Normal mode: `e`

**Comment by Yggdroot** [comment]
I think this issue can be closed.
