### ISSUE TITLE
support for spaceline 

### ISSUE THREAD

**Issue by miffyrcee** [Yggdroot/LeaderF#424]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
### Describe your question, feature request, or bug.
Statusline supports spaceline
### Expected behaviour
![Screenshot from 2019-12-09 16-59-57](https://user-images.githubusercontent.com/43992258/70421858-a4800200-1aa5-11ea-8bb4-33ae745cf4c1.png)
It may be  uncomfortable

**Comment by Yggdroot** [comment]
What is spaceline?

**Comment by miffyrcee** [comment]
vim statusline and please look this
```
https://github.com/hardcoreplayers/spaceline.vim
```

**Comment by Yggdroot** [comment]
you just need to set `g:Lf_StlSeparator`.

**Comment by miffyrcee** [comment]
ok ! thanks a lot.
