### ISSUE TITLE
[bug] lost line number if open first file by leaderf

### ISSUE THREAD

**Issue by findNextStep** [Yggdroot/LeaderF#425]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`:  1
- Output of `:py print(sys.version)`: 
2.7.17 (default, Oct 24 2019, 12:57:47)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
noremap <C-p> :Leaderf file --popup<CR>
noremap <C-j> :Leaderf function --popup<CR>

### Describe your question, feature request, or bug.
if we open first file by leaderf file --popup the line number will disapper

### Steps to reproduce

open vim in workspace folder
use Leaderf file --popup and open file
![image](https://user-images.githubusercontent.com/26270464/70436465-52020e00-1ac4-11ea-8ff9-192a9f14e7dc.png)

the line number disapper
![image](https://user-images.githubusercontent.com/26270464/70436485-5dedd000-1ac4-11ea-9a60-e16a0d28c58f.png)

but if we open any file thanuse Leaderf ,the line number is still there
![image](https://user-images.githubusercontent.com/26270464/70436496-680fce80-1ac4-11ea-9b83-6b71f107a4fd.png)

**Comment by Yggdroot** [comment]
Sorry, I can not reproduce it, could you provide a minimum vimrc to reproduce it?

**Comment by findNextStep** [comment]
it`s seem that it because i rewrite the start page
![image](https://user-images.githubusercontent.com/26270464/70590882-1e7fca80-1c0f-11ea-90c1-a15c371a4112.png)

I use this plugin 
```vim
Plug 'Carpetsmoker/startscreen.vim'

" start page change
function! T()
    " wecome界面不需要缩进线
    IndentLinesToggle
    read ~/.myvim/start.txt
    " Some margin for readability
    :silent %>>
    " Go to line 1
    :1
    echo "welcome theNext"
endfun
let g:Startscreen_function = function('T')
```
it seem to be hard to give a minimum vimrc.....

**Comment by Norbytus** [comment]
I have similar problem. If set next parameter in 1
let g:nerdtree_tabs_open_on_console_startup = 1
