### ISSUE TITLE
cuda file format support

### ISSUE THREAD

**Issue by luoleicn** [Yggdroot/LeaderF#426]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

LeaderF function do not support .cu files, while it works well with cpp files

**Comment by Yggdroot** [comment]
Please use universal-ctags instead.

**Comment by luoleicn** [comment]
> Please use universal-ctags instead.

thanks, that works
