### ISSUE TITLE
Cmd+V support on Mac

### ISSUE THREAD

**Issue by obxhdx** [Yggdroot/LeaderF#428]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: v0.4.3
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)]
- Output of `:echo g:Lf_Debug_Cmd`:  rg --no-messages --files --color never
- Output of `:echo g:Lf_FilesFromCache`:  1
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```VimL
" Contents from /tmp/minimal.vimrc
let mapleader = " "
call plug#begin('~/.vim/plugins')
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
call plug#end()
```

### Describe your question, feature request, or bug.
Leaderf doesn't support Cmd+V for pasting content on its prompt. Given that this is the default shortcut on Mac, it becomes very counter-intuitive for Mac users to have to use CTRL+V only in this case instead.

I tried to use `Lf_CommandMap` but couldn't get it to map correctly my Cmd+V to CTRL+V.

Note that I can paste normally using Cmd+V in my Vim inside the terminal with no extra configuration. I used other fuzzy finders in the past (fzf, clap) and this always worked with no extra configuration as well.

### Steps to reproduce
1. Call `Leaderf file`
2. Press `Cmd+V` to paste anything on the prompt
3. See that nothing gets pasted in the Leaderf window
4. Open some file or simply close Leaderf window without opening anything
5. See the content you pasted in the buffer that was open

### Actual behaviour
![leaderf-cmd-v-trimmed](https://user-images.githubusercontent.com/761254/70652326-45d29980-1c07-11ea-896f-e730ab750843.gif)

### Expected behaviour
Cmd+V behaves just like CTRL+V.

**Comment by Yggdroot** [comment]
This issue is because of https://github.com/vim/vim/issues/5349.

**Comment by obxhdx** [comment]
Thanks for looking into it! I’m actually using neovim though, in case you wanna open an issue in their repo as well.

**Comment by Yggdroot** [comment]
The issue for neovim: https://github.com/neovim/neovim/issues/11551

**Comment by Yggdroot** [comment]
Close this issue as neovim/neovim#11551 has been closed.

**Comment by obxhdx** [comment]
Sorry but I don't understand why this is a vim/nvim issue, when LeaderF is the only place in the entire terminal environment where Cmd+V doesn't work. This key combo works as expected in iTerm, inside tmux, inside vim, inside nvim, and with other plugins like fzf and Clap. It's literally only inside LeaderF that it doesn't work.

**Comment by Yggdroot** [comment]
Because LeaderF uses `getchar()` to get the input characters, others does not.
