### ISSUE TITLE
自動選擇搜索起始目錄

### ISSUE THREAD

**Issue by chin33z** [Yggdroot/LeaderF#43]
請問有類似CtrlP的[g:ctrlp_working_path_mode](https://github.com/kien/ctrlp.vim/blob/master/doc/ctrlp.txt#L178)選項可以設定嗎？這還滿方便的.

**Comment by Yggdroot** [comment]
目前还没有，我在考虑有没有加的必要。

**Comment by chin33z** [comment]
謝謝

**Comment by Yggdroot** [comment]
我使用vim，一般是到某个project根目录下，打开vim，然后可以随便查找这个project的所有文件； 难道需要先进入某个子目录再查找吗？
g:ctrlp_working_path_mode选项的使用场景是怎样的呢，我没体会到有了那些设定有什么优点，可以说明一下吗？

**Comment by Yggdroot** [comment]
@chin33z @createwindow Feature added. 

https://github.com/Yggdroot/LeaderF/blob/c253ca402333a435cdb5405c2aa2c6619ee39714/doc/leaderf.txt#L446-L471
