### ISSUE TITLE
<C-P> 在弹出的预览界面无法上上下滚动

### ISSUE THREAD

**Issue by 0xhacking** [Yggdroot/LeaderF#431]
\<C-Up\> 和 \<C-Down\> 无法使用

**Comment by Yggdroot** [comment]
什么系统什么终端？可能需要设置一下。
而且你还可以改键。

**Comment by 0xhacking** [comment]
在 Windows 系统，用的 Xshell

**Comment by Yggdroot** [comment]
那你看看xshell的快捷键设置，把c-up去掉

**Comment by 0xhacking** [comment]
Xshell 快捷键里面没有设置相应 C-Up ，而且有时候鼠标的滑轮滚动，页面不滚动。

**Comment by Yggdroot** [comment]
xshell确实没法识别c-up，
用let g:Lf_CommandMap 改一下快捷键吧。

**Comment by 0xhacking** [comment]
好的，我试试，多谢咯

**Comment by 0xhacking** [comment]
你使用的是什么终端？

**Comment by Yggdroot** [comment]
> 你使用的是什么终端？

xshell

**Comment by 0xhacking** [comment]
好的，知道了，多谢
