### ISSUE TITLE
Don't show line number after open file in new tab(t)

### ISSUE THREAD

**Issue by Norbytus** [Yggdroot/LeaderF#432]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of ` v0.4.3`: 
- Output of `1`: 
- Output of `:1`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `2.7.17`: 
- Output of `3.7.5`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Steps to reproduce
```
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
set autoread
set updatetime=250
set noswapfile
set number
set relativenumber
set nowrap
set cursorline
let g:rehash256 = 1
set termguicolors
set background=dark
set listchars=tab:⇢\ ,eol:¬,trail:·
set fillchars+=vert:\ 
set list
set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz
set colorcolumn=80,120
set ignorecase
set tabstop=4
set shiftwidth=4
set smarttab
set expandtab
set smartindent
set encoding=UTF-8
set exrc
autocmd! BufRead * retab "replace all space on tab
setlocal spell spelllang=ru

let mapleader = "\<Space>"

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'Yggdroot/LeaderF', { 'do': '.\install.sh'}
Plug 'jistr/vim-nerdtree-tabs'
Plug 'scrooloose/nerdcommenter'
Plug 'Xuyuanp/nerdtree-git-plugin'
call plug#end()

let NERDTreeWinSize = 25
let g:NERDTreeMinimalUI = 1
let g:NERDTreeDirArrows = 1
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:nerdtree_tabs_open_on_console_startup = 1

let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹",
    \ "Staged"    : "✚",
    \ "Untracked" : "✭",
    \ "Renamed"   : "➜",
    \ "Unmerged"  : "═",
    \ "Deleted"   : "✖",
    \ "Dirty"     : "✗",
    \ "Clean"     : "✔︎",
    \ "Unknown"   : "?"
\ }

let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1

```
### Actual behaviour
![image](https://user-images.githubusercontent.com/13504897/71072453-9611a480-218f-11ea-86c4-13b8e4e1c513.png)
![image](https://user-images.githubusercontent.com/13504897/71072467-a295fd00-218f-11ea-8473-acf786031e41.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/13504897/71072376-6b275080-218f-11ea-9b73-3ef5627cce76.png)
![image](https://user-images.githubusercontent.com/13504897/71072401-78dcd600-218f-11ea-8242-bc8699d793b3.png)

**Comment by Norbytus** [comment]
https://github.com/Yggdroot/LeaderF/issues/425

**Comment by Yggdroot** [comment]
What's the steps to reproduce? 
Is it
1. vim
2. ctrl-w-w
3. :Leaderf file
4. test
5. enter
?
I can not reproduce it.

**Comment by Norbytus** [comment]
1) neovim
2) open popup ledearF menu
3) FInd file
4) Open in tab(press t button)

**Comment by Norbytus** [comment]
https://asciinema.org/a/w9Rl5gMuY5Dcv0fxZkY8JV9Ct

**Comment by jdhao** [comment]
I have also met this issue inside Neovim. Open a file using leaderf in floating window and press <enter> open it. Then the number and relative number of the file is gone.

**Comment by Yggdroot** [comment]
I have found the root cause, it is because of https://github.com/Yggdroot/LeaderF/commit/2a715ed58467ab004bce79746ef674575c579639.

**Comment by Yggdroot** [comment]
fixed.

**Comment by Norbytus** [comment]
Whene expect new release?
=)
