### ISSUE TITLE
g:Lf_PopupHeight is a fixed value, it won't change when resizing window

### ISSUE THREAD

**Issue by fatjing** [Yggdroot/LeaderF#436]
- vim or neovim? 
    - [x] vim 8.2.12
    - [ ] neovim
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```let g:Lf_PopupHeight = float2nr(&lines * 0.3)```

### Steps to reproduce
Add ```let g:Lf_PopupHeight = float2nr(&lines * 0.3)``` to vimrc as the doc says

### Actual behaviour
g:Lf_PopupHeight is a fixed value calculated from the initial size of gvim upon startup, and it won't change when gvim window is resized

### Expected behaviour
g:Lf_PopupHeight should change when window resized. 
I think it should be able to be set to a floating number, just like g:Lf_WindowHeight does

**Comment by Yggdroot** [comment]
Done.
