### ISSUE TITLE
leaderf rg not work, even halted macvim

### ISSUE THREAD

**Issue by leoatchina** [Yggdroot/LeaderF#438]
- vim or neovim? 
    - [x] macvim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: macvim 8.1.1722
- Output of `:echo has("python3")`:  yes
- Output of `:py3 print(sys.version)`: python 3.7.5

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.
When use `Leaderf rg` in macvim, the `popup/right` windows halted, a red `Done!` appeared on the leftbottem , but no results got. BTW,  `vim/nvim/vimr` do not has this issue, leader rg worked well with them. `rg` was installed with brew, `vim` is 8.1.2152
### Steps to reproduce
:Leaderf rg

**Comment by Yggdroot** [comment]
do you mean this issue #364?

**Comment by leoatchina** [comment]
I read #364 , and done `py3` command, I `cannot` do `mvim` since my macvim is not installed with brew so my macvim was started from docker
It rasised this error 
![image](https://user-images.githubusercontent.com/4470821/71217197-d68c3200-22f7-11ea-848d-b4893e4eacbb.png)

**Comment by Yggdroot** [comment]
if you can't use py3, use py.

**Comment by leoatchina** [comment]
Since my config use python3 only or python only, I just force macvim to use ctrlsf instead.
It's not a big deal
