### ISSUE TITLE
Install error on OSX

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#44]
Tried to install it but got this error...
```Done! Plugins updated; press u to view changelog
Error detected while processing ~/.vim/bundle/LeaderF/plugin/leaderf.vim:
line   82:
E806: using Float as a String
E116: Invalid arguments for function <SNR>62_InitVar
line   88:
E806: using Float as a String
E116: Invalid arguments for function <SNR>62_InitVar```

**Comment by MightyCreak** [comment]
`has('python')` return `1`
`has('python3')` return `0`
Python is at version 2.7.13

**Comment by MightyCreak** [comment]
I updated MacVim and now I have python 3 (3.6.0)

I removed, cleaned and reinstalled LeaderF and got the same error:

```Done!
Error detected while processing /Users/romainf/.vim/bundle/LeaderF/plugin/leaderf.vim:
line   82:
E806: using Float as a String
E116: Invalid arguments for function <SNR>43_InitVar
line   88:
E806: using Float as a String
E116: Invalid arguments for function <SNR>43_InitVar```

**Comment by Yggdroot** [comment]
Please hack the code in /Users/romainf/.vim/bundle/LeaderF/plugin/leaderf.vim. change the code `call s:InitVar('g:Lf_WindowHeight', 0.5)` as `call s:InitVar('g:Lf_WindowHeight', '0.5')`, and change `call s:InitVar('g:Lf_NeedCacheTime', 1.5)` as `call s:InitVar('g:Lf_NeedCacheTime', '1.5')`, and have a try.

**Comment by Yggdroot** [comment]
Does ` :echo has('float') ` return 1 for you?  Maybe your version of Vim does not support float.

**Comment by MightyCreak** [comment]
It seems to work! Thanks!

The first launch of <Leader>f is quite long though, like 10 or 15 seconds. Some feedback might be great here.

Also, is there a way to remove some directories from the browsing? I'd like to remove .hg, .git and some project specific directories

**Comment by MightyCreak** [comment]
Yep, `:echo has('float')` returns 1

**Comment by Yggdroot** [comment]
The hack makes it work?

**Comment by Yggdroot** [comment]
I'll optimize the first launch later on.
You can see [here](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L138)

**Comment by Yggdroot** [comment]
To ignore some directories, please refer to [here](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L138).

**Comment by Yggdroot** [comment]
This is a bug of some version of vim. We are not alone, https://github.com/nathanaelkane/vim-indent-guides/issues/10 is the same.

**Comment by Yggdroot** [comment]
https://groups.google.com/forum/#!topic/vim_dev/knwTpoNiTvE may be the root cause.

**Comment by MightyCreak** [comment]
Thanks!

>The hack makes it work?
Yep, it seems to work now! (although I'm fairly new to this plugin, so I don't really know how it _should_ work ;) )

>To ignore some directories, please refer to here.
Otherwise, it would be nice if you could add '.hg' too by default.

> https://groups.google.com/forum/#!topic/vim_dev/knwTpoNiTvE may be the root cause.
Strange vim didn't fix that already 🤔
