### ISSUE TITLE
请教两个问题：关于g:Lf_WindowPosition 以及popup preview的

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#440]
1 . 我将let g:Lf_WindowPosition = ‘right’使用，但是一直没有找到设置的部分修改宽度，我期望能够占据右侧三分之一左右的空间，但是总是占据一半，那个变量可以修改这个？
2. 如何做到在popup window preview代码时，在popup的windows里面pageup以及pagedown？

谢谢

**Comment by Yggdroot** [comment]
目前这两个功能都没有。

**Comment by irreallich** [comment]
@Yggdroot  多谢
我使用的是终端下的vim，以后会加入相应功能么？
