### ISSUE TITLE
Error running `:Leaderf file` in a git repo directory in windows

### ISSUE THREAD

**Issue by fatjing** [Yggdroot/LeaderF#441]
- vim or neovim? 
    - [x] vim 8.2.12
    - [ ] neovim
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: None

### Steps to reproduce
Open a file of a git repository
Run ```:Leaderf file```
### Actual behaviour
Got error:
![image](https://user-images.githubusercontent.com/1171924/71267801-6d073480-2386-11ea-825e-a06b876aa2ac.png)

Note: I don't have git installed in windows.  Maybe that's the culprit but I haven't tested it.

**Comment by Yggdroot** [comment]
Yes, leaderf will try to use `git ls-files` if it finds it's in a git repo. 
You can set `let g:Lf_UseVersionControlTool = 0` to disable it to use `git ls-files`, then it will use `rg`, `pt`, `ag` or `find `to create a index.

**Comment by fatjing** [comment]
Thank you.
Then I'd like to make a feature request: Check if git or hg exists before indexing files, if not, falls back to default external tool.
That would provide a more user friendly experience.

**Comment by Yggdroot** [comment]
I think git is a must have tool

**Comment by fatjing** [comment]
It is a must have tool but it is not necessarily installed everywhere. Take my use case for example, I use git mainly in wsl, but I also use gvim a lot outside wsl and I don't want to install git again. Sure I can check git existence in my vimrc, no big deal. The problem is leaderf uses version control tool by default and if the tool doesn't exist then it fails without fall-back. I don't think this is a smooth experience.
