### ISSUE TITLE
Error when use popup

### ISSUE THREAD

**Issue by zzzzzzmj** [Yggdroot/LeaderF#444]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.2
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: 3.7.5 (default, Nov  1 2019, 02:16:32)
[Clang 11.0.0 (clang-1100.0.33.8)]
- Output of `:echo g:Lf_Debug_Cmd`: E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: E121: Undefined variable: g:Lf_FilesFromCache
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
use :Leaderf file --popup  or let g:Lf_WindowPosition = 'popup'

### Actual behaviour
show this error
```
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/a1/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line
 780, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/a1/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line
 712, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/a1/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", lin
e 729, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/Users/a1/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line
 1978, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "/Users/a1/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", lin
e 917, in enterBuffer
    self._createPopupWindow(clear)
  File "/Users/a1/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/instance.py", lin
e 485, in _createPopupWindow
    lfCmd("silent let winid = popup_create(%d, %s)" % (buf_number, str(options)))
vim.error: Vim(lcd):E344: Can't find directory "/usr/local/share/vim/vim82/File" in cdpa
th
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
```
thanks

**Comment by Yggdroot** [comment]
Could you provide a minimum vimrc to reproduce it?

**Comment by zzzzzzmj** [comment]
I think it's because this config `autocmd bufenter * lcd %:p:h`
when i use `autocmd bufenter * silent! lcd %:p:h` or remove it,  popup work

**Comment by zzzzzzmj** [comment]
I'm not familiar with vim，maybe its my problem，i can fix it  by myself

**Comment by Yggdroot** [comment]
vim's plugin can not protect itself from being conflict with other configurations. So I don't plan to fix it in LeaderF any more, your fix is just OK.

**Comment by yzlnew** [comment]
Very useful infomation. I guess quite a number of users setting auto change to buffer dir in their vimrc. Maybe mention this issue in help?
