### ISSUE TITLE
[Questions] Why is `'` removed in `:Leaderf help` suggestions?

### ISSUE THREAD

**Issue by tamago324** [Yggdroot/LeaderF#446]
I want to know why we have removed `'` from `:Leaderf help` suggestions.

The following code is deleted:

https://github.com/Yggdroot/LeaderF/blob/89dde784f41f748f6c4a478b2a59b901e5bd2e7a/autoload/leaderf/python/leaderf/helpExpl.py#L36

e.g. If you type `confirm` in `:Leaderf help`,

![image](https://user-images.githubusercontent.com/16581287/71318931-c08a9700-24da-11ea-9868-7f367a2c037a.png)

Both `confirm` (`'confirm'`) and `confirm()` jump to the location of `confirm()`.
Is this as expected?

I think that `'confirm'` and` confirm () `should jump to `'confirm'` and `'confirm()'`, respectively.

**Comment by Yggdroot** [comment]
didn't realize that this may cause bug.

**Comment by tamago324** [comment]
OK.
Thank you for fixing!
