### ISSUE TITLE
[Feature request] Support quickfix/location lists options to show `rg` search results

### ISSUE THREAD

**Issue by pirj** [Yggdroot/LeaderF#447]
The results of `rg` output are shown in a decidated window which is different from the default `:grep`/`:lgrep` behaviour.
The convenience of the latter two is that `:cnext`/`:cprevious`/`:cfirst`/`:clast`/... are available, and that makes `--recall` the default, and `--next`/`--previous` redundant as default Vim's commands already exist.

Would it be possible to add `--quickfix`/`--location` as an option to `rg`'s window position option?

PS Thanks for LeaderF, it's by far more usable than other fuzzy finders.

**Comment by Yggdroot** [comment]
I can't see any advantage over the native implementation of LeaderF.

**Comment by joerideg** [comment]
One advantage is that after running rg and outputting results in the quicklist I can then do `cfdo` to replace values in those files. 
Or is there a way to replace values currently that I am not aware of?

**Comment by joerideg** [comment]
btw I would much rather have a replace function with LeaderF's native implementation then to load them in the quickfix list

**Comment by tamago324** [comment]
Hi.
It is not an option like `--quickfix` or` --location`, but implements output by mapping in the result window.

https://github.com/tamago324/LeaderF/commit/def838ad6c4f7de922c7e6a411864a4a034a78ff

You can output the result of filtering.
`Q` (quickfix list) and `L` (location list) can be output in `normal` mode.

How about that?
Would you let us know what you think.

**Comment by joerideg** [comment]
This sounds usefull!

**Comment by tamago324** [comment]
Thanks!
Is this what you were looking for?

**Comment by joerideg** [comment]
If I understand correctly this would allow me to:
Put all filtered results directly in the Quick or Location results (And possibly select specific results and put them in) , which is what I needed for search and replace.
Now I could do: Leaderf rg, filter stuff, hit Q and then 'cfdo %s/something/somethingelse/` 

It would be even more seamless if Leaderf would output the current filter of results into a register so I could prepopulate the replace regex with that.

**Comment by tamago324** [comment]
> If I understand correctly this would allow me to:
Put all filtered results directly in the Quick or Location results (And possibly select specific results and put them in) , which is what I needed for search and replace.
Now I could do: Leaderf rg, filter stuff, hit Q and then 'cfdo %s/something/somethingelse/`

Yes. That understanding is correct!

> It would be even more seamless if Leaderf would output the current filter of results into a register so I could prepopulate the replace regex with that.

It looks good to save in a register.
However, it seems difficult because you can enter multiple search patterns like `Leaderf rg -e "hello" -e "world"`.

**Comment by joerideg** [comment]
Hmmm good point.
Alright then, thanks for the effort! Hope it will be in soon.

**Comment by tamago324** [comment]
#488 has been merged, so you can output it to quickfix and location list!

**Comment by tamago324** [comment]
https://github.com/thinca/vim-qfreplace is a very useful plugin.
if you like please get.
