### ISSUE TITLE
Don't show line number in 'help' files

### ISSUE THREAD

**Issue by linjiX** [Yggdroot/LeaderF#450]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
编译者 brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:py3 print(sys.version)`: 
```
3.7.4 (default, Sep 24 2019, 17:13:17)
[Clang 10.0.1 (clang-1001.0.46.4)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
set number
call plug#begin('~/.vim/plug')
Plug 'Yggdroot/LeaderF', {'do': './install.sh', 'on': 'Leaderf'}
call plug#end()
```

### Describe your question, feature request, or bug.
Normally the 'help' file should be open without line number,
But the line number appears if it is open by `Leaderf help`

### Steps to reproduce
1. Open neovim
2. `:Leaderf help`
3. search any keyword and open it

### Actual behaviour
The help file will be open with line number

### Expected behaviour
The help file will be open without line number

**Comment by Yggdroot** [comment]
This issue is due to a bug of nvim(https://github.com/neovim/neovim/issues/11525) and my workaround(https://github.com/Yggdroot/LeaderF/commit/0534ddd138f5f8f6850948f6f20eb8224cb18fe3) for it. Can only be fixed until https://github.com/neovim/neovim/issues/11525 is fixed.
