### ISSUE TITLE
[Feature request]Support search for mappings, commands and filetypes

### ISSUE THREAD

**Issue by tuberry** [Yggdroot/LeaderF#451]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Could you please support search for mappings, commands and filetypes which inspired by [fzf.vim](https://github.com/junegunn/fzf.vim)

**Comment by tamago324** [comment]
Hi!
I want you to support me too.

If possible, I’d like to implement it.

LeaderF can also be extended.

@Yggdroot Should I embed it in LeadeF or implement it as an extension like LeaderF-marks? If you like, let us know what you think.

**Comment by Yggdroot** [comment]
Either is OK. Welcome to contribute to LeaderF.
Thanks in advance.

**Comment by tamago324** [comment]
@Yggdroot Thank you too.
Let's try to embed it in LeaderF!

**Comment by tamago324** [comment]
For LeaderfCommand, the command is now executed immediately.
However, [fzf.vim](https://github.com/junegunn/fzf.vim) always moves to the command line.
Which is better?
Please let us know what you think.

**Comment by tuberry** [comment]
Thanks. 

> For LeaderfCommand, the command is now executed immediately.
> However, [fzf.vim](https://github.com/junegunn/fzf.vim) always moves to the command line.
> Which is better?

It's a good idea for commands without arguments, however it's more intricate in practice.
For example, there are a series of commands working with or without argument(s) to show or set state such as `colorscheme`, [`AirlineTheme`](https://github.com/vim-airline/vim-airline). 
And some commands requiring arugments also execute silently without argument just like `Leaderf` itself.
https://github.com/Yggdroot/LeaderF/blob/32b24bb2eec75c3ffe2c8229e8f80e91f0bc6307/autoload/leaderf/Any.vim#L323

**Comment by tamago324** [comment]
@tuberry Thanks.
Now I think it's better to go to the command line even for commands that can be executed without arguments.
Also, because I always go to the command line, I feel kind to the user.
So I want to delete `editCommand()`.

**Comment by tuberry** [comment]
@tamago324  Don't think about giving up so soon. How about extending the `bang` option to distinguish the two condition? I guess more commands are ought to run immediately than those aren't.

**Comment by tamago324** [comment]
> Don't think about giving up so soon.

It was too early to give up. Thank you very much.
> How about extending the bang option to distinguish the two conditions?

What does extending the `bang` option mean?
What are the two conditions?
Something like below?

1. Execute immediately after selection
2. Go to the command line after selection

In order to split the above two conditions, I came up with the following two things.

1. Add options to the command (e.g. `Leaderf command --run-immediately`)
2. Add global option (e.g. `g:Lf_CommandRunImmediately`)

**Comment by tuberry** [comment]
>   Execute immediately after selection
     Go to the command line after selection

Yes,  and

> What does extending the bang option mean?

I mean something like `Leaderf! command` and `Leaderf command` .

As is mentioned in README:
> If [!] is given, enter normal mode directly.

**Comment by Yggdroot** [comment]
> In order to split the above two conditions, I came up with the following two things.
> 
> 1. Add options to the command (e.g. Leaderf command --run-immediately)

I upvote this one.

**Comment by Yggdroot** [comment]
> I mean something like Leaderf! command and Leaderf command .

`Leaderf! command` has already been used.

**Comment by tuberry** [comment]
> In order to split the above two conditions, I came up with the following two things.
       Add options to the command (e.g. Leaderf command --run-immediately)
>I upvote this one.

> `Leaderf! command` has already been used.

How about `Leaderf command!`

**Comment by Yggdroot** [comment]
> 
> > `Leaderf! command` has already been used.
> 
> How about `Leaderf command!`

Actually, there is no difference between `Leaderf command!` and `Leaderf command --run-immediately` in the view of implementation. I prefer `Leaderf command --run-immediately`, because if some others want to a second feature of `Leaderf command`, could it be `Leaderf command!!` ? then `Leaderf command!!!` ...

**Comment by tamago324** [comment]
Thanks for the advice!
I'd like to implement it in `Leaderf command --run-immediately`, is that OK?

**Comment by Yggdroot** [comment]
OK for me.

**Comment by tamago324** [comment]
> I'd like to implement it in `Leaderf command --run-immediately`, is that OK?

@tuberry What about you?

**Comment by tuberry** [comment]
> > I'd like to implement it in `Leaderf command --run-immediately`, is that OK?
> 
> @tuberry What about you?

That's OK. Thanks.

**Comment by tamago324** [comment]
> > > I'd like to implement it in `Leaderf command --run-immediately`, is that OK?
> > 
> > 
> > @tuberry What about you?
> 
> That's OK. Thanks.

Thanks!

**Comment by tamago324** [comment]
#459 could implement `Leaderf command --run-immediately`.
Thank you very much.
