### ISSUE TITLE
Navigate within result window is slow

### ISSUE THREAD

**Issue by yihuang** [Yggdroot/LeaderF#453]
Navigate within result window with `j`/`k` is very slow, I try to use `LeaderF` to replace `bufexplorer` as a, buffer explorer, but i find `LeaderF` negivating is much slower than `bufexplorer`.

**Comment by tamago324** [comment]
"result window" is Vim's popup window?

I had a slow cursor movement in Vim's popup window.

However, it turned out to be the influence of other plugins, not LeaderF.
As a result, the cursor movement has been accelerated by removing the use of other plugins.

**Comment by Yggdroot** [comment]
How to reproduce it?
Is it in popup mode?

**Comment by yihuang** [comment]
> How to reproduce it?
> Is it in popup mode?

```
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_ShortcutF = "<leader>ff"
```
Open 20 files in vim at the same time, then run:
`:Leaderf! buffer`

Hold `j`/`k` to navigate up and down, it's lag behind the keyboard speed significantly.

**Comment by Yggdroot** [comment]
What's the OS? vim or nvim?
Could you remove all the other plugins and have a try?

**Comment by yihuang** [comment]
macOS Catalina, iterm2, vim8.2.
Reproduce steps:
```
mkdir /tmp/vimdebug/ && cd /tmp/vimdebug/
git clone https://github.com/Yggdroot/LeaderF.git .vim
cat > .vimrc <<EOF
let g:Lf_WindowPosition = 'popup'
EOF
for n in {1..30}; do touch test$n; done
HOME=`pwd` vim *
```

**Comment by Yggdroot** [comment]
![1](https://user-images.githubusercontent.com/2705841/71613135-89ee0400-2bdf-11ea-8e69-c42e73e4aa06.png)

What is the setting of your computer?
I don't think this is the issue of LeaderF.

**Comment by yihuang** [comment]
```
What is the setting of your computer?
I don't think this is the issue of LeaderF.
```
I mean the cursor moving is lagging behind the keyboard, even after I lift up the key, the cursor still running for a while, so it's definitely not a keyboard issue.
Also `bufexplorer` is running fine, and LeaderF normal (non popup) window runs much more smoothly.

**Comment by Yggdroot** [comment]
Can you try leaderf in another platform, such as linux, window? Maybe it's a platform dependent issue.

**Comment by Yggdroot** [comment]
Reproduced.

**Comment by Yggdroot** [comment]
It's because vim is slow on MacOS, I can only make the performance a little better.

**Comment by yihuang** [comment]
> It's because vim is slow on MacOS, I can only make the performance a little better.

I guess we can always use `--bottom` mode for buffer list ;D
