### ISSUE TITLE
MRU 又再次出现同一个文件两个名字（正斜杠分割和反斜杠分割）

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#460]
环境：windows，nvim-qt 0.4.3，

![photo_2020-01-05_01-49-11](https://user-images.githubusercontent.com/3035071/71769526-98c91380-2f5d-11ea-9719-0375c8dd833f.jpg)

我记得我以前还提交过 patch 来检测这件事情的嘛，怎么又被 revert 回去了？

Vim 下面没问题，都是 `\` 分割的文件名，NeoVim 下面如果用 dirvish 等插件打开文件的话，就会出现 `/` 分割的文件名，然后就被 mru 记录成两个不同文件了。

**Comment by Yggdroot** [comment]
没有revert，那部分代码就没动过。

**Comment by skywind3000** [comment]
那是不是有其他路径也再一起记录啊？

**Comment by skywind3000** [comment]
比如 vimscript 会不会也在写 mru 文件啊？

**Comment by skywind3000** [comment]
确实是被你改过了，这里：

https://github.com/Yggdroot/LeaderF/commit/d222b2187b359b484435628bb64829c724c453ad#diff-42d720ae936a19a7c6037570bd4e7838

我原来写了一个转换成：`os.path.abspath()`，这个函数会把 windows 下 `/` 全部转成 `\` ，但是被你删除掉了：

![mru](https://user-images.githubusercontent.com/3035071/71774173-f3d22900-2fa4-11ea-8091-16ba4c37bd69.png)

**Comment by Yggdroot** [comment]
哦，我看看当时为什么删掉它。

**Comment by skywind3000** [comment]
我现在写了个清理函数：

```VimL
function! minibox#clear_leader_mru()
	if s:windows == 0
		return 0
	endif
	let fn = expand('~/.vim/cache/.LfCache/python3/mru/mruCache')
	let content = []
	let avail = {}
	if !filereadable(fn)
		let fn = expand('~/.vim/cache/.LfCache/python2/mru/mruCache')
		if !filereadable(expand(fn))
			return -1
		endif
	endif
	for name in readfile(fn)
		let name = substitute(name, '/', '\\', 'g')
		let name = substitute(name, '\n*$', '', 'g')
		let key = tolower(name)
		if !has_key(avail, key)
			let avail[key] = 1
			let content += [name]
		endif
	endfor
	call writefile(content, fn)
endfunc
```

再运行 LeaderF 之前先调用下，暂时解决了问题。

**Comment by Yggdroot** [comment]
解决了。忘了为什么把那一行删掉了。
可能是我当时认为`os.path.abspath`只是转化为绝对路径，路径已经是绝对路径了，就没必要了。
没想到它还有`os.path.normpath`的功能。

**Comment by skywind3000** [comment]
多谢。
