### ISSUE TITLE
希望leaderf function添加对类似funky正则匹配的支持，或者类似fzf#run扩展的支持，方便写插件

### ISSUE THREAD

**Issue by Joltik** [Yggdroot/LeaderF#461]

**Comment by Yggdroot** [comment]
哎，你这问题问的。如果我问你这个问题，你会怎么做呢？
很差指的是什么，性能差还是怎么差？如果不是性能差，你期望的结果是什么，怎样才是优化了的结果？

**Comment by Joltik** [comment]
抱歉，没说明白。。。

识别react的方法结构并没有很准确

这是使用[fzf-funky](https://github.com/tracyone/fzf-funky)识别出来的效果，方法结构与代码基本一直
![image](https://user-images.githubusercontent.com/51736940/71885921-4878ce00-3176-11ea-9637-97fcdc91dc0c.png)

这是使用LeaderfFunction识别出来的效果，与真实接口相差很大
![image](https://user-images.githubusercontent.com/51736940/71886239-d1900500-3176-11ea-800e-eee8c7ffe7bd.png)

**Comment by Joltik** [comment]
测试代码如下
`import React from 'react';
import {
  View,
  FlatList,
  TouchableWithoutFeedback,
  Text,
  Image,
  DeviceEventEmitter,
  StyleSheet,
  Dimensions,
  ImageBackground,
} from 'react-native';
import {connect} from 'react-redux';
import {common} from '../../constant/common';
import {
  requestMyProducts,
  loadMoreMyProducts,
  endRefreshing,
  requestAnnouncement,
} from '../../redux/actions/machine';
import {
  requestAllProducts,
  requestTotalProducts,
} from '../../redux/actions/buy_machine';
import {requesetUserAssets} from '../../redux/actions/user';
import BigNumber from 'bignumber.js';
import {USER_BUY_PRODUCTS_SUCCESS_KEY} from '../../constant/constant';
import MarqueeLabel from '../../components/MarqueeLabel';
import transfer from '../../localization/utils';
import {Overlay} from 'teaset';

const styles = StyleSheet.create({
  fonterContainer: {
    height: common.h40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fonterText: {
    color: '#999999',
    fontSize: common.font14,
  },
  topItem: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: common.margin10,
  },
  topItem_image: {
    width: common.w50,
    height: common.w50,
  },
  topItem_text: {
    fontSize: common.font14,
    color: '#4A4035',
  },
  item_container: {
    marginHorizontal: common.margin15,
    marginVertical: common.margin10,
    flexDirection: 'row',
  },
  item_container_left1: {
    fontSize: common.font20,
    color: common.themeColor,
  },
  item_container_left2: {
    fontSize: common.font20,
    color: common.themeColor,
    marginLeft: common.margin5,
  },
  item_container_centertext: {
    fontSize: common.font16,
    color: common.navTitleColor,
    marginVertical: common.margin5,
  },
  item_container_center_mid_text: {
    fontSize: common.font16,
    color: common.navTitleColor,
    marginVertical: common.margin5,
  },
  item_container_right_text1: {
    fontSize: common.font16,
    color: '#787878',
  },
  item_container_right_text2: {
    fontSize: common.font14,
    color: common.themeColor,
    marginTop: common.margin5,
  },
  item_bottom_line: {
    width: '100%',
    height: 0.5,
    backgroundColor: common.navBgColor,
    position: 'absolute',
    bottom: 0,
  },
  header_container: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: common.margin20,
  },
  header_container_bottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: common.margin20,
  },
  header_container_bottom_center: {
    fontSize: common.font20,
    fontWeight: 'bold',
    color: common.themeColor,
    marginLeft: common.margin20,
  },
  header_container_bottom_right: {
    width: common.w25,
    height: common.w25,
    paddingHorizontal: common.margin10,
    marginHorizontal: common.margin10,
  },
});

class Machine extends React.Component {
  static navigationOptions = (props, navigation) => {
    return {
      headerTitle: transfer(props.screenProps.language, 'machine04'),
      headerTintColor: common.navTitleColor,
      headerStyle: {
        backgroundColor: common.navBgColor,
        borderBottomWidth: 0,
        elevation: 0,
      },
      headerTitleStyle: {
        flex: 1,
        alignSelf: 'center',
        textAlign: 'center',
        fontSize: common.font17,
      },
    };
  };

  constructor(props) {
    super(props);
    this.state = {
      isShowAlert: false,
    };
  }

  componentDidMount() {
    this.refreshData();
    this.uiListener = DeviceEventEmitter.addListener(
      USER_BUY_PRODUCTS_SUCCESS_KEY,
      item => {
        setTimeout(() => {
          this.refreshData();
        }, 500);
      },
    );
    this.timer = setInterval(() => {
      this.props.dispatch(requestAnnouncement({language: this.props.language}));
    }, 60 * 1000);
  }

  componentWillUnmount() {
    this.uiListener.remove();
    if (this.timer) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }

  componentWillReceiveProps(nextProps) {
    if (
      !nextProps.isLoading &&
      nextProps.showAlert &&
      !this.state.isShowAlert
    ) {
      this.state.isShowAlert = true;
      // this.showAlert(0);
    }
  }

  showAlert(index) {
    this.hideAlert();
    let overlayView = (
      <Overlay.View style={{flex: 1}} modal={false} overlayOpacity={0}>
        <View
          style={{
            flex: 1,
            justifyContent: 'center',
            alignItems: 'center',
            padding: common.margin20,
          }}>
          <View
            style={{
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
              backgroundColor: 'black',
              opacity: 0.7,
            }}
          />
          <View
            style={{
              backgroundColor: common.themeColor,
              borderRadius: common.h5,
              paddingHorizontal: common.margin20,
              paddingVertical: common.margin30,
            }}>
            <TouchableWithoutFeedback
              onPress={() => {
                this.hideAlert();
              }}>
              <View
                style={{
                  position: 'absolute',
                  top: common.margin5,
                  right: common.margin5,
                  width: common.h44,
                  height: common.h44,
                  justifyContent: 'center',
                  alignItems: 'center',
                }}>
                <Image
                  style={{
                    width: common.w15,
                    height: common.w15,
                    tintColor: common.textColor,
                  }}
                  source={require('../../resource/assets/close_icon.png')}
                />
              </View>
            </TouchableWithoutFeedback>
            <Text
              style={{
                fontSize: common.font17,
                lineHeight: common.h28,
                color: common.textColor,
                marginTop: common.margin20,
              }}>
              {transfer(
                this.props.language,
                index == 0 ? 'alert_38' : 'alert_40',
              )}
            </Text>
            <TouchableWithoutFeedback
              onPress={() => {
                this.hideAlert();
                if (index == 1) {
                  setTimeout(() => {
                    const {navigation} = this.props;
                    navigation.navigate('BuyMachine');
                  }, 300);
                }
              }}>
              <View
                style={{
                  alignItems: 'center',
                  justifyContent: 'center',
                  backgroundColor: common.bgColor,
                  marginTop: common.margin20,
                  marginHorizontal: common.margin20,
                  paddingVertical: common.margin10,
                  borderRadius: common.h5,
                }}>
                <Text
                  style={{fontSize: common.font20, color: common.themeColor}}>
                  {transfer(this.props.language, 'alert_36')}
                </Text>
              </View>
            </TouchableWithoutFeedback>
          </View>
        </View>
      </Overlay.View>
    );
    this.overlayViewKeyID = Overlay.show(overlayView);
  }

  hideAlert() {
    if (this.overlayViewKeyID) {
      Overlay.hide(this.overlayViewKeyID);
      this.overlayViewKeyID = null;
    }
  }

  refreshData() {
    const {dispatch} = this.props;
    this.loadData();
    dispatch(endRefreshing());
    dispatch(
      requestTotalProducts({
        skip: 0,
        limit: 500,
        orderby: 'id',
      }),
    );
    dispatch(
      requestAllProducts({
        skip: 0,
        limit: 500,
        orderby: 'buy_price',
        where: {
          status: 'allow',
        },
      }),
    );
    dispatch(requestAnnouncement({language: this.props.language}));
    dispatch(requesetUserAssets({token_ids: ['*']}));
  }

  loadData() {
    const {dispatch, limit} = this.props;
    dispatch(
      requestMyProducts({
        skip: 0,
        limit: limit,
        orderby: ['status', 'id'],
      }),
    );
  }

  loadMoreData() {
    if (!this.props.hasNext || this.props.isLoadingMore) return;
    const {dispatch, page, limit} = this.props;
    dispatch(
      loadMoreMyProducts({
        skip: page * limit,
        limit: limit,
        orderby: ['status', 'id'],
      }),
    );
  }

  renderFooter = () => {
    if (this.props.myProducts.length < this.props.limit) return null;

    if (this.props.hasNext) {
      return (
        <View style={styles.fonterContainer}>
          <Text style={styles.fonterText}>
            {transfer(this.props.language, 'machine02')}
          </Text>
        </View>
      );
    } else {
      return (
        <View style={styles.fonterContainer}>
          <Text style={styles.fonterText}>
            {transfer(this.props.language, 'machine03')}
          </Text>
        </View>
      );
    }
  };

  renderItem(item, index) {
    const {allProductsNameDic, stateDic} = this.props;
    return (
      <TouchableWithoutFeedback onPress={() => {}}>
        <View style={{paddingVertical: common.margin10}}>
          <View style={styles.item_container}>
            <View style={{flex: 4}}>
              <View
                style={{
                  flexDirection: 'row',
                  justifyContent: 'flex-start',
                  alignItems: 'center',
                  marginBottom: common.margin10,
                }}>
                <Text style={styles.item_container_left1}>
                  {transfer(this.props.language, 'machine04')}
                </Text>
                <Text style={styles.item_container_left2}>
                  {allProductsNameDic[item.prod_id]
                    ? allProductsNameDic[item.prod_id]
                    : item.prod_id}
                </Text>
              </View>
              <Text style={styles.item_container_centertext}>{`${transfer(
                this.props.language,
                'machine05',
              )}：${common.removeInvalidZero(
                BigNumber(item.buy_price).toFixed(8, 1),
              )}`}</Text>
              <Text style={styles.item_container_center_mid_text}>{`${transfer(
                this.props.language,
                'machine06',
              )}：${common.removeInvalidZero(
                BigNumber(item.total_income).toFixed(8, 1),
              )}`}</Text>
            </View>
            <View
              style={{
                flex: 1,
                alignItems: 'center',
                justifyContent: 'space-between',
              }}>
              <ImageBackground
                style={{
                  width: common.getH(60),
                  height: common.getH(60),
                  justifyContent: 'center',
                  alignItems: 'center',
                }}
                resizeMode="cover"
                source={require('../../resource/assets/circle.png')}>
                <Text
                  style={
                    styles.item_container_right_text2
                  }>{`${common.removeInvalidZero(
                  BigNumber(item.fixed_rate)
                    .multipliedBy(100)
                    .toFixed(2, 1),
                )}%`}</Text>
              </ImageBackground>
              <Text style={styles.item_container_centertext}>
                {stateDic[item.status]}
              </Text>
            </View>
          </View>
          <View style={styles.item_bottom_line} />
        </View>
      </TouchableWithoutFeedback>
    );
  }

  listHeaderComponent = () => {
    const {announcement} = this.props;
    const content =
      announcement && announcement.content
        ? announcement.content.replace(/[\n\r]/g, '    ')
        : '';
    let mWidth = Dimensions.get('window').width;
    return (
      <View style={{flex: 1, backgroundColor: common.bgColor}}>
        {content && content.length > 0 ? (
          <TouchableWithoutFeedback
            onPress={() => {
              const {navigation} = this.props;
              navigation.navigate('Announcement', {
                content: announcement.content,
              });
            }}>
            <View
              style={{
                flexDirection: 'row',
                alignItems: 'center',
                justifyContent: 'center',
              }}>
              <View
                style={{
                  backgroundColor: common.bgColor,
                  width: common.getH(100),
                  height: '100%',
                  zIndex: 999,
                  borderWidth: 0,
                }}
              />
              <Image
                style={{
                  backgroundColor: common.bgColor,
                  width: 25,
                  height: '100%',
                  tintColor: common.navTitleColor,
                  zIndex: 999,
                }}
                resizeMode={'contain'}
                source={require('../../resource/assets/laba.png')}
              />
              <MarqueeLabel
                bgViewStyle={{width: mWidth - 100, height: 50}}
                speed={this.props.language == 'en' ? 40 : 60}
                textStyle={{
                  fontSize: common.font17,
                  color: common.navTitleColor,
                }}>
                {content}
              </MarqueeLabel>
              <View
                style={{
                  backgroundColor: common.bgColor,
                  width: common.getH(100),
                  height: '100%',
                  zIndex: 999,
                  borderWidth: 0,
                }}
              />
            </View>
          </TouchableWithoutFeedback>
        ) : null}
        <View style={styles.header_container}>
          <TouchableWithoutFeedback
            onPress={() => {
              this.showAlert(1);
            }}>
            <View style={styles.topItem}>
              <Image
                resizeMode="contain"
                style={styles.topItem_image}
                source={require('../../resource/assets/buy.png')}
              />
              <View
                style={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  height: common.h32,
                  borderRadius: common.h32 / 2,
                  paddingHorizontal: common.margin20,
                  backgroundColor: common.themeColor,
                  marginTop: common.margin20,
                }}>
                <Text style={styles.topItem_text}>
                  {transfer(this.props.language, 'machine09')}
                </Text>
              </View>
            </View>
          </TouchableWithoutFeedback>
          {/* <TouchableWithoutFeedback
            onPress={() => {
              const {navigation} = this.props;
              navigation.navigate('UpdateMachine');
            }}>
            <View style={styles.topItem}>
              <Image
                resizeMode="contain"
                style={styles.topItem_image}
                source={require('../../resource/assets/update.png')}
              />
              <View
                style={{
                  justifyContent: 'center',
                  alignItems: 'center',
                  height: common.h32,
                  borderRadius: common.h32 / 2,
                  paddingHorizontal: common.margin20,
                  backgroundColor: common.themeColor,
                  marginTop: common.margin20,
                }}>
                <Text style={styles.topItem_text}>
                  {transfer(this.props.language, 'machine10')}
                </Text>
              </View>
            </View>
          </TouchableWithoutFeedback> */}
        </View>
        <View
          style={{
            height: common.h5,
            backgroundColor: common.navBgColor,
            width: '100%',
          }}
        />
        <View style={styles.header_container_bottom}>
          <Text style={styles.header_container_bottom_center}>
            {transfer(this.props.language, 'machine12')}
          </Text>
          <TouchableWithoutFeedback
            onPress={() => {
              const {navigation} = this.props;
              navigation.navigate('MachineRecord');
            }}>
            <Image
              source={require('../../resource/assets/record.png')}
              style={styles.header_container_bottom_right}
              resizeMode={'contain'}
            />
          </TouchableWithoutFeedback>
        </View>
        <View
          style={{width: '100%', height: 1, backgroundColor: common.navBgColor}}
        />
      </View>
    );
  };

  render() {
    return (
      <View style={{flex: 1, backgroundColor: common.bgColor}}>
        <FlatList
          refreshing={this.props.isLoading}
          onRefresh={() => {
            this.loadData();
          }}
          keyExtractor={(item, index) => index.toString()}
          showsVerticalScrollIndicator={false}
          data={this.props.myProducts}
          ListHeaderComponent={this.listHeaderComponent()}
          renderItem={({item, index}) => this.renderItem(item, index)}
          onEndReachedThreshold={0.4}
          onEndReached={() => {
            this.loadMoreData();
          }}
          ListFooterComponent={this.renderFooter}
        />
      </View>
    );
  }
}

function mapStateToProps(state) {
  return {
    ...state.system,
    ...state.machine,
    allProductsNameDic: state.buy_machine.allProductsNameDic,
  };
}

export default connect(mapStateToProps)(Machine);`

**Comment by Yggdroot** [comment]
funky用的是正则表达式处理的，leaderf function用的是ctags的结果，是ctags支持的不够好。你看看用universal-ctags会不会好点。

**Comment by Joltik** [comment]
那有没有支持自定义source展示的接口？

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/issues/144 这里有教程
也可以用Python写，参考https://github.com/Yggdroot/LeaderF-marks
