### ISSUE TITLE
Leaderf! rg的搜索结果在'popup‘模式下不选中结果直接退出导致floating window出现异常

### ISSUE THREAD

**Issue by winter233** [Yggdroot/LeaderF#462]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-27b22526-64a7-4e92-9f8e-1f0b8288a453
Features: +acl +iconv +tui
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_WindowPosition = 'popup'
let g:Lf_CacheDirectory = '/home/winter/.cache'     " must be a absolute path
noremap \<C-J> :\<C-U>\<C-R>=printf("Leaderf! rg -e %s ", expand("\<cword>"))\<CR>
noremap \<C-I> :\<C-U>Leaderf! rg --recall\<CR>
### Describe your question, feature request, or bug.
不选任何Leaderf! rg的搜索结果，退出搜索结果，floating window的第一行和最后一行依然显示在屏幕上。如果此时退出Neovim（没有别的tab），会出现E5601: Cannot close window, only floating window would remain. 如果不退出，使用\<C-I>（前面的mapping）打开搜索结果，会出现以下error：
Error invoking 'python_execute' on channel 12 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/winter/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 788, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/winter/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 720, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/winter/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 703, in startExplorer
    super(RgExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/winter/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2026, in startExplorer
    self._bangEnter()
  File "/home/winter/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 624, in _bangEnter
    instance.window.cursor = (max(instance.cursorRow - instance.helpLength, 1), 0)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

### Steps to reproduce
使用\<C-J>搜索一个关键词，然后不选中任何搜索结果，直接退出。

**Comment by Yggdroot** [comment]
退出最好这样退出，normal模式下，用q，输入模式下，按esc。
执行Leaderf! rg命令，此时应该在normal模式下，你按下q就退出了。如果你用vim自己的命令，比如说：close，或者ctrl-w c，就会出现这个问题。
原因在于，Leaderf的窗口实际上是三个floating window，而floating window退出没有回调函数（vim的popup有），也没有窗口退出的autocmd，所以另外两个窗口无法知道中间的窗口退出了。

**Comment by Yggdroot** [comment]
如果你知道怎么让另外两个窗口能够知道中间的已经退出了，麻烦告知一下。

**Comment by winter233** [comment]
> 退出最好这样退出，normal模式下，用q，输入模式下，按esc。

我确实有个nmap \<C-D> :q\<C-R>，一直在使用这个快捷键。用q解决问题了

**Comment by winter233** [comment]
> 
> 
> 如果你知道怎么让另外两个窗口能够知道中间的已经退出了，麻烦告知一下。

不好意思，我也不清楚。
