### ISSUE TITLE
Leaderf file 崩溃

### ISSUE THREAD

**Issue by skywind3000** [Yggdroot/LeaderF#463]
![leaderf](https://user-images.githubusercontent.com/3035071/72049872-d087e080-32fa-11ea-9feb-53844b096fbb.png)

克隆我的仓库：

    git clone https://github.com/skywind3000/awesome-cheatsheets.git

用 gvim 打开 awesome-cheatsheets/editors/vim.txt

光标移动到第九行 “光标移动“ 这个文本区域，然后按 SHIFT+v 开始行选，一直往下到 58 行然后zf 创建折叠，等价命令时：

    call feedkeys(":9\<cr>V}}k", '')

这时行选了整个 “光标移动” 内容，然后 `zf` 创建代码折叠，让他们收起来，然后运行：

    Leaderf file

弹出 popup 窗口后，按 b 字母，立马崩溃

**Comment by Yggdroot** [comment]
确实可以复现。

**Comment by skywind3000** [comment]
居然还把我 vim.txt 的 buffer 给弄乱了。

**Comment by Deeperand** [comment]
我在使用Mru时碰到了类似的报错, 也是显示 "Missing: endif", 不清楚是不是因为源代码里少了一个 "endif" 之类的

**Comment by skywind3000** [comment]
有线索可以规避么？

**Comment by Yggdroot** [comment]
foldmethod不是manual应该就没问题。

**Comment by Yggdroot** [comment]
为什么你的评论在github上看不到？在我邮箱才能看到。

错误原因不是"Missing: endif"， 往上看看，真正的原因在上面。

Deeperand <notifications@github.com> 于2020年1月14日周二 下午11:47写道：

**Comment by Yggdroot** [comment]
> 有线索可以规避么？

发现如果不设置模式行：
```
# vim: set ts=4 sw=4 tw=0 noet noautoindent fdm=manual :
```
而是手动设置
`set ts=4 sw=4 tw=0 noet noautoindent fdm=manual`
做上面的操作就没问题。

**Comment by Yggdroot** [comment]
> > 有线索可以规避么？
> 
> 发现如果不设置模式行：
> 
> ```
> # vim: set ts=4 sw=4 tw=0 noet noautoindent fdm=manual :
> ```
> 
> 而是手动设置
> `set ts=4 sw=4 tw=0 noet noautoindent fdm=manual`
> 做上面的操作就没问题。

还是有问题。

**Comment by Yggdroot** [comment]
费了九牛二虎之力，不知道怎么最小化复现步骤，没法给vim提bug。

**Comment by skywind3000** [comment]
二分法也不行么？

**Comment by Yggdroot** [comment]
找到代码出问题的地方了，就是最小化问题时，就没问题了。

**Comment by roachsinai** [comment]
换一个terminal试试，之前有个问题在Konsole随即复现，在xfce-terminal, terminator百分百复现。😃

**Comment by Yggdroot** [comment]
> 换一个terminal试试，之前有个问题在Konsole随即复现，在xfce-terminal, terminator百分百复现。😃

gvim也有这个问题。

**Comment by Yggdroot** [comment]
@skywind3000 这个问题我复现不了了，用的是8.2.1525。我想是不是vim已经修复了这个潜在的bug，能否帮忙确认一下。

**Comment by skywind3000** [comment]
确认，应该是修复了。

**Comment by Yggdroot** [comment]
OK, 那close了。
