### ISSUE TITLE
After set Lf_UseVersionControlTool to 0,  why can I find more files ?

### ISSUE THREAD

**Issue by thinki** [Yggdroot/LeaderF#464]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim):  No output
- Output of `:echo &pythonthreedll`(only vim, not neovim): No output
- Output of `:py print(sys.version)`: E319: 抱歉，命令在此版本中不可用
- Output of `:py3 print(sys.version)`: E319: 抱歉，命令在此版本中不可用
- Output of `:echo g:Lf_Debug_Cmd`: 
E121: 未定义的变量: g:Lf_Debug_Cmd
E15: 无效的表达式: g:Lf_Debug_Cmd

- Output of `:echo g:Lf_FilesFromCache`: 
E121: 未定义的变量: g:Lf_FilesFromCache
E15: 无效的表达式: g:Lf_FilesFromCache

- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
If I use default setting, then I can only find below files
![image](https://user-images.githubusercontent.com/8175146/72241581-21ad1280-3622-11ea-9446-a88c0032419c.png)

If I set let g:Lf_UseVersionControlTool = 0, then I can find more files
![image](https://user-images.githubusercontent.com/8175146/72241918-127a9480-3623-11ea-8244-df5d28ffcf52.png)

**Comment by Yggdroot** [comment]
`:echo g:Lf_Debug_Cmd` after `Leaderf file`. You will know why.

**Comment by thinki** [comment]
> `:echo g:Lf_Debug_Cmd` after `Leaderf file`. You will know why.

**Comment by thinki** [comment]
@Yggdroot  Thanks for your quick reply. I do find that LeaderF will search for the git managed files if found version control tools context by default. 
`git ls-files  "." && git ls-files --others --exclude-standard  "."`

**Comment by Yggdroot** [comment]
> But I suggest to disable this feature by default since developer can't find the files not managed by version control tools, e.g. develop a new file.

`git ls-files --others --exclude-standard "."` can list the files not managed by git.

> Another situation is git repository containing git submodule, just like my case. I can't find any file in git submodule folder since git submodule files is not managed by upper layer git repo.

https://github.com/Yggdroot/LeaderF/blob/acef7dcd38b1cce6ca7f93fe45835fd0ef27cfa5/doc/leaderf.txt#L520-L526
