### ISSUE TITLE
Can leaderf file be made faster without using c extensions on Windows?

### ISSUE THREAD

**Issue by jdhao** [Yggdroot/LeaderF#466]
This is not a bug report, but rather a request.

 vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `nvim --version`: `NVIM v0.5.0-172-g1ff5b60cb`
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:py3 print(sys.version)`: 3.6.5
- Output of `:echo g:Lf_Debug_Cmd`:

    ```
    rg --no-messages --files   -g "!__pycache__" -g "!*.exe" -g "!*.dll" -g "!*.so" -g "!*.o" -g "!*.pyc" -g "!*.jpg" -g "!*.png" -g "!*.gif" -g "!*.db" -g "!*.tgz" -g "!*.tar.gz" -g "!*.gz" -g "!*.zip" -g "!*.bin" -g "!*.pptx" -g "!*.xlsx" -g "!*.docx" -g "!*.pdf" -g "!*.tmp" -g "!*.wmv" -g "!*.mkv" -g "!*.mp4" -g "!*.rmvb"
    ```

- Output of `:echo g:Lf_FilesFromCache`: 0
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

    ```vim
    " Do not use cache file
    let g:Lf_UseCache = 0

    " Ignore certain files and directories when searching files
    let g:Lf_WildIgnore = {
        \ 'dir': ['.git', '__pycache__', '.DS_Store'],
        \ 'file': ['*.exe', '*.dll', '*.so', '*.o', '*.pyc', '*.jpg', '*.png',
        \ '*.gif', '*.db', '*.tgz', '*.tar.gz', '*.gz', '*.zip', '*.bin', '*.pptx',
        \ '*.xlsx', '*.docx', '*.pdf', '*.tmp', '*.wmv', '*.mkv', '*.mp4',
        \ '*.rmvb']
        \}

    " Search files in popup window
    nnoremap <silent> <leader>f :Leaderf file --popup<CR>
    ```

### Describe your question, feature request, or bug.

When I use LeaderF under a folder for the first time, without the c extension, when I open a folder with 159 text files and use `LeaderF file --popup`, I have to wait about 3-4 seconds to see the result, which is a bit slow for me.

On Windows, it is not so easy to install Leaderf c extensions. Because we need to install msvc compilers, which uses about 3-4 Gb disk space. So I would rather use the pure Python implementation.

I have done a benchmark using Python to find text files under the same folder. It takes about 0.008 seconds to find all the textual files. I am not clear why it takes leaderf 3-4 seconds to show the files under this folder.

My benchmark code:

```python
import time
import os

dir_root = "d:\\code_exprt\\"

ignore_files = [
    "exe",
    "dll",
    "so",
    "o",
    "pyc",
    "jpg",
    "png",
    "gif",
    "db",
    "tgz",
    "tar.gz",
    "gz",
    "zip",
    "bin",
    "pptx",
    "xlsx",
    "docx",
    "pdf",
    "tmp",
    "wmv",
    "mkv",
    "mp4",
    "rmvb",
]
ignore_dirs = ['.git', '__pycache__', '.DS_Store']

start = time.time()
text_files = []
for root, dirs, files in os.walk(dir_root, topdown=True):
    dirs[:] = [d for d in dirs if d not in ignore_dirs]
    for filename in files:
        basename = os.path.basename(filename)
        ext = os.path.splitext(basename)[1][1:]

        if ext not in ignore_files:
            text_files.append(filename)
end = time.time()
print(end-start)
print(text_files, len(text_files))
```

**Comment by Yggdroot** [comment]
> When I use LeaderF under a folder for the first time, without the c extension, when I open a folder with 159 text files and use LeaderF file --popup, I have to wait about 3-4 seconds to see the result, which is a bit slow for me.

The C extension is used to enhance the matching speed, not the indexing speed. So you are using the command `rg --no-messages --files   -g "!__pycache__" -g "!*.exe" -g "!*.dll" -g "!*.so" -g "!*.o" -g "!*.pyc" -g "!*.jpg" -g "!*.png" -g "!*.gif" -g "!*.db" -g "!*.tgz" -g "!*.tar.gz" -g "!*.gz" -g "!*.zip" -g "!*.bin" -g "!*.pptx" -g "!*.xlsx" -g "!*.docx" -g "!*.pdf" -g "!*.tmp" -g "!*.wmv" -g "!*.mkv" -g "!*.mp4" -g "!*.rmvb"` to build the index even though there is no C extension. 

> On Windows, it is not so easy to install Leaderf c extensions. Because we need to install msvc compilers, which uses about 3-4 Gb disk space. So I would rather use the pure Python implementation.

You can compile c extension for python2. Download the compiler tool from https://www.microsoft.com/en-us/download/details.aspx?id=44266. It's not large.

**Comment by jdhao** [comment]
Thanks for the clarification. Then why does it take 3-4 seconds for me to see the indexing result since `rg` is used for indexing? On both Linux and MacOS where `rg` is installed, I saw the result instantly even on a larger code base with more than 200 files. Is this because of the performance difference of `rg` on different platforms?

What can I do to make the indexing speed faster?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/acef7dcd38b1cce6ca7f93fe45835fd0ef27cfa5/doc/leaderf.txt#L374-L382

You can set `let g:Lf_DefaultExternalTool = ""` so that LeaderF uses the build-in python implementation to index the files. It's not asynchronous, so it's maybe slow if the project is very large.
It may be faster if there are only hundreds of files.
