### ISSUE TITLE
leaderf每次f5刷新不能输入文字,不像第一次没有缓存的时候可以异步等待输入,实时筛选结果

### ISSUE THREAD

**Issue by avriltank** [Yggdroot/LeaderF#468]
如题,如果文件目录数量不大的话,很快就能刷新出来.但是比如我刷新/或者~目录的话,要等几分钟.这就造成了vim一直假死的状态.

**Comment by Yggdroot** [comment]
可以不用缓存就不用刷新了。具体参考https://github.com/Yggdroot/LeaderF/issues/161
