### ISSUE TITLE
Is that possible for LeaderF to ignore certain path?

### ISSUE THREAD

**Issue by jzhang012** [Yggdroot/LeaderF#47]
Is that possible for LeaderF to ignore certain path? 

for example, 'node_modules' which contains a lot of files and require quite a bit time to cache and refresh but are rarely useful.

**Comment by Yggdroot** [comment]
Please refer to [Here](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L138).

**Comment by jzhang012** [comment]
thanks man. sorry didn't read the manual carefully before.
