### ISSUE TITLE
[Feature request] Jump to existing window in buffer mode

### ISSUE THREAD

**Issue by codeclem** [Yggdroot/LeaderF#471]
CtrlP and fzf.vim have an option where if the selected buffer is already open in a window somewhere, it will jump to that window instead of opening it in the current window. (https://github.com/junegunn/fzf.vim/issues/98) This would be really nice to have in LeaderF.

Edit: After some more thought, what I really want is an entirely new `window` mode that lists and jumps to open windows. Buffer mode should remain as it is.

**Comment by Yggdroot** [comment]
Add an option `g:Lf_JumpToExistingWindow`.
