### ISSUE TITLE
Not opening collapsed sections when selecting match

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#473]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
I work in popup mode with LeaderfLine.

### Describe your question, feature request, or bug.
Hi,
when I select a match using `<CR>`, if it lies inside a collapsed region, it goes to the correct line in the buffer, but it doesn't display it. It displays only the collapsed header of the region. 
Similarly to here: 

https://user-images.githubusercontent.com/23480511/70097849-0a4a3500-1633-11ea-9e1b-b05133e4f778.png

(enter wouldn't display the internals of the function)

So, I need to press 'zA' to make it happen. 

I think the relevant code is `python/leaderf/lineExpl.py` in the function `_acceptSelection` , but adding `lfCmd('norm! zA')` there did nothing.

**Comment by Yggdroot** [comment]
I can not reproduce it. I think the fix of #417 has already fix it.

**Comment by eyalk5** [comment]
It was fixed in the preview,but when I press enter to go to the section, it jumps to the location collapsed.

To reproduce:

open a new file.
Do :set foldmethod=manual
Pick some lines in <shift-v> and do zf. It will create a fold.
now search for something inside the fold using LeaderFLine. Now select it by pressing <CR>. It would close leaderf, jump to the current line in the file, but it would still be collapsed.

**Comment by Yggdroot** [comment]
Still can not reproduce it.
![1](https://user-images.githubusercontent.com/2705841/73619182-25531880-4667-11ea-947c-7b65b1abdf3a.gif)

**Comment by obxhdx** [comment]
The same happens to me. In some files I use the following modeline:
`vim: set foldmethod=marker foldenable :`.

I'm currently doing:
1. `Leaderf line`
2. Select some entry with `<CR>`

Then my cursor jumps to the correct place in the file, but the fold doesn't open automatically.

**Comment by eyalk5** [comment]
In the end I typed zA. 
![nvim3](https://user-images.githubusercontent.com/23480511/73687264-4d2b9600-46d2-11ea-9adc-f2c60665a691.gif)
