### ISSUE TITLE
[Feature request] support to storage gtags db in project directory

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#474]
### Describe your question, feature request, or bug.
There are some not very important reasons to storage gtags db in project directory instead of cache directory. It's better to let users have more choices:
1. It's easy to share gtags db with other tools. (eg. vscode, that old gtags plugin can only storage gtags db under project root).
2. When code files are changed by external tools, like `git pull`, gtags db is not updated automatically. It's easy to update it using `global -u` (by script or manually) when gtags db is under project root path.
3. one of my environment has restore point. cache files gone after reboot. So, i have to maintain different cache directory in the config file. If gtags db can follow with project, i don't need to do that (other cache files are not too big to care).

**Comment by Yggdroot** [comment]
Done.
