### ISSUE TITLE
How to set mappings for c-p and c-n to navigate?

### ISSUE THREAD

**Issue by oxysoft** [Yggdroot/LeaderF#476]
I wish to use `c-p` and `c-n` to navigate the entries instead of `c-j` and `c-k`. This is what I tried...

	let g:Lf_NormalMap = {
		\ "File":   [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>'],
		\            ["<F6>", ':exec g:Lf_py "fileExplManager.quit()"<CR>'],
		\            ["<C-n>", ':exec g:Lf_py "fileExplManager._toUpInPopup()"<CR>'],
		\            ["<C-p>", ':exec g:Lf_py "fileExplManager._toDownInPopup()"<CR>']
		\           ],
		\ "Buffer": [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>'],
		\            ["<F6>", ':exec g:Lf_py "bufExplManager.quit()"<CR>'],
		\            ["<C-n>", ':exec g:Lf_py "bufExplManager._toUpInPopup()"<CR>'],
		\            ["<C-p>", ':exec g:Lf_py "bufExplManager._toDownInPopup()"<CR>']
		\           ],
		\ "Mru":    [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>'],
		\            ["<C-n>", ':exec g:Lf_py "mruExplManager._toUpInPopup()"<CR>'],
		\            ["<C-p>", ':exec g:Lf_py "mruExplManager._toDownInPopup()"<CR>']
		\           ],
		\ "Tag":    [],
		\ "BufTag": [],
		\ "Function": [],
		\ "Line":   [],
		\ "History":[],
		\ "Help":   [],
		\ "Self":   [],
		\ "Colorscheme": []
		\}

Didn't work. How can I achieve this this?

**Comment by tamago324** [comment]
In LeaderF's insert mode?
If so, use `g:Lf_CommandMap`.

If you want to use `<C-n>` as `<C-j>` and `<C-p>` as `<C-k>`, use the following mapping.

```vim
let g:Lf_CommandMap = {
\   '<C-k>': ['<C-p>'],
\   '<C-j>': ['<C-n>'],
\}
```

Refer #236

**Comment by oxysoft** [comment]
Leaderf's insert mode yup. That looks a lot simpler, however that still doesn't work for me sadly.

**Comment by tamago324** [comment]
Umm....
How to reproduce it?
What's the OS? vim or nvim?

**Comment by oxysoft** [comment]
Sorry, false alarm!! I just reloaded my neovim with none of my mappings loaded and it works all good now! Should have done that sooner, I will investigate where the conflict is happening now.

**Comment by tamago324** [comment]
OK! Thanks.
