### ISSUE TITLE
Leaderf line --regexMode --input的参数不能用regex表达式？

### ISSUE THREAD

**Issue by ChenWeird** [Yggdroot/LeaderF#477]
- vim or neovim? 
    - [ x ] vim
    - [  ] neovim
- Output of `vim --version` or `nvim --version`:

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 29 2019 23:21:03)
MS-Windows 64-bit GUI version 带 OLE 支持
包含补丁: 1-57
 
- Output of `:echo has("python")`: 
0

- Output of `:echo has("python3")`: 
1

- Output of `:echo &pythondll`(only vim, not neovim): 
python27.dll

- Output of `:echo &pythonthreedll`(only vim, not neovim): 
python37.dll

- Output of `:py print(sys.version)`: 
无法加载python27.dll

- Output of `:py3 print(sys.version)`: 
3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]

- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

    `noremap <leader>toc :Leaderf! line --regexMode --left --input #<CR>`

### Describe your question, feature request, or bug.

希望用上述的map生成markdown文档的目录，但是提示--input参数错误

### Steps to reproduce

`<leader>toc`

### Actual behaviour

出现如下错误提示：
```
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
usage: Leaderf[!] line [-h] [--all] [--reverse] [--stayOpen] [--input <INPUT> | --cword]
                       [--top | --bottom | --left | --right | --belowright | --aboveleft | --fullScreen | --popup]
                       [--nameOnly | --fullPath | --fuzzy | --regexMode] [--nowrap] [--next | --previous]
                       [--recall] [--popup-height <POPUP_HEIGHT>] [--popup-width <POPUP_WIDTH>]
Leaderf[!] line: error: argument --input: expected 1 argument
```

### Expected behaviour

希望生成markdown文档的目录。

使用以下分步执行可以正常实现：
```
:Leaderf line --regexMode --left
\_s*\_^#\+
<tab>
```

**希望能用类似下述的map快速打开，--input参数是regex表达式，但好像不行，特求教如何使用--input参数：**
`noremap <leader>toc :Leaderf! line --regexMode --left --input \_s*\_^#\+<CR>`
其中`\_s*\_^#\+`是regex：以1个或多个`#`开头的行（无论其前面是否有空格）

**Comment by ChenWeird** [comment]
**或许更好的问题是：如何用Leaderf打造markdown的TOC？**

目前看到的相关vim plugin实现及其问题：
1.  `Plug 'vim-pandoc/vim-pandoc' `: 问题是打开关闭TOC多次后，会莫名其妙地将文档设置为nomodifialbe
2. `Plug 'plasticboy/vim-markdown'`: 问题是TOC生成的不完整，对于较长的文档，经常只显示前面一部分。
3.  `Plug 'majutsushi/tagbar'` 和 `Plug 'lvht/tagbar-markdown'`: 要安装好多东西

若Leaderf能整合TOC就完美了。

**Comment by tamago324** [comment]
Thank you for your report.
It might be a bug.
It seems that comments after `#` are parsed as comments.

**Comment by tamago324** [comment]
Hi @Yggdroot.

It is selfish, but I investigated.

`"#"` is the default for `self.commenters` in the `shlex` class. 
Also mentioned in the [shlex documentation](https://docs.python.org/3/library/shlex.html#shlex.shlex.commenters)
> shlex.commenters
> The string of characters that are recognized as comment beginners. All characters from the comment beginner to end of line are ignored. Includes just '#' by default.

There are two possible solutions:

#### 1. set `self.commenters = ""`

https://github.com/Yggdroot/LeaderF/blob/acef7dcd38b1cce6ca7f93fe45835fd0ef27cfa5/autoload/leaderf/python/leaderf/anyExpl.py#L530-L532

Add one line.

```py
  def split(self): 
      self.whitespace_split = True 
+     self.commenters = ""
      return list(self) 
```


#### 2. It seems that it is necessary to eliminate `comenters` processing of `read_token()`.

Delete the following two processes.

https://github.com/Yggdroot/LeaderF/blob/acef7dcd38b1cce6ca7f93fe45835fd0ef27cfa5/autoload/leaderf/python/leaderf/anyExpl.py#L423-L425

https://github.com/Yggdroot/LeaderF/blob/acef7dcd38b1cce6ca7f93fe45835fd0ef27cfa5/autoload/leaderf/python/leaderf/anyExpl.py#L493-L501


Thanks.

**Comment by ChenWeird** [comment]
感谢更新！--input已经可以使用带有`#`的regex了。但是发现了一个相关的新问题：`:Leaderf line --regexMode`对于空格的检索好像有点问题（该问题与本次升级无关，新旧版本都存在）

**问题描述：**
```
example，下面一行：先是几个空格，然后#等
    # Git
```

1. 使用`:Leaderf line --regexMode`搜索
2. 输入`\s\+#`，无法检索出行`    #Git`

但如果我使用vim的`/`进行搜索`/\s\+#`，却可以搜索到该行。


**背景介绍：**
我的核心目的是构建markdown文档的TOC，但以下定义无法排除文档中类似`    #Git`等带有缩进的非header的代码行。
```
noremap <leader>fc :Leaderf line --regexMode --input \(\s\+\)\@<!\_^#\+\s\+.*<CR>
```

**Comment by tamago324** [comment]
OK.
I will also look at `--refexMode`.

**Comment by Yggdroot** [comment]
It's a bug, I have fixed it.

**Comment by tamago324** [comment]
Thank you!

**Comment by ChenWeird** [comment]
Thanks! It works!
