### ISSUE TITLE
Typing in the prompt is slow

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#48]
I have 22000 files in my project (don't know if it has an impact or not for this issue) and typing in the prompt is pretty slow, like 0.5~1s slow, each time you hit a key.

I can understand that it's slow when it's filtering, but it's also slow when using the arrow keys, which gives a poor user experience in the end.

If I hit ESC then it's quick as in a regular vim buffer.

**Comment by Yggdroot** [comment]
Does this happen always? If you don't type any characters except for `<UP>` and `<Down>`, is it also slow then?
In theory, 22000 files are not many for LeaderF.

**Comment by MightyCreak** [comment]
100% repro, it's always slow for any character I type, even without any filter, up and down feel sluggish.

I'll try tomorrow without any plugin except LeaderF (currently I have vim-sensible, vim-bufkill, vim-fswitch, editorconfig and nerdcommenter, managed with vundle)

**Comment by Yggdroot** [comment]
Maybe you are using a slow terminal.

**Comment by MightyCreak** [comment]
Ha! You're thought make me think of something, and I think that's the problem!
I'm using MacVim, so it's not in a terminal. When I use Vim in the terminal, it is as fast as it should be.

So there must be something conflicting between the GUI and LeaderF. But it's really LeaderF the problem, because MacVim is as fast as the terminal for every other commands, it's just when typing in the "filter field" of LeaderF that every input is slow (but if I hit esc to have control in the LeaderF window, it's fast again)

**Comment by Yggdroot** [comment]
Please set in your vimrc like this: `let g:Lf_CursorBlink = 0`.

**Comment by MightyCreak** [comment]
It's the same with this line. Do you have the same problem if you run the gui?

**Comment by Yggdroot** [comment]
Did you update the plugin? If no, please update the plugin and set this line. 
No, I never tested it on Mac OS. But on linux and windows, it works well for  both GUI and terminal.

**Comment by MightyCreak** [comment]
Yup, I updated it (see my last edit ;) )

**Comment by MightyCreak** [comment]
I've tested on Fedora with gVim and I don't see any slowdown. So it seems to be a problem with MacVim 😞 🍎 💩

**Comment by Yggdroot** [comment]
This is a known issue, the same as https://groups.google.com/forum/#!searchin/vim_mac/getchar%7Csort:relevance/vim_mac/5adx7eFV_fU/BAJMrdzkFDkJ
I don't know why MacVim devs do not fix it.

**Comment by Yggdroot** [comment]
Workaround: `let g:Lf_CursorBlink = 0`

**Comment by MightyCreak** [comment]
The workaround works very well for me!

I guess a simple mention of this workaround in the README for us, poor MacVim users, would be enough to close this bug.

**Comment by ichizok** [comment]
It works fine with this and https://github.com/macvim-dev/macvim/issues/522#issuecomment-334942713 patches on my environment.

```diff
--- a/autoload/leaderf/python/leaderf/cli.py
+++ b/autoload/leaderf/python/leaderf/cli.py
@@ -140,11 +140,11 @@ class LfCli(object):

         if self._is_fuzzy:
             if self._is_full_path:
-                lfCmd("echohl Constant | redraw | echon '>F> ' | echohl NONE")
+                lfCmd("echohl Constant | echon '>F> ' | echohl NONE")
             else:
-                lfCmd("echohl Constant | redraw | echon '>>> ' | echohl NONE")
+                lfCmd("echohl Constant | echon '>>> ' | echohl NONE")
         else:
-            lfCmd("echohl Constant | redraw | echon 'R>> ' | echohl NONE")
+            lfCmd("echohl Constant | echon 'R>> ' | echohl NONE")

         lfCmd("echohl Normal | echon '%s' | echohl NONE" %
               escQuote(''.join(self._cmdline[:self._cursor_pos])))
@@ -155,6 +155,7 @@ class LfCli(object):
                   escQuote(''.join(self._cmdline[self._cursor_pos+1:])))
         else:
             lfCmd("echohl Lf_hl_cursor | echon ' ' | echohl NONE")
+        lfCmd("redraw")

     def _buildPattern(self):
         if self._is_fuzzy:
```

In MacVim there is the lesser frequency of I/O flushing than other gvim in order to avoid screen flickering, and I think it is hard to improve this behavior (the strategy of screen updating) of MacVim.
Thus, in regard to the above (do `redraw`), I think it is better to fix it.

**Comment by Yggdroot** [comment]
It works like a charm, thanks a lot.
Appreciate it if the patch can be merged into macvim.

**Comment by Yggdroot** [comment]
The patch of Macvim is [merged](https://github.com/macvim-dev/macvim/pull/560), now this issue is completely fixed.
