### ISSUE TITLE
track jumps  

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#480]
- vim or neovim? 
    - [ ] vim
    - [ X] neovim
- Operating system: 
    - [ ] Linux
    - [ X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

 
 let g:Lf_PreviewInPopup =1
 let g:Lf_PreviewResult = {
			\ 'File': 0,
			\ 'Buffer': 0,
			\ 'Mru': 0,
			\ 'Tag': 0,
			\ 'BufTag': 1,
			\ 'Function': 1,
			\ 'Line': 1,
			\ 'Colorscheme': 0,
			\ 'Rg' : 1
			\}

### Describe your question, feature request, or bug.
Currently, after I enter LeaderfLine, if I select a new location, the old location doesn't appear in the jump list and I can't get back to it('' or ctrl-o) . To save it in the jump list, one can do, `m'`. It would be nice to do so only in case the user doesn't press ESC . 
(I have added this before running it in the mapping, which is kind of OK)

**Comment by Yggdroot** [comment]
Fixed.
