### ISSUE TITLE
whitelist files that are in .gitignore?

### ISSUE THREAD

**Issue by jameswillett** [Yggdroot/LeaderF#481]
this is almost an edge behavior, but in some projects i have files in my .gitignore that i need to jump to somewhat frequently. usually they are local configs at the project root where i usually have vim running, so its no big deal to do `:e .someconfig` but it would be nice to be able to do everything in leaderf if possible

**Comment by Yggdroot** [comment]
You can have a try `Leaderf file --no-ignore`.

**Comment by jameswillett** [comment]
well i would like to whitelist _some_ files, not all files. is that at all possible?

**Comment by Yggdroot** [comment]
Currently, there are two ways to work around it. 
1. Use `Leaderf file --file files_list.txt`, all the files and some files in .gitignore can be written to files_list.txt(can be any name).
2. Use `g:Lf_ExternalCommand`.
