### ISSUE TITLE
The statusline and inputline will not quit if using ":q" to quit leaderf popup window

### ISSUE THREAD

**Issue by linjiX** [Yggdroot/LeaderF#482]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
编译者 brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:py3 print(sys.version)`: 
```
3.7.4 (default, Sep 24 2019, 17:13:17)
[Clang 10.0.1 (clang-1001.0.46.4)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowPosition = 'popup'
```

### Describe your question, feature request, or bug.
A leaderf popup window has three part:
- Upper part is to display input text
- Middle part is to display search result
- Lower part is to display status

If the cursor is in the middle part in normal mode, and using `:q` to quit.
Only middle part is quit, and upper part and lower part will stuck on the screen and not easy to clean them.

Here is the snapshot:
<img width="1440" alt="截屏2020-02-01下午5 11 44" src="https://user-images.githubusercontent.com/46097255/73589787-fbd6a780-4515-11ea-9463-d72f50c73da1.png">

### Steps to reproduce
- `nvim <some file>`
- `Leaderf! file`
- `:q`

### Actual behaviour
As described above.

### Expected behaviour
After `:q`, the whole leaderf window should dispear from the screen.

**Comment by Yggdroot** [comment]
You should use `q` to quit. Because in neovim, there is no way to know whether a window is closed.

**Comment by linjiX** [comment]
Is that means map `:q` to `q` is a good solution?

**Comment by Yggdroot** [comment]
No. `:q`, `:quit`, `:close`, `ctrl-w c` are the commands of vim to close a window, `q` is normal mode command of LeaderF to quit.
