### ISSUE TITLE
Leaderf popup window will produce lots of useless "[Scratch]" buffers

### ISSUE THREAD

**Issue by linjiX** [Yggdroot/LeaderF#483]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
编译者 brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`:
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:py3 print(sys.version)`: 
```
3.7.4 (default, Sep 24 2019, 17:13:17)
[Clang 10.0.1 (clang-1001.0.46.4)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowPosition = 'popup'
```

### Describe your question, feature request, or bug.
Every time the leaderf popup window appears, it will create a "[Scratch]" buffer.
After the popup window is closed, the "[Scratch]" buffer will not be removed.

Also the next time the leaderf popup window appears, the previous "[Scratch]" buffer will not be reused. Instead it will create a new one.

After using leaderf multiple times, there will be full of useless "[Scratch]" buffers in the buffer list.

### Steps to reproduce
- `nvim <some file>`
- `:Leaderf file` and quit leaderf, do it many times.
- `ls!`

### Actual behaviour
As describe above.

### Expected behaviour
The number of "[Scratch]" buffer should not increase with using leaderf.

**Comment by Yggdroot** [comment]
Fixed.
