### ISSUE TITLE
Windows: Build failed when the IDE is not installed

### ISSUE THREAD

**Issue by 9527KGG** [Yggdroot/LeaderF#485]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 28 2019 22:02:54)
MS-Windows 64-bit console version
Included patches: 1-1415
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
+acl                +eval               +multi_byte_ime/dyn +termguicolors
+arabic             +ex_extra           +multi_lang         +terminal
+autocmd            +extra_search       +mzscheme/dyn       -termresponse
+autochdir          -farsi              -netbeans_intg      +textobjects
+autoservername     +file_in_path       +num64              +textprop
-balloon_eval       +find_in_path       +packages           -tgetent
+balloon_eval_term  +float              +path_extra         +timers
-browse             +folding            +perl/dyn           +title
++builtin_terms     -footer             +persistent_undo    -toolbar
+byte_offset        +gettext/dyn        -postscript         +user_commands
+channel            -hangul_input       +printer            +vartabs
+cindent            +iconv/dyn          +profile            +vertsplit
+clientserver       +insert_expand      +python/dyn         +virtualedit
+clipboard          +job                +python3/dyn        +visual
+cmdline_compl      +jumplist           +quickfix           +visualextra
+cmdline_hist       +keymap             +reltime            +viminfo
+cmdline_info       +lambda             +rightleft          +vreplace
+comments           +langmap            +ruby/dyn           +vtp
+conceal            +libcall            +scrollbind         +wildignore
+cryptv             +linebreak          +signs              +wildmenu
+cscope             +lispindent         +smartindent        +windows
+cursorbind         +listcmds           +startuptime        +writebackup
+cursorshape        +localmap           +statusline         -xfontset
+dialog_con         +lua/dyn            -sun_workshop       -xim
+diff               +menu               +syntax             -xpm_w32
+digraphs           +mksession          +tag_binary         -xterm_save
-dnd                +modify_fname       -tag_old_static
-ebcdic             +mouse              -tag_any_white
+emacs_tags         -mouseshape         +tcl/dyn
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
Linking: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib /PDB:vim.pdb -debug
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python37.dll
- Output of `:py print(sys.version)`: E370: could not load python27.dll
- Output of `:py3 print(sys.version)`: 3.7.2 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [*] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

let g:kgg_leaderf = 1 "control leaderf

### Describe your question, feature request, or bug.
Bug: Windows: Build failed when the IDE is not installed

### Steps to reproduce
On https://visualstudio.microsoft.com/downloads/, do not install IDE.
Instead, goto "Tools for Visual Studio 2019" -> Install "Build Tools for Visual Studio 2019"
Try to install leaderF

### Actual behaviour
Begin to compile C extension of Python2 ...
Python 2 not found!
Installed Pythons found by py Launcher for Windows
 -3.7-64 *

Requested Python version (2) not installed, use -0 for available pythons

Begin to compile C extension of Python3 ...
running build
running build_ext
building 'fuzzyMatchC' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

### Expected behaviour
Because  "Build Tools for Visual Studio 2019" has all compiler/libraries, installation should succeed.
LeaderF has no reason to require user to install IDE.
As a comparison, Youcomplete installation could succeed.

**Comment by Yggdroot** [comment]
This is not a bug, you can still use LeaderF even without the C extension.
This is actually the issue of how to compile the C extension for python3.7 on Windows, it is a common issue, not LeaderF specific.
Please refer to https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat , 
```
Run python.exe to display which version of VC++ it was compiled with (example shown below).

It is important to use the corresponding version of the Visual C++ compiler that Python was compiled with since distilutils's get_build_version prevents mixing versions (per Piotr's warning).

Yellow (top) is Python 2.7, compiled with MSC v.1500 (Visual Studio C++ 2008)
Red (bottom) is Python 3.4.1, compiled with MSC v.1600 (Visual Studio C++ 2010)
Example from the command line showing Python 2.7 compiled with MSC v.1500 and Python 3.4.1 compiled with MSC v.1600

Use the table below[1] to match the internal VC++ version with the corresponding Visual Studio release:

MSC v.1000 -> Visual C++ 4.x        
MSC v.1100 -> Visual C++ 5          
MSC v.1200 -> Visual C++ 6          
MSC v.1300 -> Visual C++ .NET       
MSC v.1310 -> Visual C++ .NET 2003  
MSC v.1400 -> Visual C++ 2005  (8.0)
MSC v.1500 -> Visual C++ 2008  (9.0)
MSC v.1600 -> Visual C++ 2010 (10.0)
MSC v.1700 -> Visual C++ 2012 (11.0)
MSC v.1800 -> Visual C++ 2013 (12.0)
MSC v.1900 -> Visual C++ 2015 (14.0)
MSC v.1910 -> Visual C++ 2017 (15.0)
MSC v.1911 -> Visual C++ 2017 (15.3)
MSC v.1912 -> Visual C++ 2017 (15.5)
MSC v.1913 -> Visual C++ 2017 (15.6)
MSC v.1914 -> Visual C++ 2017 (15.7)
MSC v.1915 -> Visual C++ 2017 (15.8)
MSC v.1916 -> Visual C++ 2017 (15.9)   
Download and install the corresponding version of Visual Studio C++ from the previous step.
Additional notes for specific versions of VC++ are listed below.
```
On my machine, `py -3` print the following message:
```
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 22:20:52) [MSC v.1916 32 bit (Intel)] on win32
```
, so `Visual C++ 2017 (15.9)` is needed.

There is no doubt that build the C extention for python3 is embarrassing, usually you have to download and install several GBs of the build tool. Fortunately, LeaderF still works by using python2,
and buiding the C extension for python2.7 is much easier.

You should install python2.7 and make sure `:echo has("python")` is 1 in vim. Download the Microsoft Visual C++ Compiler for Python 2.7 from https://www.microsoft.com/en-us/download/details.aspx?id=44266 , it's only 83.8M.

At last, don't forget set 
```vim
let g:Lf_PythonVersion = 2
```

**Comment by 9527KGG** [comment]
Thanks, I will give a try.

One quick thing: without the C extension, I think the performance would be much lower. So without the C extension, it's practically not usable for large project. This is the major reason I use Leader over CtrlP, whose perf is too low to use, on large project.

**Comment by 9527KGG** [comment]
After some more trials, I don't think what you mentioned is correct ^_^. But still thanks, anyway.

Here is my observation: 
On one of my other machine, which has VS2019 Enterprise IDE and python 3.7.5 installed, leaderF "fuzzyMatchC" can be built correctly. Python 3.7.5 is built by VS2017, etc

Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)] on win32

On the machine which hit the issue, it has python 3.7.2 installed.

Then I uninstalled 3.7.2 and install 3.7.5. Then leaderF "fuzzyMatchC" can be built correctly. Everything works fine.

**Comment by 9527KGG** [comment]
Close
