### ISSUE TITLE
Cannot add custom bindings for case-sensitive bind ids

### ISSUE THREAD

**Issue by svermeulen** [Yggdroot/LeaderF#487]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`:  neovim v0.4.3 and neovim-qt (commit 70f402b)
- Operating system: 
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

I had to make the following change to LeaderF to get custom bindings working:

https://github.com/svermeulen/LeaderF/commit/0a2264b0e144aed4cb187d4a0a56e7e8c5f5c320

This is because in order to add a binding for cmd+v using macos with neovim-qt, I need to specifically use `<D-v>` and not `<D-V>`.  LeaderF currently automatically uppercases the key binding making `<D-v>` impossible.

**Comment by svermeulen** [comment]
Also see [here](https://github.com/Kethku/neovide/issues/90) where one of the neovim maintainers  says that `<D-m>` and `<D-M>` have different intended meanings

**Comment by Yggdroot** [comment]
>  LeaderF currently automatically uppercases the key binding making <D-v> impossible.

It's not because of this, it is because of #428 .
