### ISSUE TITLE
crash in Win10, E716, E171

### ISSUE THREAD

**Issue by mzlogin** [Yggdroot/LeaderF#49]
![image](https://cloud.githubusercontent.com/assets/1646590/25164873/0ced88be-2506-11e7-9543-a4b367f2c7e4.png)

Win10, Vim 8.0, Python 2.7.13

**Comment by Yggdroot** [comment]
What is your configuration about LeaderF in vimrc?

**Comment by mzlogin** [comment]
```viml
" LeaderF
nnoremap <silent> <leader>m :LeaderfMru<CR>
let g:Lf_DefaultMode = 1
let g:Lf_IndexTimeLimit = 1200
```

**Comment by Yggdroot** [comment]
It's weird. Can it be reproduced 100% ?
Could you please tell me the `pwd` and the steps of reproducing?

**Comment by Yggdroot** [comment]
Oh, I find the root cause.
`g:Lf_DefaultMode` has been changed, please refer to [here](https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L92).

**Comment by mzlogin** [comment]
It's OK now after I update my configuration. Thx.
