### ISSUE TITLE
win10+nvim环境，leaderf gtags --update执行失败

### ISSUE THREAD

**Issue by Chillbon** [Yggdroot/LeaderF#490]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
nvim v0.5.0-356-gead61e5a5
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.7.6 （tags/v3.7.6：43364a7ae0，Dec 19 2020，00:42:30）[MSC v.1916 64 bit (AMD)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

win10+nvim环境，leaderf gtags --update执行失败
返回：
gtags：nextkey not found in GPATH
gtags errors

**Comment by Yggdroot** [comment]
复现步骤是怎样的？用最新版的gtags试一下。
你的Leaderf相关配置是怎样的？
