### ISSUE TITLE
LeaderfHelp will not update after other plugin lazy load by vim-plug

### ISSUE THREAD

**Issue by linjiX** [Yggdroot/LeaderF#491]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
编译者 brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:py3 print(sys.version)`: 
```
3.7.4 (default, Oct 27 2019, 01:01:25)
[Clang 11.0.0 (clang-1100.0.33.8)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vim
" mini reproduce vimrc
call plug#begin('~/.vim/plug')
Plug 'majutsushi/tagbar', {'on': 'Tagbar'}
Plug 'Yggdroot/LeaderF', {'do': './install.sh'}
call plug#end()

let g:Lf_UseMemoryCache = 0
let g:Lf_UseCache = 0
```

### Describe your question, feature request, or bug.
vim-plug has lazy load feature which can load plugins after executing specific command.
After loading a plugin into vim, its help tags will also be loaded into vim.
But those tags will not be updated into `LeaderfHelp`

### Steps to reproduce
1. Save above vimrc as `minivimrc`
2. `nvim <anyfile> -u minivimrc`
3. `:LeaderfHelp`, check there is no tags about `Tagbar`
4. `:Tagbar`, trigger lazy load of vim-plug
5. `:LeaderfHelp`, check there is still no tags about `Tagbar`

### Actual behaviour
As described above.

### Expected behaviour
LeaderfHelp list should be updated after loading a new plugin into vim.

**Comment by Yggdroot** [comment]
You should use `<F5>`  to refresh the result if you find it is not up to date.

**Comment by linjiX** [comment]
Yes `<F5>` works.
Also I wonder how to map `<F5>` to other keys?

**Comment by Yggdroot** [comment]
please read the bottom of the readme.

**Comment by linjiX** [comment]
I found the map method, my issue is gone.
Thank you very much~~
