### ISSUE TITLE
LeaderF is discarding local settings in neovim

### ISSUE THREAD

**Issue by krage** [Yggdroot/LeaderF#492]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `nvim --version`: 
```
NVIM v0.5.0-360-g1f479fffb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DUTF8PROC_STATIC -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: `0`
- Output of `:echo has("python3")`: `1`
- Output of `:py3 print(sys.version)`: `3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]`
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
- Configurations related to LeaderF in vimrc: 
```vim
  if(has('win32'))
    Plug 'Yggdroot/LeaderF', { 'do': '.\install.bat' }
  else
    Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
  endif
```
### Describe your question, feature request, or bug.
LeaderF is discarding the local foldlevel amongst a variety of other local settings every time it's used to open a file/switch between buffers/etc.  The foldlevel is most noticeable to me as my global foldlevel is the default of 0 and resetting foldlevel to 0 force-closes all folds which is really inconvenient.  This appears to be the responsible section:

https://github.com/Yggdroot/LeaderF/blob/35bc6c210efaeb71669cbdf52a362f2f09025311/autoload/leaderf/python/leaderf/manager.py#L139-L146

[Blame](https://github.com/Yggdroot/LeaderF/blame/4e444fd9cc314d981a141f1fe126c2ad986766b9/autoload/leaderf/python/leaderf/manager.py#L139-L146) points to this being some combo of workarounds for #422 and #432.  I've tried removing this workaround completely by commenting out its usage and that seems to work fine for me.  Even without it I'm not seeing the unexpected background highlights or missing line numbers that those issues describe.  Not sure if that comes down to differences (including newer nvim) between my environment and those of the authors of those other issues?

**Comment by eyalk5** [comment]
Interesting. That's might be the reason it jumps to collapsed region (will link to the bug).

**Comment by krage** [comment]
If I leave that code in place, clear my views directory and open my `init.vim` in a fresh neovim instance and do a `:verbose set foldlevel?` it tells me it was last set from 347 here:

https://github.com/Yggdroot/LeaderF/blob/4e444fd9cc314d981a141f1fe126c2ad986766b9/autoload/leaderf.vim#L346-L348

So the buffer I think unless I'm missing some nuance...

**Comment by krage** [comment]
Looks like this is essentially the same set of values that are modified on the preview window in a couple spots:

https://github.com/Yggdroot/LeaderF/blob/4e444fd9cc314d981a141f1fe126c2ad986766b9/autoload/leaderf/python/leaderf/manager.py#L472-L477

https://github.com/Yggdroot/LeaderF/blob/4e444fd9cc314d981a141f1fe126c2ad986766b9/autoload/leaderf/python/leaderf/manager.py#L627-L631

So presumably the goal was reverting changes those actions might've made.  If that's the actual goal though the local values those settings might hold should be saved and restored rather than wiped back to the global value.  

As a means of opening all folds it also would probably be better to set `nofoldenable`/`foldenable` rather than forcing `foldlevel` to 1000 and then restoring it.  The former maintains the state of manually opened/closed folds beyond the foldlevel whereas the latter will force open all and then force close all down to the previous level discarding any manually opened/closed folds.

**Comment by Yggdroot** [comment]
Fixed.
