### ISSUE TITLE
LeaderF gtags -d/-r跳转后，CTRL+T无法返回到原来的位置，有什么方法可以实现么？

### ISSUE THREAD

**Issue by husjhz** [Yggdroot/LeaderF#497]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
用Ctrl-o。

**Comment by husjhz** [comment]
> 用Ctrl-o。

感谢～
