### ISSUE TITLE
`Leaderf! --recall`行为很异常

### ISSUE THREAD

**Issue by x1314aq** [Yggdroot/LeaderF#499]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:  0.4.3
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.6
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
在重新打开之前关闭的窗口的时候，`Leaderf --recall`表现正常，出现正常大小的窗口；
`Leaderf! --recall`表现异常，窗口只有一行

- 这是正常大小的窗口，使用`Leaderf --recall`
<img width="859" alt="截屏2020-02-1512 41 59" src="https://user-images.githubusercontent.com/18412635/74582007-40237680-4ff1-11ea-804e-f8553dcb5b89.png">

- 这是使用`Leaderf! --recall`得到的只有一行的窗口
<img width="856" alt="截屏2020-02-1512 43 58" src="https://user-images.githubusercontent.com/18412635/74582009-4580c100-4ff1-11ea-9082-35a31088f5ec.png">

### Steps to reproduce
`Leaderf! --recall`

### Expected behaviour
`Leaderf! --recall`得到一个正常大小的窗口，和`Leaderf --recall`一样

**Comment by Yggdroot** [comment]
修复了。
