### ISSUE TITLE
使用`LeaderfFile`命令错误和目录改变无效

### ISSUE THREAD

**Issue by DaSea** [Yggdroot/LeaderF#50]
1. 打开vim后, 切换到另一个目录后, 执行:LeaderfFile, 就会出现这个, 但是好像与文件夹有关,
   有的文件夹就不会出现, 暂时还没发现规律!
![tim 20170607094601](https://user-images.githubusercontent.com/8628288/26858823-257abe84-4b66-11e7-9937-e11799187ce0.png)

2. 打开vim后, 先:LeaderfFile, 然后切换到另一个目录(:cd ...), 然后调用:LeaderfFile,
   结果浏览的还是上一次的; 多次cd无效!
![tim 20170607094610](https://user-images.githubusercontent.com/8628288/26858828-310a4044-4b66-11e7-9e43-309086ababd1.png)

**Comment by Yggdroot** [comment]
这是两个问题，第二个问题好处理，我会尽快fix。
另外如果切换目录，可以直接`:LeaderfFile <目录>`, 而不用先cd再执行`:LeaderfFile`
第一个问题：
1，你电脑上装rg，ag了吗？
2，帮忙改一下代码看看错误输出
把asyncExecutor.py 里面的`raise Exception(lfEncode(lfBytes2Str(err)))`改为`raise Exception(err)`再试一下，看看输出

**Comment by DaSea** [comment]
![20170607101945](https://user-images.githubusercontent.com/8628288/26859527-f6a03e7c-4b6a-11e7-8697-0bc0e4081e3d.png)

这是错误.
我的工程目录下多了个`NUL` 文件, 删不掉, 不知道是不是与它有关! 我再试下!

**Comment by DaSea** [comment]
与这个`NUL`文件有关!

**Comment by Yggdroot** [comment]
第二个问题我无法复现。

**Comment by Yggdroot** [comment]
帮忙看看这两个问题是不是fix了。

**Comment by DaSea** [comment]
早上更新, 已经fix了!
