### ISSUE TITLE
CTRL+PageUp not work in iterm2

### ISSUE THREAD

**Issue by electrlife** [Yggdroot/LeaderF#500]
用了一下感觉ctrlp可以丢掉了，另外有个问题就是ctrl+page up 无法使用，不知是不是我设置的问题？我的环境是 macos+iterm2， 对于iterm2 做了 如下设置：

Go to iTerm / Preferences... / Profiles / Keys
Press the + button to add a profile shortcut
Use shortcut: ^Page Up, action: "Send Escape sequence", value [5;5~
Use shortcut: ^Page Down, action: "Send Escape sequence", value [6;5~

但依然不能scroll preview window ???

**Comment by Yggdroot** [comment]
可以设置的，你看看，具体哪里我忘了。

**Comment by electrlife** [comment]
如果有时间帮忙看看如何设置，另外对于Scroll preview的Key可以重新绑定嘛？

**Comment by Yggdroot** [comment]
忽然发现CTRL+PageUp CTRL+Pagedown本来就没有支持，支持的都在readme里面，现在只支持ctrl-up，ctrl-down。

> 在弹出preview窗口后，是否可以使用vim 标准的窗口切换命令（ctrl+w + [j|k]，或快捷键ctrl+j）切到preview窗口然后使用标准的 jklh

如果是nvim，可以

**Comment by electrlife** [comment]
CTRL+UP 在Macos中有作用，不知可以更改到CTRL+PageUP？
> 在弹出preview窗口后，是否可以使用vim 标准的窗口切换命令（ctrl+w + [j|k]，或快捷键ctrl+j）切到preview窗口然后使用标准的 jklh

对于vim 是否可以实现？如修改代码，还是说本身vim的pop window不支持？

**Comment by Yggdroot** [comment]
> CTRL+UP 在Macos中有作用，不知可以更改到CTRL+PageUP？
> 
这个需要添加代码来支持。

> > 在弹出preview窗口后，是否可以使用vim 标准的窗口切换命令（ctrl+w + [j|k]，或快捷键ctrl+j）切到preview窗口然后使用标准的 jklh
> 
> 对于vim 是否可以实现？如修改代码，还是说本身vim的pop window不支持？

因为vim的popup跟nvim的不一样，nvim的floatwin跟普通window一样，这个天生就支持，而vim的popup要实现这个功能比较麻烦。

**Comment by electrlife** [comment]
> CTRL+UP 在Macos中有作用，不知可以更改到CTRL+PageUP？
> 这个需要添加代码来支持。

能否增加一些快捷键配置的选项，用于配置一些快捷键。
关于修改代码能否给些提示，我自己尝试修改一下！

**Comment by electrlife** [comment]
另外我发现一个问题，就是：
1. <leader>ft
2. ;abc
3. 重复 Backspace

导致 ; 号无法删除！

我环境是macos+iterm2+vim 8.2
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan  8 2020 00:57:57)

**Comment by Yggdroot** [comment]
> > CTRL+UP 在Macos中有作用，不知可以更改到CTRL+PageUP？
> > 这个需要添加代码来支持。
> 
> 能否增加一些快捷键配置的选项，用于配置一些快捷键。
> 关于修改代码能否给些提示，我自己尝试修改一下！

如果想让ctrl-pageup有ctrl-up的功能，只要改配置就可以了，
```vim
let g:Lf_CommandMap = {'<C-UP>': ['<C-PageUp>']}
```
如果想要ctrl-pageup有翻页的功能，需要增加代码了。

**Comment by Yggdroot** [comment]
> 另外我发现一个问题，就是：
> 
> ```
> 1. <leader>ft
> 2. ;abc
> 3. 重复 Backspace
> ```
> 
> 导致 ; 号无法删除！
> 
> 我环境是macos+iterm2+vim 8.2
> :version
> VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 8 2020 00:57:57)

修复了。
