### ISSUE TITLE
insert模式下粘贴文本时可否关闭增量搜索？

### ISSUE THREAD

**Issue by fly-potato-100** [Yggdroot/LeaderF#502]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

在**较大项目**中，当我使用`:Leaderf rg`命令弹出Leaderf搜索框之后，我用`<Shift+insert>`粘贴一串文本希望搜索匹配行，Leaderf会一个字符一个字符的粘贴上去，并且每粘贴一次都会进行一次搜索。在项目代码量较大的时候，有非常明显的卡顿。

### Expected behaviour

可否增加开关选项，在`<Shift+insert>`时关闭这种类似增量搜索的行为？

**Comment by Yggdroot** [comment]
这是终端的问题，应该是终端的`<Shift+insert>`把字符一个一个的发送给vim。
你可以使用ctrl-v。
