### ISSUE TITLE
提示窗口关闭后 会把 layout 弄乱

### ISSUE THREAD

**Issue by hy172574895** [Yggdroot/LeaderF#504]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
vim 8.2.033
- Output of `:echo has("python")`: 
no
- Output of `:echo has("python3")`: 
yes
- Output of `:echo &pythondll`(only vim, not neovim): 
no
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
python
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Expected behaviour

当右侧有NERDtree窗口（竖立）的时候，leaderf的弹出窗口关闭后才会发生这个问题。

**Comment by hy172574895** [comment]
gif:
jimmyhuang454.com/18.gif

**Comment by Yggdroot** [comment]
图片看不到。

**Comment by hy172574895** [comment]
![18](https://user-images.githubusercontent.com/31300347/74833492-8449aa80-5354-11ea-866c-a2753b82f6a9.gif)
上传到github了....

**Comment by Yggdroot** [comment]
你这个问题我复现不了，这个问题好像以前报过，我修复过的。你的代码不够新？

想layout不乱，现在可以用popup mode。

**Comment by Yggdroot** [comment]
复现了，开多个tabpage会这样，单个tabpage不会。

**Comment by hy172574895** [comment]
> 你这个问题我复现不了，这个问题好像以前报过，我修复过的。你的代码不够新？
> 
> 想layout不乱，现在可以用popup mode。

我知道可以用popup mode。 就是看着很别扭，毕竟用了很久 底下弹出 了。
再加上 也有很多人都没有编译 浮动窗口 这个特性。

**Comment by Yggdroot** [comment]
奇怪，又复现不了了。

**Comment by hy172574895** [comment]
我好像找到肯定能复现的方法：
1.打开vim
2.使用 LeaderfMru 按回车打开文件 a
3.再使用 leaderfMru 用<ctrl-t> 新开一个标签打开文件 b
4.再再使用leaderMru 用<ctrl-x> 分割打开一个文件c，**注意 c 的 cwd 跟 b 是不一样的**；:echo getcwd() 可看到。
5.竖立打开NERDtree
6. 复现... layout 不会恢复正常。

我感觉 leaderf 初始化的时候得到错误的 buffer name，也就是 返回的不是全路径，而是用cwd替代了一部分。而改变了cwd后，leaderf没有跟着vim改变。关闭的时候 也就找不到对应的 windows， 高度也就无法恢复了。

**Comment by hy172574895** [comment]
我好像找到肯定能复现的方法：
1.打开vim
2.使用 LeaderfMru 按回车打开文件 a
3.再使用 leaderfMru 用 ctrl-t  新开一个标签打开文件 b
4.再再使用leaderMru 用 ctrl-x 分割打开一个文件c，注意 c 的 cwd 跟 b 是不一样的；:echo getcwd() 可看到。
5.竖立打开 NERDTree
6. 复现... layout 不会恢复正常。

我感觉 leaderf 初始化的时候得到错误的 buffer name，也就是 返回的不是全路径，而是用cwd替代了一部分。而改变了cwd后，leaderf没有跟着vim改变。关闭的时候 也就找不到对应的 windows， 高度也就无法恢复了。

**Comment by Yggdroot** [comment]
修复了。

**Comment by hy172574895** [comment]
Confirmed fix. Thanks.
