### ISSUE TITLE
在 Macvim 中, 如果输入中文进行搜索, 会导致大量拼音被输入到 Leadf 的搜索框中

### ISSUE THREAD

**Issue by HanleyLee** [Yggdroot/LeaderF#508]
- vim or neovim? 
    - [x] vim (MacVim)
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 

    ```
    VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
    macOS version
    Included patches: 1-2234
    Compiled by travis@Traviss-Mac.local
    Huge version with MacVim GUI.  Features included (+) or not (-):
    +acl               +file_in_path      +mouse_urxvt       -tcl
    +arabic            +find_in_path      +mouse_xterm       +termguicolors
    +autocmd           +float             +multi_byte        +terminal
    +autochdir         +folding           +multi_lang        +terminfo
    -autoservername    -footer            -mzscheme          +termresponse
    +balloon_eval      +fork()            +netbeans_intg     +textobjects
    +balloon_eval_term +fullscreen        +num64             +textprop
    +browse            -gettext           +odbeditor         +timers
    ++builtin_terms    -hangul_input      +packages          +title
    +byte_offset       +iconv             +path_extra        +toolbar
    +channel           +insert_expand     +perl/dyn          +transparency
    +cindent           +job               +persistent_undo   +user_commands
    +clientserver      +jumplist          +postscript        +vartabs
    +clipboard         +keymap            +printer           +vertsplit
    +cmdline_compl     +lambda            +profile           +virtualedit
    +cmdline_hist      +langmap           +python/dyn        +visual
    +cmdline_info      +libcall           +python3/dyn       +visualextra
    +comments          +linebreak         +quickfix          +viminfo
    +conceal           +lispindent        +reltime           +vreplace
    +cryptv            +listcmds          +rightleft         +wildignore
    +cscope            +localmap          +ruby/dyn          +wildmenu
    +cursorbind        +lua/dyn           +scrollbind        +windows
    +cursorshape       +menu              +signs             +writebackup
    +dialog_con_gui    +mksession         +smartindent       -X11
    +diff              +modify_fname      -sound             -xfontset
    +digraphs          +mouse             +spell             +xim
    +dnd               +mouseshape        +startuptime       -xpm
    -ebcdic            +mouse_dec         +statusline        -xsmp
    +emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
    +eval              -mouse_jsbterm     +syntax            -xterm_save
    +ex_extra          +mouse_netterm     +tag_binary
    +extra_search      +mouse_sgr         -tag_old_static
    -farsi             -mouse_sysmouse    -tag_any_white
       system vimrc file: "$VIM/vimrc"
         user vimrc file: "$HOME/.vimrc"
     2nd user vimrc file: "~/.vim/vimrc"
          user exrc file: "$HOME/.exrc"
      system gvimrc file: "$VIM/gvimrc"
        user gvimrc file: "$HOME/.gvimrc"
    2nd user gvimrc file: "~/.vim/gvimrc"
           defaults file: "$VIMRUNTIME/defaults.vim"
        system menu file: "$VIMRUNTIME/menu.vim"
      fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
    Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
    Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
    ```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): `/System/Library/Frameworks/Python.framework/Versions/2.7/Python`
- Output of `:echo &pythonthreedll`(only vim, not neovim): `/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/Python`
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 

    ![himg](https://a.hanleylee.com/HKMS/2020-02-19-091847.png?x-oss-process=style/WaMa)

- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

    ```
    nmap <F2> :Leaderf mru<CR>
    let g:Lf_WindowPosition = 'popup' "默认使用 popup 窗口弹出搜索结果
    let g:Lf_PreviewInPopup = 1 "在 popup 窗口中预览文件
    let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']} "使用上下方向按键进行上下移动焦点
    ```

### Describe your question, feature request, or bug.

在 Macvim 中输入`:Leaderf file` 或 `:Leaderf mru` 进行搜索时, 如果输入中文, 会导致大量拼音被输入到 Leadf 的搜索框中

### Steps to reproduce

![himg](https://a.hanleylee.com/HKMS/2020-02-19-Kapture%202020-02-19%20at%2017.39.48.gif)

### Actual behaviour

我一般使用 MacVim 在 Mac 上, 输入法使用搜狗, 发现这个问题后我进行排查

- ❌ 切换到系统的拼音输入法, 仍然会出现此问题, 未能解决
- ✅ 在终端中使用 `mvim -v`命令在终端中使用 MacVim, 输入中文没有问题

    ![himg](https://a.hanleylee.com/HKMS/2020-02-19-Kapture%202020-02-19%20at%2017.41.53.gif)

- ❌ 通过 Homebrew 重新安装 MacVim, 仍然会出现此问题, 未能解决

所有我很好奇是什么原因导致了在 MacVim 情况下的中文输入问题, 是我配置的问题还是作者开发时没考虑到兼容 MacVim 呢, 希望作者解答一下

### Expected behaviour

希望在输入框中输入中文时能正常录入文字

**Comment by Yggdroot** [comment]
可能跟 #200 是同一个问题，不知道是macvim的问题还是输入法的问题，我在我的mac系统上没问题。

**Comment by HanleyLee** [comment]
@Yggdroot 嗯, 我发表下我的拙见, 我认为应该排除掉输入法的问题, 原因如下:

1. 无论是搜狗还是系统内置的拼音输入法, 在 `MacVim` 这个 App 的 `Leaderf` 搜索框中输入中文时都会有这个现象发生
2. 在`MacVim`这个 App 的其他任何情况下输入中文(哪怕是在命令模式下输入中文)都不会有这种情况发生.
3. 如果在终端中的 MacVim 的 Leaderf 搜索框中输入中文也是没有这个问题出现的

所以, 如果排除掉输入法的问题的话, 那么就是 MacVim 自身的问题或者是插件 Leaderf 的小 bug 了. 我使用过的 vim 插件也很多了, 但是从没有过这种中文输入问题存在, 刚刚我还将所有的除 Leaderf 以外的插件全部禁用, 将所有的我设置过的自定义 vim 设置都注释掉, 但是结果仍然是Leaderf 的中文输入出现大量拼音. 所以我的意见更倾向于是 Leaderf 的配置有一些

我仔细观察了一下这个 bug, 我发现每次输入一个拼音字母, Leaderf 的输入框中就会重新将截止到当前的全部字母录入进来, 这种情况就像是 Leaderf 一直保持着英文输入的状态.

因为我在使用中涉及到大量中文文档, 因此这个 bug 对我这样的中文用户影响还是很大的, 希望作者能重视一下.

谢谢

**Comment by Yggdroot** [comment]
根据你的描述，我还不确定是不是跟 #200 是同一个原因，如果是的话，那个issue里有解释，请仔细看一下。之所以出现在LeaderF中，是因为LeaderF使用了vim的getchar()。
你分别在终端和Macvim上做一下：
`:echom getchar()`， 然后输入‘我’，看是不是表现一样，不一样就是macvim的bug。

**Comment by HanleyLee** [comment]
我看了 #200 , 尝试在终端 vim 和 MacVim 中输入 `echom getchar()`与`我`, 结果如下

## MacVim 中

1. 当`我`的第一个拼音字母`w`输入完后立刻输出了 119
    ![himg](https://a.hanleylee.com/HKMS/2020-02-20-160647.png?x-oss-process=style/WaMa)
2. 输入第二个拼音字母`o`时直接进入到了 Insert 模式并换了一行
3. 按下空格后, `我`被输出到了屏幕上

## 终端 Vim 中

输入完 `echom getchar()` 后, 再输入`我`会打印出结果 `25105`

![himg](https://a.hanleylee.com/HKMS/2020-02-20-161429.png?x-oss-process=style/WaMa)

所以, 我这种情况和 #200 应该是不一样的. 

刚刚我尝试了另一个插件 `CtrlP`, 我发现那个插件有和 `Leaderf`同样的中文输入问题, 而且只限于 MacVim, 所以可以确定应该是 MacVim 或者是我配置的问题, 作者知道是什么原因吗? 我应不应该去 MacVim 下面提 issue? 如果提的话怎么说呢

**Comment by Yggdroot** [comment]
现在我可以确定跟 200 是同一个问题。就是输入中文时，还没有按空格确定就把输入的字符传给vim了。现在看来很可能是macvim的问题，跟你的配置无关。
可以提issue，就说macvim跟终端vim对于`:echom getchar()， 然后输入‘我’` 处理不一致，macvim有误。 只是老外不懂中文输入法，描述起来可能不太好说，可能他们也不理解怎么复现。

**Comment by HanleyLee** [comment]
## 2020-03-20 解决办法(我成功了)

在终端中输入 `defaults write org.vim.MacVim MMUseInlineIm 0`

答案是参考了一些网上说明, 我测试下确实是可用的

这个问题的原因好像是入法没有完全截获按键, 有知道的可以详细说下

**Comment by Yggdroot** [comment]
GOOD！
