### ISSUE TITLE
LeaderF doesn't work after update

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#51]
Hi!

I just updated my plugins and now LeaderF only finds 1 file in my folder where before it was finding 20K files.

**Comment by Yggdroot** [comment]
Could you tell me the configuration in your vimrc?
Do you have installed 'rg' or 'ag'?

**Comment by MightyCreak** [comment]
Sorry for he delay, haven't seen your answer.
I made another update today and there was one for LeaderF and now it works!

Closing the issue ;)
