### ISSUE TITLE
In objc, I cannot jump from function declaration(.h) to function implementation (.m)

### ISSUE THREAD

**Issue by freedragonlxl** [Yggdroot/LeaderF#511]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.4.3
- Output of `:echo has("python")`: 3.7.5
- Output of `:echo has("python3")`: 3.7.5
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: [Clang 11.0.0 (clang-1100.0.33.17)]
- Output of `:py3 print(sys.version)`: [Clang 11.0.0 (clang-1100.0.33.17)]
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
37 " <LeaderF 不用，转用unite>
138 " -----------------------------------------------------------------------------------------
139 let g:Lf_ShowRelativePath = 0
140 " don't show the help in normal mode
141 let g:Lf_HideHelp = 1
142 let g:Lf_UseCache = 0
143 let g:Lf_UseVersionControlTool = 0
144 let g:Lf_IgnoreCurrentBufferName = 1
145 " popup mode
146 let g:Lf_WindowPosition = 'popup'
147 let g:Lf_PreviewInPopup = 1
148 let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
149 let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
150 let g:Lf_ShortcutF = "<leader>ff"
151 noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
152 noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
153 noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
154 noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
155 noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
156 noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
157 " search visually selected text literally
158 xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
159 noremap go :<C-U>Leaderf! rg --recall<CR>
160 " should use `Leaderf gtags --update` first
161 let g:Lf_GtagsAutoGenerate = 0
162 let g:Lf_Gtagslabel = 'pygments'
163 noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
164 noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
165 noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
166 noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
167 noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>

### Describe your question, feature request, or bug.
In objc language, I cannot jump from the method declaration in the header(.h) file to the method implementation in the implementation(.m) file.

**Comment by Yggdroot** [comment]
Sorry, I don't understand what you mean.

**Comment by freedragonlxl** [comment]
> Sorry, I don't understand what you mean.

Sorry, My English is so low.
My Problem is that:
Is it possible,  input the command where the function is declared in the header file, and then, jump to the function definition of the implementation file(xxx.m file is Objective-C  implementation file,  xxx.h file is Objective-C  header file)

**Comment by Yggdroot** [comment]
If you use `Leaderf gtags`, 
```vim
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
```
can jump to the definition.

**Comment by freedragonlxl** [comment]
> If you use `Leaderf gtags`,
> 
> ```viml
> noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
> ```
> 
> can jump to the definition.
大佬，我还是说中文，英文实在生硬。
我已经对工程目录运行了：Leaderf gtags --update，然后我把光标放在相应的函数声明位置（在头文件中，就是oc的.h文件），在操作你所说的之后，弹出一个框，里面是空，并没有跳转到相应的实现文件的函数定义中去（.m文件）。此外，我运行Leaderf gtags --all，查看了下，并没有与函数相关的内容，都是变量、类......

**Comment by Yggdroot** [comment]
Objective-C 我没试过，觉得应该会支持。你能不能提供一下OC的代码，以及操作的函数，我试一下看看？

**Comment by freedragonlxl** [comment]
[task.zip](https://github.com/Yggdroot/LeaderF/files/4259395/task.zip)
好! 发送附件了～我就操作updateView

**Comment by Yggdroot** [comment]
我试了，updateView确实出不来，我不懂Objective-C，可能是因为gtags对Objective-C支持的不够好。

**Comment by freedragonlxl** [comment]
谢谢大佬，那没办法～～我去尝试下其他方法～～
