### ISSUE TITLE
PreviewInPopup mode will open files in wrong window

### ISSUE THREAD

**Issue by linjiX** [Yggdroot/LeaderF#512]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
编译者 brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
```
0
```
- Output of `:echo has("python3")`: 
```
1
```
- Output of `:py3 print(sys.version)`: 
```
3.7.4 (default, Oct 27 2019, 01:01:25)
[Clang 11.0.0 (clang-1100.0.33.8)]
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vim
" minivimrc
call plug#begin('~/.vim/plug')
Plug 'Yggdroot/LeaderF', {'do': './install.sh'}
call plug#end()

let g:Lf_PreviewInPopup = 1
```

### Describe your question, feature request, or bug.
File will open in wrong window when using popup preview feature

### Steps to reproduce
1. `nvim -u minivimrc` Open neovim with minivimrc above.
2. `:vsplit` Vertical split window
3. `<C-w>l` Move cursor to the right window
4. `:Leaderf file --popup` Open Leaderf window in popup mode
5. `<C-p>` Trigger preview popup window for any file
6. `<CR>` Open any file

### Actual behaviour
Follow the reproduce steps, the file will open in left window.

### Expected behaviour
The file should open in right window because the leaderf is triggered in right window.

**Comment by Yggdroot** [comment]
Fixed.
