### ISSUE TITLE
Leaderf commands are not pure

### ISSUE THREAD

**Issue by webdavis** [Yggdroot/LeaderF#513]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`:

```
NVIM v0.5.0-397-g96059d72e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-13ebc8c2-4f6f-45b7-ad53-0dc3d8813d5f

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:py print(sys.version)`:  `2.7.17 (default, Oct 22 2019, 09:14:09) [GCC 9.2.0]`
- Output of `:py3 print(sys.version)`: `3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]`
- Operating system: 
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```vim
let g:Lf_ShortcutF = "<Leader>f<CR>"
nnoremap <Leader>fn :<C-u>Leaderf file --nameOnly<CR>
nnoremap <Leader>fh :<C-u>LeaderfFile ~<CR>
```

### Describe your question, feature request, or bug.

Leaderf commands are not pure. When executing a Leaderf command with a mode option such as `--regex`, `--nameOnly` or `--fullpath`, all subsequent calls to Leaderf commands will use the previously used mode unless another mode is explicitly declared.

I know that redefining my mappings so that they are all explicit, such as: `nnoremap <Leader>fh :<C-u>Leaderf file --fullpath<CR>` would be a workaround. The way I see it is that the model is currently as follows:

1. Either declare a default mode with `g:Lf_DefaultMode` or not.
2. Run a command with a mode set explicitly, e.g. `Leaderf file --nameOnly`.
3. Define mappings that set the mode explicitly to override step 2, e.g. `nnoremap <Leader>f<CR> :<C-u>Leaderf file --fullpath<CR>`

However I think it would be more useful to have the following model:

1. Either declare a default mode with `g:Lf_DefaultMode` or not.
2. Run a command with a mode set explicitly, e.g. `Leaderf file --nameOnly`.
3. Define mappings and expect them to fall back to the default behavior, e.g. `nnoremap <Leader>f<CR> :<C-u>LeaderfFile<CR>`

### Steps to reproduce

1. Run `LeaderfFile` with default behavior to observe `FullPath` mode.
2. Run `Leaderf file --nameOnly` to observe `NameOnly` mode.
3. Run `LeaderfFile` again to observe `NameOnly` mode.
4. Run `Leaderf file --fullpath` to switch back to `FullPath` mode.

### Actual behaviour

The previous used mode is used in all subsequent calls to Leaderf.

### Expected behaviour

Each command should be pure and not affected by previous commands so that commands like `LeaderfFile` have predictable behavior.

**Comment by Yggdroot** [comment]
This is the intended behavior. It's like the Principle of temporal locality. Suppose the command you use is mostly the same as the previous one.

BTW, you can use `<C-F>` to switch between Nameonly mode and FullPath mode.

**Comment by webdavis** [comment]
Okay. I didn't see this in the documentation but I may have missed it. If it isn't, it may be helpful to state this behavior explicitly that it's the intended behavior. It threw me off at first.
