### ISSUE TITLE
Feature request: add way to search by file extension?

### ISSUE THREAD

**Issue by webdavis** [Yggdroot/LeaderF#514]
Would you be opposed to adding a dedicated command that filters by filetype (i.e. `*.java`)? I think this would save keystrokes on large projects. Something along the lines of `Leader file --ext java`.

**Comment by Yggdroot** [comment]
I think the fuzzy matching is already smart enough to handle such a scenerio, you just need to type `java xxxx`.
Also you can try `Leader file --input java`.

**Comment by webdavis** [comment]
Ah I see, thanks. This is what I came up with.
`nnoremap <Leader>fj :<C-u>Leaderf file --input .java<CR><Space>`
