### ISSUE TITLE
请问，在写go程序时，可以用gotags代替ctags吗？

### ISSUE THREAD

**Issue by Cosson2017** [Yggdroot/LeaderF#52]
请问，在写go程序时，可以用gotags代替ctags吗？

**Comment by Yggdroot** [comment]
可以，`let g:Lf_Ctags ="path/to/gotags"`；但我不知道gotags输出的格式跟ctags是不是一样，不一样的话就需要修改代码来支持。

**Comment by Yggdroot** [comment]
也可以使用https://github.com/universal-ctags/ctags，是ctags的维护版本，同样支持go，不需要修改代码。

**Comment by Cosson2017** [comment]
@Yggdroot 谢谢大神　gotags还不能用，/universal-ctags/ctags是可以的

**Comment by axiaoxin** [comment]
请问是不是也不支持gtags，报错：
```
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 760, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 703, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1587, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 80, in getContent
    result = self._formatResult(*result)
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 148, in _formatResult
    output = [line.split('\t') for line in result if line is not None]
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 148, in <listcomp>
    output = [line.split('\t') for line in result if line is not None]
  File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 92, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: ctags: Warning: Unknown language "go" in "go-kinds" option
处理 function leaderf#Any#start 时发生错误:
第    4 行:
E171: 缺少 :endif
```

**Comment by Yggdroot** [comment]
> 请问是不是也不支持gtags，报错：
> 
> ```
> 处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
> 第    1 行:
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 760, in start
>     the_args.start(arguments, *args, **kwargs)
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 703, in _default_action
>     manager.startExplorer(win_pos[2:], *args, **kwargs)
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1587, in startExplorer
>     content = self._getExplorer().getContent(*args, **kwargs)
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 80, in getContent
>     result = self._formatResult(*result)
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 148, in _formatResult
>     output = [line.split('\t') for line in result if line is not None]
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 148, in <listcomp>
>     output = [line.split('\t') for line in result if line is not None]
>   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 92, in read
>     raise Exception(lfBytes2Str(err, encoding))
> Exception: ctags: Warning: Unknown language "go" in "go-kinds" option
> 处理 function leaderf#Any#start 时发生错误:
> 第    4 行:
> E171: 缺少 :endif
> ```

你怎么用的？
想用gtags 使用:Leaderf gtags -h

**Comment by axiaoxin** [comment]
> > 请问是不是也不支持gtags，报错：
> > ```
> > 处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
> > 第    1 行:
> > Traceback (most recent call last):
> >   File "<string>", line 1, in <module>
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 760, in start
> >     the_args.start(arguments, *args, **kwargs)
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 703, in _default_action
> >     manager.startExplorer(win_pos[2:], *args, **kwargs)
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1587, in startExplorer
> >     content = self._getExplorer().getContent(*args, **kwargs)
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 80, in getContent
> >     result = self._formatResult(*result)
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 148, in _formatResult
> >     output = [line.split('\t') for line in result if line is not None]
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/functionExpl.py", line 148, in <listcomp>
> >     output = [line.split('\t') for line in result if line is not None]
> >   File "/Users/ashin/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 92, in read
> >     raise Exception(lfBytes2Str(err, encoding))
> > Exception: ctags: Warning: Unknown language "go" in "go-kinds" option
> > 处理 function leaderf#Any#start 时发生错误:
> > 第    4 行:
> > E171: 缺少 :endif
> > ```
> 
> 你怎么用的？
> 想用gtags 使用:Leaderf gtags -h

使用LeaderfFunction报的错，刚把默认ctags换成universal-ctags是可以的
