### ISSUE TITLE
`--gtagsconf`的参数应加双引号以防止路径中有空格

### ISSUE THREAD

**Issue by stewartdud** [Yggdroot/LeaderF#520]
gtags运行参数里`--gtagsconf`的参数应加双引号以防止路径中有空格

`gtagsExpl.py` 第792/797/802行 `'--gtagsconf %s'` 最好改为 `'--gtagsconf "%s"'` 以防止gtags.conf路径中有空格

**Comment by Yggdroot** [comment]
第792/797/802行 没有 '--gtagsconf %s'，你的代码是不是不够新？

**Comment by Yggdroot** [comment]
你的提议确实不错。

**Comment by stewartdud** [comment]
抱歉，我没有review最新的代码，几天前刚装的Leaderf，提issue前就没看新的代码，一共改了9行，同一个问题

**Comment by stewartdud** [comment]
目前如果输入带有双引号，参数还是会有问题（之前忘记改回输入参数双引号了）
`gtagsExpl.py`  第543行：
```
self._gtagsconf = self._gtagsconf.join('""')
```
是否应该添加strip:
```
self._gtagsconf = self._gtagsconf.strip('"').join('""')
```

**Comment by Yggdroot** [comment]
不会有问题，因为这是给g:Lf_Gtagsconf赋值才会有问题，假定不会赋成let g:Lf_Gtagsconf = '"aaa bbb"'这种形式，这种形式认为是不正确的，只能是"aaa bbb"或者'aaa bbb'.

**Comment by stewartdud** [comment]
好，我改之前为了使用临时把输入改成了"aaa bbb"，pull之后忘改回去了没测试通过，现在OK了

**Comment by Yggdroot** [comment]
"aaa bbb"应该是可以通过的，你说的是'`"aaa bbb"`'吧？

**Comment by stewartdud** [comment]
对，现在没问题了
