### ISSUE TITLE
Preview window border

### ISSUE THREAD

**Issue by cbows** [Yggdroot/LeaderF#524]
Would it be possible to implement border style for floating window like [fzf](https://github.com/junegunn/fzf/blob/b0673c35634a04687237cd57ef4ab2fafeeb620a/plugin/fzf.vim#L877-L904).

**Comment by Yggdroot** [comment]
I don't know what it is like.

**Comment by cbows** [comment]
I linked the corresponding vimscript in the original post. It looks like this:

![image](https://user-images.githubusercontent.com/32486983/76526212-7bd52300-646d-11ea-8034-05a70cc71de9.png)

**Comment by tamago324** [comment]
I'd like to implement it when it's possible to display the borders natively in neovim. https://github.com/neovim/neovim/issues/9718

**Comment by Yggdroot** [comment]
<img width="612" alt="border" src="https://user-images.githubusercontent.com/2705841/161517382-2836c6ce-0f5e-4bdf-9bd9-a555655c3872.png">
