### ISSUE TITLE
[Feature request] Leaderf rg auto select file type

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#526]
### Describe your question, feature request, or bug.
In some big project, Using `--type` option of rg is significantly faster. I use `--type` in vim key binding of Leaderf rg. But, hard code a type in vim config file is not so flexible when working on different languages. So, Could Leaderf use mapping of `rg --type-list` to provide a method that can auto give the type string corresponding to current file type. Than, we can have a key binding of "search in files of current language (file type)". May be user specified type can also be maintained in type mapping dict.

**Comment by tamago324** [comment]
I think you should prepare the following functions, but what about?

```vim
scriptencoding utf-8

let s:type_list = []

function! s:rg_type_list() abort
    if len(s:type_list) > 0
        return s:type_list
    endif

    let l:ret = {}
    let l:output = systemlist('rg --type-list')

    for l:line in l:output
        let [l:type, l:pattern_str] = split(l:line, ': ')
        let l:pattern_list = split(l:pattern_str, ', ')

        let l:ret[l:type] = map(l:pattern_list, 'glob2regpat(v:val)')
    endfor

    let s:type_list = l:ret
    return s:type_list
endfunction

function! s:rg_get_type_by_fname(type_list, fname) abort
    for [l:type, l:pattern_list] in items(a:type_list)
        for l:pattern in l:pattern_list
            if a:fname =~# l:pattern
                return l:type
            endif
        endfor
    endfor
    return ''
endfunction

function! RgGetTypeByFname(fname) abort
    let l:type = s:rg_get_type_by_fname(s:rg_type_list(), a:fname)
    echomsg l:type
    return empty(l:type) ? '' : printf('-t "%s"', l:type)
endfunction

nnoremap <Space>fg :<C-u><C-r>=printf('Leaderf rg %s -e ""', RgGetTypeByFname(expand('%:p:t')))<CR><Left>
```

If the buffer name is `sample.vim`, it will be `:Leaderf rg -t "vimscript" -e ""`

**Comment by xaljer** [comment]
@tamago324 , that's what i want, thanks.
Maybe Leaderf has this this function as build-in is better, people don't need to find this little script on web and maintain it in vim config file.

**Comment by tamago324** [comment]
@xaljer Thanks!
How about appending to the [rg configuration example](https://github.com/Yggdroot/LeaderF/wiki/Leaderf-rg#configuration-examples)?
You can do anything depending on your idea.

**Comment by tamago324** [comment]
@Yggdroot What about appending to the wiki?

**Comment by tamago324** [comment]
Implemented #565.

> Usage:
> 
> For example, let's map the following
> 
> nnoremap <Space>fg :<C-u><C-r>=printf('Leaderf rg %s ', leaderf#Rg#getTypeByFileName(expand('%')))<CR>
> Type <Space>fg.
> 
> If the current buffer name is sample.vim, it will be :Leaderf rg -t "vimscript"

**Comment by xaljer** [comment]
@tamago324 , there are also some problems in your solution. 
1. some file type is used by more than one languages, such as *.h. Only users know what exactly type they want.
2. some types in `rg --type-list are written as regular expression format, i don't if you handle this case?
Maybe a default mapping table should be maintained, and a user defined mapping table can be specified to override the default. For example, if i work in a c/cpp project, i can remove the objective-c stuff in mapping table. When i search things from a .h file, `leaderf#Rg#getTypeByFileName` can give me both c and cpp types.

**Comment by tamago324** [comment]
Yes, that's right. Let's think about it.
