### ISSUE TITLE
g:Lf_WildIgnore doesn't seem to work anymore

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#53]
I used `g:Lf_WildIgnore` in my .vimrc to filter out some unwanted binary files. But until recently, it doesn't seem to filter anything anymore, the default filters works (e.g. `'*.o'`), but not my filters (e.g. `'*.a'`).

I tested with that and I still see the *.a files:
```let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.a','*.so','*.py[co]']
            \}```

**Comment by Yggdroot** [comment]
By default LeaderF use `git` or `hg` if your repository is under control of them, then `g:Lf_WildIgnore` will be ignored, because there is already a `.gitignore` or `.hgignore`.
`let g:Lf_UseVersionControlTool = 0`, LeaderF will use `rg` or `pt` or `ag` or `find` to index the files, `g:Lf_WildIgnore` will work as expected.

**Comment by MightyCreak** [comment]
Hey, sorry for the delay.

Indeed, `.hgignore` works, but considering the size of the project I'm working on (several millions lines of code across multiple platforms), there are part of the project that isn't relevant to me, but it is to others and that's why it is not in the project's `.hgignore`.

It would be nice to have both: follow the `.hgignore` but also be able to set your own rules in the LeaderF configuration.

Would be nice to reopen the issue, considering this request.

Thanks!

**Comment by Yggdroot** [comment]
Fixed, but only available for hg. not for git.

**Comment by MightyCreak** [comment]
That's weird, it's not deterministic... But thanks mate ;)

**Comment by retzzz** [comment]
Is this option (g:Lf_WildIgnore) working for regex mode?
Here is my setting:
```
let g:Lf_UseVersionControlTool=0
let g:Lf_WildIgnore = {
        \ 'dir': ['.svn','.git','.hg'],
        \ 'file': ['*.vcxproj','*.vcproj','*.lib','*.bak','*.exe','*.o','*.so','*.py[co]','*.obj']
        \}
```
But `:Leaderf rg -F -w -e xyz` still search the file I want to ignore.

**Comment by Yggdroot** [comment]
yes

**Comment by retzzz** [comment]
> yes

@Yggdroot Do you mean it should be working for regex mode, right? But why I cannot ignore the files? Is my setting correct? What else I should do to make it work?

**Comment by Yggdroot** [comment]
these options only work for `Leaderf file`, if you want to ignore files when using `Leaderf rg`, Leaderf rg -g! xxx

**Comment by retzzz** [comment]
@Yggdroot Thank you. This command `leaderf rg -g!xxx` is working.

**Comment by retzzz** [comment]
@Yggdroot
Suggest to let options `g:Lf_UseVersionControlTool` and `g:Lf_WildIgnore` work for `Leaderf rg` as well. So all functions of `Leaderf` will be consistent.

**Comment by weisiok365** [comment]
file "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 696, in input^@    callback()^@  File "/root/.vim/plugged/LeaderF/autoload/l
eaderf/python/leaderf/manager.py", line 70, in deco^@    func(self, *args, **kwargs)^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/ma
nager.py", line 2488, in _workInIdle^@    raise self._read_content_exception[1]^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager
.py", line 2461, in _readContent^@    for line in content:^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105,
 in read^@    raise Exception(lfBytes2Str(err, encoding))^@Exception: /bin/sh: 1: rg: not found

find key word
nnoremap <space>a :Leaderf rg -i<cr>
nnoremap <space>A :Leaderf rg -i --cword<cr>
xnoremap <space>a :<c-u>execute ":Leaderf rg -i --input " . <sid>GetSelectArea()<cr>
xnoremap <space>A :<c-u>execute ":Leaderf rg -i " . <sid>GetSelectArea()<cr><tab>

cannot use
have a find windows left the origin location ,so no way to clear

**Comment by Yggdroot** [comment]
> file "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 696, in input^@ callback()^@ File "/root/.vim/plugged/LeaderF/autoload/l eaderf/python/leaderf/manager.py", line 70, in deco^@ func(self, *args, **kwargs)^@ File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/ma nager.py", line 2488, in _workInIdle^@ raise self._read_content_exception[1]^@ File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager .py", line 2461, in _readContent^@ for line in content:^@ File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105, in read^@ raise Exception(lfBytes2Str(err, encoding))^@exception: /bin/sh: 1: rg: not found
> 
> find key word nnoremap a :Leaderf rg -i nnoremap A :Leaderf rg -i --cword xnoremap a :execute ":Leaderf rg -i --input " . GetSelectArea() xnoremap A :execute ":Leaderf rg -i " . GetSelectArea()
> 
> cannot use have a find windows left the origin location ,so no way to clear

Please install rg first.
