### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#530]
`Leaderf mru`

delete all items, press `dd` will raise error.

screenshot:
![GIF](https://user-images.githubusercontent.com/5853792/76851105-a8c97180-6883-11ea-8bee-0d615d3f9cad.gif)

**Comment by Yggdroot** [comment]
It's fixed.

**Comment by bstaint** [comment]
没问题了，谢谢。
