### ISSUE TITLE
[Feature request] let `leaderf#Rg#visual()` also capture `vim * search text`

### ISSUE THREAD

**Issue by icycandy** [Yggdroot/LeaderF#531]
When press `*`, vim will search the word under cursor, is it good for `leaderf#Rg#visual()` also capture this?

**Comment by Yggdroot** [comment]
I think they are different thing.

**Comment by icycandy** [comment]
Thanks.

**Comment by icycandy** [comment]
For those who want this feature, can add the following code in your `.vimrc`
Code was inspired by [this](https://github.com/Yggdroot/LeaderF/blob/master/autoload/leaderf/Rg.vim#L53) and [this](https://stackoverflow.com/a/27732667/522159)
```vim
function MyGetSearch()
    try
        let x_save = @x
        norm! gv"xy
        if @x == ""
            normal! gn"xy
        endif
        return '"' . escape(@x, '"') . '"'
    finally
        let @x = x_save
    endtry
endfunction

noremap <leader>lf :<C-U><C-R>=printf("Leaderf rg %s", MyGetSearch())<CR><CR>
```

**Comment by icycandy** [comment]
I'm sorry. The above `MyGetSearch()` not work as expected.

When nothing is visual selected, it is expected to return empty string, but indeed it returned the previous selected text.

I don't know how to fix it.
