### ISSUE TITLE
add -1 option like fzf

### ISSUE THREAD

**Issue by paopaol** [Yggdroot/LeaderF#534]
fzf has a option `-1`, if only one candidate matched, accepted it directly.could  leaderf add such option,if has no such option, i have to type enter to accepted it manual.

**Comment by Yggdroot** [comment]
I can not figure out the scenario that needs this option in LeaderF.

**Comment by tamago324** [comment]
You might use it when you want to jump to the definition source.

For example, if you want to jump to the  function definition under the cursor

```vim
nnoremap <silent> <C-g><C-r> :<C-u><C-r>=printf('Leaderf bufTag --input %s', leaderf#Rg#getPattern(0))<CR><CR>
```

What do you think?
However, since you only have to press Enter once right after it appears, it may not be necessary.

**Comment by tamago324** [comment]
I thought about it for a minute, but it doesn't seem necessary.
I'm sorry.
