### ISSUE TITLE
Leaderf! rg --recall exception

### ISSUE THREAD

**Issue by HuanGong** [Yggdroot/LeaderF#537]
- vim or neovim? 
    - [*] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  8.2
- Output of `:echo has("python")`:  yes
- Output of `:echo has("python3")`:  yes
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [*] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vimscript
let g:Lf_ShortcutF = "<leader>ff"
  if executable("rg")
    noremap <leader>tq :<C-U>Leaderf! rg --recall<CR>
    noremap <leader>go :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
    noremap <leader>fc :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
    noremap <leader>fb :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR>
endif
```
### Describe your question, feature request, or bug.
```bash
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gh/.ltvim/Plug/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 797, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/gh/.ltvim/Plug/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 729, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/gh/.ltvim/Plug/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 718, in startExplorer
    super(RgExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/gh/.ltvim/Plug/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2052, in startExplorer
    self._bangEnter()
  File "/home/gh/.ltvim/Plug/LeaderF/autoload/leaderf/python/leaderf/rgExpl.py", line 639, in _bangEnter
    instance.window.cursor = (max(instance.cursorRow - instance.helpLength, 1), 0)
vim.error: cursor position outside buffer
```

**Comment by Yggdroot** [comment]
What is the **Steps to reproduce**?

**Comment by HuanGong** [comment]
> What is the **Steps to reproduce**?

- in editor, using <leader>fc got the rg result
- choose one result item or just close result window
- using key: <leader>tq (ps: just recall the result window)
- error occur

**Comment by Yggdroot** [comment]
I still cannot reproduce it. Are you using the latest LeaderF?
Could you provide a minimum vimrc to reproduce it please?
