### ISSUE TITLE
do not show devicons by default

### ISSUE THREAD

**Issue by habamax** [Yggdroot/LeaderF#538]
With the recent update I can see squares before filenames when I try to open a file:

![image](https://user-images.githubusercontent.com/234774/78004575-f691af80-7342-11ea-842f-1bf625e19548.png)

(vim in cmd, gvim, neovim(qt), nvim in WSL)

Would it be possible to not apply devicons (or what is this?) by default?

**Comment by tamago324** [comment]
You can hide it below.
```vim
let g:Lf_ShowDevIcons = 0
```

**Comment by habamax** [comment]
> 
> 
> You can hide it below.
> 
> ```viml
> let g:Lf_ShowDevIcons = 0
> ```

I did in the end. 

Do you think this is a good idea to make default setting which probably(?) wouldn't work for most of users?

**Comment by tamago324** [comment]
I didn't think most users would be able to use it, so I left the default value enabled.
I'm sorry. I didn't take enough into account.

**Comment by Yggdroot** [comment]
Show icons by default to let more people know this feature, maybe several days later I'll disable it by default.

**Comment by tamago324** [comment]
That might be good too.
