### ISSUE TITLE
LeaderF line  是什么意思？line是什么？又该如何使用？

### ISSUE THREAD

**Issue by ly1243667342** [Yggdroot/LeaderF#542]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
在当前buffer里查找行

**Comment by ly1243667342** [comment]
你好，查找行是什么？和普通的查找有什么区别？谢谢

**Comment by Yggdroot** [comment]
跟vim下的/ 查找差不多，你用一下就知道了。
