### ISSUE TITLE
This operation must be run in a work tree

### ISSUE THREAD

**Issue by Shamaoke** [Yggdroot/LeaderF#544]
When running Vim inside a Git controlled repository and then lcd to the `.git` directory and run `:LeadeF file` I get `Exception('fatal: this operation must be run in a work tree\n')`.

_Linux (Arch)_
_Vim 8.2_
_echo has("python") ~> 1_
_echo has("python3") ~> 0_
_echo &pythondll ~> libpython2.7.so.1.0_
_echo &pythonthreedll ~> libpython3.8.so.1.0_
_py print(sys.version) ~> 2.7.17 [GCC 9.3.0]_
_p3 print(sys.version) ~>_
`E837: This Vim cannot execute :py3 after using :python`
`E267: Sorry, this command is disabled, the Python library could not be loaded`

**Comment by Yggdroot** [comment]
Why did you lcd to the .git? 
```vim
let g:Lf_UseVersionControlTool = 0
```

**Comment by Shamaoke** [comment]
Sometimes it's needed to edit files in it (e. g. `hooks`, `info/exclude`, etc.).

`let g:Lf_UseVersionControlTool = 0`

I know this option, but I think it's better to catch the exception. It's confusing.

**Comment by Yggdroot** [comment]
It's because LeaderF uses `git ls-files` to create the index, your usage of git will throw the exception.
`let g:Lf_UseVersionControlTool = 0` will stop LeaderF from using `git ls-files` and use other command instead.

**Comment by Yggdroot** [comment]
And I don't think it is Leaderf 's job to catch the exception. It is the wrong usage of git.

**Comment by Shamaoke** [comment]
When I run `git ls-files` inside the `.git` directory, it still outputs the files which are tracked by the VCS. No exceptions are raised.

May be it's better to take this functional away into a separate mode, `vcs` for example. So, `:Leaderf vcs` will display the files tracked by Git and `:Leaderf file` will display all files in the cwd.

**Comment by Yggdroot** [comment]
I don't think it is necessary.

**Comment by Shamaoke** [comment]
> I don't think it is necessary

How one is supposed to find files __untracked__ by the VCS in the `Lf_UseVersionControlTool = 1` mode?
