### ISSUE TITLE
Reproduce issue #473.

### ISSUE THREAD

**Issue by yan42685** [Yggdroot/LeaderF#545]
#473  

Vim or NeoVim:
   - [ ] vim
   - [x] neovim

OS:
   - [x] Linux
   - [ ] Mac OS X
   - [ ] Windows
   - [ ] Etc.

Related settings:
```vim
set foldenable
set foldmethod=marker
set foldlevel=0     " I guess this option causes that issue.
set foldopen=block,hor,mark,percent,quickfix,search,tag,undo
```

**Comment by yan42685** [comment]
`:Leaderf line` will automatically unfold but `:leaderf rg` won't.

**Comment by Yggdroot** [comment]
Still can not reproduce. Could you provide a minimum vimrc and the steps to reproduce please?

**Comment by yan42685** [comment]
···
let mapleader = '<space>'
call plug#begin('~/.vim/plugged')

Plug 'Yggdroot/LeaderF', {'do': './install.sh'}
nnoremap <silent> / :Leaderf rg --current-buffer<cr>
call plug#end()

" ==========================================
" 设置 Settings
" ==========================================
filetype on  "{{{
set clipboard+=unnamedplus
set foldenable
set foldmethod=marker
set foldlevel=0
"}}}
set foldopen=block,hor,mark,percent,quickfix,search,tag,undo
function! s:Autosave(timed)
    if &readonly || mode() == 'c' || pumvisible()
        return
    endif
    let current_time = localtime()
    let s:last_update = get(s:, 'last_update', 0)
    let s:time_delta = current_time - s:last_update

    if a:timed == 0 || s:time_delta >= 1
        let s:last_update = current_time
        if &buftype != 'nofile'  " 不对非文件的buffer进行检测
            checktime  " checktime with autoread will sync files on a last-writer-wins basis.
        endif
        silent! doautocmd BufWritePre %  " needed for soft checks
        silent! update  " only updates if there are changes to the file.
        if a:timed == 0 || s:time_delta >= 4
            silent! doautocmd BufWritePost %  " Periodically trigger BufWritePost.
        endif
    endif
endfunction

augroup Autosave
    au! BufLeave,FocusLost,FocusGained * call s:Autosave(0)
    au! CursorHold * call s:Autosave(1)
augroup end
···
Autosave and `let foldlevel=0` are the root cause.
I notice that when Leaderf call rg, the buffer will be saved. Then all folds will be closed.

**Comment by yan42685** [comment]
Maybe Saving the buffer when calling rg is inevitable?

**Comment by Yggdroot** [comment]
修复了。

**Comment by yan42685** [comment]
大哥你这效率可真高啊 我评论的语法错误都没改完 :joy:

**Comment by yan42685** [comment]
:+1:
