### ISSUE TITLE
can it provide a hotkey to delete(wipe out) buffer, close window in `Leaderf buf`, `Leaderf window`?

### ISSUE THREAD

**Issue by Freed-Wu** [Yggdroot/LeaderF#546]

**Comment by Yggdroot** [comment]
normal mode，d

**Comment by tamago324** [comment]
The `Leaderf window` does not have a `delete` feature, so I will implement it later.

**Comment by Freed-Wu** [comment]
thanks! i notice 'd' in normal mode is useful. can it provide a hotkey in insert mode? it will be more convenient!

**Comment by Yggdroot** [comment]
I think `d` in normal mode is also convenient, so won't add in input mode.
