### ISSUE TITLE
Error when delete the last buffer on a tab page with `Leaderf buffer --popup`.

### ISSUE THREAD

**Issue by tamago324** [Yggdroot/LeaderF#548]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 21 2020 23:11:36)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-140
Compiled by appveyor@APPVYR-WIN
```

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: `1`
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: `3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]`
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```vim
set encoding=utf-8
scriptencoding utf-8

syntax enable
filetype plugin indent on

set nocompatible

set runtimepath^=~/ghq/github.com/tamago324/LeaderF

lang mess en
```

### Describe your question, feature request, or bug.

An error occurred when deleting the last buffer of the current tab page with `d` in normal mode of `Leaderf buffer --popup`.

### Steps to reproduce

1. `:tabedit`
2. `:Leaderf buffer --popup`
3. Switch to normal mode using `<Tab>`
4. Delete the last buffer of the current tab page with a `d`

### Actual behaviour

```vim
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
Traceback (most recent call last):
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
  File "<string>", line 1, in <module>
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
  File "C:\Users\user\ghq\github.com\tamago324\LeaderF\autoload\leaderf\python\leaderf\bufExpl.py", line 263, in deleteBuffer
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
    del instance._buffer_object[instance.window.cursor[0] - 1]
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
  File "C:\Users\user\ghq\github.com\tamago324\LeaderF\autoload\leaderf\python\leaderf\instance.py", line 111, in cursor
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
    lfCmd("""call win_execute(%d, 'let cursor_pos = getpos(".")') | let cursor_pos[2] -= 1""" % self._winid)
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
vim.error: Vim(let):E684: list index out of range: 2
Error detected while processing function leaderf#Buffer#NormalModeFilter:
line   81:
E171: Missing :endif
```

### Expected behaviour

i hope you don't get any errors.

**Comment by Yggdroot** [comment]
I can not reproduce it.

**Comment by tamago324** [comment]
Does that mean I can successfully delete the last buffer (the current buffer) in the current tab?
Does this happen with GVim on Windows?

**Comment by Yggdroot** [comment]
Yes. I think it works the same either on Linux or Windows.
