### ISSUE TITLE
random colorscheme?

### ISSUE THREAD

**Issue by Freed-Wu** [Yggdroot/LeaderF#549]
i notice all the colorschemes of leaderf are beautiful. can it provide a random colorscheme for user to own all of them?

and how can i change Leaderfcolorsceme after vim had init? change g:Lf_StlColorscheme looks like useless.

and how can user know current colorschem of leaderf? echo g:Lf_StlColorscheme looks like useless, too.

and looks like if use popup, some my favourite colorschems cannot be used?

thanks! it is an enhancement!

**Comment by Yggdroot** [comment]
> i notice all the colorschemes of leaderf are beautiful. can it provide a random colorscheme for user to own all of them?
> 

Won't do that.

> and how can i change Leaderfcolorsceme after vim had init? change g:Lf_StlColorscheme looks like useless.
> 
set g:Lf_StlColorscheme  in vimrc.

> and how can user know current colorschem of leaderf? echo g:Lf_StlColorscheme looks like useless, too.
> 

If you have not set `g:Lf_StlColorscheme`, you are using the default colorscheme, otherwise you should know what it is.

> and looks like if use popup, some my favourite colorschems cannot be used?
> 
> thanks! it is an enhancement!
