### ISSUE TITLE
switching to fuzzy mode

### ISSUE THREAD

**Issue by thisguychris** [Yggdroot/LeaderF#55]
In the documentation, pressing <Ctrl-R> switches between Regex and Fuzzy mode. 
https://github.com/Yggdroot/LeaderF/blob/master/doc/leaderf.txt#L469

On my end, it's switching between Fullpath (I guess it's still fuzzy) and regex mode.

I've tried adding this in my vimrc
`let g:Lf_DefaultMode="Fuzzy" `

to switch to Fuzzy mode, and I'm getting mixed results:

When searching this file, view-page-desktop.js for example, if I search "view " with a space, it returns zero results.  Is that an intended behaviour?

Any option to make it more fuzzy?  Or do I need to switch to regex?

**Comment by Yggdroot** [comment]
FullPath and NameOnly are fuzzy mode. You don't have to set the option `g:Lf_DefaultMode`. If you want to start with the FullPath mode or regex mode, you can set it.(By default, it's NameOnly mode).
If you are in fuzzy mode, you don't need to type `<space>`, `<space>` is considered to be a character, so if you search "view" with a space, it will match a file name with space in it. e.g., `view-page desktop.js`. `view-page-desktop.js` does not match. 
It's already very fuzzy, "view" can match such kind of name, for instance, "**v**xxx**i**xxx**e**xxx**w**xxx.js", "**v**xxx**I**xxx**E**xxx**w**xxx.js"
If you intend to match `view-page-desktop.js`, you can input `viewpd`, no need to type space.

**Comment by thisguychris** [comment]
Hi, thanks for the reply, @Yggdroot, I guess I'm just used to typing space. 😢   

Is it possible to define delimiters for a file name like dashes, underscore and spaces are all treated the same?

Just to site you what I previously use: Sublime Text Fuzzy finder, Visual Studio Code and FZF, all yield results on "view desktop" with space.

Sorry, Just clarifying things.

**Comment by Yggdroot** [comment]
I don't understand why type more characters(with spaces) to get the same result? I can not see any advantage.
