### ISSUE TITLE
in some path :Leaderf file will not work

### ISSUE THREAD

**Issue by Freed-Wu** [Yggdroot/LeaderF#550]
as the following picture, my `~/Documents` exist many files, but leaderf cannot find these files. even if  i press `<F5>` to refresh. it still can not find.

![image](https://user-images.githubusercontent.com/32936898/78421047-68d9fb00-7687-11ea-9080-e1fe312125f3.png)

for other some path, the phenomena exist, sometimes.

OS: Linux 5.4
Vim: gvim8.2
Leaderf: Latest

Thanks!

**Comment by Yggdroot** [comment]
Output of :echo g:Lf_Debug_Cmd？

**Comment by Freed-Wu** [comment]
```
git ls-files  "." && git ls-files --others --exclude-standard  -x ".svn" -x ".hg" -x "*.sw?" -x "~$*" -x "*.bak" -x "*.exe" -x "*.o" -x "*.so" -x "*.py[co]" "."
```

**Comment by Yggdroot** [comment]
run the cmd in the command line to see the output.

**Comment by Freed-Wu** [comment]
![image](https://user-images.githubusercontent.com/32936898/78465103-0edb4300-7724-11ea-9fab-c9c012d371a3.png)

**Comment by Yggdroot** [comment]
not in Vim，in shell.

**Comment by Freed-Wu** [comment]
![image](https://user-images.githubusercontent.com/32936898/78470584-53370500-775d-11ea-9861-ead4b54c09a6.png)

**Comment by Yggdroot** [comment]
Run 
```
git ls-files  "." && git ls-files --others --exclude-standard  -x ".svn" -x ".hg" -x "*.sw?" -x "~$*" -x "*.bak" -x "*.exe" -x "*.o" -x "*.so" -x "*.py[co]" "."
```
in shell, Leaderf file executes this command under the hood.

**Comment by Freed-Wu** [comment]
![image](https://user-images.githubusercontent.com/32936898/78555292-4b4f9180-783f-11ea-8930-912ebbccedef.png)

i found this phenomenon is probably related with git. if a .git exist in a parent directory of a directory, leaderf will only search file of gitignore. i backup my shell rc and some other rc in `~`.... but i still don't know why:(

**Comment by Yggdroot** [comment]
我们还是说中文吧。
是不是这条命令在命令行依然没有输出？我不清楚你的目录是怎么样被git管理的，是不是都放到.gitignore里去了。这其实是个git相关的问题，看看为什么`git ls-files`没有输出。

**Comment by Freed-Wu** [comment]
噢，我明白了，就是Leaderf 依赖git进行搜索，gitignore忽略的文件Leaderf 就无法搜索到，对吗？

**Comment by Freed-Wu** [comment]
噢，我明白了，`let g:Lf_UseVersionControlTool = 0` 之后，就可以搜索被gitignore忽略的文件。

看了一下Leader 依赖的rg 也是这样的。默认依赖 .gitignore，除非在配置文件指明`-uuu`，才会像以前的grep一样不依赖.gitignore。Leaderf 这样做也是对的。是我out了：）没用过rg

感谢！也希望能对其他人有所帮助。

**Comment by Yggdroot** [comment]
`Leaderf file --no-ignore` 这样也可以。
