### ISSUE TITLE
加载 Startify 的 session 之后，经常会出现 Leaderf 部分功能不能使用的情况

### ISSUE THREAD

**Issue by yan42685** [Yggdroot/LeaderF#551]
- vim or neovim? 
    - [ ] vim
    - [x] neovim

- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.
不在 session 内的时候一切正常，加载 Startify 的 session 后如题，不过在设置 `let g:Lf_ShowDevIcons = 0` 之后就能正常使用了

![image](https://user-images.githubusercontent.com/41834091/78501030-8b097100-778c-11ea-95b5-fd69631c3016.png)

### Steps to reproduce
- 安装Startify插件
- `:SSave test`
- `:qa`
- `nvim`
- `:SLoad test`
- `:Leaderf buffer` 、`:Leaderf file`、`:Leaderf mru` 不能使用，但是 `:Leaderf rg`、`:Leaderf line` 可以使用

**Comment by yan42685** [comment]
加载Session后也不是每次都不能使用 `:Leaderf buffer` 、`:Leaderf file`、`:Leaderf mru` ，就是一开始可能能用，但是再次加载这个 session 可能 Leaderf 就会报错了了

**Comment by Yggdroot** [comment]
我觉得这如果是bug也是Startify 的bug，session 恢复后应该跟之前一模一样，它没做到。

**Comment by Yggdroot** [comment]
因为它没有把highlight group保存起来。

**Comment by Yggdroot** [comment]
LeaderF做了点修改，让Startify的bug不暴露出来。

**Comment by yan42685** [comment]
能这么快搞定真是太好了，想点10个star，这个插件相当好用 :+1:
