### ISSUE TITLE
MacVim通过LeaderF打开文件中文乱码

### ISSUE THREAD

**Issue by yiguo-bj** [Yggdroot/LeaderF#554]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
    - [x] Macvim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 21:29:07)
macOS version
Included patches: 1-319
Compiled by Homebrew
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.7
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
set encoding=utf-8
let &termencoding=&encoding
set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,latin1,gbk,gb2312
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_UseVersionControlTool = 0
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
let g:Lf_AutoResize = 1

" let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_RootMarkers = ['.git', '.hg', '.svn']
nnoremap <silent> <Leader>t :LeaderfBufTag<CR>
nnoremap <silent> <Leader>l :LeaderfLine<CR>
nnoremap <silent> <Leader>m :LeaderfMru<CR>
nnoremap <silent> <Leader>h :LeaderfHistoryCmd<CR>

" search word under cursor literally only in current buffer
noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR>
```

### Describe your question, feature request, or bug.
vim中是正常的，macvim直接用路径打开文件显示也是正常，但是通过leaderf显示中文为乱码。

### Steps to reproduce
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 21:29:07)
macOS version
Included patches: 1-319
Compiled by Homebrew
![image](https://user-images.githubusercontent.com/59589729/78751310-8cad8180-79a4-11ea-807e-24dc74c457ee.png)

实际上是 测试.txt，但是显示乱码。
![image](https://user-images.githubusercontent.com/59589729/78751680-44429380-79a5-11ea-8a27-f67d0a944971.png)
打开后：
![image](https://user-images.githubusercontent.com/59589729/78751838-84097b00-79a5-11ea-972d-4025be793765.png)

直接通过路径打开，``mvim 测试.txt``
![image](https://user-images.githubusercontent.com/59589729/78751890-9c799580-79a5-11ea-811a-97e08fb858ae.png)

**Comment by Yggdroot** [comment]
能否来个截图？
macvim是指mac上的gui vim吧？

**Comment by yiguo-bj** [comment]
> * vim or neovim? 
>   
>   * [ ]  vim
>   * [ ]  neovim
>   * [x]  Macvim
> * Output of `vim --version` or `nvim --version`:
>   VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar  3 2020 21:29:07)
>   macOS version
>   Included patches: 1-319
>   Compiled by Homebrew
> * Output of `:echo has("python")`: 0
> * Output of `:echo has("python3")`: 1
> * Output of `:echo &pythondll`(only vim, not neovim):
> * Output of `:echo &pythonthreedll`(only vim, not neovim):
> * Output of `:py print(sys.version)`:
> * Output of `:py3 print(sys.version)`: 3.7.7
> * Output of `:echo g:Lf_Debug_Cmd`:
> * Output of `:echo g:Lf_FilesFromCache`:
> * Operating system: 
>   
>   * [ ]  Linux
>   * [x]  Mac OS X
>   * [ ]  Windows
>   * [ ]  Etc.
> * Configurations related to LeaderF in vimrc:
>   set encoding=utf-8
>   let &termencoding=&encoding
>   set fileencodings=ucs-bom,utf-8,cp936,gb18030,big5,latin1,gbk,gb2312
>   let g:Lf_ShortcutF = ''
>   let g:Lf_WindowPosition = 'popup'
>   let g:Lf_PreviewInPopup = 1
>   let g:Lf_UseVersionControlTool = 0
>   let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
>   let g:Lf_AutoResize = 1
> 
> " let g:Lf_WorkingDirectoryMode = 'Ac'
> let g:Lf_RootMarkers = ['.git', '.hg', '.svn']
> nnoremap t :LeaderfBufTag
> nnoremap l :LeaderfLine
> nnoremap m :LeaderfMru
> nnoremap h :LeaderfHistoryCmd
> 
> " search word under cursor literally only in current buffer
> noremap :=printf("Leaderf! rg -F --current-buffer -e %s ", expand(""))
> 
> ### Describe your question, feature request, or bug.
> vim中是正常的，macvim直接用路径打开文件显示也是正常，但是通过leaderf显示中文为乱码。
> 
> ### Steps to reproduce
> ### Actual behaviour
> ### Expected behaviour

**Comment by yiguo-bj** [comment]
> 能否来个截图？
> macvim是指mac上的gui vim吧？
> 使用的是Python2还是Python3？

已补充信息到上面了。

**Comment by Yggdroot** [comment]
复现不了，可能跟环境有关系。
两种情况下的`echo &fileencoding` 和`echo &encoding`分别是什么？

**Comment by yiguo-bj** [comment]
> echo &fileencoding

都是utf-8

**Comment by Yggdroot** [comment]
既然一样，为什么一个有乱码一个没有，搞不明白。

**Comment by yiguo-bj** [comment]
> 既然一样，为什么一个有乱码一个没有，搞不明白。

又试了一下ctrlp是正常的，好奇怪

**Comment by WoodyGuo** [comment]
刚刚更新了 LeaderF 也遇到了此问题

**Comment by Yggdroot** [comment]
> 刚刚更新了 LeaderF 也遇到了此问题

确定是同一个问题？ 而不是仅仅第一列？

**Comment by jzdxeb** [comment]
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 23:05:13)
macOS version
Included patches: 1-2234
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cursorshape       +job               +mouse_urxvt       +signs             +user_commands
+arabic            +dialog_con_gui    +jumplist          +mouse_xterm       +smartindent       +vartabs
+autocmd           +diff              +keymap            +multi_byte        -sound             +vertsplit
+autochdir         +digraphs          +lambda            +multi_lang        +spell             +virtualedit
-autoservername    +dnd               +langmap           -mzscheme          +startuptime       +visual
+balloon_eval      -ebcdic            +libcall           +netbeans_intg     +statusline        +visualextra
+balloon_eval_term +emacs_tags        +linebreak         +num64             -sun_workshop      +viminfo
+browse            +eval              +lispindent        +odbeditor         +syntax            +vreplace
++builtin_terms    +ex_extra          +listcmds          +packages          +tag_binary        +wildignore
+byte_offset       +extra_search      +localmap          +path_extra        -tag_old_static    +wildmenu
+channel           -farsi             +lua               +perl              -tag_any_white     +windows
+cindent           +file_in_path      +menu              +persistent_undo   -tcl               +writebackup
+clientserver      +find_in_path      +mksession         +postscript        +termguicolors     -X11
+clipboard         +float             +modify_fname      +printer           +terminal          -xfontset
+cmdline_compl     +folding           +mouse             +profile           +terminfo          +xim
+cmdline_hist      -footer            +mouseshape        -python            +termresponse      -xpm
+cmdline_info      +fork()            +mouse_dec         +python3           +textobjects       -xsmp
+comments          +fullscreen        -mouse_gpm         +quickfix          +textprop          -xterm_clipboard
+conceal           -gettext           -mouse_jsbterm     +reltime           +timers            -xterm_save
+cryptv            -hangul_input      +mouse_netterm     +rightleft         +title
+cscope            +iconv             +mouse_sgr         +ruby              +toolbar
+cursorbind        +insert_expand     -mouse_sysmouse    +scrollbind        +transparency


echo &fileencoding && echo &encoding
0 utf-8



![image](https://user-images.githubusercontent.com/19486826/78894048-f6aa5180-7a9e-11ea-82d3-c4a5e2b8114d.png)

**Comment by jzdxeb** [comment]
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 23:05:13)
> macOS version
> Included patches: 1-2234
> Compiled by Homebrew
> Huge version with MacVim GUI. Features included (+) or not (-):
> +acl +cursorshape +job +mouse_urxvt +signs +user_commands
> +arabic +dialog_con_gui +jumplist +mouse_xterm +smartindent +vartabs
> +autocmd +diff +keymap +multi_byte -sound +vertsplit
> +autochdir +digraphs +lambda +multi_lang +spell +virtualedit
> -autoservername +dnd +langmap -mzscheme +startuptime +visual
> +balloon_eval -ebcdic +libcall +netbeans_intg +statusline +visualextra
> +balloon_eval_term +emacs_tags +linebreak +num64 -sun_workshop +viminfo
> +browse +eval +lispindent +odbeditor +syntax +vreplace
> ++builtin_terms +ex_extra +listcmds +packages +tag_binary +wildignore
> +byte_offset +extra_search +localmap +path_extra -tag_old_static +wildmenu
> +channel -farsi +lua +perl -tag_any_white +windows
> +cindent +file_in_path +menu +persistent_undo -tcl +writebackup
> +clientserver +find_in_path +mksession +postscript +termguicolors -X11
> +clipboard +float +modify_fname +printer +terminal -xfontset
> +cmdline_compl +folding +mouse +profile +terminfo +xim
> +cmdline_hist -footer +mouseshape -python +termresponse -xpm
> +cmdline_info +fork() +mouse_dec +python3 +textobjects -xsmp
> +comments +fullscreen -mouse_gpm +quickfix +textprop -xterm_clipboard
> +conceal -gettext -mouse_jsbterm +reltime +timers -xterm_save
> +cryptv -hangul_input +mouse_netterm +rightleft +title
> +cscope +iconv +mouse_sgr +ruby +toolbar
> +cursorbind +insert_expand -mouse_sysmouse +scrollbind +transparency
> 
> echo &fileencoding && echo &encoding
> 0 utf-8
> 
> ![image](https://user-images.githubusercontent.com/19486826/78894048-f6aa5180-7a9e-11ea-82d3-c4a5e2b8114d.png)

只是这个窗口有乱码

**Comment by Yggdroot** [comment]
@jzdxeb 这是一个feature，就是显示文件类型对应的图标，需要字体支持。
不想显示 `let g:Lf_ShowDevIcons = 0`，想显示就要装一下字体。

**Comment by jzdxeb** [comment]
> @jzdxeb 这是一个feature，就是显示文件类型对应的图标，需要字体支持。
> 不想显示 `let g:Lf_ShowDevIcons = 0`，想显示就要装一下字体。

多谢 解惑 之前没看到过默认开启的吗?

**Comment by Yggdroot** [comment]
> > @jzdxeb 这是一个feature，就是显示文件类型对应的图标，需要字体支持。
> > 不想显示 `let g:Lf_ShowDevIcons = 0`，想显示就要装一下字体。
> 
> 多谢 解惑 之前没看到过默认开启的吗?

默认开启的。不这样估计有人永远不知道有这个feature。

**Comment by jzdxeb** [comment]
> > > @jzdxeb 这是一个feature，就是显示文件类型对应的图标，需要字体支持。
> > > 不想显示 `let g:Lf_ShowDevIcons = 0`，想显示就要装一下字体。
> > 
> > 
> > 多谢 解惑 之前没看到过默认开启的吗?
> 
> 默认开启的。不这样估计有人永远不知道有这个feature。

有道理,新功能只有在闲了的时候 看readme 才能发现,但是闲的时候太少...

leaderf 很好用加油

**Comment by yiguo-bj** [comment]
> et g:Lf_ShowDevIcons =

哈哈，关闭这个功能就好了，有bug哦

**Comment by Yggdroot** [comment]
> > et g:Lf_ShowDevIcons =
> 
> 哈哈，关闭这个功能就好了，有bug哦

我认为是Vim有bug，leaderf窗口有乱码也就罢了，进入到buffer中还有乱码，这应该是vim的bug。

**Comment by connectluole** [comment]
感天动地啊，这个乱码困扰我好久
