### ISSUE TITLE
跳转到一个已被其他vim打开的文件会卡住

### ISSUE THREAD

**Issue by fly-potato-100** [Yggdroot/LeaderF#555]
不论是gtags还是rg，都遇到了这个情况：卡住不动，也无提示。

回车后能正常跳转。

是否可以以默认只读的方式直接跳转打开呢？

---------------------
补充一下：文件跳转的话，能正常出现编辑中、选择打开方式的提示

**Comment by Yggdroot** [comment]
首先，我觉得有提示比没有提示要好，这样可以知道再别的地方打开了。
其次，这个事情不应该LeaderF来做，你可以在vimrc里面加个`autocmd SwapExists * let v:swapchoice = 'o'`

**Comment by Yggdroot** [comment]
卡住确实是个问题。

**Comment by fly-potato-100** [comment]
> 首先，我觉得有提示比没有提示要好，这样可以知道再别的地方打开了。
> 其次，这个事情不应该LeaderF来做，你可以在vimrc里面加个`autocmd SwapExists * let v:swapchoice = 'o'`

理解，感谢解答:)

**Comment by Yggdroot** [comment]
修复了，更新一下就会有提示了。
