### ISSUE TITLE
macvim下无法使用leaderf rg

### ISSUE THREAD

**Issue by cncqtan** [Yggdroot/LeaderF#557]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb 29 2020 00:47:39)
macOS version
Included patches: 1-503, 505-680, 682-2292
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
-arabic            +file_in_path      -mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       -termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
-balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            -gettext           +num64             +textprop
+builtin_terms     -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        -vartabs
+clipboard         -keymap            +printer           +vertsplit
+cmdline_compl     +lambda            -profile           +virtualedit
+cmdline_hist      -langmap           +python/dyn        +visual
+cmdline_info      +libcall           -python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
-conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          -rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            -mouse_dec         +statusline        -xsmp
-emacs_tags        -mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          -mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.7 (default, Mar 10 2020, 15:43:33)
 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
  let g:Lf_WindowPosition = 'popup'
  let g:Lf_PreviewInPopup = 1
  let g:Lf_PreviewCode = 1
  let g:Lf_PreviewResult = {
        \ 'File': 0,
        \ 'Buffer': 0,
        \ 'Mru': 0,
        \ 'Tag': 0,
        \ 'BufTag': 1,
        \ 'Function': 1,
        \ 'Line': 0,
        \ 'Colorscheme': 0,
        \ 'Rg': 1,
        \ 'Gtags': 0
        \}
  let g:Lf_ShowRelativePath = 0
  let g:Lf_DefaultMode='NameOnly'
  let g:Lf_UseVersionControlTool = 0
  let g:Lf_DefaultExternalTool = 'rg'
  let g:Lf_WildIgnore = {
        \ 'dir': ['.svn','.git'],
        \ 'file': ['.tags','compile_commands.json']
        \}
  nnoremap <Leader>t :LeaderfBufTag<CR>
  nnoremap <Leader>T :LeaderfTag<CR>
  noremap <leader>g :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
  noremap <leader>G :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>

### Describe your question, feature request, or bug.
<img width="507" alt="image" src="https://user-images.githubusercontent.com/11835195/78978708-e2bd2900-7b4c-11ea-8683-08283acd433b.png">
macvim下使用leaderf rg，总是没有任何结果输出。

### Steps to reproduce
:Leaderf! rg -e plugin_manager#leaderf_config
### Actual behaviour
<img width="487" alt="image" src="https://user-images.githubusercontent.com/11835195/78978829-2e6fd280-7b4d-11ea-933d-92ce5a593187.png">

### Expected behaviour
<img width="537" alt="image" src="https://user-images.githubusercontent.com/11835195/78978776-11d39a80-7b4d-11ea-8c32-b4f635c2d1b7.png">

**Comment by Yggdroot** [comment]
leaderf rg在任何系统都能使用。你如果遇到什么问题请把问题描述清楚。

**Comment by cncqtan** [comment]
> leaderf rg在任何系统都能使用。你如果遇到什么问题请把问题描述清楚。

抱歉抱歉，一不小心按了回车，还没来得及补充描述就发送出去了，描述已更新。

**Comment by Yggdroot** [comment]
这个可能跟 #364 一个原因。

**Comment by cncqtan** [comment]
> 这个可能跟 #364 一个原因。

似乎是的，从终端启动的macvim没有这样的问题。
