### ISSUE TITLE
new feature request:open quickfix in leaderf 

### ISSUE THREAD

**Issue by cncqtan** [Yggdroot/LeaderF#558]
sometimes, we will have some result that will output to quick fix, such as 'make' command, I would like to have leaderf to open quickfix window.

**Comment by cncqtan** [comment]
> * vim or neovim? 
>   
>   * [ ]  vim
>   * [ ]  neovim
> * Output of `vim --version` or `nvim --version`:
> * Output of `:echo has("python")`:
> * Output of `:echo has("python3")`:
> * Output of `:echo &pythondll`(only vim, not neovim):
> * Output of `:echo &pythonthreedll`(only vim, not neovim):
> * Output of `:py print(sys.version)`:
> * Output of `:py3 print(sys.version)`:
> * Output of `:echo g:Lf_Debug_Cmd`:
> * Output of `:echo g:Lf_FilesFromCache`:
> * Operating system: 
>   
>   * [ ]  Linux
>   * [ ]  Mac OS X
>   * [ ]  Windows
>   * [ ]  Etc.
> * Configurations related to LeaderF in vimrc:
> 
> ### Describe your question, feature request, or bug.
> ### Steps to reproduce
> ### Actual behaviour
> ### Expected behaviour

**Comment by cncqtan** [comment]
I look for help in leaderf help document, but failed.

**Comment by tamago324** [comment]
Implemented by https://github.com/Yggdroot/LeaderF/pull/624.
Try it.

**Comment by cncqtan** [comment]
thanks, OK now
