### ISSUE TITLE
I saw a wired char in the popup window

### ISSUE THREAD

**Issue by etorth** [Yggdroot/LeaderF#559]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
:version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2020 09:21:58)
Compiled by matrix@vlsj-ctrh65
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +cmdline_hist      +ex_extra          +keymap            -mouse_gpm         +persistent_undo   +spell             +timers            +X11
-arabic            +cmdline_info      +extra_search      +lambda            -mouse_jsbterm     +popupwin          +startuptime       +title             -xfontset
+autocmd           +comments          -farsi             +langmap           +mouse_netterm     +postscript        +statusline        +toolbar           +xim
+autochdir         +conceal           +file_in_path      +libcall           +mouse_sgr         +printer           -sun_workshop      +user_commands     +xpm
-autoservername    +cryptv            +find_in_path      +linebreak         -mouse_sysmouse    +profile           +syntax            +vartabs           +xsmp_interact
+balloon_eval      +cscope            +float             +lispindent        +mouse_urxvt       +python/dyn        +tag_binary        +vertsplit         +xterm_clipboard
+balloon_eval_term +cursorbind        +folding           +listcmds          +mouse_xterm       +python3/dyn       -tag_old_static    +virtualedit       -xterm_save
+browse            +cursorshape       -footer            +localmap          +multi_byte        +quickfix          -tag_any_white     +visual
++builtin_terms    +dialog_con_gui    +fork()            +lua               +multi_lang        +reltime           +tcl/dyn           +visualextra
+byte_offset       +diff              +gettext           +menu              -mzscheme          +rightleft         +termguicolors     +viminfo
+channel           +digraphs          -hangul_input      +mksession         +netbeans_intg     -ruby              +terminal          +vreplace
+cindent           +dnd               +iconv             +modify_fname      +num64             +scrollbind        +terminfo          +wildignore
+clientserver      -ebcdic            +insert_expand     +mouse             +packages          +signs             +termresponse      +wildmenu
+clipboard         +emacs_tags        +job               +mouseshape        +path_extra        +smartindent       +textobjects       +windows
+cmdline_compl     +eval              +jumplist          +mouse_dec         -perl              +sound             +textprop          +writebackup
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/grid/common/pkgs/vim/v8.2/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/
cairo -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -g -O2 -D_RE
ENTRANT   -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -std=gnu99   -L/usr/local/lib -Wl,--as-needed -o vim   -pthread -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lpangocairo-1.0
-lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf -lns
l  -lselinux   -lcanberra   -lacl -lattr  -L/grid/common/pkgs/lua/v5.3.5//lib -llua    -L/usr/lib -ltclstub8.5 -ldl -lieee -lm
Press ENTER or type command to continue

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.so.1.0
- Output of `:py print(sys.version)`: 
2.7.8 (default, Dec 11 2019, 05:28:42)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

- Output of `:py3 print(sys.version)`: 
3.7.2 (default, Apr 22 2019, 02:54:03)
[GCC 4.8.3]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
find -L "." -name "." -o   -name ".*" -prune -o -type f -print  2>/dev/null | sed 's#^\./##'
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
650 " config for leaderF
651 " still uses ctrlp shortkey
652 let g:Lf_ShortcutF = '<C-P>'
653 let g:Lf_FollowLinks = 1
654 let g:Lf_PreviewInPopup = 1
655 let g:Lf_WindowPosition = 'popup'
656 let g:Lf_CommandMap = {'<C-J>': ['<C-N>'], '<C-K>': ['<C-P>']}
657 " let g:Lf_DefaultMode = 'NameOnly'
658 if !empty($P_HOME)
659     " let g:Lf_WorkingDirectory = $P_HOME
660     let g:Lf_RootMarkers = ['.P4Config', '.P4ignore']
661     let g:Lf_WorkingDirectoryMode = 'a'
662 endif

### Describe your question, feature request, or bug.

      
![image](https://user-images.githubusercontent.com/1754214/79061299-ad473700-7c43-11ea-8b2a-a328e44ca31d.png)

**Comment by Yggdroot** [comment]
this is a new feature "Show icons". it needs to install specific fonts.
