### ISSUE TITLE
LeaderfColorScheme not work in win32

### ISSUE THREAD

**Issue by tracyone** [Yggdroot/LeaderF#56]
here is the message:

>  searching ...
Error detected while processing function leaderf#Colors#startExpl[1]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tracyone\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 643, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "C:\Users\tracyone\vimfiles\bundle\LeaderF\autoload\leaderf\python\leaderf\colorschemeExpl.py", line 25, in getContent
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined

**vim version**

> 

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Aug  2 2017 22:09:43)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-844
Compiled by appveyor@APPVYR-WIN
Huge version with GUI.  Features included (+) or not (-):
+acl                +cmdline_info       +emacs_tags         +insert_expand      +mksession          +persistent_undo    +startuptime        +timers             +writebackup
+arabic             +comments           +eval               +job                +modify_fname       -postscript         +statusline         +title              -xfontset
+autocmd            +conceal            +ex_extra           +jumplist           +mouse              +printer            -sun_workshop       +toolbar            -xim
+balloon_eval       +cryptv             +extra_search       +keymap             +mouseshape         +profile            +syntax             +user_commands      +xpm_w32
+browse             +cscope             +farsi              +lambda             +multi_byte_ime/dyn +python/dyn         +tag_binary         +vertsplit          -xterm_save
++builtin_terms     +cursorbind         +file_in_path       +langmap            +multi_lang         +python3/dyn        +tag_old_static     +virtualedit        
+byte_offset        +cursorshape        +find_in_path       +libcall            +mzscheme/dyn       +quickfix           -tag_any_white      +visual             
+channel            +dialog_con_gui     +float              +linebreak          +netbeans_intg      +reltime            +tcl/dyn            +visualextra        
+cindent            +diff               +folding            +lispindent         +num64              +rightleft          -termguicolors      +viminfo            
+clientserver       +digraphs           -footer             +listcmds           +ole                +ruby/dyn           -terminal           +vreplace           
+clipboard          +directx            +gettext/dyn        +localmap           +packages           +scrollbind         -tgetent            +wildignore         
+cmdline_compl      -dnd                -hangul_input       +lua/dyn            +path_extra         +signs              -termresponse       +wildmenu           
+cmdline_hist       -ebcdic             +iconv/dyn          +menu               +perl/dyn           +smartindent        +textobjects        +windows            
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
  system gvimrc file: "$VIM\gvimrc"
    user gvimrc file: "$HOME\_gvimrc"
2nd user gvimrc file: "$HOME\vimfiles\gvimrc"
3rd user gvimrc file: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
    system menu file: "$VIMRUNTIME\menu.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE  -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32   -DWINVER=0x500 -D_WIN32_WINNT=0x500 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DFEAT_GUI_W32 -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a0solc.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a0solc.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=22 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby220.dll\" -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
Linking: link /RELEASE /nologo /subsystem:windows /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib  /machine:AMD64 /nodefaultlib libcmt.lib oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python35.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib xpm\x64\lib\libXpm.lib /PDB:gvim.pdb -debug

**Comment by Yggdroot** [comment]
Thanks for the report. Fixed.
