### ISSUE TITLE
cannot work with coc when open in first buffer

### ISSUE THREAD

**Issue by sunliang711** [Yggdroot/LeaderF#562]
- vim or neovim? 
    - [x] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: vim 8.2;  nvim 0.4.3
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
- Output of `:echo g:Lf_Debug_Cmd`:  Undefined variable
- Output of `:echo g:Lf_FilesFromCache`:  Undefined variable
- Operating system: 
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

let g:Lf_ShowDevIcons = 1
" let g:Lf_WindowPosition = 'popup'
" use <Ctrl>P to preview
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}

" file
let g:Lf_ShortcutF = "<leader><leader>f"
let g:Lf_ShortcutB = "<leader><leader>b"
nnoremap <leader><leader>m :Leaderf mru<CR>

nnoremap <leader><leader>s :Leaderf rg<CR>

nnoremap <leader>sn :Leaderf rg --next<CR>

nnoremap <leader>sp :Leaderf rg --previous<CR>

nnoremap <leader>sc :Leaderf --cword rg<CR>

nnoremap <leader><leader>g :Leaderf gtags<CR>

nnoremap <leader><leader>c :Leaderf command<CR>
nnoremap <leader><leader>h :Leaderf cmdHistory<CR>
nnoremap <leader><leader>w :Leaderf window<CR>

let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
if has('nvim')
    let g:Lf_CacheDirectory = expand('~/.config/.nvim/cache')
else
    let g:Lf_CacheDirectory = expand('~/.vim/cache')
endif
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'powerline'

### Describe your question, feature request, or bug.
when use 'leaderF file' to open a cpp file in FIRST buffer,then coc plugin not work, cann't use "go to define", cann't use "show doc",etc;
However, when use  ctrlP plugin or defx plugin or NerdTree plugin,coc plugin works normally.
### Steps to reproduce
1. cd to project directory
2. run vim or nvim
3. run :LeaderF file
4. type a cpp file;then <Enter> to open it
5. put cursor on a function call, CANNOT jump to function definitions
### Actual behaviour
CANNOT jump to function definitions
### Expected behaviour
Should jump to function definitions

**Comment by Yggdroot** [comment]
It's CoC that can not work but not LeaderF, so you should turn to Coc to find the reason. I'm not familiar with Coc, so I can not do any help.

**Comment by sunliang711** [comment]
But CtrlP,NerdTree,DefX can work well with Coc,I guess the way LeaderF to open file makes difference.

**Comment by Yggdroot** [comment]
So, if you are the author of LeaderF, how do you investigate this issue ? (I'm not familiar with Coc)
