### ISSUE TITLE
Lf_hl_stlBlank color group doesn't respect linked color group

### ISSUE THREAD

**Issue by habamax** [Yggdroot/LeaderF#564]
- vim or neovim? 
    - [x] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 22:02:13)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-566
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python38.dll
- Output of `:py print(sys.version)`: E370: Could not load library python27.dll
- Output of `:py3 print(sys.version)`: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [x] WSL
- Configurations related to LeaderF in vimrc: 

```
    let g:Lf_StlSeparator = { 'left': '', 'right': '' }
    let g:Lf_ShowDevIcons = 0
    let g:Lf_WindowHeight = 0.30
    let g:Lf_ShowHidden = 1
    let g:Lf_FollowLinks = 1
    let g:Lf_PreviewResult = { 'BufTag': 0 }
    let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]', '*.tmp','*.ttf']
            \}
    let g:Lf_MruWildIgnore = copy(g:Lf_WildIgnore)
    let g:Lf_UseVersionControlTool = 1
    let g:Lf_MruMaxFiles = 500
    " This is set by default
    " nnoremap <leader>f :LeaderfFile<CR>
    " nnoremap <leader>b :LeaderfBuffer<CR>
    nnoremap <leader>/ :Leaderf line<CR>
    nnoremap <leader>: :Leaderf command<CR>
    nnoremap <leader>T :Leaderf tag<CR>
    nnoremap <leader>[ :Leaderf function<CR>
    nnoremap <leader>h :Leaderf help<CR>
    nnoremap <leader>m :Leaderf mru<CR>
    nnoremap <leader>g :Leaderf rg<CR>
    nnoremap <leader>c :LeaderfColorscheme<CR>
    nnoremap <leader>; :Leaderf cmdHistory<CR>
    silent! packadd LeaderF

```

### Describe your question, feature request, or bug.
When you tune statusline colors of leaderf you expect that `Lf_hl_stlBlank` would cover blank part of statusline:

For example I want for all my colorschemes I use set following leaderf colors:

```vim

let g:Lf_StlSeparator = { 'left': '', 'right': '' }

""" Customize colors {{{1
func! s:my_colorschemes_setup() abort
    " This exact highlight group for leaderf can only be overwritten with linking
    " another group which is not what I would expect from 
    " :highlight def Lf_hl_cursorline
    " definition
    hi DumbNONE guifg=NONE
    hi link Lf_hl_cursorline DumbNONE

    " Leaderf "chrome"
    hi link Lf_hl_stlName StatuslineNC
    hi link Lf_hl_stlMode StatuslineNC
    hi link Lf_hl_stlCategory StatuslineNC
    hi link Lf_hl_stlSeparator0 StatuslineNC
    hi link Lf_hl_stlSeparator1 StatuslineNC
    hi link Lf_hl_stlSeparator2 StatuslineNC
    hi link Lf_hl_stlSeparator3 StatuslineNC
    hi link Lf_hl_stlSeparator4 StatuslineNC
    hi link Lf_hl_stlSeparator5 StatuslineNC
    hi link Lf_hl_stlLineInfo StatuslineNC
    hi link Lf_hl_stlNameOnlyMode StatuslineNC
    hi link Lf_hl_stlRegexMode StatuslineNC
    hi link Lf_hl_stlFullPathMode StatuslineNC
    hi link Lf_hl_stlFuzzyMode StatuslineNC
    hi link Lf_hl_stlCwd Statusline
    hi link Lf_hl_stlBlank Statusline
    hi link Lf_hl_stlTotal StatuslineNC
endfunc


augroup colorscheme_change | au!
    au ColorScheme * call s:my_colorschemes_setup()
augroup END

```

![image](https://user-images.githubusercontent.com/234774/79195607-383c5300-7e37-11ea-81b8-9b1cd9b9be84.png)

For some colorshemes it works (for example `desert` and `darkblue`) but not for all of them.

### Steps to reproduce
include snippet from top of the issue, run vim and `:colo default` or `:colo elflord`

### Actual behaviour

![image](https://user-images.githubusercontent.com/234774/79196036-fcee5400-7e37-11ea-9168-89c826b7e883.png)

### Expected behaviour

![image](https://user-images.githubusercontent.com/234774/79196081-1099ba80-7e38-11ea-9a37-3bfc7806f6be.png)

What I have found in the source is that you can change:

https://github.com/Yggdroot/LeaderF/blob/2af9968a0c8e45a61f4a4f2b8f82c76930ba2eb1/autoload/leaderf/python/leaderf/instance.py#L272

to 

```
        stl += "%#Lf_hl_stlBlank#%="
```

Note `%=` the end instead of beginning.

And it works as expected. Basically, as far as I understand you have to apply color group first and then expand it with `%=`.

**Comment by Yggdroot** [comment]
Thanks, fixed.

**Comment by habamax** [comment]
Thx!
