### ISSUE TITLE
搜索界面的第一列出现问号

### ISSUE THREAD

**Issue by egolearner** [Yggdroot/LeaderF#567]
请问是需要配置字体吗？
已升级到最新版本
![image](https://user-images.githubusercontent.com/45122959/79244901-fdbfce00-7ea9-11ea-8ace-6ebfb8ebb87a.png)

**Comment by Yggdroot** [comment]
对，如果不想要，也可以关掉这个feature。

**Comment by egolearner** [comment]
@Yggdroot 有说明吗？第一次用leaderf，help文档里也没找到

**Comment by Yggdroot** [comment]
`let g:Lf_ShowDevIcons = 0` 是关掉这个feature。怎么安装字体可以看https://github.com/ryanoasis/nerd-fonts 的帮助。

**Comment by egolearner** [comment]
谢谢

**Comment by tommyjiang** [comment]
感谢 @Yggdroot 回复，补充一下，安装后是要设置 terminal 的字体。

**Comment by tamago324** [comment]
@Yggdroot There are a lot of issues about this, so how about pinning it?

**Comment by wenwade** [comment]
install nerdfont
