### ISSUE TITLE
how to disable updating gtags index files automatically

### ISSUE THREAD

**Issue by zzyalbert** [Yggdroot/LeaderF#568]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
I have other tools to manage gtags index, so how can I disable updating gtags index files automatically in leaderF?

**Comment by Yggdroot** [comment]
let g:Lf_GtagsAutoGenerate = 0

**Comment by zzyalbert** [comment]
> let g:Lf_GtagsAutoGenerate = 0

still update gtags index automatically whenever I save file

**Comment by Yggdroot** [comment]
if you want to use Leaderf gtags,  you can't use other tools to manage gtags.
