### ISSUE TITLE
Lf_ShowHidden not work?

### ISSUE THREAD

**Issue by jzdxeb** [Yggdroot/LeaderF#569]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 12 2020 17:46:58)
macOS version
Included patches: 1-539
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cursorshape       +job               +mouse_urxvt       +scrollbind        +transparency
+arabic            +dialog_con_gui    +jumplist          +mouse_xterm       +signs             +user_commands
+autocmd           +diff              +keymap            +multi_byte        +smartindent       +vartabs
+autochdir         +digraphs          +lambda            +multi_lang        -sound             +vertsplit
-autoservername    +dnd               +langmap           -mzscheme          +spell             +virtualedit
+balloon_eval      -ebcdic            +libcall           +netbeans_intg     +startuptime       +visual
+balloon_eval_term +emacs_tags        +linebreak         +num64             +statusline        +visualextra
+browse            +eval              +lispindent        +odbeditor         -sun_workshop      +viminfo
++builtin_terms    +ex_extra          +listcmds          +packages          +syntax            +vreplace
+byte_offset       +extra_search      +localmap          +path_extra        +tag_binary        +wildignore
+channel           -farsi             +lua               +perl              -tag_old_static    +wildmenu
+cindent           +file_in_path      +menu              +persistent_undo   -tag_any_white     +windows
+clientserver      +find_in_path      +mksession         +popupwin          -tcl               +writebackup
+clipboard         +float             +modify_fname      +postscript        +termguicolors     -X11
+cmdline_compl     +folding           +mouse             +printer           +terminal          -xfontset
+cmdline_hist      -footer            +mouseshape        +profile           +terminfo          +xim
+cmdline_info      +fork()            +mouse_dec         -python            +termresponse      -xpm
+comments          +fullscreen        -mouse_gpm         +python3           +textobjects       -xsmp
+conceal           -gettext           -mouse_jsbterm     +quickfix          +textprop          -xterm_clipboard
+cryptv            -hangul_input      +mouse_netterm     +reltime           +timers            -xterm_save
+cscope            +iconv             +mouse_sgr         +rightleft         +title
+cursorbind        +insert_expand     -mouse_sysmouse    +ruby              +toolbar
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

" leaderf
let g:Lf_ShowDevIcons = 0
let g:Lf_ShortcutF = '<C-P>'
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowPosition = 'popup'
let g:Lf_WindowHeight=0.3
let g:Lf_WildIgnore = {
  \ 'dir': ['.svn','.git','.hg','.clangd','deps'],
  \ 'file': ['*.bak','*.o','.py[co]','.git*','.DS_Store']
  \}

### Actual behaviour

![image](https://user-images.githubusercontent.com/19486826/79436022-ef38fa00-8002-11ea-9f1f-2fe733240a13.png)

### Expected behaviour
don't show .gitignore

**Comment by Yggdroot** [comment]
Yes, it does not work if g:Lf_UseVersionControlTool is 1.
