### ISSUE TITLE
Can you add a feature like `LeaderfGrep` ?

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#57]
Instead of vimgrep

**Comment by Yggdroot** [comment]
I think CtrlSF is good enough, I do not know if it is necessary to support this feature.
Could you pls describe what you want in detail?

**Comment by fcying** [comment]
I will try to use `CtrlSF`, thanks~~

**Comment by Yggdroot** [comment]
I'll add this feature in the future in my leisure time.

**Comment by tar-zxvf** [comment]
or can you write a md to express the mechanism of LeaderF ? So someone else can create some prs easily. @Yggdroot

**Comment by Yggdroot** [comment]
Added support for rg, now you can use `:Leaderf rg` to grep code, for more details, please refer to:
`:Leaderf rg -h` and Readme.

**Comment by fcying** [comment]
@Yggdroot  can't work.
```
#rg test
GPATH
1:test

tags
1:test

a.c
1:test

src/a.c
1:test

Out/a.c
1:test

aaa/out/a.c
1:test

Out/a/a.c
1:test
```

in vim  `:Leaderf rg test`, nothing.
![image](https://user-images.githubusercontent.com/106934/49360085-214e0280-f713-11e8-9294-c01a64a703da.png)

**Comment by Yggdroot** [comment]
You should use `Leaderf rg -e test` instead.

**Comment by fcying** [comment]
It can work by use `rg -e`, tks~~
