### ISSUE TITLE
Can it create cooperation with coclist?

### ISSUE THREAD

**Issue by hackingcat** [Yggdroot/LeaderF#573]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.5.0-445-gca02db1f9
- Output of `:echo has("python")`: 
1
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
2.7.17 
[GCC 9.3.0]
- Output of `:py3 print(sys.version)`: 
3.8.2
[GCC 9.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
" Show icons, icons are shown by default
let g:Lf_ShowDevIcons = 1

" don't show the help in normal mode
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 1
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
" popup mode
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewPopupWidth = 15
let g:Lf_PopupPreviewPosition='top'
let g:Lf_PopupPosition = [16,0]
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {
        \ 'File': 1,
        \ 'Buffer': 0,
        \ 'Mru': 1,
        \ 'Tag': 1,
        \ 'BufTag': 1,
        \ 'Function': 1,
        \ 'Line': 0,
        \ 'Colorscheme': 1,
        \ 'Rg': 1,
        \ 'Gtags': 1
        \}

let g:Lf_ShortcutF = "<leader>ff"
let g:Lf_ShortcutB = "<leader>bb"
noremap <leader>fm :Leaderf mru<CR>
noremap <leader>bt :Leaderf bufTag<CR>
noremap <leader>ls :Leaderf line<CR>
noremap <leader>fu :Leaderf function<CR>
noremap <leader>fl :Leaderf self<CR>
noremap <leader>w? :Leaderf window<CR>
noremap <leader>ct :Leaderf tag<CR>

noremap <leader>rc :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
noremap <leader>rg :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
" search visually selected text literally
xnoremap <leader>rg :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
noremap <leader>rr :<C-U>Leaderf! rg --recall<CR>

" gtags
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagslabel = 'native-pygments'
noremap <leader>gt :Leaderf gtags<CR>

" remap
let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}

```
### Describe your question, feature request, or bug.
LeaderF is awesome. Thanks to you for your persistent efforts. Is it possible to add support for coc.nvim just like [coc-fzf](https://github.com/antoinemadec/coc-fzf) or [coc-clap](https://github.com/vn-ki/coc-clap)?

**Comment by Yggdroot** [comment]
I'm not familiar with coc, I don't know how to support it.
