### ISSUE TITLE
请教如何在设置能够不关闭popup的窗口?

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#574]
比如说我search某个字符串后生成一个列表,在popup窗口中
然后我想一个一个的修改这些字符串
我在popup中选择回车
包含这条搜索结果的文件被打开,但是popup窗口被关掉

有没有办法打开文件,但是popup窗口不被关掉?

**Comment by Yggdroot** [comment]
如果有这种需求，建议不使用popup，如果是neovim，使用也可以。
从你的描述，使用的是Leaderf rg（希望我猜对了），可以在normal模式下导入到quickfix或locallist里，用Q或L。

**Comment by irreallich** [comment]
非常感谢

**Comment by gVimer** [comment]
你加参数 —stayOpen —bottom

**Comment by Yggdroot** [comment]
> 非常感谢
> 我 :help locallist后没有反应
> 可否请教下
> 什么是locallist,这个如何使用,是vim的概念还是leaderf的概念?

:h location-list
是vim的概念。
