### ISSUE TITLE
[Question] How to make  LeaderF window automatically focused and be in input mode after switching tabpage back?

### ISSUE THREAD

**Issue by iiifr** [Yggdroot/LeaderF#576]
### Describe your question, feature request, or bug.
When I call `LeaderF` with option `--stayOpen`, after I press `<C-T>` to open a file in a new tabpage then come back to original tabpage, LeaderF window will be in normal mode and become a inactive window. How to make LeaderF window be the active window with input mode after I switch back to original tabpage?

**Comment by Yggdroot** [comment]
There is no way, because LeaderF will be switch to normal mode after you press C-T.

**Comment by iiifr** [comment]
> There is no way, because LeaderF will be switch to normal mode after you press C-T.

OK, thank you.
