### ISSUE TITLE
Issues with background colors of `Lf_hl_cursorline` and `Lf_hl_match`

### ISSUE THREAD

**Issue by xulongwu4** [Yggdroot/LeaderF#577]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 17 2020 13:03:59)
Included patches: 1-587
Modified by Solus
Compiled by Solus
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           -netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-solus-linux-gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -Wformat -Wformat-security -fstack-protector-strong --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: x86_64-solus-linux-gcc   -L. -Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=0x1000 -Wl,-Bsymbolic-functions -Wl,--sort-common -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--copy-dt-needed-entries -Wl,-O1 -Wl,-z,relro -Wl,-z,now -Wl,-z,max-page-size=0x1000 -Wl,-Bsymbolic-functions -Wl,--sort-common -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses    -lgpm -ldl  -L/usr/lib -llua     -lruby -lm     
```
 
- Output of `:echo has("python")`: 
```
1
```
- Output of `:echo has("python3")`: 
```
1
```

- Configurations related to LeaderF in vimrc: 
```
  " popup mode
  let g:Lf_WindowPosition = 'popup'
  let g:Lf_PreviewInPopup = 1 
  let g:Lf_ShowDevIcons = 0 
  let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "Source Code Pro" }
  let g:Lf_PreviewResult = {'File': 1, 'Buffer': 1}
  
  let g:Lf_CommandMap = {'<C-]>': ['<C-v>']}
  
  let g:Lf_WorkingDirectoryMode = 'a' 
  nnoremap <silent> <leader>l :<C-u>LeaderfLine<CR>
  nnoremap <silent> <leader><leader>l :<C-u>LeaderfLineAll<CR>
  nnoremap <silent> <leader>u :<C-u>LeaderfFunction<CR>
  nnoremap <silent> <leader><leader>u :<C-u>LeaderfFunctionAll<CR>
  nnoremap <silent> <leader>h :<C-u>LeaderfHistoryCmd<CR>
  nnoremap <silent> <leader>s :<C-u>LeaderfHistorySearch<CR>
```

### Describe your question, feature request, or bug.
If I set `Lf_hl_match`'s background to `NONE` and `Lf_hl_cursorline`'s background color to, say, `Green`, I would expect that all characters in the current cursor line (including matches and non-matches) should have the same backgournd color--Green. In reality, the non-matching characters have a green background. However, the matching characters have some background that I am not sure where they are from.

### Steps to reproduce
Add the following lines to `.vimrc`.
```
let g:Lf_PopupPalette = {
\    'dark': {
\        'Lf_hl_match': {
\               'gui': 'bold',
\               'guifg': 'Yellow',
\               'guibg': 'NONE',
\               'cterm': 'bold',
\               'ctermfg': '3',
\               'ctermbg': 'NONE'
\       },
\       'Lf_hl_cursorline': {
\               'gui': 'NONE',
\               'guifg': 'White',
\               'guibg': 'Red',
\               'cterm': 'NONE',
\               'ctermfg': '7',
\               'ctermbg': '1'
\       }
\    }
\}

```

### Actual behaviour
Matching characters and non-matching characters in the cursor line have different background colors.
![Screenshot from 2020-04-27 22:29:31](https://user-images.githubusercontent.com/16892446/80440432-c6ecad80-88d6-11ea-8f60-2b6e2647a3af.png)
As can be seen above, the matching characters `DSI` have different backgrounds than other characters in the red cursor line. This should not have happened since I set the background color of `Lf_hl_match` to `NONE`.

I should also point out that if I set `Lf_hl_cursorline`'s background color to `NONE`, then all characters in the cursor line (matching or non-matching) have the same background color.

### Expected behaviour
If `Lf_hl_match`'s background color is set to `NONE`, then the matching characters in the cursor line should have red background in the above screenshot.

**Comment by Yggdroot** [comment]
I don't know how to fix it. They both use `matchadd` to highlight, can you achieve your expected behavior?
For example, there is text like `aaabbbaaa` in vim,
```vim
hi aaa guifg=White guibg=Red
hi bbb guifg=Yellow guibg=NONE
call matchadd('aaa', 'aaa.*aaa')
call matchadd('bbb', 'bbb')
```

**Comment by xulongwu4** [comment]
Yeah the result seems not as expected:
![Screenshot from 2020-04-28 09:54:30](https://user-images.githubusercontent.com/16892446/80495781-5d9c8700-8936-11ea-8368-4b7f7d14ed64.png)

**Comment by xulongwu4** [comment]
Do you think it would work if we do the following way?

1. Define internal highlight groups (invisible to users) for matching characters in the cursor line, one for each of `Lf_hl_match`, `Lf_hl_match0`, `Lf_hl_match1`, ... The colors of these groups mostly derive from the corresponding `Lf_hl_matchX`, except for the background color.

2. When deciding the background colors (let's call it `internal_bg`) for these internal highlight groups, first check if the background color of `Lf_hl_macthX` (let's call it `match_bg`. If `match_bg` is something other than `NONE`, then `internal_bg` should match `match_bg`.

3. If `internal_bg` is `NONE`, then we check the background color of `Lf_hl_cursorline` (we call it `cursorline_bg`). If `cursorline_bg` is something other than `NONE`, then `internal_bg` is set to `cursorline_bg`.

4. If `cursorline_bg` is also NONE, we set `internal_bg` to the background color of `Lf_hl_popup_window`, no matter it is `NONE` or not.

I don't know whether it is useful, but I got some of these ideas from here: https://stackoverflow.com/questions/17728343/word-under-cursor-highlighting-and-multi-highlighting-in-vim

If `Lf_hl_match`'s background is NONE, then matching characters in the cursorline should have the same background as `Lf_hl_cursorline`. If `Lf_hl_cursorline`'s background color is also `NONE`, then `

**Comment by Yggdroot** [comment]
> Do you think it would work if we do the following way?
> 
> 1. Define internal highlight groups (invisible to users) for matching characters in the cursor line, one for each of `Lf_hl_match`, `Lf_hl_match0`, `Lf_hl_match1`, ... The colors of these groups mostly derive from the corresponding `Lf_hl_matchX`, except for the background color.
> 2. When deciding the background colors (let's call it `internal_bg`) for these internal highlight groups, first check if the background color of `Lf_hl_macthX` (let's call it `match_bg`. If `match_bg` is something other than `NONE`, then `internal_bg` should match `match_bg`.
> 3. If `internal_bg` is `NONE`, then we check the background color of `Lf_hl_cursorline` (we call it `cursorline_bg`). If `cursorline_bg` is something other than `NONE`, then `internal_bg` is set to `cursorline_bg`.
> 4. If `cursorline_bg` is also NONE, we set `internal_bg` to the background color of `Lf_hl_popup_window`, no matter it is `NONE` or not.
> 5. Use these internal highlight groups to render the matching characters in a cursor line.
> 

the matching characters are not highlighted line by line, they are highlighted only by, for example, 
`call matchadd('bbb', 'bbb')`.

This method is too tricky.  In my opinion, if you want to have color background of cursorline, you can define the color of `CursorLine`.

**Comment by xulongwu4** [comment]
>  In my opinion, if you want to have color background of cursorline, you can define the color of `CursorLine`.
Setting `CursorLine` would also affect the look of texts in the vim buffer is the `cursorline` option is set, but I only want to change the look of the popup window. Originally I thought that setting `Lf_hl_cursorline` will do the job for me, but it seems that `Lf_hl_cursorline` controls the look of text in the cursorline, and `CursorLine` controls the background of the whole cursor line, including the part that does not have text.

Is it possible to have another highlight group to control the background of the cursor line in the popup window, rather than let `CursorLine` in control of that?

**Comment by Yggdroot** [comment]
`Lf_hl_cursorline`.

**Comment by xulongwu4** [comment]
Yeah I tried that and that only affects the texts in the cursorline, not the whole cursorline. I mean the overall background of the cursorline is set by `CursorLine`. Is it possible to create a highlight group in `LeaderF` to control the line-wise background of the cursor line?

**Comment by Yggdroot** [comment]
I'm afraid there is no way.

**Comment by xulongwu4** [comment]
I see. Thanks for your quick reply and this awesome plugin.
