### ISSUE TITLE
搜索列表项前出现乱码

### ISSUE THREAD

**Issue by wlon** [Yggdroot/LeaderF#578]
- vim or neovim? 
    - [x] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2
NVIM v0.4.3
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
搜索列表项前出现乱码
### Expected behaviour

![image](https://user-images.githubusercontent.com/83916/80513064-156e7a80-89b1-11ea-8f74-b42deb4b74a6.png)
![image](https://user-images.githubusercontent.com/83916/80513522-c1b06100-89b1-11ea-80a7-579c8353c518.png)

**Comment by tamago324** [comment]
See #567

**Comment by wlon** [comment]
@tamago324 
Thank you very much, I resolved the issue after install the font.

**Comment by tamago324** [comment]
I'm glad I was able to help ☺
