### ISSUE TITLE
LeaderF don't work anymore (on Mac at least)

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#58]
I just updated the plugin and now vim doesn't start and completely mess up the shell (I can't even use the mouse to select the output.

Here are the steps I've done to determine that LeaderF was the source of the problem. At that point, LeaderF is already at it latest revision, vim crash as soon as I run it:
- With nano, I've commented out all the plugins
- I started vim (it works this time, without any plugin), I uncommented LeaderF, closed vim
- I started vim again: crash.

Here's the screenshot of the shell:
<img width="431" alt="capture d ecran 2017-08-09 a 11 17 16" src="https://user-images.githubusercontent.com/6382548/29129311-5c76a1a4-7cf4-11e7-9bb9-6da435874173.png">

**Comment by MightyCreak** [comment]
I actually went quite far back in the LeaderF log (dec 2016), but vim still crashed.
It seems to be a problem with my machine... But if someone on Mac has the same problem, please post something here. Otherwise we'll be able to close this issue (but I'll have to use CtrlP again... 😢 )

**Comment by Yggdroot** [comment]
Have it ever worked before on your current vim on this machine?
It works well on my Mac os X 10.11,  vim 8.0.771.
I think any plugin that written in python can not work on you vim, please reinstall the vim.

**Comment by MightyCreak** [comment]
Yep, I was using it for the last 5 months or so. I'll try to update python, vim, etc...

**Comment by MightyCreak** [comment]
Ok, I updated everything (including both mac and python) and now it works!
Thanks!

Closing the issue.
