### ISSUE TITLE
'py' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by petermeng** [Yggdroot/LeaderF#580]
On win7 system, when I run install.bat, it will show "'py' is not recognized as an internal or external command". Which tool should be installed first? Thanks!

**Comment by Yggdroot** [comment]
Have you installed python On Win7?

**Comment by petermeng** [comment]
I have installed Microsoft Visual C++ Compiler for Python, Python 2.7.18 and Visual Studio C++ 2015 Build Tools.

**Comment by Yggdroot** [comment]
add py into the environment variable PATH or reinstall Python 2.7.18 carefully to add to **PATH**.

**Comment by petermeng** [comment]
Thank you for your support, I also install python 3.7 and it works!
