### ISSUE TITLE
MacVim 使用 LeaderF 打开最近使用的文件乱码了

### ISSUE THREAD

**Issue by mzlogin** [Yggdroot/LeaderF#588]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 30 2019 11:57:56)
macOS version
Included patches: 1-2234
```
- Output of `:echo has("python")`: 
```
1
```
- Output of `:echo has("python3")`: 
```
0
```
- Output of `:echo &pythondll`(only vim, not neovim): 
```
/usr/local/Frameworks/Python.framework/Versions/2.7/Python
```
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
```
/usr/local/Frameworks/Python.framework/Versions/3.7/Python
```
- Output of `:py print(sys.version)`: 
```
2.7.17 (default, Oct 24 2019, 12:57:38)
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.8)]
```
- Output of `:py3 print(sys.version)`: 
```
E837: This Vim cannot execute :py3 after using :python
E263: Sorry, this command is disabled, the Python library could not be loaded. 
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```viml
" LeaderF
nnoremap <silent> <leader>m :LeaderfMru<CR>
let g:Lf_DefaultMode = 'FullPath'
let g:Lf_IndexTimeLimit = 1200
let g:Lf_MruWildIgnore = {
            \ 'dir': ['.git'],
            \ 'file': []
            \ }
```

### Describe your question, feature request, or bug.

今天更新到最新版本后，打开最近使用的文件，文件列表和文件内容都乱码了。

### Steps to reproduce

![image](https://user-images.githubusercontent.com/1646590/80932275-66d39b00-8df1-11ea-8cb8-e2882a0dcf04.png)

![image](https://user-images.githubusercontent.com/1646590/80932281-6e933f80-8df1-11ea-91c9-90ee2670abb0.png)

### Actual behaviour

文件列表图标乱码，文件内容乱码。

### Expected behaviour

正常显示。

### 补充信息

我定位到是这一次提交以后就出现这个问题了：

![image](https://user-images.githubusercontent.com/1646590/80932343-b1edae00-8df1-11ea-8eac-bbc248083190.png)

我在配置文件里将 devicons 禁用后功能正常。

```viml
let g:Lf_ShowDevIcons = 0
```

**Comment by Yggdroot** [comment]
第一列又乱码是需要装字体。
至于文件内容有乱码我觉得可能是vim的bug，以前也有人报了同样的问题（mac上）。

确定是 `19949b8 Custom devicons (#541)` 而不是`b4667ac Support vim-devicons (#532)` 才出现的这个问题？
```
19949b8 Custom devicons (#541)
da3111c Fix bufname min length (#540)
c8630d2 autocmd ColorScheme call highlightDevIcons() (#539)
e039584 remove the dependency on vim-devicons
b4667ac Support vim-devicons (#532)
```

**Comment by mzlogin** [comment]
我这边试过是 `19949b8 Custom devicons (#541)`，在这次提交之前正常，含这次提交之后就乱码了。

**Comment by Yggdroot** [comment]
你说的乱码是指第一列乱码还是文件内容乱码，如果是第一列又乱码，理论上从`e039584 remove the dependency on vim-devicons`开始就应该有。

**Comment by mzlogin** [comment]
> 你说的乱码是指第一列乱码还是文件内容乱码，如果是第一列又乱码，理论上从`e039584 remove the dependency on vim-devicons`开始就应该有。

在我这边看这两个现象是一起的，一乱都乱。因为我只是把 devicons 禁用了然后两个都好了，所以也不知道会不会有其中一个好另一个不乱的情况。

**Comment by Yggdroot** [comment]
e039584 remove the dependency on vim-devicons 这个没有问题？第一列也没有乱码？

**Comment by mzlogin** [comment]
> [e039584](https://github.com/Yggdroot/LeaderF/commit/e039584b52ec46fa7194eb8520efd7a76a34bb70) remove the dependency on vim-devicons 这个没有问题？第一列也没有乱码？

好吧……是你说的这次提交为分界线。我光标都是停在这次提交上的，截图的时候框错了。

包含你说的这次提交时就第一列和文本内容都乱。不包含就是好的，第一列不显示图标。

**Comment by Yggdroot** [comment]
那就说的通了。内容乱了应该是vim的bug。

**Comment by codekeeperjava** [comment]
我使用这个配置后，出现了乱码，取消后就可以了。这段配置我没有了解具体的含义，因为我从网上拷贝的。

```
" Avoid garbled characters in Chinese language windows OS
let $LANG='en'
set langmenu=en
```

**Comment by Yggdroot** [comment]
> 我使用这个配置后，出现了乱码，取消后就可以了。这段配置我没有了解具体的含义，因为我从网上拷贝的。
> 
> ```
> " Avoid garbled characters in Chinese language windows OS
> let $LANG='en'
> set langmenu=en
> ```

你这个应该不是同一个问题。
