### ISSUE TITLE
sometimes  g:Lf_CommandMap did not take effect

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#59]
I'm useing `esc` to quit leaderf, `<c-i>` to switch normal mode, sometimes  `<c-i>` did not take effect.
If I use `esc` to switch mode work right always. 

```
let g:Lf_CommandMap = {'<C-C>': ['<Esc>'],'<Esc>':['<C-I>']}
let g:Lf_ShortcutF = 'ff'
```

os: ubuntu16.04
commit 3e7dc2621d747bcf831610ff658f853567d12ee9

test way:
```
open vim
ff
<c-i>
:qa
```

**Comment by Yggdroot** [comment]
Fixed, please have a try.

**Comment by fcying** [comment]
It work right now, thanks~~
