### ISSUE TITLE
[Feature] Recursive searching in RG

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#590]
What I mean by this is that I can use some keyword to search all files in certain dir (:LeaderfRgInterfactive IIRC). Then, I want to use another keyword to search just on these files. Is this something that can be implemented? 

Thanks

**Comment by Yggdroot** [comment]
I don't know if I understand correctly, I think LeaderF already can do it.
`Leaderf -e IIRC`, then search another keyword as you type in the fuzzy way.

**Comment by eyalk5** [comment]
The thing is that it assumes the two keywords are on the same line. 
I want to look for lines with a certain keyword in all files that contains another keyword(up to a small miss).

**Comment by Yggdroot** [comment]
I think what I said is exactly what you want.

**Comment by eyalk5** [comment]
well, i did a test .vimrc contains `neovim` and contains `showtabline` in a different place in the file. I tried to do  `Leaderf rg -e  neovim` and then lookfor `showtabline`. Not found.

**Comment by Yggdroot** [comment]
make sure the two words are in the same line.

**Comment by Yggdroot** [comment]
I don't plan to implement this feature. You can easily achieve this goal by a small script.
