### ISSUE TITLE
LeaderfMru UnicodeDecodeError

### ISSUE THREAD

**Issue by DerekTan** [Yggdroot/LeaderF#592]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.1 (2018 May 18, compiled Mar 31 2019 22:02:39)
MS-Windows 64-bit console version
包含补丁: 1-1099
编译者 appveyor@APPVYR-WIN
巨型版本 无图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +eval               +multi_byte_ime/dyn +termguicolors
+arabic             +ex_extra           +multi_lang         +terminal
+autocmd            +extra_search       +mzscheme/dyn       -termresponse
+autochdir          -farsi              -netbeans_intg      +textobjects
+autoservername     +file_in_path       +num64              +textprop
-balloon_eval       +find_in_path       +packages           -tgetent
+balloon_eval_term  +float              +path_extra         +timers
-browse             +folding            +perl/dyn           +title
++builtin_terms     -footer             +persistent_undo    -toolbar
+byte_offset        +gettext/dyn        -postscript         +user_commands
+channel            -hangul_input       +printer            +vartabs
+cindent            +iconv/dyn          +profile            +vertsplit
+clientserver       +insert_expand      +python/dyn         +virtualedit
+clipboard          +job                +python3/dyn        +visual
+cmdline_compl      +jumplist           +quickfix           +visualextra
+cmdline_hist       +keymap             +reltime            +viminfo
+cmdline_info       +lambda             +rightleft          +vreplace
+comments           +langmap            +ruby/dyn           +vtp
+conceal            +libcall            +scrollbind         +wildignore
+cryptv             +linebreak          +signs              +wildmenu
+cscope             +lispindent         +smartindent        +windows
+cursorbind         +listcmds           +startuptime        +writebackup
+cursorshape        +localmap           +statusline         -xfontset
+dialog_con         +lua/dyn            -sun_workshop       -xim
+diff               +menu               +syntax             -xpm_w32
+digraphs           +mksession          +tag_binary         -xterm_save
-dnd                +modify_fname       -tag_old_static
-ebcdic             +mouse              -tag_any_white
+emacs_tags         -mouseshape         +tcl/dyn
     系统 vimrc 文件: "$VIM\vimrc"
     用户 vimrc 文件: "$HOME\_vimrc"
 第二用户 vimrc 文件: "$HOME\vimfiles\vimrc"
 第三用户 vimrc 文件: "$VIM\_vimrc"
      用户 exrc 文件: "$HOME\_exrc"
  第二用户 exrc 文件: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
编译方式: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT -DFEAT_MBYTE_IME -DDYNAMIC_IME -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_MZSCHEME -I "C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=24 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby240.dll\" -DFEAT_HUGE /Fd.\ObjCULYHTRZAMD64/ /Zi
链接方式: link  /nologo /subsystem:console,5.02 /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64   libcmt.lib  user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python37.lib   "C:\Tcl\lib\tclstub86.lib" WSock32.lib /PDB:vim.pdb -debug

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python23.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python37.dll
- Output of `:py print(sys.version)`: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
- Output of `:py3 print(sys.version)`: 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]

- Output of `:echo g:Lf_Debug_Cmd`: git ls-files  "." && git ls-files --others --exclude-standard  "."

- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
" for LeaderF
"let g:Lf_ShortcutF = '<c-p>'
"let g:Lf_ShortcutB = '<m-n>'
noremap <Leader>M :LeaderfMru<cr>
noremap <Leader>F :LeaderfFunction!<cr>
"noremap <m-n> :LeaderfBuffer<cr>
noremap <Leader>t :LeaderfTag<cr>
"let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
"
let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
```

### Describe your question, feature request, or bug.
:LeaderfMru报错：
```
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
E28: 没有这个高亮群组名: Lf_hl_match
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
E28: 没有这个高亮群组名: Lf_hl_match_refine
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\tan-69\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 797, in start
    the_args.start(arguments, *args, **kwargs)
  File "C:\Users\tan-69\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 729, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "C:\Users\tan-69\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2005, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "C:\Users\tan-69\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\mruExpl.py", line 31, in getContent
    mru.saveToCache(lfEval("readfile(lfMru#CacheFileName())"))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 14: invalid start byte
```

### Steps to reproduce
任意打开一个文件，执行:LeaderfMru
### Actual behaviour
出现如上描述的错误
### Expected behaviour
正常显示文件列表

**Comment by Yggdroot** [comment]
现在encoding是什么？可能是因为你中间改变过encoding的值导致的。需要删掉`~/.LfCache/python3/mru` 再重新来吧

**Comment by DerekTan** [comment]
> .LfCache/python3/mru

的确改过encoding。
删除了~/.LfCache/temMru，问题还在

**Comment by DerekTan** [comment]
> 现在encoding是什么？可能是因为你中间改变过encoding的值导致的。需要删掉`~/.LfCache/python3/mru` 再重新来吧

删除了~/.vim下的cache后好了，感谢！
