### ISSUE TITLE
多个大文件 leaderf 各种功能都被卡住

### ISSUE THREAD

**Issue by hellowxwworld** [Yggdroot/LeaderF#594]
多个大文件 leaderf 各种功能都被卡住很久，有十几秒， 文件大概十几兆

**Comment by Yggdroot** [comment]
能说具体一点吗，复现步骤？

**Comment by hellowxwworld** [comment]
neovim  打开十个大文件，每个大概十几兆，打开之后 :leaderd buffer<CR> 之后要等十几秒甚至一分钟以上才会出现 buffer列表 window

**Comment by Yggdroot** [comment]
感觉这个问题跟LeaderF没关系，我也不知道怎么复现，按照你说的没有复现。

**Comment by hellowxwworld** [comment]
应该跟 highlight 有关， 你用 vim-log-highlight 插件，把这些大文件重命名成 .log 文件，这样就会卡住

**Comment by Yggdroot** [comment]
你把其他插件都禁掉，只剩下LeaderF，看看还会卡住吗？如果不会就不说话LeaderF的问题。
