### ISSUE TITLE
Leaderf file --no-ignore 不生效, Leaderf file看不到.ccls文件

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#596]
文档里面没看到这个参数. 
直接运行 Leaderf file 自动提示的时候看到的. 
看着像是用来忽略 `g:Lf_WildIgnore` 参数?
试了下, 没效果. 

另外还有一个. 我的目录下有一个 `.ccls` 文件, Leaderf file 一直无法找到他...g:Lf_WildIgnore里面没加.ccls

vimrc
```
set nocompatible
set encoding=utf-8
set mouse=n

set runtimepath^=~/.vim/plugged/LeaderF
filetype plugin indent on
syntax on
set hidden

filetype plugin indent on
syntax enable

let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_WildIgnore = {
      \ 'dir': ['.root','.svn','.git','.hg','.ccls-cache'],
      \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
      \}

```

**Comment by Yggdroot** [comment]
`echom g:Lf_Debug_Cmd` 是什么？

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/5552fa0671006c5edddeadd0282f9a67156bb29f/doc/leaderf.txt#L510-L513

**Comment by fcying** [comment]
> 
> 
> `echom g:Lf_Debug_Cmd` 是什么？
E121: Undefined variable: g:Lf_Debug_Cmd

不是`g:Lf_ShowHidden`的问题. 同目录下别的隐藏文件可以找到. 
===========================================

问题找到了. `Leaderf file` 不会管`g:Lf_RgConfig` 里rg的配置. 会去读系统全局的rg config, 我在全局的rg config 里面写了.ccls

**Comment by Yggdroot** [comment]
`echom g:Lf_Debug_Cmd` 是在运行Leaderf file后查看的。

> 问题找到了. Leaderf file 不会管g:Lf_RgConfig 里rg的配置. 会去读系统全局的rg config, 我在全局的rg config 里面写了.ccls

Leaderf file 会管g:Lf_RgConfig 里rg的配置，你的g:Lf_RgConfig配置和全局的rg config分别是什么？

`Leaderf file --no-ignore` 不会没效果，它跟`g:Lf_WildIgnore`没关系，它只相当于rg 加了个`--no-ignore`。

**Comment by fcying** [comment]
```  
let g:Lf_RgConfig = [
        \ '--glob=!.ccls-cache',
        \ '--glob=!.ccls',
        \ '--hidden'
        \ ]
```
全局 rg config
```
--no-ignore
--hidden
--color=auto
--no-heading
--no-column
--follow
--glob=!.ccls-cache
--glob=!.ccls
```

测试关闭`g:Lf_WildIgnore`, 删掉全局rg config文件, 只使用`g:Lf_RgConfig`, 还是能搜索到`.ccls`文件, `g:Lf_RgConfig` 没生效

`echom g:Lf_Debug_Cmd`
```
rg --no-messages --files --color never   --hidden
```

测试关闭`g:Lf_WildIgnore`, 使用全局rg config文件, 关闭`g:Lf_RgConfig`, 搜索不到到`.ccls`文件, 全局的rg config能生效

**Comment by Yggdroot** [comment]
哦，是我搞错了，`g:Lf_RgConfig`的配置是给`Leaderf rg` 用的，`Leaderf file`不会读这个配置。

**Comment by Yggdroot** [comment]
所以一切可以说的通了，全局配置会影响rg的行为，所以不管是Leaderf file还是Leadf rg还是其他的，只要使用了rg，都会受其影响。

**Comment by fcying** [comment]
这下明白了. 感谢回复~~
