### ISSUE TITLE
能不能加个选项 g:Lf_GtagsStoreInRootMarkers

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#599]
把gtags几个文件保存在对应项目的 `.git` 或者其他 rootmasrkers 目录里.
全局统一的目录, 不方便管理. 
直接放项目根目录下跑`git clean -dfx` 就被清了.

**Comment by Yggdroot** [comment]
#474  已经有了。

**Comment by fcying** [comment]
`g:Lf_GtagsStoreInProject` 是放在项目根目录下的. 跑`git clean -dfx` 就被清了.
现在是想放到`g:Lf_RootMarkers` 定义的目录里去. 比如 `.git/.LfGtags/*`

**Comment by Yggdroot** [comment]
放.git里不好吧。
全局统一目录为什么不方便管理？

**Comment by fcying** [comment]
项目目录太多了. 现在`.LfCache/gtags`下面几百个目录了...
一些不用的项目, 都是直接 `rm`了. 也没专门去跑一次`Leaderf gtags --remove`.
放项目目录里的话. 可以跟着`rm`一起删了.
我是看到这个插件是写在`.git`里面的, 写里面会有什么问题吗?
`jsfaint/gen_tags.vim`

**Comment by Yggdroot** [comment]
放. git里不是不可以，我觉得他是放置git相关配置的地方，放别的东西进去就太混乱了。
如果你说的不方便只是存在一些项目已经不存在的gtags文件的话，我可以提供一个命令，一次把所有失效的gtags都删掉。

**Comment by fcying** [comment]
能自动处理失效gtags也行, 感谢

**Comment by fcying** [comment]
这两天整理了下目录. 只是删除失效的. 还是有点不够. 
项目移动了位置的, gtags就没了. 
把生成好的gtags 分享给别人用. 去公共目录里找也比较麻烦.

**Comment by Yggdroot** [comment]
重新生成不可以吗

**Comment by fcying** [comment]
只是移动位置的话. 跑下命令 没找到, 重新生成没问题. 
给别人用的话. 没配置gtags.conf 生成出来的不准确.

**Comment by efikarl** [comment]
为什么不提供一个g:Lf_GtagsDataBaseRoot的选项？我从使用文档中没有发现相关配置，现在找不到Gtags的DataBase放在哪里了。这样的话与其它Gtags插件集成很难搞，cscope也不生效，因为他找不到这个database的位置。

**Comment by fcying** [comment]
@efikarl 设成 `g:Lf_GtagsStoreInProject`  就在项目目录下了. 和别的插件配合应该是最方便了.  
设成 g:Lf_GtagsStoreInRootMarkers 是放在项目的 `.git`或者其他 rootmasrkers 目录里.
啥都不设. 默认是在`g:Lf_CacheDirectory`目录下面.

**Comment by efikarl** [comment]
@fcying 有帮助，谢谢
