### ISSUE TITLE
:LeaderfMru 打开之后是空白新文件

### ISSUE THREAD

**Issue by blurm** [Yggdroot/LeaderF#60]
比如，在Leaderf窗口中显示为：
```
book.css                   "mydata/vim/chrome_extentions/imdb/css/"
```
打开之后显示空白新文件，文件路径提示为：
```
"mydata/vim/chrome_extentions/imdb/css/book.css" [New DIRECTORY]
```
`:LeaderMruCwd`也是一样的情况

**Comment by Yggdroot** [comment]
路径和文件名连接之后没错，到底当前目录下有没有`mydata/vim/chrome_extentions/imdb/css/book.css`这个文件呢？

**Comment by Yggdroot** [comment]
This issue is caused by https://github.com/neovim/neovim/issues/3636. Please update the neovim.
