### ISSUE TITLE
--stayOpen时，如何快速关闭窗口（gtags、funcfion...）

### ISSUE THREAD

**Issue by lvyanpo** [Yggdroot/LeaderF#600]
我设置了gtags窗口的--stayOpen选项，之后如果想关闭gtags窗口，
有没有快捷的方法关闭它？无论gtags窗口是不是当前激活的buffer。
必须要激活窗口后按ESC吗？

**Comment by Yggdroot** [comment]
按q可以关掉

**Comment by lvyanpo** [comment]
> 按q可以关掉

谢谢～
如果我当前在编辑代码的窗口里（gtags不是当前的buffer），有没有快捷键可以关闭gtags窗口？

**Comment by Yggdroot** [comment]
现在没这个功能。
