### ISSUE TITLE
accelerate UI manipulation

### ISSUE THREAD

**Issue by hellowxwworld** [Yggdroot/LeaderF#603]
though native c fuzzy search is fast enough, the UI response like buffer open, key manipulation still lag the finger and thoughts, can it be accelerated by rust or cpp implementation

**Comment by Yggdroot** [comment]
why do you think that rust would be faster than c? 
I don't understand what"the UI response like buffer open, key manipulation still lag the finger and thoughts" means, how to reproduce it?
