### ISSUE TITLE
support for complete?

### ISSUE THREAD

**Issue by Freed-Wu** [Yggdroot/LeaderF#606]
Can `:LeaderfCommand` support command complete? Can `:LeaderfFile` support file path complete?
It is an enhancement. thanks!

**Comment by Yggdroot** [comment]
I think LeaderfFile already supports it.

**Comment by Freed-Wu** [comment]
history complete is also a complete... right.
and can it complete command which not be inputed but exists?

**Comment by Freed-Wu** [comment]
https://github.com/youran0715/LeaderF-Cmdpalette can do.
thanks!

**Comment by Freed-Wu** [comment]
perhaps can split many functions from leaderf as leaderf-extension, then give a list of all extensions, user can install their favourite extension and do not install these extension which they seldomly use.

it is just a proposal, thanks!
