### ISSUE TITLE
Leaderf rg在结果中进行跳转后，会产生undo历史？

### ISSUE THREAD

**Issue by lvyanpo** [Yggdroot/LeaderF#608]
**test文件内容：**
aaa
bbb
ccc
aaa
bbb
ccc

**使用Leaderf rg aaa 搜索后，结果如下：**
test:1:aaa
test:4:aaa

**选中一个结果进行跳转后，再按“u”（undo）显示如下message：**
6 changes; before #1  1 second ago

**test文件内容没有变化，但是当“：q”退出时提示需要保存**

**Comment by Yggdroot** [comment]
修复了。

**Comment by lvyanpo** [comment]
验证OK，谢谢~
