### ISSUE TITLE
provide many information about extension?

### ISSUE THREAD

**Issue by Freed-Wu** [Yggdroot/LeaderF#609]
where can user to find more information about extension? such as APIs about extension, a list containing a brief introduction to extensions which exist, etc? as a form of help.txt or wiki?

thanks!

**Comment by Yggdroot** [comment]
Currently, there is no such information.
https://github.com/Yggdroot/LeaderF/issues/144#issuecomment-540008950 is an introduction of how to write extension in VimL.

You can find some extensions from
https://github.com/search?q=LeaderF&type=Repositories&ref=advsearch&l=&l=  .

**Comment by Freed-Wu** [comment]
> [#144 (comment)](https://github.com/Yggdroot/LeaderF/issues/144#issuecomment-540008950) is an introduction of how to write extension in VimL.

Looks good! Let me have a look.

> You can find some extensions from
> https://github.com/search?q=LeaderF&type=Repositories&ref=advsearch&l=&l= .

Can add a wiki about extensions like <https://github.com/kana/vim-textobj-user/wiki>? it will be more convenient than searching in github.

**Comment by Yggdroot** [comment]
> Can add a wiki about extensions like https://github.com/kana/vim-textobj-user/wiki? it will be more convenient than searching in github.

I will.
