### ISSUE TITLE
feature request, 输出结果的展示控制

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Yggdroot/LeaderF#611]
希望可以配置输出结果的展示, 比如不展示文件全路径, 省略展示文件路径等.

**Comment by Yggdroot** [comment]
不明白。

**Comment by FinallyFinancialFreedom** [comment]
比如leaderf rg的时候, 搜出的结果 会展示文件全路径, 会展示文件名,会展示匹配代码, 一条匹配内容非常长, 全路径用处不大, 想隐藏.

**Comment by Yggdroot** [comment]
没法做，需要路径来跳转。

**Comment by gVimer** [comment]
> 比如leaderf rg的时候, 搜出的结果 会展示文件全路径, 会展示文件名,会展示匹配代码, 一条匹配内容非常长, 全路径用处不大, 想隐藏.

可以显示相对路径的吧
