### ISSUE TITLE
gtags使用出错

### ISSUE THREAD

**Issue by krisfans** [Yggdroot/LeaderF#614]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: `0.4.3`
- Output of `:echo has("python3")`: `1`
- Output of `:py3 print(sys.version)`: `3.8.2（tags/v3.8.2:7b3ab59，Feb 25 2020, 22:45:29）[MSC v.1916 32bit (Intel) ]`
- Output of `:echo g:Lf_Debug_Cmd`: `Undefined variable: g Lf_Debug_Cmd`
- Output of `:echo g:Lf_FilesFromCache`: `Undefined variable g:Lf_FilesFromCache`
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vim
call plug#begin('$HOME/.vim/plugged') 
Plug 'Yggdroot/LeaderF', { 'do': '.\install.bat' }
call plug#end()
let g:plugged#enable_at_startup = 1 

"--------------------------------------"
"let $GTAGSLABEL = 'native-pygments'
"let $GTAGSCONF = 'D:/Software/global-6.6.3/gtags.conf'
"let g:Lf_GtagsAutoGenerate = 1
"let g:Lf_Gtagsconf = 'D:/Software/global-6.6.3/gtags.conf'

" should use `Leaderf gtags --update` first
let g:Lf_GtagsAutoGenerate = 0
let g:Lf_Gtagslabel = 'native-pygments'
noremap <space>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <space>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <space>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <space>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <space>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>
"--------------------------------------"

```
### Describe your question, feature request, or bug.
我用的`windows` ,并且安装了`gtag`，版本`global-6.6.3`，然是使用的是你给的配置，上面已经给出，但是我得不到函数列表或者目录，并且有时候会报错，或者显示`No content`。

### Steps to reproduce and Actual behaviour
我打开以一个`cpp`文件，然后输入`LeaderfFunction`,得到这样的结果
![Snipaste_2020-06-04_13-03-30](https://user-images.githubusercontent.com/57793534/83717224-c0372000-a664-11ea-9789-f62ec414b82e.png)

还是同一个文件，输入`Leaderf gtags`,什么列表都没有
![Snipaste_2020-06-04_13-13-18](https://user-images.githubusercontent.com/57793534/83717404-36d41d80-a665-11ea-9d4f-e4255fd03b78.png)

### Expected behaviour
期望的结果是可以得到函数列表或者目录/大纲之类的。

**Comment by Yggdroot** [comment]
第一个图是用的ctags，你装ctags了吗？
第二个图有没有先生成gtags？

**Comment by krisfans** [comment]
第一个图确实没装`ctags`。
第二个图的话我是执行过`Leaderf gtags --update`的，但是没有产生什么实际效果。我该怎么做来生成gtags？

**Comment by Yggdroot** [comment]
let g:Lf_Gtagslabel = 'default' 试一下。

**Comment by krisfans** [comment]
问题解决了。我开始下载的`gtags`是源码没编译，下载编译好的`gtags.exe`加入路径就可以工作了。打扰了

**Comment by krisfans** [comment]
问题解决了。我开始下载的`gtags`是源码没编译，下载编译好的`gtags.exe`加入路径就可以工作了。打扰了
