### ISSUE TITLE
[FR] custom g:Lf_KeyMap or add a shortcut for all open file operations

### ISSUE THREAD

**Issue by roachsinai** [Yggdroot/LeaderF#618]
### Describe your feature request

当前可开候选项有四种操作：

```
<2-LeftMouse>
<CR>	open the file under cursor or selected(when multiple files are selected)
<C-X>	open in horizontal split window
<C-]>	open in vertical split window
<C-T>	open in new tabpage
```

希望可以设置一个快捷键比如`<c-->`，然后触发之后是让输入`e, h, v, t, dr`这些，来选择是`edit, split, vsplit, newtabe, drop`. 类似`confirm`函数
![image](https://user-images.githubusercontent.com/9500049/83852166-fa2c2300-a745-11ea-8fcb-a2fde4a717c8.png)

或者可以定制一下快捷键。

**Comment by roachsinai** [comment]
想提交个PR,但是遇到个问题：

`~/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py`:

```
elif equal(cmd, '<C-\>'):
    actions = ['', 'h', 'v', 't', 'dr']
    a_count = len(actions)
    selection = int( vim.eval(
        'confirm("Action?", "&Edit\n&Split\n&Vsplit\n&Tabnew\n&Drop")' ) ) - 1
    if selection < 0 or selection >= a_count:
        return
    action = actions[selection]
    if self.accept(action) is None:
        break
```

上面的情况在执行`confirm`的过程如果按下`ESC`就是没有做选择，这让`return`，`Leaderf`就得不到焦点了，就一直悬浮在那里也关闭不了。这个是如何处理，是添加个默认的`action`比如`drop`？

**Comment by Yggdroot** [comment]
你这段代码准备放哪里的，我放input（）函数里面怎么什么反应都没有？

**Comment by roachsinai** [comment]
https://github.com/roachsinai/LeaderF/commit/5caffe20729f34153f06bfb77240a3cc13383518

上面这个是在我fork上面的commit链接（目的就是减少需要记忆的快捷键的个数）。

之后运行`Leaderf file` 在触发`<c-\>`之后的按下ESC就出现了Leaderf不消失，也没有focus的问题。

**Comment by roachsinai** [comment]
emmm，貌似把`return`改成`self.input()`就可以了。

**Comment by roachsinai** [comment]
感觉这个功能能合入么？能合入的话快捷键使用`<c-\>`是否合适。
