### ISSUE TITLE
Leaderf rg freezes the whole UI

### ISSUE THREAD

**Issue by jm33-m0** [Yggdroot/LeaderF#623]
My vim environment can be found in #616 (macvim 8.2, run in iterm2)

`rg` runs fine when executed directly, giving result without noticeable delay

<img width="633" alt="image" src="https://user-images.githubusercontent.com/10167884/83933380-74a68280-a7da-11ea-8d08-1995fcce99e2.png">

Steps to reproduce:

1. Open a file under a git project
2. Run `Leaderf rg` to search text
3. Type something to search

vim becomes unresponsive and its CPU usage rises to 100%

**Comment by jm33-m0** [comment]
The project I tested: https://github.com/jm33-m0/emp3r0r

**Comment by Yggdroot** [comment]
maybe it's the same as #318 .

**Comment by jm33-m0** [comment]
Thanks, adding

```
 let g:Lf_RgConfig = [
    \ "--max-columns=150",
    \ "--glob=!node_modules/*",
    \ "--glob=!dist/*",]
```

solves this issue
