### ISSUE TITLE
Leaderf --recall fail

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#625]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
neovim 0.5.0-508
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.6.8
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
![image](https://user-images.githubusercontent.com/8309631/83935037-28fad580-a7e8-11ea-8269-1bf3e709df0f.png)

### Steps to reproduce
1. use Leaderf rg search a word.
2. quite the window.
3. use Leaderf --recall, than errors appear like above.
4. Leaderf --next/--previous has same problem.

**Comment by Yggdroot** [comment]
I can't reproduce it. Can you provide the project and the keyword you search please?

**Comment by xaljer** [comment]
I also can't reproduce this on my another envirment (nvim 0.5.0-547, latest Leaderf). I will upgrade the Neovim and Leaderf version and try it again.
Can you get something useful from the error log? You think it has something to do with specific project, keyword, or command line parameters?

**Comment by Yggdroot** [comment]
if some file name has `:` in it, and the file is deleted after rg searches, there will be such a error.

**Comment by xaljer** [comment]
It happens on i use root marker to spec rg to search in a sub path of pwd. when searching in pwd, it's ok.

**Comment by xaljer** [comment]
#604

**Comment by xaljer** [comment]
@Yggdroot , hi, would you like to fix this issue? This may be caused by my usage in #604 ? Or a indepentent root marker for rg can be provided? if it's not easy to change to my expected behaviour?

**Comment by Yggdroot** [comment]
I  don't  know the exact steps to reproduce this issue.

**Comment by xaljer** [comment]
reproduce steps on my env:
1. set root marker to `.root` and touch a .root file in a sub-path of `pwd`;
2. using `Leaderf rg` to search a word (in the sub-path which contains .root);
3. using `Leaderf --recall` or `Leaderf --next`, error appears.

**Comment by Yggdroot** [comment]
Maybe it's related to some configuration, can you paste some configuration about LeaderF please?

**Comment by Yggdroot** [comment]
> reproduce steps on my env:
> 
> 1. set root marker to `.root` and touch a .root file in a sub-path of `pwd`;

So it is `let g:Lf_RootMarkers = [ '.root' ]`?
> 2. using `Leaderf rg` to search a word (in the sub-path which contains .root);

How do you use it? what is the current `pwd`?

**Comment by xaljer** [comment]
@Yggdroot , sorry, let me state more clearly:
```
- working-dir (where vim opened from)
 |- .repo
 |- sub-dir-1
 |- sub-dir-2
 |- sub-dir-3
   |- .root
   |- some-files
```
1. `let g:Lf_RootMarkers = ['.repo']` in vimrc;
2. open vim in working-dir, so `pwd` == working-dir;
3. run `:let g:Lf_RootMarkers = ['.root']`
4. run `:Leaderf rg --wd-mode Ac -w "some_word"` searching in sub-dir-3;
5. quite the Leaderf window;
4. run `:Leaderf --recall/--next/--previous`, then it happens.

**Comment by xaljer** [comment]
```
let g:Lf_RootMarkers = ['.repo']
let g:Lf_WorkingDirectoryMode = 'c'

nnoremap <Leader>fsg :<C-U><C-R>=printf("let g:Lf_RootMarkers = ['.git']")<CR><CR>
nnoremap <Leader>fsr :<C-U><C-R>=printf("let g:Lf_RootMarkers = ['.repo']")<CR><CR>
nnoremap <Leader>fsc :<C-U><C-R>=printf("let g:Lf_RootMarkers = ['.root']")<CR><CR>

nnoremap <Leader>fr :<C-U>Leaderf --recall<CR>
nnoremap <M-o>      :<C-U>Leaderf --next<CR>
nnoremap <M-i>      :<C-U>Leaderf --previous<CR>
nnoremap <Leader>fw :match Cursor '<C-R><C-W>'<CR> :<C-U><C-R>
    \=printf("Leaderf! rg --match-path --wd-mode Ac -e %s -w", expand("<cword>"))<CR>
```

**Comment by Yggdroot** [comment]
> 4. run `:Leaderf rg --wd-mode Ac -w "some_word"` searching in sub-dir-3;

What is the current buffer? 
What do you mean by `searching in sub-dir-3`? 
 `:Leaderf rg --wd-mode Ac -w "some_word" sub-dir-3 ` ?

**Comment by Yggdroot** [comment]
I reproduce this issue with `Leaderf --next`, but can not reproduce it with `Leaderf --recall`.

**Comment by Yggdroot** [comment]
OK, `Leaderf --recall` then `enter`, the issue is reproduced.

**Comment by xaljer** [comment]
@Yggdroot , thanks, it should have nothing to do with current buffer.
