### ISSUE TITLE
关于Leaderf的若干问题和建议

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#627]
![Snipaste_2020-06-06_18-40-20](https://user-images.githubusercontent.com/6241431/83942388-8e20ec00-a825-11ea-92ab-0a31dee10ae1.png)
就是文件总数 当前行数信息显示到下面的状态栏更好 （个人建议 ）

**Comment by gVimer** [comment]
Windows+gVim8.2 
nnoremap ? :execute("Leaderf! rg --regexMode --cword --nowrap --reverse")<CR>
用这个命令搜索的时候 预览窗口会不断闪屏 
还有就是 因为打开直接进入正常默认 Popup窗口中会选中第一个选项 但是对应预览窗口并没有跳转到对应的位置 而是当前文件的开头

**Comment by gVimer** [comment]
3、建议预览窗口也加一个可以不换行的选项 因为换行影响排版
我自己目前是直接改的代码  加了 nowrap选项
magager.py 576行 
       `     lfCmd("call win_execute(%d, 'setlocal nowrap cursorline number norelativenumber colorcolumn= ')" % self._preview_winid)`

**Comment by Yggdroot** [comment]
> ![Snipaste_2020-06-06_18-40-20](https://user-images.githubusercontent.com/6241431/83942388-8e20ec00-a825-11ea-92ab-0a31dee10ae1.png)
> 就是文件总数 当前行数信息显示到下面的状态栏更好 （个人建议 ）

非popup模式是在下面，放上面我认为搜索时文件个数的变化更醒目一点。

**Comment by gVimer** [comment]
关于2楼闪屏的问题补充下  就是在异步搜索的过程中 光标总是跟在最新搜索的行下面 导致了预览窗口的内容不断变化  所以闪屏了  其实默认在第一个搜索结果  预览窗口也定位到对应的位置就可以了  还有就是预览窗口里面的被搜索的次能高亮不

**Comment by gVimer** [comment]
那个数字放在右边的话 需要移一下视野 感觉别扭 哈哈 可能是个人习惯吧

**Comment by gVimer** [comment]
有时候预览窗口匹配的行不在预览窗口的中间 所以看不到匹配行下面几行的内容 有时候是OK的
![Snipaste_2020-06-06_19-11-33](https://user-images.githubusercontent.com/6241431/83942822-a72b9c00-a829-11ea-84b3-41057340f6ac.png)

**Comment by gVimer** [comment]
还有一个问题是Popup窗口和Preview窗口同时存在的情况下 能不能按Esc的时候两个都关闭

**Comment by Yggdroot** [comment]
> 还有一个问题是Popup窗口和Preview窗口同时存在的情况下 能不能按Esc的时候两个都关闭

那就连个都关了吧。

**Comment by gVimer** [comment]
多谢大佬 另外再提个建议 就是我用Leaderf gtags的时候 这个能不能把路径都左对齐 类似的都做这样的处理  这样会好看些
![QQ截图20200606231800](https://user-images.githubusercontent.com/6241431/83947847-17e3b000-a84c-11ea-98ae-35c1e92a9d03.png)

**Comment by Yggdroot** [comment]
可以看这里https://zhuanlan.zhihu.com/p/64842373，有几种显示模式。

**Comment by gVimer** [comment]
> 可以看这里https://zhuanlan.zhihu.com/p/64842373 ，有几种显示模式。

多些大神  文章之前看过了 没反应过了 
再反应一个问题 命令：Leaderf rg -w --cword  
这个-w参数不起作用 即不是匹配完整的单词 我单独用RG是可以的
![{9F622745-60CD-4C8E-9825-B6D5992C7C7A}_20200608103429](https://user-images.githubusercontent.com/6241431/83987703-bc144680-a973-11ea-85e5-17de2fbe5ea9.jpg)
当然 也可能在在Leaderf中的这个参数跟rg原生的有本来就不一样

**Comment by Yggdroot** [comment]
你用的不对。
noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -w %s ", expand("<cword>"))<CR>

这样才是搜索光标下的单词。

--cword 是把光标下的词作为模糊匹配的输入，不一样。你这样用相当于用Leaderf rg， 然后在手动输入we, 而不是 Leaderf rg we。

**Comment by gVimer** [comment]
多谢大神了 这样也解决了上面说的闪屏的问题

**Comment by Yggdroot** [comment]
闪屏问题我还没有去复现呢，既然解决了我就不看了。

**Comment by cage1618** [comment]
![trim](https://user-images.githubusercontent.com/2541448/84132246-3b8b3e00-aa78-11ea-91ac-f287db4ab668.gif)

借这里报下另外一个问题，列表显示有些问题
1.莫名多出字符，如图上 app 显示成了  aapp
2.字符有残影，图上右边 好几个字母 p

**Comment by Yggdroot** [comment]
这算是nvim的bug吧

**Comment by Yggdroot** [comment]
nvim刷新有时候就有问题，可能跟平台有关，可能跟某个版本有关，Linux下应该没这个问题，nvim相比vim还是有一些不足的地方。

**Comment by cage1618** [comment]
> nvim刷新有时候就有问题，可能跟平台有关，可能跟某个版本有关，Linux下应该没这个问题，nvim相比vim还是有一些不足的地方。

好的

**Comment by Yggdroot** [comment]
> > nvim刷新有时候就有问题，可能跟平台有关，可能跟某个版本有关，Linux下应该没这个问题，nvim相比vim还是有一些不足的地方。
> 
> 好的

你把图标禁掉也许会好些。

**Comment by cage1618** [comment]
> > > nvim刷新有时候就有问题，可能跟平台有关，可能跟某个版本有关，Linux下应该没这个问题，nvim相比vim还是有一些不足的地方。
> > 
> > 
> > 好的
> 
> 你把图标禁掉也许会好些。

的确是，谢谢
