### ISSUE TITLE
如存在 buffer，对于选中的搜索结果，光标如何快速移动至相应的位置

### ISSUE THREAD

**Issue by NGPONG** [Yggdroot/LeaderF#628]
作者您好，感谢您提供如此精美巧妙的插件，先为您点个赞

对于搜索出来的结果，如果存在结果所对应文件的 buffer 时，当我们在选中当前结果词条的时候，光标能够直接快速的在对应buffer中跳转; 我不确定 LeaderF 是否内置了上述功能，因为在最初我是发现存在该功能，但是在后面对该插件进行配置的时候，我发现该功能无故消失了，我不确定我是否删除了某个重要的配置项而导致的

我曾翻阅过文档，似乎没有发现存在对应该功能的配置项，亦或者说是因为我的粗心而忽略了它

以下是我对于该插件的配置

```vim
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
let g:Lf_ReverseOrder = 1
let g:Lf_PreviewInPopup = 1
let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}
let g:Lf_WindowHeight = 0.2
let g:Lf_PreviewHorizontalPosition = 'right'
let g:Lf_PreviewPopupWidth = 0

let g:Lf_ShortcutF = "<leader>ff"
noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
" search visually selected text literally
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
noremap go :<C-U>Leaderf! rg --recall<CR>
```

**Comment by Yggdroot** [comment]
> 光标能够直接快速的在对应buffer中跳转; 

我不太明白这具体什么意思。

**Comment by NGPONG** [comment]
感谢您如此快速的回复!

如下图
![1](https://github.com/NGPONG/Blog/blob/master/img/2020-6-7-14-56-47.png)

预览窗口的弹出是一个非常棒的功能，但是仅对于当前文件的搜索，正如 vscode 亦或者众多 IDE 的功能一样; 我在当前文件中执行搜索(ctrl+f)时，仅通过光标的移动告知我当前搜索的结果是在当前文件中的哪一行，哪个位置，这样可能对于搜索结果的巡视会更加的直观点(仅对于当前文件)
![2](https://github.com/NGPONG/Blog/blob/master/img/2020-6-7-14-56-48.gif)

**Comment by NGPONG** [comment]
> > 光标能够直接快速的在对应buffer中跳转;
> 
> 我不太明白这具体什么意思。

**Comment by Yggdroot** [comment]
确实有个配置，叫previewresult，你看看帮助文档吧，我手机不方便。

**Comment by NGPONG** [comment]
> 确实有个配置，叫previewresult，你看看帮助文档吧，我手机不方便。

谢谢大佬，我再去翻一翻文档

**Comment by NGPONG** [comment]
问题已解决，我忽略了一下这一配置：
```vim
let g:Lf_PreviewInPopup = 0
```

但随之而来又产生了一个新的问题，请原谅我; 请问下是否有命令行参数的支持亦或者其他方式，能够在执行搜索前，指定针对于当前搜索的结果所使用的预览模式呢？

正如最开始的问题

仅我需要在当前文件中进行搜索时，才需要 **以光标跳转的方式** 去进行结果的预览

但是在进行全局搜索时，由于设计到的文件较多，那么再使用光标跳转的方式去进行预览的话，所导致的结果就是会打开非常多无用的 buffer，这时候使用 LeaderF 内置的 **Popup preview window** 去进行结果的预览或许是一个更好的选择

**Comment by Yggdroot** [comment]
`let g:Lf_PreviewResult = { 'rg': 1 }`可能是你想要的功能。

现在更新一下LeaderF，你的这段代码应该就可以用了。

**Comment by NGPONG** [comment]
> `let g:Lf_PreviewResult = { 'rg': 1 }`可能是你想要的功能。
> 
> 现在更新一下LeaderF，你的这段代码应该就可以用了。

非常感谢百忙之中增加此功能!刚尝试了下，的确是可以了，非常高兴，愿 LeaderF 越做越优秀!
