### ISSUE TITLE
More compatible with other stausline plugin?

### ISSUE THREAD

**Issue by iiifr** [Yggdroot/LeaderF#629]
LeaderF is a good vim plugin, but LeaderF has its own statusline rendering function, which sometimes conflict with other statusline plugin. For example, I have the plugin airline installed, when I re-enter LeaderF buffer, airline will override original LeaderF statusline.

Could we have following features:
* An option to disable LeaderF statusline rendering
* Some buffer-scoped variable for LeaderF buffer, which provide current LeaderF status like: current LeaderF subcommand, current search mode etc., to support other statusline plugin render statusline of LeaderF.

Thanks.

**Comment by Yggdroot** [comment]
> For example, I have the plugin airline installed, when I re-enter LeaderF buffer, airline will override original LeaderF statusline.

So you don't want airline to override LeaderF statusline?

**Comment by iiifr** [comment]
> > For example, I have the plugin airline installed, when I re-enter LeaderF buffer, airline will override original LeaderF statusline.
> 
> So you don't want airline to override LeaderF statusline?

我希望的是有个选项能让LeaderF不去更改statusline，并且LeaderF有个类似get_status()之类的function，能取得当前LeaderF buffer的一些资讯，好让airline能处理这些资讯并为LeaderF显示statusline。

谢谢。
