### ISSUE TITLE
compatibility with neovim

### ISSUE THREAD

**Issue by alextooter** [Yggdroot/LeaderF#63]
macOS下，brew安装了neovim0.2.0，想使用C extension，按照提示操作，无法完成。

我用的是 vim-plug，在init.vim中添加了
 Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }之后，又PlugInstall，提示都成功完成了，

但是echo g:Lf_fuzzyMatch_C，还是出错：
E121: Undefined variable: g:Lf_fuzzyMatch_C
E15: Invalid expression: g:Lf_fuzzyMatch_C

**Comment by Yggdroot** [comment]
有可能是我readme上说的不太清楚，需要执行一下LeaderF的命令再查看`echo g:Lf_fuzzyMatch_C`。
