### ISSUE TITLE
用Rg搜索单词的时候不会默认打开第一项的预览窗口

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#634]
Win+gVim8.2
`nnoremap ? :<C-U><C-R>=printf("Leaderf! rg -w  %s", expand("<cword>"))<CR><CR>
`
当我在一个单词下面按下“?”的时候 窗口是这样的:
![Snipaste_2020-06-13_10-24-00](https://user-images.githubusercontent.com/6241431/84557798-864ed380-ad60-11ea-8161-9dfa44f7e53f.png)
然后我需要按下“k”去预览第一项：
![Snipaste_2020-06-13_10-24-17](https://user-images.githubusercontent.com/6241431/84557820-aed6cd80-ad60-11ea-8978-7db9389fcaef.png)
然后换成按“j”去预览其它项.希望默认就直接打开第一项的预览!

**Comment by gVimer** [comment]
还有就是能不能加个选项：是否在预览窗口中也高亮搜索的单词

**Comment by Yggdroot** [comment]
好了。

**Comment by gVimer** [comment]
感谢了 上面的两个问题都OK了 但是又出现新的问题 绘制错乱了 之前是不会的
![QQ截图20200615231607](https://user-images.githubusercontent.com/6241431/84675014-435a4f00-af5e-11ea-935d-2dfca1f462a0.png)

**Comment by gVimer** [comment]
可能是gVIM的BUG吧  确定跟插件没关系的话 这个ISSEUE麻烦大神关下

**Comment by gVimer** [comment]
又对比了下 之前的版本没这个问题 最新版本 在按 K J键浏览的时候 上面标记的区域闪的很厉害

**Comment by Yggdroot** [comment]
嗯，这是vim的问题，不是leaderf的问题。
