### ISSUE TITLE
  How to configure to search the current word directly instead of entering ‘Enter’ confirm

### ISSUE THREAD

**Issue by rolandjon** [Yggdroot/LeaderF#635]
For example, when I search “test”, the current behavior is listed below the screen like:
**:Leaderf! rg --current-buffer -e test**
 asked me to confirm ,and I needed to input ‘Enter’ to perform the search. The behavior I want is to display the search results directly after I enter the shortcut key without needing to confirm twice.

**Comment by Yggdroot** [comment]
It depends on how you map the command.

`noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR><CR>`

**Comment by rolandjon** [comment]
Um, I see, two consecutive <CR>s can achieve what I want, thank u  for your patience. -)
