### ISSUE TITLE
How to disable the icon before each item?

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#636]
- vim or neovim? 
    - [ ] vim
    - [ x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

After upgrading LeaderF, now my Neovim will show the icon like this:

![image](https://user-images.githubusercontent.com/5763157/84612195-6e0ebe00-aef2-11ea-9076-7dfdadc4725d.png)

How could I disable the icon? I know it is caused by the missing font, but I do not want to install extra font.

Thanks!

**Comment by Yggdroot** [comment]
let g:Lf_ShowDevIcons = 0
