### ISSUE TITLE
Open buffer in current window instead of jumping to the window that contains the buffer

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#637]
Hi,

In the old version of LeaderF, when I search for a buffer, it will open that buffer in current window even it is opened in another window. So I could open the same buffer in two splits side by side.

In the latest version of LeaderF, it will jump to the window that contains that buffer instead of replacing current buffer in current window.

Is there any option to change the behavior?

Thanks!

**Comment by Yggdroot** [comment]
let g:Lf_JumpToExistingWindow = 0
