### ISSUE TITLE
预览窗口的宽度超了

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#638]
Win+gVim8.2 
大部分情况下都是正常的 这个简单的文本居然会这样 行尾没有空格的
![{74488AA9-0303-4587-A293-C5E927D19C1E}_20200616120703](https://user-images.githubusercontent.com/6241431/84730971-0a57c400-afca-11ea-9bf5-03bfd391a045.jpg)

**Comment by gVimer** [comment]
还有一个问题就是滚动条能不能一直显示 不然不显示的时候有点丑
![{B1B94531-EB0B-451F-ACD9-481F13C5FFFD}_20200616122802](https://user-images.githubusercontent.com/6241431/84731910-e9dd3900-afcc-11ea-9ef6-1a83cc748fab.jpg)

**Comment by Yggdroot** [comment]
复现不了。

**Comment by gVimer** [comment]
打扰了我自己处理了

**Comment by gVimer** [comment]
我自己把宽度 定死 
` options["maxwidth"] = 123`
