### ISSUE TITLE
buffer from another tab?

### ISSUE THREAD

**Issue by eyalk5** [Yggdroot/LeaderF#639]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim

Hi,
More of a question than a bug. if I run leaderf buffer and there is a buffer that is attached to another tab ( this attachment is by default or by ctrlspace plugin?), after `Leaderf buffer` upon selecting the buffer,  I get transferred to another tab.

Is this expected? Can this behavior be changed(or is there another option)?

**Comment by Yggdroot** [comment]
What is your expected behavior?

**Comment by Yggdroot** [comment]
let g:Lf_JumpToExistingWindow = 0

**Comment by eyalk5** [comment]
Good enough. Thanks!
