### ISSUE TITLE
need a reindex when reopen vim?

### ISSUE THREAD

**Issue by xltan** [Yggdroot/LeaderF#64]
Greet Plugin! Thanks~
It seems the cache is not persistent when vim is closed, intended?

**Comment by Yggdroot** [comment]
Yes, if there is no `rg` or `ag` or `pt` or `find`, the cache will work.

**Comment by xltan** [comment]
Thanks for the prompt reply. 
Another question about cache:
In some scenarios, one may work with multi directories, again, the reindex is needed there, but the cost may be intolerable. 
Are there any plans to address this problem?

**Comment by Yggdroot** [comment]
OK, I'll add an option to specify whether to cache the filenames later.

**Comment by xltan** [comment]
Wow, you're so great, thanks again, btw, your code is really good and clean!

**Comment by xltan** [comment]
Hi again~

**Comment by xltan** [comment]
Hi again~
I find this snippet in your code, `bufTagExpl\functionExpl`, etc:
`lfCmd("setlocal cursorline! | redraw | sleep 100m | setlocal cursorline!")`
I think this cursorline trick can be a little annoying when in preview mode~

**Comment by Yggdroot** [comment]
`let g:Lf_PreviewResult = { 'BufTag': 0, 'Function': 0 }`, this can disable the preview.

**Comment by xltan** [comment]
yep~ at first glance, I thought the preview is really cool, but later, I find it will mess up with my jumplist, so I just disable them, thanks anyway.

**Comment by Yggdroot** [comment]
Cache added. Please use the dev branch to have a try.

**Comment by xltan** [comment]
Work like a charm! Thanks

**Comment by xltan** [comment]
refresh the cache seems broken~

**Comment by xltan** [comment]
2 bugs: 
when cache option turns on, after reopen vim, _buildCmd may not be processed, so no external cmd will be initialized.
getFreshContent should ignore cache.

**Comment by Yggdroot** [comment]
Thanks, I'll fix it soon.

**Comment by Yggdroot** [comment]
fixed. Please have a try.

**Comment by xltan** [comment]
cool, everything works very well.
btw, in the mean time, with little vim knowledge, I wrote a tag jump leaderf extension.
[LeaderF-tjump](https://github.com/xltan/LeaderF-tjump): a simplified just work leaderf version [vim-ctrlp-tjump](https://github.com/ivalkeen/vim-ctrlp-tjump).
just want to share with you that your extension is really easy to extend.

**Comment by Yggdroot** [comment]
Good, thanks.

**Comment by sisrfeng** [comment]
Is there anything bad about  this :  `LeaderF won't reindex the files when reopen vim`
