### ISSUE TITLE
[gtags相关]gtags的跳转是行号跳转还是模式跳转？如何切换？

### ISSUE THREAD

**Issue by fly-potato-100** [Yggdroot/LeaderF#640]
不确定是插件问题还是我没找到global的相关设置参数。

目前的情况是：当我update完gtags的数据库后，源文件发生了修改，符号行号变化了。

这时执行`Leaderf! gtags -r XXX`打开的LeaderF窗口中，行号还是老的，该行内容也错乱了；实际跳转过去也是错的。

联想到ctags的number和pattern两种跳转模式，怀疑是不是自己哪里没配对？

请大佬抽空指点一下

**Comment by fly-potato-100** [comment]
情况不太好重现，不能排除是我自己有误操作造成的，我再摸索一周看看规律。

如果不能复现就先close好了

**Comment by Yggdroot** [comment]
是根据行号跳转的。有可能是数据库还没更新好，还是旧的，你就执行了那个命令。

**Comment by fly-potato-100** [comment]
试着总结了下规律：
0. g:Lf_GtagsAutoGenerate一直设为0
1. 当vim保持打开状态，编辑源码改变行号，`:w`保存，gtags查询和跳转，能够看到新的行号，并不会错乱（不论是否手动update）
2. `:q`关闭vim，重新打开，并使用gtags查询和跳转，也没有问题，是新的行号
3. `:q`关闭vim，执行类似`svn revert XXX`之类的操作，把前面的更改都回退掉
4. 这时再次打开vim，gtags查询和跳转，行号是错误的。
5. 此时再次`:w`强制刷一次buffer，gtags查询和跳转，行号正常了，跳转也无误了（似乎后台偷偷调用了一次gtags？？）

最后想确认下，是否有办法采用ctags那样的mixed的模式去跳转呢？

**Comment by Yggdroot** [comment]
原来是这样，那很好解释了。
因为文件改动，vim会检测到被修改，用autocmd 通知gtags更新数据库。
> 3. :q关闭vim，执行类似svn revert XXX之类的操作，把前面的更改都回退掉

这一步，你没有通过vim修改，Leaderf gtags 并不知道这个修改，所以不会更新数据库。这种情况只能手动更新数据库了。

没有办法支持mixed 模式。

**Comment by fly-potato-100** [comment]
> vim会检测到被修改，用autocmd 通知gtags更新数据库。
这个倒是可能解释了我遇到的其他问题：
因为项目比较大，我有时同时打开多个buffer改多个文件，然后保存时触发了更新数据库。
然后我很快的`:q`（有时甚至直接`ZZ`），我猜测gtags更新数据库可能已经写坏了。
我出现过vim关闭后gtags和sort进程不停产生无法停止直到负载撑爆的情况（不确定具体频率，大概5分钟产生了20多个？开始的时候完全没注意，直到开始卡了，top一看一大片的gtags在跑）

所以autocmd通知gtags更新数据库的行为，该如何关闭呢？

**Comment by Yggdroot** [comment]
> 所以autocmd通知gtags更新数据库的行为，该如何关闭呢？

写死的，没法关闭。
