### ISSUE TITLE
Request: installer: python2 install process move to 2nd method becase python2 deprecated .

### ISSUE THREAD

**Issue by tsuyoshicho** [Yggdroot/LeaderF#642]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 12 2020 10:39:30)
Included patches: 1-950
Compiled by Homebrew
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): ""
- Output of `:echo &pythonthreedll`(only vim, not neovim): nothing
- Output of `:py print(sys.version)`: -
- Output of `:py3 print(sys.version)`: `3.8.3 (default, Jun  1 2020, 10:20:09)`
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
 not need this issue

### Describe your question, feature request, or bug.

Currently, python2 is End of Life, and although it is installed on the system, it is possible that there is no python-dev due to a system script(ptyon3-dev is installed and so on, E.g linuxbrew python2 removed from build env ).
At this time, the installer first tries to install with python2, but it gives an error here.

The installer will continue and the python3 installation will succeed, but the plugin manager may consider the update failed as the installer returns a not 0 exit code.

As a suggestion, I would like the installer processing order to be python3 -> python2(speed) and treat error handling by 1st try.

### Steps to reproduce

python2 installed, python2-dev not installed.
python3 and python3-dev installed.

vim with only python3 build.

then install it.

### Actual behaviour

python2 or 3 avaliabled, install success but install process display as failed.

### Expected behaviour

python2 or 3 avaliabled, install success.

**Comment by Yggdroot** [comment]
I don't understand. If python2 fails and python3 succeeds, `$?` should be 0.

**Comment by tsuyoshicho** [comment]
Okay, logging and report it. please wait...

**Comment by tsuyoshicho** [comment]
I'm sorry, the error code was 0, it seems that there was a mistake in the description of the installation procedure...
