### ISSUE TITLE
`<C-T>` won't open a new tabpage when the file has been opened in an existing tabpage

### ISSUE THREAD

**Issue by hao-lee** [Yggdroot/LeaderF#643]
- vim or neovim? 
    - [x] vim
- Operating system: 
    - [x] Linux
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

`<C-T>` is designed to open file in a new tabpage, but if the file has been opened in an existing tabpage, LeaderF will switch to this tabpage instead of create a new tabpage. Is this the intended behavior?

### Expected behaviour

When pressing `<C-T>`, LeaderF will open the file in a new tabpage even this file has already been opened in  an existing tabpage.

**Comment by Yggdroot** [comment]
Yes, it's by design.

**Comment by hao-lee** [comment]
When I'm reading source code, I usually open the same file in several tabs simultaneously so I can read functions according to their calling order. This behavior breaks the order of tabpages. Is it possible to add an option to control what `<C-T>` should do.

**Comment by Yggdroot** [comment]
let g:Lf_JumpToExistingWindow = 0

**Comment by hao-lee** [comment]
Many thanks!
