### ISSUE TITLE
Leaderf rg doesn't support --multiline searching?

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#645]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by eyalk5** [comment]
see #646

**Comment by Yggdroot** [comment]
Won't support.

**Comment by xaljer** [comment]
@Yggdroot , i think it's a useful feature, why Leaderf won't support it?

**Comment by Yggdroot** [comment]
Because I hardly ever use it. 
OK, I will add the support some time later.

**Comment by xaljer** [comment]
Thanks, it's not a daily used feature. but sometimes i need it, it will be very helpful.
