### ISSUE TITLE
Unknown function LfDefineDefaultColors

### ISSUE THREAD

**Issue by yehuohan** [Yggdroot/LeaderF#650]
- vim or neovim? 
    - [x] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:  vim8.2-754, neovim-0.5-558
- Output of `:py3 print(sys.version)`: 3.8.3
- Output of `:echo g:Lf_Debug_Cmd`: rg --no-messages --files   -g "!.git" -g "!.svn" -g "!.hg"  --hidden
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```
    let g:Lf_CacheDirectory = $DotVimPath
    "let g:Lf_WindowPosition = 'popup'
    "let g:Lf_PreviewInPopup = 1
    let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0}
if s:gset.use_powerfont
    let g:Lf_StlSeparator = {'left': '', 'right': ''}
else
    let g:Lf_StlSeparator = {'left': '', 'right': ''}
endif
    let g:Lf_ShowDevIcons = 0
    let g:Lf_ShortcutF = ''
    let g:Lf_ShortcutB = ''
    let g:Lf_ReverseOrder = 1
    let g:Lf_ShowHidden = 1
    let g:Lf_GtagsAutoGenerate = 0
    let g:Lf_Gtagslabel = 'native-pygments'
    let g:Lf_WildIgnore = {
        \ 'dir': ['.git', '.svn', '.hg'],
        \ 'file': []
        \ }
```

### Describe your question, feature request, or bug.

已经update到最新版leaderf，执行LeaderfFile命令，使用popup正常，不使用popup时，出现“Unknown function LfDefineDefaultColors”

目前，发现通过注释掉

https://github.com/Yggdroot/LeaderF/blob/adf7bb88039f1732f82401812e2a3c8baed8ac92/autoload/leaderf/colorscheme/popup.vim#L229

这一行时，在自己电脑上 使用popup和不使用popup 都可以正常工作。

**Comment by Yggdroot** [comment]
Fixed.

**Comment by likelxl** [comment]
没有解决呀，我只要设置了let g:Lf_WindowPosition = 'popup' 就报错，就算注释了都不行，
![image](https://user-images.githubusercontent.com/12811070/87785713-384f5300-c86b-11ea-8d4d-d6ca4602dba5.png)

**Comment by Yggdroot** [comment]
你代码是最新的吗？我一直设着let g:Lf_WindowPosition = 'popup'， 没有问题。

**Comment by likelxl** [comment]
> 你代码是最新的吗？我一直设着let g:Lf_WindowPosition = 'popup'， 没有问题。

是，刚才拉取的，不过我用的是pack方式管理插件，不过奇怪的是在公司没有这情况

**Comment by Yggdroot** [comment]
> 
> 
> > 你代码是最新的吗？我一直设着let g:Lf_WindowPosition = 'popup'， 没有问题。
> 
> 是，刚才拉取的，不过我用的是pack方式管理插件，不过奇怪的是在公司没有这情况，系统环境都是一样的

pack 方式是怎样的？ 你换其他插件管理器试试。

**Comment by likelxl** [comment]
> > > 你代码是最新的吗？我一直设着let g:Lf_WindowPosition = 'popup'， 没有问题。
> > 
> > 
> > 是，刚才拉取的，不过我用的是pack方式管理插件，不过奇怪的是在公司没有这情况，系统环境都是一样的
> 
> pack 方式是怎样的？ 你换其他插件管理器试试。

就是vim自带的,https://aisk.me/vim-8-native-plugin-manager/ 参考此文章，我试试plug去

**Comment by likelxl** [comment]
测试了下，plug没问题，但是我在公司用的也是pack形式，奇怪
