### ISSUE TITLE
how to search files from upper level directory?

### ISSUE THREAD

**Issue by tanglianggithub** [Yggdroot/LeaderF#652]
for example:
current in directory dir2, but want to search file 1 in dir1, what can I do?

![image](https://user-images.githubusercontent.com/3445470/86510665-59a05000-be24-11ea-84cc-6de4671e21cd.png)

**Comment by Yggdroot** [comment]
:LeaderfFile ..

**Comment by tanglianggithub** [comment]
If directory has multiple levels, must run like LeaderfFile ../../.. or LeaderfFile ../.. ?  
If so, that is not convenient as ctrlp does.

**Comment by Yggdroot** [comment]
It can do whatever ctrlp can do.

**Comment by tanglianggithub** [comment]
yes, it can do. But how can I do it without knowing directory levels?

**Comment by tanglianggithub** [comment]
I read leaderf.txt and found Lf_RootMarkers. How can I search for files from Lf_RootMarkers directory at any time?

**Comment by tanglianggithub** [comment]
let g:Lf_WorkingDirectoryMode = 'Ac' work for me.
