### ISSUE TITLE
write the core engine with go or RUST

### ISSUE THREAD

**Issue by zhuzhzh** [Yggdroot/LeaderF#656]
I like LeaderF very much! but one thing makes me painful.
my industry is very conservative. RHEL6 is still dominent.
so I have to compile Python3 and vim by myself.
I find Go and RUST is pretty good on resolving dependecy issue. ( all in one)
so I just want to check if it's possible to write the core engine with Go or RUST, and not use python.
it's just one questions, not any request or recommendation. :-)

**Comment by Yggdroot** [comment]
LeaderF is mainly written in python, and a little code in vimL and C, if using Go or Rust, I have to write it from scratch, it is a huge effort.
