### ISSUE TITLE
希望能给preview加入一个lazy mode

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#657]
我同时在linux和window上通过vim使用leaderf这个插件
popup 自动preview的功能非常好
但如果工程中的文件太多的时候
在文件或者taglist中移动光标的时候,每个都会显示popup preview,这会非常慢
可否加入一个lazy模式, 使得光标选中某个文件之后的几百毫秒后才开始preview?

**Comment by Yggdroot** [comment]
可以默认不开启preview，按p再preview

**Comment by irreallich** [comment]
preview的功能很好用, 按p开启是个办法
我这仅是一个提议.
