### ISSUE TITLE
两点优化建议

### ISSUE THREAD

**Issue by cage1618** [Yggdroot/LeaderF#658]
提两个优化建议，希望能被采纳：

1.LeaderF file 或 LeaderF rg 的时候，打开的文件在 statusline 中显示的是完整路径，即使在 vimrc 中配置了显示相对路径也不生效

2.设置了 wildignore 或 gitignore 后，希望进入到被忽略的子目录下时能正常使用 file 命令（比如想看 node_modules下的某个npm 包），当前 :Leaderf file 列表是空的

**Comment by Yggdroot** [comment]
> 
> 
> 提两个优化建议，希望能被采纳：
> 
> 1.LeaderF file 或 LeaderF rg 的时候，打开的文件在 statusline 中显示的是完整路径，即使在 vimrc 中配置了显示相对路径也不生效
> 

这里说的statusline是LeaderF的statusline吗，statusline里显示的是当前工作路径，没有配置能改。如果显示成相对路径，就是一个点，无意义。

> 2.设置了 wildignore 或 gitignore 后，希望进入到被忽略的子目录下时能正常使用 file 命令（比如想看 node_modules下的某个npm 包），当前 :Leaderf file 列表是空的

Leaderf file --no-ignore.

**Comment by cage1618** [comment]
> > 提两个优化建议，希望能被采纳：
> > 1.LeaderF file 或 LeaderF rg 的时候，打开的文件在 statusline 中显示的是完整路径，即使在 vimrc 中配置了显示相对路径也不生效
> 
> 这里说的statusline是LeaderF的statusline吗，statusline里显示的是当前工作路径，没有配置能改。如果显示成相对路径，就是一个点，无意义。
> 
> > 2.设置了 wildignore 或 gitignore 后，希望进入到被忽略的子目录下时能正常使用 file 命令（比如想看 node_modules下的某个npm 包），当前 :Leaderf file 列表是空的
> 
> Leaderf file --no-ignore.

不是LeaderF 的statusline，是主窗口的 statusline

<img width="350" alt="image" src="https://user-images.githubusercontent.com/2541448/87744602-77a38280-c81e-11ea-8161-8a125cf9d4e7.png">

直接在命令行 vim vimrc 是对的：
<img width="100" alt="image" src="https://user-images.githubusercontent.com/2541448/87744633-89852580-c81e-11ea-93a3-566e1006d457.png">

**Comment by Yggdroot** [comment]
主窗口的statusline跟LeaderF没关系呀。
