### ISSUE TITLE
`g:Lf_JumpToExistingWindow` should be off by default

### ISSUE THREAD

**Issue by bennyyip** [Yggdroot/LeaderF#659]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
LeaderF introduced `g:Lf_JumpToExistingWindow` in https://github.com/Yggdroot/LeaderF/issues/471 and set it to 1 by default, but LeaderF works as this option is 0 before. 

This is an unexpected breaking change.

Since this feature has been added months ago, setting it to 0 is also a breaking change. Maybe it's better to keep it on. I wish future features won't break previous behaviors.

**Comment by Yggdroot** [comment]
OK.
