### ISSUE TITLE
Some error message

### ISSUE THREAD

**Issue by ChampionLi** [Yggdroot/LeaderF#66]
Thanks for the nice plugin. However, after I follow the installation(Windows10) to install it, the vim prompts the following error message when I open my vim.  
![error](https://user-images.githubusercontent.com/11646855/30727421-b4af684a-9f83-11e7-8b59-8f32f0aad6fa.JPG)

**Comment by Yggdroot** [comment]
I think this error is caused by your vim encoding.
Please `set encoding=utf-8` in your vimrc.

**Comment by ChampionLi** [comment]
Thank you very much. The problem is solved.
