### ISSUE TITLE
双击Rg命令搜索的结果报错 AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#660]
WIN10+gVim8.2+最新的Leaderf代码
命令
`nnoremap <Leader>t :exec("Leaderf rg --nowrap --belowright --stayOpen")<CR>
`

![{5BA3E43A-EAF6-4877-8F75-3120D572CA50}_20200716143339](https://user-images.githubusercontent.com/6241431/87635328-6c464d80-c771-11ea-8d35-5472be04685a.jpg)

在搜索的结果中双击其中一行以打开到对应的文件 经常报错 可以说是必现的
![A26CD0A3-79B1-4d82-832E-488101BC1B53](https://user-images.githubusercontent.com/6241431/87635354-7a946980-c771-11ea-9e5e-ab71c8ae492a.png)

**Comment by Yggdroot** [comment]
不知道怎么复现。

**Comment by gVimer** [comment]
应该很容易出现啊  多点几次就可以了 不过我都是在WIN下操作的

**Comment by Yggdroot** [comment]
最好能像https://github.com/Yggdroot/LeaderF/issues/625#issuecomment-647088073 这样把复现步骤写清楚，最好能提供一个minivimrc。
