### ISSUE TITLE
Leaderf file的结果cache问题

### ISSUE THREAD

**Issue by lvyanpo** [Yggdroot/LeaderF#661]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 10 2020 00:32:34)
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7.12 (default, Apr 15 2020, 17:07:12)
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: git ls-files  "." && git ls-files --others --exclude-standard  -x ".svn" -x ".hg" -x ".vscode" -x ".wine" -x ".deepinwine" -x ".oh-my-zsh" -x ".repo" -x "*.sw?" -x "~$*" -x "*.bak" -x "*.exe" -x "*.o" -x "*.so" -x "*.py[co]" -x "*.class" "."
- Output of `:echo g:Lf_FilesFromCache`:0
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
有时候有的文件已经删除了，但是Leaderf file结果中还会出现此文件。
### Steps to reproduce
没有找到再现方法，通过设置let g:Lf_UseMemoryCache = 0和let g:Lf_UseCache = 0没有作用，
还有其他方法清除file结果的cache吗？

**Comment by Yggdroot** [comment]
这个原因是你git没用对。
如果你删除了文件，不想把他列出来，不应该也从git中删掉吗？

**Comment by lvyanpo** [comment]
> 这个原因是你git没用对。
> 如果你删除了文件，不想把他列出来，不应该也从git中删掉吗？

谢谢，知道了，我以为工作目录里删除了就不会提示了。
git rm后没有问题了。
