### ISSUE TITLE
匹配相关问题

### ISSUE THREAD

**Issue by bstaint** [Yggdroot/LeaderF#664]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
1. 打开g:Lf_ShowDevIcons和关闭g:Lf_ShowDevIcons选项匹配高亮结果不同：

打开状态：

![1](https://user-images.githubusercontent.com/5853792/88405129-67346e80-ce01-11ea-972d-8cfcd178884d.png)

关闭状态：

![2](https://user-images.githubusercontent.com/5853792/88405136-6a2f5f00-ce01-11ea-88af-5f099e0c2990.png)

2. 高亮匹配的时候有一定延迟：

![GIF](https://user-images.githubusercontent.com/5853792/88405230-87642d80-ce01-11ea-8e49-e289364f32f8.gif)

**Comment by bstaint** [comment]
看了下延迟是跟https://github.com/Yggdroot/LeaderF/commit/afbfa0b57c08fb824bb395946b19a24fbd0f5412 有关，是feature么

**Comment by Yggdroot** [comment]
是的，你这是vim还是neovim？

**Comment by bstaint** [comment]
gvim

**Comment by Yggdroot** [comment]
> gvim

最后一个图看着像nvim。

**Comment by Yggdroot** [comment]
用的是最新的code吗？ 高亮错位和延迟我都复现不了。

**Comment by bstaint** [comment]
最新的，我查了下错位跟set encoding=utf-8有关.

延迟还没弄清楚，不过
```
             if lfEval("has('nvim') && exists('g:GuiLoaded')") == '1':
                 threshold = 2
             else:
-                threshold = 25
+                threshold = 5
```
这样会缓解一些。

**Comment by Yggdroot** [comment]
奇怪，难道跟电脑配置有关。

**Comment by bstaint** [comment]
我尝试下载
https://github.com/vim/vim-win32-installer/releases

vimrc
```
" 编码设置 {{{
set nocompatible
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,cp936,gb2312
set fileencodings+=big5,euc-jp,euc-kr,latin1
let &termencoding=&encoding
set encoding=utf-8
language messages zh_CN
" language messages en_US
set synmaxcol=500
syntax on
"}}}

let $VIMFILES = has('win32') ? $VIM.'/vimfiles' : $HOME.'/.vim'
if has('win32')
    set viminfo+=n$TEMP\\vim\\_viminfo
endif


let g:Lf_HideHelp = 1
" let g:Lf_ShowDevIcons = 0
let g:Lf_CacheDirectory = $TEMP.'/vim/'

```

也可以复现

**Comment by Yggdroot** [comment]
延迟问题不能复现。太奇怪了，就算threshold = 25，总共也就sleep 0.025 秒，应该不会感觉到延迟。

**Comment by Yggdroot** [comment]
能否提供一个minivimrc来复现这个延迟问题。

**Comment by bstaint** [comment]
上面的那个vimrc就可以复现。

**Comment by Yggdroot** [comment]
```diff
diff --git a/autoload/leaderf/python/leaderf/manager.py b/autoload/leaderf/python/leaderf/manager.py
index 0ce02fa..e6f2144 100644
--- a/autoload/leaderf/python/leaderf/manager.py
+++ b/autoload/leaderf/python/leaderf/manager.py
@@ -1355,6 +1355,7 @@ class Manager(object):
         else:
             self._highlight_method = highlight_method
             self._highlight_method()
+        lfCmd("redraw")
 
     def _guessFilter(self, filename, suffix, dirname, icon, iterable):
         """
```
试一下这个patch

**Comment by bstaint** [comment]
没有延迟了

**Comment by Yggdroot** [comment]
看看最新的提交是否修复了延迟的问题。

**Comment by bstaint** [comment]
没问题了，感谢。

**Comment by bstaint** [comment]
错位问题不能复现么。
set encoding=utf-8
let g:Lf_ShowDevIcons = 0
的时候就会出现。

**Comment by bstaint** [comment]
应该是这里的问题。
```
--- a/autoload/leaderf/python/leaderf/devicons.py
+++ b/autoload/leaderf/python/leaderf/devicons.py
@@ -392,7 +392,7 @@ def webDevIconsStrLen():
     return len(webDevIconsString())

 def webDevIconsBytesLen():
-    return lfBytesLen(webDevIconsString())
+    return lfBytesLen(webDevIconsString()) if vim.vars.get('Lf_ShowDevIcons', True) else 0
```

**Comment by Yggdroot** [comment]
> 错位问题不能复现么。
> set encoding=utf-8
> let g:Lf_ShowDevIcons = 0
> 的时候就会出现。

复现不了。
你那里必现吗？换台机器试试也是必现吗？

**Comment by bstaint** [comment]
我开了台Win7的虚拟机可以复现，下载：https://github.com/vim/vim-win32-installer/releases

vimrc:
```vim
set nocompatible
if &modifiable
    set fileencoding=utf-8
    set fileencodings=ucs-bom,utf-8,gbk,cp936,gb2312
    set fileencodings+=big5,euc-jp,euc-kr,latin1
endif
set encoding=utf-8
let &termencoding=&encoding
language messages zh_CN
" language messages en_US
set synmaxcol=500
syntax on
"}}}

let g:Lf_HideHelp = 1
let g:Lf_ShowDevIcons = 0
```

我测试了下，`Leaderf file`正常，`Leaderf mru`错位。

**Comment by Yggdroot** [comment]
复现了，缺省很诡异，我的vimrc也设了`set encoding=utf-8`，就没问题。

**Comment by Yggdroot** [comment]
> 复现了，确实很诡异，我的vimrc也设了`set encoding=utf-8`，就没问题。

原因找到了，我设了`let g:Lf_PythonVersion = 2`， 使用的是Python2，在使用Python3时有bug。

**Comment by bstaint** [comment]
@Yggdroot 
https://github.com/Yggdroot/LeaderF/blob/877b6af4011e08af03899c22550d18c12eb7c00b/autoload/leaderf/python/leaderf/manager.py#L1360

这里应该是`>=1`吧，我发现如果`==1`的话敲的快一点还是有一定迟钝感

**Comment by Yggdroot** [comment]
错位问题已修复。

> https://github.com/Yggdroot/LeaderF/blob/877b6af4011e08af03899c22550d18c12eb7c00b/autoload/leaderf/python/leaderf/manager.py#L1360
> 
> 这里应该是`>=1`吧，我发现如果`==1`的话敲的快一点还是有一定迟钝感

你是说 `if len(self._cli.pattern) >= 1 and len(self._cli.pattern) - len(self._last_pattern) == 1: `？

其实直接redraw 是能彻底解决延迟问题，只是每敲一个字符就redraw有点损耗性能，所以我加了点条件。

**Comment by bstaint** [comment]
```
if len(self._cli.pattern) > 1 and len(self._cli.pattern) - len(self._last_pattern) >= 1: 
```
这样，比如
m
main
这样的话应该就不符合条件就会有一定延迟

**Comment by Yggdroot** [comment]
明白了。其实这个条件基本相当于不加条件。

**Comment by bstaint** [comment]
不会吧，我测试了，还是会有效果，截图感觉不出来，但是能感觉到延迟没了。

**Comment by Yggdroot** [comment]
我的意思是相当于直接无条件redraw，肯定有效果。

**Comment by Yggdroot** [comment]
这一次应该彻底的解决了，只是损失了点性能。

**Comment by bstaint** [comment]
感谢

**Comment by wsdjeg** [comment]
好熟悉的id，原来是你给我的arch pdf教程的么？后来QQ不用都失联了。

不好意思，借用下issue thread。

**Comment by hy172574895** [comment]
最新的代码，错位没有了，但是还能感觉到延迟！
![搜狗截图20200804134840](https://user-images.githubusercontent.com/31300347/89257757-64cfe100-d659-11ea-82d7-79b7cde862ea.png)

**Comment by Yggdroot** [comment]
> 
> 
> 最新的代码，错位没有了，但是还能感觉到延迟！

重新编译一下c扩展

**Comment by hy172574895** [comment]
> > 最新的代码，错位没有了，但是还能感觉到延迟！
> 
> 重新编译一下c扩展

重新编译了一下了。错误没有了。
但是只要我输入字符输入得快，就有一秒的延迟才显示结果。

**Comment by Yggdroot** [comment]
> 但是只要我输入字符输入得快，就有一秒的延迟才显示结果。

https://github.com/Yggdroot/LeaderF/blob/12179a7606ef15819e62585e8b08c5578b0143b4/autoload/leaderf/python/leaderf/manager.py#L1357-L1358

把这里改成
`lfCmd("redraw")` 试试。不加条件了。

**Comment by hy172574895** [comment]
![搜狗截图20200804141102](https://user-images.githubusercontent.com/31300347/89259225-7070d700-d65c-11ea-817c-4176c9bed53b.png)
改成这样，还是很明显........

**Comment by Yggdroot** [comment]
> 改成这样，还是很明显........

太奇怪了，能截个动图吗？ 我各个平台都没感到。

**Comment by hy172574895** [comment]
> > 改成这样，还是很明显........
> 
> 太奇怪了，能截个动图吗？ 我各个平台都没感到。

好的。今晚再聊吧。我现在要去搬砖了

**Comment by hy172574895** [comment]
![2](https://user-images.githubusercontent.com/31300347/89278391-9b692400-d678-11ea-849d-86f4c9be9b5d.gif)
不知道你能不能看出来。我已经完全输入好了 “vim” 这个关键字了，但leaderf 过了一秒才高亮好“vim”。无论是否使用 popup。
相对于旧版本v1.21，leaderf是没有这个延迟的。

**Comment by hy172574895** [comment]
![搜狗截图20200804173805](https://user-images.githubusercontent.com/31300347/89278957-58f41700-d679-11ea-93c2-a5b4bb482ce5.png)
我用 leaderf-filter 也出现了错位的情况，但leaderf却正常。 全部都是最新的代码。

**Comment by Yggdroot** [comment]
> 我用 leaderf-filter 也出现了错位的情况，但leaderf却正常。 全部都是最新的代码。

给他提issue吧，可能相关代码他用了我的，我的bug修复了，他没修复。

**Comment by Yggdroot** [comment]
> 不知道你能不能看出来。我已经完全输入好了 “vim” 这个关键字了，但leaderf 过了一秒才高亮好“vim”。无论是否使用 popup。
> 相对于旧版本v1.21，leaderf是没有这个延迟的。

能看出来一点，可能是你对这个太敏感，其实要远远小于一秒。

**Comment by Yggdroot** [comment]
> 不知道你能不能看出来。我已经完全输入好了 “vim” 这个关键字了，但leaderf 过了一秒才高亮好“vim”。无论是否使用 popup。
> 相对于旧版本v1.21，leaderf是没有这个延迟的。

你可能用习惯了对每个字符及时响应，我重新修改了，文件数10万以下用以前的逻辑。

**Comment by Yggdroot** [comment]
改动了一些代码，帮忙看一下延迟问题是否回来了。

**Comment by bstaint** [comment]
我已经换成neovim了，没遇到延迟问题

**Comment by Yggdroot** [comment]
谢谢。
