### ISSUE TITLE
mapping <c-v> using primay not clipboard

### ISSUE THREAD

**Issue by roachsinai** [Yggdroot/LeaderF#667]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jul 12 2020 00:14:12) 编译者 Arch Linux
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.8.so.1.0
- Output of `:py3 print(sys.version)`: 3.8.3 (default, May 17 2020, 18:15:42) [GCC 10.1.0]
- Operating system: 
    - [x] Manjaro Linux
- Configurations related to LeaderF in vimrc: 

```
" 定义快捷键的前缀，即<leader>
let mapleader=" "
call plug#begin('~/.vim/plugged')
Plug 'sainnhe/gruvbox-material' | Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
call plug#end()

let g:gruvbox_material_background = 'soft'
set background=dark
colorscheme gruvbox-material

```
### Describe your question, feature request, or bug.

Leaderf paster content in reigster `*` not `+`, does it by design?

### Steps to reproduce

run `Leader line`, use <C-V> paste to search lines match it.

### Actual behaviour

paste content in register `*`

### Expected behaviour

paste content in register `+`

**Comment by Yggdroot** [comment]
it's by design.

**Comment by Yggdroot** [comment]
Because usually, I copy some word from outside of vim.

**Comment by roachsinai** [comment]
@Yggdroot I update typo of first comment.(`" -> +`)

Doesn't regester `+` was used to keep consistant with system clipboard?

I mean expected behaviour is: paste content in register `+`.

**Comment by roachsinai** [comment]
And yeah current setting no need press `Ctrl-C`, you mean this?

**Comment by Yggdroot** [comment]
Do you feel any difference between `@+` and` @*`?

**Comment by roachsinai** [comment]
The differenct is in Vim, copy from outside is same. And now I think use `*` is more wise.
