### ISSUE TITLE
How to delete a buffer

### ISSUE THREAD

**Issue by createwindow** [Yggdroot/LeaderF#67]
Sometimes we don't need some buffer opened unexpectedly, how can we delete them in Buffers by LeaderF? @Yggdroot

**Comment by Yggdroot** [comment]
`:LeaderfBuffer`->`ESC`->`d`

**Comment by createwindow** [comment]
Thanks for your quick reply, and it works.

**Comment by pingsoli** [comment]
I don't get it. `<ESC>` close the buffer list window, `d` key can't be hit.

**Comment by Yggdroot** [comment]
`<ESC>` has been changed into `<tab>`.
:LeaderfBuffer->Tab->d

**Comment by pingsoli** [comment]
appreciate your reply.
`<tab>` + `d` will delete the buffer under the cursor line,  use `d` multiple times to delete the corresponding buffers. (all items' color will turn white)

It works like a charm. thanks a lot. :100:
