### ISSUE TITLE
Can i hide file name in Leaderf rg results?

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#673]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Can i hide file name in Leaderf rg results? Sometimes I want to search in current buffer, and file name is too long to bother me.

**Comment by Yggdroot** [comment]
#696 is implemented. Now you can use `--heading`.
