### ISSUE TITLE
Support using mouse to resize Leaderf windows?

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#674]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
I found that Nerdtree support to use mouse to adjust window size. It's cool if Leaderf could support that.

**Comment by Yggdroot** [comment]
switch tonormal mode, then do what you want.

**Comment by xaljer** [comment]
Thanks @Yggdroot
