### ISSUE TITLE
使用Leaderf! rg输入目录无法补全目录

### ISSUE THREAD

**Issue by UKeeySDis** [Yggdroot/LeaderF#676]
leaderf和rg配合确实很流畅。但最近使用时发现在vim命令行输入`Leaderf! rg `接目录时，按tab会有错误提示。
如图：
![image](https://user-images.githubusercontent.com/26181669/90731612-7a513600-e2fc-11ea-9bbe-c15a53ce6650.png)

**Comment by Yggdroot** [comment]
现在不支持补全路径，~ 在命令行上有特殊含义。

**Comment by UKeeySDis** [comment]
> 现在不支持补全路径，~ 在命令行上有特殊含义。

明白了，不知道搜索字符串的时候有没有更好的替代方式？如果不能补全路径全靠记忆输路径有点困难

**Comment by Yggdroot** [comment]
我一般都是在当前项目内搜索。

**Comment by UKeeySDis** [comment]
> 我一般都是在当前项目内搜索。

如果项目的目录太多了，或者是跨项目的搜索，还是可以直接指定路径会方便许多。ack和ag类似的插件都支持目录补全，并且rg本身也是支持指定目录的，但不能补全确实有点尴尬。

**Comment by Yggdroot** [comment]
实在想要这个功能可以根据自己的需求自己定义，比如：
`command! -bar -nargs=? -complete=dir LeaderfRg Leaderf rg "" <q-args>`

**Comment by UKeeySDis** [comment]
> :LeaderfRg

这样就没法指定字符了吧，只能指定目录了。
