### ISSUE TITLE
Problems when mapping <CR> to <C-T>

### ISSUE THREAD

**Issue by hao-lee** [Yggdroot/LeaderF#678]
- vim or neovim? 
    - [x] vim
- Operating system: 
    - [x] Linux
- Configurations related to LeaderF in vimrc: 

```
let g:Lf_CommandMap = {'<C-T>': ['<CR>']}
```

### Describe your question, feature request, or bug.

The default behaviour of Leaderf is:
* `<C-T>` to open in a new tabpage
* `<CR>` to open in a new buffer

I use the above config to let `<CR>` open a tabpage. It works but when I use `:tabclose` to close this tabpage, the buffer corresponding to the tabpage still exists. It seems that this commandmap works like `<C-T> + <CR>`.

**Comment by Yggdroot** [comment]
This issue is not related to LeaderF, vim works like that.

**Comment by hao-lee** [comment]
Get it. Thanks!
