### ISSUE TITLE
Feature request: auto-locate project root dir

### ISSUE THREAD

**Issue by createwindow** [Yggdroot/LeaderF#68]
GIT, SVN are probably used in our daily work. And there is a dir named .git/.svn in the root directory. By this, LeaderF can locate the project root dir automatically. It's useful sometimes. Ctrlp with ag can do this. It's great if LeaderF can do that. @Yggdroot

**Comment by Yggdroot** [comment]
This is a duplicate with issue #43 . Since so many people request for this feature, I'll add it later.

**Comment by createwindow** [comment]
great, i am looking forward that feature
