### ISSUE TITLE
nvim下用leaderf line查看有特殊符号的log文件出错pynvim.api.common.NvimError: Vim:E115: Missing quote: '

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#680]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.44
- Output of `:echo has("python3")`: 1
- Output of `:py3 print(sys.version)`: 3.7.3
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

mini_vimrc:
```
set nocompatible
set encoding=utf-8
set runtimepath^=~/.vim/plugged/LeaderF/
filetype plugin indent on
syntax on
set hidden
filetype plugin indent on
syntax enable
nnoremap fl :<C-u>Leaderf line --regex<CR>
```

### Describe your question, feature request, or bug.
打开log文件, 调用leaderf line, 输入一个字母, 出错. 附件中的log 文件只保留了出错行.
用vim能正常工作. 
![image](https://user-images.githubusercontent.com/106934/91273254-94cd5880-e7af-11ea-8682-6776945ea8cc.png)

[t.log](https://github.com/Yggdroot/LeaderF/files/5128186/t.log)

**Comment by Yggdroot** [comment]
这个问题不太好处理，^@是0，字符串一般把0作为终止符，有点麻烦。

**Comment by fcying** [comment]
vim下面没问题, 2边的处理方式不同?

**Comment by Yggdroot** [comment]
> 
> 
> vim下面没问题, 2边的处理方式不同?

vim 也有问题。

**Comment by Yggdroot** [comment]
修复了。
我是在popup模式用的，两个都有错，在非popup模式，只有nvim有错，我对比了一下代码，发现原来我曾经解决过这个问题，忘记了。

**Comment by fcying** [comment]
正常了~
