### ISSUE TITLE
about python detection

### ISSUE THREAD

**Issue by ZSaberLv0** [Yggdroot/LeaderF#681]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 7.4
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.

on my env:
* `has('python')` is 1
* `has('python2')` / `has('python3')` / `has('pythonx')` is 0

start vim and LeaderF would echo:

`LeaderF requires Vim compiled with python and/or a compatible python version.`

which caused by `!has('pythonx') && !has('python3') && !has('python2')` check

so, why `has('python2')` instead of `has('python')` ?

**Comment by Yggdroot** [comment]
It's a bug.
