### ISSUE TITLE
<C-P>预览提示错误：Unknown function: bufadd

### ISSUE THREAD

**Issue by bmeww** [Yggdroot/LeaderF#683]
- vim or neovim? 
    - [ x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
![image](https://user-images.githubusercontent.com/27851596/91394962-5f874000-e86d-11ea-9e1d-049416d0eb67.png)
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
python36.dll
- Output of `:py print(sys.version)`: 
![image](https://user-images.githubusercontent.com/27851596/91397349-108dda80-e86e-11ea-98b1-ab4724e7e0db.png)
- Output of `:py3 print(sys.version)`: 
![image](https://user-images.githubusercontent.com/27851596/91398657-19cb7700-e86f-11ea-8dda-d7e6aec049d0.png)
- Output of `:echo g:Lf_Debug_Cmd`: 
![image](https://user-images.githubusercontent.com/27851596/91398841-75960000-e86f-11ea-9897-2cc30f8f64e2.png)
- Output of `:echo g:Lf_FilesFromCache`: 
1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_PreviewInPopup = 1 
### Describe your question, feature request, or bug.
<C-P>触发预览时报错
![image](https://user-images.githubusercontent.com/27851596/91399159-0d93e980-e870-11ea-81e5-f660dd17e0e5.png)
在https://gitter.im/vim-china/Lobby上，发现有人问过该问题，解决方法是vim升级到8.1。我在ubuntu18.04上也遇到这个问题，vim版本确实是8.0。但是我win10上安装的是gvim 8.1.1，也有同样的问题。
### Steps to reproduce
1、用vundle安装LeaderF；
2、在LeaderF目录下，运行install.bash；
3、用gvim打开\LeaderF\doc\leader.txt；
4、运行：LeaderfFile，ctrl+p预览，报错。

**Comment by Yggdroot** [comment]
因为你使用了popup （`let g:Lf_PreviewInPopup = 1`），需要neovim 0.42+ or vim 8.1.1615+

**Comment by bmeww** [comment]
感谢，另外还有一个问题：安装了LeaderF以后不做任何配置，用LeaderfFile命令搜索目录，然后按ctrl+p预览，结果直接打开了一个buffer，退出Leaderf以后buffer还在。正常吗？

**Comment by Yggdroot** [comment]
这个是没有popup之前的实现，只能手动关闭。

**Comment by bmeww** [comment]
好的，谢谢！
