### ISSUE TITLE
*Question*: What is LeaderF's "default command"?

### ISSUE THREAD

**Issue by OmanF** [Yggdroot/LeaderF#684]
I would like to configure `LeaderF` to use a custom query/command (like `FZF`'s `FZF_DEFAULT_COMMAND`), however, I couldn't find the equivalent no matter how much I try.
How can I define my own command? Can I use tools other than `RipGrep` for it (e.g `find`, `fd`, etc.)?

Thanks!

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/bc1ed5291191663fa3136f29bb07b8874d1226c3/doc/leaderf.txt#L381-L413

Maybe `g:Lf_ExternalCommand` is what you want.

**Comment by OmanF** [comment]
Ah, cool, thanks.
Though I'm guessing from the text that `fd` isn't supported (yet)?
I guess I can alias `find` to `fd` if I must, though I would like to keep them separate.

Anyway, since I do have `rg`, I guess the results I'm getting are the default `rg` settings... I'll adjust those via `.ripgreprc` then.

Thanks again.
