### ISSUE TITLE
Leaderf! rg的结果能否支持也对文件路径进行模糊匹配？

### ISSUE THREAD

**Issue by UKeeySDis** [Yggdroot/LeaderF#685]
现在使用`Leaderf! rg`，结果会依次展示路径 行号 搜索结果，进行模糊匹配时只会对搜索结果进行匹配。但有时候搜索的时候能知道大概文件名是什么，但却无法进行匹配，反而得进入vim的command模式输入"/filename"进行查找。希望作者帮忙看下需要怎么调整下。
如图
![image](https://user-images.githubusercontent.com/26181669/92685046-751a6080-f369-11ea-9ed5-02c815474bf9.png)
![image](https://user-images.githubusercontent.com/26181669/92685091-86636d00-f369-11ea-98bc-638f28d74ed6.png)
如果想得到`repair.cc`那行结果，用模糊匹配搜不到。文件少一点还好，可以手动上下选择，或者进command模式去匹配，但文件一多，就比较麻烦了。

**Comment by Yggdroot** [comment]
加上`--match-path`.

**Comment by UKeeySDis** [comment]
> 加上`--match-path`.

赞！多谢
