### ISSUE TITLE
better performance when press <backspace> key and hold

### ISSUE THREAD

**Issue by chaneyzorn** [Yggdroot/LeaderF#686]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:  NVIM v0.4.4
- Output of `:echo has("python")`:  1
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`:  2.7.18
- Output of `:py3 print(sys.version)`:  3.8.5
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
" Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
" ================================================================================

" let g:Lf_WindowPosition = 'popup'
" let g:Lf_PreviewInPopup = 1

let g:Lf_UseCache = 0
let g:Lf_ShowHidden = 1
let g:Lf_HideHelp = 1
let g:Lf_WindowHeight = 0.30
let g:Lf_StlColorscheme = 'default'
let g:Lf_StlSeparator = { 'left': '', 'right': '' }
let g:Lf_CacheDirectory = expand('~/.vim/cache')

let g:Lf_RootMarkers = ['.root', '.svn', '.git', '.hg', '.idea', '.project']
let g:Lf_WildIgnore = {
    \ 'dir': ['.svn','.git','.hg', 'build', 'debug', '.idea', '.ropeproject', 'vendor'],
    \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
    \ }

let g:Lf_RgConfig = [
    \ "--glob=!node_modules/*",
    \ "--hidden",
    \]

let g:Lf_MruMaxFiles = 2048
let g:Lf_MruFileExclude = ['*.so', '*.exe', '*.py[co]', '*.sw?', '~$*', '*.bak', '*.tmp', '*.dll']

let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}

let g:Lf_NormalMap = {
    \ "File":     [["<ESC>", ':exec g:Lf_py "fileExplManager.quit()"<CR>']],
    \ "Buffer":   [["<ESC>", ':exec g:Lf_py "bufExplManager.quit()"<CR>']],
    \ "Mru":      [["<ESC>", ':exec g:Lf_py "mruExplManager.quit()"<CR>']],
    \ "Tag":      [["<ESC>", ':exec g:Lf_py "tagExplManager.quit()"<CR>']],
    \ "BufTag":   [["<ESC>", ':exec g:Lf_py "bufTagExplManager.quit()"<CR>']],
    \ "Function": [["<ESC>", ':exec g:Lf_py "functionExplManager.quit()"<CR>']],
    \ "Rg":       [["<ESC>", ':exec g:Lf_py "rgExplManager.quit()"<CR>']],
    \ }

```
### Describe your question, feature request, or bug.
wish it faster when delete chars in search bar of `:Leaderf rg` by holding `<backspace>`.

It seems like that each change in search bar will emit a seach action, during every fast keystrokes.
May it better to introduce a delay to trigger search action.
Another fuzzy search plugin `:Clap grep`  seems to have this strategy.
Wish it nice to have.

### Steps to reproduce
open LeaderF in large project and search file content with `:Leaderf rg`,  and hold `<backspace>` to delete chars.

### Actual behaviour
A bit slow to delete chars, and search result changes fast.

### Expected behaviour
delete char faster and not emit search action for each keystrokes.

**Comment by Yggdroot** [comment]
You can use ctrl-u to delete the whole pattern.

**Comment by xaljer** [comment]
@Yggdroot , I think ctrl-u is just a workaround. Leaderf does slower than other fuzzy finder such as fzf and coc-list when delete chars. This is an important for UX of fuzzy finder. It worth to be optimized.

**Comment by Yggdroot** [comment]
OK, will optimize it.
