### ISSUE TITLE
how to disable signcolumn in popup window?

### ISSUE THREAD

**Issue by chaneyzorn** [Yggdroot/LeaderF#688]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: v0.4.4
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 2.7
- Output of `:py3 print(sys.version)`: 3.8
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
set signcolumn=yes
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
```

### Describe your question, feature request, or bug.
how to disable `signcolumn` in popup window?

I need `set signcolumn=yes` for ALE code lint info. And this option makes popup window broken print,
look at the down-left corner and up-right corner of popup windows:

![image](https://user-images.githubusercontent.com/8176642/92951787-89f21380-f491-11ea-8d9a-fcc77022ea70.png)

the whole window content is pushed to right by one width of `signcolumn`.

### Steps to reproduce
```
set signcolumn=yes
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
```
and open LeaderF to search.

### Expected behaviour

not show `signcolumn` in popup window

**Comment by chaneyzorn** [comment]
```
autocmd FileType leaderf setlocal signcolumn=no
```

I get it.

And I found that all `setlocal signcolumn=no` have been commented out in `autoload/leaderf/python/leaderf/instance.py`. Anything problem?

I find the following line, but I didn't figure it out why not work in my nvim.

https://github.com/Yggdroot/LeaderF/blob/54ddcbb9bec2235d5aabe6982765ab4575e83927/autoload/leaderf/python/leaderf/instance.py#L298

**Comment by Yggdroot** [comment]
`setlocal signcolumn=no` makes vim flicker, so I removed it.

**Comment by Yggdroot** [comment]
`autocmd FileType leaderf setlocal signcolumn=no` should work now.
