### ISSUE TITLE
[typo] doc: wrong name "g:Lf_PopupHeight" in example of "g:Lf_PopupWidth"

### ISSUE THREAD

**Issue by chaneyzorn** [Yggdroot/LeaderF#689]
https://github.com/Yggdroot/LeaderF/blob/54ddcbb9bec2235d5aabe6982765ab4575e83927/doc/leaderf.txt#L749

**Comment by Yggdroot** [comment]
Thanks， will fix it later.

**Comment by Yggdroot** [comment]
Fixed, thanks.
