### ISSUE TITLE
install script problem

### ISSUE THREAD

**Issue by aceforeverd** [Yggdroot/LeaderF#69]
The install.sh suppose python is python2, which cause build fail in some distro that map python default to python3.

**Comment by Yggdroot** [comment]
What is the command of python 2 then?

**Comment by aceforeverd** [comment]
@Yggdroot I think /use/bin/python2 is more appropriate.

**Comment by Yggdroot** [comment]
Usually, python is python 2 on many environments. Your fix only fix your own issue, but may break others' usage.

**Comment by aceforeverd** [comment]
@Yggdroot so do you mean there is somewhere do not have python2? Or I can't see mime will break other's usage. 
No matter python, python2 or python3, they are all linker that link to a more specific version.
Correct me if I'm wrong. :)

**Comment by Yggdroot** [comment]
Yes, there may be somewhere do not have python2.

**Comment by aceforeverd** [comment]
OK, closing
