### ISSUE TITLE
'Leaderf gtags' cannot list python symbols except for c/c++

### ISSUE THREAD

**Issue by yslib** [Yggdroot/LeaderF#693]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.4.3
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.3
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: same as github home page

### Describe your question, feature request, or bug.

'Leaderf gtags --all' or any Leaderf commands with gtags don't list python symbols even if there are python symbols in GPATH GRTAGS GTAGS file. If there are c/c++ file in the project directory, Leaderf gtags can only list c/c++ symbols.

I used 'Leaderf gtags --update --gtagslabel native-pygments' so as to generate the tags information of python. Without --gtabslabel option, it is not able to generate symbols for python.

My gtags version is 6.6.3 on Windows. There is the same issuse on Manjaro linux with gtags 6.6.4, it generates but not lists.

**Comment by yslib** [comment]
I tested further. It looks weired.
I upgrade my gtags to 6.6.5, and compile with --with-universal-ctags and pygments isntalled. I use gtags natively by 'gtags --gtagslabel {labelpath} --gtagsconf {confpath} .', it generates the three files GPATH GTAGS GRTAGS well. But when I use 'Leaderf gtags --update --gtagslabel {labelpath} --gtagsconf {confpath} ', it generates GTAGS with no definitions so that Leaderf cannot list any symbols with no definitions(You can list referenced symbols with no definitions by adding -s options), but it generates other two files with symbols properly.

**Comment by Yggdroot** [comment]
what is the output of `echo g:Lf_Debug_GtagsCmd` after 'Leaderf gtags --all' ?
Try this command in the command line, to see what happen.

**Comment by yslib** [comment]
I had solved it somehow. I just upgraded my gtags to 6.6.5 (just released days before,and 6.6.4 can't be compiled by gcc 10)and compiled it with --with-universal-ctags=/path/to/ctags. 
As far as I know, pygments seems to do not generate definitions for python. The definitions part are generates by ctags.

Thanks all the same.
