### ISSUE TITLE
Support '--heading' option for Leaderf rg

### ISSUE THREAD

**Issue by joerideg** [Yggdroot/LeaderF#696]
Hi, 
I love this plugin, still use it every day! Thanks for your hard work!
One thing that I find really hard to read is Leaderf rg output especially in projects with deeper folder structures. 
The huge path in front of every line makes it hard to find what I'm looking for.
I understand its simply rg's output but it would be of great help if we could use the --heading option for rg. Right now it seems you set --no-heading explicitly and I cant override it using g:Lf_RgConfig. 

My output could then go from something like (similar to `rg --no-heading`):
```sh
src/app/app.module.ts:4:import { AppComponent } from './app.component';
src/app/app.component.ts:5:  templateUrl: './app.component.html',
src/app/app.component.ts:6:  styleUrls: ['./app.component.css']
src/app/app.component.spec.ts:2:import { AppComponent } from './app.component';
src/app/app.component.spec.ts:15:    const app = fixture.componentInstance;
src/app/app.component.spec.ts:21:    const app = fixture.componentInstance;
```

To (similar to `rg --heading`):
```
src/app/app.component.ts
5:  templateUrl: './app.component.html',
6:  styleUrls: ['./app.component.css']

src/app/app.component.spec.ts
2:import { AppComponent } from './app.component';
15:    const app = fixture.componentInstance;
21:    const app = fixture.componentInstance;

src/app/app.module.ts
4:import { AppComponent } from './app.component';
```
Which is just much more readable. (its also similar to CocSearch output if you are familiar with [nvim coc](https://github.com/neoclide/coc.nvim)
Would it be possible to support this?

**Comment by Yggdroot** [comment]
Added.
