### ISSUE TITLE
不能通过输入发输入中文

### ISSUE THREAD

**Issue by codekeeperjava** [Yggdroot/LeaderF#697]
无法通过输入法输入中文，输入过程中会变成英文字母，请问这种情况是输入法的问题吗？有什么好的解决方案吗？

![Sep-22-2020 19-50-13](https://user-images.githubusercontent.com/67270968/93878591-e57f9500-fd0c-11ea-915b-44f0bf5d5f28.gif)

**Comment by codekeeperjava** [comment]
刚才使用终端测试，没有出现问题。

使用 MacVim 会出现这个问题，我应该去 MacVim 提 Issue 吗？但其他比如 nerdtree, tarbar 搜索可以，当然这肯定不是一个机制。

**Comment by Yggdroot** [comment]
请参考#508.
