### ISSUE TITLE
Miss results from rg

### ISSUE THREAD

**Issue by zoumi** [Yggdroot/LeaderF#701]
os: Fedora32 64bit
gvim version:
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 31 2020 00:00:00)
Included patches: 1-1551
```

I'm searching at the root of linux source code.
When I search 'cpuinfo_max_freq' through :Leaderf rg, it shows nothing.
But if I search it through vim's commandline :!rg cpuinfo_max_freq , several results show up.

**Comment by Yggdroot** [comment]
what about 'Leaderf rg a'?

**Comment by zoumi** [comment]
![Uploading 捕获.PNG…]()

**Comment by zoumi** [comment]
I have found something:
this is the result of
```
:Leaderf rg cpuinfo_max_freq
```
![b](https://user-images.githubusercontent.com/5162901/94695241-468c1600-0368-11eb-99bd-abba054c9d90.PNG)

this is the result of:
1,press \fg to call out rg   (I have a key map:  noremap <leader>fg :Leaderf rg<CR>)
2,input cpuinfo_max_freq in the floatwindow
![a](https://user-images.githubusercontent.com/5162901/94695257-49870680-0368-11eb-847a-2760d44c06b8.PNG)

**Comment by Yggdroot** [comment]
this is because leaderf restrict the maximum number of lines to 2000000, then search from the 2000000 lines.

**Comment by zoumi** [comment]
So, what I input in the float window only filter the results from rg, not send to rg for searching?

**Comment by Yggdroot** [comment]
yes

**Comment by Yggdroot** [comment]
The recommended way to use `Leaderf rg` is `Leaderf rg xxx`.

Details can be found in https://github.com/Yggdroot/LeaderF/wiki/Leaderf-rg.
