### ISSUE TITLE
Lf_WorkingDirectoryMode not working

### ISSUE THREAD

**Issue by ccshao** [Yggdroot/LeaderF#702]
- vim or neovim? 
    - [ ] vim
    - [X] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: E319: No "python" provider found. Run...
- Output of `:py3 print(sys.version)`: 3.6.10
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
" LeaderF
let g:Lf_RootMarkers = ['.git']
let g:Lf_WorkingDirectoryMode = 'Ac'

### Describe your question, feature request, or bug.
Strangely `,f` only lists files under the current folder, but doesn't respect the `Lf_RootMarkers` setting. Pretty sure there is .git folder in the parent directory. `:Leaderf rg `also only search the current folder.

LeaderF is installed and updated with vim-plug.

**Comment by Yggdroot** [comment]
Make sure that you know the difference between `let g:Lf_WorkingDirectoryMode = 'Ac'` and `let g:Lf_WorkingDirectoryMode = 'ac'`.

**Comment by Yggdroot** [comment]
Make sure that you know the difference between `let g:Lf_WorkingDirectoryMode = 'Ac'` and `let g:Lf_WorkingDirectoryMode = 'ac'`.

**Comment by ccshao** [comment]
True, Ac works only when opening an existed file. Thanks!

**Comment by as79-alex** [comment]
It never works correctly as I see.
