### ISSUE TITLE
leadrf rg problem, error('Vim(drop):E319: 抱歉，命令在此版本中不可用: tab drop /home/bioinfo/github/leovim/settings/R.vim',)

### ISSUE THREAD

**Issue by leoatchina** [Yggdroot/LeaderF#703]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
vim-7.4.1689, install with apt in my `docker image`
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`:
1 
- Output of `:py print(sys.version)`: 
E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: 
3.5.2 (default, Jul 17 2020, 14:04:10)
[GCC 5.4.0 20160609]
- Operating system: 
    - [x] Linux unbuntu 16.04
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
https://github.com/leoatchina/leovim/blob/e12fa25f1df39e92219adcf2e4e58030a771daae/settings/fly_grep.vim#L60
### Describe your question, feature request, or bug.
I somtimes have to work on ubuntu16.04 machine without network , have to use vim7.4, but I can copy vim plugins, my config and install some debs like ripgrep.  Then I found after do `leader rg`, the result show in bottom, but I could not open the cursor focused line into tab, while the result could be opened splitedly/vsplitedly.

Accually, this problom  appeared in all `leaderf function` results if I tried to open something with ctrl-t when working with legacy vim 

### Steps to reproduce
Do `leaderf rg` in vim 7.4 ? minor version not tested 
### Actual behaviour
error('Vim(drop):E319: 抱歉，命令在此版本中不可用: tab drop /home/bioinfo/github/leovim/settings/R.vim',)
### Expected behaviour
Open in tab

**Comment by Yggdroot** [comment]
Fix 了。

**Comment by leoatchina** [comment]
Yes, well done! Thank you !!
