### ISSUE TITLE
Leaderf lose highlight after change colorscheme

### ISSUE THREAD

**Issue by roachsinai** [Yggdroot/LeaderF#707]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: gvim 8.2.1704-1
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.8.so.1.0
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.5 (default, Sep  5 2020, 10:50:12)
[GCC 10.2.0]
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

Leaderf lose highlight after change colorscheme

### Steps to reproduce

1. colorscheme one
2. Leaderf file

### Actual behaviour

Leaderf popup lose colors

### Expected behaviour

Add an `autocmd Colorscheme` to recover colors.

**Comment by Yggdroot** [comment]
This issue is caused by a bug of vim(https://github.com/vim/vim/issues/7151).

**Comment by roachsinai** [comment]
嗯嗯，修复了。感谢！
