### ISSUE TITLE
gtags hold 100% CPU forever

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#708]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
0.5
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_Gtagslabel = "native"
```
### Describe your question, feature request, or bug.
Sometimes Leaderf gtags holds 100% CPU forever updating a single file. Sometimes It even hold all 48 cores of CPU on server using many thread.
1. gtags files may have some error, `global -u` will crash.
2. Does Leaderf gtags need some timeout mechanism to handler this error case?
3. Does Leaderf gtags use multi-threads to update tag files?
4. I don't know how to locate gtags issues, any suggestion?
5. what is the better parser front end for C project? gtags native or pygments?

### Steps to reproduce
I don't know how to reproduce it.

**Comment by Yggdroot** [comment]
I think it's better if you can provide more details about how it is reproduced.

> what is the better parser front end for C project? gtags native or pygments?

gtags native

> Does Leaderf gtags use multi-threads to update tag files?

Yes, I guess the root cause may be it. Perhaps gtags can not update the database in parallel.

**Comment by xaljer** [comment]
1. I can keep watch this issue to find more details.
2. May be a option should be added for parallel behave. On the one hand, job number should be controlled to avoid hold all resources on shared server. On the other hand, It helps to locate if parallel way cause some error.

**Comment by Yggdroot** [comment]
Hope the commit can fix the issue.
