### ISSUE TITLE
能否使用绝对路径来保存MRU文件

### ISSUE THREAD

**Issue by csbde** [Yggdroot/LeaderF#71]
在使用过程中一切都非常顺利，但是，因为MRU文件保存的路径是相对路径，造成换一个目录打开vim，再召唤MRU就有可能出错。使用起来很不方便，能否用绝对路径来保存MRU文件

![deepinscreenshot_select-area_20171007103329](https://user-images.githubusercontent.com/478239/31304022-100b2fc0-aade-11e7-9dea-a194fb67ff0f.png)

**Comment by Yggdroot** [comment]
`let g:Lf_ShowRelativePath = 0`, 只显示绝对路径。
你用的是不是neovim？你说的可能出错是neovim的bug，跟issue #60 类似，vim就没问题。

**Comment by csbde** [comment]
确实是使用的neovim 。那就只能neovim更新了，我用的最新版还是这样

**Comment by csbde** [comment]
哈，显示了绝对路径后好像没有这个问题了，按照绝对路径在读取了
