### ISSUE TITLE
Bug encountered in lasted version

### ISSUE THREAD

**Issue by sillybun** [Yggdroot/LeaderF#710]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 21 2020 04:03:24)
macOS version
包含补丁: 1-1719
编译者 travis@Traviss-Mac.local
巨型版本 带 MacVim 图形界面。  可使用(+)与不可使用(-)的功能:
+acl               +file_in_path      -mouse_sysmouse    -tag_old_static
+arabic            +find_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +float             +mouse_xterm       -tcl
+autochdir         +folding           +multi_byte        +termguicolors
-autoservername    -footer            +multi_lang        +terminal
+balloon_eval      +fork()            -mzscheme          +terminfo
+balloon_eval_term +fullscreen        +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +odbeditor         +textprop
+byte_offset       +iconv             +packages          +timers
+channel           +insert_expand     +path_extra        +title
+cindent           +ipv6              +perl/dyn          +toolbar
+clientserver      +job               +persistent_undo   +transparency
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
-farsi             +mouse_sgr         +tag_binary
     系统 vimrc 文件: "$VIM/vimrc"
     用户 vimrc 文件: "$HOME/.vimrc"
 第二用户 vimrc 文件: "~/.vim/vimrc"
      用户 exrc 文件: "$HOME/.exrc"
    系统 gvimrc 文件: "$VIM/gvimrc"
    用户 gvimrc 文件: "$HOME/.gvimrc"
第二用户 gvimrc 文件: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
        系统菜单文件: "$VIMRUNTIME/menu.vim"
         $VIM 预设值: "/Applications/MacVim.app/Contents/Resources/vim"
编译方式: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -Wshadow -Werror -Wno-error=missing-field-initializers -Wno-error=deprecated-declarations -Wno-error=unused-function
链接方式: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv /usr/local/lib/libintl.a -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
`/usr/local/Frameworks/Python.framework/Versions/2.7/Python`
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
`/Library/Frameworks/Python.framework/Versions/3.8/Python`
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
```
3.8.6 (v3.8.6:db455296be, Sep 23 2020, 13:31:39)
[Clang 6.0 (clang-600.0.57)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
After I update the lasted LeaderF, everytime I open a file with vim and edit it (such as add a new line), the screen will be in wrong order and I have to type `:redraw!` to fix it.

### Steps to reproduce
```
vim a.py
edit it: add a new empty line
:w
```

then the whole screen will be in wrong place.

<img width="812" alt="image" src="https://user-images.githubusercontent.com/15951598/96898886-d2eeac00-14c2-11eb-802e-8bde9ab4c337.png">

I disable all my plugin, and find that when I disable LeaderF, everything works fine.

**Comment by Yggdroot** [comment]
```vim
vim a.py -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=~/.vim/plugged/LeaderF
    syntax enable
EOF                                    
)
```
Please try this command to see if it can be reproduced.
`~/.vim/plugged/LeaderF` needs to change to the location of your LeaderF location.

**Comment by sillybun** [comment]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/15951598/96957913-88a31480-152e-11eb-82c1-3928fb962e6c.png">

**Comment by sillybun** [comment]
I tried on both my imac and mbp. Same bug appeared.

**Comment by sillybun** [comment]
![2020-10-23 12 57 37](https://user-images.githubusercontent.com/15951598/96958226-6a89e400-152f-11eb-9951-2332fa7c1227.gif)

**Comment by sillybun** [comment]
configuration for LeaderF

```
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
" 需要安装 ripgrep: brew install ripgrep (macOS)
let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}
let g:Lf_WorkingDirectoryMode = 'a'
let g:Lf_WildIgnore = {
        \ 'dir': ['.mypy_cache', '__python__'],
        \ 'file': ['*.png', '*.jpg', '*.gif', '*.swp', '*.gif']
        \}
" let g:Lf_PreviewCode = 1
" let g:Lf_PreviewInPopup = 1
" let g:Lf_PreviewResult = {'File': 1}
" let g:Lf_PreviewPopupWidth = 100
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
" Plug 'junegunn/fzf.vim'
" nnoremap \ :Ag<Cr>
nnoremap \ :Leaderf rg<Cr>
```

**Comment by Yggdroot** [comment]
I think this is not related to LeaderF.

```vim
vim test.py -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=~/.vim/plugged/LeaderF
    syntax enable
EOF                                    
)
```

This command means:
edit test.py without loading other configuration and plugins except LeaderF. 
You should make sure that your plugins are put in ~/.vim, and LeaderF is at `~/.vim/plugged/LeaderF`, if not, change the command accordingly.

From your gif, I see you still use `vim test.py`.

I also find that seems you are using some lint plugin, please disable that plugin and have a try if you use `vim test.py`.

**Comment by Yggdroot** [comment]
set `let g:Lf_GtagsAutoUpdate = 0` and have a try.

**Comment by sillybun** [comment]
I try a minimum `.vimrc` setting:
```
if has('python3')
endif

filetype off                  " required

call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}
let g:Lf_WorkingDirectoryMode = 'a'
let g:Lf_WildIgnore = {
        \ 'dir': ['.mypy_cache', '__python__'],
        \ 'file': ['*.png', '*.jpg', '*.gif', '*.swp', '*.gif']
        \}
nnoremap \ :Leaderf rg<Cr>

call plug#end()

set nocompatible
syntax on
```

and then get the following result:

![2020-10-23 14 12 51](https://user-images.githubusercontent.com/15951598/96962750-03bdf800-153a-11eb-9028-619a6297d1c7.gif)

**Comment by sillybun** [comment]
What is the meaning of `/bin/sh: gtags: command not found?`

**Comment by ZSaberLv0** [comment]
> Maybe the reason is related to `/bin/sh: gtags: command not found`? I haven't install gtags on my computer. But it works fine with older version of LeaderF.

got the same issue, I believe it's due to the `/bin/sh: gtags: command not found` which messed up vim's drawing

**Comment by sillybun** [comment]
@ZSaberLv0 everything works fine after installing gtags on macOS using the command `brew install global`.

**Comment by sillybun** [comment]
Maybe it's better to give users a notification that `gtags` is required for currently version of LeaderF.

**Comment by Yggdroot** [comment]
gtags is not required.
This issue is caused by https://github.com/Yggdroot/LeaderF/pull/709.

**Comment by Yggdroot** [comment]
It is fixed, please update the code.

**Comment by sillybun** [comment]
WOW, thanks a lot!
