### ISSUE TITLE
查看tag时CPU占用过高

### ISSUE THREAD

**Issue by CHANTXU64** [Yggdroot/LeaderF#711]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 17 2020 21:54:53)
Included patches: 1-1704
Compiled by Arch Linux
Huge version with GTK3 GUI.
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
libpython3.8.so.1.0
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.8.6 (default, Sep 30 2020, 04:00:38)
[GCC 10.2.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
my vimrc: 
```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/LeaderF'
call plug#end()
```
另外我手动运行了LeaderF的install.sh
### Describe your question, feature request, or bug.

当使用`:LeaderfBufTagAll`或`:LeaderfFunctionAll`时，CPU占用很高，50%左右。（这仅仅只有一个文件很简单的c++文件，而且输入命令后没有任何操作）

一般打开一个小项目CPU占用会直接达到90%多，风扇很吵。

不过当按Tab键切换到普通模式后CPU占用就降下来了。

### Steps to reproduce
1. 创建一个test_lf文件夹
2. 创建一个test.cc文件，内容为: 
```
int main () { return 0; }
```
3. 使用vim在test_lf中打开test.cc
4. `:Leaderf gtags --update`
5. `:LeaderfBufTagAll`或`:LeaderfFunctionAll`
6. 使用htop查看到vim test.cc的CPU占用达50%

**Comment by Yggdroot** [comment]
使用leaderf file呢？

**Comment by CHANTXU64** [comment]
`:LeaderfFile`还好，打开那个test_lf占用13%。打开LeaderF项目占用20%。

**Comment by Yggdroot** [comment]
是一直很高还是一瞬？哪个Linux版本？

**Comment by CHANTXU64** [comment]
一直很高，没有任何操作都很高。
不过切换成普通模式就只有按j/k上下跳转的瞬间才有点高，不会一直很高。
Arch Linux version 5.8.14-arch1-1

**Comment by Yggdroot** [comment]
那就奇怪了，LeaderfFile 跟Leaderf bugtag逻辑是一样的。

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/e677d8fb38885ce60346c685be08da5ba5a7721a/autoload/leaderf/python/leaderf/cli.py#L660

把sleep的数字改大一点试一下

**Comment by CHANTXU64** [comment]
改大后有些效果，但副作用明显。
改成`time.sleep(0.01)`后CPU占用率70%。
改成`time.sleep(0.1)`后CPU占用率35%，但加载显示tag的速度变慢了很多，貌似每0.1秒才加载显示20个tag。
另外我注意到一个现象：更改`time.sleep(0.1)`后，打开一个小项目（一共有2000多个tag）后使用`:LeaderfBufTagAll`，加载显示tag时CPU占用只有10%，全部加载显示完之后CPU才会升至35%。

**Comment by Yggdroot** [comment]
你是说只有:Leaderf gtags --update
:LeaderfBufTagAll或:LeaderfFunctionAll才这样是吧，LeaderfBufTag不会？

**Comment by CHANTXU64** [comment]
`:LeaderfBufTag`或者`:LeaderfFunction`也差不多，不过情况稍微好一点，即使没有任何操作CPU占用也一直保持在：
1行c++文件，1个函数，`:LeaderfFunction`CPU占用12%
9300行js文件，400个函数，`:LeaderfFunction`CPU占用15%

**Comment by CHANTXU64** [comment]
wow，现在`:LeaderfFunctionAll`从原来90%降到了20%，好了很多，谢谢！

**Comment by heronghua** [comment]
我也遇到了  leaderffile 风扇就很响，请问怎么解决的。

**Comment by CHANTXU64** [comment]
> 我也遇到了 leaderffile 风扇就很响，请问怎么解决的。

CPU占用率多少？还有，你的电脑有没有很久没换硅脂了？当年我就发现我电脑CPU一两个核心满载一下，温度就上升到八九十度，风扇很吵，后来发现硅脂已经变成水了。换硅脂就正常了
