### ISSUE TITLE
Leaderf! rg show only filename in results or relative path

### ISSUE THREAD

**Issue by jlxz** [Yggdroot/LeaderF#714]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
command! -nargs=+ SearchNotes Leaderf! rg -e "<args>" "$HOME/iCloud/Life/"<CR>
nnoremap <leader>ss :SearchNotes<space>
```

### Describe your question, feature request, or bug.
When the command Leaderf! rg show the matches prints the full path making difficult to read and identify the matches. Is there any way/feature to print only the filenames, or a simplify path /../../../thepath/thefile.xyz or a relative path to the working directory? I couldn't find any option, neither Leaderf docs, nor RipGrep options
### Actual behaviour
![Captura de pantalla 2020-11-02 a las 14 35 41](https://user-images.githubusercontent.com/383360/97874227-fa424600-1d18-11eb-8b1f-00a78e11c638.png)

**Comment by Yggdroot** [comment]
This seems to be the convention that tool outputs absolute path if it is passed to an absolute and relative path otherwise, such as `find` that do the same.

So if you would like it to show relative path, just pass the relative path.

```vim
exec "py3 import vim, os.path"
func! GetRelativePath(path)
    let s:path = a:path
    let relpath = py3eval("os.path.relpath(vim.eval('s:path'))")
    return relpath == '.' ? '' : relpath
endf

command! -nargs=+ SearchNotes exec printf('Leaderf! rg -e "<args>" %s', GetRelativePath("$HOME/iCloud/Life/"))
nnoremap <leader>ss :SearchNotes<space>
```

**Comment by jlxz** [comment]
Thank you very much. It didn't work, at least on macOS. It seems you can't cheat rg and you actually have to execute the command in the right path so rg shows all the result from the current path as root. 
I managed to get what I want like this:
```
command! -nargs=+ SearchNotes Leaderf! rg -e "<args>" "."<CR>
nnoremap <leader>ss :lcd $HOME/iCloud/Life/<CR>:SearchNotes<space>
```
Probably not very elegant, but it works.

Thank you very much, again.

**Comment by Yggdroot** [comment]
On macOS it should work too. I don't know why, maybe you can replace py3 with py.

Anyway, close this issue.
