### ISSUE TITLE
rerun last leaderf command

### ISSUE THREAD

**Issue by ZhiyuanLck** [Yggdroot/LeaderF#717]
Is there some way to rerun or roll back to last leaderf command/window? 

For example, I use `g:Lf_Extensions` to add a `rtp` module to show runtime paths and `<enter>` will run `Leaderf file <rtp path>`, but if I want to go back to the window that shows runtime paths, I have to rerun `Leaderf rtp`.

It will be nice if there are some maps like `<Plug>(PrevLeaderf)` and `<Plug>(NextLeaderf)` to navigate historical calls of leaderf commands.

**Comment by Yggdroot** [comment]
`Leaderf {cmd} --recall` recall the last state of cmd.
`Leaderf --recall` recall the last state of the last used cmd.

So in your case, You can use `Leaderf rtp --recall` or `Leaderf --recall`.
`

**Comment by ZhiyuanLck** [comment]
Thanks, is it possible to maintain a calling list just like a buffer list and recall these commands by `LeaderfPrev` and `LeaderfNext` like `bp` and `bn`. May it be an useful feature?

**Comment by Yggdroot** [comment]
I don't think it is necessary. In my opinion it is more efficient to run a specific command directly.
