### ISSUE TITLE
项目名包含连接线时报错“global: GPATH not found”

### ISSUE THREAD

**Issue by chenghua-root** [Yggdroot/LeaderF#718]
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 25 2020 09:13:18)
CentOS Linux release 7.4.1708

使用了Lf_CacheDirectory配置。
当项目名包含连接线"-"时，提示“global: GPATH not found”。
修改项目名（去掉连接线）后，则使用正常。

问题：当使用了Lf_CacheDirectory配置，项目名中包含连接线"-"时，Leaderf gtags无法正确运行？

**Comment by Yggdroot** [comment]
你怎么配置的？

**Comment by chenghua-root** [comment]
> 你怎么配置的？

是我使用的问题。已解决。多谢！
