### ISSUE TITLE
hg files输出带着文件大小，导致无法打开文件

### ISSUE THREAD

**Issue by Renxiuhu** [Yggdroot/LeaderF#72]
对于hg的代码库，使用hg files建立索引是在文件相对路径前会携带文件的大小，如下：
  123534 vobs/dsl/a.cpp

这么会导致回车后要打开的文件名变成了“ 123534 vobs/dsl/a.cpp”， 而真正的文件名应该是“vobs/dsl/a.cpp”，从而导致文件无法打开，而是新建了一个名为“ 123534 vobs/dsl/a.cpp”的文件

**Comment by Yggdroot** [comment]
我在hg的代码库下使用`hg files` 不会出现文件大小，
可能我理解的不太对，能把你使用的具体步骤说一下吗？

**Comment by Renxiuhu** [comment]
找到原因了，是.hgrc中verbose = True导致的。
