### ISSUE TITLE
calling g:Lf_ShortcutF return "NameError: name 'anyHub' is not defined"

### ISSUE THREAD

**Issue by machun-china** [Yggdroot/LeaderF#720]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 18 2020 07:56:56)
Included patches: 1-592
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
python38.dll
- Output of `:py print(sys.version)`: 
Could not laod library python27.dll
Sorry, this command is disabled, the Python library could not be loaded
- Output of `:py3 print(sys.version)`: 
3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
E121: Undefined variable: g:Lf_FilesFromCache
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 1
let g:Lf_IgnoreCurrentBufferName = 1
" popup mode
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }

let g:Lf_ShortcutF = "<leader>lf"
let g:Lf_ShortcutB = "<leader>lb"
noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>

noremap <leader>lm :LeaderfMru<cr>
noremap <F3> :LeaderfFunction!<cr>
"noremap <leader>fb :LeaderfBuffer<cr>
noremap <F4> :LeaderfTag<cr>

let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
let g:Lf_ShowRelativePath = 0
let g:Lf_StlColorscheme = 'powerline'
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
noremap go :<C-U>Leaderf! rg --recall<CR>
let g:Lf_GtagsAutoGenerate = 0
let g:Lf_Gtagslabel = 'native-pygments'
noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>

### Describe your question, feature request, or bug.
Recently I used Plug to upgrade all Plugins. Afer that error happened
When calling g:Lf_ShortcutF in gvim (already opened a file in a git repo), the following error printed:
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line      1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'anyHub' is not defined
Press ENTER or type command to continue
### Steps to reproduce
1. open a file in git repo
2. use hotkey to call g:Lf_ShortcutF. Then error will happen

**Comment by Yggdroot** [comment]
I can not reproduce this issue. Please fresh install the plugin and have a try.

**Comment by machun-china** [comment]
Sorry for raising this issue. After updating Plug and retry, the error gone.
