### ISSUE TITLE
Show error. Mac os x & neovim 0.4.4

### ISSUE THREAD

**Issue by orlandoxu** [Yggdroot/LeaderF#721]
yes

- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.4.4
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_WindowPosition = 'popup'

### Describe your question, feature request, or bug.
See png file.
![Uploading image.png…]()

**Comment by orlandoxu** [comment]
![image](https://user-images.githubusercontent.com/8287723/98456335-585aa780-21b7-11eb-9da6-2233ef9c0c78.png)

**Comment by Yggdroot** [comment]
Show icons (should install fonts from https://github.com/ryanoasis/nerd-fonts)

Support commands: buffer,file,mru,window

" Show icons, icons are shown by default
let g:Lf_ShowDevIcons = 1
" For GUI vim, the icon font can be specify like this, for example
let g:Lf_DevIconsFont = "DroidSansMono Nerd Font Mono"
" If needs
set ambiwidth=double

**Comment by orlandoxu** [comment]
> Show icons (should install fonts from https://github.com/ryanoasis/nerd-fonts)
> 
> Support commands: buffer,file,mru,window
> 
> " Show icons, icons are shown by default
> let g:Lf_ShowDevIcons = 1
> " For GUI vim, the icon font can be specify like this, for example
> let g:Lf_DevIconsFont = "DroidSansMono Nerd Font Mono"
> " If needs
> set ambiwidth=double

Ok. Thx!!!
