### ISSUE TITLE
冲突，LeaderF和NERDTree

### ISSUE THREAD

**Issue by orlandoxu** [Yggdroot/LeaderF#722]
如果buffer是在NERDTree里面，打开LeaderF之后，新的文件会在nerdTree中打开。
可以在vimrc中通过
![image](https://user-images.githubusercontent.com/8287723/98461516-a4254500-21e7-11eb-8cf9-12214edfccc0.png)
上面代码绕过。
上面解决方案在只有一个buffer的时候，会有副作用。
期望结果：如果是在NERDTree中，希望在新的buffer中打开。

**Comment by Yggdroot** [comment]
我觉得可以通过写点代码来实现你的要求，只是你的需求我不是很清楚。

**Comment by Yggdroot** [comment]
就是你想在哪打开，就把光标跳到哪里，再调用leaderf

**Comment by orlandoxu** [comment]
好的，收到。只是建议哈，😁

**Comment by Yggdroot** [comment]
我不是很清楚你说的什么副作用，我觉得可以这样：
比如：
```vim
func! BeforeStartingLeaderF()
  if bufname() =~# '^NERD_tree_'
    跳到想要打开的窗口
  endif
endf

nnoremap <C-P> :BeforeStartingLeaderF()<CR>:LeaderfFile<CR>
```
