### ISSUE TITLE
custom callback function

### ISSUE THREAD

**Issue by ZhiyuanLck** [Yggdroot/LeaderF#723]
'g:Lf_Extensions' makes it possible for writting custom extensions, but it is hard to  change the callback function of `cli.input()` with only vim or even with python.

If I want to change the content by some other rules (not the result of fuzzy match),  it seems that I need to rewrite the whole member function `_workInIdle` of class `Manager`, is there some way to make it easier for customizing callback function?

**Comment by Yggdroot** [comment]
No.

What do you want to do exactly?

**Comment by ZhiyuanLck** [comment]
Well, I want to write a color panel with leaderf, and have done it, thanks your code anyway.
