### ISSUE TITLE
something wrong when repeating opening one file using LeaderfFile

### ISSUE THREAD

**Issue by wyg1997** [Yggdroot/LeaderF#724]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
  ```
  VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 18 2020 18:29:15)
  ```
- Output of `:echo has("python")`: 
  ```
  0
  ```
- Output of `:echo has("python3")`: 
  ```
  1
  ```
- Output of `:echo &pythondll`(only vim, not neovim): Nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim): Nothing
- Output of `:py print(sys.version)`: 
  ```
  E319: Sorry, the command is not available in this version
  ```
- Output of `:py3 print(sys.version)`: 
  ```
  3.6.9 (default, Jul 17 2020, 12:50:27)
  [GCC 8.4.0]
  ```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
  ```
  " LeaderF
  nnoremap <leader>f :LeaderfFile .<cr>
  let g:Lf_WildIgnore = {
              \ 'dir': ['.svn','.git','.hg','.vscode','.wine','.deepinwine','.oh-my-zsh'],
              \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
              \}
  let g:Lf_UseCache = 0
  ```

### Describe your question, feature request, or bug.

When re-open the file which has opened using `LeaderfFile`, it will show: 

```
File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 855, in _acceptSelection^@    lfDrop('', file)^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/l
eaderf/utils.py", line 194, in lfDrop^@    lfCmd("keepj hide drop %s" % escSpecial(file_name))^@vim.error: Vim(drop):E319: Sorry, the command is not available in this version: keepj hide drop
/root/work/codes/oneflow/oneflow/user/ops/relu_op.cpp
```

### Steps to reproduce

Re-open the file which has opened in the vim using `LeaderfFile`.

### Actual behaviour

Show the info: 

```
File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 855, in _acceptSelection^@    lfDrop('', file)^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/l
eaderf/utils.py", line 194, in lfDrop^@    lfCmd("keepj hide drop %s" % escSpecial(file_name))^@vim.error: Vim(drop):E319: Sorry, the command is not available in this version: keepj hide drop
/root/work/codes/oneflow/oneflow/user/ops/relu_op.cpp
```

**Comment by Yggdroot** [comment]
What is the output of `exists(':drop')` ?

**Comment by wyg1997** [comment]
> echo exists(':drop')

2

**Comment by Yggdroot** [comment]
It's weird that `:drop` command exists but vim still report E319.

`keepj hide drop /root/work/codes/oneflow/oneflow/user/ops/relu_op.cpp` try this command to see what will happen.

**Comment by wyg1997** [comment]
> `keepj hide drop /root/work/codes/oneflow/oneflow/user/ops/relu_op.cpp` try this command to see what will happen.

E319: Sorry, the command is not available in this version

**Comment by Yggdroot** [comment]
I also reproduced this issue.

**Comment by Yggdroot** [comment]
Fixed.
