### ISSUE TITLE
使用第三方扩展开启preview时会crash

### ISSUE THREAD

**Issue by jheroy** [Yggdroot/LeaderF#726]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  9 2020 14:22:30)
macOS version
Included patches: 1-1955
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 

- Output of `:echo &pythonthreedll`(only vim, not neovim): 

- Output of `:py print(sys.version)`: 

- Output of `:py3 print(sys.version)`: 
3.9.0 (default, Oct 27 2020, 14:15:17)
[Clang 12.0.0 (clang-1200.0.32.21)]  

- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_PreviewResult = {
    \ 'File': 0,
    \ 'Buffer': 0,
    \ 'Mru': 0,
    \ 'Tag': 0,
    \ 'BufTag': 1,
    \ 'Function': 1,
    \ 'Line': 1,
    \ 'Colorscheme': 0,
    \ 'Rg': 1,
    \ 'floaterm': 1,
    \ 'commit': 1,
    \ 'Gtags': 0
    \}

### Describe your question, feature request, or bug.
用第三方插件的时候比如 Leaderf-floaterm, Leaderf-git, 如果开启了preview就会报如下错误：
File "/Users/wenhuxian/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 678, in input^@    callback()^@  File "/Users/wenhuxian/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 70, in deco^@    func(se
lf, *args, **kwargs)^@  File "/Users/wenhuxian/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2302, in _workInIdle^@    self._previewResult(False)^@  File "/Users/wenhuxian/.vim/bundle/LeaderF/autoload/leaderf/python
/leaderf/manager.py", line 385, in _previewResult^@    self._previewInPopup(line)^@  File "/Users/wenhuxian/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 382, in _previewInPopup^@    filename = lfBytes2Str(filename)
^@  File "/Users/wenhuxian/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/utils.py", line 41, in lfBytes2Str^@    return bytes.decode(locale.getdefaultlocale()[1])^@AttributeError: 'int' object has no attribute 'decode'

不开启preview可以正常使用

**Comment by jheroy** [comment]
我通过以下改动临时解决了， 但是不知道是否会引发其他问题，目前来说对我使用没有影响了
diff --git a/autoload/leaderf/python/leaderf/anyExpl.py b/autoload/leaderf/python/leaderf/anyExpl.py
index 9baab58..bc061f8 100644
--- a/autoload/leaderf/python/leaderf/anyExpl.py
+++ b/autoload/leaderf/python/leaderf/anyExpl.py
@@ -379,13 +379,15 @@ class AnyExplManager(Manager):
                 if result:
                     filename, line_num, jump_cmd = result
                     if not self._has_nvim:  # py3 in nvim return str, in vim return bytes
-                        filename = lfBytes2Str(filename)
+                        if isinstance(filename, bytes):
+                            filename = lfBytes2Str(filename)
                     # for backward compatibility
-                    if isinstance(filename, int): # it is a buffer number
-                        if lfEval("bufloaded(%d)" % filename) != '1':
-                            filename = vim.buffers[filename].name
-                    elif lfEval("bufloaded('%s')" % escQuote(filename)) == '1':
-                        filename = int(lfEval("bufnr('%s')" % escQuote(filename))) # actually, it's a buffer number
+                    # if isinstance(filename, int): # it is a buffer number
+                    #     if lfEval("bufloaded(%d)" % filename) != '1':
+                    #         raise Exception(lfEval("bufloaded(%d)" % filename))
+                    #         filename = vim.buffers[filename].name
+                    # if lfEval("bufloaded('%s')" % escQuote(filename)) == '1':
+                    #     filename = int(lfEval("bufnr('%s')" % escQuote(filename))) # actually, it's a buffer number
                     self._createPopupPreview("", filename, line_num, lfBytes2Str(jump_cmd) if not self._has_nvim else jump_cmd)
             except vim.error as err:
                 raise Exception("Error occurred in user defined %s: %s" % (str(preview), err))

**Comment by Yggdroot** [comment]
修复了。
