### ISSUE TITLE
Change the color of LeaderF

### ISSUE THREAD

**Issue by MCotocel** [Yggdroot/LeaderF#730]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.5.0-ad56527
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
2.7.16 (default, Oct 30 2020, 02:15:49)
[GCC Apple LLVM 12.0.0 (clang-1200.0.30.4) [+internal-os, ptrauth-isa=sign+stri  
- Output of `:py3 print(sys.version)`: 
3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23)
[Clang 6.0 (clang-600.0.57)]
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`let g:Lf_WindowPosition = 'popup'`
### Describe your question, feature request, or bug.

Is it possible to change the color of LeaderF? Right now it's brown, and I'd like to change it to blend in with my color scheme.

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/71439440a07cdd670dff7d6f969cc4d53b27d832/doc/leaderf.txt#L823-L858

or you can follow https://github.com/Yggdroot/LeaderF/blob/master/autoload/leaderf/colorscheme/popup/gruvbox_default.vim to define your own colorscheme and put it under `autoload/leaderf/colorscheme/popup/`

**Comment by MCotocel** [comment]
Thank you!
