### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#732]
Win10+gVIM8.0(支持Python)  复现步骤如下

1、执行命令Leaderf rg --nowrap --belowright --stayOpen

2、随便搜索一个字符串 此处为“main” 弹出了预览窗口

3、然后按下Tab切换到正常模式 这样可以在底部窗口上下移动 这样预览窗口里面也跟着会变化 到这一步都是完美的

4、用鼠标双击第六项 这时候预览窗口消失 第6行对应的文件出现在正常的窗口中

5、此处鼠标焦点在上面的窗口 现在我移动到底部窗口 然后开始移动鼠标的时候 这个时候就报错了 (正常情况应该是回到第2步 )

录制了一个GIF动画如下：

![FSbsqeYb54](https://user-images.githubusercontent.com/6241431/100069743-0af75f00-2e74-11eb-818f-6c2d20615532.gif)

**Comment by Yggdroot** [comment]
奇怪，我复现不了。
动图里你又点到第四行做了其他的操作没？

**Comment by Yggdroot** [comment]
> 然后开始移动鼠标的时候 这个时候就报错了

移动鼠标不应该触发什么操作呀

**Comment by gVimer** [comment]
> 奇怪，我复现不了。
> 动图里你又点到第四行做了其他的操作没？
没什么操作 就是鼠标双击第四行 想打开第四行对应的文件进行编辑其中的内容

**Comment by gVimer** [comment]
> > 然后开始移动鼠标的时候 这个时候就报错了
> 
> 移动鼠标不应该触发什么操作呀

这个时候应该是插件试着去打开预览窗口

**Comment by gVimer** [comment]
希望能解决下这个问题 因为在VIM搜索字符串啥的 我现在都是自己用RG命令去搜索的 如果这个问题解决了 我就直接用插件里面封装的命令去搜索 这样更好 
建议 
![Dingtalk_20201125085448](https://user-images.githubusercontent.com/6241431/100168268-e5ae3380-2efb-11eb-87aa-cbae886a9914.jpg)
就是鼠标在“搜索结果”(Leaderf rg --nowrap --belowright --stayOpen)窗口中移动的时候 对应行的文件会会出现在预览窗口中 能不能加个选项 就是可以不在预览窗口中打开 而是直接在编辑窗口中打开

**Comment by Yggdroot** [comment]
> > > 然后开始移动鼠标的时候 这个时候就报错了
> > 
> > 
> > 移动鼠标不应该触发什么操作呀
> 
> 不好意思 是我描述不准确 我是用按键去移动光标所在行 这个时候应该是插件试着去打开预览窗口 预览光标对应行的文件

几种情况我都试过了，复现不了，能否帮忙调试一下，在https://github.com/Yggdroot/LeaderF/blob/71439440a07cdd670dff7d6f969cc4d53b27d832/autoload/leaderf/python/leaderf/rgExpl.py#L918 这一行下面打印一下 file, line_num 的值？

**Comment by Yggdroot** [comment]
> 能不能加个选项 就是可以不在预览窗口中打开 而是直接在编辑窗口中打开 且 焦点依然保留在 “搜索结果“ 窗口中


let g:Lf_PreviewInPopup = 0应该就可以了

**Comment by gVimer** [comment]
> > > > 然后开始移动鼠标的时候 这个时候就报错了
> > > 
> > > 
> > > 移动鼠标不应该触发什么操作呀
> > 
> > 
> > 不好意思 是我描述不准确 我是用按键去移动光标所在行 这个时候应该是插件试着去打开预览窗口 预览光标对应行的文件
> 
> 几种情况我都试过了，复现不了，能否帮忙调试一下，在
> 
> https://github.com/Yggdroot/LeaderF/blob/71439440a07cdd670dff7d6f969cc4d53b27d832/autoload/leaderf/python/leaderf/rgExpl.py#L918
> 
> 这一行下面打印一下 file, line_num 的值？
能把打印的代码发出来吗 这个我不熟

**Comment by Yggdroot** [comment]
直接print (file, line_num) 就可以，添加后看看出错时输出啥

**Comment by gVimer** [comment]
哦 我以为这样打出来的VIM中无法直接看到
![Dingtalk_20201125093357](https://user-images.githubusercontent.com/6241431/100170783-60c61880-2f01-11eb-9424-92ebc7cfa068.jpg)

**Comment by Yggdroot** [comment]
再在下面打印一下os.path.exists(lfDecode(file))看看

**Comment by gVimer** [comment]
> 再在下面打印一下os.path.exists(lfDecode(file))看看

False

**Comment by Yggdroot** [comment]
> > 再在下面打印一下os.path.exists(lfDecode(file))看看
> 
> False

这里不应该是FALSE才对，你是不是有autocmd改不了pwd？再打印一下os. getcwd ()

**Comment by gVimer** [comment]
确实改变了 但是我鼠标双击 搜索结果窗口 的时候能打开对应的文件啊  
我的文件都在E 打印的路径在C盘根目录了

**Comment by Yggdroot** [comment]
看看你配置了什么autocmd？

**Comment by gVimer** [comment]
没有啊  所有的autocmd如下 另外我设置了这个 set autochdir  "自动切换当前目录为工作目录
![Dingtalk_20201125095015](https://user-images.githubusercontent.com/6241431/100172622-b13e7580-2f03-11eb-96f3-7f0ec971bf3c.jpg)

**Comment by Yggdroot** [comment]
把set autochdir禁掉试一下

**Comment by gVimer** [comment]
好了好了 多谢大神了

**Comment by gVimer** [comment]
大神可以考虑贴个二维码出来 便于打赏

**Comment by Yggdroot** [comment]
> 大神可以考虑贴个二维码出来 便于打赏

😊

**Comment by gVimer** [comment]
> > > 再在下面打印一下os.path.exists(lfDecode(file))看看
> > 
> > 
> > False
> 
> 这里不应该是FALSE才对，你是不是有autocmd改变了pwd？再打印一下os. getcwd ()

我用self._getInstance().getCwd()打印是OK的 也就是虽然我设置了chdir 但是实际上这上面的操作中并没有改变工作目录 通过os. getcwd ()获取的是Python获取的工作目录 本来就跟Vim中的不一样 所以 认为这个地方还是有BUG的 跟set autochdir没有关系 大神怎么看

**Comment by Yggdroot** [comment]
os. getcwd ()是真的，self._getInstance().getCwd()是我为了fix一个路径问题实现的，我看看怎么在设了autochdir的情况下不报错。

**Comment by gVimer** [comment]
![Dingtalk_20201126192743](https://user-images.githubusercontent.com/6241431/100345586-7df00980-301d-11eb-9b80-9aefdd2edc71.jpg)
能加个选项吗？就是在bottom模式下+不显示预览窗口的情况下 用方向键在“搜索结果窗口”中移动光标的时候,能够自动显示在"可编辑窗口"中 
现在是在打开预览窗口的时候是自动显示在预览窗口的 我想关闭预览窗口选项后可直接显示在“可编辑窗口"中

**Comment by Yggdroot** [comment]
let g:Lf_PreviewInPopup = 0 就可以吧

**Comment by gVimer** [comment]
> let g:Lf_PreviewInPopup = 0 就可以吧

多谢 确实可以 我以为是在let g:Lf_PreviewResult中设置了

**Comment by Yggdroot** [comment]
不用单独加个选项。可以定义两个map，bottom模式let g:Lf_PreviewInPopup = 0，popup模式，let g:Lf_PreviewInPopup = 1

**Comment by gVimer** [comment]
能具体说下不 不知道怎么监听这两个模式 文档里面也没看见

**Comment by Yggdroot** [comment]
比如： `map  <F7> :let g:Lf_PreviewInPopup = 0<CR>:Leaderf rg --bottom <CR>`

**Comment by gVimer** [comment]
> 比如： `map <F7> :let g:Lf_PreviewInPopup = 0<CR>:Leaderf rg --bottom <CR>`

多谢
