### ISSUE TITLE
:LeaderfTag doesn't preview tag in pop up window

### ISSUE THREAD

**Issue by kongjun18** [Yggdroot/LeaderF#734]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.5.0-a6bd52d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/usr/local/src/neovim/build/config -I/usr/local/src/neovim/src -I/usr/local/src/neovim/.deps/usr/include -I/usr/include -I/usr/local/src/neovim/build/src/nvim/auto -I/usr/local/src/neovim/build/include
编译者 root@Friday

Features: +acl +iconv +tui
See ":help feature-compile"
```
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
```
3.9.0 (default, Oct  6 2020, 00:00:00)
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```
- Output of `:py3 print(sys.version)`: 
```
3.9.0 (default, Oct  6 2020, 00:00:00)
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PopupHeight = 0.3
let g:Lf_DefaultExternalTool = 'fd'
let g:Lf_ExternalCommand = 'fd -E _builds --type f "%s"'     
let g:Lf_PreviewCode = 1
let g:Lf_PreviewResult = {
			\ 'File': 0,
			\ 'Buffer': 0,
			\ 'Mru': 0,
			\ 'Tag': 1,
			\ 'BufTag': 1,
			\ 'Function': 1,
			\ 'Line': 0,
			\ 'Colorscheme': 0,
			\ 'Rg': 1,
			\ 'Gtags': 1
			\}
let g:Lf_CtagsFuncOpts = {
        \ 'c': ' --c-kinds=fp --exclude=_builds --exclude=doc',
        \ 'cpp': '--c++-kinds=fp --exclude=_builds --exclude=doc',
        \ 'rust': ' --rust-kinds=f --exclude=doc',
        \ }
let g:Lf_RootMarkers = ['.root', '.git', '.pro', 'Cargo.toml']
let g:Lf_WorkingDirectoryMode = 'A'      
```
### Describe your question, feature request, or bug.
I set `g:Lf_PreviewResult.Tag` to `1`, but `:LeaderfTag` doesn't preview tag in pop up window.

I clear my init.vim and only retain the configuration of Leaderf. But it not fix the problem.

ctags version:
```
Universal Ctags 0.0.0(e0a976d7), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Dec 16 2019, 17:58:44
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +iconv, +option-directory, +xpath, +json, +interactive, +yaml, +packcc
```
### Steps to reproduce
Just use my configuration and open C file in any project.
### Actual behaviour
`:LeaderTag` doesn't preview tag in pop up window.
![Screenshot_20201201_161117](https://user-images.githubusercontent.com/44012232/100713854-e826f680-33ef-11eb-8c98-33a1c23f4bfe.png)

### Expected behaviour
`:LeaderTag` previews tag in pop up window.

**Comment by Yggdroot** [comment]
Done.
