### ISSUE TITLE
Leaderf for cmake support

### ISSUE THREAD

**Issue by etorth** [Yggdroot/LeaderF#737]
Everything works correctly, this is a new feature request.
When using ctrl-p, in the build dir I can directly search for the src dir, but this is not supported by leaderf.

Can leaderf support this?
i.e., the source dir is /home/xxx/repo, the build dir is /home/xxx/build.

Then in /home/xxx/build, vim ctrl-p can search files in /home/xxx/repo

**Comment by Yggdroot** [comment]
Is XXX a git repository or something like that?
Please `:h g:Lf_WorkingDirectoryMode`

**Comment by etorth** [comment]
xxx is my user name, but yes this is a case for git.
like: git clone https://github.come/etorth/x.git

then the repo dir: /home/etorth/x
if I build the repo at: /home/etorth/build by:

```shell
cd /home/etorth/build
cmake ../x
vim -c mak
```

when some line fails the compilation, vim can stop at the error line.
and ctrl-p can accurately find the /home/etorth/x as the root for file finding.

I think it just detected some files in /home/etorth/build to find the correct path automatically, no need to specifcally config.

**Comment by Yggdroot** [comment]
You can use `LeaderfFile ../x`.

**Comment by etorth** [comment]
Can you please give us some automation for this?

**Comment by Yggdroot** [comment]
```vim
let g:Lf_RootMarkers = ['build']
let g:Lf_WorkingDirectoryMode = 'ac'
```

**Comment by etorth** [comment]
I added this, ugly but looks working for now:

```shell
" cmake support for LeaderF
" find the configured source dir: https://stackoverflow.com/questions/27188786/find-source-directory-from-build-directory-in-cmake
if filereadable("CMakeCache.txt")
    for line in readfile("CMakeCache.txt")
        let foundDirLine = matchstr(line, '.*_SOURCE_DIR:STATIC=.*')
        let foundDir = matchstr(foundDirLine, '/.*')
        if !empty(foundDir)
            let g:Lf_WorkingDirectory = foundDir
        endif
    endfor
endif
```
