### ISSUE TITLE
Only show directories / folders when I press `<leader>f`

### ISSUE THREAD

**Issue by paul-pen** [Yggdroot/LeaderF#738]
It can work normally for the first few days.
But now, It only show directories  when I press `<leader>f`,  do not show files under folders. 

![bug](https://user-images.githubusercontent.com/63177004/102156713-165d0980-3eb9-11eb-80b2-f1b5af1a53e5.png)

**Comment by Yggdroot** [comment]
What is the Output of `:echo g:Lf_Debug_Cmd`?

**Comment by paul-pen** [comment]
E121: undefined variable g:Lf_Debug_Cmd

**Comment by paul-pen** [comment]
> What is the Output of `:echo g:Lf_Debug_Cmd`?
E121: undefined variable g:Lf_Debug_Cmd

**Comment by Yggdroot** [comment]
run after pressing `<leader>f`.

**Comment by paul-pen** [comment]
git ls-files  "." && git ls-files --others --exclude-standard  "."

A few days ago, I installed git lfs.

**Comment by Yggdroot** [comment]
`let g:Lf_UseVersionControlTool = 0`

**Comment by paul-pen** [comment]
Done! Thanks.
