### ISSUE TITLE
Since LeaderF update, vim crashes when using `hg commit`

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#74]
## What happened?

When I try to commit with Mercurial, vim crashes and it only happen if LeaderF is enabled. Here is the output of the crash (I can't copy/paste because the mouse is broken as well after this crash).

![hg-vim-leaderf-crash](https://user-images.githubusercontent.com/6382548/31634351-31d82526-b291-11e7-83fe-c7682d2258a1.png)

## How to reproduce?

1. Take the config files .vimrc and .hgrc
2. Create or get a Mercurial repository
   (see "Quick Start" section at https://www.mercurial-scm.org/)
3. Change a file
4. Type `hg commit`
5. => Crash

If you comment LeaderF in .vimrc, then `hg commit` works again.

## Workaround

Use nano in Mercurial instead of vim.

## Versions

**LeaderF:**
master (b5489be9316257697b374265fe780b196d778bdf)

**OS:**
OSX 10.12.6

**Vim:**
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 11 2017 12:59:58)
MacOS X (unix) version
Included patches: 1-1175
Compiled by Homebrew

**Mercurial:**
4.3.2

## Configs

**~/.hgrc**

```
[ui]
username = User Name <username@domain.com>
editor = vim
```

**~/.vimrc**

```
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Yggdroot/LeaderF'

" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required
```

**Comment by Yggdroot** [comment]
I don't think this issue is related to LeaderF.
Many same issues here:
https://github.com/Miserlou/Zappa/issues/854
https://teamtreehouse.com/community/importerror-bad-magic-number-in-time-bx03xf3rn
https://github.com/neovim/neovim/issues/3085
https://stackoverflow.com/questions/514371/whats-the-bad-magic-number-error
hope these can help.

**Comment by MightyCreak** [comment]
As suggested in the links, I deleted all the *.pyc I could find in my home dir, but no luck.
Then I deleted all the *.pyc in `/ `(which kinda broke my machine, so I reinstalled python 2 and 3 and all their modules, using pip2 and pip3), I made it work again, but the error on `hg commit` is still here.

What is weird is that here is the list of Vundle modules I have:
```Plugin 'tpope/vim-sensible'
Plugin 'editorconfig/editorconfig-vim'

Plugin 'Yggdroot/LeaderF'
Plugin 'qpkorr/vim-bufkill'
Plugin 'derekwyatt/vim-fswitch'
Plugin 'mileszs/ack.vim'

Plugin 'scrooloose/nerdcommenter'
```

And if I comment out just LeaderF, then everything works again. Maybe it's because no other module is using python... I don't know.

I'll try with previous versions of LeaderF, to see if all this is coming from LeaderF or the recent hg upgrade. (but if it comes from the recent hg upgrade, how come it works if I remove LeaderF?)

**Comment by MightyCreak** [comment]
Well, even with a previous version of LeaderF, I still have the problem, so it must come from MacVim, or Python, or Hg. For now I'll use nano as my hg editor.

Closing the issue.
Thanks!

**Comment by Yggdroot** [comment]
@MightyCreak I find the root cause. The vim you are using when hg commit is not the same as that you usually use. You can check by `:echo $VIMRUNTIME`.
You can solve it like this:
~/.hgrc
```
[ui]
username = User Name <username@domain.com>
editor = /the absolute path/of/vim
```
or
~/.bashrc
```
export EDITOR=/the absolute path/of/vim
```
mine is `export EDITOR=/Applications/MacVim.app/Contents/MacOS/Vim`
