### ISSUE TITLE
[Feature Request] Help to alternate between header and implementation file in CPP

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#740]
Hi,

Currently I use `fswitch` plugin to help alternate between the `.h` and `.cpp` files. But it just only searches within the same folder. Could `LeaderF` take this functionality up?

I wonder if we could:

1. First look into opened buffers to find the file;
1. Then look into the same folder;
2. If not found, do a search using keyword `xxxxx.cpp` to check;
    1. If there is only one match, jump to it directly;
    2. Otherwise, stay in the search result list and let user choose.

Thank you for your great plugin!

**Comment by Yggdroot** [comment]
I think LeaderF aleady has the feature. 
If your current file is xxx.cpp, then launch Leaderf file, xxx.h would be on the top.

**Comment by Yggdroot** [comment]
Please refer to #295 .

**Comment by tamlok** [comment]
OK! Thank you! It is usable, though we need to wait for the result and do another extra key press.
