### ISSUE TITLE
fatal: Not a git repository (or any parent up to mount point /data11)^@stopping at filesystem

### ISSUE THREAD

**Issue by Jason-WT** [Yggdroot/LeaderF#744]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 26 2020 03:33:16)
Included patches: 1-2211
Compiled by wutong.1995@n115-204-021
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            -gettext           -netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
-clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShowDevIcons = 0
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_ShortcutF = "<C-P>"
" noremap <C-L> :<C-U><C-R>=printf("Leaderf! rg -ie ")<CR>
let g:Lf_ShowDevIcons = 0
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_ShortcutF = "<C-P>"
" noremap <C-L> :<C-U><C-R>=printf("Leaderf! rg -ie ")<CR>
noremap <C-L> :<C-U><C-R>=printf("Leaderf! rg -ie %s ", expand("<cword>"))<CR> 79 noremap <C-L> :<C-U><C-R>=printf("Leaderf! rg -ie %s ", expand("<cword>"))<CR>

### Describe your question, feature request, or bug.
vim version 8.2.2211
File "\~/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 678, in input^@    callback()^@  File "\~/.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 70, in deco^@    func(self, *args, **kwargs)^@  File "\~.vim/bundle/LeaderF/autoload/leaderf/python/leaderf/manager.p
y", line 2320, in _workInIdle^@    raise self._read_content_exception[1]^@Exception: fatal: Not a git repository (or any parent up to mount point /data11)^@Stopping at filesystem
 boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

### Steps to reproduce
vim 
ctrl + p
### Actual behaviour
leaderf file 
### Expected behaviour
without exception

**Comment by Yggdroot** [comment]
`let g:Lf_UseVersionControlTool = 0` may fix this issue.

I think this issue is because that your project is not under control by git but there is a `.git` directory under the root of your project.

**Comment by Jason-WT** [comment]
> `let g:Lf_UseVersionControlTool = 0` may fix this issue.
> 
> I think this issue is because that your project is not under control by git but there is a `.git` directory under the root of your project.

Thank you very much!! solve it !!
One more question: Is there a param in leaderf file to exclude some directories when search file?

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/97b62cf112c599ea4dc17441a85f11473431c46b/doc/leaderf.txt#L139-L163
