### ISSUE TITLE
Pressing "Tab" several times causes Leaderf to Quite unexpectedly.

### ISSUE THREAD

**Issue by einthusan** [Yggdroot/LeaderF#746]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 22 2020 23:44:34)
macOS version
Included patches: 1-1719
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      -mouse_sysmouse    -tag_old_static
+arabic            +find_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +float             +mouse_xterm       +tcl
+autochdir         +folding           +multi_byte        +termguicolors
-autoservername    -footer            +multi_lang        +terminal
+balloon_eval      +fork()            -mzscheme          +terminfo
+balloon_eval_term +fullscreen        +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +odbeditor         +textprop
+byte_offset       +iconv             +packages          +timers
+channel           +insert_expand     +path_extra        +title
+cindent           +ipv6              +perl              +toolbar
+clientserver      +job               +persistent_undo   +transparency
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
-farsi             +mouse_sgr         +tag_binary        
```
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_PopupHeight = 0.6
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_ShowDevIcons = 0
let g:Lf_WildIgnore = { 'dir': [], 'file': ['z-*.go'] }
let g:Lf_DefaultExternalTool = 'find'
```

### Describe your question, feature request, or bug.
The problem is that when I press Tab to go back and forth between command prompt and results window, LeaderF sometimes quits unexpectedly. Can be reproduce every single time, regardless of the speed at which I toggle between Normal and Insert mode of LeaderF.

### Steps to reproduce
1. enter the command `:LeaderF file --popup` to open LeaderF popup window.
2. Repeatedly press `Tab` like 10 times. LeaderF quits.

### Actual behaviour
LeaderF quits.

### Expected behaviour
Should cycle between command prompt and results window without ever quitting.

**Comment by Yggdroot** [comment]
This issue only happens on MacOS, maybe it is a bug of macvim.

**Comment by einthusan** [comment]
commenting out this particular line in `File.vim` within the `elseif key ==# "i" || key ==? "<Tab>"` check stops this problem from happening .. in other words, some code inside this `input()` function. Any pointers so maybe I can put a workaround or something? Really would like to fix it.

`exec g:Lf_py "fileExplManager.input()`

**Comment by einthusan** [comment]
more specifically, its within this call.
```
lfCmd("call leaderf#ResetPopupOptions(%d, 'filter', '%s')" % (self._getInstance().getPopupWinId(),
                                'leaderf#%s#NormalModeFilter' % self._getExplorer().getStlCategory()))
```

**Comment by einthusan** [comment]
maybe its related to coc variables used in LeaderF? even though I do not use coc and I have disabled all plugins completely.
https://github.com/liuchengxu/vista.vim/issues/149

**Comment by einthusan** [comment]
I found a good lead for you!
In `manager.py`, the line `elif equal(cmd, '<Tab>'):   # switch to Normal mode` has a `break` at the end of it. When I delete this break statement, you will see the popup doesn't close unexpectedly. However, there is indeed a bug in LeaderF .. I do not believe this is a vim bug anymore! Please look into it.

**Comment by Yggdroot** [comment]
This issue may be caused by https://github.com/vim/vim/issues/7178 , please update your vim.

**Comment by Yggdroot** [comment]
Confirmed, after I update vim to version 8.2.2100, the issue does not show up any more.

**Comment by einthusan** [comment]
Thanks!
