### ISSUE TITLE
从输入模式到正常模式的时候 搜索框里面的内容会整体向右移动一下

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#747]
WIN10+GVIM8.2
![DF9oxdtOvf](https://user-images.githubusercontent.com/6241431/103448867-81407a00-4cda-11eb-841d-710f505d2cf8.gif)
不知道是不是BUG 体验不是很好 哈哈

**Comment by gVimer** [comment]
顺便说下 能不能考虑跟COC集成啊 FZF已经这样做了 https://github.com/antoinemadec/coc-fzf 你说过的 LeaderF比FZF优秀的 
而且COC是以后必不可少的插件

**Comment by Yggdroot** [comment]
set numberwidth=8应该就可以了。

大致看了下，感觉相当于把每个source重新写一遍，没那个时间。

**Comment by gVimer** [comment]
设置了 set numberwidth=8 还是会有移动的情况出现

**Comment by Yggdroot** [comment]
非popup模式应该可以。
这个问题只有将就一下了，因为输入模式时，整个buffer最多200行，当normal模式时，结果有多少行整个buffer就有多少行，行号列变宽了。

**Comment by gVimer** [comment]
原来如此 好的
