### ISSUE TITLE
有考虑支持Everything的非GUI程序ES.EXE的吗

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#748]
这个大佬已经做了 但是有问题 打开文件的位置不对等等 看 能不能集成到官方
https://github.com/voldikss/LeaderF-everything

**Comment by gVimer** [comment]
http://jdev.tw/blog/6141/es-with-fzf 已经做了 里面有ES.EXE的下载链接

**Comment by Yggdroot** [comment]
> 这个大佬已经做了 但是有问题 打开文件的位置不对等等 看 能不能集成到官方
> https://github.com/voldikss/LeaderF-everything

如果问题不大可以给他提issue。

**Comment by gVimer** [comment]
![image](https://user-images.githubusercontent.com/6241431/103456298-b1663800-4d2f-11eb-89f7-3c95766a462f.png)
不支持提啊

**Comment by Yggdroot** [comment]
@voldikss 不支持提issue？

**Comment by voldikss** [comment]
这个的实现特别糊，有个朋友临时需要所以我才做的。抱歉但是我已经没精力维护了。

**Comment by gVimer** [comment]
哈哈 要不要考虑合到Leaderf上来啊

**Comment by voldikss** [comment]
其实不建议合到 Leaderf

1. 我的实现很乱，不好合
2. 这个我的看法是做成第三方扩展更好点，毕竟需求估计是少数而且比较特别

你可以参考一下我的内容自己改一下

**Comment by gVimer** [comment]
我不会合 看上面大佬有没有时间弄吧 感觉还是挺有用的 我经常用Everything搜索文件 然后在VIM中打开 
我喜欢把任何文本文件都拖到VIM中来打开 可能在非WIN下很少这样操作

**Comment by Yggdroot** [comment]
> 我不会合 看上面大佬有没有时间弄吧 感觉还是挺有用的 我经常用Everything搜索文件 然后在VIM中打开
> 我喜欢把任何文本文件都拖到VIM中来打开 可能在非WIN下很少这样操作

es的命令行用熟的话，写个leaderf的扩展很容易的

**Comment by gVimer** [comment]
好的 我试着在上面做些修改看吧

**Comment by gVimer** [comment]
做了些修改 可以用了 但是有个问题就是 ES每次都要重新去索引 不能从缓存中读取 所以每次
都要等一会儿 而且还不是异步的  这样还不如直接用EveryThing了
 但是我又找到了一个直接用EveryThing的
https://github.com/Aborres/vim-everything
这个完善一下还是不错的
