### ISSUE TITLE
Cursor Blink not worked on Ubuntu 20.04

### ISSUE THREAD

**Issue by stark-zhang** [Yggdroot/LeaderF#749]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:  8.2.0716
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`: 1 
- Output of `:echo &pythondll`(only vim, not neovim):  none
- Output of `:echo &pythonthreedll`(only vim, not neovim):  none
- Output of `:py print(sys.version)`:  no python2
- Output of `:py3 print(sys.version)`: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_CursorBlink = 1
```
### Describe your question, feature request, or bug.
as title said, cursor blink not worked.

**Comment by Yggdroot** [comment]
I don't have a Ubuntu environment.

**Comment by stark-zhang** [comment]
OK, could you tell me how to debug? I met this bug on RHEL, too.

**Comment by Yggdroot** [comment]
I  don't know. are you sure that g:Lf_CursorBlink is 1.

**Comment by stark-zhang** [comment]
yes, I am sure that, and output of `echo g:Lf_CursorBlink` is `1`.

**Comment by Yggdroot** [comment]
Does all the other functionality work well?

**Comment by Yggdroot** [comment]
Could you provide a minimal-vimrc and the steps to reproduce please?
In theory, if it's a bug, it should happen on all OS.

**Comment by stark-zhang** [comment]
the minimal vimrc is following:
```
call plug#begin($HOME.'/.vim/plugged')
Plug 'Yggdroot/LeaderF', { 'do': 'install.sh' }
call plug#end()

let g:Lf_CursorBlink = 1 
```

other functionality works well, and this bug occurs in every interactive function of Leaderf.

**Comment by Yggdroot** [comment]
can not reproduce.
