### ISSUE TITLE
can not find pygments_parser.py

### ISSUE THREAD

**Issue by zombo** [Yggdroot/LeaderF#750]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim):  python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim):  python38.dll
- Output of `:py print(sys.version)`: 2.7.15
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1

" Show icons, icons are shown by default
let g:Lf_ShowDevIcons = 1
" For GUI vim, the icon font can be specify like this, for example
let g:Lf_DevIconsFont = "SauceCodePro NF"
" If needs
set ambiwidth=double

" popup mode
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }

let g:Lf_RootMarkers = ['.git', '.svn']
let g:Lf_GtagsAutoGenerate = 1
let g:Lf_Gtagsconf = 'd:/software/gtags/share/gtags/gtags.conf'
let g:Lf_Ctags = 'd:/software/gtags/bin/gtags.exe'
let g:Lf_Gtagslabel = 'native-pygments'
let g:Lf_GtagsSkipUnreadable = 1
let g:Lf_WildIgnore = {
       \ 'dir': ['.svn','.git','.hg'],
       \ 'file': ['*.sw?','~$*','*.bak','*.exe','dll','lib', 'pdb', 'sdf', 'pch', 'class', 'doc', 'docx', 'xls', 'xlsx', 'pdf', '*.o','*.so','*.py[co]']
       \}
let g:Lf_ShortcutF = "<leader>lf"
"noremap <Leader>lf :<C-U><C-R>=printf("LeaderfFile")<CR>
"noremap <Leader>lb :<C-U><C-R>=printf("LeaderfBuffer")<CR>
"noremap <Leader>lg :<C-U><C-R>=printf("LeaderfBufTag")<CR>
"noremap <Leader>lt :<C-U><C-R>=printf("LeaderfTag")<CR>
"noremap <Leader>lu :<C-U><C-R>=printf("LeaderfFunction")<CR>
"noremap <Leader>lm :<C-U><C-R>=printf("LeaderfMru")<CR>
"noremap <Leader>ll :<C-U><C-R>=printf("LeaderfLine")<CR>

noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
noremap <leader>fg :<C-U><C-R>=printf("LeaderfTag %s", "")<CR><CR>
noremap <leader>ff :<C-U><C-R>=printf("LeaderfFunction %s", "")<CR><CR>

noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <leader>fu :<C-U><C-R>=printf("Leaderf! gtags --update")<CR><CR>
noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>

" search word under cursor, the pattern is treated as regex, and enter normal mode directly
noremap <Leader>rf :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>

" search word under cursor, the pattern is treated as regex,
" append the result to previous search results.
noremap <Leader>rg :<C-U><C-R>=printf("Leaderf! rg --append -e %s ", expand("<cword>"))<CR>

" search word under cursor literally only in current buffer
noremap <Leader>rb :<C-U><C-R>=printf("Leaderf! rg -F --current-buffer -e %s ", expand("<cword>"))<CR>

" search word under cursor literally in all listed buffers
noremap <Leader>rd :<C-U><C-R>=printf("Leaderf! rg -F --all-buffers -e %s ", expand("<cword>"))<CR>

" search visually selected text literally, don't quit LeaderF after accepting an entry
xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F --stayOpen -e %s ", leaderf#Rg#visual())<CR>

" recall last search. If the result window is closed, reopen it.
noremap go :<C-U>Leaderf! rg --recall<CR>

" search word under cursor in *.h and *.cpp files.
noremap <Leader>rs :<C-U><C-R>=printf("Leaderf! rg -e %s --type-add \"src:include:cpp,java,py,md,log\" -t src ", expand("<cword>"))<CR>

### Describe your question, feature request, or bug.

python: can't open file 'd:\edu\vim\vim82\../share/gtags/script/pygments_parser.py' : [Errno 2] no such file or directory

**Comment by Yggdroot** [comment]
pip install pygments

**Comment by zombo** [comment]
> 
> 
> pip install pygments

I have installed pygments. 
The problem is error path. 

> python: can't open file 'd:\edu\vim\vim82../share/gtags/script/pygments_parser.py' : [Errno 2] no such file or directory

The correct problem is d:/software/gtags/share/gtags/script/pygments_parser.py. 

So, leaderF could not find the script because the path was combined errorneously.

**Comment by Yggdroot** [comment]
**Steps to reproduce**
