### ISSUE TITLE
[Feature] Allow fd to be used instead of find

### ISSUE THREAD

**Issue by einthusan** [Yggdroot/LeaderF#751]
This is `fd`, a faster `find` that allows regexp as well. It seems to be much much faster. Would you make it so that if `fd` is found, it will automatically use that instead of `find`, for those who have set external command to `find`?
https://github.com/sharkdp/fd

**Comment by Yggdroot** [comment]
You can use `g:Lf_ExternalCommand`.

https://github.com/Yggdroot/LeaderF/blob/880888469193a6bf020376bab098a7401a06e445/doc/leaderf.txt#L402-L413

**Comment by einthusan** [comment]
thanks!
