### ISSUE TITLE
Leaderf rg 能忽略指定的文件吗

### ISSUE THREAD

**Issue by huanglei104** [Yggdroot/LeaderF#752]
默认不要搜索二进制文件，或者可以配置一个忽略列表

**Comment by Yggdroot** [comment]
可以，rg本身就可以，具体可以参考rg的帮助。

https://github.com/Yggdroot/LeaderF/blob/97b62cf112c599ea4dc17441a85f11473431c46b/doc/leaderf.txt#L582-L592

可以把命令行选项配置在这个里面。
