### ISSUE TITLE
Rq:增加Popup窗口中的按键回调以自定义快捷键打开文件

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#753]
我自己给Leaderf谢了显示收藏的文件和文件夹的扩展 
![image](https://user-images.githubusercontent.com/6241431/103727009-2928b100-5015-11eb-9dcd-909b265f2eb1.png)
显示效果如下
![image](https://user-images.githubusercontent.com/6241431/103727291-e1565980-5015-11eb-8cbd-78dd7be4da66.png)

因为列表很多的时候 希望在“正常“模式监听按键来打开对应的文件或者文件夹

就是增加自定义的Popup创建时候的参数filter

**Comment by Yggdroot** [comment]
有点麻烦。

**Comment by gVimer** [comment]
就是告诉我按下了那个键 然后剩下的事情自己处理
