### ISSUE TITLE
无法退出搜索窗口，按enter后无法跳转

### ISSUE THREAD

**Issue by xlxyearning** [Yggdroot/LeaderF#755]
vim版本：8.2
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl              +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save

vim中输入：Leaderf function后输入函数名称，然后按回车按钮后卡住，只能通过Ctrl-C退出。

**Comment by xlxyearning** [comment]
在C++代码中可以调整，在python文件中会卡住。

**Comment by Yggdroot** [comment]
请提供一个mini-vimrc以便复现。

**Comment by xlxyearning** [comment]
> 请提供一个mini-vimrc以便复现。

谢谢回复，我用的https://github.com/amix/vimrc，个人的配置如下：
set number
set mouse=a

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Colorscheme
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syntax on
set nocompatible
let g:airline_theme = 'onedark'
let g:lightline = {
    \ 'colorcheme': 'onedark',
    \ }
colorscheme onedark

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => YouCompleteMe
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:ycm_python_interpreter_path = '/home/xlx/anaconda3/bin/envs/tf24/bin/python'
let g:ycm_python_sys_path = []
let g:ycm_extra_conf_vim_data = [
    \ 'g:ycm_python_interpreter_path',
    \ 'g:ycm_python_sys_path'
    \]
let g:ycm_global_ycm_extra_conf = '~/.ycm_extra_conf.py'

let g:ycm_confirm_extra_conf = 0
let g:ycm_complete_in_comments = 0
let g:ycm_add_preview_to_completeopt = 0
let g:ycm_show_diagnostics_ui = 0
let g:ycm_server_log_level = 'info'
let g:ycm_min_num_identifier_candidate_chars = 2
let g:ycm_collect_identifiers_from_comments_and_strings = 1
let g:ycm_complete_in_strings=1
let g:ycm_key_invoke_completion = '<M-;>'
set completeopt=menu,menuone,preview

let g:ycm_semantic_triggers =  {
			\ 'c,cpp,python,java,go,erlang,perl': ['re!\w{2}'],
			\ 'cs,lua,javascript': ['re!\w{2}'],
			\ }
" let g:ycm_key_list_select_completion = ['<TAB>', '<Down>', '<Enter>']
let g:ycm_key_list_select_completion = ['<c-n>', '<Down>', '<Enter>']
let g:ycm_filetype_whitelist = {
			\ "c":1,
			\ "cpp":1,
			\ "objc":1,
			\ "sh":1,
			\ "zsh":1,
            \ "python":1,
			\ }
nnoremap <leader>gl :YcmCompleter GoToDeclaration<CR>
nnoremap <leader>gf :YcmCompleter GoToDefinition<CR>
nnoremap <leader>gg :YcmCompleter GoToDefinitionElseDeclaration<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => vim-snippets
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:snips_author = "xlx_yearning"
let g:snips_email = "xxlacd1005@gmail.com"

let g:ultisnips_python_style = 'google'
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => 调试运行
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"C，C++ 按F5编译运行
map <F5> :call CompileRunGcc()<CR>
func! CompileRunGcc()
    exec "w"
    if &filetype == 'c'
       exec "!gcc % -o %<"
       exec "! ./%<"
    elseif &filetype == 'cpp'
       exec "!g++ % -o %<"
       exec "! ./%<"
    elseif &filetype == 'java'
        exec "!javac %"
        exec "!java %<"
    elseif &filetype == 'sh'
         :!./%
    elseif &filetype == 'python'
        exec "!time python %"
    endif
endfunc

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => leaderfunction
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let $GTAGSLABEL = 'native-pygments'
let $GTAGSCONF = '/usr/local/share/gtags/gtags.conf'

noremap <F2> :LeaderfFunction!<cr>
"文件搜索
nnoremap <silent> <Leader>f :Leaderf file<CR>
"历史打开过的文件
nnoremap <silent> <Leader>m :Leaderf mru<CR>
"Buffer
nnoremap <silent> <Leader>b :Leaderf buffer<CR>
"函数搜索（仅当前文件里）
nnoremap <silent> <Leader>F :Leaderf function<CR>
"模糊搜索，很强大的功能，迅速秒搜
nnoremap <silent> <Leader>rg :Leaderf rg<CR>

**Comment by Yggdroot** [comment]
你提供的这个都没有安装插件的代码，很明显不是完整的vimrc。
初步判断可能是跟你的哪个配置或插件冲突了，因为这是个最基本的功能，不可能有问题。

用
```vim
vim -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=/path/to/LeaderF
    syntax enable
    
EOF
)
```
把/path/to/LeaderF 改为LeaderF所在的路径

看看能不能复现，不能复现说明不是Leaderf的问题。

**Comment by xlxyearning** [comment]
> 你提供的这个都没有安装插件的代码，很明显不是完整的vimrc。
> 初步判断可能是跟你的哪个配置或插件冲突了，因为这是个最基本的功能，不可能有问题。
> 
> 用
> 
> ```viml
> vim -Nu <(cat <<'EOF'
>     set rtp-=~/.vim
>     set rtp-=~/.vim/after
>     set rtp^=/path/to/LeaderF
>     syntax enable
>     
> EOF
> )
> ```
> 
> 把/path/to/LeaderF 改为LeaderF所在的路径
> 
> 看看能不能复现，不能复现说明不是Leaderf的问题。

安装方式用的pythogen，我贴出来的只是自己增加的插件及配置信息，其他的都是https://github.com/amix/vimrc中自带的，配置文件内容比较多，我没贴过来，如果你那边需要复现，麻烦到我提供链接下载。
cpp代码下功能正常，python代码按enter后依然卡住，需要ctrl-c后 按enter退出，错误栈如下：

处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/manager.py", line 2265, in startExplorer
    self.input()
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/manager.py", line 2542, in input
    if self.accept() is None:
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/manager.py", line 1865, in accept
    self._getInstance().exitBuffer()
  File "/home/xlx/.vim_runtime/my_plugins/leaderf/autoload/leaderf/python/leaderf/instance.py", line 1057, in exitBuffer
    lfCmd("silent! hide")
KeyboardInterrupt
请按 ENTER 或其它命令继续

**Comment by Yggdroot** [comment]
你是说用
```
vim -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=/path/to/LeaderF
    syntax enable
    
EOF
)
```
依然如此？

**Comment by xlxyearning** [comment]
> 你是说用
> 
> ```
> vim -Nu <(cat <<'EOF'
>     set rtp-=~/.vim
>     set rtp-=~/.vim/after
>     set rtp^=/path/to/LeaderF
>     syntax enable
>     
> EOF
> )
> ```
> 
> 依然如此？

谢谢回复。
用你提供的命令结果是一致的，.cpp文件可以正常跳转，.py文件不行（可以进行函数搜索等，但按enter卡住，无法跳转），这个『enter』跟配置或插件有关？

**Comment by Yggdroot** [comment]
用上面这个是只加载leaderf插件，没有任何配置，按理说不应该有问题了呀。
你是怎么用的？
这样进入vim后，打开你那个py文件，再执行leaderffunction吗？

**Comment by xlxyearning** [comment]
> 用上面这个是只加载leaderf插件，没有任何配置，按理说不应该有问题了呀。
> 你是怎么用的？
> 这样进入vim后，打开你那个py文件，再执行leaderffunction吗？

命令如下：
1、vim -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=/mypath/to/LeaderF
    syntax enable
    
EOF
)  test.cpp，然后输入：『:Leaderf mru』可以跳转
2、vim -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=/mypath/to/LeaderF
    syntax enable
    
EOF
)  test.py，然后输入：『:Leaderf mru』可以使用，但无法enter跳转

我的vim是自己编译的

**Comment by Yggdroot** [comment]
太奇怪了，你的vim版本多少？
在其他机器上试试？

**Comment by xlxyearning** [comment]
> 太奇怪了，你的vim版本多少？
> 在其他机器上试试？

好的，谢谢了。
我再试下吧，vim版本是8.2.1412。

**Comment by Yggdroot** [comment]
我用8.2.1412也试了，也没问题。
不管打开cpp还是打开py，LeaderF的跑到的代码都是一样的，委实奇怪。
