### ISSUE TITLE
how to specify the python edition

### ISSUE THREAD

**Issue by foxerfly** [Yggdroot/LeaderF#758]
my vim is compiled by python35  ,and i set python39 in the win10's enviroment settings,

when lanched the vim,it  pops up a dialog,warning  LeaderF requires Vim compiled with python and/or a compatible 
python version.

is there anyway to specify the python35 in the vimrc for leaderf

plz help,very appreciate.

**Comment by Yggdroot** [comment]
set pythonthreedll=path to your python dll
