### ISSUE TITLE
vim + python3 + leaderf + Gtags, will have a zombie process [global] <defunct>, need change asyncExecutor.py to fix it

### ISSUE THREAD

**Issue by co0l1ce** [Yggdroot/LeaderF#759]
- vim or neovim? 
    - [ ] vim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python3")`: 
    - [ ] Linux

### Describe your question, feature request, or bug.
when use " :Leaderf! gtags -d functions --auto-jump", after run this command, will have a zombie process like:
123909    1548 31926  0 16:22 ?        00:00:00 [global] <defunct>
123909    6431 31926  0 16:22 ?        00:00:00 [global] <defunct>

I google the solutions,  In the asyncExecutor.py files, we user the subprocess.Popen to run global command

after run, we read the output and close it, but in the same time, we need call poll() to get the subprocess‘s status and signal

I use the follow patch to fix it

```diff
@@ -111,6 +111,7 @@ class AsyncExecutor(object):
                         if self._process:
                             self._process.stdout.close()
                             self._process.stderr.close()
+                            self._process.poll()
                     except IOError:
                         pass

@@ -158,6 +159,7 @@ class AsyncExecutor(object):
                         if self._process:
                             self._process.stdout.close()
                             self._process.stderr.close()
+                            self._process.poll()
                     except IOError:
                         pass

```

**Comment by Yggdroot** [comment]
I haven't met this issue. Could you show me the solution that you googled please?

**Comment by co0l1ce** [comment]
I use vim + python2 has no problem
I use vim + python3 + Mac has no problem

centos + vim8 + python3  has problem， I am not sure this config will must meet

https://stackoverflow.com/questions/2760652/how-to-kill-or-avoid-zombie-processes-with-subprocess-module
this is i google’s result

**Comment by Yggdroot** [comment]
Thanks.
