### ISSUE TITLE
Lf_Wildignore not respecting a simple *.png

### ISSUE THREAD

**Issue by shmup** [Yggdroot/LeaderF#76]
I'm probably overlooking something! I added `*.png` alongside the defaults mentioned in the docs, and I'm stilling seeing pngs. I'm probably doing something wrong, yeah?

Quite simply: 

![image](https://user-images.githubusercontent.com/118710/31675856-d3a7071c-b333-11e7-9c10-5826d0acfd97.png)

**Comment by shmup** [comment]
Oh, perhaps it doesn't ignore files watched in source control.

**Comment by Yggdroot** [comment]
This issue is a duplicate with issue #53. If the source is under control by git, `Lf_Wildignore` is ignored.
If under hg control, `Lf_Wildignore`  will work as you expected.
