### ISSUE TITLE
stayOpen使用情况下，输入栏高度异常

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#760]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 22 2020 23:02:19)
MS-Windows 64-bit GUI version 带 OLE 支持
包含补丁: 1-2195
编译者 appveyor@APPVYR-WIN
巨型版本 带图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +eval               +multi_byte_ime/dyn -tag_old_static
+arabic             +ex_extra           +multi_lang         -tag_any_white
+autocmd            +extra_search       +mzscheme/dyn       +tcl/dyn
+autochdir          -farsi              +netbeans_intg      -termguicolors
+autoservername     +file_in_path       +num64              +terminal
+balloon_eval       +find_in_path       +ole                -termresponse
-balloon_eval_term  +float              +packages           +textobjects
+browse             +folding            +path_extra         +textprop
++builtin_terms     -footer             +perl/dyn           -tgetent
+byte_offset        +gettext/dyn        +persistent_undo    +timers
+channel            -hangul_input       +popupwin           +title
+cindent            +iconv/dyn          -postscript         +toolbar
+clientserver       +insert_expand      +printer            +user_commands
+clipboard          +ipv6               +profile            +vartabs
+cmdline_compl      +job                +python/dyn         +vertsplit
+cmdline_hist       +jumplist           +python3/dyn        +virtualedit
+cmdline_info       +keymap             +quickfix           +visual
+comments           +lambda             +reltime            +visualextra
+conceal            +langmap            +rightleft          +viminfo
+cryptv             +libcall            +ruby/dyn           +vreplace
+cscope             +linebreak          +scrollbind         -vtp
+cursorbind         +lispindent         +signs              +wildignore
+cursorshape        +listcmds           +smartindent        +wildmenu
+dialog_con_gui     +localmap           +sound              +windows
+diff               +lua/dyn            +spell              +writebackup
+digraphs           +menu               +startuptime        -xfontset
+directx            +mksession          +statusline         -xim
-dnd                +modify_fname       -sun_workshop       +xpm_w32
-ebcdic             +mouse              +syntax             -xterm_save
+emacs_tags         +mouseshape         +tag_binary         
     系统 vimrc 文件: "$VIM\vimrc"
     用户 vimrc 文件: "$HOME\_vimrc"
 第二用户 vimrc 文件: "$HOME\vimfiles\vimrc"
 第三用户 vimrc 文件: "$VIM\_vimrc"
      用户 exrc 文件: "$HOME\_exrc"
  第二用户 exrc 文件: "$VIM\_exrc"
    系统 gvimrc 文件: "$VIM\gvimrc"
    用户 gvimrc 文件: "$HOME\_gvimrc"
第二用户 gvimrc 文件: "$HOME\vimfiles\gvimrc"
第三用户 gvimrc 文件: "$VIM\_gvimrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
        系统菜单文件: "$VIMRUNTIME\menu.vim"
编译方式: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE 
-DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6   
-DFEAT_XPM_W32   -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /source-charset:utf-8 /MP 
-DHAVE_STDINT_H /Ox /GL -DNDEBUG  /Zl /MT /D_CRT_SECURE_NO_DEPRECATE 
/D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME 
-DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI 
-DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_TCL -DDYNAMIC_TCL -DDYNAMIC_TCL_DLL=\"tcl86
t.dll\" -DDYNAMIC_TCL_VER=\"8.6\" -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua53.dll\" 
-DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 
-DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python38.dll\" -DFEAT_MZSCHEME -I 
"C:\Program Files\Racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME 
-DDYNAMIC_MZSCH_DLL=\"libracket3m_a36fs8.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_a36fs8.dll\
" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL 
-DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64
-msvcrt-ruby240.dll\" -DRUBY_VERSION=24 -DFEAT_HUGE /Fd.\ObjGXOULYHTRZAMD64/ /Zi
链接方式: link  /nologo /opt:ref /LTCG:STATUS /HIGHENTROPYVA:NO oldnames.lib kernel32.lib 
advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib 
version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64  libcmt.lib 
oleaut32.lib user32.lib  /nodefaultlib:lua53.lib  /STACK:8388608  /nodefaultlib:python27.lib 
/nodefaultlib:python38.lib   "C:\Tcl\lib\tclstub86.lib" winmm.lib WSock32.lib Ws2_32.lib 
xpm\x64\lib-vc14\libXpm.lib /PDB:gvim.pdb -debug
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python38.dll
- Output of `:py print(sys.version)`: E370 无法加载
- Output of `:py3 print(sys.version)`: 3.8.7 xxxxxxxxxxxxxxxx
- Output of `:echo g:Lf_Debug_Cmd`: 未定义变量
- Output of `:echo g:Lf_FilesFromCache`: 未定义变量
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
- 
let g:Lf_Gtagslabel = 'native-pygments' " gtags 默认 C/C++/Java 等六种原生支持的代码直接使用 gtags 本地分析器，而其他语言使用 pygments 模块
let g:Lf_Gtagsconf = 'D:\programs\glo663wb\share\gtags\gtags.conf' " gtags.conf路径
" 自动生成Gtags
let g:Lf_GtagsAutoGenerate = 1
" 从下向上展示内容 popup场景下无效
let g:Lf_ReverseOrder = 1
" 限制输出的行长度，否则会卡死
let g:Lf_RgConfig = [ "--max-columns=150", ]
" 索引存储位置
let g:Lf_CacheDirectory = 'D:\programs'
" 弹出窗口展示内容
"let g:Lf_WindowPosition = 'popup'
" 自动调整LeaderF窗口大小
"let g:Lf_AutoResize = 1

" 取消<leader>f 和 <leader>b的绑定，避免干扰下面的key绑定
let g:Lf_ShortcutF = ''
let g:Lf_ShortcutB = ''
nnoremap <leader>fi :Leaderf --nameOnly file<CR>
nnoremap <leader>mr :Leaderf mru<CR>
nnoremap <leader>fu :Leaderf --stayOpen --left --nowrap function<CR>
nnoremap <leader>rg :Leaderf rg<CR>
nnoremap <leader>bu :Leaderf buffer<CR>
nnoremap <leader>bt :Leaderf bufTag<CR>
nnoremap <leader>g :<C-U><C-R>=printf("Leaderf! gtags --by-context --literal --auto-jump --result ctags-mod %s", "")<CR><CR>
nnoremap <leader>li :Leaderf line<CR>
### Describe your question, feature request, or bug.
非popup下，开启stayOpen选项，使用--left 或--right参数，输入过滤字符后，窗口表现异常，输入栏会变得很大

抱歉，网络限制，无法上传图片
### Actual behaviour
输入栏高度很大，代码窗口高度为1
### Expected behaviour
输入栏高度为1，代码窗口高度正常

**Comment by Yggdroot** [comment]
这个我复现不了，你执行的这个命令`nnoremap fu :Leaderf --stayOpen --left --nowrap function`?
```vim
vim -Nu <(cat <<'EOF'
    set rtp-=~/.vim
    set rtp-=~/.vim/after
    set rtp^=/mypath/to/LeaderF
    syntax enable
    
EOF
) 
```
用这个命令，把相关的命令写到syntax enable下面，/mypath/to/LeaderF 改成LeaderF真正的目录。
看看能不能复现，把步骤写下来。

**Comment by MerliniKing** [comment]
我也不明白为啥突然无法复现了，暂时先关闭该问题
