### ISSUE TITLE
Feature Request: display :Leaderf tag in the format of :LeaderfBufTagAll

### ISSUE THREAD

**Issue by kongjun18** [Yggdroot/LeaderF#761]
The output of `:Leaderf tag` is not very pretty. Could you add an option to display `:Leaderf tag` like `:LeaderfBufTagAll`?

**Comment by Yggdroot** [comment]
The output of `:Leaderf tag ` is from tags, usually the tags is very large, formatting it will take tool long to tolerate.

**Comment by kongjun18** [comment]
OK, I see. Thanks for your reply!
