### ISSUE TITLE
Window height can not be auto fit content when using '--heading' option in Leaderf rg

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#764]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
nvim 0.5.0-dev+950
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`let g:Lf_ReverseOrder = 1`

### Describe your question, feature request, or bug.
Is this behave by design?

### Steps to reproduce
`Leaderf! rg --match-path --wd-mode Ac -heading -w -e text`

### Actual behaviour
fixed window height.

### Expected behaviour
window height is auto resized to fit actual content.

**Comment by Yggdroot** [comment]
Yes, it's by design. If `--heading` is present, `let g:Lf_ReverseOrder = 1`  will not take effect. Auto adjust the height only happen if `let g:Lf_ReverseOrder = 1` takes effect.

**Comment by xaljer** [comment]
OK, thanks.
