### ISSUE TITLE
求一份vim配置

### ISSUE THREAD

**Issue by Holmeyoung** [Yggdroot/LeaderF#765]
- vim or neovim? 
    - [ ] vim
    - [ x] neovim
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.

你好，你的vim界面真滴挺好看的，可以求一份配置文件么，哈哈，或者说一下比如用的什么我自己鼓捣一下也好～～～

**Comment by Yggdroot** [comment]
我的配置太乱了。
关于界面好看，无非就是配色和所谓的xxxline插件，装好就可以了。我的配色是https://github.com/Yggdroot/duoduo ，自己改的一个。
statusline插件是用的https://github.com/Yggdroot/twoline 
然后装一下字体，   ` let g:TL_stl_seperator = { 'left': '', 'right': '', 'font': 'DejaVu Sans Mono for Powerline' }`

**Comment by Holmeyoung** [comment]
感谢哇

很好看，赞👍
