### ISSUE TITLE
使用preview后有一些操作上的建议

### ISSUE THREAD

**Issue by GoodlPlus** [Yggdroot/LeaderF#769]
1、在LeaderfLine、LeaderfTag、LeaderfFunction的时候使用preview之后，添加只预览而没有选择项目就退出时，回到初始位置的选项。
2、在使用LeaderfFile preview文件之后添加一个选项，当只预览而没有打开时，退出LeaderfFile后，删除预览的buffer。

**Comment by Yggdroot** [comment]
你说的是非popup模式吧，建议使用popup模式，这样就满足你的要求了。

**Comment by GoodlPlus** [comment]
<img width="959" alt="1612094582(1)" src="https://user-images.githubusercontent.com/42902526/106383218-a7535a00-63ff-11eb-8b99-d2ed3be55b49.png">

<img width="959" alt="1612094747(1)" src="https://user-images.githubusercontent.com/42902526/106383232-c225ce80-63ff-11eb-8caf-e57399b31935.png">

嗯嗯，popup我也试过，但是不知道怎么控制预览时preview的高度，宽度我知道可以通过设置g:Lf_PreviewPopupWidth，但是这个高度的位置看了整个文档也没找到怎么设置。。。

**Comment by Yggdroot** [comment]
高度不能设置，就是一直到顶部

**Comment by GoodlPlus** [comment]
哦，这样啊，底部的高度也不能设置吗？默认状况好像是预览到选择的cursorline处。

**Comment by Yggdroot** [comment]
是的。
我说的popup模式，是leaderf窗口也是popup的。

**Comment by GoodlPlus** [comment]
嗯嗯，用popup时可以的，但是我感觉还是更习惯于默认模式。。。

另外我不知道我是不是没有描述清楚，我的意思是进行预览退出之后cursor位置发生了变化，从初始时启动的cursor位置变成了预览后的cursor位置。

按习惯操作而言，预览操作可能只是想查看一下一些函数的定义，并不想要改变文件的cursor位置，所以在启动leaderf时能否自动记录初始位置，当没有选择项目而只是预览时，在退出leaderf后可以自动跳转到初始位置。

我在视频中回到初始位置是通过在原来位置定义一个mark，跳转回去的。

是不是可以添加一个这样的判断条件：

1、当选择项目之后，退出leaderf，跳转到所选择项目的位置。

2、只进行上下选择预览时，退出leaderf，跳转到打开leaderf之前的cursor位置。

不知道有没有解释清楚，我感觉这样的操作好像比较符合操作习惯。。。

https://user-images.githubusercontent.com/42902526/106384197-9a853500-6404-11eb-89ec-01f145d224bd.mp4
