### ISSUE TITLE
Could it be possible to use Cmd-V on Mac?

### ISSUE THREAD

**Issue by MightyCreak** [Yggdroot/LeaderF#77]
It's clearly not a priority, but a nice to have.
On Mac paste is done using Cmd-V instead of Ctrl-V and it would be easier to be able to use Cmd-V in LeaderF when on Mac (because Mac users are used to it, it's hard written in their brains ;) ).

**Comment by Yggdroot** [comment]
I'm afraid it is impossible, because `getchar()` of vim on Mac can not identify `Cmd-V`.

**Comment by MightyCreak** [comment]
It was worth a try 😀
I'll close this issue then.
Thank you!
