### ISSUE TITLE
leaderf function只能搜索函数，如何搜索class类呢？

### ISSUE THREAD

**Issue by yllr78** [Yggdroot/LeaderF#770]
最近拜读了大神的leaderf文章，使用以后爱不释手，感谢大神的辛苦付出。
目前有两个小问题一直不知道怎么解决，求教大神。
1.leaderf function只能搜到函数，python中的class怎么可以方便的搜索呢？
2.顺路问个题外话，今年将cgats升级到了universal ctags，也根据韦大神的文章使用gutentags来管理，但一直看不到任何tags文件的生成，难道不是自动生成的吗？需要自己手动生成？

最后希望大神不吝赐教。谢谢

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
`let g:Lf_CtagsFuncOpts = {"python": "--python-kinds=fmc --language-force=Python"}`
或者使用`Leaderf bufTag`

**Comment by Yggdroot** [comment]
gutentags 我没有深入研究过，至少最基本的使用，不太清楚。

**Comment by yllr78** [comment]
搜索class的问题已解决，感谢！
还有个问题不知是否知道原因，使用file选项中文文件名可以正确显示，但是使用rg搜索时看到中文都是乱码，不知是何原因？

**Comment by Yggdroot** [comment]
你的encoding是什么

**Comment by yllr78** [comment]
set encoding=utf-8                                    "设置gvim内部编码
set fileencoding=utf-8                                "设置当前文件编码
set termencoding=utf-8                                "设置终端编码
set fileencodings=ucs-bom,utf-8,gbk,gb18030,cp936,big5,euc-jp,euc-kr,latin     "设置支持打开的文件的编码

**Comment by Yggdroot** [comment]
你执行echo &encoding 看一下

**Comment by yllr78** [comment]
显示：utf-8

**Comment by Yggdroot** [comment]
你不用vim，直接在shell里用rg命令，看看有乱码吗

**Comment by yllr78** [comment]
cmder里运行rg命令也出现乱码，使用type命令查看该中文txt文件可以正常显示。

**Comment by Yggdroot** [comment]
rg内部编码是utf8，你的文件不是utf8编码，那没办法了，除非再额外进行转码

**Comment by yllr78** [comment]
好嘞，知道问题在哪就行，谢谢回答。
