### ISSUE TITLE
LeaderF popup 窗口，在normal模式时，如何按 Esc 关闭弹出的窗口？

### ISSUE THREAD

**Issue by alexya** [Yggdroot/LeaderF#774]
```
let g:Lf_WindowPosition = 'popup' " popup mode
noremap <leader>lm :<C-U><C-R>=printf("Leaderf! mru %s", "")<CR><CR>

```
当我使用 <leader>lm打开 mru的窗口后，是直接进入normal mode的，但是此时，按Esc不能关闭，只能按q
vim里面q 通常是开启 宏录制，由于经常连接按q，结果，就变成录制宏。命令混乱了。

所以，想请教一下，LeaderF怎么设置Esc直接关闭窗口？（注：INSERT 模式是可以的）

**Comment by Yggdroot** [comment]
用vim是可以的，nvim目前不可以。

**Comment by alexya** [comment]
是nvim 的限制么？能具体一点么？
如果需要，我去那边提一个需求。

**Comment by Yggdroot** [comment]
不是，是vim的popup默认就可以esc关掉，nvim的不可以。当然LeaderF可以写代码实现，我只是保持了默认行为。

**Comment by alexya** [comment]
那还是 nvim 不支持 esc 关掉popup。奇怪，不清楚nvim为啥不支持这个......

**Comment by Yggdroot** [comment]
nvim的floatwin 是一个正常的窗口，只不过是浮动的，你正常的窗口里按esc也不会退出。

**Comment by alexya** [comment]
“行为不一致”，使用起来好郁闷啊。有没有办法我自己弄一弄？

**Comment by Yggdroot** [comment]
https://github.com/Yggdroot/LeaderF/blob/f1d05f41739e4f6f9a9e7883c0eaa4f24a90e45e/doc/leaderf.txt#L447
