### ISSUE TITLE
启用devicon，有时从Leaderf打开文件devicon会前缀在文件名上

### ISSUE THREAD

**Issue by g6ai** [Yggdroot/LeaderF#776]
比如我打开项目的local .vimrc文件，文件名加了vim script devicon的前缀，相当于新建了一个文件名为"V .vimrc"的文件：
![](https://i.imgur.com/9yr6KoI.png)

这个情况总会出现我使用`:source ~/.vimrc`加载用户vimrc之后，重启Vim后可解决，但是再次source的时候就会复现。

**Comment by Yggdroot** [comment]
能说具体点吗？

**Comment by g6ai** [comment]
好的！在我尝试提供具体细节的过程中，发现了问题所在哈哈。是这样的：

我的配置和vimrc相关设置请参见https://github.com/Yggdroot/LeaderF/issues/772 ，在vimrc里我设置的是`let g:Lf_ShowDevIcons = 0`，因为命令行Vim使用devicon还是有点问题。此处使用MacVim的gVim，已在gvimrc设置`let g:Lf_ShowDevIcons = 1`。

有时我在gVim实例运行的时候，在命令行Vim对vimrc进行了改动，然后回到gVim通过`:source ~/.vimrc`加载vimrc。问题就出在这里，我忘记重新加载gvimrc了，于是vimrc设置了`let g:Lf_ShowDevIcons = 0`，Leaderf窗口里的devicon就被加在了文件名前面。解决方法是在vimrc里添加`has("gui_running")则自动加载gvimrc的功能。

**Comment by Yggdroot** [comment]
good！
