### ISSUE TITLE
采用推荐的配置出现一些如下问题

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [Yggdroot/LeaderF#777]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Expected behaviour
![image](https://user-images.githubusercontent.com/28779327/109248873-9ee51800-7821-11eb-9e0f-38581043fb6f.png)

**Comment by Yggdroot** [comment]
你没有安装gtags。

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/109274894-f9e13400-784e-11eb-8b74-ae881d27f07a.png)
已经安装gtags了，为什么有些快捷键还是不好使呢，这个插件有哪些依赖呢

**Comment by Yggdroot** [comment]
还依赖ctags，ripgrep

**Comment by wangwenqiangGitHub** [comment]
> 还依赖ctags，ripgrep

这几个都安装完成了，还是有图片中的问题，我看是报python问题

**Comment by Yggdroot** [comment]
你敲global这个命令有什么反应？

**Comment by wangwenqiangGitHub** [comment]
> 你敲global这个命令有什么反应？

![image](https://user-images.githubusercontent.com/28779327/109306597-59086e00-787a-11eb-9b42-144960993994.png)

**Comment by Yggdroot** [comment]
> ![image](https://user-images.githubusercontent.com/28779327/109274894-f9e13400-784e-11eb-8b74-ae881d27f07a.png)
> 已经安装gtags了，为什么有些快捷键还是不好使呢，这个插件有哪些依赖呢

有些快捷键不好使是哪些？报什么问题？

**Comment by wangwenqiangGitHub** [comment]
我运行了leaderf gtags --update可以了。这个如何设置自动产生，为什么我把g:Lf_GtagsAutoGenerate = 0改为g:Lf_GtagsAutoGenerate = 1.也没自动生成

**Comment by Yggdroot** [comment]
g:Lf_GtagsAutoGenerate = 1 会在打开文件时，或者修改文件时自动更新（没有就生成）.
