### ISSUE TITLE
Is there any way to ignore the `term:\\` item in buffer list?

### ISSUE THREAD

**Issue by waruqi** [Yggdroot/LeaderF#78]
Is there any way to ignore the `term:\\` item in buffer list if I opened a terminal windows in neovim?

![snip20171020_6](https://user-images.githubusercontent.com/151335/31801825-46130bec-b510-11e7-9ec0-7706b60ccf83.png)

**Comment by Yggdroot** [comment]
Currently, no.

**Comment by waruqi** [comment]
Can you consider to support this feature in the future? Ignores some buffer items by configuration. 😄

**Comment by cyansprite** [comment]
if you have the buffer, let's call it a:buf, you could check this, it will ignore hidden, and odd buftypes.
I know this works in neovim, I'm not sure about vim.
```vim    
a:buf.hidden || getbufvar(a:buf.bufnr, "&buftype") != ""
```

Source `:h buftype`
```vim
						*'buftype'* *'bt'* *E382*
'buftype' 'bt'		string (default: "")
			local to buffer
	The value of this option specifies the type of a buffer:
	  <empty>	normal buffer
	  acwrite	buffer will always be written with |BufWriteCmd|s
	  help		help buffer (do not set this manually)
	  nofile	buffer is not related to a file, will not be written
	  nowrite	buffer will not be written
	  quickfix	list of errors |:cwindow| or locations |:lwindow|
	  terminal	|terminal-emulator| buffer
```

**Comment by waruqi** [comment]
@cyansprite Thanks, I will try it. 👍 😄
