### ISSUE TITLE
LeaderfFile不能检测到文件的添加和删除

### ISSUE THREAD

**Issue by huanglei104** [Yggdroot/LeaderF#789]
let g:Lf_UseVersionControlTool = 0 好像不起作用

**Comment by huanglei104** [comment]
已经找到解决办法了

**Comment by huanglei104** [comment]
let g:Lf_UseVersionControlTool = 0 好像不作用

**Comment by Yggdroot** [comment]
首先，可以用F5刷新一下，如果不起作用，执行Leaderf file 后`echo g:Lf_Debug_Cmd`，看看后台跑的是什么命令。

**Comment by huanglei104** [comment]
> echo g:Lf_Debug_Cmd

感谢回复！ 后台命令是：rg --no-messages --files --color never

**Comment by Yggdroot** [comment]
按F5没效果吗

**Comment by huanglei104** [comment]
> 按F5没效果吗

我电脑上F5是调节调度的，而且如果每次都按F5这种体验也不太好吧。我的环境 ： archlinux，neovim 0.4.4

**Comment by Yggdroot** [comment]
```vim
let g:Lf_UseCache = 0
let g:Lf_UseMemoryCache = 0
```

**Comment by huanglei104** [comment]
> ```viml
> let g:Lf_UseCache = 0
> let g:Lf_UseMemoryCache = 0
> ```

可以了，感谢！
