### ISSUE TITLE
Noob question: How to search line globally

### ISSUE THREAD

**Issue by sava-vidakovic** [Yggdroot/LeaderF#791]
Hello! 
This is not an issue it's a just noob question.
I'm using this extension and I don't know is possible to search whole project for specific line?
For example I want to find usage of my function, how can I do that?
Thanks!

**Comment by Yggdroot** [comment]
There are several ways to do it:
1. `:Leaderf rg myFunction`
2. `:Leaderf rg`,  then type the function name
3. `:Leaderf gtags`, then type the function name
4. `:Leaderf gtags -r myFunction`
5. `Leaderf tag`, then type the function name
