### ISSUE TITLE
发现noremap <CR>中的回车不起作用

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [Yggdroot/LeaderF#792]
- vim or neovim? 
    - [ x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
` <Leader>a :<C-U><C-R>=printf("Leaderf! rg -e %s -g *.h -g *.cpp", expand("<cword>"))`，类似的rg这种结尾回车都不起作用。
这种就是可以的 noremap <c-n> :LeaderfMru<CR>

**Comment by Yggdroot** [comment]
加两个回车。
第一个回车相当于计算`<C-R>=`，第二个回车才是你想要的回车。

**Comment by wangwenqiangGitHub** [comment]
> 加两个回车。
> 第一个回车相当于计算`<C-R>=`，第二个回车才是你想要的回车。

嗯嗯，谢谢，这个问题完美解决了，还有就是关键字搜索这块，一个大的工程，我进入某个文件夹下的.cpp文件搜索某个类，但是搜索的路径就是在当前的文件夹，而不是整个工程中，有什么快捷方式查找么

**Comment by Yggdroot** [comment]
你用的什么命令？

**Comment by wangwenqiangGitHub** [comment]
> 你用的什么命令？
<Leader>a :<C-U><C-R>=printf("Leaderf! rg -e %s -g *.h -g *.cpp", expand("<cword>"))

**Comment by wangwenqiangGitHub** [comment]
> 你用的什么命令？

用的<Leader>a :<C-U><C-R>=printf("Leaderf! rg -e %s -g *.h -g *.cpp", expand("<cword>"))

**Comment by wangwenqiangGitHub** [comment]
> > 你用的什么命令？
`<Leader>a :<C-U><C-R>=printf("Leaderf! rg -e %s -g *.h -g *.cpp", expand("<cword>"))<cr><cr>`

**Comment by Yggdroot** [comment]
let g:Lf_WorkingDirectoryMode = 'ac'

**Comment by wangwenqiangGitHub** [comment]
> let g:Lf_WorkingDirectoryMode = 'ac'

在rg查找时，是否可以切换Fuzzy为Full呢，我觉得是这个原因

**Comment by Yggdroot** [comment]
上个问题解决了吗？这是个新问题？

**Comment by wangwenqiangGitHub** [comment]
> 上个问题解决了吗？这是个新问题？

还是在当前目录查找，没有解决

**Comment by Yggdroot** [comment]
你的工程是用git管理的吗

**Comment by wangwenqiangGitHub** [comment]
> 你的工程是用git管理的吗

是的

**Comment by Yggdroot** [comment]
那设了let g:Lf_WorkingDirectoryMode = 'ac'应该管用呀。你用Leaderf file可以找到其它目录的文件吗？

**Comment by wangwenqiangGitHub** [comment]
> 那设了let g:Lf_WorkingDirectoryMode = 'ac'应该管用呀。你用Leaderf file可以找到其它目录的文件吗？

如果是打开了工程的某个目录，那么查找的内容就是在这个目录，而非整个工程

**Comment by Yggdroot** [comment]
let g:Lf_WorkingDirectoryMode = 'ac' 肯定可以，除非是跟别的插件冲突导致的，你把别的插件都禁掉试一下，如果还有问题请贴出一个最小能复现的vimrc。
