### ISSUE TITLE
Feature Request: add function list regular expression support Javascript and Objective-C

### ISSUE THREAD

**Issue by jackhub** [Yggdroot/LeaderF#794]
Objective-c function style:

`- (void)testFunction {

}
`

JavaSctipt function style:

`function testFunction(touches) {

}
`

Please add function list support Javascript and Objective-C, or someone can tell me how to add it myself.
Thanks.

Maybe leaderf can provide  options to setting how to match a function statement, we can add whatever we want.

**Comment by Yggdroot** [comment]
I don't understand what you mean, could you describe in more detail? 
Doesn't `Leaderf function` work?

**Comment by jackhub** [comment]
Leaderf function works for some language, but not for ALL.

It's not works for objc / objcpp filetype.

**Comment by jackhub** [comment]
> I don't understand what you mean, could you describe in more detail?
> Doesn't `Leaderf function` work?

Leaderf function works for some language, but not for ALL.

It's not works for objc / objcpp filetype.

**Comment by Yggdroot** [comment]
let g:Lf_CtagsFuncOpts = {
            \ 'objc': '--ObjectiveC-kinds=fp',
            \ }

**Comment by Yggdroot** [comment]
use https://github.com/universal-ctags/ctags instead.
