### ISSUE TITLE
Navigate tags

### ISSUE THREAD

**Issue by kostajh** [Yggdroot/LeaderF#8]
Nice plugin!

Ctrlp also supports navigating tags. Would you consider adding this to LeaderF?

**Comment by johnzeng** [comment]
Do you have any plan about adding this feature? If no, I may help about this. I need to use tag searching now, so I am looking for plugin to do this, but ctrlp is too large and slow. I think leaderf can do it better.

**Comment by Yggdroot** [comment]
@johnzeng I'm thinking about adding async support recently. It would be easy to add this feature when the async framework is established. Also welcome to add new features for this plugin.

**Comment by Leandros** [comment]
@Yggdroot Any plans on adding this feature?

**Comment by Yggdroot** [comment]
@Leandros I'm very busy recently, maybe it will take a lot of time to add this feature.

**Comment by Yggdroot** [comment]
Perhaps for several months, I have no time to develop this plugin.

**Comment by Yggdroot** [comment]
Done.

**Comment by Leandros** [comment]
Awesome! That works very well! To make it just a little bit better, it would be great if you could only search in the current opened buffer.

**Comment by Yggdroot** [comment]
A new feature has been added to navigate tags in opening buffers. 
Please use `LeaderfBufTag` and `LeaderfBufTagAll`.

**Comment by Leandros** [comment]
Thanks a lot for your work on LeaderF @Yggdroot! It's definitely one of my most used and loved plugins for Vim! Couldn't work without it anymore.

**Comment by Yggdroot** [comment]
I'm glad that you love it.
Please also try `LeaderfFunction` and `LeaderfFunctionAll`.
