### ISSUE TITLE
Sluggish on a big project

### ISSUE THREAD

**Issue by smekkley** [Yggdroot/LeaderF#803]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
 
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 29 2020 00:00:00)
Included patches: 1-1770
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       +xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/libxml2 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld   -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm  -lselinux  -lncurses -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.9.so.1.0
- Output of `:py print(sys.version)`: nothing
- Output of `:py3 print(sys.version)`: 
```
3.9.0 (default, Oct 6 2020, 00:00:00)
[GCC 10.2.1 20200826 (Red Hat 10.2.1-3)]
```
- Output of `:echo g:Lf_Debug_Cmd`: Undefined variable
- Output of `:echo g:Lf_FilesFromCache`: Undefined variable
- Operating system: 
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_RootMarkers = ['.git']
let g:Lf_WorkingDirectoryMode = 'a'
let g:Lf_PopupWidth = 0.6
let g:Lf_PopupHeight = 0.3
let g:Lf_PopupPosition = [1, 0]
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_AutoResize = 0
let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}
nmap <C-f> :Leaderf file<CR>
nmap <C-g> :Leaderf rg<CR>
```

### Describe your question, feature request, or bug.
On a big project like linux kernel, Leaderf file --popup and Leaderf rg --popup becomes sluggish with or without C extention.

### Steps to reproduce
Check out linux kernel, run Leaderf rg --popup

### Actual behaviour
Typing and deleting word responds noticeably slow, that you wouldn't see in a small projects.

### Expected behaviour
Behave the same regardless of the project size.
 
 
Also let me thank for the best fuzzy finder plug in.  
Let me know where I can look into to fix the issue.

**Comment by Yggdroot** [comment]
I don't know why, in theroy, Leaderf won't be sluggish even on 1,000,000 files project. Linux kernel files are less than 100,000.
What is the behavior if not use popup mode? .i.e, `Leaderf file`.
Have you tried on other platforms?

**Comment by Yggdroot** [comment]
maybe it's the same reason as https://github.com/Yggdroot/LeaderF/issues/318

**Comment by smekkley** [comment]
The issue randomly happens on the same project, having column limit might've decreased the frequency.
#686 issue sounds familiar. Is the related patch only applicable to nvim?  So it's just limitation of vim, maybe?  
 
Especially with paste being sometime extremely slow behaviour, it is as if one character is causing some action and freeze the input. It also might be that when I add space in the search time it gets even slower. backspace also feels slow and sometimes crash(keep popup open and go back to editing mode) when that issue happens.

**Comment by smekkley** [comment]
I did some digging. Here are my findings with leaderf rg --popup.   
1. backspace is always slower than normal input.
2. shift + insert paste is always slow regardless compared to ctrl + v
3 removing sleep in cli.py improves the situation.
4. if you type like test test test test and back space, it can crash sometimes, also becomes slow.

**Comment by smekkley** [comment]
I finally found out how to reproduce the issue consistently. It's overall slow on big project but I haven't been able to reproduce very-slow issue consistently up until now.   

1. Open vim
2. Jump around files, using ctags, some language server client, and etc. (I use vim-lsc to jump to references)
3. Run Leaderf file --popup or anything with popup. Typing will be extremely slow.  


The issue doesn't happen with non popup mode, fortunately.

**Comment by Yggdroot** [comment]
If the current open file is very large or has very long lines, the popup mode may become slow, I know this issue, it should be a bug of vim.

**Comment by smekkley** [comment]
Thanks for clearing it up. Closing the issue now. I'll watch out for vim update.

**Comment by smekkley** [comment]
I created an issue in vim-lsc just, as I didn't observe the issue when it's disabled. I pasted vim profiler results there, if you are interested.   
The profiler results look normal but maybe vim-lsc is blocking something on input.
