### ISSUE TITLE
preview fail when using --heading in Leader rg

### ISSUE THREAD

**Issue by xaljer** [Yggdroot/LeaderF#804]
- vim or neovim? 
    - [ ] vim
    - [ x ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
nnoremap <Leader>fw :match Cursor '<C-R><C-W>'<CR> :<C-U><C-R>
    \=printf("Leaderf! rg --match-path --wd-mode Ac -e %s -w --heading", expand("<cword>"))<CR>
```

### Steps to reproduce
press 'p' in result window of Leader rg.

### Actual behaviour
preview fail when using '--heading' in Leader rg

### Expected behaviour
preview normal when using '--heading' in Leader rg

**Comment by Yggdroot** [comment]
Can not reproduce. What do you mean by 'fail'?

**Comment by xaljer** [comment]
![image](https://user-images.githubusercontent.com/8309631/119246362-8e8bd180-bbb3-11eb-9cbf-78bb5c48eb11.png)

**Comment by xaljer** [comment]
![image](https://user-images.githubusercontent.com/8309631/119246555-18886a00-bbb5-11eb-828a-31aebd540f01.png)
Also fail when do `Leader --previous` after search using `--heading`.

**Comment by Yggdroot** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/8309631/119246555-18886a00-bbb5-11eb-828a-31aebd540f01.png)
> Also fail when do `Leader --previous` after search using `--heading`.

This can be reproduced, because `--previous` is not supported yet.
The first still can not reproduce.

**Comment by xaljer** [comment]
Would you like to support `--previous` and `--next` for `--heading`? Do I need to open another issue?
I will try to find the condition to reproduce the fail of preview.

**Comment by Yggdroot** [comment]
Fixed.
