### ISSUE TITLE
Preview for files doesn't refresh when typing out file names

### ISSUE THREAD

**Issue by shyun3** [Yggdroot/LeaderF#807]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: `E319: No "python" provider found. Run ":checkhealth provider"`
- Output of `:py3 print(sys.version)`:
```
3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0]
```
- Output of `:echo g:Lf_Debug_Cmd`: `E121: Undefined variable: g:Lf_Debug_Cmd`
- Output of `:echo g:Lf_FilesFromCache`: `E121: Undefined variable: g:Lf_FilesFromCache`
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = {
  \ 'File': 1,
  \ 'Buffer': 1,
  \ 'Mru': 1,
  \ 'Tag': 1,
  \ 'BufTag': 1,
  \ 'Function': 1,
  \ 'Line': 1,
  \ 'Colorscheme': 1,
  \ 'Rg': 1,
  \ 'Gtags': 0
  \}
```

### Describe your question, feature request, or bug.
When first using `<leader>f` in a directory, the preview for the first file in the list may show up but typing more characters to select different files does not cause the preview to refresh. `<C-p>`, `<C-j>`, and `<C-k>` do work to update the preview but I feel that I shouldn't be require to use these keys. Typing the file names by itself should refresh the preview.

### Steps to reproduce
Create a new directory and some simple files:
```
mkdir tmp
cd tmp
echo hello > file.txt
echo world > notes.txt
```

Press `<leader>f` and observe that the preview window for `file.txt` has popped up.

Now, type `notes` in the dialog.

### Actual behaviour
The preview window is still open for `file.txt`.

### Expected behaviour
The preview window should be showing the contents of `notes.txt`

**Comment by Yggdroot** [comment]
it works by design in order for performance.

**Comment by shyun3** [comment]
Would it be possible to add some sort of timer to handle this situation? For example, there could be a new `g:Leaderf` variable the user could set and if the time of last typing exceeds this timeout, then the preview window would be refreshed.

**Comment by Yggdroot** [comment]
Fixed.
