### ISSUE TITLE
Crash on windows

### ISSUE THREAD

**Issue by waynelau1989** [Yggdroot/LeaderF#810]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May 20 2021 22:02:20)
MS-Windows 64-bit GUI version 带 OLE 支持
包含补丁: 1-2875
编译者 appveyor@APPVYR-WIN
巨型版本 带图形界面。  可使用(+)与不可使用(-)的功能:
+acl                +comments           +file_in_path       +lispindent         +perl/dyn           +startuptime        +user_commands
+arabic             +conceal            +find_in_path       +listcmds           +persistent_undo    +statusline         +vartabs
+autocmd            +cryptv             +float              +localmap           +popupwin           -sun_workshop       +vertsplit
+autochdir          +cscope             +folding            +lua/dyn            -postscript         +syntax             +virtualedit
+autoservername     +cursorbind         -footer             +menu               +printer            +tag_binary         +visual
+balloon_eval       +cursorshape        +gettext/dyn        +mksession          +profile            -tag_old_static     +visualextra
-balloon_eval_term  +dialog_con_gui     -hangul_input       +modify_fname       +python/dyn         -tag_any_white      +viminfo
+browse             +diff               +iconv/dyn          +mouse              +python3/dyn        +tcl/dyn            +vreplace
++builtin_terms     +digraphs           +insert_expand      +mouseshape         +quickfix           -termguicolors      -vtp
+byte_offset        +directx            +ipv6               +multi_byte_ime/dyn +reltime            +terminal           +wildignore
+channel            -dnd                +job                +multi_lang         +rightleft          -termresponse       +wildmenu
+cindent            -ebcdic             +jumplist           +mzscheme/dyn       +ruby/dyn           +textobjects        +windows
+clientserver       +emacs_tags         +keymap             +netbeans_intg      +scrollbind         +textprop           +writebackup
+clipboard          +eval               +lambda             +num64              +signs              -tgetent            -xfontset
+cmdline_compl      +ex_extra           +langmap            +ole                +smartindent        +timers             -xim
+cmdline_hist       +extra_search       +libcall            +packages           +sound              +title              +xpm_w32
+cmdline_info       -farsi              +linebreak          +path_extra         +spell              +toolbar            -xterm_save

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python39.dll
- Output of `:py print(sys.version)`: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] 
- Output of `:py3 print(sys.version)`: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_fuzzyEngine_C=1
" for LeaderF
if has('unix')
    let g:Lf_GtagsAutoGenerate=1
endif
let g:Lf_UseVersionControlTool=0
nmap <Leader>@ :Leaderf function<CR>

### Describe your question, feature request, or bug.
处理 function leaderf#Any#start[4]..leaderf#LfPy 时发生错误:
第    1 行:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 808, in startExplorer
    super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 2191, in startExplorer
    self._getInstance().enterBuffer(win_pos, not isinstance(content, list))
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\instance.py", line 1029, in enterBuffer
    self._after_enter()
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 737, in _afterEnter
    self._match_ids.extend(matchaddDevIconsExtension(icon_pattern, winid))
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\devicons.py", line 510, in matchaddDevIconsExtension
    return _matchadd(fileNodesExtensionSymbols, pattern, 7, winid)
  File "D:\Users\liuwei\.vim\plugged\LeaderF\autoload\leaderf\python\leaderf\devicons.py", line 470, in _matchadd
    id = int(lfEval("matchadd('{:s}', '{:s}')".format(group_name, tmp_pattern)))
UnicodeEncodeError: 'euc_jp' codec can't encode character '\ue624' in position 33: illegal multibyte sequence   
### Steps to reproduce
:Leaderf file
### Actual behaviour
crash
### Expected behaviour
display files

**Comment by ccecfei** [comment]
i have same crash

**Comment by Yggdroot** [comment]
What is `&encoding`? 
What is the value of `g:Lf_PythonVersion`?

**Comment by bruce-bst** [comment]
echo &encoding
cp936

echo g:Lf_PythonVersion
3

**Comment by waynelau1989** [comment]
echo &encoding
cp936

echo g:Lf_PythonVersion
3

**Comment by Yggdroot** [comment]
set encoding=utf-8

**Comment by waynelau1989** [comment]
> set encoding=utf-8

Thanks, it works after set encoding=utf-8
