### ISSUE TITLE
MRU中一个文件显示两次

### ISSUE THREAD

**Issue by kdurant** [Yggdroot/LeaderF#816]
- vim or neovim? 
    - [ ] vim
    - [x] neovim

- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```viml
    let g:Lf_UseCache=0
    let g:Lf_UseMemoryCache=0
    let g:Lf_WindowHeight = 0.4
    let g:Lf_WorkingDirectoryMode ='Ac'
    let g:Lf_DefaultMode = 'NameOnly'
    let g:Lf_CommandMap = {'<C-]>': ['<C-V>'], '<C-X>': ['<C-S>']}
    let g:Lf_WindowPosition = 'popup'
    let g:Lf_ShowRelativePath=0
    let g:Lf_MruMaxFiles=1000
    "let g:Lf_Gtagslabel="native-pygments"

    let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.html']
            \}
    let g:Lf_MruWildIgnore = {
            \ 'dir': [],
            \ 'file': ['*.txt', '*.log']
            \}

    let g:Lf_PreviewInPopup = 1
    let g:Lf_PreviewResult = {
            \ 'File': 0,
            \ 'Buffer': 0,
            \ 'Mru': 0,
            \ 'Tag': 0,
            \ 'BufTag': 1,
            \ 'Function': 1,
            \ 'Line': 0,
            \ 'Colorscheme': 0,
            \ 'Rg': 1,
            \ 'Gtags': 0
            \}
```

### Describe your question, feature request, or bug.
使用`Leaderf mru`命令时，同样的文件会显示两次
![QQ截图20210602180458](https://user-images.githubusercontent.com/2704364/120461961-12706580-c3cd-11eb-9d56-7415db3b8051.png)

### Expected behaviour
只显示一次就好了

**Comment by Yggdroot** [comment]
具体复现步骤是什么？

**Comment by kdurant** [comment]
win10系统使用`Leaderf mru`命令就这样
wsl里的ubuntu18.04没有问题

**Comment by Yggdroot** [comment]
你把Lfcache那个文件夹删掉，再看看复现步骤是怎样的。如果Windows10是只要使用就有这个问题，肯定早就修复了。

**Comment by kdurant** [comment]
1. 关闭vim
2. 删掉Lfcache文件夹
3. 打开init.vim
4. 执行`Leaderf mru`命令，就可以看到两个相同的记录
![QQ截图20210603082312](https://user-images.githubusercontent.com/2704364/120567709-f3151f00-c444-11eb-86d5-7b2701c33c3d.png)

**Comment by Yggdroot** [comment]
复现不了，能不能提供一个最小的vimrc，怀疑是你的哪个autocmd导致的。
第三步和第四部是先打开init.vim, 然后再tabnew ~/.config/nvim/init.vim ？

**Comment by kdurant** [comment]
最小的vimrc
```viml
set autochdir
call plug#begin('~/.config/nvim/bundle')
Plug 'git@github.com:Yggdroot/LeaderF.git'
call plug#end()
```

1. 关闭vim
2. 删掉Lfcache文件夹
3. 打开init.vim,   然后`:tabnew ~/.config/nvim/init.vim`
4. 执行Leaderf mru命令，就可以看到两个相同的记录

**Comment by Yggdroot** [comment]
找到原因了，这应该算是nvim的bug，再Windows上，tabnew ~/.config/nvim/init.vim 打开的文件路径应该是~\.config\nvim\init.vim.

**Comment by kdurant** [comment]
谢谢
