### ISSUE TITLE
rg搜索时，能不能popup一个窗口出来 预览文件哈

### ISSUE THREAD

**Issue by owenstake** [Yggdroot/LeaderF#817]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

rg搜索后的结果，能不能popup一个窗口出来 预览文件哈。正如fzf-vim一般，效果如下图。

### Expected behaviour
![image](https://user-images.githubusercontent.com/45960823/120495718-8b80b480-c3ef-11eb-824e-60da6bf93cf3.png)

**Comment by Yggdroot** [comment]
```
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = {
            \ 'File': 0,
            \ 'Buffer': 0,
            \ 'Mru': 0,
            \ 'Tag': 0,
            \ 'BufTag': 1,
            \ 'Function': 1,
            \ 'Line': 0,
            \ 'Colorscheme': 0,
            \ 'Rg': 1,
            \ 'Gtags': 0
            \}
```
