### ISSUE TITLE
无法安装成功

### ISSUE THREAD

**Issue by roverway** [Yggdroot/LeaderF#819]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: +python/dyn +python3/dyn...python27.dll.....python39.dll
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`:1 
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python39.dll
- Output of `:py print(sys.version)`: 无法加载库python27.dll 
- Output of `:py3 print(sys.version)`: givm闪退，vim也闪退（窗口消失）
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
没有相关内容，除了vimplug内的配置

操作系统、vim、python都是64位，系统安装的python是3.9

**Comment by Yggdroot** [comment]
请参考https://zhuanlan.zhihu.com/p/89243293 这篇文章。

**Comment by roverway** [comment]
> 请参考https://zhuanlan.zhihu.com/p/89243293 这篇文章。

看过了，似乎我就是这篇文章里说的1%的需要靠人品解决问题的那部分。

目前同样的环境不做任何修改，neovim是正常的。只有vim不行。而且开了leaderf之后，还会导致vim保存的时候直接闪退。

**Comment by roverway** [comment]
> > 请参考https://zhuanlan.zhihu.com/p/89243293 这篇文章。
> 
> 看过了，似乎我就是这篇文章里说的1%的需要靠人品解决问题的那部分。
> 
> 目前同样的环境不做任何修改，neovim是正常的。只有vim不行。而且开了leaderf之后，还会导致vim保存的时候直接闪退。

从上面的输出也可以看到，能识别到python39.dll，只是似乎不能加载（闪退）

**Comment by Yggdroot** [comment]
https://github.com/vim/vim-win32-installer/releases 这里下载vim，再在https://www.python.org/downloads/ 里下载对应版本的Python，会有问题？

**Comment by roverway** [comment]
> https://github.com/vim/vim-win32-installer/releases 这里下载vim，再在https://www.python.org/downloads/ 里下载对应版本的Python，会有问题？

vim就是上面的地址下载的，python是anaconda安装的。。

谢谢大佬，先不折腾了，等vim和你的插件都更新几个版本之后再试试。

**Comment by roverway** [comment]
大佬，搞定了。

其他条件不变，补充这样两句就行了：

let &pythonthreedll='C:\Users\XX\miniconda3\python39.dll'
let &pythonthreehome='C:\Users\XX\miniconda3'

**Comment by Yggdroot** [comment]
所以原来你并没有按照我那篇文章说的做，不是人品问题

**Comment by roverway** [comment]
> 所以原来你并没有按照我那篇文章说的做，不是人品问题

是我知识储备不够，分不清let和set的区别，还有到底是so还是dll，甚至路径用/还是\，以及应该用单引号还是双引号包裹都搞不清，更别说还出来个phthonthreehome。。。就是网上一通搜，各种尝试。

set pythondll我肯定是操作过的，确实没生效，原因不知道是不是缺少&，或者斜杠用错了，或者少了pythonhome。总之现在能用了就好。

**Comment by roverway** [comment]
![image](https://user-images.githubusercontent.com/657850/121875081-a0880c80-cd3a-11eb-9f7b-3c15b7f16635.png)
现在leaderf file有时候会出现这个，不知道啥原因。

**Comment by roverway** [comment]
> ![image](https://user-images.githubusercontent.com/657850/121875081-a0880c80-cd3a-11eb-9f7b-3c15b7f16635.png)
> 现在leaderf file有时候会出现这个，不知道啥原因。

换成目前官网稳定版vim8.2（32位）以及对应版本的32位python，暂时不弹这个错误了。

**Comment by Yggdroot** [comment]
set encoding=utf-8试一下

**Comment by roverway** [comment]
> > set encoding=utf-8试一下
> 
> 还是会弹出上面的错误提示，用的 skywind3000/vim-init 这个配置，编码设定好了。

应该是和这个配置安装的某些插件有冲突，我禁用了大量我用不到的插件之后没再出现上面的错误提示了，

**Comment by roverway** [comment]
> > > set encoding=utf-8试一下
> > 
> > 
> > 还是会弹出上面的错误提示，用的 skywind3000/vim-init 这个配置，编码设定好了。
> 
> 应该是和这个配置安装的某些插件有冲突，我禁用了大量我用不到的插件之后没再出现上面的错误提示了，

补充一点内容，报错应该和ctags，gtags以及rg的安装和配置有关，windows下搞这些有点麻烦啊。

**Comment by Yggdroot** [comment]
一点不麻烦。

**Comment by liming2013** [comment]
谢谢分享

**Comment by liming2013** [comment]
> 一点不麻烦。

请问要怎么配置呢？？

**Comment by Yggdroot** [comment]
> > 一点不麻烦。
> 
> 请问要怎么配置呢？？

下载可执行文件，加到`PATH`里面去。
