### ISSUE TITLE
Can't open file in directory with + as first character of directory name

### ISSUE THREAD

**Issue by wdu-wei** [Yggdroot/LeaderF#82]
Matlab file saved in folders  +dir1/@ dir2/file.m
When I tried to open it with LeaderF, it doesn't work. I saw message as below, and the + is missing. 
Vim:E492: Not an editor command: dir1/@ dir2/file.m

**Comment by wdu-wei** [comment]
My system is Windows 7 64 bit.

Please note there's no space between @ and dir2.

**Comment by Yggdroot** [comment]
Fixed.
