### ISSUE TITLE
can not find xxx.env file

### ISSUE THREAD

**Issue by lsaint** [Yggdroot/LeaderF#821]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: ╰─ nvim --version
NVIM v0.4.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/config -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20210318-48132-k7r45c/neovim-0.4.4/build/include
Compiled by brew@BigSur
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.8.9 (default, Apr  3 2021, 01:51:00)
[Clang 12.0.0 (clang-1200.0.32.29)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_WildIgnore = {
  \ 'dir': ['.svn','.git','.hg', 'node_modules', 'tmp', 'bin'],
  \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]','*.bson','*.exe','*.swp']
  \}
### Describe your question, feature request, or bug.
In search files mode, can't find xxx.env file. There is no *.env ignored in setting.

### Steps to reproduce
In search files mode, input .env file name.

### Expected behaviour
should be found.

**Comment by Yggdroot** [comment]
What is `Output of :echo g:Lf_Debug_Cmd` after running Leaderf file?
It's probable that *.env is in .gitignore.

**Comment by lsaint** [comment]
git ls-files  "." && git ls-files --others --exclude-standard  -x ".svn" -x ".hg" -x "node_modules" -x "tmp" -x "bin" -x "*.sw?" -x "~$*" -x "*.bak" -x "*.exe" -x "*.o" -x "*.so" -x "*.py[co]" -x "*.bson"
 -x "*.exe" -x "*.swp" "."

**Comment by lsaint** [comment]
hmm, i found it in .gitignore.  so there is no other way to find it if the pattern was in .gitignore?

**Comment by Yggdroot** [comment]
`Leaderf file --no-ignore`
