### ISSUE TITLE
New file does not appear in `Leaderf file` nor in results of `Leaderf rg`

### ISSUE THREAD

**Issue by carljohnesan** [Yggdroot/LeaderF#822]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
    ```
      NVIM v0.4.4
      Build type: Release
      LuaJIT 2.0.5
      Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/build/config -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/deps-build/include -I/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-21571-gjtb7k/neovim-0.4.4/build/include
      Compiled by brew@HighSierra
      
      Features: +acl +iconv +tui
      See ":help feature-compile"
      
         system vimrc file: "$VIM/sysinit.vim"
        fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"
      
      Run :checkhealth for more info
    ```

- Output of `:echo has("python")`:  `0`
- Output of `:echo has("python3")`:  `1`

- Output of `:py print(sys.version)`:  `no python provider`
 - Output of `:py3 print(sys.version)`:
     ```
      3.9.5 (default, Jun  8 2021, 09:03:00)
     [Clang 10.0.0 (clang-1000.10.44.4)]
     ```

- Output of `:echo g:Lf_Debug_Cmd`: `rg --no-messages --files --color never --hidden`
- Output of `:echo g:Lf_FilesFromCache`:  `1`
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vim
let g:Lf_UseVersionControlTool=0

nnoremap <C-p> :Leaderf file<cr>
nnoremap <Leader>f :Leaderf rg -S<cr>
```

### Describe your question, feature request, or bug.
When I create a new file with either `:e new_file.txt`, or a NerdTree plugin, or with terminal, or any other way - in all the cases file just not appears in `Leaderf file` files, nor it does in the results of `Leaderf rg`. Existing issues and their solutions didn't help me to solve this problem.

### Steps to reproduce
* Open Vim/NeoVim
* Open some file with `:Leaderf file`
* Create new file with `:e new_file.txt`
* Save new file with `:w`
* Go to some other file, input `:Leaderf file` from there
You will not see `new_file.txt` there

### Actual behaviour
No new `new_file.txt` file inside of `:Leaderf file`

### Expected behaviour
New `new_file.txt` file inside of `:Leaderf file`

**Comment by Yggdroot** [comment]
First, you can use `F5` to refresh the result.

Or

```
let g:Lf_UseCache = 0
let g:Lf_UseMemoryCache = 0
```

**Comment by carljohnesan** [comment]
Oh, thank you!
