### ISSUE TITLE
g:Lf_JumpToExistingWindow = 0 can't work for Leaderf file

### ISSUE THREAD

**Issue by fcying** [Yggdroot/LeaderF#824]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 0.44
- Output of `:py3 print(sys.version)`:  3.7.3
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
set nocompatible
set encoding=utf-8
set runtimepath^=~/.vim/.plugged/LeaderF
filetype plugin indent on
syntax on
let g:Lf_JumpToExistingWindow = 0
```

### Describe your question, feature request, or bug.
g:Lf_JumpToExistingWindow = 0 can't work for Leaderf file, also jump to the exist window.
it work fine with Leaderf buffer.

### Steps to reproduce
```
nvim a
:vs b
:Leaderf file
a<CR>
jump to exist a window.

nvim a
:vs b
:Leaderf buffer
a<CR>
open file a in current window.
```

**Comment by Yggdroot** [comment]
fixed
