### ISSUE TITLE
新打开一个标签页后，leaderF file popup异常

### ISSUE THREAD

**Issue by panpansuannai** [Yggdroot/LeaderF#826]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```NVIM v0.5.0-dev+1233-g82ac44d01
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az73-911

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: 
- 0
- Output of `:echo has("python3")`: 
- 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- no python provider
- Output of `:py3 print(sys.version)`: 
- 3.9.5 (default, May 24 2021, 12:50:35)                                                                       
[GCC 11.1.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
在一个标签页编辑c++源代码(使用coc-clangd)，但是有错误，coc-clangd会提示，如下图
![image](https://user-images.githubusercontent.com/59492930/123548940-85d18100-d799-11eb-8eb8-2ba08010c1bb.png)
，这时打开一个新标签页，调用leaderF file的popup窗口，会出错，如下 
![image](https://user-images.githubusercontent.com/59492930/123548948-8ec25280-d799-11eb-8135-a59cdced6364.png)
提示的异常代码cli.py，如下图
![image](https://user-images.githubusercontent.com/59492930/123549193-7a328a00-d79a-11eb-9aaf-60a66cfa90ca.png)

**Comment by panpansuannai** [comment]
修改text也出现了同样了python异常信息

**Comment by panpansuannai** [comment]
修改text后也出现了同样的python异常信息

**Comment by Yggdroot** [comment]
能否加个打印，把format参数都打印一下？

**Comment by panpansuannai** [comment]
> 能否加个打印，把format参数都打印一下？
![image](https://user-images.githubusercontent.com/59492930/123584429-edc4ad80-d813-11eb-81d2-e962ae99a896.png)


每次出错时part1_width都是负数，只要将part1_width = len(part1_width)改为part1_width = max(0,len(part1_width))就不会出现异常。


![image](https://user-images.githubusercontent.com/59492930/123584397-df769180-d813-11eb-8af5-fd4be0df5090.png)

**Comment by Yggdroot** [comment]
能把
input_win_width 
       part3_start = input_win_width - len(part3) - 2
        sep2_start = part3_start - len(sep)
        part2_start = sep2_start - 2 - len(part2)
        sep1_start = part2_start - len(sep)
        spin_start = sep1_start - 1 - len(spin)
        part1_width = spin_start - 1

这些变量也打印一下吗，我看看为什么会算出负值来。

**Comment by panpansuannai** [comment]
> 能把
> input_win_width
> part3_start = input_win_width - len(part3) - 2
> sep2_start = part3_start - len(sep)
> part2_start = sep2_start - 2 - len(part2)
> sep1_start = part2_start - len(sep)
> spin_start = sep1_start - 1 - len(spin)
> part1_width = spin_start - 1
> 
> 这些变量也打印一下吗，我看看为什么会算出负值来。
结果如下
![image](https://user-images.githubusercontent.com/59492930/123592887-6df11000-d820-11eb-9b71-1a1048397834.png)
打印的代码如下
![image](https://user-images.githubusercontent.com/59492930/123592922-79443b80-d820-11eb-8b1d-78dc989a44dd.png)

**Comment by Yggdroot** [comment]
input_win_width 的值是1 很不正常。
是使用coc-clangd有错误时才这样的对吧，正常情况下没问题吧？

**Comment by panpansuannai** [comment]
> input_win_width 的值是1 很不正常。
> 是使用coc-clangd有错误时才这样的对吧，正常情况下没问题吧？

正常情况没有问题，只有当coc-clangd的代码linting不通过时才会发生。

**Comment by Yggdroot** [comment]
我没装coc-clangd，不知道怎么复现。如果感兴趣，能否帮忙调试一下。
https://github.com/Yggdroot/LeaderF/blob/3899965851a0b3e59998f2b42e716eeee6bcc473/autoload/leaderf/python/leaderf/instance.py#L444-L488

看看self._popup_instance.input_win 的width为什么是1.

**Comment by panpansuannai** [comment]
之前使用的是nightly, 现在切换到了neovim的stable版本，已经不会出现这种情况了。
