### ISSUE TITLE
Open file from my current cursor?

### ISSUE THREAD

**Issue by simprince** [Yggdroot/LeaderF#83]
I must say, this is clearly better than fzf. The fact we have cache and don't need to reindex every time is awesome. I am working on projects with over 1 million files. fzf is too slow.

One suggestion/question: is there a way to search file based on my cursor position? Like if I am editing a line like this

ClassName.functionCall()
    ^

my cursor is at 'a' now. Can we perform a file search of ClassName?

**Comment by Yggdroot** [comment]
Now you can use `LeaderfFileCword`.

**Comment by simprince** [comment]
So awesome! Thanks.
