### ISSUE TITLE
Feature: Add a option to change gtags command.

### ISSUE THREAD

**Issue by mrbeardad** [Yggdroot/LeaderF#830]
- vim or neovim? 
    - [x] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

能不能给个接口让用户更改gtags的命令啊

### Expected behaviour
```vim
let Lf_GtagsCommandPath = '/bin/gogtags'
```

**Comment by mrbeardad** [comment]
好吧，我发现不太可能

**Comment by Yggdroot** [comment]
`g:Lf_Global` and `g:Lf_Gtags` are added.
