### ISSUE TITLE
Feature Request: restore cursor position when jumping to a file that is already loaded into a buffer.

### ISSUE THREAD

**Issue by dsummersl** [Yggdroot/LeaderF#833]
I use the `file` and `mru` extensions - when I select a file that is already loaded into a buffer (for instance, my alternate file `#`) Leaderf opens the file for me and puts the cursor at the top of the file.

This interrupts my work since I have to navigate back to the location I was at in the file. Since the file is already loaded into a buffer, it already has a location...it would be nice if Leaderf didn't lose that information when navigating to a file that is already loaded into a buffer.

**Comment by Yggdroot** [comment]
I cannot reproduce it. Could you show me your configuration about LeaderF? If necessary, a minimal vimrc is preferred.

**Comment by dsummersl** [comment]
I stripped my _vimrc down to the nubbins + leaderf and ... the bug is gone! Hopefully I can narrow it down to the source and post back here for posterity. Thank you!
