### ISSUE TITLE
Leaderf is 10x slower with `let g:Lf_PreviewInPopup =1`

### ISSUE THREAD

**Issue by eyalk11** [Yggdroot/LeaderF#836]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- 0
- Output of `:echo has("python3")`: 
- 1
- Output of `:py3 print(sys.version)`: 
- 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
 ```
let g:Lf_PreviewResult = {
			\ 'File': 0,
			\ 'Buffer': 1,
			\ 'Mru': 0,
			\ 'Tag': 0,
			\ 'BufTag': 1,
			\ 'Function': 1,
			\ 'Line': 1,
			\ 'Colorscheme': 0,
			\ 'Rg' : 1
			\}

l
let g:Lf_StlSeparator = { 'left': '', 'right': '' }

let g:Lf_StlColorscheme = 'powerline'
"Make c-h , c-l a valid option in leaderf
let g:Lf_CommandMap = {'<C-k>':['<C-h>'], '<C-j>':['<C-l>'], '<Down>': ['<C-j>','<Down>'], '<UP>': ['<C-k>','<UP>']}

let g:Lf_MruMaxFiles=100000
let g:Lf_ShowHidden  = 1
let g:Lf_MaxCount = 50000
let g:Lf_PreviewInPopup =1

let g:Lf_PopupHeight =0.5
let g:Lf_PopupWidth =0.9
let g:Lf_WindowPosition = 'popup'

""ideally would be called each time
let g:Lf_PopupPosition=[max([float2nr(&lines * 0.4),10]),1]
let g:Lf_CacheDirectory = "c:\\users\\ekarni\\.vim\\lcache"
let g:Lf_IndexTimeLimit =7
let g:Lf_RgConfig = [ "--max-columns=150"]
let g:Lf_WorkingDirectoryMode = 'c'
```

### Describe your question, feature request, or bug.

Leaderf is much slower with `let g:Lf_PreviewInPopup =1` compared to 0. It happens in all modes (buffers, files). 
I assume that the problem relates to loading of preview. When it is on, I wait a second or two after I press down or up (move up/down in lines ) before it gets to the right line. Sometimes it executes couple of those commands simultaneously at once , confusing me.

**Comment by Yggdroot** [comment]
After 
`let g:Lf_CommandMap = {'<C-k>':['<C-h>'], '<C-j>':['<C-l>'], '<Down>': ['<C-j>','<Down>'], '<UP>': ['<C-k>','<UP>']}` 
this setting, no key can navigate up and down.
And when you press up and down, it means `recall last/next input pattern from history`.

**Comment by eyalk11** [comment]
You would think, but I already changed a bit the code to switch them. Not very smart maybe.

**Comment by Yggdroot** [comment]
I don't understand what you mean. 
remove `let g:Lf_CommandMap = {'<C-k>':['<C-h>'], '<C-j>':['<C-l>'], '<Down>': ['<C-j>','<Down>'], '<UP>': ['<C-k>','<UP>']}`, just use `<C-j>` and `<C-K>` to navigate up and down, does the slow issue still happen?

**Comment by eyalk11** [comment]
Yes. The issue doesn't relate to this. I can navigate well up and down. The issue is that it is slow.

**Comment by Yggdroot** [comment]
I don't know why ` When it is on, I wait a second or two after I press down or up `. One ore two seconds are too slow, I have never encountered this scenario.

Could you remove all the plugins except for LeaderF and have a try?
