### ISSUE TITLE
Is there a local setting file in the project root path for porject level settings.

### ISSUE THREAD

**Issue by irreallich** [Yggdroot/LeaderF#837]
Hi,
     Leaderf is very good  software.   I use is for reading kernel, and  there is problem,  e.g:
1. project 1:
the source code we needed is in  
rootpath/arch/arm
rootpath/kernel
rootpath/include
rootpath/driver/base
...   
2. project 2:
the source code we needed is in  
rootpath/arch/arm64
rootpath/kernel
rootpath/include
rootpath/driver/base

Is there a local setting file in the project root path for porject level settings? 
for project1 , it browser necessary files in rootpath/arch/arm
for project2 , it browser necessary files in rootpath/arch/arm64

Thanks

**Comment by Yggdroot** [comment]
no
