### ISSUE TITLE
無法安裝：Intalling Error: Post-update hook for LeaderF ... Vim:E492: 不是編輯器的命令: LeaderfInstallCExtension

### ISSUE THREAD

**Issue by fhopecc** [Yggdroot/LeaderF#839]
- vim or neovim? 
    - [X] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`:vim 8.2 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python36.dll
- Output of `:py print(sys.version)`: 無法重新載入程式庫python27.dll
- Output of `:py3 print(sys.version)`:無法重新載入程式庫python36.dll 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
call plug#begin('~/vimfiles/plugin')
Plug 'Neur1n/neuims', {'on': 'IMSToggle'}
Plug 'skywind3000/vim-auto-popmenu'
Plug 'skywind3000/vim-dict'
Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
call plug#end()
### Describe your question, feature request, or bug.
I
### Steps to reproduce
執行 :PlugInstall
### Actual behaviour
installing Error: Post-update hook for LeaderF ... Vim:E492: 不是編輯器的命令: LeaderfInstallCExtension
### Expected behaviour
安裝完成

**Comment by Yggdroot** [comment]
Output of :echo has("python"): 0
Output of :echo has("python3"): 0
你的Vim不支持python。

**Comment by fhopecc** [comment]
我安裝python3.6.8 embedded後，並設定環境變數的路徑就可以使用了，感謝你寫出這麼好用的套件。

Yggdroot ***@***.***> 於 2021年8月23日 週一 下午9:24 寫道：

**Comment by Yggdroot** [comment]
😊
