### ISSUE TITLE
Switching buffer updates recent list

### ISSUE THREAD

**Issue by Leandros** [Yggdroot/LeaderF#84]
Is it possible that a recent update changed the behavior how switching between buffers interacted with the recent list? Right now it updates the last visited, after switching buffer, which I not remember it doing before. Can the old behavior be activated again?

**Comment by Yggdroot** [comment]
Sorry, I can not quite catch your point. Could you please describe in more detail?

**Comment by Leandros** [comment]
When I have vim open with multiple splits, changing focus between split will update the recent buffer list. If I remember correctly, this used to be different.

![2017-11-13 18_34_13](https://user-images.githubusercontent.com/396475/32739813-42320b0a-c8a1-11e7-91dc-fb3c8f285875.gif)

**Comment by Yggdroot** [comment]
This works as designed. Always put the current file at the bottom, and at the top is the last visited file. So you can just press `Enter` to switch to last visited file.
The behavior has never changed.
