### ISSUE TITLE
how can i set the transparency of popup window？

### ISSUE THREAD

**Issue by lsaint** [Yggdroot/LeaderF#845]
I set my vim's backgoup with 
`highlight Normal     ctermbg=NONE guibg=NONE
`
but the popup window in LeaderF didn't work with it

it didn't work with 
`highlight Pmenu     ctermbg=NONE guibg=NONE
`
either.

so how can i do it?

![image](https://user-images.githubusercontent.com/896079/133883649-628a8c47-a24d-4f28-9746-b84bbee383e5.png)

**Comment by Yggdroot** [comment]
there seems no way.
