### ISSUE TITLE
无法通过gtags索引到C++的类定义等

### ISSUE THREAD

**Issue by GoGoTryAgain** [Yggdroot/LeaderF#846]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: vim8.2
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

leaderf 通过gtags索引，发现并不能索引到头文件里面的代码。

我是用的c++代码，就写了一个类，gtags -r和-d都无法索引到头文件的函数以及类定义。

vim配置用的就是leaderf 的readme的填写的内容

### Steps to reproduce

写一个cpp和一个.h文件。 类定义与类方法定义在h文件内。  
leaderf gtags--update 生成索引。
查找cpp里面的类名定义，以及定义和实现在.h文件内的方法

### Actual behaviour

无法找到定义以及引用

**Comment by Yggdroot** [comment]
Could you describe in more detail please?

**Comment by GoGoTryAgain** [comment]
leaderf 通过gtags索引，发现并不能索引到头文件里面的代码。  

我是用的c++代码，就写了一个类，gtags -r和-d都无法索引到头文件的函数以及类定义。   

vim配置用的就是leaderf 的readme的填写的内容

> Could you describe in more detail please?

**Comment by GoGoTryAgain** [comment]
> Could you describe in more detail please?

不好意思，输入问题的时候不小心敲了个回车，直接发出来了。  已经修改了

**Comment by Yggdroot** [comment]
直接Leaderf gtags 有输出吗？ 如果有的话，我也不知道怎么办，可能是gtags本身的问题吧。

**Comment by GoGoTryAgain** [comment]
> 直接Leaderf gtags 有输出吗？ 如果有的话，我也不知道怎么办，可能是gtags本身的问题吧。

没有.h里面的输出，只有cpp的tags

**Comment by GoGoTryAgain** [comment]
在vimrc里面添加 let $GTAGSFORCECPP = 1  看Leaderf gtags里面可以生成类与头文件里面方法的tag了。   但是leaderf gtags -d,和leaderf gtags -r还是无法搜到写正在头文件里面的类定义和方法。   只有leaderf gtags -s 可以搜到。

**Comment by Yggdroot** [comment]
这应该是gtags本身的局限。
