### ISSUE TITLE
"Leaderf function" command can not work on file with extention ".hc"

### ISSUE THREAD

**Issue by donkeymoto** [Yggdroot/LeaderF#848]
### Describe your question, feature request, or bug.
when I open a ".c" source file, Leaderf function can work well and show me the function list; while I change the file extention to ".hc", reopen the file with vim, then "Leaderf function" command will output "No content!", which i suppose the file is not recognized as a "c" source.
### Steps to reproduce
1. vi foo.hc
2. Leaderf function

### Actual behaviour
"No contents"
### Expected behaviour
A function list of current file is showed.(since actually currentj source file is a c file).

**Comment by Yggdroot** [comment]
Please try:

```vim
au BufWinEnter *.hc setlocal ft=c
let g:Lf_CtagsFuncOpts = {
            \ 'c': '--language-force=c --c-kinds=fp',
            \ }
```

**Comment by donkeymoto** [comment]
> Please try:
> 
> ```viml
> au BufWinEnter *.hc setlocal ft=c
> let g:Lf_CtagsFuncOpts = {
>             \ 'c': '--language-force=c --c-kinds=fp',
>             \ }
> ```

Tested and it works well.
Thanks.
