### ISSUE TITLE
LeaderfHelp open in vertical split by default (<CR>)

### ISSUE THREAD

**Issue by jlxz** [Yggdroot/LeaderF#849]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
I would like to configure LeaderfHelp to open in a vertical split when I press <CR> instead of opening a new buffer.
I'm trying to achieve this using the g:Lf_NormalMap like this:
```
let g:Lf_NormalMap = {
    \ "Help": [["<CR>",':exec g:Lf_py "helpExplManager.accept(''v'')"<CR>']]
    \}
```
But it's not working.

Thanks.

**Comment by Yggdroot** [comment]
This command works in normal mode, i.e, press tab to switch to normal mode and then Enter to open in a vertical split window.

**Comment by linjiX** [comment]
@Yggdroot Is that possible to open help buffer in split window by <CR> in command mode, just like the old behavior (before f80ff99c434d4d233a4a8bf2d116289b6619fbcd)?
