### ISSUE TITLE
[Question] run zt after jumping to a function

### ISSUE THREAD

**Issue by pablogipi** [Yggdroot/LeaderF#853]
Hello.
One thing I do again and again is jump to a function using _LeaderFFunction_ and then press `zt` to put the start of the function to the top of the window, it just makes me easier to read the function code.
Is there any way to do this in one  go, basically setup a command to be run after leaderf jumps to the junction?
Thanks

**Comment by Yggdroot** [comment]
Currently, there is no way.

pablogipi ***@***.***> 于2021年10月22日周五 上午3:11写道：
