### ISSUE TITLE
用vim-plug安装了leaderf插件，一切正常，但是打开vim后输入“:LeaderF" 后就收到错误了

### ISSUE THREAD

**Issue by sgyhunter** [Yggdroot/LeaderF#855]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by sgyhunter** [comment]
在linux tree 中打开vim，敲入:Leaderf memory.c 回车， 得到如下错误：

Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'anyHub' is not defined

- VIM
- VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 20 2021 11:42:42) 
- Output of :echo has("python"): 0
- Output of :echo has("python3"):1
- Output of :echo &pythondll(only vim, not neovim): 空
- Output of :echo &pythonthreedll(only vim, not neovim): 空
- Output of :py print(sys.version):
- Output of :py3 print(sys.version): 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0]
- Output of :echo g:Lf_Debug_Cmd: Pattern not found: Lf_Debug_Cmd 
- Output of :echo g:Lf_FilesFromCache: E492: Not an editor command: Pattern not found: Lf_Debug_Cmd

**Comment by Yggdroot** [comment]
感觉是没安装成功。
