### ISSUE TITLE
[Feature request] a new command to search vim ':map' output

### ISSUE THREAD

**Issue by rickywxg** [Yggdroot/LeaderF#856]
### Describe your question, feature request, or bug.

It would be useful to be able to search vim key mappings. It is common we setup some key mappings but forgot it.
We can use ':map' or ':nmap' to list the mappings but that is not searchable.

### Expected behaviour

Have a new LeaderfKeyMap command to search the output of ':map" command

**Comment by Yggdroot** [comment]
https://github.com/Freed-Wu/LeaderF-keymaps
Maybe it meets your request.

**Comment by rickywxg** [comment]
Hi friends,
Thanks for your reply.
I just had a try, this tool cannot search vim key maps. Don't know what is for.

**Comment by FahimAnayet** [comment]
Hi,
I've cloned https://github.com/Yggdroot/LeaderF-marks repo and modified to work with maps. Hope it'll help.
https://github.com/FahimAnayet/LeaderF-map

**Comment by rickywxg** [comment]
Hi @FahimAnayet,
Sorry for late reply. Thanks a lot for your work on this. https://github.com/FahimAnayet/LeaderF-map is exactly what I was looking for.
