### ISSUE TITLE
Border is not aligned properly

### ISSUE THREAD

**Issue by lu5je0** [Yggdroot/LeaderF#857]
neovim version:NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wex
tra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes
-Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED
_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neov
im-20210927-1441-demfsz/neovim-0.5.1/build/config -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/src -I/usr/l
ocal/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/incl
ude -I/tmp/neovim-20210927-1441-demfsz/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20210927-1441-demfsz/neo
vim-0.5.1/build/include

LeaderF commit: 48fbae95f5ba26affb490488eb606ff127ccb0da

LeaderF config:
let g:Lf_StlSeparator = { 'left': '', 'right': '' }
let g:Lf_WindowPosition = 'popup'
let g:Lf_ShortcutF = "<leader>ff"
let g:Lf_CommandMap = {'<C-J>': ['<DOWN>'], '<C-K>': ['<UP>']}
let g:Lf_ShortcutB = ""
let g:Lf_PreviewInPopup = 1

let g:Lf_WildIgnore = {
            \ 'dir': ['.svn','.git','.hg'],
            \ 'file': ['*.sw?','~$*','*.bak','*.exe','*.o','*.so','*.py[co]']
            \}

let g:Lf_PopupHeight = 0.7
 
![image](https://user-images.githubusercontent.com/17700877/142339936-d5a03604-4704-4b91-a482-7968a01dd459.png)

**Comment by Yggdroot** [comment]
What if `let g:Lf_StlSeparator = { 'left': '', 'right': '' }` ?

**Comment by lu5je0** [comment]
![image](https://user-images.githubusercontent.com/17700877/142647391-5fe435e8-9733-49be-afd0-0e5c43c2e636.png)
But it is same after remove this line.

**Comment by lu5je0** [comment]
I have found the setting that caused this. It can be reproduced by set signcolumn=auto:1-2

**Comment by Yggdroot** [comment]
This issue won't be fixed in LeaderF because of eac1c2b8.

**Comment by lu5je0** [comment]
Ok, but It seems no flicker on neovim.

**Comment by Yggdroot** [comment]
You can have a workaround: `autocmd FileType *  setlocal signcolumn=no`.
