### ISSUE TITLE
LeaderF rg stuck nvim in big projects

### ISSUE THREAD

**Issue by liyiheng** [Yggdroot/LeaderF#865]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`:  E319: No "python" provider found. Run ":checkhealth provider"
- Output of `:py3 print(sys.version)`: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc. Arch Linux with WSL2
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

100% CPU
```
/usr/sbin/python3-cimport sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; neovim.start_host()script_host.py
```
![image](https://user-images.githubusercontent.com/16461061/147813320-84e40f08-1d73-4782-bea0-835b01019ad1.png)

### Steps to reproduce
```
:LeaderF rg 
Enter
type something
```

### Actual behaviour
nvim doesnt response

### Expected behaviour
Get search result

**Comment by Yggdroot** [comment]
Where is `/usr/sbin/python3-cimport sys; sys.path = list(filter(lambda x: x != "", sys.path)); import neovim; neovim.start_host()script_host.py` from? It's not LeaderF's code.

**Comment by liyiheng** [comment]
FYI:   It's [pynvim/plugin/script_host.py](https://github.com/neovim/pynvim/blob/master/pynvim/plugin/script_host.py)
LeaderF rg works well with vim,  I'm currently using vim to move around this issue.
