### ISSUE TITLE
<Leaderf file> file order not expect

### ISSUE THREAD

**Issue by chenghua-root** [Yggdroot/LeaderF#866]
- vim or neovim? 
    - [y] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun  6 2020 11:49:29)
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [y] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
![image](https://user-images.githubusercontent.com/53387415/148734256-56eb504d-8164-4ebe-b294-8bd2f7704ebb.png)
noremap <leader>** :Leaderf file<cr>  the files result order is not expected

### Expected behaviour
src/bsr/metadata/file.h  should be in advance of 3rdparty/fio-2.8/file.h

  1   src/bsr/metadata/file.h
  2   3rdparty/fio-2.8/file.h
  3   src/bsr/metadata/file_sys.h
  4   src/bsr/metadata/file.cc

**Comment by Yggdroot** [comment]
I can not reproduce. Could you show me your configurations about LeaderF please?

**Comment by Yggdroot** [comment]
Make sure you don't set `let g:Lf_EmptyQuery = 0`.
