### ISSUE TITLE
[Feature Request]: Option to find/follow file symlinks

### ISSUE THREAD

**Issue by karlredman** [Yggdroot/LeaderF#867]
# [Feature request]: Option to find/open file symlinks

- vim or neovim?
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:
```
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): N/A
- Output of `:echo &pythonthreedll`(only vim, not neovim): N/A
- Output of `:py print(sys.version)`: N/A
- Output of `:py3 print(sys.version)`:
```
3.9.0 (default, Jan 20 2021, 13:44:38)
[GCC 8.3.0]
```
- Output of `:echo g:Lf_Debug_Cmd`: N/A
- Output of `:echo g:Lf_FilesFromCache`: N/A
- Operating system:
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

### Describe your question, feature request, or bug.

- I've read through the documentation and there is no information (that I can find) about LeaderF being able to open/find file symlinks.
- I'm aware of the directory 'follow' switch but the finder does not recognize symlinks at all.
- Is this a possible or wanted feature? I find that I'm using `:Explore` to read my symlinked files...

**Comment by Yggdroot** [comment]
Have you tried this option?

https://github.com/Yggdroot/LeaderF/blob/5626a1f71bcc2dd7a74156f22c53734621c12433/doc/leaderf.txt#L133-L137

**Comment by Yggdroot** [comment]
After run `Leaderf file`, what is the output of `:echo g:Lf_Debug_Cmd` ?
Are the symlink files added into .gitignore?
Please have a try `Leaderf file --no-ignore`?

**Comment by karlredman** [comment]
OMG. I guess I misunderstood the meaning behind `--no-ignore`. 
That works perfectly!
Thank you for your patience and the quick replies.
