### ISSUE TITLE
请问在编辑gb18030文件时，如何全文搜索

### ISSUE THREAD

**Issue by gamark** [Yggdroot/LeaderF#868]
~/.vim/bin/nvim --version
NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/seal/workspace/neovim/build/config -I/home/seal/workspace/neovim/src -I/home/seal/workspace/neovim/.deps/usr/include -I/usr/include -I/home/seal/workspace/neovim/build/src/nvim/auto -I/home/seal/workspace/neovim/build/include
Compiled by seal@host-192-168-21-25

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/seal/FirServer/thirdpart_seal/share/nvim"

Run :checkhealth for more info
- Configurations related to LeaderF in vimrc: 
set encoding=utf-8
set termencoding=gb18030
set fileencodings=utf-8,gbk,big5,gb18030

### Describe your question, feature request, or bug.
使用leaderf rg打开悬浮搜索时，搜索框能输入中文 ，但列表里看不到中文
nvim运行在LINUX,终端通过WINDOWS下的securecrt连接到LINUX， 终端设置的编码也同gb18030
环境变量:
![image](https://user-images.githubusercontent.com/11284639/149713137-61656e54-f2e3-4f8d-8f80-1758119424dd.png)
终端设置:
![image](https://user-images.githubusercontent.com/11284639/149717298-8861d017-e24d-4500-9c9e-adf9fc15e220.png)

vimrc编码设置:
set encoding=utf-8
set termencoding=gb18030
set makeencoding=gb18030
set fileencodings=utf-8,gbk,big5,gb18030 
能正常输入中文 ，但在leaderf悬浮中看不到gb18030的中文，也无法完成搜索:请看第34行代码
![image](https://user-images.githubusercontent.com/11284639/149717107-22c3a95d-eeb4-40b9-a144-a7f75b491251.png)

**Comment by Yggdroot** [comment]
你直接运行rg命令，看看输出，因为leaderf仅仅是把rg的输出显示出来，如果rg输出是这样，那就是rg的问题。

**Comment by gamark** [comment]
> 你直接运行rg命令，看看输出，因为leaderf仅仅是把rg的输出显示出来，如果rg输出是这样，那就是rg的问题。

感谢回答，使用不带参数的rg，确实搜不出来。是rg的问题。用ag可以搜出来，leaderf支持使用ag来替换rg吗
![image](https://user-images.githubusercontent.com/11284639/150065958-f3e21245-3863-4605-beaa-f12f5f8cf88b.png)

**Comment by gamark** [comment]
> 你直接运行rg命令，看看输出，因为leaderf仅仅是把rg的输出显示出来，如果rg输出是这样，那就是rg的问题。

 let g:Lf_DefaultExternalTool = 'ag' 使用这个设置会报错，无法用ag来打开搜索
![image](https://user-images.githubusercontent.com/11284639/150067020-c943e195-a141-4c72-9401-3fe8934ef0ab.png)

**Comment by gamark** [comment]
> 你直接运行rg命令，看看输出，因为leaderf仅仅是把rg的输出显示出来，如果rg输出是这样，那就是rg的问题。

感谢，搞定了，使用:Leaderf rg -Egb18030, 这样打开可以搜索了。

**Comment by Yggdroot** [comment]
OK
