### ISSUE TITLE
plugin crashed when I type <leader>f

### ISSUE THREAD

**Issue by licett** [Yggdroot/LeaderF#87]
![tim 20171104165305](https://user-images.githubusercontent.com/5344478/32403946-d8fc4d52-c180-11e7-8677-24b715c4ea5c.png)

vim version:8.0
python enable: 1

Is it releated to file encoding? 
encoding setting of my vim:
![2](https://user-images.githubusercontent.com/5344478/32403967-3b1b93c6-c181-11e7-89e2-72556465e469.png)

**Comment by licett** [comment]
well, there is no configuration about leaderF in my vimrc. 
So I think, all behaviors of leaderf is in default mode?

**Comment by Yggdroot** [comment]
Please update LeaderF and have a try.

**Comment by licett** [comment]
![123](https://user-images.githubusercontent.com/5344478/32601496-cd1c3474-c57d-11e7-9c64-9462149c2f46.png)
I update the plugin by command PluginUpdate, but it seems that the newer one has some problem in finding files

**Comment by Yggdroot** [comment]
What problem?

**Comment by Yggdroot** [comment]
Do you have `rg` or `ag` installed?

**Comment by Yggdroot** [comment]
What is the output of `echo executable('sed')`?

**Comment by licett** [comment]
echo executable('sed') : 1

"Do you have rg or ag installed?"
What do you mean? Do you mean if I have installed a plugin named "rg"?
Here is all of my plugins:

 Plugin 'gmarik/Vundle.vim'
 Plugin 'tmhedberg/SimpylFold'
 Bundle 'Valloric/YouCompleteMe'
 Plugin 'rdnetto/YCM-Generator'
 Plugin 'aur-archive/vim-lookupfile'
 Plugin 'ervandew/supertab'
 Plugin 'vim-scripts/taglist.vim'
 Plugin 'vim-scripts/timestamp.vim'
 Plugin 'vim-scripts/c.vim'
 Plugin 'vim-scripts/indentpython.vim'
 Plugin 'scrooloose/nerdtree'
 Plugin 'scrooloose/syntastic'
 Plugin 'Yggdroot/LeaderF'
 Plugin 'bling/vim-airline'
 Plugin 'majutsushi/tagbar'
 Plugin 'scrooloose/nerdcommenter'
 Plugin 'a.vim'

**Comment by Yggdroot** [comment]
`rg` I mean https://github.com/BurntSushi/ripgrep, which is a tool like `grep`.
`ag` I mean https://github.com/ggreer/the_silver_searcher.

I think the root cause is that the `find` command you are using is the dos command, not the linux command. Since you have `sed`, you should make sure the system using `find` which is in the same directory as `sed`.

**Comment by licett** [comment]
In order to remain other windows bat files "unpolluted" , gnu versioned find is renamed "gfind" in my system. I think it is the cause.
So is it a good solution if I change the command which is called by LeaderF in the source file?
Do you have other suggestiones?

**Comment by licett** [comment]
I will do a test to verify if it is the cause tommorrow and tell you the result.

**Comment by Yggdroot** [comment]
You can install `rg`, make sure `echo executable('rg')` is 1, then LeaderF can build the index using it instead of `find`.

**Comment by licett** [comment]
Thanks for your advice, I can use this plugin now!
But how to change the default directory which LeaderF searches?
I mean, does this plugin has several configurations that I can use in vimrc to manage that?

**Comment by licett** [comment]
well, I got it!
Adding 'let g:Lf_WorkingDirectoryMode = 'ac'' to vimrc makes it work!
A wonderful plugin!
Thank you!
