### ISSUE TITLE
LeaderfFunction 能够查找函数定义吗

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#870]
WIN10+GVIM8.2+Lf最新版本
LeaderfFunction 好像只能在打开的文件BUF中查找 那能不能在当前目录下所有文件中查找了？相当于是
查找函数的定义 我需要在LUA中查找函数 用RG命令可以实现 但是效果不好 

> Leaderf! rg function --cword
原因之一：不能将函数名即(--cword)作为一个单词来查找
原因之二：function会高亮

**Comment by Yggdroot** [comment]
可以使用Leaderf tag或者gtags。

**Comment by gVimer** [comment]
因为是对LUA所以选TAG了
`nnoremap F :<C-U><C-R>=printf("Leaderf tag --input %s",expand("<cword>"))<CR><CR>
`
问题1：会闪一下 就是先显示了全部的TAG 然后再过滤了 体验不是很好
![QQPlayer_Dum8jHhBKs](https://user-images.githubusercontent.com/6241431/150626343-241e8a05-fdb8-4606-bfb7-d308ba17731d.gif)
问题2：将上面的 Leaderf变成Leaderf后不会显示结果
![image](https://user-images.githubusercontent.com/6241431/150626377-57acb3cb-78f8-41b7-b05d-19b90b823c8e.png)
需要按下TAB切换下模式才显示出来
![image](https://user-images.githubusercontent.com/6241431/150626391-a7057737-e7f5-458b-b17c-87c2e7db5d7d.png)
问题三：显示结果不精确
![image](https://user-images.githubusercontent.com/6241431/150626423-33f7944a-91da-4568-ad30-c563fbcf3388.png)
如果能跟ts命令结合起来可能会好点儿 但是不知道如何做
这个是ts open的结果
![image](https://user-images.githubusercontent.com/6241431/150626448-472727ad-2e68-49f3-ab74-c1f6c7969aca.png)

**Comment by gVimer** [comment]
算了 用RG凑合用吧 不打扰大神了
`nnoremap F :<C-U><C-R>=printf("Leaderf! rg function.*\(%s\)[(]",expand("<cword>"))<CR><CR>
`

**Comment by gVimer** [comment]
能加个参数指定预览窗口的位置吗 三个选项：
zz：将光标置于屏幕的中间
zt: 将光标移动到屏幕的顶部
zb：将光标移动到屏幕的底部

**Comment by gVimer** [comment]
针对LUA和Python
`function! GoToFuncDef()
    let g:Lf_RgHighlightInPreview=0
    if &filetype==?'LUA'
       let CMD=printf("function\\s+.*[:.]%s\\(",expand("<cword>"))
    elseif &filetype==?'Python'
       let CMD=printf("def\\s+%s\\(",expand("<cword>"))
    endif
    let CMD="Leaderf! rg --nowrap ".CMD
    exec CMD
endfunction

"查找函数定义
nnoremap F : call GoToFuncDef()<CR>`
