### ISSUE TITLE
Will leaderf support force case-insensitive option in file explorer?

### ISSUE THREAD

**Issue by raoweijian** [Yggdroot/LeaderF#871]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:  NVIM v0.5.1
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.9.9
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
If the search text contains uppercase characters, the search will be case-sensitive. But what if I want a force it to be case-insensitve?
For example, in ruby projects, a class `TaskOne` is defined in `task_one.rb`. 
I want to find the file by searching the class name,

### Steps to reproduce
Search `TaskOne`

### Actual behaviour
The file `task_one.rb` was not listed

### Expected behaviour
The file `task_one.rb` can be found

**Comment by Yggdroot** [comment]
Fixed.

**Comment by raoweijian** [comment]
Great thanks!
