### ISSUE TITLE
使用rg或gtags搜索得到内容, 能否再通过目录二次搜索?

### ISSUE THREAD

**Issue by RsrnlWysxr** [Yggdroot/LeaderF#872]
- vim or neovim? 
    - [ ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
可以

**Comment by Yggdroot** [comment]
可以

**Comment by RsrnlWysxr** [comment]
> 可以

请问具体怎么操作
我使用 LeaderF gtag --by-context 会出现多个结果, 我再输入, 只会基于结果的所在行再此过滤, 而不能匹配到文件路径

**Comment by Yggdroot** [comment]
--match-path

**Comment by RsrnlWysxr** [comment]
> --match-path

非常感谢!
