### ISSUE TITLE
Bug - Miss argument or Not need escape function

### ISSUE THREAD

**Issue by FloatingLab** [Yggdroot/LeaderF#874]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.2
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.10.so.1.0
- Output of `:py3 print(sys.version)`: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vim
nmap <unique> <leader>frg <plug>LeaderfRgWORDLiteralBoundary
```
### Describe your question, feature request, or bug.
Bug - Miss argument or Not need escape function

### Steps to reproduce
1. Set the mapping command to LeaderfRgWORDLiteralBoundary
2. Use it in Vim

### Actual behaviour
Get error message: "E119: Not enough arguments for function: escape"

### Expected behaviour
Get ":Leaderf rg -F -w -e \<cWORD>" in the command line

Note: It works fine when I remove the escape()
https://github.com/Yggdroot/LeaderF/blob/bafe5cda6371035220ec7c12351e6922afd691b3/autoload/leaderf/Rg.vim#L76

**Comment by Yggdroot** [comment]
Fixed.
