### ISSUE TITLE
The performance of regex mode is worse than fuzzy mode

### ISSUE THREAD

**Issue by krisfans** [Yggdroot/LeaderF#875]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: nvim 0.6.1
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
`let g:Lf_DefaultMode = "regex" `
### Describe your question, feature request, or bug.
The performance of regex mode is worse than fuzzy mode

### Expected behaviour
The Regex pattern should perform as well as Fuzzy

在体验过程中发现，正则模式的相应速度比模糊模式差。正则模式的结果显示跟不上输入，在fuzzy模式则没有这个问题

**Comment by Yggdroot** [comment]
正常现象，正则就是慢。

**Comment by krisfans** [comment]
我想完全匹配某个字符序列，只能使用正则模式吗？主要是模糊模式也能搜到，但是候选结果太多了

**Comment by Yggdroot** [comment]
目前是这样。你如果完全匹配某个字符序列，用模糊模式候选结果会排在前面应该。
