### ISSUE TITLE
设置Colorscheme不生效

### ISSUE THREAD

**Issue by RsrnlWysxr** [Yggdroot/LeaderF#877]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
    nvim  0.7.0
- Output of `:echo has("python")`: 
    yes
- Output of `:echo has("python3")`: 
     yes
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
let g:Lf_ShowDevIcons = 1
let g:Lf_HideHelp = 1
let g:Lf_WindowPosition = 'popup'
let g:Lf_PopupPosition = [15, 0]
let g:Lf_PopupPreviewPosition = 'bottom'
let g:Lf_AutoResize = 1
let g:Lf_PreviewResult = {
		\ 'File': 1,
		\ 'Buffer': 1,
		\ 'Mru': 1,
		\ 'Tag': 1,
		\ 'BufTag': 1,
		\ 'Function': 1,
		\ 'Line': 1,
		\ 'Colorscheme': 1,
		\ 'Rg': 1,
		\ 'Gtags': 1
		\}

let g:Lf_StlColorscheme = "powerline"
let g:Lf_PopupColorscheme = "gruvbox_material"

### Describe your question, feature request, or bug.

我想让整个搜索弹窗的背景是透明的, 我修改了LeaderF/autoload/leaderf/colorscheme/popup/下所有的主题的guibg和ctermbg为NONE, 但是都没有生效

我尝试通过配置更换颜色主题, 但是好像也不生效

**Comment by Yggdroot** [comment]
让背景透明好像无法做到。

**Comment by RsrnlWysxr** [comment]
> 让背景透明好像无法做到。

谢谢
