### ISSUE TITLE
如何为LeaderF新增插件

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#880]
个人想扩展LeaderF插件可以搜索的List，想请教下，有没有相关的文档指导

**Comment by Yggdroot** [comment]
可以参考https://github.com/Yggdroot/LeaderF/issues/144#issuecomment-540008950
如果用Python写，可以参考https://github.com/Yggdroot/LeaderF-marks

**Comment by MerliniKing** [comment]
thx
