### ISSUE TITLE
使用leaderf gtags查找tag时，如果携带了--by-context参数，则--result 参数不生效，格式无法调整

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#881]
- vim or neovim? 
    - [ ] vim
    - [ x ] neovim
- Output of `vim --version` or `nvim --version`: 
NVIM v0.6.1
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/chi/neovim/build/config -I/home/chi/neovim/src -I/home/chi/neovim/.deps/usr/include -I/usr/include -I/home/chi/neovim/build/src/nvim/auto -I/home/chi/neovim/build/include
Compiled by chi@W00573115

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/chi/neovim/share/nvim"

Run :checkhealth for more info

- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
2.7.18 (default, Mar  8 2021, 13:02:45)
[GCC 9.3.0]
- Output of `:py3 print(sys.version)`: 
3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
undefined variable
- Output of `:echo g:Lf_FilesFromCache`: 
undefined variable
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] wsl.
- Configurations related to LeaderF in vimrc: 
 let g:Lf_Gtagslabel = 'native-pygments' " gtags 默认 C/C++/Java 等六种原生支持的代码直接使用 gtags 本地分析器，而>  其他语言使用 pygments 模块
  " 自动生成Gtags
  let g:Lf_GtagsAutoGenerate = 1
  " 限制输出的行长度，否则会卡死                                                                                      let g:Lf_RgConfig = [ "--max-columns=150", ]
  " 索引存储位置
  let g:Lf_CacheDirectory = '/home/chi/.lf_gtags'
  let g:Lf_PreviewCode    = 1                                                                                         let g:Lf_ShowDevIcons = 0

  let g:Lf_PreviewResult = { 'Rg': 1, 'Gtags': 1, 'Colorscheme': 1 }
  " 不使用git目录信息，对整个根目录建立索引，同时解决file找不到的问题                                                 let g:Lf_GtagsSource = 0
  let g:Lf_DevIconsFont = "Agave"
  " 可以用来解决中文目录问题，gtags无法处理中文字符
  let g:Lf_WildIgnore = {                                                                                                 ¦   ¦   \ 'dir': ['cloudmonitor', ],
      ¦   ¦   \ 'file': []
      ¦   ¦   \}
  " 取消<leader>f 和 <leader>b的绑定，避免干扰下面的key绑定
  let g:Lf_ShortcutF = ''
  let g:Lf_ShortcutB = ''                                                                                           
  nnoremap <leader>f  :LeaderfSelf<CR>
  nnoremap <leader>fe :Leaderf file --nameOnly --no-ignore<CR>
  nnoremap <leader>ff :Leaderf! --nowrap function<CR>
  nnoremap <leader>fb :Leaderf! buffer<CR>                                                                            nnoremap <leader>fm :Leaderf! mru<CR>

  nnoremap <leader>fg :<C-U><C-R>=printf("Leaderf! gtags --auto-jump --by-context --literal %s", "")<CR><CR>
  nnoremap <leader>fa :Leaderf gtags<CR>
  nnoremap <leader>f; :Leaderf gtags --next<CR>
  nnoremap <leader>f' :Leaderf gtags --next<CR>                                                                       nnoremap <leader>fs :Leaderf rg -F -S --fuzzy --nowrap<CR>

  nnoremap <leader>fo :Leaderf! bufTag<CR>
  nnoremap <leader>fp :Leaderf --recall<CR>

### Describe your question, feature request, or bug.
使用leaderf gtags查找tag时，如果携带了--by-context参数，则--result 参数不生效，格式无法调整

### Steps to reproduce
:Leaderf gtags --result ctags-x --by-context --auto-jump --literal

### Actual behaviour
实际输出：
文件名 | 行号 | tag引用处的内容

### Expected behaviour
期待输出：
tag | 行号 | 文件名 |  tag引用处的内容

**Comment by MerliniKing** [comment]
同时，我发现使用:Leaderf gtags --result xxxxx --literal查找时，ctags格式加载速度远高于ctags-x格式，项目中一共有130w左右tag
使用ctags格式查找时，加载所有tag，大约要耗时5s
使用ctags-x格式查找时，加载所有tag，大约要耗时30s

**Comment by Yggdroot** [comment]
修好了。
速度问题不清楚，后台都是调用同一条命令，只是参数`--result`的值不一样。

**Comment by MerliniKing** [comment]
更新了后，参数已生效 ，thx

**Comment by MerliniKing** [comment]
不同格式速度的问题，我猜测，是否是因为ctags-x相对于ctags格式，需要额外加载tag应用处的代码，导致加载速度变慢呢？

**Comment by Yggdroot** [comment]
这是global内部实现的问题。
