### ISSUE TITLE
建议给神器LeaderF增加预览选项和向左向右移动一个单词的功能

### ISSUE THREAD

**Issue by persytry** [Yggdroot/LeaderF#882]
LeaderF真的是神器,已经离不开它了,感谢作者的倾情奉献!!!
建议新增功能:
1. 增加预览选项,就是在ex模式下输入`Leaderf --preview`可以在弹出的窗口中直接展现出预览界面, 预览界面随着上下选择而变化
2. 建议增加快捷键可以在leaderf的弹出窗口中向左或向右移动一个单词

感谢百忙中审阅!

**Comment by Yggdroot** [comment]
对于1，现在就支持预览界面随着上下选择而变化，只是不是通过`--preview`设置的。你的意思是增加`--preview`？
2. 移动一个单词是出于什么需求呢？目前能想到的是移动一个字符更方便实现。

**Comment by persytry** [comment]
对于1, 是的, 是加一个--preview选项,或全局配置,可以在结果窗口上下移动的时候,自动显示出当前选择项的预览窗口,而现在每当向上或向下选择的时候,需要再ctrl+p才能展示预览窗口.
对于第2条, 出于想把所有操作都vim化的强迫症+完美主义倾向产生的需求, 嘿嘿, 建议支持一下, 比如vim本身就支持对"Command-line editing"的快捷键. 
以下是我对command-line的一些键位(输入模式下我都是采用的emacs键位):
cnoremap <C-a> <Home>
cnoremap <C-f> <Right>
cnoremap <C-b> <Left>
cnoremap <M-f> <S-Right>
cnoremap <M-b> <S-Left>
cnoremap <C-d> <Del>
cnoremap <C-y> <C-r>+
而leaderf的输入框也类似于command-line, 我想对二者进行统一的按键绑定.
noremap <leader>rs :<C-U><C-R>=printf("Leaderf rg %s ", expand("<cword>"))<CR>
当我键入快捷键<leader>rs后, 我可能需要全字匹配, 那么我希望快速跳过前面一个词,然后输入一个"-w"选项, 我还有可能会删除后面的一个字符等.
所以我建议leaderf的输入框里增加多一些快捷键, 尽量覆盖vim的command-line的快捷键, 把二者的键位统一成一样,感觉意义挺大.
谢谢, 如果您同意做这两个需求的话, 我就不再自己尝试去做了

**Comment by Yggdroot** [comment]
`    let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0, 'Rg': 0, 'File': 1, 'Mru': 1, 'Colorscheme': 1 }`
值为1就会自动预览，不用按ctrl-p。不过加个`--auto-preview`倒可以考虑。

2. 不是太明白，你说的好像是vim的command-line, 不是LeaderF的输入框。
vim 本身有一些快捷键的：
```
<C-B>:  home
<C-E>: end
<C-W>: delete a word
<S-Left>
<S-Right>
```

**Comment by persytry** [comment]
好的,谢谢.
LeaderF的输入框能不能支持一下<S-Left>,<S-Right>和删除后面的一个单词呢? 我试了下, LeaderF的输入框的<S-Left>和<S-Right>貌似没有任何反应.
另外, 我又想到了一个需求, 就是当我通过--recall选项把窗口重新打开以后, 能不能增加一个快捷键让它stayOpen(或者可以切换stayOpen状态)呢?

**Comment by persytry** [comment]
为什么要增加向左或向右移动一个单词呢?
是因为当我通过一些快捷键打开LeaderF的输入框之后, 我可能需要再填或修改一些字符,比如向左移动一个单词后,加一个`-w`或`--stayOpen`选项之类的, 或者修改我要查询的字符串, 比如给字符串再增加一些前缀(包名)之类的

**Comment by persytry** [comment]
对了, 既然已经有了`g:Lf_PreviewResult`可以配置, 那么`--auto-preview`选项感觉就没什么必要了

**Comment by Yggdroot** [comment]
> 另外, 我又想到了一个需求, 就是当我通过--recall选项把窗口重新打开以后, 能不能增加一个快捷键让它stayOpen(或者可以切换stayOpen状态)呢?

这个没法做。

**Comment by persytry** [comment]
好的, 谢谢
好快的速度, 好高的效率哇!!!

**Comment by Yggdroot** [comment]
> 为什么要增加向左或向右移动一个单词呢? 是因为当我通过一些快捷键打开LeaderF的输入框之后, 我可能需要再填或修改一些字符,比如向左移动一个单词后,加一个`-w`或`--stayOpen`选项之类的, 或者修改我要查询的字符串, 比如给字符串再增加一些前缀(包名)之类的

<img width="552" alt="Snipaste_2022-04-04_20-36-23" src="https://user-images.githubusercontent.com/2705841/161544921-bed9f5e4-2998-4b36-98ce-cb273209cde9.png">

这个不是LeaderF的输入框，是vim的。
红框里才是LeaderF的输入框。

**Comment by persytry** [comment]
嗯, 这个我知道的, 我说的就是LeaderF的输入框, 有图为证(嘿嘿):
<img width="704" alt="image" src="https://user-images.githubusercontent.com/88146305/161545631-bea7eaf9-73b4-4f33-a9fc-1a414bd1e303.png">
希望能支持一下向左,向右移动一个单词, 和删除右侧的单词功能

**Comment by persytry** [comment]
> > 另外, 我又想到了一个需求, 就是当我通过--recall选项把窗口重新打开以后, 能不能增加一个快捷键让它stayOpen(或者可以切换stayOpen状态)呢?
> 
> 这个没法做。

<img width="541" alt="image" src="https://user-images.githubusercontent.com/88146305/161546120-9b868966-2d39-479d-850c-c06f7009958b.png">
这个leaderf的窗口在被recall(没有加stayOpen选项)打开以后, 有没有办法在按回车选择一个条目以后, 可以不关闭这个leaderf窗口呢?

**Comment by Yggdroot** [comment]
> 另外, 我又想到了一个需求, 就是当我通过--recall选项把窗口重新打开以后, 能不能增加一个快捷键让它stayOpen(或者可以切换stayOpen状态)呢?

改好了。但是需要--recall后面再加上--stayOpen。

**Comment by Yggdroot** [comment]
> 希望能支持一下向左,向右移动一个单词, 和删除右侧的单词功能
不打算支持了。

**Comment by persytry** [comment]
好的,谢谢,您辛苦了

**Comment by persytry** [comment]
希望并祝福LeaderF的star早日破100k
