### ISSUE TITLE
Leaderf rg命令中-w参数不生效

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#884]
vim or neovim?
 vim
[ x ] neovim
Output of vim --version or nvim --version:
NVIM v0.6.1
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/chi/neovim/build/config -I/home/chi/neovim/src -I/home/chi/neovim/.deps/usr/include -I/usr/include -I/home/chi/neovim/build/src/nvim/auto -I/home/chi/neovim/build/include
Compiled by chi@W00573115
Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/home/chi/neovim/share/nvim"

Run :checkhealth for more info

Output of :echo has("python"): 1

Output of :echo has("python3"): 1

Output of :echo &pythondll(only vim, not neovim):

Output of :echo &pythonthreedll(only vim, not neovim):

Output of :py print(sys.version):
2.7.18 (default, Mar 8 2021, 13:02:45)
[GCC 9.3.0]

Output of :py3 print(sys.version):
3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]

Output of :echo g:Lf_Debug_Cmd:
undefined variable

Output of :echo g:Lf_FilesFromCache:
undefined variable

Operating system:

 Linux
 Mac OS X
 Windows
 wsl.
Configurations related to LeaderF in vimrc:
let g:Lf_Gtagslabel = 'native-pygments' " gtags 默认 C/C++/Java 等六种原生支持的代码直接使用 gtags 本地分析器，而> 其他语言使用 pygments 模块
" 自动生成Gtags
let g:Lf_GtagsAutoGenerate = 1
" 限制输出的行长度，否则会卡死 let g:Lf_RgConfig = [ "--max-columns=150", ]
" 索引存储位置
let g:Lf_CacheDirectory = '/home/chi/.lf_gtags'
let g:Lf_PreviewCode = 1 let g:Lf_ShowDevIcons = 0

let g:Lf_PreviewResult = { 'Rg': 1, 'Gtags': 1, 'Colorscheme': 1 }
" 不使用git目录信息，对整个根目录建立索引，同时解决file找不到的问题 let g:Lf_GtagsSource = 0
let g:Lf_DevIconsFont = "Agave"
" 可以用来解决中文目录问题，gtags无法处理中文字符
let g:Lf_WildIgnore = { ¦ ¦ \ 'dir': ['cloudmonitor', ],
¦ ¦ \ 'file': []
¦ ¦ }
" 取消f 和 b的绑定，避免干扰下面的key绑定
let g:Lf_ShortcutF = ''
let g:Lf_ShortcutB = ''
nnoremap f :LeaderfSelf
nnoremap fe :Leaderf file --nameOnly --no-ignore
nnoremap ff :Leaderf! --nowrap function
nnoremap fb :Leaderf! buffer nnoremap fm :Leaderf! mru

nnoremap fg :=printf("Leaderf! gtags --auto-jump --by-context --literal %s", "")
nnoremap fa :Leaderf gtags
nnoremap f; :Leaderf gtags --next
nnoremap f' :Leaderf gtags --next nnoremap fs :Leaderf rg -F -S --fuzzy --nowrap

nnoremap fo :Leaderf! bufTag
nnoremap fp :Leaderf --recall

Describe your question, feature request, or bug.
使用leaderf gtags查找tag时，如果携带了--by-context参数，则--result 参数不生效，格式无法调整

Steps to reproduce
:Leaderf rg -w回车后输入需要搜索的字符串，比如passwrod does not match

Actual behaviour
实际输出：
xxxx password xxx does not match xxxx
dxxx oxxx exxxx password xxx sxx not match xxxx

Expected behaviour
期待输出：
xxxx password xxx does not match xxxx

**Comment by Yggdroot** [comment]
-w参数是rg本身的参数，用法是`Leaderf rg -w xxx`。
当你`Leaderf rg -w`回车，实际上只有模糊匹配。
根据你的期望输出，搜索是中间不加空格就可以了，`passwroddoesnotmatch`，但仍然是模糊匹配。

**Comment by MerliniKing** [comment]
感谢，明白了
