### ISSUE TITLE
How to search in only two folders among tons of folders?

### ISSUE THREAD

**Issue by tamlok** [Yggdroot/LeaderF#885]
Hi,

I work on a big project with lots of folders under the root. What I am interested are only two of them (such as `vim` and `leaderf`). How to instruct LeaderF to only search files in those two folders? Using `WildIgnore` needs to write a long list of folders to ignore. Can we use regexp for this?

**Comment by Yggdroot** [comment]
Now you can use `LeaderfFile dir1 dir2 dir3` or `Leaderf file dir1 dir2 dir3`.

**Comment by tamlok** [comment]
Great! FYI, I use `git ls-files pattern1 pattern2` to get this.
