### ISSUE TITLE
LeaderF buffer remains after closing window

### ISSUE THREAD

**Issue by jm33-m0** [Yggdroot/LeaderF#886]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Output of `:echo has("python")`: `0`
- Output of `:echo has("python3")`: `1`
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: `3.10.3 (main, Mar 19 2022, 12:19:47) [GCC 11.2.0]                                                           `
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```vim
let g:Lf_ShortcutF = '<c-p>'
let g:Lf_ShortcutB = '<c-n>'
let g:Lf_RgConfig = [
            \ "--max-columns=150",
            \ "--glob=!node_modules/*",
            \ "--glob=!dist/*",]
" noremap <leader>u :LeaderfMru<cr>
noremap <leader>f :LeaderfFunction<cr>
" noremap <leader>b :LeaderfBuffer<cr>
" noremap <leader>m :LeaderfTag<cr>
noremap <leader>r :Leaderf rg<cr>
let g:Lf_StlSeparator = { 'left': '', 'right': '', 'font': '' }
" let g:Lf_WindowPosition = 'popup'

let g:Lf_RootMarkers = ['.project', '.root', '.svn', '.git']
let g:Lf_WorkingDirectoryMode = 'Ac'
let g:Lf_WindowHeight = 0.30
let g:Lf_CacheDirectory = expand('~/.vim/cache')
let g:Lf_ShowRelativePath = 0
let g:Lf_HideHelp = 1
let g:Lf_StlColorscheme = 'powerline'
let g:Lf_PreviewResult = {'Function':0, 'BufTag':0}
```

### Describe your question, feature request, or bug.

LeaderF buffer remains after closing window:

![image](https://user-images.githubusercontent.com/10167884/162873194-83ed943e-03b6-46e7-ba37-8b9c8f4306b6.png)

### Steps to reproduce

1. Press <kbd>Ctrl</kbd> + <kbd>p</kbd>, LeaderF shows up.
2. Press <kbd>ESC</kbd>.

### Actual behaviour

LeaderF exits, and buffer remains.

### Expected behaviour

Both the window and buffer should be gone, as in the previous versions.

**Comment by Yggdroot** [comment]
LeaderF buffer is a unlisted(`buflisted is 0`) buffer. The issue is why your tabline show unlisted buffer. It's not bug of LeaderF.

**Comment by jm33-m0** [comment]
Thanks for explaining, I suppose it has something to do with vim-airline then
