### ISSUE TITLE
在leaderf的搜索结果框中，如何排除掉含有某些字符串的结果（行）？

### ISSUE THREAD

**Issue by persytry** [Yggdroot/LeaderF#887]
我先用`Leaderf rg 'query_some'`命令进行搜索，弹出的搜索结果框有很多的结果（行），我想在这个基础上进行进一步的过滤，想把包含某些字符串的结果（行）给排除掉，请问有什么办法？谢谢

**Comment by Yggdroot** [comment]
没有，LeaderF没有这个功能。排除掉只能用rg的功能了。

**Comment by persytry** [comment]
好的，谢谢
