### ISSUE TITLE
Leader file Error

### ISSUE THREAD

**Issue by bbchung** [Yggdroot/LeaderF#890]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
![image](https://user-images.githubusercontent.com/3892170/165425141-3c4a4964-ea22-424b-969e-beff93feb935.png)
- Output of `:echo has("python")`: 
- 0
- Output of `:echo has("python3")`: 
- 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- empty
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- empty
- Output of `:py print(sys.version)`: 
- E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: 
![image](https://user-images.githubusercontent.com/3892170/165425391-eb60b486-8cc4-47be-9f3e-40618b426ecc.png)
- Output of `:echo g:Lf_Debug_Cmd`: 
E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
E121: Undefined variable: g:Lf_FilesFromCache
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
![image](https://user-images.githubusercontent.com/3892170/165425678-495808c9-68e0-477f-a674-94c866dacbd6.png)
### Describe your question, feature request, or bug.
command ":Leaderf file" cause vim error if there is a .swp of the opened file
![image](https://user-images.githubusercontent.com/3892170/165426076-8ab84d01-868c-4c4e-89c5-f69c41122e38.png)

### Steps to reproduce
1. vim a.txt
2. ctrl-z
3. vim
4. :Leaderf file to open a.txt
5. 
![image](https://user-images.githubusercontent.com/3892170/165426394-5ce459ba-fbe7-4e46-9652-0a767b273fa6.png)
### Actual behaviour
vim error
### Expected behaviour
vim load a.txt and able to edit

**Comment by Yggdroot** [comment]
This is expected behavior.
Because a.txt has swp file.

**Comment by bbchung** [comment]
I think it's normal if I can edit the file after pressed E, but I only got the empty buffer and need reopen the file, looks not like expected behavior

**Comment by bbchung** [comment]
thats true, I will figure out where is the conflict, thanks!

**Comment by Yggdroot** [comment]
Have you installed coc.nvim? I find a bug of coc that may cause this issue.

**Comment by bbchung** [comment]
> Have you installed coc.nvim? I find a bug of coc that may cause this issue.

yeah, I use coc

**Comment by Yggdroot** [comment]
Fixed.

**Comment by bbchung** [comment]
I found there is another confict with plugin [LightLine](https://github.com/itchyny/lightline.vim) and [Fugitive](https://github.com/tpope/vim-fugitive) with config snippets 
![image](https://user-images.githubusercontent.com/3892170/169440446-898ab43e-3e0f-4c2d-81d9-2cc35d2ad90f.png)
![image](https://user-images.githubusercontent.com/3892170/169440646-bae2f54c-077d-429f-bf5a-18b03de62524.png)
