### ISSUE TITLE
File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start

### ISSUE THREAD

**Issue by adventure-nate** [Yggdroot/LeaderF#891]
- vim or neovim? 
    - [* ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
root@~# vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled May  3 2022 01:44:03)
Compiled by Professional operations
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
-balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
-browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     -perl              +title
+cindent           +job               +persistent_undo   -toolbar
-clientserver      +jumplist          +popupwin          +user_commands
-clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3           +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        -lua               -ruby              +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con        +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -ldl     -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm
- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`:  [GCC 9.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [*] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

   " don't show the help in normal mode
  let g:Lf_WorkingDirectoryMode = 'AF'
  let g:Lf_RootMarkers = ['.git', '.svn', '.hg', '.project', '.root']
  let g:Lf_HideHelp = 1
  let g:Lf_UseCache = 0
  let g:Lf_UseVersionControlTool = 0
  let g:Lf_IgnoreCurrentBufferName = 1
  " popup mode
  let g:Lf_WindowPosition = 'popup'
  let g:Lf_PreviewInPopup = 1
  let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
  let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }
  
  let g:Lf_ShortcutF = "<leader>f"
  noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
  noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
  noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
  noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
  
  "noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
   noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
  "search visually selected text literally
   xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
   noremap go :<C-U>Leaderf! rg --recall<CR>
  
   " should use `Leaderf gtags --update` first
   let g:Lf_GtagsAutoGenerate = 1
   let g:Lf_Gtagslabel = 'native-pygments'
   noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
   noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
   noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
   noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
   noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>
   " No.2 Gtags
   " enable gtags module
   let g:gutentags_modules = ['ctags', 'gtags_cscope']
   
  let g:gutentags_ctags_tagfile = '.tags'

  let g:gutentags_project_root = ['.root']
 
  " generate datebases in my cache directory, prevent gtags files polluting my project
 
   let g:gutentags_cache_dir = expand('~/.cache/tags')
  
   " change focus to quickfix window after search (optional).
   let g:gutentags_plus_switch = 1
   
   " disable the default keymaps by
    let g:gutentags_plus_nomap = 1

### Describe your question, feature request, or bug.
 When use “ leader + fr ” (Leaderf! gtags -r %s --auto-jump", expand("<cword>")) to find function reference， some errors ccurs as follow:
Some trys:   set encoding=utf8  has already do this.

Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 1209, in startExplorer
    super(GtagsExplManager, self).startExplorer(win_pos, *args, **kwargs)
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2291, in startExplorer
    content = self._getExplorer().getContent(*args, **kwargs)
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/gtagsExpl.py", line 283, in getContent
    first_two = list(itertools.islice(content, 2))
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105, in read
    raise Exception(lfBytes2Str(err, encoding))
Exception: global: /root/.LfCache/gtags/_root_linux_kernel_linux-5.0/GRTAGS seems corrupted.

Press ENTER or type command to continue

### Expected behaviour
 should be normal

**Comment by Yggdroot** [comment]
> GRTAGS seems corrupted

I don't know why. Please `Leaderf gtags --update` and retry or `Leaderf gtags --remove` and `Leaderf gtags --update` then retry.

**Comment by adventure-nate** [comment]
> > GRTAGS seems corrupted
> 
> I don't know why. Please `Leaderf gtags --update` and retry or `Leaderf gtags --remove` and `Leaderf gtags --update` then retry.

Thanks for replying.   When i use  ‘Leaderf gtags --update" , there shows:  gtags error!
Then,  when i use :mess to find the real reason,  the real reason: "ImportError: No module named pexpect"
When I installed pygments, it was not installed correctly, resulting in the library not being found under python3, the issue has been resolved.
