### ISSUE TITLE
Make .LfCache use XDG directory spec

### ISSUE THREAD

**Issue by ghost** [Yggdroot/LeaderF#892]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.7.0
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:py print(sys.version)`: 3.10.4
- Output of `:py3 print(sys.version)`: 3.10.4
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.

### Describe your question, feature request, or bug.
The XDG Base Directory Spec defines a standard, user-configurable set of directories defined as environment variables.

LeaderF should be using `$XDG_CACHE_HOME/Lf` as its cache directory instead of `~/.LfCache`.

[reference spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by Yggdroot** [comment]
You can set `g:Lf_CacheDirectory`.
