### ISSUE TITLE
Bug: Powerline render error

### ISSUE THREAD

**Issue by cospotato** [Yggdroot/LeaderF#893]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`: 
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Output of `:echo has("python")`: `0`
- Output of `:echo has("python3")`: `1`
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: `E319: No "python" provider found. Run ":checkhealth provider"`
- Output of `:py3 print(sys.version)`: `3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]`
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

Already installed Nerd Font `JetbrainMono NF`

<img width="823" alt="image" src="https://user-images.githubusercontent.com/7987906/167284179-ee08a11b-dc60-4f09-a021-056a994f75da.png">

### Actual behaviour

Powerline triangle render error.

### Expected behaviour

Powerline triangle render correct.

**Comment by Yggdroot** [comment]
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2"}

**Comment by cospotato** [comment]
> let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2"}

Thanks a lot! That's worked.
