### ISSUE TITLE
搜索后，需要Ctrl+o多次才能返回之前的位置

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#894]
请教一个问题：
在查询gtags时，因为输入过程中，leaderf会持续查找匹配结果，同时自动定位和展示当前第一个匹配项，导致返回之前位置时需要使用ctrl+o返回多次
有没有什么办法，可以优化这个体验呢？

**Comment by Yggdroot** [comment]
使用popup模式。

**Comment by MerliniKing** [comment]
thx

**Comment by Leviathan1995** [comment]
@Yggdroot 这个返回能重新映射吗，习惯了 Ctrl+t, 并且我发现 ctrl+o 需要两次才能返回，第一次是回到选中的函数开头
