### ISSUE TITLE
popup模式下显示的tags总数数字不全

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#895]
vim or neovim?
vim
[ x ] neovim
Output of vim --version or nvim --version:
NVIM v0.6.1
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/chi/neovim/build/config -I/home/chi/neovim/src -I/home/chi/neovim/.deps/usr/include -I/usr/include -I/home/chi/neovim/build/src/nvim/auto -I/home/chi/neovim/build/include
Compiled by chi@W00573115
Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/home/chi/neovim/share/nvim"

Run :checkhealth for more info

Output of :echo has("python"): 1

Output of :echo has("python3"): 1

Output of :echo &pythondll(only vim, not neovim):

Output of :echo &pythonthreedll(only vim, not neovim):

Output of :py print(sys.version):
2.7.18 (default, Mar 8 2021, 13:02:45)
[GCC 9.3.0]

Output of :py3 print(sys.version):
3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]

Output of :echo g:Lf_Debug_Cmd:
undefined variable

Output of :echo g:Lf_FilesFromCache:
undefined variable

Operating system:

Linux
Mac OS X
Windows
wsl.
Configurations related to LeaderF in vimrc:
let g:Lf_Gtagslabel = 'native-pygments' " gtags 默认 C/C++/Java 等六种原生支持的代码直接使用 gtags 本地分析器，而> 其他语言使用 pygments 模块
" 自动生成Gtags
let g:Lf_GtagsAutoGenerate = 1
" 限制输出的行长度，否则会卡死 let g:Lf_RgConfig = [ "--max-columns=150", ]
" 索引存储位置
let g:Lf_CacheDirectory = '/home/chi/.lf_gtags'
let g:Lf_PreviewCode = 1 let g:Lf_ShowDevIcons = 0

let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = { 'Rg': 1, 'Gtags': 1, 'Colorscheme': 1 }
" 不使用git目录信息，对整个根目录建立索引，同时解决file找不到的问题 let g:Lf_GtagsSource = 0
let g:Lf_DevIconsFont = "Agave"
" 可以用来解决中文目录问题，gtags无法处理中文字符
let g:Lf_WildIgnore = { ¦ ¦ \ 'dir': ['cloudmonitor', ],
¦ ¦ \ 'file': []
¦ ¦ }
" 取消f 和 b的绑定，避免干扰下面的key绑定
let g:Lf_ShortcutF = ''
let g:Lf_ShortcutB = ''
nnoremap f :LeaderfSelf
nnoremap fe :Leaderf file --nameOnly --no-ignore
nnoremap ff :Leaderf! --nowrap function
nnoremap fb :Leaderf! buffer nnoremap fm :Leaderf! mru

nnoremap fg :=printf("Leaderf! gtags --auto-jump --by-context --literal %s", "")
nnoremap fa :Leaderf gtags
nnoremap f; :Leaderf gtags --next
nnoremap f' :Leaderf gtags --next nnoremap fs :Leaderf rg -F -S --fuzzy --nowrap

nnoremap fo :Leaderf! bufTag
nnoremap fp :Leaderf --recall

Describe your question, feature request, or bug.
popup模式下显示的tags数少了最后一位
非popup模式下，tag总数为1275067，popup模式下只显示了127506

Steps to reproduce
使用如下配置切换为popup模式
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1

Actual behaviour
实际输出：127506

Expected behaviour
期待输出：1275067

**Comment by MerliniKing** [comment]
有没有可能是字体原因呢？

**Comment by Yggdroot** [comment]
是字体原因

**Comment by MerliniKing** [comment]
请问，推荐什么字体呢，我去尝试一下

**Comment by Yggdroot** [comment]
这个根据自己的喜好，可以在https://github.com/ryanoasis/nerd-fonts 里找。

**Comment by MerliniKing** [comment]
感谢

**Comment by MerliniKing** [comment]
安装了nerd font字体后，发现问题没解决，虽然icon显示正常了。
是statusline的字体需要单独配置吗？因为我看float window的顶部和底部的状态栏中，箭头的显示和示例中的不太一样

**Comment by MerliniKing** [comment]
猜测是通过g:Lf_StlSeparator设置

**Comment by Yggdroot** [comment]
那就奇怪了。

**Comment by MerliniKing** [comment]
![1](https://user-images.githubusercontent.com/10217348/167667530-8dcfaf30-2166-408b-a3d9-298994905b81.jpg)
如图float window右上角，因为只有个位数entry，所以没有显示total总数

**Comment by Yggdroot** [comment]
你的行号左侧有一列不知道是什么。

**Comment by MerliniKing** [comment]
使用mini.vim测试了下，是没问题的
应该是我自己配置的问题，感谢！ @

**Comment by MerliniKing** [comment]
测试发现，是与coc.nvim的一个设置有冲突，导致左边多了一列
set signcolumn=yes

**Comment by MerliniKing** [comment]
set signcolumn=number或set signcolumn=no，都可以正常显示
更正一下，signcolumn是nvim自身的设置

**Comment by Yggdroot** [comment]
修复了。
这个选项开了好像有什么问题，我忘了，就注释起来了。
