### ISSUE TITLE
rg支持--no-filename参数，Leaderf rg不支持

### ISSUE THREAD

**Issue by MerliniKing** [Yggdroot/LeaderF#897]
vim or neovim?
vim
[ x ] neovim
Output of vim --version or nvim --version:
NVIM v0.6.1
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/chi/neovim/build/config -I/home/chi/neovim/src -I/home/chi/neovim/.deps/usr/include -I/usr/include -I/home/chi/neovim/build/src/nvim/auto -I/home/chi/neovim/build/include
Compiled by chi@W00573115
Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/home/chi/neovim/share/nvim"

Run :checkhealth for more info

Output of :echo has("python"): 1

Output of :echo has("python3"): 1

Output of :echo &pythondll(only vim, not neovim):

Output of :echo &pythonthreedll(only vim, not neovim):

Output of :py print(sys.version):
2.7.18 (default, Mar 8 2021, 13:02:45)
[GCC 9.3.0]

Output of :py3 print(sys.version):
3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0]

Output of :echo g:Lf_Debug_Cmd:
undefined variable

Output of :echo g:Lf_FilesFromCache:
undefined variable

Operating system:

Linux
Mac OS X
Windows
wsl.
Configurations related to LeaderF in vimrc:
let g:Lf_Gtagslabel = 'native-pygments' " gtags 默认 C/C++/Java 等六种原生支持的代码直接使用 gtags 本地分析器，而> 其他语言使用 pygments 模块
" 自动生成Gtags
let g:Lf_GtagsAutoGenerate = 1
" 限制输出的行长度，否则会卡死 let g:Lf_RgConfig = [ "--max-columns=150", ]
" 索引存储位置
let g:Lf_CacheDirectory = '/home/chi/.lf_gtags'
let g:Lf_PreviewCode = 1 let g:Lf_ShowDevIcons = 0

let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = { 'Rg': 1, 'Gtags': 1, 'Colorscheme': 1 }
" 不使用git目录信息，对整个根目录建立索引，同时解决file找不到的问题 let g:Lf_GtagsSource = 0
let g:Lf_DevIconsFont = "Agave"
" 可以用来解决中文目录问题，gtags无法处理中文字符
let g:Lf_WildIgnore = { ¦ ¦ \ 'dir': ['cloudmonitor', ],
¦ ¦ \ 'file': []
¦ ¦ }
" 取消f 和 b的绑定，避免干扰下面的key绑定
let g:Lf_ShortcutF = ''
let g:Lf_ShortcutB = ''
nnoremap f :LeaderfSelf
nnoremap fe :Leaderf file --nameOnly --no-ignore
nnoremap ff :Leaderf! --nowrap function
nnoremap fb :Leaderf! buffer nnoremap fm :Leaderf! mru

nnoremap fg :=printf("Leaderf! gtags --auto-jump --by-context --literal %s", "")
nnoremap fa :Leaderf gtags
nnoremap f; :Leaderf gtags --next
nnoremap f' :Leaderf gtags --next nnoremap fs :Leaderf rg -F -S --fuzzy --nowrap

nnoremap fo :Leaderf! bufTag
nnoremap fp :Leaderf --recall

Describe your question, feature request, or bug.
rg支持--no-filename参数，Leaderf rg不支持

Steps to reproduce
Leaderf rg --no-filename报错，参数不支持

Actual behaviour
实际输出：Leaderf rg --no-filename报错，参数不支持

Expected behaviour
期待输出：Leaderf rg --no-filename可以查询成功

**Comment by Yggdroot** [comment]
搞不清楚为什么要`--no-filename`。
不打算支持。

**Comment by MerliniKing** [comment]
这个参数在竖屏+float wiindow场景比较有用
因为文件名 + content line会超过float window时，导致每个结果都跨行了，如果添加nowrap，又会导致看不到匹配项

**Comment by MerliniKing** [comment]
如果可以的话，我可以提一个MR来支持这个参数

**Comment by Yggdroot** [comment]
没有文件名怎么跳转？

**Comment by MerliniKing** [comment]
明白你的意思了

**Comment by Yggdroot** [comment]
> 这个参数在竖屏+float wiindow场景比较有用 因为文件名 + content line会超过float window时，导致每个结果都跨行了，如果添加nowrap，又会导致看不到匹配项

可以使用`--heading`

**Comment by MerliniKing** [comment]
我试了下
`Leaderf rg --heading`会直接进入normal模式，且无法进入INPUT模式，会提示无法‘modifiable’ is off

**Comment by Yggdroot** [comment]
是不支持input模式来过滤，因为过滤了后，就会丢失文件名信息，无法跳转了。

**Comment by MerliniKing** [comment]
懂了

**Comment by MerliniKing** [comment]
非常感谢你的回复
