### ISSUE TITLE
`Leaderf gtags --auto-jump`在没有打开目标tab的情况下，能不能打开新的tab？

### ISSUE THREAD

**Issue by persytry** [Yggdroot/LeaderF#898]
```vim
:<C-U><C-R>=printf("Leaderf gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
```

配合`let g:Lf_JumpToExistingWindow = 1`，我想实现当只有一处定义（搜索结果）的时候，如果已存在目标tab，那么跳到目标tab，如果不存在目标tab则新建tab并跳过去，请问可以做到吗？

**Comment by ijpq** [comment]
> ```vim
> 
> :<C-U><C-R>=printf("Leaderf gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
> 
> ```
> 
> 
> 
> 配合`let g:Lf_JumpToExistingWindow = 1`，我想实现当只有一处定义（搜索结果）的时候，如果已存在目标tab，那么跳到目标tab，如果不存在目标tab则新建tab并跳过去，请问可以做到吗？

看了一下doc，应该是C-】

**Comment by persytry** [comment]
> > ```viml
> > :<C-U><C-R>=printf("Leaderf gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 配合`let g:Lf_JumpToExistingWindow = 1`，我想实现当只有一处定义（搜索结果）的时候，如果已存在目标tab，那么跳到目标tab，如果不存在目标tab则新建tab并跳过去，请问可以做到吗？
> 
> 看了一下doc，应该是C-】

我的问题是Leaderf中的gtags的功能，而`C-]`是vim下的功能

**Comment by Yggdroot** [comment]
let g:Lf_JumpToExistingWindow = 1，使用ctrl-t应该可以。

**Comment by persytry** [comment]
> let g:Lf_JumpToExistingWindow = 1，使用ctrl-t应该可以。

您好, 目前测试下来是不可以的. 当`let g:Lf_JumpToExistingWindow = 1`时, 执行`:<C-U><C-R>=printf("Leaderf gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>`命令, 哪怕只有一个搜索结果, 并且已经打开了相关窗口的情况下, 依然会重新再打开一个新的窗口来

**Comment by Yggdroot** [comment]
执行`:<C-U><C-R>=printf("Leaderf gtags -d %s --auto-jump t", expand("<cword>"))<CR><CR>`

**Comment by persytry** [comment]
谢谢作者
