### ISSUE TITLE
[Q] gtags-cscope got zomibne process

### ISSUE THREAD

**Issue by arthurkiller** [Yggdroot/LeaderF#899]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/11133870/169947278-c5dbe27a-f1f7-4633-b10a-ebb0d487c4b1.png">

**Comment by Yggdroot** [comment]
LeaderF does not use gtags-cscope.

**Comment by arthurkiller** [comment]
> LeaderF does not use gtags-cscope.

thx for reply, I got wrong place
