### ISSUE TITLE
Don't map leader f

### ISSUE THREAD

**Issue by joereynolds** [Yggdroot/LeaderF#90]
As discussed [here](https://www.reddit.com/r/vim/comments/7djon0/leaderf_yet_another_fuzzy_finder_plugin_for_vim/dpyh1iy/)

You shouldn't map our leader commands, you should expose plug mappings for us to map to :)

**Comment by Yggdroot** [comment]
If `<leader>f` is already mapped, this plugin won't map it any more. So this issue is invalid.
