### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by arthurkiller** [Yggdroot/LeaderF#902]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Apr 06 2022 16:59:21)
macOS version - x86_64
Included patches: 1-4700
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DMACOS_X -DMACOS_X_DARWIN -g -O2 -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: clang -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -L/usr/local/lib -o vim -lm -lncurses -liconv -lintl -framework AppKit -L/usr/local/opt/lua/lib -llua5.4 -mmacosx-version-min=12.0 -fstack-protector-strong -L/usr/local/lib -L/usr/local/Cellar/perl/5.34.0/lib/perl5/5.34.0/darwin-thread-multi-2level/CORE -lperl -L/usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/config-3.10-darwin -lpython3.10 -framework CoreFoundation -lruby.3.1 -L/usr/local/Cellar/ruby/3.1.1/lib 
```

- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`:  E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
Error detected while processing function leaderf#Any#start[4]..leaderf#LfPy[1]..function leaderf#Any#start[4]..leaderf#LfPy:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 815, in start
    the_args.start(arguments, *args, **kwargs)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 747, in _default_action
    manager.startExplorer(win_pos[2:], *args, **kwargs)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2360, in startExplorer
    self.input()
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 62, in deco
    func(self, *args, **kwargs)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2646, in input
    self._search(cur_content)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 1176, in _search
    self._previewResult(False)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 393, in _previewResult
    self._previewInPopup(line, self._getInstance().buffer, line_nr)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/tagExpl.py", line 228, in _previewInPopup
    self._createPopupPreview("", tagfile, line_nr)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 91, in deco
    func(self, *args, **kwargs)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 753, in _createPopupPreview
    self._createPopupModePreview(title, source, line_nr, jump_cmd)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 91, in deco
    func(self, *args, **kwargs)
  File "/Users/arthur/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 722, in _createPopupModePreview
    lfCmd("call win_execute(winid, 'doautocmd filetypedetect BufNewFile %s')" % escQuote(source))
vim.error: Vim(redir):E930: Cannot use :redir inside execute()
Error detected while processing function leaderf#Any#start:
line    4:
E171: Missing :endif
Press ENTER or type command to continue

**Comment by Yggdroot** [comment]
How to reproduce?
Please refer to https://github.com/Yggdroot/LeaderF/issues?q=E930 to see if it will help.
