### ISSUE TITLE
Leadef file 能不能加上--auto-jump参数

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#905]
这样就可以直接跳转到对应文件了

**Comment by Yggdroot** [comment]
就算结果只剩一个，也不一定就是想打开的文件。而且我认为按一下回车也不麻烦。

**Comment by gVimer** [comment]
VIM默认有个快捷键是gf就是打开光标所在文件名的文件 不是很好用 所以我想着是用Leaderf来实现 
`nnoremap gf  :exec("Leaderf! file --cword --auto-jump")<CR>`
 不好加的话就算了吧 我自己再研究研究

**Comment by Yggdroot** [comment]
你map后面多加一个`<cr>`

**Comment by Yggdroot** [comment]
```vim
nnoremap gf :exec("Leaderf! file --cword")<CR><CR>
```

**Comment by gVimer** [comment]
这样有点粗暴  会先弹窗 然后关闭
如果有多个同名文件的话 也可能跳的不准 不纠结了 就多按一下回车吧 打扰了!!!

**Comment by gVimer** [comment]
改了下代码 基本能满足要求
![image](https://user-images.githubusercontent.com/6241431/174463844-31fb3ff5-40fd-4332-901f-e22f090b13eb.png)
![image](https://user-images.githubusercontent.com/6241431/174464262-36da8ad3-6d25-46ef-849d-624a8f39df14.png)
这个退出好像有点小问题 但是也不是很影响
