### ISSUE TITLE
用g:Lf_Extensions创建的扩展对象能缓存吗

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#907]
我用g:Lf_Extensions创建了一个书签 每次关闭后再打开都是重新创建对象 需要等几秒钟
能不能将这个对象缓存起来 下次就可以直接打开了(在VIM没关闭的情况下)

**Comment by Yggdroot** [comment]
这依赖于自己的实现。

**Comment by gVimer** [comment]
能说下关键点在哪里吗 扩展定义如下
![image](https://user-images.githubusercontent.com/6241431/174730677-be129bb2-82ab-42ea-b043-85f4fab22080.png)

**Comment by Yggdroot** [comment]
比如GetBookMarksSource，第一次调用把结果缓存起来，第二次调用直接返回结果。

**Comment by gVimer** [comment]
这个影响不大 都是定义好的数据LIST 不超过10条

**Comment by Yggdroot** [comment]
那就不需要缓存呀，结果应该很快出来呀，不可能几秒钟。

**Comment by gVimer** [comment]
我知道了 应该是我这个定义有问题
我用nnoremap <Leader>b去打开 但是有其他插件定义了nnoremap <Leader>bX 等系列快捷键 所以有延迟 打扰了
