### ISSUE TITLE
关于结果列表序号格式化的问题

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#908]
![image](https://user-images.githubusercontent.com/6241431/174957038-0809ac05-dccf-419a-b74f-4d3ab008aaa1.png)
想把这个编号变成001 002 003...这样的应该在哪里改啊？麻烦告之下。谢谢！

**Comment by Yggdroot** [comment]
这是行号，没法改

**Comment by gVimer** [comment]
打扰了
