### ISSUE TITLE
(Win 10) :LeaderfFile<cr> error

### ISSUE THREAD

**Issue by auwsmit** [Yggdroot/LeaderF#91]
`:LeaderfFile` by itself opens the Leaderf window for my current working directory, but the results are empty, it starts in normal mode, and gives these errors (I only see them via `:messages`):

    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line    3:
    E108: No such variable: "s:show_range"
    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line    9:
    E802: Invalid ID: -1 (must be greater than or equal to 1)
    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line   11:
    E802: Invalid ID: -1 (must be greater than or equal to 1)
    
     searching ...
    
    "X:\Programs\vim\vim80\File\LeaderF"  --No lines in buffer--
    Error detected while processing function <SNR>5_BMRemove:
    line    9:
    E329: No menu "LeaderF (2)	X:\Programs\vim\vim80\File"

and if I try to insert any text it gives these errors (which I assume are only because of the previous ones, so these are probably unimportant):

    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line    3:
    E108: No such variable: "s:show_range"
    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line    9:
    E802: Invalid ID: -1 (must be greater than or equal to 1)
    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line   11:
    E802: Invalid ID: -1 (must be greater than or equal to 1)
    >>>  
    Error detected while processing :
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 47, in deco
        func(self, *args, **kwargs)
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 818, in input
        self._search(self._content)
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 281, in _search
        self.clearSelections()
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 584, in clearSelections
        lfCmd("call matchdelete(%d)" % i)
    vim.error: Vim(call):E803: ID not found: 4

**Comment by Yggdroot** [comment]
I think this is a conflict with some other plugin. You can grep "s:show_range" in `.vim` to see what plugin it is.

**Comment by auwsmit** [comment]
So, `s:show_range` was present in [traces.vim](https://github.com/traces.vim), but even after disabling all my other plugins and deleting traces, the problem persists, albeit with less errors:

     searching ...
    
    "X:\Programs\vim\vim80\File\LeaderF"  --No lines in buffer--
    Error detected while processing function <SNR>5_BMRemove:
    line    9:
    E329: No menu "LeaderF (2)	X:\Programs\vim\vim80\File">>>  

It still starts me in normal mode, and now when I try to insert text, it allows me to enter a pattern, but there aren't any results to parse.

**Comment by Yggdroot** [comment]
I googled "s:show_range", found that it probably is https://github.com/xtal8/traces.vim that conflict with LeaderF.

**Comment by Yggdroot** [comment]
`BMRemove` is in another plugin, I think this also is a conflict.

**Comment by auwsmit** [comment]
problems fixed because of an issue with `find` (same as issue #87), 

I discovered `BMRemove` in `vim80\menu.vim`, but now that I'm using `rg`, both `s:show_range` and `BMRemove` are non-issues, so they must just be warnings and/or non-vital conflicts.
