### ISSUE TITLE
LeaderF 拓展插件 回调函数问题

### ISSUE THREAD

**Issue by HaomingJu** [Yggdroot/LeaderF#910]
Hi 我最近再基于LeaderF做拓展插件[LeaderF-gitlab](https://github.com/HaomingJu/LeaderF-gitlab.git)，有遇到一个问题是
```
let g:Lf_Extensions.mr = {
            \ 'source': string(function('s:lf_gitlab_source'))[10:-3],
            \ 'preview': string(function('s:lf_gitlab_mr_preview'))[10:-3]}
```
以上代码中的preview对应的函数，尽在INSERT模式下会自动调用，但是当单击Tab换为NORMAL之后，该函数就不能被回调了

如何使得preview回调函数再INSERT & NORMAL下均可以回调？

INSERT模式下 preview
![1](https://user-images.githubusercontent.com/24786568/175457179-6b58c284-52dd-4b64-93bc-aedad893703b.png)

NORMAL模式下 preview界面未刷新
![2](https://user-images.githubusercontent.com/24786568/175457201-058c2312-95ea-4899-9b85-8344abc84ce9.png)

期待你的回复，谢谢

**Comment by Yggdroot** [comment]
Normal模式需要按p才会触发。
如果想自动触发,可以加个`--auto-preview`. 或者设置一下g:Lf_PreviewResult。

**Comment by HaomingJu** [comment]
您说的 --auto-preview 喝g:Lf_PreviewRresult 我都有试过
针对INSERT是有效的，但是一旦进入NORMAL后，上下选择不同条目，并不会触发 preview 回调函数

**Comment by HaomingJu** [comment]
我录制一个动图给您

**Comment by HaomingJu** [comment]
![Peek 2022-06-24 15-30](https://user-images.githubusercontent.com/24786568/175485971-8cbe47fc-3f81-40df-93e5-d2e7e96a7c8f.gif)

**Comment by HaomingJu** [comment]
但是您内置命令`LeaderfTag`  `LeaderfFunction` 却可以在NORMAL模式下正常触发

**Comment by Yggdroot** [comment]
那奇怪了，是不是你写的preview函数有问题。https://github.com/Yggdroot/LeaderF-changes 这个插件就是个extension，没有这个问题。

**Comment by HaomingJu** [comment]
好，我自查一下，谢谢您
我想问一句这个bang_enter表征的是哪个动作

**Comment by Yggdroot** [comment]
`Leaderf! file` 这样多个感叹号会直接进入normal mode，bang_enter是刚进入normal mode的hook，比如Leaderf! function，直接进入normal mode后，会把光标定位到当前那个函数位置。

**Comment by HaomingJu** [comment]
我定位了一下， 当我以 `Leaderf! mr`运行时，会打印出 'Done !'， 定位到是`` autoload/leaderf/python/leaderf/manager.py
:2389

**Comment by Yggdroot** [comment]
修复了，原因是nvim没有支持。

**Comment by HaomingJu** [comment]
谢谢，我这边测试通过！
