### ISSUE TITLE
`LeaderF file` result does not honor ordering produced by `g:Lf_ExternalCommand`

### ISSUE THREAD

**Issue by qx220** [Yggdroot/LeaderF#915]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

I use external command to generate file lists sorted by modtime. More precisely:

```
let g:Lf_ExternalCommand = 'find "%s" -not -iwholename "*.git*" -type f -printf "%%T@ %%p\n" | sort -n -t " " -k 1 -r | cut -f 2- -d " "'
```

It works like a charm when launching vim with an empty buffer name, such as using `vim`

However, if vim is launched with a named buffer/file, such as `vim README.md`, `LeaderF file` seems to automatically sort the results internally, overriding the order produced by `g:Lf_ExternalCommand`

After digging into the code, I was able to pinpoint the relevant spot:

https://github.com/Yggdroot/LeaderF/blob/f55c96bf3725db9b817e8cfcdc9ec3efa4c15b95/autoload/leaderf/python/leaderf/manager.py#L1631

IMO, it would be more flexible to disable sorting by default, and let external commands to produce a sorted list. Also out of curiosity, it seems like `sort_results=True` occurs only once in the code, was sorting intended to be hard-coded here at all?

I'm also creating a merge request fixing this issue.

**Comment by Yggdroot** [comment]
```
let g:Lf_EmptyQuery = 0
```
will meet your requirement.
