### ISSUE TITLE
Question: is this a right way mapping C-] ?

### ISSUE THREAD

**Issue by ijpq** [Yggdroot/LeaderF#919]
write in simple style, because it is a not complex question.

acc to docs:
`<C-]> : open in vertical split window.`

there is a setting in my vim config:
`let g:Lf_CommandMap = {'<C-]>': ['<leader>p']}`
but when <leader>p Key pushed, this messages show up:
`E42: No Errors`

**Comment by ijpq** [comment]
i am firmly assure there is not another <leader>p key mapping

**Comment by Yggdroot** [comment]
ctrl-] is built-in, you do not need to do anything.

**Comment by ijpq** [comment]
> ctrl-] is built-in, you do not need to do anything.

i found ctrl-] key not working. thats why i mapping it

**Comment by Yggdroot** [comment]
ctrl-] is used in input mode.

**Comment by ijpq** [comment]
> ctrl-] is used in input mode.

ok.  but,
first select entry within prompt 
then `tab` to get cursor back from prompt to input line 
then using C-] to open with split. 
it is really unnecessary `tab` here, i think

**Comment by Yggdroot** [comment]
In normal mode, v has the same effect as ctrl-].

**Comment by ijpq** [comment]
> In normal mode, v has the same effect as ctrl-].

this information is contained within help?(F1)

**Comment by Yggdroot** [comment]
yes
