### ISSUE TITLE
(Win10) :LeaderfFile <any dir> error

### ISSUE THREAD

**Issue by auwsmit** [Yggdroot/LeaderF#92]
`:LeaderfFile` with any specific directory (e.g. `.`, `X:\`, `C:\Program Files\Vim\vim80\`, etc.) gives these errors with no LeaderF window or anything:

    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line    3:
    E108: No such variable: "s:show_range"
    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line    9:
    E802: Invalid ID: -1 (must be greater than or equal to 1)
    Error detected while processing function <SNR>38_main[53]..<SNR>38_clean:
    line   11:
    E802: Invalid ID: -1 (must be greater than or equal to 1)
    >>>  
    Error detected while processing :
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 47, in deco
        func(self, *args, **kwargs)
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 818, in input
        self._search(self._content)
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 281, in _search
        self.clearSelections()
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 584, in clearSelections
        lfCmd("call matchdelete(%d)" % i)
    vim.error: Vim(call):E803: ID not found: 4

seems related to #91

**Comment by auwsmit** [comment]
after disabling traces.vim (because of `s:show_range`, explained here #91) and all my other plugins, these are now the errors that appear:

     searching ...
    Error detected while processing function leaderf#File#startExpl[5]..leaderf#LfPy:
    line    1:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 557, in startExplorer
        super(FileExplManager, self).startExplorer(win_pos, *args, **kwargs)
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\manager.py", line 726, in startExplorer
        content = self._getExplorer().getContent(*args, **kwargs)
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\fileExpl.py", line 443, in getContent
        lfCmd("silent cd %s" % args[0])
    vim.error: Vim(cd):E472: Command failed
    Error detected while processing function leaderf#File#startExpl:
    line    5:
    E171: Missing :endif

**Comment by Yggdroot** [comment]
First make sure `C:\Program Files\Vim\vim80\` exist,
then launch `LeaderfFile C:\Program\ Files\Vim\vim80\` , note that the space between `Program` and `Files` should be escaped.

**Comment by auwsmit** [comment]
It gives these errors with paths that don't have spaces, and even if I correctly escape them

**Comment by Yggdroot** [comment]
It's weird. On my machine it is OK.
You can just try `:cd <directory>`, to see if there is an error `E472`.

**Comment by auwsmit** [comment]
I can change directories fine with no errors

**Comment by Yggdroot** [comment]
What is the version of your vim?
Could you provide a minimal vimrc?

**Comment by auwsmit** [comment]
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 31 2017 23:01:47)
    MS-Windows 64-bit GUI version with OLE support
    Included patches: 1-1241

and a minimal vimrc:

    " setup vim-plug
    call plug#begin()
        Plug 'Yggdroot/LeaderF' " {{{
        nnoremap <space>- :LeaderfFile <c-r>=fnameescape(expand('%:p:h'))<cr>/<cr>
        nnoremap <space>+ :LeaderfFile<cr>
        nnoremap <space>b :LeaderfBuffer<cr>
        nnoremap <space>r :LeaderfMru<cr>
        nnoremap <space>ff :LeaderfFile<space>
        nnoremap <space>fl :LeaderfLineAll<cr>
        nnoremap <space>fb :LeaderfLine<cr>
        nnoremap <space>ft :LeaderfTag<cr>
        nnoremap <space>fh :LeaderfHelp<cr>
        nnoremap <space>f: :LeaderfHistoryCmd<cr>
        nnoremap <space>f/ :LeaderfHistorySearch<cr>
    " initialize vim-plug
    call plug#end()

**Comment by Yggdroot** [comment]
Sorry, I still can not reproduce.
![000](https://user-images.githubusercontent.com/2705841/33006257-a4471340-ce04-11e7-8766-784b4cd9591d.gif)

**Comment by Yggdroot** [comment]
I can not reproduce even with your full [vimrc](https://github.com/auwsmit/dotfiles/blob/master/vimconfig/vimrc).

**Comment by auwsmit** [comment]
It's almost certainly on my end, then. I'll try to look more into it and post results if/when I find them.

Thanks a ton for the help and sorry for my mistake!

**Comment by auwsmit** [comment]
So, I'm dumb and left out this part of the error:

      ...
      File "C:\Users\aws\AppData\Roaming\vimfiles\plugged\LeaderF\autoload\leaderf\python\leaderf\asyncExecutor.py", line 80, in read
        raise Exception(lfEncode(lfBytes2Str(err)))
    Exception: File not found - -NAME^M
    Access denied - .^M
    File not found - -O^M
    File not found - -TYPE^M
    File not found - D^M
    File not found - -NAME^M
    File not found - .SVN^M
    File not found - -PRUNE^M
    File not found - -O^M
    File not found - -TYPE^M
    File not found - D^M
    File not found - -NAME^M
    File not found - .GIT^M
    File not found - -PRUNE^M
    File not found - -O^M
    File not found - -TYPE^M
    File not found - D^M
    File not found - -NAME^M
    File not found - .HG^M
    File not found - -PRUNE^M
    File not found - -O^M
    File not found - -TYPE^M
    File not found - F^M
    File not found - -PRINT^M
    sed: -e expression #1, char 1: unknown command: `''^M

Any ideas based on that? Maybe Windows line endings are somehow mucking things up during the process?

**Comment by Yggdroot** [comment]
This is the same as issue #87 . Because you are using dos command `find`.
The sequence of choosing external tool to index the files is `rg`->`ag`->`find`(if sed is also available).
You can install `rg` to solve the issue.

**Comment by auwsmit** [comment]
Hooray! It works now that I put `rg` in my path. 

I have `sed` from [Gow](https://github.com/bmatzelle/gow), but I guess it doesn't come with a unixey find..

also, *one* last question: How do I get git repositories to show up in my file searches?

![](https://i.imgur.com/GrQ1X8p.png)

e.g. I have a `vimfiles\plugged` folder full of my plugins, yet none of those files are in my results for `:LeaderfFile C:\Users\aws\AppData\Roaming\vimfiles`

**Comment by Yggdroot** [comment]
Use `rg --files` to see the files are listed.

**Comment by auwsmit** [comment]
Ah, it was because `rg` ignores .gitignore files by default. I added `let g:Lf_ExternalCommand = 'rg "%s" --files --no-ignore'`, and that got the desired result

**Comment by Yggdroot** [comment]
You can follow [here ](https://github.com/Yggdroot/LeaderF#performance) to install the C extension to get better performance.
