### ISSUE TITLE
希望在名字匹配的时候不拆分

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#920]
`Leaderf file --nowrap --nameOnly`
用上面的命令查找文件 结果如下
![image](https://user-images.githubusercontent.com/6241431/176357963-0c0b850a-90a5-4e22-aa53-17d7d3333d38.png)
希望只显示完整包含`mainp`的列表 而不是把这个拆分了去匹配 这个有办法设置吗 这样的话是不是速度很快些？

**Comment by Yggdroot** [comment]
如果有，肯定排在前面。而且现在的速度应该够用。

**Comment by gVimer** [comment]
是的  速度肯定是没问题 我只是说理论上的
