### ISSUE TITLE
Leadef function/line 在自动打开预览窗口的时候有延时

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#922]
WIN10下GVIM9.0中定义如下
`nnoremap <silent><Leader>f :let g:Lf_PreviewInPopua=1<CR>:exec("Leaderf  function  --nowrap ")<CR>`
`nnoremap <silent><Leader>l :let g:Lf_PreviewInPopua=1<CR>:exec("Leaderf  line  --nowrap ")<CR>`
`nnoremap <silent><Leader>g :let g:Lf_PreviewInPopua=1<CR>:exec("Leaderf  rg   --nowrap ")<CR>`
在前面两个命令执行后打开预览窗口会有延时 
![dopus_IlHQe3xQe7](https://user-images.githubusercontent.com/6241431/177479020-363089cf-e951-4045-83b5-e2a776e79af6.gif)
对比第三个命令则是瞬间打开
![dopus_Rvwdx1ULFD](https://user-images.githubusercontent.com/6241431/177479193-a786658b-bb2a-48b6-8ee6-c428f31eab0b.gif)

**Comment by Yggdroot** [comment]
修复了。

**Comment by gVimer** [comment]
感谢！上面的问题已经修正。但如果加上 ！后
```
nnoremap <silent><Leader>f :let g:Lf_PreviewInPopua=1<CR>:exec("Leaderf! function --nowrap ")<CR>
nnoremap <silent><Leader>l :let g:Lf_PreviewInPopua=1<CR>:exec("Leaderf! line --nowrap ")<CR>
```
第一个不能自动打开预览窗 第二个正常

**Comment by Yggdroot** [comment]
修复了。
你的map可以这样：
`nnoremap <silent><Leader>f :exec("Leaderf! function --nowrap --auto-preview")<CR>`

**Comment by gVimer** [comment]
感谢 确实可以了！在此之前我也尝试过加--auto-preview。

还有个小问题Popup中光标的定位是在原窗口中离光标最的函数 这个是故意这样设计的吗?可以强行定位到第一项吗？

执行命令前 原窗口的光标位置
![image](https://user-images.githubusercontent.com/6241431/177676612-be8265b2-b677-49ca-993e-a728e0c261d1.png)
执行命令后(原窗口和弹出窗口的背景颜色稍微不一样)
![image](https://user-images.githubusercontent.com/6241431/177676336-5c5bf77a-042d-4a8b-b61f-5e6d511cc386.png)

**Comment by Yggdroot** [comment]
是故意的。

**Comment by gVimer** [comment]
好的 但又发现一个问题 执行下面命令即加了 --auto-preview 后输入会导致下面的错误 不加是OK的
`nnoremap <silent><Leader>f :exec("Leaderf function --nowrap --auto-preview")<CR>`
![gVim_0Vri0f2i0o](https://user-images.githubusercontent.com/6241431/177682456-bef90bf8-c174-4286-a4ab-48f5441b8c4d.gif)



![Dingtalk_20220707110741](https://user-images.githubusercontent.com/6241431/177682474-9882f545-7957-4b21-adbf-199f46358d5b.jpg)

**Comment by gVimer** [comment]
还有个问题 就是VIM9.0可以用 **def** 开头来定义函数了 Leaderf function可能需要对应改下

**Comment by Yggdroot** [comment]
你这是什么语言？

**Comment by gVimer** [comment]
LUA

**Comment by Yggdroot** [comment]
使用的ctags，只有ctags增加支持才行。

**Comment by gVimer** [comment]
好的 其实问题不大 谢谢了
