### ISSUE TITLE
Leaderf mru在搜索的时候排序问题

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#923]
![image](https://user-images.githubusercontent.com/6241431/178127833-95141e9b-3c16-416d-ade2-fa466da13b7c.png)
上面的窗口是存储最近文件列表的文件 下面的窗口是执行`Leaderf  mru  --no-split-path --nowrap`后的结果 两者顺序一样OK
但是当我输入搜索的时候 搜索的结果就不是按照时间来排序的
![image](https://user-images.githubusercontent.com/6241431/178127904-e6f248f3-b6da-402b-bd44-a57e469686df.png)

**Comment by Yggdroot** [comment]
--no-sort

**Comment by gVimer** [comment]
多谢 加上就可以了 那能显示相对路径吗

**Comment by Yggdroot** [comment]
修复了。

**Comment by gVimer** [comment]
好的 我试试

**Comment by gVimer** [comment]
![image](https://user-images.githubusercontent.com/6241431/178172080-a716a9c9-5146-4dee-a834-ff24aeaf662e.png)
加上--no-sort后又出现这样的 完全匹配的都无法排在最前面

**Comment by Yggdroot** [comment]
不排序就是按照时间排序，如果完全匹配的排在前面，就没有按照实际排序，这两个需求矛盾。

**Comment by gVimer** [comment]
#920 那又回到这个问题 有考虑不拆分输入的内容去匹配吗？这块逻辑应该在C++里面吧

**Comment by Yggdroot** [comment]
对。
