### ISSUE TITLE
Leaderf XXX --recall不能恢复之前的正常模式

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#931]
用的是Popup窗口模式`let g:Lf_WindowPosition="popup"`
以**Leadef function**为例:上一次退出前是正常模式
![image](https://user-images.githubusercontent.com/6241431/179875144-8558017b-4f33-494e-ad35-d8f967149a53.png)
使用**Leaderf function --recall**后是输入模式
![image](https://user-images.githubusercontent.com/6241431/179875305-1f2f9fa6-c6f9-43fb-947f-2a1911c1a851.png)

**Comment by Yggdroot** [comment]
Leaderf! function --recall
可以，模式只由那个感叹号控制。

**Comment by gVimer** [comment]
这个我知道 我的意思是之前是什么模式 recall就应该是什么模式

**Comment by Yggdroot** [comment]
--recall 没这功能。

**Comment by gVimer** [comment]
**Leaderf --recall** 这样是可以的 但是这个只能恢复上一次的
