### ISSUE TITLE
当有多tab,执行Leaderf gtags相关命令的bug

### ISSUE THREAD

**Issue by fzhzhen1987** [Yggdroot/LeaderF#932]
commit 7dc648448e5de788e0498c8c789a980e19dda722

- vim or neovim? 
    - [* ] neovim
- Output of `vim --version` or `nvim --version`: NVIM v0.7.0
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: INFO: Python version: 3.6.9
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [* ] Linux

- Configurations related to LeaderF in vimrc: 

### Actual behaviour
使用的gtags引用命令(不论引用还是定义都需要修改这个bug.     bug举例是引用):
noremap <silent> <A-,> :<C-U><C-R>=printf("Leaderf gtags -r %s --auto-jump --top --auto-preview", expand("<cword>"))<CR><CR>
1.bug前的准备.
准备一:
<img width="894" alt="Snipaste_2022-07-20_13-10-22" src="https://user-images.githubusercontent.com/40282264/179895156-61eed720-6519-4f9a-b83a-20fb8ae772ff.png">

准备二:
<img width="895" alt="Snipaste_2022-07-20_13-17-02" src="https://user-images.githubusercontent.com/40282264/179895847-eb20a334-efc6-49c4-85b6-b99e7506f88c.png">

2.bug发生时的操作:在tab3中执行分屏操作C-X或C-]
bug结果:
①自动跳转到tab2刚才已经打开的结果位置
②tab3被分屏，但是是将tab3分屏复制，并没有显示查询的结果。
<img width="889" alt="Snipaste_2022-07-20_13-24-39" src="https://user-images.githubusercontent.com/40282264/179896560-db98155c-74c4-4b57-95a4-80dcf83e39b5.png">

受累了,改一下这个bug.你做的这个真挺好用的.

**Comment by fzhzhen1987** [comment]
看了手册发现解法了
let g:Lf_JumpToExistingWindow = 0
就是我想要的在tab3打开查找的引用结果。

**Comment by Yggdroot** [comment]
复现不了，是不是跟你的tab插件冲突。

**Comment by fzhzhen1987** [comment]
还想请教个问题,    g:Lf_NormalMap 的按键列表有么.想修改按键映射

**Comment by Yggdroot** [comment]
不明白你的意思。

**Comment by gVimer** [comment]
> 还想请教个问题, g:Lf_NormalMap 的按键列表有么.想修改按键映射

看文档啊 可以自定义的
