### ISSUE TITLE
Leaderf mru --cwd没有从根目录开始列出文件列表

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#933]
只是列出了当前目录及其子目录的文件 而不是从当前工作目录或者说根目录开始

**Comment by Yggdroot** [comment]
--cwd 就是这样啊。

**Comment by gVimer** [comment]
--cwd 不是说当前工作目录吗？工作目录和当前目录应该不是一个概念吧？

**Comment by gVimer** [comment]
那可能是我理解错了   我自己改成去改成工作目录吧 打扰了

**Comment by Yggdroot** [comment]
现在可以用Leaderf mru --project试一下。

**Comment by gVimer** [comment]
> 现在可以用`Leaderf mru --project`试一下。

完美
