### ISSUE TITLE
I want to know the popup windown ctermbg color mapped highlightname 

### ISSUE THREAD

**Issue by connectluole** [Yggdroot/LeaderF#934]
system:   Linux
terminal:   xterm
colorshchem:   duoduo
what is the problem:
![image](https://user-images.githubusercontent.com/16472308/180694761-b2cb156c-c35c-47d1-bc1f-83294478080f.png)

大神你好，我想知道popup框这几个不同的bg对应的名字，然后hack它，让他们变成同一个颜色，不然看起来有点分裂，请问可以告知这些highlight的名字嘛？ 我就可以hack他们了。

**Comment by connectluole** [comment]
![image](https://user-images.githubusercontent.com/16472308/180695247-916d4a54-29eb-4d74-bc58-3b4ce53c826a.png)

**Comment by Yggdroot** [comment]
bg3 is Lf_hl_popup_window, bg2 LineNr, bg1 is FoldColumn.

**Comment by connectluole** [comment]
![image](https://user-images.githubusercontent.com/16472308/180995742-21b09fa9-25bc-42ab-9e66-4195975617c1.png)

thanks very much for the immediately reply, this works !
