### ISSUE TITLE
为什么命令 LeaderF gtags 只搜索 .cpp/.java 等文件的而不搜索 .go/.rs 等文件？

### ISSUE THREAD

**Issue by zeminzhou** [Yggdroot/LeaderF#936]
我尝试用 LeaderF gtags 去搜索的时候，为什么LeaderF 只显示  .cpp/.java 等文件的内容，而不显示 .go/.rs 等文件内容？在 .LFCache/gtags/go项目 下面生成的 GPATH，GRTAGS, GTAGS 里面也有数据。

- vim or neovim? 
    - [*] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [*] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

let g:Lf_GtagsGutentags = 1
let g:Lf_CacheDirectory = expand('~')
let g:gutentags_cache_dir = expand(g:Lf_CacheDirectory.'/.LfCache/gtags')
noremap <leader>ft :<C-U><C-R>=printf("Leaderf gtags %s", "")<CR><CR>

let $GTAGSLABEL = 'native-pygments'
let $GTAGSCONF = '/root/.globalrc

**Comment by Yggdroot** [comment]
可能是以为go rust是新语言，gtags不支持，参考#830。
