### ISSUE TITLE
utf-8出错

### ISSUE THREAD

**Issue by feng84** [Yggdroot/LeaderF#94]
运行命令:LeaderfHistoryCmd ，出错如下：

Traceback (most recent call last):                                                                          
  File "<string>", line 1, in <module>                                                                      
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 726, in startExplorer  
    content = self._getExplorer().getContent(*args, **kwargs)                                               
  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/historyExpl.py", line 22, in getContent  
    tmp = lfEval("@x")                                                                                      
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 13: invalid start byte

python是系统自带的版本3.6.3，vim已设置utf-8编码，工作正常的。看了半天，不知道bug出在哪儿

**Comment by Yggdroot** [comment]
我这边没法复现。
希望你能多提供点信息：
`:echo g:Lf_PythonVersion`
`:reg x`
`:echo &encoding`
以及vimrc中编码相关的设置。

**Comment by feng84** [comment]
我找到原因了，@x里有"..<80>..."，导致失败，寄存器x清掉就可以了，谢谢！

**Comment by feng84** [comment]
这里代码可能需要修改
我查了下，是<80>kb导致的，这个backspace的内部表示，backspace保存到寄存器时，都会转换成<80>kb，所以可能导致:LeaderfHistory...出现错误率较高

**Comment by Yggdroot** [comment]
这个你可以帮忙改吗？欢迎Pull Request

**Comment by Yggdroot** [comment]
奇怪，在我这边，即使有<80>kb，也不会出错。

**Comment by feng84** [comment]
不好意思，我对python不熟。这个<80>kb不是直接输入的，<80>是一个字符，不是4个，如下操作可以得到
qx，输入xxx，用backspace删除一个字母，q
:reg x，就能看到@x里是xx<80>kb

**Comment by Yggdroot** [comment]
我明白你的意思，我就是录宏录进去的，但我这边还是没有错。
tmp = lfEval("@x")只是一句赋值，怎么会错呢，奇怪。
你的下面的输出是什么？
```
:echo g:Lf_PythonVersion
:echo &encoding
```
还有vimrc里编码相关的配置？
另外你直接执行以下`:py print vim.eval("@x")`看一下

**Comment by feng84** [comment]
没事就再看了下，python2没问题，python3有问题，搜了下，如下信息可供你参考
https://github.com/SirVer/ultisnips/issues/171
https://docs.python.org/3/howto/unicode.html#the-unicode-type

没时间深究，感觉没什么好办法，ultisnips用try catch绕过去了
用了个变通办法，@x直接保存在vim变量然后取回，autoload/leaderf/python/leaderf/historyExpl.py 

22行：
```
#tmp = lfEval("@x")
lfCmd('let tmp = eval("@x")')
```                                                                 

35行：
```                                                                 
#lfCmd("let @x = '%s'" % escQuote(tmp))
lfCmd("let @x = tmp")
```

**Comment by Yggdroot** [comment]
谢谢你的提示，已经fix了。
