### ISSUE TITLE
vim9.0 fileExpl.py line 914 

### ISSUE THREAD

**Issue by owner888** [Yggdroot/LeaderF#945]
File "~/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/fileExpl.py", line 914, in _acceptSelection^@    lfCmd("hide edit %s" % escSpecial(file))^@vim.error: css_color: create_syn_match invoked on bad match data

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
VIM - Vi IMproved 9.0 (2022 Jun 28, 编译于 Jul 25 2022 07:38:38)
macOS 版本 - arm64
包含补丁: 1-65
编译者 Homebrew

- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): null, but old version is /System/Library/Frameworks/Python.framework/Versions/2.7/Python
- Output of `:echo &pythonthreedll`(only vim, not neovim): null, but old version is /System/Library/Frameworks/Python.framework/Versions/3.9/Python
- Output of `:py print(sys.version)`: 抱歉, 命令在此版本中不可用
- Output of `:py3 print(sys.version)`: 
    3.10.6 (main, Aug 11 2022, 13:36:31) [clang-1316.0.21.2.5)]
    but old version is:
    3.9.13 (main, Aug 11 2022, 13:40:36) [Clang 13.1.6 (clang-1316.0.21.2.5)]
- Output of `:echo g:Lf_Debug_Cmd`:  未定义的变量: g:Lf_Debug_Cmd, also old version
- Output of `:echo g:Lf_FilesFromCache`: 未定义的变量:  g:Lf_FilesFromCache, also old version
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc:

**Comment by Yggdroot** [comment]
How to reproduce ?

**Comment by owner888** [comment]
> How to reproduce ?

just upload to vim9.0 can reproduce,  no need macvim

**Comment by Yggdroot** [comment]
Only install LeaderF and have a try.

**Comment by owner888** [comment]
> Only install LeaderF and have a try.

I updated the 9.0 update again today and found that the problem is no longer there
