### ISSUE TITLE
Leaderf rg on the fly mode has poor search result

### ISSUE THREAD

**Issue by ykqiu** [Yggdroot/LeaderF#957]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 8.0
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): no
- Output of `:py print(sys.version)`: 2.7.5 (default, Mar 20 2020, 17:08:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
- Output of `:py3 print(sys.version)`: no
- Output of `:echo g:Lf_Debug_Cmd`: no
- Output of `:echo g:Lf_FilesFromCache`: no
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
no
### Describe your question, feature request, or bug.
directly using Leaderf rg(without any argument), then search on the fly, I found it hard to finding desired results, compared to using Laderf rg xxx(or Leaderf rg -e xxx), which I could get desired result on the top.
### Steps to reproduce
Press :Leaderf rg
### Actual behaviour
cannot find pattern I want
### Expected behaviour
find the result just as using Leaderf rg xxx

**Comment by eyalk5** [comment]
Indeed , it passes over a small subset of the files in case the directory contain many files.
