### ISSUE TITLE
How to show history for leaderf gtags

### ISSUE THREAD

**Issue by qifeng-git** [Yggdroot/LeaderF#959]
使用 leaderf gtags 对文件中的多个函数进行过搜索，
使用 leadf gtags --recall 只能快速调出最后一次的搜索内容，
如何快速调出对之前函数的搜索？

**Comment by Yggdroot** [comment]
没这个功能

**Comment by keeferwu** [comment]
https://github.com/keeferwu/LeaderF-gtags-history
