### ISSUE TITLE
g:Lf_RootMarkers option seems not work on Windows

### ISSUE THREAD

**Issue by zhmars** [Yggdroot/LeaderF#96]
use below config,  LeaderF only show file in current directory, not the parent  where `target.txt` exist

```vim
let g:Lf_RootMarkers = ['target.txt']
```

![image](https://user-images.githubusercontent.com/18466397/34067957-0166aa5e-e26e-11e7-9633-41bfff5d1874.png)

**Comment by Yggdroot** [comment]
You should also set `let g:Lf_WorkingDirectoryMode = 'ac'` or `let g:Lf_WorkingDirectoryMode = 'Ac'`, please refer to below:
https://github.com/Yggdroot/LeaderF/blob/379fe98b1c0b327af1474c84b8de18acbdcab4ea/doc/leaderf.txt#L446-L471

**Comment by zhmars** [comment]
Thank you for your reply!

I should have read the document more carefully. It works now
