### ISSUE TITLE
some sshfs files not found

### ISSUE THREAD

**Issue by ly1243667342** [Yggdroot/LeaderF#962]
- vim or neovim? 
    - [ ] vim
    - [ x] neovim
- Output of `vim --version` or `nvim --version`: 
- NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

- Output of `:echo has("python")`: 
0
- Output of `:echo has("python3")`: 
1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
0
- Operating system: 
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
ls -alh can see the blow files. but leadf only can find Makefile, other files can not find. why? this dir is by  sshfs mount server dir.
total 608K
drwxrwxrwx 1 68001826 vboxsf 4.0K 10月 12 16:11 .
drwxr-xr-x 1 68001826 vboxsf 4.0K 10月 12 16:11 ..
-rwxr-xr-x 1 68001826 vboxsf  71K 10月 12 16:11 codegen.c
-rw-r--r-- 1 68001826 vboxsf  250 10月 12 16:11 codegen.h
-rw-r--r-- 1 68001826 vboxsf 317K 10月 12 16:11 codegen.o
-rwxr-xr-x 1 68001826 vboxsf 2.7K 10月 10 13:29 Makefile

**Comment by Yggdroot** [comment]
What is the Output of `:echo g:Lf_Debug_Cmd`?

**Comment by ly1243667342** [comment]
> 

E121: Undefined variable: g:Lf_Debug_Cmd

**Comment by ly1243667342** [comment]
> What is the Output of `:echo g:Lf_Debug_Cmd`?

E121: Undefined variable: g:Lf_Debug_Cmd

**Comment by Yggdroot** [comment]
`:echo g:Lf_Debug_Cmd` after running Leaderf file.

**Comment by ly1243667342** [comment]
> 



> `:echo g:Lf_Debug_Cmd` after running Leaderf file.

rg --no-messages --files --color never

**Comment by ly1243667342** [comment]
> > 
> 
> > `:echo g:Lf_Debug_Cmd` after running Leaderf file.
> 
> rg --no-messages --files --color never

➜  api rg --no-messages --files --color never
Makefile
➜  api ls -alh
total 608K
drwxrwxrwx 1 68001826 vboxsf 4.0K 10月 12 16:11 .
drwxr-xr-x 1 68001826 vboxsf 4.0K 10月 12 16:11 ..
-rwxr-xr-x 1 68001826 vboxsf  71K 10月 12 16:11 codegen.c
-rw-r--r-- 1 68001826 vboxsf  250 10月 12 16:11 codegen.h
-rw-r--r-- 1 68001826 vboxsf 317K 10月 12 16:11 codegen.o
-rwxr-xr-x 1 68001826 vboxsf 2.7K 10月 10 13:29 Makefile

**Comment by ly1243667342** [comment]
> 



> > > 
> > 
> > 
> > > `:echo g:Lf_Debug_Cmd` after running Leaderf file.
> > 
> > 
> > rg --no-messages --files --color never
> 
> ➜ api rg --no-messages --files --color never Makefile ➜ api ls -alh total 608K drwxrwxrwx 1 68001826 vboxsf 4.0K 10月 12 16:11 . drwxr-xr-x 1 68001826 vboxsf 4.0K 10月 12 16:11 .. -rwxr-xr-x 1 68001826 vboxsf 71K 10月 12 16:11 codegen.c -rw-r--r-- 1 68001826 vboxsf 250 10月 12 16:11 codegen.h -rw-r--r-- 1 68001826 vboxsf 317K 10月 12 16:11 codegen.o -rwxr-xr-x 1 68001826 vboxsf 2.7K 10月 10 13:29 Makefile ➜ api rg --files Makefile ➜ api find ./ -type f ./codegen.o ./codegen.h ./Makefile ./codegen.c
> 
> what is wrong with rg? thanks!

➜  api rg -uuu --files
codegen.o
codegen.h
Makefile
codegen.c

add -uuu parameter can resolve the problem. How to alter leaderf to adapt rg?

**Comment by Yggdroot** [comment]
Have a try `Leaderf file --no-ignore`.

**Comment by ly1243667342** [comment]
> `Leaderf file --no-ignore`.

It works. Thanks

**Comment by Yggdroot** [comment]
> Have a try `Leaderf file --no-ignore`.

So why are these files in the .gitignore?

**Comment by Yggdroot** [comment]
> > > `Leaderf file --no-ignore`.
> > 
> > 
> > It works. Thanks
> 
> But, `Leaderf! rg -t c -t cpp -e buf `can not search key word in the mising files.How to resolve the issue?

Leaderf rg --no-ignore
