### ISSUE TITLE
how to search and open a dot file with LeaderF?

### ISSUE THREAD

**Issue by dimosz** [Yggdroot/LeaderF#963]
hi,
I have some dot files in my project's root directory. Sometimes, I want to open them with LeaderF, but no result.
How can I search and open them with LeaderF like a normal file?

Thanks

**Comment by Yggdroot** [comment]
let g:Lf_ShowHidden = 1

**Comment by dimosz** [comment]
@Yggdroot 

Thank you so much for this great plugin.
