### ISSUE TITLE
How to transport LeaderF vim keybind to lua

### ISSUE THREAD

**Issue by fzhzhen1987** [Yggdroot/LeaderF#964]
I want to transport keybind to Lua format.But i have no idea.
noremap <silent> <leader>js :\<C-U\>\<C-R\>=printf("Leaderf gtags -s %s --top --auto-preview", expand("\<cword\>"))\<CR\>\<CR\>

lua keybind format like this,but error.

local opts = { noremap = true, silent = true } 
local keymap = vim.api.nvim_set_keymap
keymap("n", "<leader>js", ":\<C-U\>\<C-R\>=printf("Leaderf gtags -s %s --top --auto-preview", expand("\<cword\>"))\<CR\>\<CR\>", opts)

**Comment by Yggdroot** [comment]
I don't know lua.
