### ISSUE TITLE
REPO project，Leadef files cannot find files under sub git repository

### ISSUE THREAD

**Issue by JaminYoung** [Yggdroot/LeaderF#966]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.2
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): no output
- Output of `:echo &pythonthreedll`(only vim, not neovim): no output
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.7.10 
(default, May 31 2021, 10:48:48)
[GCC 5.4.0 20160609]

- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 1
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
my latest project is managed  by Repo, so there are several git repositories under sub-directory. In this case, I couldn't look up files under sub-directory which is managed by another git repository by using cmd "Leaderf files ".

I have tried several ways refrenced in history issues but failed in the end.
first I tried  add belows lines in vimrc

    let g:Lf_UseVersionControlTool = 0
    let g:Lf_DefaultExternalTool = "rg" 
 then I run `echo g:Lf_Debug_Cmd` which output is `rg --no-messages --files --color never`
 which seems right, but I still can't files which is in other git repository

I also tried `let g:Lf_ExternalCommand = 'rg --files %s'`
after run  `echo g:Lf_Debug_Cmd` which output is `rg --files "."`
and I still failed to look up files in under repository...

I confirm rg installed and works well as I type rg --files "xxx" , results show up instantly.

**Comment by Yggdroot** [comment]
let g:Lf_RecurseSubmodules = 1

**Comment by Yggdroot** [comment]
What is the hierarchy of your Repo?

**Comment by Yggdroot** [comment]
Are the folders of other git repo in the .gitignore?

**Comment by Yggdroot** [comment]
Run `rg --no-messages --files --color never` in the command line, I think it should work.

**Comment by JaminYoung** [comment]
> Are the folders of other git repo in the .gitignore?



> Are the folders of other git repo in the .gitignore?

yes, so it seems to be the reason?  How can I exclude the .gitignore files whithout modifiled the .gitignore

**Comment by Yggdroot** [comment]
`Leaderf file --no-ignore`.

**Comment by JaminYoung** [comment]
> Run `rg --no-messages --files --color never` in the command line, I think it should work.

I run `rg --no-messages --files --color never > tmp_file`,  and files in sub-directory didn't exits in the tmp_files.
but if run `rg --files "xxx"  > tmp_file`, files in sub-directory match the pattern 'xxx' can be found

run `Leaderf file --no-ignore` only show up the directory'name in .gitignore which matchs the pattern , but files under sub-directory  which matchs the patternstill can't be found

**Comment by JaminYoung** [comment]
set `let g:Lf_UseVersionControlTool = 0`
`let g:Lf_DefaultExternalTool = "rg" `,
plus with running `Leaderf file --no-ignore` works, confusing :)

**Comment by JaminYoung** [comment]
but I do want to exclude some files in .gitnore except the the sub-directory , is there any bettery way to acchive this?

**Comment by JaminYoung** [comment]
using g:Lf_WildIgnore would will fix this, thank you so much

**Comment by 416207298** [comment]
How to auto execute this command `Leaderf file --no-ignore`  when enter vim ? 
I've tried to write down `autocmd BufWinEnter  Leaderf file --no-ignore` in `.vimrc` but it did not work.

**Comment by 416207298** [comment]
Finally, I write like this to solve that:
``` vim
func OpenLeaderF()
  :Leaderf file --no-ignore
  :LeaderfFile
endfunc

nnoremap <c-p> :call OpenLeaderF()<cr>

```
