### ISSUE TITLE
Leaderf rg error

### ISSUE THREAD

**Issue by abcvav** [Yggdroot/LeaderF#967]
- vim or neovim? 
    - [ ] vim
    - [x] neovim
- Output of `vim --version` or `nvim --version`:
  ```
  NVIM v0.8.0-1210-gd367ed9b2
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  Compiled by runneradmin@fv-az177-603
  
  Features: -acl +iconv +tui
  See ":help feature-compile"
  
     system vimrc file: "$VIM\sysinit.vim"
    fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
  
  Run :checkhealth for more info
  ```

- Output of `:echo has("python")`:  `0`
- Output of `:echo has("python3")`: `1`
- Output of `:py print(sys.version)`: 
   `3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]`
- Output of `:py3 print(sys.version)`: 
   `3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]`
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

```vimscript
call plug#begin('~/.vim/plugged')
Plug 'Yggdroot/LeaderF' ", { 'do': ':LeaderfInstallCExtension' }
call plug#end()
```
### Steps to reproduce
Input `:Leaderf rg` when neovim is open.

### Actual behaviour
![image](https://user-images.githubusercontent.com/47599849/202115803-aa0cbd28-316b-4e2b-8a78-e57525b444e2.png)

### Expected behaviour
no error

**Comment by Yggdroot** [comment]
Have you installed rg?

**Comment by abcvav** [comment]
> Have you installed rg?

Sorry no, I'm new to vim, and have no idea what else need to be installed except for LeaderF itself, I only install LeaderF using `Plug 'Yggdroot/LeaderF' ", { 'do': ':LeaderfInstallCExtension' }` following the instruction.

**Comment by Yggdroot** [comment]
Install rg please.

**Comment by abcvav** [comment]
Ok, thank you
