### ISSUE TITLE
Why the gtags in the ~/.LfCache/gtags is empty?

### ISSUE THREAD

**Issue by boyjoy1127** [Yggdroot/LeaderF#970]
Why the gtags in the ~/.LfCache/gtags is empty?

directory in `~/.LfCache/gtags` is empty
'~/.cache/tags' is not empty.  There is GTAGS in the directory.
Could I configure Leaderf to use that GTAGS path? and how？

- vim or neovim? 
    - [X] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 8.2
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 0
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.7m.a
- Output of `:py print(sys.version)`: 2.7.12 (default, Mar  1 2021, 11:38:31) [GCC 5.4.0 20160609]
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`:E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: Undefined variable: g:Lf_FilesFromCache
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
  "-----------------------------------------
  " LeaderF 
  "
  " don't show the help in normal mode
  let g:Lf_HideHelp = 1 
  let g:Lf_UseCache = 0 
  let g:Lf_UseVersionControlTool = 0 
  let g:Lf_IgnoreCurrentBufferName = 1 
  " popup mode
  let g:Lf_WindowPosition = 'popup'
  let g:Lf_PreviewInPopup = 1 
  let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
  let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 } 
  let mapleader=","
  let g:Lf_ShortcutF = "<leader>ff"
  noremap <leader>fb :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
  noremap <leader>fm :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
  noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
  noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>
  noremap <leader>ffun :<C-U><C-R>=printf("Leaderf function %s", "")<CR><CR>
  
  noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
  noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
  " search visually selected text literally
  xnoremap gf :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
  noremap go :<C-U>Leaderf! rg --recall<CR>
  
  " should use `Leaderf gtags --update` first
  let g:Lf_GtagsAutoGenerate = 1 
  let g:Lf_Gtagslabel = 'native-pygments'
  noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
  noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
  noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
  noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
  noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>

```
### Describe your question, feature request, or bug.
Fail to execute 'Leaderf gtags --update', result is below:
```
gtags: unrecognized option '--skip-symlink'
Usage: gtags [-ciIOqvw][-d tag-file][-f file][dbpath]
gtags error!

```

### Steps to reproduce
Leaderf gtags --update

### Actual behaviour
directory in `~/.LfCache/gtags` is empty
'~/.cache/tags' is not empty.  There is GTAGS in the directory.
Could I configure Leaderf to use that GTAGS path? and how？

**Comment by Yggdroot** [comment]
let g:Lf_GtagsHigherThan6_6_2 = 0

**Comment by swordligit** [comment]
I also have this isuse, and the 
```
let g:Lf_GtagsHigherThan6_6_2 = 0
```
works indeed, but that is strange,my gtags version is higher than 6.6.2.
```
gtags --version
gtags (Global) 6.6.7
Powered by Berkeley DB 1.85 and SQLite3 3.37.2.
Copyright (c) 1996-2021 Tama Communications Corporation
License GPLv3+: GNU GPL version 3 or later <http://www.gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
does the Lf_GtagsHigherThan6_6_2 not mean the gtags version?
