### ISSUE TITLE
Can not find the file if whe workspace includes multi-repos.

### ISSUE THREAD

**Issue by swordligit** [Yggdroot/LeaderF#971]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
     -VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 10 2022 08:40:37)
     Included patches: 1-749
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): none
- Output of `:echo &pythonthreedll`(only vim, not neovim): none
- Output of `:py print(sys.version)`: E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
- Output of `:echo g:Lf_Debug_Cmd`: E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: E121: Undefined variable: g:Lf_FilesFromCach
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```
" LeaderF
" don't show the help in normal mode
let g:Lf_HideHelp = 1
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
" popup mode
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_StlSeparator = { 'left': "\ue0b0", 'right': "\ue0b2", 'font': "DejaVu Sans Mono for Powerline" }
let g:Lf_PreviewResult = {'Function': 0, 'BufTag': 0 }

let g:Lf_ShortcutF = "<leader>ff"
noremap <leader>m :<C-U><C-R>=printf("Leaderf mru %s", "")<CR><CR>
noremap <leader>b :<C-U><C-R>=printf("Leaderf buffer %s", "")<CR><CR>
noremap <leader>ft :<C-U><C-R>=printf("Leaderf bufTag %s", "")<CR><CR>
noremap <leader>fl :<C-U><C-R>=printf("Leaderf line %s", "")<CR><CR>

" noremap <C-B> :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
" noremap <C-F> :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>
noremap <leader>fb :<C-U><C-R>=printf("Leaderf! rg --current-buffer -e %s ", expand("<cword>"))<CR>
noremap <leader>fe :<C-U><C-R>=printf("Leaderf! rg -e %s ", expand("<cword>"))<CR>

" search visually selected text literally
xnoremap <leader>fg :<C-U><C-R>=printf("Leaderf! rg -F -e %s ", leaderf#Rg#visual())<CR>
noremap go :<C-U>Leaderf! rg --recall<CR>

" should use `Leaderf gtags --update` first
let g:Lf_GtagsAutoGenerate = 0
let g:Lf_Gtagslabel = 'native-pygments'
noremap <leader>fr :<C-U><C-R>=printf("Leaderf! gtags -r %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fd :<C-U><C-R>=printf("Leaderf! gtags -d %s --auto-jump", expand("<cword>"))<CR><CR>
noremap <leader>fo :<C-U><C-R>=printf("Leaderf! gtags --recall %s", "")<CR><CR>
noremap <leader>fn :<C-U><C-R>=printf("Leaderf gtags --next %s", "")<CR><CR>
noremap <leader>fp :<C-U><C-R>=printf("Leaderf gtags --previous %s", "")<CR><CR>
```

### Describe your question, feature request, or bug.
when input the \<leader\>ff, which call :<C-U>LeaderfFile<CR>,it can not find myfile.
### Steps to reproduce
I have a large code base, and use the android repo tool, the file I search is not
in the currently git repo.
1, repo list:
 : smartos
apps : nuttx_apps
framework/services : services
mirtos : nuttx
2. find . -name rptun.h -type f
./mirtos/nuttx/drivers/rptun/rptun.h
./mirtos/nuttx/include/nuttx/rptun/rptun.h
3. LeaderfFile
### Actual behaviour
can not find rptun.h

### Expected behaviour
should list the rptun.h, at least two files.

**Comment by swordligit** [comment]
Interesting, if I move all the .git in the workspace, it will list the files.

**Comment by Yggdroot** [comment]
Leaderf file --no-ignore

**Comment by swordligit** [comment]
That works, thank a lot.
but how to customized the shortcut? I change the file to
```
diff --git a/plugin/leaderf.vim b/plugin/leaderf.vim
index 54d28b4..13f7c9a 100644
--- a/plugin/leaderf.vim
+++ b/plugin/leaderf.vim
@@ -245,7 +245,7 @@ command! -bar -nargs=0 LeaderfLocList  Leaderf loclist
 
 try
     if g:Lf_ShortcutF != ""
-        exec 'nnoremap <silent><unique> ' g:Lf_ShortcutF ':<C-U>LeaderfFile<CR>'
+        exec 'nnoremap <silent><unique> ' g:Lf_ShortcutF ':<C-U>LeaderfFile --no-ignore<CR>'
     endif
 catch /^Vim\%((\a\+)\)\=:E227/
 endtry 
```

**Comment by Yggdroot** [comment]
`noremap <leader>ff :<C-U>Leaderf file --no-ignore<CR>`

**Comment by swordligit** [comment]
It works, thank you!
