### ISSUE TITLE
Strange chars in buffers

### ISSUE THREAD

**Issue by eyalk11** [Yggdroot/LeaderF#975]
- vim or neovim? 
    - [ ] vim
    - [x ] neovim
- Output of `vim --version` or `nvim --version`: 
- NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az30-11

- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.9.6
- 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

```
let g:Lf_DevIconsFont = "DroidSansMono Nerd Font Mono"

set ambiwidth=double
let g:Lf_PreviewResult = {
			\ 'File': 0,
			\ 'Buffer': 1,
			\ 'Mru': 0,
			\ 'Tag': 0,
			\ 'BufTag': 1,
			\ 'Function': 1,
			\ 'Line': 1,
			\ 'Colorscheme': 0,
			\ 'Rg' : 1
			\}
"When you go to normal mode , doing I inserts the line
"call win_execute(%d, "exec 'norm! %yy'")""" % (self._preview_winid, line_nr))
			"\'Line':[['I','"zyy:exec g:Lf_py "lineExplManager.quit()"<CR>"zp']],

"			\'Line':[['I','exec g:Lf_py "call win_execute(%d, "exec ''norm! "zyy''")" % (lineExplManager._preview_winid)<CR>:exec g:Lf_py "lineExplManager.quit()"<CR>"zp']]
let g:Lf_NormalMap ={ 
			\ 'Line':[['I','"zyt[:exec g:Lf_py "lineExplManager.quit()"<CR>"zp']],
			\ 'File':[['I','"zyy:exec g:Lf_py "lineExplManager.quit()"<CR>"zp']],
		\ 'History' :[['I','"zyy:exec g:Lf_py "lineExplManager.quit()"<CR>"zp']]
			\} 

let g:Lf_StlSeparator = { 'left': '', 'right': '' }

let g:Lf_StlColorscheme = 'powerline'
"Make c-h , c-l a valid option in leaderf
let g:Lf_CommandMap = {'<C-k>':['<C-h>'], '<C-j>':['<C-l>'], '<Down>': ['<C-j>','<Down>'], '<UP>': ['<C-k>','<UP>']}

let g:Lf_MruMaxFiles=100000
let g:Lf_ShowHidden  = 1
let g:Lf_MaxCount = 50000
let g:Lf_PreviewInPopup =0

let g:Lf_PopupHeight =0.5
let g:Lf_PopupWidth =0.9
let g:Lf_WindowPosition = 'popup'

""ideally would be called each time
let g:Lf_PopupPosition=[max([float2nr(&lines * 0.4),10]),1]
let g:Lf_CacheDirectory = "c:\\users\\ekarni\\.vim\\lcache"
let g:Lf_IndexTimeLimit =7
let g:Lf_RgConfig = [ "--max-columns=150"]
let g:Lf_WorkingDirectoryMode = 'c'
```

### Describe your question, feature request, or bug.
When I am running buffers ,sometimes(always) I get strange chars when typing. 

### Steps to reproduce
:LeaderfMru
### Actual behaviour
![image](https://user-images.githubusercontent.com/72234965/207725220-656cf2b3-2210-4af6-bec5-40c4a42bfb67.png)

The c in the beginning of files doesn't exists. It includes the first letter I type in the beginning of every line.

I get the same behavior in `leaderf --popup buffers` sometimes. 

I am updated up to 1326f60715adf6c434c0a6287e071af02d13dc26 (6th dec)

**Comment by Yggdroot** [comment]
Have a try `set ambiwidth=single` or `let g:Lf_ShowDevIcons = 0`.
Maybe there is bug with nvim rendering.

**Comment by eyalk11** [comment]
Solves it, thanks
