### ISSUE TITLE
Results didn't appear for new added directory?

### ISSUE THREAD

**Issue by ucasfl** [Yggdroot/LeaderF#978]
When search files, the new added directory of the project didn't appear in the menu? does something wrong or because some cache do not clear?

**Comment by Yggdroot** [comment]
what is the output of :echo g:Lf_Debug_Cmd ?

**Comment by ucasfl** [comment]
> echo g:Lf_Debug_Cmd

git ls-files  "/data/fenglv/ClickHouse" && git ls-files --others --exclude-standard  "/data/fenglv/ClickHouse"

**Comment by Yggdroot** [comment]
> > echo g:Lf_Debug_Cmd
> 
> git ls-files "/data/fenglv/ClickHouse" && git ls-files --others --exclude-standard "/data/fenglv/ClickHouse"

Run this command in the command line to see why.
