### ISSUE TITLE
LeaderfFile does not work properly when using with lcd

### ISSUE THREAD

**Issue by xltan** [Yggdroot/LeaderF#98]
g:Lf_WorkingDirectoryMode is the default value
autochdir is not set.

steps to reproduce the bug:
1. open vim
2. open a new window(a tab works too), edit another directory using lcd (so the first window's working directory should not be affected)
3. launch LeaderfFile at the newly created window and accept a file, now the first window's working directory is also changed.

the bug may caused by os.chdir cmd located in fileExpl.py 596 line

**Comment by Yggdroot** [comment]
Fixed.
But the issue still exists if `g:Lf_WorkingDirectoryMode` or `autochdir` is set up, and I don't know how to fix it any more.

**Comment by xltan** [comment]
👍
