### ISSUE TITLE
怎么把输出定向到quickfix窗口

### ISSUE THREAD

**Issue by swordligit** [Yggdroot/LeaderF#980]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: IM - Vi IMproved 9.0 (2022 Jun 28, compiled May 10 2022 08:40:37)
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): nothing
- Output of `:echo &pythonthreedll`(only vim, not neovim): nothing
- Output of `:py print(sys.version)`: E319: Sorry, the command is not available in this version
- Output of `:py3 print(sys.version)`: E319: Sorry, the command is not available in this version
- Output of `:echo g:Lf_Debug_Cmd`:  
   E121: Undefined variable: g:Lf_Debug_Cmd
- Output of `:echo g:Lf_FilesFromCache`: 
   E121: Undefined variable: g:Lf_FilesFromCache
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
把命令Leaderf! rg -e 的输出从popup 窗口输出到quickfix窗口

**Comment by Yggdroot** [comment]
normal模式下按Q

**Comment by swordligit** [comment]
OMG，that works, 哪里有文档啊，没看到

**Comment by Yggdroot** [comment]
文档比较隐秘，https://github.com/Yggdroot/LeaderF/wiki/Leaderf-rg
谢谢你的coffee。
