### ISSUE TITLE
<C-J> and <C-K> map not work

### ISSUE THREAD

**Issue by zoumi** [Yggdroot/LeaderF#981]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Dec  7 2022 23:14:31)
MS-Windows 64-bit console version
Included patches: 1-1026
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.  Features included (+) or not (-):
```
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): python27.dll
- Output of `:echo &pythonthreedll`(only vim, not neovim): python38.dll
- Output of `:py print(sys.version)`: 
```
Could not load library python27.dll
...
```
- Output of `:py3 print(sys.version)`: 
```
3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
```
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
 ```vim
pyx=3
set langmenu=none
let $LANG = 'en'
let $VIM_DIR = $VIM

let $PATH .= ';' . $VIM_DIR
set scrolloff=5
set nocompatible              " be iMproved, required
filetype off                  " required
set pythonthreedll=python38.dll
call plug#begin('$VIM_DIR/vimfiles/plugged')
" ===========================
let g:Lf_UseCache = 0
let g:Lf_UseVersionControlTool = 0
let g:Lf_IgnoreCurrentBufferName = 1
let g:Lf_WindowPosition = 'popup'
let g:Lf_ShowDevIcons = 0
let g:Lf_PreviewInPopup = 1
let g:Lf_PreviewResult = {'Function': 1, 'BufTag': 1 ,'Rg': 1 }
let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}
let g:Lf_ShortcutF = "<leader>ff"
let g:Lf_GtagsGutentags = 1
Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
" ===========================
call plug#end()
filetype plugin indent on    " required
set backupcopy=yes
 ```

### Describe your question, feature request, or bug.
Can't move down  using \<C-J>  in LeaderF popup window.

### Steps to reproduce
1,press \<leader>ff
2,press \<C-J> when popup window is shown.

### Actual behaviour
next item is not selected

### Expected behaviour
next item is selected

**Comment by forceofsystem** [comment]
I have the same problem. My mapping configuration is
```viml
let g:Lf_CommandMap = {'<C-K>': ['<C-J>'], '<C-L>': ['<C-K>']}
" I also try this:
let g:Lf_CommandMap = {'<A-K>': ['<C-J>'], '<A-L>': ['<C-K>']}
```
It doesn't work.

**Comment by Yggdroot** [comment]
@zoumi  Please remove `let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}`

**Comment by zoumi** [comment]
@Yggdroot Yes,it works after removing ```let g:Lf_CommandMap = {'<C-K>': ['<Up>'], '<C-J>': ['<Down>']}```. But <Up> and <Down> will not work anymore.

**Comment by Yggdroot** [comment]
`let g:Lf_CommandMap = {'<C-K>': ['<Up>', '<C-K>'], '<C-J>': ['<Down>', '<C-J>']}`
