### ISSUE TITLE
not use

### ISSUE THREAD

**Issue by weisiok365** [Yggdroot/LeaderF#983]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: 
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.
config .vimrc ,following as :
" find key word
nnoremap <space>a :Leaderf rg -i<cr>
nnoremap <space>A :Leaderf rg -i --cword<cr>
xnoremap <space>a :<c-u>execute ":Leaderf rg -i --input " . <sid>GetSelectArea()<cr>
xnoremap <space>A :<c-u>execute ":Leaderf rg -i " . <sid>GetSelectArea()<cr><tab>

input  space + a / A，appear as:

file "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/cli.py", line 696, in input^@    callback()^@  File "/root/.vim/plugged/LeaderF/autoload/l
eaderf/python/leaderf/manager.py", line 70, in deco^@    func(self, *args, **kwargs)^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/ma
nager.py", line 2488, in _workInIdle^@    raise self._read_content_exception[1]^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/manager
.py", line 2461, in _readContent^@    for line in content:^@  File "/root/.vim/plugged/LeaderF/autoload/leaderf/python/leaderf/asyncExecutor.py", line 105,
 in read^@    raise Exception(lfBytes2Str(err, encoding))^@Exception: /bin/sh: 1: rg: not found

**Comment by Yggdroot** [comment]
Please install rg first.

**Comment by weisiok365** [comment]
Thank you very much !.I am a newer.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
