### ISSUE TITLE
LeaderF starts with Error

### ISSUE THREAD

**Issue by 8taiiat8** [Yggdroot/LeaderF#986]
![grafik](https://user-images.githubusercontent.com/37664678/219496013-8c2974f8-90ec-45c3-aff9-1f5e9bbd1ba1.png)

- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 9.0
- Output of `:echo has("python")`: 1
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): libpython2.7.so.1.0
- Output of `:echo &pythonthreedll`(only vim, not neovim): libpython3.6m.so.1.0
- Output of `:py print(sys.version)`: 2.7.18 (default, Mar 04 2021, 23:25:57) [GCC]
- Output of `:py3 print(sys.version)`: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
- Output of `:echo g:Lf_Debug_Cmd`: pt --nocolor   -g="" "."
- Output of `:echo g:Lf_FilesFromCache`: 1
- 
- Operating system: 
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
nothing, only install with vim-plug:

Plug 'Yggdroot/LeaderF'

### Steps to reproduce
1. Install Leader F with vim-plug 
2. reload vim and open LeaderF with shortcut
-> Error Loger comes out

**Comment by Yggdroot** [comment]
Does `pt --nocolor -g="" "."` work in your command line?
There is something wrong with your `pt` command.
Or you can set `let g:Lf_DefaultExternalTool = "find"`.

**Comment by 8taiiat8** [comment]
Thanks for your Tipp and your quick Support!

The command works in my command line.

After setting the Parameter in .vimrc, LeaderF seems to work again

So Thank you :)

Yggdroot ***@***.***> schrieb am Fr. 17. Feb. 2023 um 02:35:
