### ISSUE TITLE
能否在leaderf rg的输出结果中，进一步过滤文件名

### ISSUE THREAD

**Issue by futurehome** [Yggdroot/LeaderF#989]
因为通过leader rg的关键字匹配有时候输出的内容很多，能否在leaderf rg的输出结果中，进一步过滤文件名呢？目前在input mode好像只能过滤文件内容；normal mode虽然能够搜索，但是不会过滤显示。

**Comment by Yggdroot** [comment]
加上`--match-path`

**Comment by futurehome** [comment]
有没有简单的方法，可以在rg的结果中，排除掉某种后缀的文件呢，比如log？

**Comment by Yggdroot** [comment]
> 有没有简单的方法，可以在rg的结果中，排除掉某种后缀的文件呢，比如log？

rg本身就有这个功能，比如：Leaderf rg xxx -g!*.log

**Comment by futurehome** [comment]
> > 有没有简单的方法，可以在rg的结果中，排除掉某种后缀的文件呢，比如log？
> 
> rg本身就有这个功能，比如：Leaderf rg xxx -g!*.log

是的，但是有时候rg的查找时间比较长，好容易找到结果，发现大量是log，退出当前结果，加option重新查找是个方式，如果能够在之前找到的结果里面，直接过滤掉比如log文件，那就更好了。

**Comment by Yggdroot** [comment]
> > > 有没有简单的方法，可以在rg的结果中，排除掉某种后缀的文件呢，比如log？
> > 
> > 
> > rg本身就有这个功能，比如：Leaderf rg xxx -g!*.log
> 
> 是的，但是有时候rg的查找时间比较长，好容易找到结果，发现大量是log，退出当前结果，加option重新查找是个方式，如果能够在之前找到的结果里面，直接过滤掉比如log文件，那就更好了。

目前还不支持反向过滤。

**Comment by futurehome** [comment]
> > > > 有没有简单的方法，可以在rg的结果中，排除掉某种后缀的文件呢，比如log？
> > > 
> > > 
> > > rg本身就有这个功能，比如：Leaderf rg xxx -g!*.log
> > 
> > 
> > 是的，但是有时候rg的查找时间比较长，好容易找到结果，发现大量是log，退出当前结果，加option重新查找是个方式，如果能够在之前找到的结果里面，直接过滤掉比如log文件，那就更好了。
> 
> 目前还不支持反向过滤。

期待。。。
