### ISSUE TITLE
can't show submodule files after updating LeaderF

### ISSUE THREAD

**Issue by skygragon** [Yggdroot/LeaderF#99]
I'm using Plug in vim, and it works perfectly when I search files in current project. But it can't search any files under its git submodule. Not sure if I miss anything in the configuration?

**Comment by Yggdroot** [comment]
By default, LeaderF use ` git ls-files && git ls-files --others --exclude-standard` if your repo is under control by git, this command can not list files under submodule.
You can `let g:Lf_DefaultExternalTool = "rg"`,  then LeaderF will use `rg --files` instead.
Also you can define a command by yourself, e.g., `let g:Lf_ExternalCommand = "cd %s && git ls-files --recurse-submodules"`. NOTE: `--recurse-submodules` is only available with Git 2.11+.

**Comment by skygragon** [comment]
@Yggdroot I tried add "let g:Lf_DefaultExternalTool = "rg"" to my .vimrc but it hanged and show "searching ..." in the status line. However if I close vim and run "rg --files" in the same directory, the output is print quickly. Not sure what am I missing here?

**Comment by Yggdroot** [comment]
Could you add the code `print(cmd)` below this line:
https://github.com/Yggdroot/LeaderF/blob/ddd1b8a967935fa18d276901fff28b7674f533c3/autoload/leaderf/python/leaderf/fileExpl.py#L465
to see the output after launching LeaderF.

**Comment by skygragon** [comment]
@Yggdroot changed as you suggested but nothing printout? 

![screen shot 2018-01-11 at 1 24 51 pm](https://user-images.githubusercontent.com/1295096/34809862-da4469e2-f6d2-11e7-85c3-bff7e5412893.png)

**Comment by Yggdroot** [comment]
晕。 
`g:Lf_ExternalCommand` and `g:Lf_DefaultExternalTool` are different. 
https://github.com/Yggdroot/LeaderF/blob/ddd1b8a967935fa18d276901fff28b7674f533c3/doc/leaderf.txt#L361-L369

https://github.com/Yggdroot/LeaderF/blob/ddd1b8a967935fa18d276901fff28b7674f533c3/doc/leaderf.txt#L382-L394

I suggested you to use `let g:Lf_DefaultExternalTool = "rg"`, but not `let g:Lf_ExternalCommand = "rg"`.

**Comment by skygragon** [comment]
It's weird that `let g:Lf_DefaultExternalTool = "rg"` still can't list submodule files, but `let g:Lf_ExternalCommand = 'rg --files "%s"'` works perfectly, thanks a lot~

**Comment by Yggdroot** [comment]
Sorry, you should also set `let g:Lf_UseVersionControlTool = 0` if set `let g:Lf_DefaultExternalTool = "rg"`. Because `git` takes precedence over `rg` if the repository is under control by git.

**Comment by skygragon** [comment]
@Yggdroot good to know, thanks again for your kindly help!
