### ISSUE TITLE
LeaderF mru 支持限定当前工作目录

### ISSUE THREAD

**Issue by vimerzhao** [Yggdroot/LeaderF#990]
关于这个Issue讨论的问题：https://github.com/Yggdroot/LeaderF/issues/933

我觉得还是很有必要的，比如我在两个独立工程编辑，mru 最好不要互相污染，但一个工程内能自由跳转最近文件（任意目录层级）。

目前看好像还不支持

**Comment by Yggdroot** [comment]
不太明白，能把需求描述的更具体一点吗？

**Comment by vimerzhao** [comment]
`g:Lf_RootMarkers` 范围下的 mru 搜索。当前只支持全局的 or 当前目录的。

**Comment by Yggdroot** [comment]
现在可以用`Leaderf mru --project`试一下。

**Comment by vimerzhao** [comment]
试了下，确实可以了
感谢
