### ISSUE TITLE
How to remap <C-J> keybinding?

### ISSUE THREAD

**Issue by forceofsystem** [Yggdroot/LeaderF#991]
- vim or neovim? 
    - [x] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: VIM - Vi IMproved 9.0
- Output of `:echo has("python")`: 0
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)]
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```viml
""" leaderf
" popup window
let g:Lf_WindowPosition = 'popup'
let g:Lf_PreviewInPopup = 1
let g:Lf_CommandMap = {'<C-L>': ['<Up>', '<C-K>'], '<C-K>': ['<Down>', '<C-J>']}
```
### Describe your question, feature request, or bug.
I want to use `<C-L>` and `<C-K>` to replace `<C-K>` and `<C-J>`, but it doesn't work.
### Steps to reproduce
You can just add the configuration:

`let g:Lf_CommandMap = {'<C-L>': ['<Up>', '<C-K>'], '<C-K>': ['<Down>', '<C-J>']}`.

Then you can enter command `:LeaderfFile`.

### Actual behaviour

I can use `<C-K>` like `<C-J>` and `<C-L>` like `<C-K>` to move up and down.

### Expected behaviour

Nothing happened.

**Comment by Yggdroot** [comment]
let g:Lf_CommandMap = {'<C-J>': ['<Up>', '<C-K>'], '<C-K>': ['<Down>', '<C-L>']}

**Comment by forceofsystem** [comment]
Thank you, it works well, I will close the issue.
