### ISSUE TITLE
leaderf still show deleted file in LeaderfFile result

### ISSUE THREAD

**Issue by jackywu** [Yggdroot/LeaderF#993]
vim or neovim? 
    - [ ] vim
    - [ ] neovim
    - [x] MacVim

- Output of `vim --version` or `nvim --version`: 

![Xnip2023-03-07_11-02-06](https://user-images.githubusercontent.com/587955/223309380-611633a7-437c-467c-b524-a4a1b7f6911d.png)

- Output of `:echo has("python")`:  0
- Output of `:echo has("python3")`:  1
- Output of `:echo &pythondll`(only vim, not neovim):  `/usr/local/Frameworks/Python.framework/Versions/2.7/Python`
- Output of `:echo &pythonthreedll`(only vim, not neovim): `/usr/local/Frameworks/Python.framework/Versions/3.10/Python`
- Output of `:py print(sys.version)`: no
- Output of `:py3 print(sys.version)`: `3.10.9 (main, Dec 15 2022, 18:25:35) [Clang 14.0.0 (clang-1400.0.29.202)]`
- Output of `:echo g:Lf_Debug_Cmd`: `git ls-files  "." && git ls-files --others --exclude-standard  "."`
- Output of `:echo g:Lf_FilesFromCache`:  0
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 
```vim
        " LeaderF {{{
            Plug 'Yggdroot/LeaderF', { 'do': ':LeaderfInstallCExtension' }
            ">>> use <F5> to refresh file cache,
            ">>> <https://github.com/Yggdroot/LeaderF/issues/161#issuecomment-391223847>
            let g:Lf_CacheDirectory = expand('$HOME/.vim')
            let g:Lf_PopupWidth = 0.85
            let g:Lf_PopupHeight = 0.75
            let g:Lf_RememberLastSearch = 0
            let g:Lf_PreviewResult = {'Rg': 0, 'BufTag': 1, 'Function': 1}
            let g:Lf_UseCache = 0 " not reindex files when reopen vim
            let g:Lf_UseMemoryCache = 0 " not use memory cache
            ">>> use python3
            let g:Lf_PythonVersion = 3
            let g:Lf_WindowPosition = 'popup'
            let g:Lf_PreviewInPopup = 1
            let g:Lf_ShowDevIcons=0
            ">>> key map
            let g:Lf_ShortcutF = '<C-p>'  " search file
            let g:Lf_ShortcutB = '<C-b>'  " search buffer
            command! -bar -nargs=* -complete=file LeaderfRg Leaderf rg <args>
            noremap <C-f> :LeaderfFile<Space>
            noremap <C-s> :LeaderfRg -e<Space>
            noremap <C-m> :LeaderfMru<CR>
            noremap <leader>fb :LeaderfBuffer<CR>
            noremap <leader>fm :LeaderfMru<CR>
            noremap <leader>ff :LeaderfFunction<CR>
            noremap <leader>fl :LeaderfLine<CR>
            noremap <leader>fr :LeaderfRgRecall<CR>
            noremap <leader>fg  <Plug>LeaderfRgCwordLiteralNoBoundary
            ">>> search
            let g:Lf_DefaultExternalTool = "rg"
            let g:Lf_ReverseOrder = 1
            let g:Lf_NoChdir = 1
            let g:Lf_Ctags = 'ctags'
            ">>> c-v trigger vertical split
            let g:Lf_CommandMap = {'<C-]>': ['<C-V>'], '<C-X>': ['<C-S>']}
            ">>> root marker
            let g:Lf_WorkingDirectoryMode = 'ac'
            let g:Lf_RootMarkers = ['.git', '.svn', 'Makefile']
        "}}}
        " GrepRg {{{
            ">>> set ripgrep to the external grep tool
            ">>> refer: https://www.wezm.net/technical/2016/09/ripgrep-with-vim/
            if executable("rg")
                set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
                set grepformat=%f:%l:%c:%m,%f:%l:%m
            else
                set grepprg="internal"
            endif
        " }}}
    " }}}

```
### Describe your question, feature request, or bug.
after delete file, leaderf will still search and hit the file . for example， the first file was deleted，but still appear at top of the result.
![Xnip2023-03-07_10-59-21](https://user-images.githubusercontent.com/587955/223310915-4222e869-b714-4afc-ab4b-48e429e49002.png)

**Comment by Yggdroot** [comment]
Because current command using is `git ls-files  "." && git ls-files --others --exclude-standard  "."`,  if you delete a file from a git repository, you should use `git rm`.

Anyway, you can set `let g:Lf_UseVersionControlTool = 0` to bypass the issue.

**Comment by jackywu** [comment]
thanks
