### ISSUE TITLE
Leaderf mru  not  find  recent file

### ISSUE THREAD

**Issue by ooing** [Yggdroot/LeaderF#995]
*  Open the file to write content and exit(:wq)
*  Open the file just now 
* :Leaderf mru     not  find the file

**Comment by Yggdroot** [comment]
can you show me in more detail how to reproduce?

**Comment by ooing** [comment]
*   open an existing file
``` bash
vim  hello.lua
```

* Write some content and then save to exit

* start  vim ,  then input   `:Leaderf mru`  not find    ` hello.lua`

**Comment by ooing** [comment]
can you see the video   https://www.bilibili.com/video/BV1Gv4y1771R/

**Comment by ooing** [comment]
I am sorry  , I use lazy load the plug
