### ISSUE TITLE
`Leaderf rg -e 'some' .` always return "No Content!"

### ISSUE THREAD

**Issue by jackywu** [Yggdroot/LeaderF#996]
- vim or neovim? 
    - [x ] vim
    - [ ] neovim
- Output of `vim --version` or `nvim --version`: `VIM - Vi IMproved 9.0 (2022 Jun 28, 编译于 Feb  7 2023 12:17:42)`
- Output of `:echo has("python")`: 
- Output of `:echo has("python3")`: 1
- Output of `:echo &pythondll`(only vim, not neovim): 
- Output of `:echo &pythonthreedll`(only vim, not neovim): 
- Output of `:py print(sys.version)`: 
- Output of `:py3 print(sys.version)`: 
- Output of `:echo g:Lf_Debug_Cmd`: 
- Output of `:echo g:Lf_FilesFromCache`: 
- Operating system: 
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Configurations related to LeaderF in vimrc: 

### Describe your question, feature request, or bug.

run `Leaderf rg -e 'some' .` always return "No Content!"
run `LeaderfRg -e 'some' .` always return "No Content!"

any suggestion to debug it  more particular further?

**Comment by Yggdroot** [comment]
Use `Leaderf rg -e some .` or `Leaderf rg -e "some" .` instead.
