### ISSUE TITLE
自定义书签在WIN下完全正常运行在Mac下卡死

### ISSUE THREAD

**Issue by gVimer** [Yggdroot/LeaderF#998]
用的是最新版本 自定义书签如下：
let g:BookMarks = [
            \ "【书◄►◄►◄►◄►签】 ~/Desktop/A.TXT",
            \ "【书◄►◄►◄►◄►签】 ~/Desktop/B.TXT",
\]

function! GetBmSource(Args)
    let T=[]
    for i in g:BookMarks
        let Path=expand(split(i," ")[1])
        if filereadable(Path) || isdirectory(Path)
            call add(T,i)
        endif
    endfor
    return T
endfunction

function! BookMarksACCEPT(LineData,Args)
    let Path=expand(split(a:LineData," ")[1])
    exec L('EDIT ').Path
endfunction

let g:Lf_Extensions = {
   \"BookMark": 
   \{
   \  "source"     : 'GetBmSource',
   \  "arguments"  : [{"name": [L("PATTERN")],"nargs": '*'}],
   \  "accept"     : "BookMarksACCEPT",
   \  "after_enter": "",
   \  "before_exit": "",
   \  "highlights_def": 
   \  {
   \    "Word1": '/\@<!\w\+\W\@=\.\@!',
   \  },
   \  "highlights_cmd": 
   \   [
   \     "highlight Word1 GUIFG=#0000FF",
   \   ],
   \  },}
代码无法缩进  我截个图吧 
![image](https://user-images.githubusercontent.com/6241431/226335466-1a045db2-a7aa-4139-a11b-be3e5ad4c700.png)
这里换成你电脑上文件的路径即可![image](https://user-images.githubusercontent.com/6241431/226335527-932cf2db-bb9b-4165-8497-b70d717927a6.png)

执行命令`Leaderf! BookMark` 的时候弹出界面 然后卡死了 任何按键都无效

**Comment by Yggdroot** [comment]
你提供的好像不是可运行的代码。

**Comment by gVimer** [comment]
不好意思 手机邮件APP关闭通知了现在才看见 上面可能是缩进问题 
`
let g:BookMarks = [
            \ "【书◄►◄►◄►◄►签】 ~/Desktop/A.TXT",
            \ "【书◄►◄►◄►◄►签】 ~/Desktop/B.TXT",
\]

function! GetBmSource(Args)
    let T=[]
    for i in g:BookMarks
        let Path=expand(split(i," ")[1])
        if filereadable(Path) || isdirectory(Path)
            call add(T,i)
        endif
    endfor
    return T
endfunction

function! BookMarksACCEPT(LineData,Args)
    let Path=expand(split(a:LineData," ")[1])
    exec L('EDIT ').Path
endfunction

let g:Lf_Extensions = {
   \"BookMark": 
   \{
   \  "source"     : 'GetBmSource',
   \  "arguments"  : [{"name": [L("PATTERN")],"nargs": '*'}],
   \  "accept"     : "BookMarksACCEPT",
   \  "after_enter": "",
   \  "before_exit": "",
   \  "highlights_def": 
   \  {
   \    "Word1": '/\@<!\w\+\W\@=\.\@!',
   \  },
   \  "highlights_cmd": 
   \   [
   \     "highlight Word1 GUIFG=#0000FF",
   \   ],
   \  },
   \}
`

代码好像不能识别 无法缩进 截个图吧 
![image](https://user-images.githubusercontent.com/6241431/226333611-92ba7135-3153-4f8f-b7d9-3b9568f759d4.png)
注意这里换成你MacOS上的文件路径即可
![image](https://user-images.githubusercontent.com/6241431/226333739-756eb4fa-f099-412e-bfba-198f8afe2e54.png)
然后执行命令 `Leaderf! BookMark`

**Comment by gVimer** [comment]
不好意思 手机APP关闭通知了 现在才看见  我重新编辑下

**Comment by Yggdroot** [comment]
E117: Unknown function: L

**Comment by Yggdroot** [comment]
你可以学一下markdown语法，看看怎么贴代码。

**Comment by gVimer** [comment]
> 你可以学一下markdown语法，看看怎么贴代码。

好的 这个其实一直有想学的 感觉用不到 就没动力去学了
这个忘了 因为这个函数是定义在另外一个文件的  我忘了
![image](https://user-images.githubusercontent.com/6241431/226506758-5f2a09e6-c4f7-448a-a9ee-02bd20f123e3.png)
麻烦你先改下 `exec "edit ".path`

**Comment by Yggdroot** [comment]
`"arguments" : [{"name": [L("PATTERN")],"nargs": '*'}],`
这里也用到了

**Comment by gVimer** [comment]
这个函数就是把大写变成小写 麻烦你再改下吧

**Comment by Yggdroot** [comment]
Mac下，没有复现。这么简单的功能感觉不至于。

**Comment by gVimer** [comment]
那就奇怪了 `Leaderf! BookMark`这个命令确定带`!`了吗 那我再看看吧 把所有不相关的都去掉 升级下MacVIM

**Comment by gVimer** [comment]
我的是执行`Leaderf! BookMark` 然后任何按键都无效
![image](https://user-images.githubusercontent.com/6241431/226511448-fa433860-825e-40d1-a48a-602cc99c8799.png)

**Comment by gVimer** [comment]
如果执行 `Leaderf BookMark` 即输入模式 可以正常输入并回车打开对应文件
![image](https://user-images.githubusercontent.com/6241431/226511617-56df59ec-bf93-4a80-a261-9823d94e197a.png)

**Comment by gVimer** [comment]
那我自己再看看吧 打扰了 有结果了再来
